### ISSUE TITLE
[New game]: Sudoku

### ISSUE THREAD

**Issue by nikim178** [kunjgit/GameZone#10]
### 🎮 Game Request

Game logic and basic description
This game is built using HTML, CSS, and vanilla JavaScript. It is a classic Sudoku Solver game that challenges players to solve Sudoku puzzles. The game provides a user-friendly interface where players can input numbers and the solver algorithm will generate the solution for them. It is designed to be beginner-friendly and suitable for those who are new to Sudoku.

### Point down the features

Game points
Puzzle Generator: The game generates random Sudoku puzzles of varying difficulty levels, ensuring a unique and challenging experience for each player.

User Input: Players can easily input numbers into the Sudoku grid using an intuitive interface. The input is validated to ensure that only valid numbers are entered.

Solver Algorithm: The game incorporates a powerful solver algorithm that analyzes the inputted Sudoku puzzle and generates the correct solution. This feature helps players learn and improve their Sudoku-solving skills.

Solution Check: Players can verify their solution by checking it against the solver algorithm's output. This provides instant feedback and helps players identify any mistakes or errors.

Score Tracking: The game includes a score tracker that keeps a record of the player's performance. It tracks the number of puzzles solved correctly, the time taken to solve each puzzle, and provides an overall rating based on the player's achievements.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by rahultomarr** [comment]
I'm here to contribute to the GSSOC'23.
Please assign me to do that.

**Comment by kunjgit** [comment]
Hey @nikim178  ! Thank you for raising an issue 💗 You have been assigned this issue you can start working on the issue 🎮

**Comment by nikim178** [comment]
Thank you @kunjgit !

**Comment by nikim178** [comment]
@kunjgit  Does it have a deadline to complete this task?

**Comment by kunjgit** [comment]
Hello @nikim178, Time's Uppp!⏰ 
 Sorry for closing your issue! 
 But it's more than a week since we haven't received anything from your side 😢 . 
 Come up with new ideas, create a new issue and make sure you finish it within a week! 🔥 
 All the best! 🚀 
 Happy Hacking! 💗

**Comment by kunjgit** [comment]
Hey @nikim178 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
