### ISSUE TITLE
[New game]: 1024 MOVES 👾

### ISSUE THREAD

**Issue by 0xabdulkhalid** [kunjgit/GameZone#1004]
### 🎮 Game Request

Game logic and basic description
- Great Sokoban Style game with some beautifully minimalist 3D graphics and animations.

### Point down the features

Game points
- This puzzle can be solved in 1024 movements.
- Very well designed puzzles and challenging.
- Definitely you gonna enjoy playing through all the stages on this one. 
- That is to say, I think it is not possible to do it in less than 1024 movements.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @0xabdulkhalid ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
