### ISSUE TITLE
[New game]: off the line

### ISSUE THREAD

**Issue by S-ishita** [kunjgit/GameZone#1008]
### 🎮 Game Request

Action! Danger! Coins! What more could you want from a game?! Jump off the line and try not to die or throw your keyboard across the room in this twitchy arcade tapper. Can you beat all 20 hand-crafted levels? It's harder than it sounds! Good luck and watch out for those walls!

### Point down the features

Game points will be awarded on basis of level clearance

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @S-ishita ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)
