### ISSUE TITLE
[New game]: Tetris

### ISSUE THREAD

**Issue by tayyab-ilyas** [kunjgit/GameZone#101]
### 🎮 Game Request

Tetris is a fun puzzle game where a player tries to arrange blocks to form gapless lines.

### Point down the features

Features:

1. A playfield that is divided into a grid of squares.

2. Falling blocks that need to be placed in a way to fill up rows.

3. A scoring system that rewards players for clearing rows.

4. A game over state when the playfield is filled up.

5. A variety of different block shapes: This adds a layer of strategy to the game, as players need to learn how to use the different shapes to create different patterns and clear rows.

6. A scoring system: This rewards players for clearing rows and completing special blocks.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by tayyab-ilyas** [comment]
hey @kunjgit ! can you assign this issue to me under GSSoc'23?

**Comment by kunjgit** [comment]
Hey @tayyab-ilyas ! we are already having the similar game request on #48 !! 
Thank you for raising an issue 💗
