### ISSUE TITLE
[Find the words]: 

### ISSUE THREAD

**Issue by samhitaveluri** [kunjgit/GameZone#1011]
### 🎮 Game Request

Game logic and basic description:
This is a simple word search puzzle generator / game made using JS and p5 library with 15 * 15 grid with 15 words in the puzzle with word length <= 7
![image](https://github.com/kunjgit/GameZone/assets/121224422/05378fe9-a372-4558-882f-1950c5d08b12)

### Point down the features

Game points:
1) Vertical / Diagonal / Horizontal Word placement
2) Random puzzle generation

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @samhitaveluri! 🙂 
 It seems like you are not following proper guidelines !! 👀 
 Read documentation properly !!🙏 
 If you have any queries reach out to us on [Discord🕹️](https://discord.gg/fgwk4XZfxG) .

**Comment by kunjgit** [comment]
Hey @samhitaveluri ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @samhitaveluri ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
