### ISSUE TITLE
[Oh, flip]: 

### ISSUE THREAD

**Issue by samhitaveluri** [kunjgit/GameZone#1016]
### 🎮 Game Request

Game logic and basic description:
it is a game built with html,css and javascript.This game is about backflips.
![image](https://github.com/kunjgit/GameZone/assets/121224422/40dce5c1-9a8a-460e-8016-3b702561ca7b)

### Point down the features

Game points:
Tap or Click to flip
Land upright to gain height
Complete goals to fill yourself with happiness.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @samhitaveluri ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)
