### ISSUE TITLE
[New game]: Snake Feeder Game [GSSoC'23]

### ISSUE THREAD

**Issue by Avdhesh-Varshney** [kunjgit/GameZone#1018]
### 🎮 Game Request

Game logic and basic description

- In this game, Players control a growing snake and guide it to eat food items while avoiding collisions with its own body and the game boundaries.
- The players are to accumulate points by consuming feeders, with the challenge increasing as the snake grows longer.

### Point down the features

Game points

- More food items consumption, more will be your score.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Avdhesh-Varshney ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)
