### ISSUE TITLE
Corona Fighter Game

### ISSUE THREAD

**Issue by Amitdahiya08** [kunjgit/GameZone#104]
### 🎮 Game Request

The game involves a player, enemies, and a gem that needs to be collected. The player's objective is to collect the gem while avoiding collisions with the enemies.

### Point down the features

Player Control: The game allows the player to control a character using mouse input. The character moves horizontally across the screen.

Enemies: There are multiple enemy objects that move vertically on the screen. The player needs to avoid colliding with these enemies.

Gem Collection: The game includes a gem object that the player needs to collect by reaching it without colliding with enemies. Collecting the gem signifies a win condition.

Health and Score: The player's health is represented by a health bar or score, which increases when the player moves and decreases upon colliding with enemies. The current health or score is displayed on the screen.

Game Over Condition: If the player's health drops below zero, it triggers a game over condition. The game ends, and an alert message is displayed.

Victory Condition: If the player successfully collects the gem without losing all health, it triggers a victory condition. An alert message is displayed to signify the win.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Amitdahiya08 ! Thank you for raising an issue 💗 You have been assigned this issue you can start working on the issue 🎮

**Comment by kunjgit** [comment]
Hello @Amitdahiya08, Time's Uppp!⏰ 
 Sorry for closing your issue! 
 But it's more than a week since we haven't received anything from your side 😢 . 
 Come up with new ideas, create a new issue and make sure you finish it within a week! 🔥 
 All the best! 🚀 
 Happy Hacking! 💗

**Comment by kunjgit** [comment]
Hey @Amitdahiya08 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
