### ISSUE TITLE
[New game]: Hunt your card

### ISSUE THREAD

**Issue by dhruvishavaghani** [kunjgit/GameZone#105]
### 🎮 Game Request

Hunt your card is a card game in which one card will be displayed known as a target card and a few cards will be shuffled randomly in such a way that the card's symbols are not displayed to the player. Then the player has to select a random card from the shuffled cards. If the chosen card is not the same as the target card, the rest cards will be displayed to the player which the player needs to remember. In the next turn, cards will be shuffled again and the player has to choose a random card again and the target card will remain the same. On selecting the right card player will get points and in the next turn, a new target card will be set.

### Point down the features

Functionalities of the game:
-This game has rounds as per the player's selection of the right card.
-The player's best score will always be stored and updated every time a player scores the highest score.
-Good animated card shuffling.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey  @dhruvishavaghani ! Thank you for raising an issue 💗 You have been assigned this issue you can start working on the issue 🎮

**Comment by kunjgit** [comment]
Hello @dhruvishavaghani, Time's Uppp!⏰ 
 Sorry for closing your issue! 
 But it's more than a week since we haven't received anything from your side 😢 . 
 Come up with new ideas, create a new issue and make sure you finish it within a week! 🔥 
 All the best! 🚀 
 Happy Hacking! 💗

**Comment by kunjgit** [comment]
Hey @dhruvishavaghani ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
