### ISSUE TITLE
[New game]: The_Music_Game

### ISSUE THREAD

**Issue by cleveranu** [kunjgit/GameZone#1052]
### 🎮 Game Request

Game logic and basic description
This will be a game made using HTML,CSS and Js where on clicking on Different instruments you can play music or by pressing keyboard key.

### Point down the features

Game points

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @cleveranu ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by cleveranu** [comment]
@kunjgit can you please assign me this issuse under GsSOC'23 label.

**Comment by cleveranu** [comment]
Please add GsSOC'23 label

**Comment by cleveranu** [comment]
@kunjgit

**Comment by kunjgit** [comment]
Hello @cleveranu, Time's Uppp!⏰ 
 Sorry for closing your issue! 
 But it's more than a week since we haven't received anything from your side 😢 . 
 Come up with new ideas, create a new issue and make sure you finish it within a week! 🔥 
 All the best! 🚀 
 Happy Hacking! 💗

**Comment by kunjgit** [comment]
Hey @cleveranu ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by cleveranu** [comment]
#1186 I contributed
