### ISSUE TITLE
[New game]: Space Invaders Game

### ISSUE THREAD

**Issue by PriyankaTamhankar01** [kunjgit/GameZone#1054]
### 🎮 Game Request

Initialize the game:
Set up the game screen with the player's spaceship at the bottom and a grid of alien invaders at the top.

Set the score to 0 and the number of lives to a predefined value.

Handle player input:
Listen for player input, typically left/right arrow keys for movement and spacebar for shooting.

Move the player's spaceship horizontally based on the input.

If the player presses the spacebar, create a bullet entity and launch it towards the aliens.

### Point down the features

Game points

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @PriyankaTamhankar01 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @PriyankaTamhankar01! 
We are already having a similar game request in #1050 👀 
Make sure you come up with a cool unique idea 😀 
 Waiting for your new game idea 💗.

**Comment by kunjgit** [comment]
Hey @PriyankaTamhankar01 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by PriyankaTamhankar01** [comment]
I was assign this issue in  #336 ..but due to time constraints I was not able to submit .what should I do ..?
