### ISSUE TITLE
[New game]: Guess the Number 

### ISSUE THREAD

**Issue by Sudhanshu-Sharma-22** [kunjgit/GameZone#106]
### 🎮 Game Request

Game logic and basic description:
Game Will be Simply Guess the Number Between a Given Range.
Logic Can Simply Be Applying Binary Search or Just Guessing.

### Point down the features

Game points:
It's Easy to Play.
Don't Require any Extra Knowledge.
Easy to Handle By any Web Browser.
Interactive With User/Player's.
Easy to Load on Low End Device's Since the Game isn't too Heavy.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by ZAPatil** [comment]
Hello I am GSSOC'23 contributor, Please assign me this task.

**Comment by Anjali07Patel** [comment]
I would like to work on this issue, please assign this issue to me under GSSoC'23.

**Comment by kunjgit** [comment]
Hey @Sudhanshu-Sharma-22 we are already having such requests #28 !!
Make sure you come up with some new ideas or you can do enhancement later on 💗

**Comment by kunjgit** [comment]
Hey @Sudhanshu-Sharma-22 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
