### ISSUE TITLE
[Enhancement]: adding a search bar 

### ISSUE THREAD

**Issue by mobtomc** [kunjgit/GameZone#107]
### Is your enhancement request related to a problem? Please describe.➕

adding a search bar to the website makes it much more convenient for the users to play their favourite games and saves them time.

### Describe the solution you'd like

Solution steps-
i will be making the search bar using html,css and javascript.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @mobtomc !! we are already having it in #116 !!

**Comment by kunjgit** [comment]
Hey @mobtomc ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
