### ISSUE TITLE
[New game]: DEAD AGAIN  👾

### ISSUE THREAD

**Issue by 0xabdulkhalid** [kunjgit/GameZone#1071]
### 🎮 Game Request

Game logic and basic description
- Death was not enough to keep these evil spirits down.
- Defend yourself against the onslaught of zombies, vampires, ghosts ... and more.
- The longer you play, the stronger they get.
- Survive for as long as you can, but it is only a matter of time before you are ... DEAD AGAIN

### Point down the features

Game points
- The art style is amazing, the gameplay is fluid and polished.
- the music fits nicely. 
- I also liked the line of sight mechanic, made the game more eerie, as you dont know whats around each corner.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @0xabdulkhalid ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @0xabdulkhalid ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
