### ISSUE TITLE
[New game]:  THE RAISING FIGHTING SPIRITS 👾

### ISSUE THREAD

**Issue by 0xabdulkhalid** [kunjgit/GameZone#1076]
### 🎮 Game Request

Game logic and basic description
- This game is a simple strategy card game where you fight against the Grim Reaper using a horde of spirits!
- Try to kill the Reaper faster to receive a better score!!! BUT watch out for the Reaper's next turn intended action!!!

### Point down the features

Game points
- You can stop/start the game sounds in the top right speaker icon.
-  Click/touch a soul to select it or use the buttons at the bottom right (next soul/previous soul) to navigate them.
- Look at the Reaper's next turn intention/action to create your strategy.
- Energy lets you know the amount of cards you can play per turn.
- Click and drag cards out/above your hand area to play them.
- End your turn and see the reaper action.
- During game events you can select one of the power up options.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @0xabdulkhalid ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @0xabdulkhalid ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
