### ISSUE TITLE
[New game]:  Connect4

### ISSUE THREAD

**Issue by SoarinSkySagar** [kunjgit/GameZone#1079]
### 🎮 Game Request

Game logic and basic description

The game board will be displayed, represented by a 6x7 grid.

Players will take turns choosing a column number to drop their disc into. The disc will occupy the lowest available slot in the chosen column.

The game will continue until one of the players achieves four discs of their color in a row or if the game board is completely filled with discs, resulting in a tie.

If a player wins, a message will be displayed announcing the winner. If the game ends in a tie, a tie message will be displayed.

### Point down the features

Game points

Interactive Gameplay: The game provides an interactive interface where players can take turns choosing a column to drop their discs into.

Win Condition: The game automatically detects when a player achieves four discs of their color in a row, declaring them as the winner of the game.

Tie Condition: If the game board is completely filled with discs and no player has achieved a win, the game ends in a tie.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @SoarinSkySagar ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @SoarinSkySagar ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
