### ISSUE TITLE
[New Game]: Moving Dice

### ISSUE THREAD

**Issue by SyedImtiyaz-1** [kunjgit/GameZone#108]
### 🎮 Game Request

 The **Moving Dice** game is a classic kids game that have sound of dice while shuffling and this is developed using HTML, **CSS, & JavaScript**.

The game starts with a single play button which make the game more clear and fun to the player because he/she going to direct step into the game, also have a count section to count the numbers of wins of the player in the correct order.

🎲🎲🎲🎲🎲🎲🎲🎲🎲🎲🎲🎲🎲🎲🎲🎲🎲🎲🎲🎲🎲🎲🎲🎲🎲🎲🎲🎲🎲🎲🎲🎲🎲🎲🎲🎲🎲🎲🎲🎲🎲🎲🎲🎲🎲🎲🎲🎲🎲🎲🎲🎲🎲🎲🎲🎲🎲

### Game points -
- Press the "Play" button to start the game.
- The game will randomly choose a dice **Number** in the form of **Dice-Dots** and will play a sound. Repeat the dice to earn more points.
- If there is something issue with the device then it will pop-up "Please refresh the page."
- Press the "Play" button again or continue the game.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @SyedImtiyaz-1 ! Thank you for raising an issue 💗 You have been assigned this issue you can start working on the issue 🎮

**Comment by SyedImtiyaz-1** [comment]
## Hello @kunjgit,
## You can check the PR, I'hv added Moving Dice game. #110

**Comment by kunjgit** [comment]
Hello @SyedImtiyaz-1, Time's Uppp!⏰ 
 Sorry for closing your issue! 
 But it's more than a week since we haven't received anything from your side 😢 . 
 Come up with new ideas, create a new issue and make sure you finish it within a week! 🔥 
 All the best! 🚀 
 Happy Hacking! 💗

**Comment by kunjgit** [comment]
Hey @SyedImtiyaz-1 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
