### ISSUE TITLE
[New game]: Chess game

### ISSUE THREAD

**Issue by SoarinSkySagar** [kunjgit/GameZone#1087]
### 🎮 Game Request

Game logic and basic description

A chess game, where two people can play with each other.

### Point down the features

Game points

Interactive game
The game keeps track of all player moves and then decides winner at the end
Responsive design

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @SoarinSkySagar ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by SoarinSkySagar** [comment]
@kunjgit please review and merge this PR under GSSoC'23 label

Issue: #1087 
PR: #1095

**Comment by kunjgit** [comment]
Hey @SoarinSkySagar ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
