### ISSUE TITLE
Rock ,Paper and Scissor 

### ISSUE THREAD

**Issue by Tusharjoshi1703** [kunjgit/GameZone#11]
### 🎮 Game Request

Creating three buttons of rock,paper and scissor and using two players in which one is user that clicks the button and another one is computer that generates random of the three buttons.
Using conditional statements,we will choose the winner and  can increase score of the winner and update the score respectively.

### Point down the features

Initially both the scores are 0.Whoever wins ,their score will get updated .

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by himanshu1781** [comment]
Hey @Tusharjoshi1703 it seems some intresting to me .here i will use my js skills can you please assign the issue to me.

**Comment by kunjgit** [comment]
Hey @Tusharjoshi1703  ! Thank you for raising an issue 💗 You have been assigned this issue you can start working on the issue 🎮

**Comment by Tusharjoshi1703** [comment]
Thank you for assigning it to me . I'll do my best and make sure you won't
get disappointed.

**Comment by kunjgit** [comment]
Hey @Tusharjoshi1703 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by Tusharjoshi1703** [comment]
Will I get points now
