### ISSUE TITLE
[New game]: space Invaders

### ISSUE THREAD

**Issue by Mannu292001** [kunjgit/GameZone#1108]
### 🎮 Game Request

Game logic and basic description
In Space Invaders, the player controls a small spaceship that moves horizontally at the bottom of the screen. The objective is to shoot and destroy waves of descending alien invaders while avoiding their projectiles and barriers. The aliens move left and right, gradually descending towards the player's spaceship. If the aliens reach the bottom of the screen or the player's spaceship is hit by an enemy projectile, the game ends.

### Point down the features

Game points
Player-Controlled Spaceship
Shooting Mechanism
Alien Invaders

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Mannu292001 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by Mannu292001** [comment]
Plz assign this to me under GSSOC'23

**Comment by kunjgit** [comment]
Hello @Mannu292001, Time's Uppp!⏰ 
 Sorry for closing your issue! 
 But it's more than a week since we haven't received anything from your side 😢 . 
 Come up with new ideas, create a new issue and make sure you finish it within a week! 🔥 
 All the best! 🚀 
 Happy Hacking! 💗

**Comment by kunjgit** [comment]
Hey @Mannu292001 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
