### ISSUE TITLE
[New game]: Drum kit

### ISSUE THREAD

**Issue by SagarPatil007** [kunjgit/GameZone#111]
### 🎮 Game Request

It is just simple drum playing game.
When we type key from {W,A,S,D,J,K,L} then different type of sound are produced. 

### Point down the features

Musical instrument game
No Hi-Fi logic is required to play

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by Sudhanshu-Sharma-22** [comment]
I would like to work on this issue under GSSOC 2023 . If you want you can assign me for this game 😁.

**Comment by kunjgit** [comment]
Hey @SagarPatil007 !! we are having similar game in #3 
Come up with some exciting game !! 💗

**Comment by kunjgit** [comment]
Hey @SagarPatil007 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
