### ISSUE TITLE
[New game]: Connect Four

### ISSUE THREAD

**Issue by Iron-Thunder** [kunjgit/GameZone#112]
### 🎮 Game Request

A two-player game where players take turns dropping colored discs into a grid and try to connect four of their discs in a row, column, or diagonal. The objective of the game is to be the first player to connect four of their own colored discs in a horizontal, vertical, or diagonal line.

### Point down the features

Game points
The game is played on a grid that consists of six rows and seven columns, resulting in a total of 42 slots. Players take turns dropping one of their colored discs into any of the columns. The disc will fall to the lowest available empty slot in the chosen column.

To win the game, a player must create a sequence of four of their discs in a row, either horizontally, vertically, or diagonally. The four discs can be connected in a straight line or in a combination of directions.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by Iron-Thunder** [comment]
I would like to work on this issue of making this game. So please assign me this issue.

**Comment by kunjgit** [comment]
Hey  @Iron-Thunder ! Thank you for raising an issue 💗 You have been assigned this issue you can start working on the issue 🎮

**Comment by kunjgit** [comment]
Hello @Iron-Thunder, Time's Uppp!⏰ 
 Sorry for closing your issue! 
 But it's more than a week since we haven't received anything from your side 😢 . 
 Come up with new ideas, create a new issue and make sure you finish it within a week! 🔥 
 All the best! 🚀 
 Happy Hacking! 💗

**Comment by kunjgit** [comment]
Hey @Iron-Thunder ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
