### ISSUE TITLE
[New game]: Memory Cards Game by Ajay-Dhangar 

### ISSUE THREAD

**Issue by Ajay-Dhangar** [kunjgit/GameZone#1123]
### 🎮 Game Request

**Game Name:** Memory Cards Game

**Game logic and basic description:**

The Memory Cards Game is a fun and challenging online game that tests your memory and cognitive skills. The objective of the game is to match pairs of cards with identical symbols or images within a limited time frame. The game board consists of a grid of facedown cards, and the player needs to flip them over to reveal the hidden symbols. By remembering the positions of the cards and making strategic flips, players can gradually uncover and match all the pairs to complete the game.

Deploy Link: [Memory Cards Game](https://ajay-dhangar.github.io/Memory-Cards-Game-0.1/)

Demo:
![image](https://github.com/kunjgit/GameZone/assets/99037494/8f7738ff-3fc7-4c53-a73d-69b695d39c77)

### Point down the features

**Game points:**

- Matching Pairs
- Mistakes Penalty

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Ajay-Dhangar ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by Ajay-Dhangar** [comment]
**Guess The Number:** https://javascript-mastery.github.io/Javascript-coding-assignment/projects/dom-1/index.html

Similar to this.

**Comment by Ajay-Dhangar** [comment]
> Hey @Ajay-Dhangar ! Thank you for raising an issue 💗 You can self assign the issue by commenting /assign in comment 😀 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone) Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @Ajay-Dhangar ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by kunjgit** [comment]
Hey @Ajay-Dhangar ! , This issue is already assigned to @Ajay-Dhangar. 💗 
 You can work on other issues 🚀 
 If there is anything wrong you can contact us on [Discord🕹️](https://discord.gg/fgwk4XZfxG)👀

**Comment by Ajay-Dhangar** [comment]
I have complited my task: [PR](https://github.com/kunjgit/GameZone/pull/1237)

**Comment by kunjgit** [comment]
Hello @Ajay-Dhangar, Time's Uppp!⏰ 
 Sorry for closing your issue! 
 But it's more than a week since we haven't received anything from your side 😢 . 
 Come up with new ideas, create a new issue and make sure you finish it within a week! 🔥 
 All the best! 🚀 
 Happy Hacking! 💗

**Comment by kunjgit** [comment]
Hey @Ajay-Dhangar ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
