### ISSUE TITLE
[New game]: humming hums

### ISSUE THREAD

**Issue by S-ishita** [kunjgit/GameZone#1126]
### 🎮 Game Request

Play Roger the hummingbird in his quest for delicious nectar!

Roger is a very hungry hummingbird. He needs nectar, pronto.

Space bar: flap Roger's tiny wings. You will press this many many times

Arrow keys: move Roger

### Point down the features

- Roger needs to sip from the center of the flower. His tongue will flick out when he can feed

- Roger grows heavier the more he feeds

- Roger needs more energy to flap the higher he is

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @S-ishita ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @S-ishita ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
