### ISSUE TITLE
[New game]: trivia quiz game

### ISSUE THREAD

**Issue by Iron-Thunder** [kunjgit/GameZone#113]
### 🎮 Game Request

The trivia quiz game is a basic implementation that focuses on the core functionality of presenting questions, accepting player input, checking answers, and tracking scores. It has more features such as a timer, difficulty levels, lifelines, or even incorporating a leaderboard for multiplayer functionality.

### Point down the features

Game points
The game displays each question along with a set of options for the player to choose from. The game prompts the current player to enter their answer by selecting the corresponding number of their choice. The game checks if the player's answer matches the correct answer stored in the question dictionary.  The game keeps track of the player's score throughout the quiz. For each correct answer, the player's score is incremented by 1. At the end of the quiz, the player's score is displayed. The game checks if the player's answer is correct after each question and provides immediate feedback.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by Iron-Thunder** [comment]
I want to work on this issue of making this game. So please assign me this issue.

**Comment by kunjgit** [comment]
Hey @Iron-Thunder ! we are already having similar game request in #120

**Comment by kunjgit** [comment]
Hey @Iron-Thunder ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
