### ISSUE TITLE
[New game]: Wordle

### ISSUE THREAD

**Issue by ritik48** [kunjgit/GameZone#1137]
### 🎮 Game Request

Game logic and basic description

#### Wordle is a word game.
Here user will be displayed blank boxes, and will have to guess the word.
With each guesses the user will be given a hint like:

- if the letter in the guess exists in the original word but is at wrong position, then it's color will change to yellow.

- if the letter in the guess exists in the original word and is at a right position, then it's color will change to green.

### Point down the features

Game points

#### Features: 
- flexibility in selecting word length
- easy, medium and tough category options
-there will be fixed number of guesses. and based on in how many guess user figured out the word, score will be given.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @ritik48 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @ritik48! 
We are already having a similar game request in #1111 👀 
Make sure you come up with a cool unique idea 😀 
 Waiting for your new game idea 💗.

**Comment by kunjgit** [comment]
Hey @ritik48 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
