### ISSUE TITLE
[New game]: Rock Paper Scissors Game

### ISSUE THREAD

**Issue by Saurabhrajput1234** [kunjgit/GameZone#114]
### 🎮 Game Request

The  Pock Paper Scissors Game is a classic popular game that have fun between peoples and this is developed using HTML, CSS, & JavaScript.

The game starts with a single play button which make the game more clear and fun to the player because he/she going to direct step into the game, also have a count section to count the numbers of wins of the player in the correct order.

### Point down the features

1.Game   start with pointsPress the "Play" button to start the game.
2.The game will randomly choose a hand position in the form of specific position and will play a sound. Repeat  to earn more points.
3.If there is something issue with the device then it will pop-up "Please refresh the page."
Press the "Play" button again or continue the game.

### Select program in which you are contributing

GSSoc23

### Code of Conduct

- [yes] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by Saurabhrajput1234** [comment]
please, assign me  this issue to develop this game

**Comment by Saurabhrajput1234** [comment]
please ,assign me tis issue(GSSoC23

**Comment by kunjgit** [comment]
Hey @Saurabhrajput1234 !! We are already having similar game request before in #11 !!

**Comment by kunjgit** [comment]
Hey @Saurabhrajput1234 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by Saurabhrajput1234** [comment]
ok sir,thanks
