### ISSUE TITLE
[New game]: PLAYBACK 👾

### ISSUE THREAD

**Issue by 0xabdulkhalid** [kunjgit/GameZone#1147]
### 🎮 Game Request

Game logic and basic description
- Oh no, you've been kicked out of the castle! Solve puzzles and make your way back to your rightful home.
- Puzzle-platformer game with an audio mechanic. Robots and platforms will only respond to sounds from tapes of the same color. 
- Platforms with dark arrows on them will remember their position after saving, so you don't need to worry about losing too much progress if you die. 

### Point down the features

Game points

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @0xabdulkhalid ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)
