### ISSUE TITLE
[New game]:  Create Doraemon Jump

### ISSUE THREAD

**Issue by amelia2802** [kunjgit/GameZone#115]
### 🎮 Game Request

Game logic and basic description
Jump from cloud to cloud to ascend higher and higher. Collect power-ups like bamboocopter, doracakes, and anywhere door to help you reach new heights.

### Point down the features

Game points
- Avoid obstacles like Rats and Gians, which will knock you down if you make contact.
- Rack up points and try to beat your high score!

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by amelia2802** [comment]
Hi @kunjgit, please assign this to me as a GSSOC contibutor.

**Comment by kunjgit** [comment]
Hey  @amelia2802 ! Thank you for raising an issue 💗 You have been assigned this issue you can start working on the issue 🎮

**Comment by kunjgit** [comment]
Hey @amelia2802 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
