### ISSUE TITLE
[Enhancement]: Wordle

### ISSUE THREAD

**Issue by ritik48** [kunjgit/GameZone#1155]
### Is your enhancement request related to a problem? Please describe.➕

Game enhancement

There are some more functionalities that can be added to the Wordle game to make it even more interesting , and I would like to implement them.
#### Functionalities like:

- Accept keyboard inputs too not just using buttons provided on website
- Show popups when there is a win or loss with high scores.
- Give option to choose how many letter word user want to play with. and based on that number of tiles will increase or decrease.
- give scores depending on in how many trials word was guessed.

### Describe the solution you'd like

Solution steps

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @ritik48 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @ritik48 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
