### ISSUE TITLE
add search button for finding games [Enhancement]: 

### ISSUE THREAD

**Issue by gaur15** [kunjgit/GameZone#116]
### Is your enhancement request related to a problem? Please describe.➕

Game enhancement if more games are added then adding of search button is important so that user can find game easily

### Describe the solution you'd like

Solution steps 
search button  addition by making changes in html and after that styling with CSS

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by Saurabhrajput1234** [comment]
hii ,sir I can do work on this issue .please assign me this to develop search bar .(GSSoC23)
thanks you

**Comment by kunjgit** [comment]
Hey @gaur15  ! Thank you for raising an issue 💗 You have been assigned this issue you can start working on the issue 🎮

**Comment by kunjgit** [comment]
Hello @gaur15, Time's Uppp!⏰ 
 Sorry for closing your issue! 
 But it's more than a week since we haven't received anything from your side 😢 . 
 Come up with new ideas, create a new issue and make sure you finish it within a week! 🔥 
 All the best! 🚀 
 Happy Hacking! 💗

**Comment by kunjgit** [comment]
Hey @gaur15 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
