### ISSUE TITLE
[New game]: brave adventure

### ISSUE THREAD

**Issue by S-ishita** [kunjgit/GameZone#1166]
### 🎮 Game Request

You are on your Epic Quest to find the dangerous beast that is hiding in the forest.

### Point down the features

--- Game mechanics ---
Control your hero by using actions on actionbar.
Each time you use an action, a new one will be randomly choosen.
If there is couple of the same actions next to each other, all will be used at the same time.
Each action cost you 1 turn. Turn couter display just above action bar. After you use your all turns, enemy turn begin.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @S-ishita ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)
