### ISSUE TITLE
[New game]: Guess My Number!

### ISSUE THREAD

**Issue by midhun-developer** [kunjgit/GameZone#117]
### 🎮 Game Request

Guess My Number Game will generate random number between 1 - 20 and the user needs to find the generated number by guessing it where they will be displayed with guessed number is high or low.

<img width="1465" alt="Guess My Number" src="https://github.com/kunjgit/GameZone/assets/82802499/8baf4525-5331-45f1-8eef-e777cebb4d50">

### Point down the features

- Game interacts with user by guessing number in between range 1 - 20
- Upon Guessing correct number the background color changes indicating success to user

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by midhun-developer** [comment]
Hi @kunjgit , please assign this to me as a GSSOC contibutor.

**Comment by kunjgit** [comment]
Hey @midhun-developer ! it seems really interesting but we are already having similar game request in #28 !!
Thank you 💗 !!

**Comment by kunjgit** [comment]
Hey @midhun-developer ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
