### ISSUE TITLE
[New game]: breakaway

### ISSUE THREAD

**Issue by S-ishita** [kunjgit/GameZone#1170]
### 🎮 Game Request

Breakaway is a platform/puzzle game.

Bubu while doing the poo unfortunately finds himself on a strange planet,
and now he need your help to escape from here!

### Point down the features

CONTROLS:
ARROWS: move Bubu
H: show/hide menu
R: restart current level (if you stuck)
P: enter a level password

TIPS:
Jump on enemy to kill him, collect keys to open the door.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @S-ishita ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)
