### ISSUE TITLE
[New game]: geometriko

### ISSUE THREAD

**Issue by S-ishita** [kunjgit/GameZone#1178]
### 🎮 Game Request

GEOMETRIKO is a twisted mix of Tic–tac–toe and Reversi, featuring three single player modes and a two–player hotseat mode.

How to play:
GEOMETRIKO is a turn–based game played on a 4x4 grid, and features four different tiles, aka Tiers, arranged in ascending order.
Each player starts with an infinite number of Tier–1 tiles.
Every time a player makes a three–of–a–kind he performs a Trip on the board; once a Trip is made it is removed from the board and the player is awarded an upgraded Tier.
Making a four–of–a–kind, a Quad, gives the player two upgraded Tiers.
If a higher Tier is put next to a lesser one, the lesser one switches side.

### Point down the features

Victory conditions:
A player can win a match either by filling the entire board with more of his own tiles than his opponent’s, or by achieving a Trip/Quad of Tier–4 tiles.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @S-ishita ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @S-ishita ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
