### ISSUE TITLE
[New game]: Kazuki Escape

### ISSUE THREAD

**Issue by S-ishita** [kunjgit/GameZone#1182]
### 🎮 Game Request

On a summer night , after five years in prison for an uncommitted murder, Kazuki finnaly found a way to escape and return to his family. However, when he reached the courtyard he heard the alarm going off! Help Kazuki fight his way through security and stay out of the lights!

### Point down the features

Features
========

- 4 different mobs
- 4 types of bosses with unique names
- the mobs are getting stronger with the level increase
- effects ( blood )
- the character's stats are getting better with the level increase

Controls
========

- WASD to move
- Mouse to look around
- Left click to kill

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @S-ishita ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @S-ishita ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
