### ISSUE TITLE
[New game]: Guess the name

### ISSUE THREAD

**Issue by shineishukla** [kunjgit/GameZone#1185]
### 🎮 Game Request

Prepare a collection of pictures and their corresponding correct answers.
Randomly select a picture from the collection.
Display the picture to the player.
Provide an input field or text box where the player can enter their guess.
Listen for the player's guess submission.
Compare the player's guess with the correct answer.
If the guess is correct, congratulate the player and move to the next picture.
If the guess is incorrect, the player can change the image.

### Point down the features

- Time limit to answer the guess
- Feature to change the picture
- LeaderBoard

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @shineishukla ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @shineishukla! 
We are already having a similar game request in #1123 👀 
Make sure you come up with a cool unique idea 😀 
 Waiting for your new game idea 💗.

**Comment by kunjgit** [comment]
Hey @shineishukla ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
