### ISSUE TITLE
[New game]: "Whack-a-Mole

### ISSUE THREAD

**Issue by prachisingh1008** [kunjgit/GameZone#1187]
### 🎮 Game Request

Game logic and basic description
Whack-a-Mole is a game where players have to click on randomly appearing moles to score points. The game lasts for a set time, and players aim to achieve the highest score possible within that time. Beware, as the moles pop up and disappear quickly, testing your reflexes and speed.

### Point down the features

Game points
Randomized Mole Pop-up: Moles will appear randomly in different holes, challenging the player's reaction time and agility.
Scoring System: Each successful whack on a mole will earn the player points, increasing their score and adding to the excitement.
Time Limit: The game will have a predefined time limit, adding a sense of urgency and encouraging players to achieve the highest score within that timeframe.
![Screenshot (245)](https://github.com/kunjgit/GameZone/assets/89354933/b53066d5-4320-4f0b-8d3c-fe6d43be8952)

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @prachisingh1008 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hello @prachisingh1008, Time's Uppp!⏰ 
 Sorry for closing your issue! 
 But it's more than a week since we haven't received anything from your side 😢 . 
 Come up with new ideas, create a new issue and make sure you finish it within a week! 🔥 
 All the best! 🚀 
 Happy Hacking! 💗

**Comment by kunjgit** [comment]
Hey @prachisingh1008 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
