### ISSUE TITLE
[Documentation Bug]: Updating Contributing Guidelines

### ISSUE THREAD

**Issue by rajatnai49** [kunjgit/GameZone#119]
### Describe the bug ✍️

Adding a special note for GSSoC contributors, so they can follow the Contributing rules effectively and another for they want to work on the issue or not!

### Checklist

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.
- [x] I am willing to work on this issue (optional)
- [x] I am a GSSoC'23 contributor

### Provide step by step information reproduce the bug 📄

Update YAML files in "ISSUE_TEMPLATE" folder

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @rajatnai49 !! 
We would not be able to do that as we have automated the things now and making change in issue templates will lead to few issues !!
Thank you !!

**Comment by kunjgit** [comment]
Hey @rajatnai49 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
