### ISSUE TITLE
[Every game should have a footer(Plateform Name not provided)]: 

### ISSUE THREAD

**Issue by shuddhi-jain** [kunjgit/GameZone#1191]
### Is your enhancement request related to a problem? Please describe.➕

By adding a footer to every game present it will be known that this game belongs to the current web page provider and there are some more advancements which should be done to fitting every game to the fixed window size whether scrolled down 
![Screenshot (50)](https://github.com/kunjgit/GameZone/assets/92723741/7423b98f-58cc-4380-a40b-cba02b83203f)

### Describe the solution you'd like

Solution steps

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @shuddhi-jain! 🙂 
 It seems like you are not following proper guidelines !! 👀 
 Read documentation properly !!🙏 
 If you have any queries reach out to us on [Discord🕹️](https://discord.gg/fgwk4XZfxG) .

**Comment by kunjgit** [comment]
Hey @shuddhi-jain ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @shuddhi-jain ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by shuddhi-jain** [comment]
Okay Thankyou @kunjgit
