### ISSUE TITLE
[New game]:  Sky_High_Jumper Game

### ISSUE THREAD

**Issue by singhshivanii** [kunjgit/GameZone#1192]
### 🎮 Game Request

The Doodle Jump game is a simple vertical platform game where the player controls a character called the "doodler" who jumps on platforms to go higher and earn points. The game ends if the doodler falls off the screen.

Here's a brief overview of the game logic:
1>The player controls a character called the "doodler," who is constantly jumping on platforms.
2>The goal is to climb as high as possible without falling off the screen.
3>The doodler can move left and right by tapping or clicking on the screen.
4>The platforms are randomly generated and move down the screen at a constant speed.
5>The doodler needs to jump from one platform to another to avoid falling.
6>Colliding with a platform allows the doodler to jump again.
7>The game ends if the doodler falls off the screen.

 **key features of the Doodle Jump game are:**

Endless vertical jumping gameplay
Platforms for the Doodler to land on
Tilt and tap controls for movement
Power-ups for temporary advantages
Collectibles to enhance gameplay
High score tracking for competition
Gradually increasing difficulty

### Point down the features

 **key features of the Doodle Jump game are:**

Endless vertical jumping gameplay
Platforms for the Doodler to land on
Tilt and tap controls for movement
Power-ups for temporary advantages
Collectibles to enhance gameplay
High score tracking for competition
Gradually increasing difficulty

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @singhshivanii ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @singhshivanii ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
