### ISSUE TITLE
[Bug]: Master_Typing game screenshot not showing

### ISSUE THREAD

**Issue by sagnik3788** [kunjgit/GameZone#12]
### Give a brief about the bug ✍️

The bug i am  encountering is that the screenshots are not displaying in the readme file of the Master_Typing game. This means that when users view the readme file, they are unable to see the screenshots that are intended to showcase the game.

### What is the expected behavior? 🤔

When users access the readme file, they should be able to see the screenshots without any issues. The screenshots should be clear, properly formatted, and correctly embedded in the readme file. This allows users to get a visual understanding of the game and its visuals, enhancing their comprehension and interest in the project.

### Provide step by step information reproduce the bug 📄

1.Clone the repository: Start by cloning the repository containing the Master_Typing game to your local development environment.

2.Navigate to the readme file: Locate the readme file in the repository directory. It is typically named "README.md" or similar.

3.Review screenshot references: Open the readme file and examine the sections where the screenshots are referenced or embedded. Look for any image markup syntax (e.g., Markdown or HTML) used to display the screenshots.

4.Verify screenshot files: Check that the actual screenshot files exist in the specified location and have the correct file names and extensions. Ensure that the screenshots are in a compatible file format, such as PNG or JPEG.

5.Confirm file paths: Double-check the file paths specified in the readme file for the screenshots. Ensure that the paths accurately reflect the location of the screenshot files within the repository structure.

6.Test image display: Open the readme file using a markdown viewer or render the file in a web browser. Verify if the screenshots are visible and properly displayed. If not, take note of any error messages or broken image icons that might indicate an issue.

7.Debugging steps: If the screenshots are not showing, try the following debugging steps:

By following these steps i  can systematically investigate and identify the cause of the bug where the screenshots are not displaying in the readme file of the Master_Typing game. 
 
I want to work on this issue in GSSoC. Pease assign me.

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @sagnik3788  ! Thank you for raising an issue 💗
I have fixed that already but it was not merged 😃 !!
Still, Thank you for pointing out 🙇‍♂️ 
But we can't have this as an issue !!

**Comment by sagnik3788** [comment]
Ok sir
