### ISSUE TITLE
[New game]: Trivia it !

### ISSUE THREAD

**Issue by harshita-kaushik2** [kunjgit/GameZone#120]
### Game logic and basic description:
This is a Trivia game that tests your knowledge on American RomComs and Shows like Game of Thrones using fun question. 
Also, hints are provided to help them guess it.

### Game features :
1. A countdown clock
2. A tracker for points
3. Correct answer displayed in case of incorrect answer chosen or time-run-out.

**Hence, I request you to assign this issue to me as GSSoC 2023 Contributor. Thank You :)**

### Select program in which you are contributing

GSSoC 2023

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @harshita-kaushik2  ! Thank you for raising an issue 💗 You have been assigned this issue you can start working on the issue 🎮

**Comment by kunjgit** [comment]
Hey @harshita-kaushik2 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
