### ISSUE TITLE
[New game]: Wall Crosser

### ISSUE THREAD

**Issue by Durgesh4993** [kunjgit/GameZone#121]
### 🎮 Game Request

Their are ball need to be cross thee balls they have multiple levels the designe of a game is 
![image](https://github.com/kunjgit/GameZone/assets/98798977/e05d3845-b81d-4351-960b-e7fb155c9c85)

### Point down the features

They have infinite number of levels

### Select program in which you are contributing

GSSoC'23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Durgesh4993  ! Thank you for raising an issue 💗 You have been assigned this issue you can start working on the issue 🎮

**Comment by Durgesh4993** [comment]
Thank You @kunjgit

**Comment by Durgesh4993** [comment]
Sir issue #122 is also my please check it out also

**Comment by kunjgit** [comment]
Hello @Durgesh4993, Time's Uppp!⏰ 
 Sorry for closing your issue! 
 But it's more than a week since we haven't received anything from your side 😢 . 
 Come up with new ideas, create a new issue and make sure you finish it within a week! 🔥 
 All the best! 🚀 
 Happy Hacking! 💗

**Comment by kunjgit** [comment]
Hey @Durgesh4993 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
