### ISSUE TITLE
[New game]: Life of blobb

### ISSUE THREAD

**Issue by S-ishita** [kunjgit/GameZone#1212]
### 🎮 Game Request

It's hard being a blob -- there is always a bigger blob who may consume you. Even if you outgrow everyone, this doesn't mean that you will succeed - you need to be quick and fit to get through life. And in the end, it all depends on luck, doesn't it?

### Point down the features

Walls kill you instantly, so go through the gap

Score points by growing and shrinking Blobb

Finish levels faster to earn bonus points

Move with arrow keys or ASDW.

Show the high scores with Esc / P

Show this info screen with I.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @S-ishita ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @S-ishita ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
