### ISSUE TITLE
[New game]: Lightless

### ISSUE THREAD

**Issue by S-ishita** [kunjgit/GameZone#1214]
### 🎮 Game Request

It`s a adventure with a man, who woke up in the dark cave, where are no fire, no lights. You should to try find out and save his live. You can read his thoughts and control him. He could hold in his memory a way, where he was a few seconds ago, but not more...Try to find out!

### Point down the features

Through the adventure: you can see his thoughts; items, that he will find;changing depth information, when he will fall down or climb up; some special places that he will find; bad news\...I hope You won`t see it 

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @S-ishita ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)
