### ISSUE TITLE
[New game]: luck casino

### ISSUE THREAD

**Issue by S-ishita** [kunjgit/GameZone#1217]
### 🎮 Game Request

		Here's the quick rundown.  You are the new owner of this dump of a casino.  You need to keep the casino from bankruptcy!
		To do this you can place various games on the casino floor.  You can also rig these games in order to let customers win just enough to keep them
		happy and your coffers full.

### Point down the features

Game points will be awarded on basis of least bankruptcy!

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @S-ishita ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)
