### ISSUE TITLE
[New game]: Ninja-Run

### ISSUE THREAD

**Issue by Durgesh4993** [kunjgit/GameZone#122]
### 🎮 Game Request

The gameplay is simple and is very much interesting. All you have to do is the control your and make a jump over the blocks and collect the coins. The player has to run over the bombs so that they won’t hit you. Here you have to make your Ninja jump and try to avoid the coming threats. The control key is your mouse. When you keep progressing the game, the game speed will generally increase at a greater rate.

### Point down the features

Collect coin and creat an High score

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by Durgesh4993** [comment]
Demo link https://durgesh4993.github.io/Ninja-Run/

**Comment by kunjgit** [comment]
Hey @Durgesh4993  ! Thank you for raising an issue 💗 You have been assigned this issue you can start working on the issue 🎮

**Comment by Durgesh4993** [comment]
ok Sir

**Comment by kunjgit** [comment]
Hello @Durgesh4993, Time's Uppp!⏰ 
 Sorry for closing your issue! 
 But it's more than a week since we haven't received anything from your side 😢 . 
 Come up with new ideas, create a new issue and make sure you finish it within a week! 🔥 
 All the best! 🚀 
 Happy Hacking! 💗

**Comment by kunjgit** [comment]
Hey @Durgesh4993 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
