### ISSUE TITLE
[New game]: Atari breakout

### ISSUE THREAD

**Issue by singh-anushka** [kunjgit/GameZone#123]
### 🎮 Game Request

Game logic and basic description
A single-player game where one needs to smash the bricks using a paddle and a ball. The player will have full control over the paddle in the horizontal direction. You need to smash all the bricks before all your life runs out, which happens when the ball hits the ground.

### Point down the features

Game points
As the bricks are smashed the points are scored. Once all the bricks are smashed. Player wins.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @singh-anushka  ! Thank you for raising an issue 💗 You have been assigned this issue you can start working on the issue 🎮

**Comment by singh-anushka** [comment]
Hey @kunjgit can you look into [#53 ](https://github.com/kunjgit/GameZone/issues/53), [#49](https://github.com/kunjgit/GameZone/issues/49) and [#56](https://github.com/kunjgit/GameZone/issues/56) and remove the pending label from the same too. So that I can start working on them too.

**Comment by kunjgit** [comment]
Hey @singh-anushka ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
