### ISSUE TITLE
[New Game] : Whack-a-Mole 👾 

### ISSUE THREAD

**Issue by Abhinavcode13** [kunjgit/GameZone#124]
### 🎮 Game Request

Objective: The player has to whack as many moles as possible within a given time limit.

Game Elements:

1) Game board: Create a grid of holes where the moles will randomly appear.
2) Moles: Display mole images in random holes, and the player needs to click or tap on them to "whack" them.
3) Score: Keep track of the player's score, incrementing it each time a mole is successfully whacked.
4) Timer: Set a countdown timer for the game. When the time runs out, the game ends.
5) Start button: Provide a button to start or restart the game.

Implementation Steps:

1) Set up the HTML structure: Create a game board with a grid of holes using HTML elements (e.g., <div>).
2) Style the game board and holes using CSS and Bootstrap to make it visually appealing.
3) Use JavaScript to randomly select holes and display mole images in them. Attach event listeners to the mole images to detect when the player whacks them.
4) Implement the scoring mechanism: Increment the score each time the player successfully whacks a mole.
Create a timer using JavaScript. When the game starts, start the timer and display the remaining time on the screen. When the time runs out, end the game.
5) Add a start button that initializes the game. When clicked, it should reset the score, timer, and any other game variables, and start the game.
6) Display the score and remaining time on the screen, updating them dynamically as the player interacts with the game.
Provide visual feedback when the player successfully whacks a mole, such as changing the mole's image or applying animation effects.
7) Add game over conditions: When the time runs out, display the final score and a game over message. Allow the player to start a new game by clicking the start button.
8) Test the game thoroughly to ensure all functionalities work as expected.

### Point down the features

When the player clicks on a mole, the whackMole function is triggered, incrementing the score variable and updating the score display by +1.

Their is no negative point in missing the whackMole.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by Abhinavcode13** [comment]
please kindly assign this issue to @kunjgit !

**Comment by kunjgit** [comment]
Hey @Abhinavcode13  ! Thank you for raising an issue 💗 You have been assigned this issue you can start working on the issue 🎮

**Comment by kunjgit** [comment]
Hey @Abhinavcode13 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
