### ISSUE TITLE
[Enhancement]: Remove the number given to game in home page

### ISSUE THREAD

**Issue by rajatnai49** [kunjgit/GameZone#125]
### Is your enhancement request related to a problem? Please describe.➕

By removing we can ensuring that there are no two games with same number, so no two pr contradict with each other...

### Describe the solution you'd like

Update main index.html file!!

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by Omkarkale59** [comment]
Hi! I would like to contribute to this issue under the GSSoC'23. It seems interesting and aligned with my skills. I would be happy to take it up and work on this project. plz assigned me .

**Comment by kunjgit** [comment]
Hey @rajatnai49 ! We will be making changes in index ourself so there will not be any such conflict !! 
Thank you soo much for pointing out !! 😃 
But we are having the numbers !! 🚀

**Comment by kunjgit** [comment]
Hey @rajatnai49 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
