### ISSUE TITLE
[New game]: Duck hunting game

### ISSUE THREAD

**Issue by singh-anushka** [kunjgit/GameZone#126]
### 🎮 Game Request

Game logic and basic description
A basic game prepared using HTML, CSS and Javascript. Your role in this game is of a hunter who has to hunt for the ducks that are randomly flying in the sky. Use your mouse as a gun to do the same.

### Point down the features

Game points
There are no points as such with respect to this game. Hunt for as many ducks as possible and don't forget to enjoy!

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey  @singh-anushka ! Thank you for raising an issue 💗 You have been assigned this issue you can start working on the issue 🎮

**Comment by kunjgit** [comment]
Hello @singh-anushka, Time's Uppp!⏰ 
 Sorry for closing your issue! 
 But it's more than a week since we haven't received anything from your side 😢 . 
 Come up with new ideas, create a new issue and make sure you finish it within a week! 🔥 
 All the best! 🚀 
 Happy Hacking! 💗

**Comment by kunjgit** [comment]
Hey @singh-anushka ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
