### ISSUE TITLE
[New game]: DUNGEON PUZZLE 👾

### ISSUE THREAD

**Issue by 0xabdulkhalid** [kunjgit/GameZone#1263]
### 🎮 Game Request

Game logic and basic description
- You must to mount a puzzle to connect lands and build a path where your heroes will walk and fight the undead, until find and kill the Lord of Death.
- When you place a piece, you earn gold and more warriors on each neighbor piece with the same terrain. If no available piece matches the place you want, you can pay to randomly replace one.

### Point down the features

Game points

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @0xabdulkhalid ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)
