### ISSUE TITLE
[New game]: rogueluck

### ISSUE THREAD

**Issue by S-ishita** [kunjgit/GameZone#1265]
### 🎮 Game Request

Rogueluck is a roguelike game. Why? Because it has "Rogue" in the title. Rogueluck is also about luck, but this time not only because of the title. There are monsters, luck, arrows, blood, luck, points, haunted trees, luck and many more!

### Point down the features

Game features:
* 1 mighty weapon!
* 2 types of randomly generated worlds!
* 4 wicked enemies!
* unlimited arrows and blood!
* awesome points to collect!

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @S-ishita! 
We are already having a similar game request in #1192 👀 
Make sure you come up with a cool unique idea 😀 
 Waiting for your new game idea 💗.

**Comment by kunjgit** [comment]
Hey @S-ishita ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by kunjgit** [comment]
Hey @S-ishita ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)
