### ISSUE TITLE
[New game]: Guess the colour from the given RGB coordinates.

### ISSUE THREAD

**Issue by singh-anushka** [kunjgit/GameZone#127]
### 🎮 Game Request

Game logic and basic description
A basic game with 3 options for choosing which will be the best colour for the closest match for the asked RGB coordinates.

### Point down the features

Game points
A series of questions will be asked and if you get the correct answers more than the wrong ones, you win!

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @singh-anushka  ! Thank you for raising an issue 💗 You have been assigned this issue you can start working on the issue 🎮

**Comment by kunjgit** [comment]
Hey @singh-anushka ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
