### ISSUE TITLE
[Enhancement]: Among Us game

### ISSUE THREAD

**Issue by shambhaveesrivastava12** [kunjgit/GameZone#1272]
### Is your enhancement request related to a problem? Please describe.➕

Game enhancement: I am looking forward to contributing to this open-source projects and making it even better.

I noticed an aspect that could be improved for a better user experience.

### Describe the solution you'd like

I recommend considering the following points:
1) Visual Appeal: By incorporating a good theme music at the very start, can help gain good user experience and attract the so. Also, the start button conflicts with the UI.
![Screenshot 2023-06-11 130811](https://github.com/kunjgit/GameZone/assets/110680194/00c9b152-6a1f-4c26-acb2-452e9434300c)
![Screenshot 2023-06-11 123827](https://github.com/kunjgit/GameZone/assets/110680194/50aa5fcc-7dfa-4088-88fb-8aee82edc3c7)

2)Accessibility: By adding more crew-mates, the duration of the game can be extended and it makes it more interesting. Also, there should be an option to play again at the very end since it may persuade the user to try it again, which somehow enhances the user experience.
![Screenshot 2023-06-11 123804](https://github.com/kunjgit/GameZone/assets/110680194/edcaad8e-6aae-4d0d-a223-76c628169d0f)

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @shambhaveesrivastava12 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hello @shambhaveesrivastava12, Time's Uppp!⏰ 
 Sorry for closing your issue! 
 But it's more than a week since we haven't received anything from your side 😢 . 
 Come up with new ideas, create a new issue and make sure you finish it within a week! 🔥 
 All the best! 🚀 
 Happy Hacking! 💗

**Comment by kunjgit** [comment]
Hey @shambhaveesrivastava12 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
