### ISSUE TITLE
Adding glitch effect to the main text

### ISSUE THREAD

**Issue by piyushkhurana2019** [kunjgit/GameZone#128]
### Give a brief about the bug ✍️

Description:- The main text of the website is not eye catching.
<img width="1440" alt="Screenshot 2023-05-21 at 10 22 05 AM" src="https://github.com/kunjgit/GameZone/assets/96003210/08ecd7a7-7e38-4a08-a7b5-78c7cd52a294">

### What is the expected behavior? 🤔

Description:- As a gaming website it needs a cool user interface, adding a glitch effect in the main text "Game Zone" makes the user to pause there for a second, the website will become more eye catching 

### Provide step by step information reproduce the bug 📄

Just open the website and see

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @piyushkhurana2019 !
We are not up for the changes for UI yet !! 
Thank you !!

**Comment by kunjgit** [comment]
Hey @piyushkhurana2019 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
