### ISSUE TITLE
[New game]: Candy crush

### ISSUE THREAD

**Issue by singh-anushka** [kunjgit/GameZone#129]
### 🎮 Game Request

Game logic and basic description
Basic Candy Crush Game using HTML, CSS and JavaScript.
The goal is to match at least three candies of the same colour and type in a row or column to clear them from the board. With each successful match, players earn points.

### Point down the features

Game points
Points are earned when at least 3 candies in the same row or column are matched. The more candies you match in a single move, the higher the score.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by singh-anushka** [comment]
Please assign me this issue. And add a GSSOC'23 tag

**Comment by kunjgit** [comment]
Hey @singh-anushka  ! Thank you for raising an issue 💗 You have been assigned this issue you can start working on the issue 🎮

**Comment by kunjgit** [comment]
Hey @singh-anushka ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
