### ISSUE TITLE
[New game]: Timer madness

### ISSUE THREAD

**Issue by S-ishita** [kunjgit/GameZone#1294]
### 🎮 Game Request

Train your reflexes in a race against time. Click the dots to make them explode and start the Madness

### Point down the features

Click the dots to make them explode.
Don't need to rush things, though: the closer you get to the explosion, the more points you earn!

Pay attention to the wandering dots and don't let them go away: if you click them the background turns red and the madness begins!
Swipe as much as you can and make plenty of points destroying multiple dots with a single gesture.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @S-ishita ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)
