### ISSUE TITLE
[New game]: under the crypt

### ISSUE THREAD

**Issue by S-ishita** [kunjgit/GameZone#1301]
### 🎮 Game Request

In this dungeon crawling tower defense game you play a paranormal researcher tasked with ridding an old crypt of its supernatural inhabitants. 

### Point down the features

Try to survive as long as possible while defeating wave after wave of enemies. Because you will die a lot, you can choose between hard mode (permadeath) and normal mode.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @S-ishita ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)
