### ISSUE TITLE
[New game]: Alchemist defense

### ISSUE THREAD

**Issue by S-ishita** [kunjgit/GameZone#1307]
### 🎮 Game Request

So let's say you are a famous alchimist, poorly drawn spartans runs toward your home and they looks angry.

Use your powers to defend your laboratory, build defences.

Each element give a unique capacity for the tower, it's possible to combine elements to upgrade the tower.

### Point down the features

The game is played in a isometric 3D view.

The map can be rotated when dragging it, which allows to see hidden spot and produce a nice effect.

Drag and drop an element from the right menu into the map to build a tower.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @S-ishita ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @S-ishita ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
