### ISSUE TITLE
[New game]: Dinosaur Game

### ISSUE THREAD

**Issue by singh-anushka** [kunjgit/GameZone#131]
### 🎮 Game Request

Game logic and basic description
In this game, there is a prehistoric landscape where our player is a dinosaur. The objective is simple: help the dinosaur navigate through an endless desert while avoiding obstacles and surviving for as long as possible. As you progress, the game becomes increasingly challenging. Cacti and flying pterodactyls will try to block your path, and you must time your jumps and crouches perfectly to avoid them.

### Point down the features

Game points
Each time dinosaur dodges an obstacle, a point is scored. As the points increase the game becomes more difficult.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @singh-anushka  ! Thank you for raising an issue 💗 You have been assigned this issue you can start working on the issue 🎮

**Comment by kunjgit** [comment]
Hey @singh-anushka ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
