### ISSUE TITLE
[New game]: Dark legend

### ISSUE THREAD

**Issue by S-ishita** [kunjgit/GameZone#1314]
### 🎮 Game Request

A portal to the dark realm has opened releasing a hoard of shadowy demons and plunges the world into eternal darkness. These creatures are weak to light which turns your flashlight into a weapon. However your flashlight has limited batteries and using it messes with your eyes adjustment to this perpetual darkness.

### Point down the features

 So use with care and survive as long as you can. The game ends when you run out of battery for your flashlight.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @S-ishita ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @S-ishita ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
