### ISSUE TITLE
[New game]: SUPER_BUNNY 👾

### ISSUE THREAD

**Issue by 0xabdulkhalid** [kunjgit/GameZone#1315]
### 🎮 Game Request

Game logic and basic description
- Take Kitty on a quest to find Bunny lost! Journey through dark forests and snowy meadows, pass through a great waterfall to finally reach the steppes and confront the Lion King! Clear the game to unlock Super Bunny and then hop with him at increased difficulty!

- Player starts hopping from the left side of the screen to the right on scrolling platforms. The goal is to avoid the creatures that appear on the platforms and reach the power-up on the right side of the screen. Taking the power-up turns the player into Super Kitty/Bunny, at which point he must dispatch all creatures to clear the stage and proceed to the next one.

### Point down the features

Game points

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @0xabdulkhalid ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)
