### ISSUE TITLE
[New game]: elemental shooter

### ISSUE THREAD

**Issue by S-ishita** [kunjgit/GameZone#1325]
### 🎮 Game Request

Elemental Block Shooters is a top-down shooter roguelike with procedurally generated levels. The game has four different weapons and 4 different types of level that represents each element. In this game you need to survive.

### Point down the features

Controls:
=========

- WASD or ARROWS;
- Mouse to aim;
- Click to shoot;

Gameplay:
=========
- Shoot at the enemies (blocks);
- Dodge the enemies bullets;
- When kill all enemies, you need to go to the center of the map and pass over a specific tile, to go to the next map;
- The weapons are random, you can't choose;
- The enemies sometimes drop weapons;

Modes
=====

Arcade
------

16 procedurally generated maps, when you beat the last one, returns to the first;

Survivor
--------
A lot of random maps!

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @S-ishita ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)
