### ISSUE TITLE
[New game]: Memory Game

### ISSUE THREAD

**Issue by Arka2708** [kunjgit/GameZone#133]
### 🎮 Game Request

Memory Game, also known as the Concentration card game or Matching Game is a classic card-flipping game where players test their memory skills by matching pairs of cards. The objective of the game is to flip over two cards at a time and find all the matching pairs within the specified number of moves.

### Point down the features

1. You will start by flipping over one card
2. If the next card you flip matches, a pop-up alert notifies you and you get +1 to your score
3. These cards then disappear.
4. If the next card you flip does not match, a pop-up alert notifies you of this and the cards flip back
5. The game continues until you match all the cards on the board.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Arka2708 we are having similar game in #34 !!

**Comment by kunjgit** [comment]
Hey @Arka2708 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by Arka2708** [comment]
@kunjgit That's fine, but you assigned this project to someone at issue #162, if it's already exists then how he can do that, just a general query...
