### ISSUE TITLE
[New game]: Flappy Bird

### ISSUE THREAD

**Issue by Arka2708** [kunjgit/GameZone#134]
### 🎮 Game Request

A simple JS clone of the flappy bird. The Flappy Bird game is a popular side-scrolling mobile game where players control a bird and navigate it through a series of pipes. The objective of the game is to fly the bird as far as possible without hitting the pipes or the ground.

### Point down the features

In the Flappy Bird game, points are typically scored based on successfully passing through the gaps between the pipes. If you hit the pipe or ground, the game is over and the total score will be shown.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Arka2708 !! We are already having similar game in #22 !!

**Comment by kunjgit** [comment]
Hey @Arka2708 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
