### ISSUE TITLE
[New game]: Rubik's cube simulator

### ISSUE THREAD

**Issue by singh-anushka** [kunjgit/GameZone#135]
### 🎮 Game Request

Game logic and basic description
A basic simulation of a physical Rubik's cube using HTML, CSS and Javascript. Where the motion controls are done using mouse clicks. The Rubik's cube used will be of the of size 3x3.

### Point down the features

Game points
There won't be any points scored or reduced per move. Just use the motion controls and keep on changing the configuration so that. To the the one that you want!

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @singh-anushka  ! Thank you for raising an issue 💗 You have been assigned this issue you can start working on the issue 🎮

**Comment by kunjgit** [comment]
Hello @singh-anushka, Time's Uppp!⏰ 
 Sorry for closing your issue! 
 But it's more than a week since we haven't received anything from your side 😢 . 
 Come up with new ideas, create a new issue and make sure you finish it within a week! 🔥 
 All the best! 🚀 
 Happy Hacking! 💗

**Comment by kunjgit** [comment]
Hey @singh-anushka ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
