### ISSUE TITLE
[New game]: dropdown element

### ISSUE THREAD

**Issue by S-ishita** [kunjgit/GameZone#1358]
### 🎮 Game Request

A fall-down style platformer with an elements theme. 

### Point down the features

Drop as far as you can go while avoiding the fire. Hit water to put out fires and air to fall slower.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @S-ishita ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
