### ISSUE TITLE
[New game]: RETURN 👾

### ISSUE THREAD

**Issue by 0xabdulkhalid** [kunjgit/GameZone#1359]
### 🎮 Game Request

Game logic and basic description
- You were one of the select few chosen to trial a new hyperspace jump drive. You reach towards the red jump button in the front of your cockpit as directed; there is a whooshing noise as the jump drive spins up. Space and time warps around you, suddenly there is a bang and the ship drops out of hyperspace.
-  'This isn’t the correct destination' you think to yourself, the jump drive must be faulty. Return is a game about finding your way back home after being lost amongst the stars. ('Home' is the blue planet of course, a.k.a Earth).

### Point down the features

Game points

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @0xabdulkhalid ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)
