### ISSUE TITLE
Creative home page design(Gssoc'23)

### ISSUE THREAD

**Issue by Bharatpathak08** [kunjgit/GameZone#136]
I would like to make the home page creative and more interesting.

**Comment by Bharatpathak08** [comment]
I'll make the home page a bit more creative and interesting. Plz assign it to me and label it as Gssoc'23.

**Comment by kunjgit** [comment]
Hey @Bharatpathak08 !! Use the template to raise an issue !! 
according the changes you want to make !!!

**Comment by kunjgit** [comment]
Hey @Bharatpathak08 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
