### ISSUE TITLE
[New game]: Pit Escape

### ISSUE THREAD

**Issue by S-ishita** [kunjgit/GameZone#1363]
### 🎮 Game Request

Escape the pit inhabited by biologically improbable snakes.

### Point down the features

Make your way through 9 levels of varying difficulty. If you get caught, you go back one level. The game is turn-based, constantly giving you an opportunity to think.

Controls: arrows to move (or WASD, or HJKL like in Vi).

Cheat: press ] to skip level.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @S-ishita ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)
