### ISSUE TITLE
[New game]: Felicity

### ISSUE THREAD

**Issue by S-ishita** [kunjgit/GameZone#1367]
### 🎮 Game Request

'Oh no!',
                     'Felicity\'s boyfriend is losing his love!',
                     'Brave the four elements and collect the hearts before they break.',
                     'Fill the heartmeter to complete the level.',
                     'Watch out for windducks, firesprites, sandmonsters and snowmen.',
                     'Use the correct element to defeat them.',
                     '',
                    

### Point down the features

 'Controls:',
                     'Arrow keys: Move left/right, Jump, Go down stairs',
                     'Z: Jump',
                     'X: Switch Element',
                     'C: Use Element',
                     '',
                     'M: Mute sounds',
                     'P: Pause'

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @S-ishita ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)
