### ISSUE TITLE
[New game]: Tower Blocks

### ISSUE THREAD

**Issue by singh-anushka** [kunjgit/GameZone#137]
### 🎮 Game Request

Game logic and basic description
Blocks will be sliding in different directions. Your aim is to stop them at the right place so as to make the highest tower possible.

### Point down the features

Game points
Each time the height of a tower is increased 10 points are scored. When this series breaks, the game ends.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @singh-anushka  ! Thank you for raising an issue 💗 You have been assigned this issue you can start working on the issue 🎮

**Comment by kunjgit** [comment]
Hey @singh-anushka ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
