### ISSUE TITLE
[New game]: fewa

### ISSUE THREAD

**Issue by S-ishita** [kunjgit/GameZone#1371]
### 🎮 Game Request

You have the four elements and 3 types of bricks from each element type.
Stroked empty bricks are weak, color filled bricks are stronger and signed bricks are the strongest.
If you shoot the signed bricks with the proper element it has a special effect.

Fire special brick explodes the whole column of bricks.
Earth special brick explodes surrounding bricks.
Water special brick explodes the whole row of bricks.
Air special brick explodes all the weak(stroked) air bricks.

### Point down the features

The Fire element, most effective against fire bricks, but least effective against water bricks.
The Earth element, most effective against earth bricks, but least effective against air bricks.
The Water element, most effective against water bricks, but least effective against fire bricks.
The Air element, most effective against air bricks, but least effective against earth bricks.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @S-ishita ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @S-ishita ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
