### ISSUE TITLE
[New game]: Ibex

### ISSUE THREAD

**Issue by S-ishita** [kunjgit/GameZone#1378]
### 🎮 Game Request

The world is burning, Protect and Escort a group of wild ibex away from the inferno.
On the path there are sleeping ibex to rescue, wake them and they will join the group.

You will have to use the 4 elements (Air, Earth, Fire, Water)
to make your animal progress safely in the environnment.

The 4 elements are primary elements but there are also secondary elements at play:
- The Volcano (creates fire)
- The Source (drops water)
- The Forest (created by Earth and Water)
- The Wind (left wind and right wind is created randomly in Air)

### Point down the features

All elements interact with each other and the ibex also react to elements in different ways.

- Earth is a platform for the ibex
- Fire scares the ibex
- Water attracts the ibex
- Forest makes the ibex running faster

Controls
---

Keyboard: SPACE to draw an element, ARROWS to move, W/Z + X + C + V to switch between Air + Earth + Fire + Water.

Keyboard is recommended but playing only with mouse is also possible (click on elements and DRAG the inner cursor).

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @S-ishita ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
