### ISSUE TITLE
[New game]: Tic-tac-toe

### ISSUE THREAD

**Issue by pavitrachavda97** [kunjgit/GameZone#138]
### 🎮 Game Request

**Game logic and basic description**
This game will be created using HTML, CSS and JavaScript. This is two player game. User will play this game turn by turn. And will check for win after every move, if anyone won then game is over and they can start play again.

**Basic Logic for game:**
- First game board will be Initialize.
- Starting player will be X
- Player will select board
- Check for win 
- Update board
- Switch player
- If player win then game stopped

### Point down the features

**Game points**
When one player will satisfy winner conditions then that player will win the game.

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @pavitrachavda97 !! We are already having similar issue in #18 !!!

**Comment by kunjgit** [comment]
Hey @pavitrachavda97 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
