### ISSUE TITLE
[New game]: Dance Mat Challenge

### ISSUE THREAD

**Issue by singh-anushka** [kunjgit/GameZone#139]
### 🎮 Game Request

Game logic and basic description
Move your keys in coordination with the arrows displayed on the screen. The dance mat itself is displayed on the screen, consisting of arrow keys in different directions. As the music starts playing, the arrows will light up, indicating the steps you need to perform, or the key you need to press.

### Point down the features

Game points
Every right arrow press will help you score a point!

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @singh-anushka  ! Thank you for raising an issue 💗 You have been assigned this issue you can start working on the issue 🎮

**Comment by kunjgit** [comment]
Hey @singh-anushka ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
