### ISSUE TITLE
[New game]: Memorizing the cards game

### ISSUE THREAD

**Issue by Devanxh** [kunjgit/GameZone#14]
### Game logic and basic description

1. Display the cards face-down in a grid pattern on the webpage.
2. Allow the player to click on a card.
3. When a card is clicked, reveal its symbol.
4. Track the number of flipped cards.
5. If it's the first card flipped, remember it.
6. If it's the second card flipped:
7. Compare the symbols of the two cards.
8. If they match, keep them face-up.
9. If they don't match, flip them face-down after a short delay.
10. Allow the player to continue selecting pairs of cards.
11. Keep track of the number of attempts or time taken.
12. Once all cards are matched, display the player's score.

### Game points

- **Score Tracking:** Implement a scoring system that keeps track of the player's performance. Assign points for each successful match and deduct points for incorrect guesses or flips.
- **Timer:** Include a timer to add a time constraint to the game. Start the timer when the player begins the game and stop it when all the cards are matched. Display the elapsed time to the player as they play.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey  @Devanxh ! Thank you for raising an issue 💗 You have been assigned this issue you can start working on the issue 🎮

**Comment by kunjgit** [comment]
Hello @Devanxh, Time's Uppp!⏰ 
 Sorry for closing your issue! 
 But it's more than a week since we haven't received anything from your side 😢 . 
 Come up with new ideas, create a new issue and make sure you finish it within a week! 🔥 
 All the best! 🚀 
 Happy Hacking! 💗

**Comment by kunjgit** [comment]
Hey @Devanxh ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
