### ISSUE TITLE
Connect 4

### ISSUE THREAD

**Issue by dishal35** [kunjgit/GameZone#140]
### 🎮 Game Request

The objective is to be the first to connect four of your colored discs in a vertical, horizontal, or diagonal line. Players take turns dropping one disc into any of the seven columns, causing it to occupy the lowest available space.

### Point down the features

It will render a 7x6 board for the classic battle of connect 4. It will also allow the users to change the color of their discs.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @dishal35 !! we are having similar game in #112 !!

**Comment by kunjgit** [comment]
Hey @dishal35 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
