### ISSUE TITLE
[New game]: Mission

### ISSUE THREAD

**Issue by S-ishita** [kunjgit/GameZone#1407]
### 🎮 Game Request

You play as Reverend Captain Lore Whitaker, a missionary en route to prefecture 461.

For centuries, successful missions have been founded on one simple concept: that the four elements describe both our terrestial lives and our spiritual lives. Easy to remember. Easy to spread to alien civilizations

### Point down the features

Try to pick planets that might be habitable. If you don't like your current selection, you can hit the '...' button to search for more planets. This takes a turn, but doesn't waste fuel.
Ratings
When you visit a planet, you'll see a rating of 1-4 for each element. Three is ideal. All elements can be estimated from a visual inspection, so try to learn the relationship between the look of the planet and the ratings! 

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @S-ishita ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @S-ishita ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by kunjgit** [comment]
Hey @S-ishita ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
