### ISSUE TITLE
[New game]: orbcraft

### ISSUE THREAD

**Issue by S-ishita** [kunjgit/GameZone#1409]
### 🎮 Game Request

* Use the mouse to make an Orb of type Fire, Earth, Water, or Air.
* The Orb will apear in your inventory, click and drag it to a building in the game board.
* The building can now defend itself from enemy's.
* Making Orbs cost Mana.
* You make more Mana over time, you also gain it from enemy's
* You can combine Orbs to make them more powerful, and to have interesting properties.
* When you kill all the enemy's, a new Level will start in which the enemy's will become more difficult.
* Good luck

### Point down the features

Orbs and Attributes:

Orbs come in the following types, and have the corresponding attribute bonuses

* Fire - bonus to attack
* Earth - bonus to range
* Water - bonus to health
* Air - bonus to speed

* attack - The amount of damage that will be done to an enemy when an Orb attacks
* range  - The range in which an Orb can attack an enemy.
* health - Increases the max HP of the building in which the Orb is socketed, as well as the auto-heal rate.
* speed  - The rate at which an Orb attacks, and auto-heals per second.

All Orbs have the given attributes, however as stated above, certain orbs have bonuses to certain attributes. 
You can also make composite orbs with bonuses in more then one attribute depending on it's composition.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @S-ishita ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)
