### ISSUE TITLE
[New game]: Escape the Enchanted Mansion 🏚️ 

### ISSUE THREAD

**Issue by Abhinavcode13** [kunjgit/GameZone#141]
### 🎮 Game Request

Game logic and basic description 

Description:
"Escape the Enchanted Mansion" is an immersive and challenging escape room game that tests your puzzle-solving skills and ability to think outside the box. You find yourself trapped inside a mysterious mansion filled with hidden clues, mind-bending puzzles, and intriguing secrets. Your mission is to navigate through the mansion's rooms, uncover the secrets of its past, and find a way to escape.

Features:

1) Multi-Room Escape: Explore multiple rooms within the mansion, each with its own unique atmosphere, challenges, and puzzles to solve.
2)Interactive Environment: Click on objects, examine them closely, and interact with the environment to uncover hidden clues and unlock new areas.
3)Engaging Puzzles: Encounter a variety of puzzles, riddles, and challenges that require critical thinking, logic, and observation skills to solve.
4)Inventory System: Collect and manage items in your inventory, utilizing them at the right time and place to progress through the game.
5)Hint System: Stuck on a puzzle? Use the built-in hint system to receive subtle clues or guidance to help you move forward.
6)Atmospheric Graphics and Sound: Immerse yourself in the captivating ambiance of the Enchanted Mansion with visually appealing graphics and sound effects.
7)Time Pressure: Feel the thrill of racing against the clock as you strive to escape before time runs out.
8)Responsive Design: Play the game on various devices and screen sizes, thanks to its responsive design powered by Bootstrap.

### Point down the features

Game points

Clue Discovery: Earn 10 points for each discovered clue or hidden object.
Puzzle Solving: Receive 50 points for successfully solving each puzzle or challenge.
Efficiency: Gain 1 point for every second remaining on the timer when you escape the mansion.
Item Collection: Collecting each useful item adds 20 points to your score.
Accuracy: No points deducted for mistakes or incorrect choices.
Bonus Challenges: Completing each bonus challenge awards 100 points.
Penalty for Mistakes: No points deducted for mistakes or incorrect choices.
Leaderboards: Compete for the highest score among other players.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by Abhinavcode13** [comment]
please assign this issue to me @kunjgit

**Comment by kunjgit** [comment]
Hey  @Abhinavcode13 ! Thank you for raising an issue 💗 You have been assigned this issue you can start working on the issue 🎮

**Comment by kunjgit** [comment]
Hello @Abhinavcode13, Time's Uppp!⏰ 
 Sorry for closing your issue! 
 But it's more than a week since we haven't received anything from your side 😢 . 
 Come up with new ideas, create a new issue and make sure you finish it within a week! 🔥 
 All the best! 🚀 
 Happy Hacking! 💗

**Comment by kunjgit** [comment]
Hey @Abhinavcode13 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
