### ISSUE TITLE
[New game]: Tower Of Hanoi

### ISSUE THREAD

**Issue by AnkitaBarbora** [kunjgit/GameZone#1411]
### 🎮 Game Request

The Tower of Hanoi is a classic mathematical puzzle or game that consists of three rods and a set of disks of different sizes. The puzzle starts with all the disks stacked in ascending order of size on one rod, with the largest disk at the bottom and the smallest at the top. The objective is to transfer the entire stack of disks to another rod, while following certain rules.

The rules are as follows:

- Only one disk can be moved at a time.
- Each move consists of taking the top disk from one of the rods and placing it on top of the stack on another rod.
- A larger disk should never be placed on top of a smaller disk. In other words, at any point during the game, each rod should maintain the order of disk sizes with the largest disk at the bottom and the smallest at the top.

### Point down the features

- Problem-Solving: The Tower of Hanoi puzzle requires logical thinking, problem-solving skills, and careful planning. 
- Mathematical Application: The Tower of Hanoi puzzle has connections to various mathematical concepts, including number theory, combinatorics, and binary representation. 

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @AnkitaBarbora ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @AnkitaBarbora ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
