### ISSUE TITLE
 Binary Sudoku

### ISSUE THREAD

**Issue by dishal35** [kunjgit/GameZone#142]
### 🎮 Game Request

Binary Sudoku, also known as 0/1 Sudoku, is a logic-based puzzle game played on a grid of squares divided into smaller regions. Instead of using numbers, players must fill in the grid with 0s and 1s, following the rule that each row, column, and region must contain an equal number of 0s and 1s. The objective is to solve the puzzle by applying logical deduction.

### Point down the features

Game Modes: Include different game modes such as "Easy," "Medium," and "Hard" to cater to players of varying skill levels.

Puzzle Generation: Implement an algorithm that generates unique Sudoku puzzles with varying levels of difficulty. This ensures that players have a wide range of puzzles to solve.

Customization Options: Allow players to customize the appearance of the game board, including different themes, colors, and backgrounds. This adds a personal touch to the game.

Undo/Redo Functionality: Allow players to undo or redo their moves to correct any mistakes or try different strategies without starting the puzzle from scratch.

Timer and Leaderboards: Add a timer to keep track of the player's solving time and display it at the end of each puzzle.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey  @dishal35 ! Thank you for raising an issue 💗 You have been assigned this issue you can start working on the issue 🎮

**Comment by kunjgit** [comment]
Hello @dishal35, Time's Uppp!⏰ 
 Sorry for closing your issue! 
 But it's more than a week since we haven't received anything from your side 😢 . 
 Come up with new ideas, create a new issue and make sure you finish it within a week! 🔥 
 All the best! 🚀 
 Happy Hacking! 💗

**Comment by kunjgit** [comment]
Hey @dishal35 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
