### ISSUE TITLE
[New game]: shadow ball

### ISSUE THREAD

**Issue by S-ishita** [kunjgit/GameZone#1435]
### 🎮 Game Request

# Shadow Ball

Shadow Ball is a game in which you must shoot and kill the never ending armies of the four elements. To the north there is the Air army, to the east the Water army, to the south the Earth army, and to the west the Fire army. Each level adds increasingly more enemies in each room. But you have one advantage: The spirit Orb; providing an endless supply of golden power for you to absorb. But watch out for the deadly mist that protects the enemy territories, and remember to make regular trips back to the Orb to recharge.

### Point down the features

# Controls
**Move:** Arrows  
**Jump/Fly:** Space  
**Fire:** M  
**Absorb:** N  
**Push:** B  
**Pickup/Drop:** V  
**Pause:** P  

Hold down the Space key in mid-air to fly.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @S-ishita ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @S-ishita ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
