### ISSUE TITLE
[Enhancement]: Modify Project Item Card Dimensions

### ISSUE THREAD

**Issue by NarendraKoya999** [kunjgit/GameZone#1438]
### Is your enhancement request related to a problem? Please describe.➕

Game enhancement:

### Actual Picture in Desktop Screen Size
<img width="916" alt="Gamezone Pic" src="https://github.com/kunjgit/GameZone/assets/84512164/e809f597-2e99-4741-b9bf-f7b2836f828b">

### Description:

- Observing above Screenshot related to Gamezone Website.
- In this Website, Multiple Games having Too Much Project Item Card Screen Ratio like Height Wise.
- I made this Issue and Solve this in Two Scenarios.

 ### The Best Example:
 **If confusing, the Best Example is Grid Pattern with Different Row/Column Ratios.**

### Describe the solution you'd like

Solution steps:

### Scenario 1:( Only One Project having This Issue in One Line & Follow these Things)

- Whenever Project Item Card having Too Much Screen Ratio. Much Do Follow Things. 
- We can Design that Project Item Card Deep Dive Into Next Line and Settled Full Screen Size according to Our Previous Design Codes.
- Before Do That, Add Some Interactivity with JavaScript with Certain Conditions attached with CSS related to above Screen Sizes. 
- Whenever Particular Fixed Project Item Card Screen Size is Increased, Its goes into the Next Entire Maximum Screen .
- It saves Maximum Space around the Project Item Cards List.

### Scenario 2:( If you Have Multiple Projects having this Issue in One Line & Follow These Things)

- If Multiple Too Much Project Item Cards are having Same Thing happens in One Line. Then, You can Provide Some Interactivity Using JavaScript attached with CSS related to respective Individual  Screen Sizes.
- Design Conditionally and Individually with Fixed Dimensions using JavaScript according to above Screen Size Ratios.

### NOTE: 

- In these above Two Scenarios, We can only Interactivity with JavaScript & Project Item Card Screen Sizes.
- Above Two Scenarios, Giving Measurable and Proper Height Value, and Fixed Width value connect with Previous Design code, When the Specific Condition is Reached.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @NarendraKoya999 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by tanbirali** [comment]
Hello 
Can I work on this issue?

**Comment by NarendraKoya999** [comment]
Hey @kunjgit . This issue Given To Others

**Comment by kunjgit** [comment]
Hello @NarendraKoya999, Time's Uppp!⏰ 
 Sorry for closing your issue! 
 But it's more than a week since we haven't received anything from your side 😢 . 
 Come up with new ideas, create a new issue and make sure you finish it within a week! 🔥 
 All the best! 🚀 
 Happy Hacking! 💗

**Comment by kunjgit** [comment]
Hey @NarendraKoya999 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
