### ISSUE TITLE
[New game]: Zelda

### ISSUE THREAD

**Issue by KhushiTayal** [kunjgit/GameZone#144]
### 🎮 Game Request

This game is a 2D platformer where you control a character and navigate through different levels. Your objective is to collect coins, defeat enemies, and reach the exit point to progress to the next level. 

### Point down the features

Use arrow keys to move Link and interact with doors. 
Avoid hazards and enemies to stay alive. 
The game features multiple levels, scoring, and a game over screen displaying your final score.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @KhushiTayal  ! Thank you for raising an issue 💗 You have been assigned this issue you can start working on the issue 🎮

**Comment by kunjgit** [comment]
Hello @KhushiTayal, Time's Uppp!⏰ 
 Sorry for closing your issue! 
 But it's more than a week since we haven't received anything from your side 😢 . 
 Come up with new ideas, create a new issue and make sure you finish it within a week! 🔥 
 All the best! 🚀 
 Happy Hacking! 💗

**Comment by kunjgit** [comment]
Hey @KhushiTayal ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
