### ISSUE TITLE
[New game]: spellcast away

### ISSUE THREAD

**Issue by S-ishita** [kunjgit/GameZone#1442]
### 🎮 Game Request

Mr Elementualle has been in a deserter island for a couple of years when, unexpectedly, he ran into a magic coconut that gave him powers to make an escape from the island!

### Point down the features

Press:
    "1"  - to fix the raft, with your earth power, and gain some health;
    "2"  - to catch a fish, with your air power, and gain some health;
    "3"  - to attack the sharks, with your fire power;
    <=-  - to move left;
    -=>  - to move right.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @S-ishita ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @S-ishita ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
