### ISSUE TITLE
[New game]: Tic-Tac Toe

### ISSUE THREAD

**Issue by 1TusharSharma1** [kunjgit/GameZone#145]
### 🎮 Game Request

Game logic and basic description

Tic-Tac-Toe is a classic paper-and-pencil game played on a 3x3 grid. The game involves two players, often referred to as "X" and "O," who take turns marking spaces on the grid. The objective is to create a horizontal, vertical, or diagonal line of three of your marks (either "X" or "O") before the opponent does.

Here are some key features of the Tic-Tac-Toe game:

Grid: The game is played on a 3x3 grid, which provides a total of 9 cells where players can make their moves.

Turn-Based Gameplay: The game follows a turn-based structure, where players alternate placing their marks on empty cells of the grid.

Player Markers: There are two types of markers used in Tic-Tac-Toe: "X" and "O." Each player selects one marker at the beginning of the game.

Valid Moves: Players can only place their markers on empty cells. Once a cell is marked, it cannot be changed or overwritten.

Winning Conditions: The game continues until one player achieves a winning condition. A winning condition is met when a player successfully places three of their markers in a horizontal, vertical, or diagonal line on the grid.

Draw Condition: If all the cells on the grid are filled, and no player has achieved a winning condition, the game is considered a draw.

Restart Option: After the game ends, players should have the option to restart and play again without having to reload the page.

### Point down the features

Game points

User Interface: The game will have a visually appealing and user-friendly interface that displays the Tic-Tac-Toe grid, markers, and other necessary elements.

Player vs. Player: The game will support a two-player mode where two human players can play against each other on the same device.

Interactive Gameplay: Players will be able to interact with the game by clicking or tapping on the grid cells to place their markers.

Restart and Reset: Players will have the option to restart the game after it ends, allowing for continuous play without reloading the page. Additionally, a reset option will be available to start a new game at any point.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @1TusharSharma1 ! we are already having similar game request in #18  !!

**Comment by kunjgit** [comment]
Hey @1TusharSharma1 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
