### ISSUE TITLE
[Beware of the ghost]: 

### ISSUE THREAD

**Issue by sinhapalak** [kunjgit/GameZone#146]
### 🎮 Game Request

The player has to jump away from the coming ghost with the help of arrow buttons. The speed of coming ghost will increase with time.

### Point down the features

The player will try to jump away from the ghost.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @sinhapalak  ! Thank you for raising an issue 💗 You have been assigned this issue you can start working on the issue 🎮

**Comment by kunjgit** [comment]
Hello @sinhapalak, Time's Uppp!⏰ 
 Sorry for closing your issue! 
 But it's more than a week since we haven't received anything from your side 😢 . 
 Come up with new ideas, create a new issue and make sure you finish it within a week! 🔥 
 All the best! 🚀 
 Happy Hacking! 💗

**Comment by kunjgit** [comment]
Hey @sinhapalak ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
