### ISSUE TITLE
[New game]: RETURN_TO_PLANET_FIGADORE 👾

### ISSUE THREAD

**Issue by 0xabdulkhalid** [kunjgit/GameZone#1465]
### 🎮 Game Request

Game logic and basic description
- It's 50 years since humans first went to the moon. Now that we are planning to go back, the Regoliths need to escape before we find them. They have light-jumped to planet Figadore in the Hercules cluster to flee.
- Fred has been kidnapped by the aliens who want to take over the planet. Play as his sister Jade and race to get the planet back and prevent the Regolith spreading a deadly infection.

### Point down the features

Game points

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @0xabdulkhalid ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @0xabdulkhalid ! , This issue is already assigned to @0xabdulkhalid. 💗 
 You can work on other issues 🚀 
 If there is anything wrong you can contact us on [Discord🕹️](https://discord.gg/fgwk4XZfxG)👀

**Comment by kunjgit** [comment]
Hey @0xabdulkhalid ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
