### ISSUE TITLE
[New game]: MrFake Game

### ISSUE THREAD

**Issue by singhshivanii** [kunjgit/GameZone#1473]
### 🎮 Game Request

MrFakeGame is a simple online JavaScript game where the objective is to score 750 points within 45 seconds. Players control a character on the right side of the screen using the WASD or arrow keys. The enemy remains on the left side. By pressing the space bar, players can send a projectile towards the enemy, earning around 35 points per hit. Only one projectile can be sent at a time. The game ends when either the target score is reached or the time runs out.

### Point down the features

MrFakeGame is a straightforward online JavaScript game that offers a fast-paced and engaging experience. The main objective of the game is to score 750 points within a time limit of 45 seconds. Players have control over a character situated on the right side of the screen and can navigate it using either the WASD or arrow keys.

The game introduces an enemy character positioned on the left side of the screen. To earn points, players must successfully hit the enemy by sending a projectile towards them. However, they can only send one projectile at a time, adding an element of strategy and timing to the gameplay.

Each successful hit on the enemy awards players with around 35 points, contributing to their overall score. The clock is ticking, and players must be swift and accurate to achieve the target score before the 45-second time limit expires.

MrFakeGame's simplicity and quick rounds make it a captivating choice for players seeking an enjoyable and challenging gaming experience. With its intuitive controls and a clear objective, players can dive right into the action and test their reflexes and precision.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @singhshivanii ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @singhshivanii ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
