### ISSUE TITLE
GhostBusters[New game]: 

### ISSUE THREAD

**Issue by shraddha761** [kunjgit/GameZone#1478]
### 🎮 Game Request

The game follows the player's character as a recruit in the Ghostbusters, a team of parapsychologists who pursue and capture ghosts. The game features elements of typical third-person shooters, but instead of a traditional gun, each player is equipped with a Proton Pack, and other technological means of fighting and capturing ghosts. The game's plot is set two years after Ghostbusters II, in 1991, with the Ghostbusters team training the player's character while investigating paranormal activities in New York City.

### Point down the features

The Ghost Busters Video Game is a 2009 action-adventure game based on the Ghostbusters media franchise. Terminal Reality developed the Windows, PlayStation 3, and Xbox 360 versions, while Red Fly Studio developed the PlayStation 2, PlayStation Portable, and Wii versions. The game was released after several delays in development and multiple publisher changes. 

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @shraddha761 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @shraddha761 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
