### ISSUE TITLE
[New game]: Guess the Number Game

### ISSUE THREAD

**Issue by vidhimakani74** [kunjgit/GameZone#148]
### 🎮 Game Request

Game logic and basic description:
In this Game Computer will guess the number between 1 to 100. And your task is to find that number in 10 Chance.
you can also  reset the game and play again. computer also provide hints based on previous entered number like enter small number or enter grater number.

### Point down the features

Game points:
user can reset game
computer provides hints
10 chance to guess number
user friendly UI

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @vidhimakani74 !! 
Come up with some unique exciting game we are already having it on #37 !!
If you feel to have enhancement once it is on website you can do that too !!

**Comment by kunjgit** [comment]
Hey @vidhimakani74 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
