### ISSUE TITLE
Angry Wall[New game]: 

### ISSUE THREAD

**Issue by shraddha761** [kunjgit/GameZone#1483]
### 🎮 Game Request

Click the bird and drag left & right.
Navigate to open the game in pydroid3, click anywhere to start the game. The objective of the game is to create high score without touching the falling walls & red balls.

### Point down the features

Angry Walls is a simple hypercasual game made with pygame. The game is specifically meant to run on pydroid3 on android.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @shraddha761 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)
