### ISSUE TITLE
Snake game:

### ISSUE THREAD

**Issue by iamsuyashpatel07** [kunjgit/GameZone#149]
### 🎮 Game Request

A Snake will be inside a box and will be moved on the basis of an arrow 
- top
- bottom 
- left
- right
If hit the wall then the game will be over if he will eat the "feed" then its length will  increases as well as score will also.

### Point down the features

Game points.
- it can be played on mobile as well as on laptop (Device Friendly)
- Smoothness of Game without any lag

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by Krishna9027** [comment]
I would like to work on this issue please kindly assign me this issue so I can start working on it as early as I can.

**Comment by kunjgit** [comment]
Hey  @iamsuyashpatel07 ! Thank you for raising an issue 💗 You have been assigned this issue you can start working on the issue 🎮

**Comment by iamsuyashpatel07** [comment]
Hey @kunjgit  can you review https://github.com/kunjgit/GameZone/pull/215 completed this issue.

**Comment by kunjgit** [comment]
Hey @iamsuyashpatel07 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
