### ISSUE TITLE
Breakout Game[New game]: 

### ISSUE THREAD

**Issue by shraddha761** [kunjgit/GameZone#1494]
### 🎮 Game Request

Use your right and left keys to move the paddle to bounce the ball up and break the blocks. If you miss the ball, your score and the blocks will reset.

### Point down the features

simple game using html, css and js

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @shraddha761 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
