### ISSUE TITLE
Car racing game

### ISSUE THREAD

**Issue by shraddha761** [kunjgit/GameZone#1496]
### 🎮 Game Request

The game could be as simple as two lane road racing where multiple cars compete to reach the finish line first. With two lane road, it would be easier for gesture control and wouldn't take much conrol.The main objective is to get the experience of Virtual Drive like Same In real.

### Point down the features

Control Turn Left
Control Turn Right
Control Turn Back
Control Running Straight
Control Running Back

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @shraddha761 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @shraddha761 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
