### ISSUE TITLE
[New game]: Car racing

### ISSUE THREAD

**Issue by Arnabhit** [kunjgit/GameZone#15]
### 🎮 Game Request

Game logic and basic description

It is a 3D racing game using HTML, CSS, and
JavaScript. It sets up event listeners for keyboard input, initializes game variables and objects, and updates the game state in a loop. The game involves driving a car on a road,avoiding obstacles and other cars, and trying to complete laps as quickly as possible. The code also includes functionality for displaying a high score table and playing sound effects.

The code sets the background color, font family, and height of the body. It also defines the styles for the top UI elements such as the time, score, and lap counters. Additionally, it sets the styles for the tachometer at the bottom of the screen.

It has all the styles for a game interface, including the positioning and appearance of various elements such as the road, hero character, clouds, and high score display. It also includes animations for blinking text and transitions for opacity and timing.
 

 

### Point down the features

It has all the styles for a game interface, including the positioning and appearance of various elements such as the road, hero character, clouds, and high score display. It also includes animations for blinking text and transitions for opacity and timing.

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by 584aditya** [comment]
I have a great interest in games also. Assign this issue to me. I will try my best and build it as soon as possible.

**Comment by kunjgit** [comment]
Hey @Arnabhit  ! Thank you for raising an issue 💗 You have been assigned this issue you can start working on the issue 🎮

**Comment by 584aditya** [comment]
Sir have to assigned the issue to @Arnabhit.

**Comment by kunjgit** [comment]
Hey @Arnabhit ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
