### ISSUE TITLE
[New game]: Tower of Hanoi

### ISSUE THREAD

**Issue by Sudhanshu-Sharma-22** [kunjgit/GameZone#150]
### 🎮 Game Request

Game logic and basic description:
In Tower of Hanoi game players have to move a stack of discs from one tower to another, following specific rules and minimizing the number of moves.

### Point down the features

Game points:
Shift all the discs in minimum number of moves.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by Krishna9027** [comment]
I would like to work on this project  as an GSSOC 23 contributor kindly assign me this issue

**Comment by SALONI-AGGARWAL0304** [comment]
I want to work on this project

**Comment by kunjgit** [comment]
Hey @Sudhanshu-Sharma-22 ! we are already having similar game request in #51 !!!

**Comment by kunjgit** [comment]
Hey @Sudhanshu-Sharma-22 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by Sudhanshu-Sharma-22** [comment]
Sure. I'll Start Working on it right away....:)
