### ISSUE TITLE
[New game]: HangMan

### ISSUE THREAD

**Issue by MrVisc** [kunjgit/GameZone#1500]
### 🎮 Game Request

Hangman is a word guessing game. It is a game where the user is given a world but all the letters are blanks and the user is to guess the word. The user can guess random letters to try and reveal the word but he/she has to do it within limited tries or he loses.

### Point down the features

1.Generating a hidden word.
2.Validating the user option.
3.Revealing the right letter or decreasing the players lives by one depending on the validation.
4.The victory or a game over message to denote the end of the game

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @MrVisc ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @MrVisc ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
