### ISSUE TITLE
[New game]: Fruit Ninja

### ISSUE THREAD

**Issue by varunshankar07** [kunjgit/GameZone#151]
### 🎮 Game Request

Fruit Ninja using HTML, CSS, and JavaScript. Fruit Ninja is an exciting and fast-paced game where players slice flying fruits while avoiding slicing bombs. The objective is to achieve a high score by slicing as many fruits as possible within a given time limit.

### Point down the features

Features 😊

Fruit Slicing: Allow players to slice flying fruits by using mouse clicks or touch events. Detect the slicing action and provide visual feedback, such as fruit splitting into halves.

Fruit Generation: Randomly generate fruits at different positions on the screen. Vary the size, type, and velocity of fruits to add challenge and excitement.

Score Tracking: Keep track of the player's score based on the number of fruits sliced correctly. Display the current score and highest achieved score on the game screen.

Bombs: Include bombs that appear along with the fruits. Slicing a bomb should result in a penalty or reduction of the player's score. Display warnings or indicators to help players avoid slicing bombs.

Sound Effects and Visual Feedback: Enhance the gaming experience with engaging sound effects for fruit slicing, combo achievements, and bomb explosions. Provide visual feedback through animations and effects to make the game more immersive.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by varunshankar07** [comment]
@kunjgit please look at this one

**Comment by op-amateur** [comment]
Please assign me this issue, thank you.

**Comment by kunjgit** [comment]
Hey @varunshankar07  ! Thank you for raising an issue 💗 You have been assigned this issue you can start working on the issue 🎮

**Comment by varunshankar07** [comment]
@kunjgit Sure.thank you😊

**Comment by kunjgit** [comment]
Hey @varunshankar07 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
