### ISSUE TITLE
[New game]: Mastermind 

### ISSUE THREAD

**Issue by srujana-16** [kunjgit/GameZone#1510]
### 🎮 Game Request

The Mastermind game is a classic game implemented using HTML, CSS, and JavaScript. It is a memory based game in which the player flips the cards and tries to get a match. 

### Point down the features

In this project, we will be looking at creating a grid of cards, that can be flipped over and matched. If a match is found, the cards stay flipped, if not, they will turn back. The game continues until all cards are flipped.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @srujana-16 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
