### ISSUE TITLE
[New game]: Cosmic Blaster

### ISSUE THREAD

**Issue by U-DAY-333** [kunjgit/GameZone#1518]
### 🎮 Game Request

Embark on an interstellar adventure with "Cosmic Blaster." In this thrilling game, you find yourself at the epicenter of a cosmic battleground, armed with an arrow-shaped blaster. Your mission? Destroy the asteroids that surround you by shooting them down. As your shots connect, the asteroids shatter into smaller fragments until they reach their breaking point. The skillful precision of your aim is rewarded with points, where the value of each hit is determined by the size of the asteroid. The smaller the asteroid, the higher the points awarded. Brace yourself for an exhilarating journey into space as you demonstrate your marksmanship and astronomical expertise in Cosmic Blaster.

### Point down the features

For blasting a large asteroid - 20 points
For blasting a Medium asteroid - 35 points
For blasting a small asteroid - 50 points

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @U-DAY-333 , You can't have another issue before completing the previous one 😀 
 you already have the following 1 open issues 👀 ! : 
#1514

**Comment by kunjgit** [comment]
Hey @U-DAY-333 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by kunjgit** [comment]
Hey @U-DAY-333 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @U-DAY-333 ! , This issue is already assigned to @U-DAY-333. 💗 
 You can work on other issues 🚀 
 If there is anything wrong you can contact us on [Discord🕹️](https://discord.gg/fgwk4XZfxG)👀

**Comment by kunjgit** [comment]
Hey @U-DAY-333 ! , This issue is already assigned to @U-DAY-333. 💗 
 You can work on other issues 🚀 
 If there is anything wrong you can contact us on [Discord🕹️](https://discord.gg/fgwk4XZfxG)👀
