### ISSUE TITLE
[Bug]: No scroll to top button

### ISSUE THREAD

**Issue by kaashikaagrawal** [kunjgit/GameZone#1520]
### Give a brief about the bug ✍️

I can include an arrow icon near the scroll bar that allows the user to scroll to the top with one click.

### What is the expected behavior? 🤔

After scrolling through the games, if the user wishes to go back to the top of the screen, they can click the button. It will take them to the top.

### Provide step by step information reproduce the bug 📄

I can try using html, css and javascript to  take care of the issue.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @kaashikaagrawal ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @kaashikaagrawal ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
