### ISSUE TITLE
[Enhancement]: UI design of master typing

### ISSUE THREAD

**Issue by samratghosh291** [kunjgit/GameZone#1522]
### Is your enhancement request related to a problem? Please describe.➕

Game enhancement:

- Background add color grinding

### Describe the solution you'd like

Solution steps:

- Updated the CSS file

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @samratghosh291 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
