### ISSUE TITLE
[New game]: Tower Defense

### ISSUE THREAD

**Issue by tayyab-ilyas** [kunjgit/GameZone#153]
### 🎮 Game Request

A tower defense game is a popular genre of strategy game where the player's objective is to defend a specific location, typically referred to as a "base" or "castle," from waves of enemies. The game typically takes place on a grid-based map, and the player must strategically place defensive structures, known as towers, along the enemy's path to stop their advance.

### Point down the features

1. Tower Placement: Players can strategically place towers along enemy paths or designated areas to attack and eliminate enemies.

2. Enemy Waves: Waves of enemies spawn at regular intervals and move along predetermined paths towards the player's base. Each wave typically increases in difficulty.

3. Resource Management: Players earn resources or in-game currency by defeating enemies. They can use these resources to build or upgrade towers. 

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @tayyab-ilyas ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @tayyab-ilyas ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
