### ISSUE TITLE
[New game]: Tilting Maze

### ISSUE THREAD

**Issue by Pavan8421** [kunjgit/GameZone#1531]
### 🎮 Game Request

Game logic and basic description
The basic description of the game involves navigating some balls through a maze by tilting the maze itself. The player's objective is to reach the goal or target location within the maze while avoiding obstacles and walls. The maze's tilt is controlled either by keyboard/mouse input. The game provides visual feedback of the maze's tilt and updates the player's position accordingly. Collision detection ensures that the player cannot pass through walls or obstacles. The game can have an easy and a hard level, each with progressively more complex mazes to navigate.

### Point down the features

Game points
In this game if the player reaches all the balls to the target location of the maze then the player wins.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hello @Pavan8421, Time's Uppp!⏰ 
 Sorry for closing your issue! 
 But it's more than a week since we haven't received anything from your side 😢 . 
 Come up with new ideas, create a new issue and make sure you finish it within a week! 🔥 
 All the best! 🚀 
 Happy Hacking! 💗

**Comment by kunjgit** [comment]
Hey @Pavan8421 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
