### ISSUE TITLE
[New game]: Whack a mole game

### ISSUE THREAD

**Issue by lakhan06** [kunjgit/GameZone#1532]
### 🎮 Game Request

IN this game a mole will come out of the pipes and if you click on it then your points will increase 
But also a plant will come so if you click on the plant then game will over .
![image](https://github.com/kunjgit/GameZone/assets/119161467/072cee86-3c34-445c-8da4-e59076076cf3)

### Point down the features

- In this game their will be nine pipes out of which a mole will come and user have to click on the mole before it disappear.
- To increase the difficulty a plant also come from holes and if user click on the plant then game will over.In this game their will be nine pipes out of which a mole will come and user have to click on the mole before it disappear.
- To increase the difficulty a plant also come from holes and if user click on the plant then game will over.
- Every correct click on the mole will increase your point by 10.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @lakhan06 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @lakhan06 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
