### ISSUE TITLE
[New game]: Chrome Dinosaur Game Dodging

### ISSUE THREAD

**Issue by chinmayjain08** [kunjgit/GameZone#1534]
### 🎮 Game Request

The game logic is as follows:

The game starts with the dinosaur running to the right.
Obstacles, such as cacti and pterodactyls, are randomly generated on the screen.
The player can jump over obstacles by pressing the spacebar or up arrow key.
If the player hits an obstacle, the game ends.
The player's score increases for each obstacle they jump over.
The game gets progressively faster as the player progresses.
The player can use power-ups to increase their score or slow down the game.
The player can also use the Konami code to unlock a secret mode.

### Point down the features

Simple controls: The game is controlled with just two keys: the spacebar to jump and the down arrow to duck.
Endless gameplay: The game is endless, so you can keep playing as long as you can avoid the obstacles.
High score tracking: The game keeps track of your high score, so you can see how you compare to other players.
Online leaderboards: You can compare your high score to other players around the world.
No internet connection required: The game can be played even when you don't have an internet connection.

The Chrome Dinosaur Game is a simple, fun game that you can play when you're bored. It's a great way to pass the time and improve your reflexes.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @chinmayjain08 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @chinmayjain08! 
We are already having a similar game request in #1448 👀 
Make sure you come up with a cool unique idea 😀 
 Waiting for your new game idea 💗.

**Comment by kunjgit** [comment]
Hey @chinmayjain08 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
