### ISSUE TITLE
[New game]: Tetris Game

### ISSUE THREAD

**Issue by chinmayjain08** [kunjgit/GameZone#1535]
### 🎮 Game Request

A new tetromino piece is spawned at the top of the playfield.
The player can rotate and move the tetromino piece left and right.
The player can drop the tetromino piece by pressing the down arrow key.
When the tetromino piece touches the bottom of the playfield or another tetromino piece, it will be locked into place.
If a row of tetromino pieces is filled, it will be removed from the playfield and the player will score points.
The game ends when the playfield is filled with tetromino pieces.

### Point down the features

Different levels: The game can have different levels with different challenges, such as faster falling speed or more difficult tetromino pieces.
Power-ups: The player can collect power-ups that can help them clear rows or score more points.
Reflex and Concentration of user increases.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @chinmayjain08 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @chinmayjain08 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
