### ISSUE TITLE
[New game]: 3D Stack 

### ISSUE THREAD

**Issue by chinmayjain08** [kunjgit/GameZone#1536]
### 🎮 Game Request

Game logic and basic description
The simple logic of a stack game is to keep the stack from falling over. The player can do this by adding blocks to the stack in a way that they support each other. The game can be made more challenging by adding different types of blocks, or by making the stack taller.

### Point down the features

Power-ups: Power-ups can be added to the game to help the player, such as a block that can be used to clear the entire stack, or a block that can be used to make the stack taller.
Leveling system: A leveling system can be added to the game to give the player a sense of progression. As the player progresses through the levels, the stack will become taller and more challenging.
Online multiplayer: Online multiplayer can be added to the game so that players can compete against each other.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @chinmayjain08 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
