### ISSUE TITLE
[New game]: 

### ISSUE THREAD

**Issue by Sampath-Vatsavaya** [kunjgit/GameZone#155]
### 🎮 Game Request

The objective of Pac-Man is to navigate through a maze, consuming all the dots while avoiding ghosts. Four ghosts, each with their own unique color and behavior, roam the maze. The ghosts are constantly chasing Pac-Man, attempting to capture him. If Pac-Man collides with a ghost, he loses a life. The player's goal is to score as many points as possible before losing all their lives. 

### Point down the features

1. Maze: The game takes place in a maze consisting of corridors, walls, and dots. The maze is typically displayed from a top-down perspective.

2. Pac-Man: The player controls Pac-Man, a small, circular character with a big mouth. Pac-Man can move in four directions (up, down, left, and right) through the corridors of the maze.

3. Dots(Pellets): The maze is filled with small dots that Pac-Man must eat. Each dot consumed adds points to the player's score. 

4. Ghosts: Four ghosts, each with its own unique color and behavior, roam the maze. The ghosts are constantly chasing Pac-Man, attempting to capture him. If Pac-Man collides with a ghost, he loses a life. 

5. Lives: Pac-Man begins the game with a set number of lives. Losing a life occurs when Pac-Man collides with a ghost. When all lives are lost, the game ends. Lives are indicated by Pac-Man symbol at the bottom of the maze

6. Score: Every time Pac-Man eats a dot the score will be increased(initially it starts at 0) and the score will be reset if game is over. The Score is presented at the bottom of the maze 

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Sampath-Vatsavaya ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @Sampath-Vatsavaya ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
