### ISSUE TITLE
[New game]: AirBalloon

### ISSUE THREAD

**Issue by MrVisc** [kunjgit/GameZone#1550]
### 🎮 Game Request

The player is flying a balloon and has limited fuel, he/she has to go as far as possible while avoiding the tree obstacles.
And also flying too high consumes more fuel.

### Point down the features

1.Clicking down the mouse will make the balloon go up 
2.Releasing the mouse will make the balloon gradually go down.
3.If balloon touches a tree or if it runs out of fuel, you lose.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @MrVisc ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @MrVisc ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
