### ISSUE TITLE
[New game]: Star battle game

### ISSUE THREAD

**Issue by Abhinavcode13** [kunjgit/GameZone#1559]
### 🎮 Game Request

Game logic and basic description:

Press W A S D control spacecraft，Press Space fire.
The initial fuel value is 15. Decrement by 1 point per second. When the fuel value is 0, the game is over.
The fuel bottle that touches it can be increased by 15 points and the maximum value is 30 points.
Hit the enemy spacecraft to increase by 5 points. The planet needs to hit twice, increasing by 10 points. Hit the friend to deduct 10 points.
Collision enemy loses 15 points of fuel, and the friendly party deducts 10 points.
Game allows negative points.
Press P Pause game. Press M mute。

### Point down the features

Game points:

Mentioned in game description

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Abhinavcode13 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
