### ISSUE TITLE
[New game]: Mastermind game

### ISSUE THREAD

**Issue by Abhinavcode13** [kunjgit/GameZone#1560]
### 🎮 Game Request

Game logic and basic description

The code is a four color code containing the colored buttons displayed. The code may contain multiples of the same color. Try to guess the correct code (color and order) by clicking on the colored buttons and then hitting the submit button. Your guess will then be compared to the code. For every correct color that is in the correct position, a black peg will be displayed. However, for every correct color that is in the wrong position, a white peg will be displayed. Use this feedback to determine the correct code

Crack the hidden code

### Point down the features

Game points

### Select program in which you are contributing

GSSoC23, Other

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Abhinavcode13 , You can't have another issue before completing the previous one 😀 
 you already have the following 1 open issues 👀 ! : 
#1559

**Comment by kunjgit** [comment]
Hey @Abhinavcode13 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by kunjgit** [comment]
Hey @Abhinavcode13 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @Abhinavcode13! 
We are already having a similar game request in #1510 👀 
Make sure you come up with a cool unique idea 😀 
 Waiting for your new game idea 💗.
