### ISSUE TITLE
[New game]: Typing game

### ISSUE THREAD

**Issue by Abhinavcode13** [kunjgit/GameZone#1561]
### 🎮 Game Request

Game logic and basic description:

Usually, a typing game will require the player to quickly or precisely type in words - or individual letters, numbers, or other keys - that display on the screen to proceed in the game, functioning as both a challenge and a means to improve one's skill at touch typing.

### Point down the features

Game points

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Abhinavcode13 , You can't have another issue before completing the previous one 😀 
 you already have the following 1 open issues 👀 ! : 
#1559

**Comment by kunjgit** [comment]
Hey @Abhinavcode13 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by kunjgit** [comment]
Hey @Abhinavcode13! 
We are already having a similar game request in #798 👀 
Make sure you come up with a cool unique idea 😀 
 Waiting for your new game idea 💗.

**Comment by kunjgit** [comment]
Hey @Abhinavcode13 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)
