### ISSUE TITLE
[New game]: 3D Car Game

### ISSUE THREAD

**Issue by harshitaaa8** [kunjgit/GameZone#1562]
### 🎮 Game Request

Game logic and basic description
Use left right arrow keys on your keyboard to play the game.
Aim is to collect maximum number of coins without crashing your car.

### Point down the features

Game points
Interactive interface which is easy to use by the user.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @harshitaaa8! 
We are already having a similar game request in #991 👀 
Make sure you come up with a cool unique idea 😀 
 Waiting for your new game idea 💗.

**Comment by kunjgit** [comment]
Hey @harshitaaa8 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @harshitaaa8 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by harshitaaa8** [comment]
Can still work on this issue??
I will make the pr by tomorrow
@kunjgit

**Comment by harshitaaa8** [comment]
@kunjgit please let me know if I can still make the pr as its showing closed status??

![Screenshot 2023-06-25 144413](https://github.com/kunjgit/GameZone/assets/121786696/01c4b671-f9cb-4a25-867b-030427329434)
