### ISSUE TITLE
[Bug]: Remove all the unnecessary console logs

### ISSUE THREAD

**Issue by Avinash905** [kunjgit/GameZone#1563]
### Give a brief about the bug ✍️

There are many console logs in the project which appear while using the website which clutters the browser console.

### What is the expected behavior? 🤔

The browser console tag should not show console.log messages to the user.

### Provide step by step information reproduce the bug 📄

- Remove console.log statements from all the files.

### Screenshots
![Screenshot (484)](https://github.com/kunjgit/GameZone/assets/56786344/3a24a804-af49-4809-86e0-a7df5d5acfc2)
![Screenshot (485)](https://github.com/kunjgit/GameZone/assets/56786344/e3832ef4-d4b4-464f-84d9-7314ebe2a1fb)

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by Avinash905** [comment]
Please assign me this issue so that I can work on this issue under **GSSOC'23**.

**Comment by kunjgit** [comment]
Hey @Avinash905 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @Avinash905 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
