### ISSUE TITLE
Website does not have proper meta tags

### ISSUE THREAD

**Issue by Avinash905** [kunjgit/GameZone#1564]
**Issue:** The website does not have meta tags with descriptions.

**Impact:** This means that the website is not as visible in search results, and users are less likely to click on the website's links.

**Resolution:** The website should contain important meta tags. This will help the website rank higher in search results and attract more visitors.

**Comment by kunjgit** [comment]
Hey @Avinash905 , You can't have another issue before completing the previous one 😀 
 you already have the following 1 open issues 👀 ! : 
#1563

**Comment by kunjgit** [comment]
Hey @Avinash905 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by kunjgit** [comment]
Hey @Avinash905 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)
