### ISSUE TITLE
[Documentation Bug]: Adding dependabot.yml file

### ISSUE THREAD

**Issue by Anshika-Jain02** [kunjgit/GameZone#1566]
### Describe the bug ✍️

*We need to add dependabot.yml file as it helps us to keep our dependencies up to date. Every day, it checks your dependency files for outdated requirements and opens individual PRs for any it finds.*

@kunjgit please assign me this issue under gssoc'23.

### Provide step by step information reproduce the bug 📄

Sample file:-

[dependabot.yml](https://github.com/kunjgit/GameZone/files/11751447/dependabot.yml.txt)

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Anshika-Jain02 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by Anshika-Jain02** [comment]
@kunjgit Sorry sir, i will take care of this from next time.

**Comment by kunjgit** [comment]
Hey @Anshika-Jain02 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
