### ISSUE TITLE
Typewriter effect in main heading

### ISSUE THREAD

**Issue by Anshika-Jain02** [kunjgit/GameZone#1567]
*We can add a typewriter effect in the below heading to give a dynamic effect and to improve the visual appearance of the overall website.*

![game zone](https://github.com/kunjgit/GameZone/assets/104912087/72b79538-4ec0-4534-bd62-58b91f55ec45)

@kunjgit Please assign me this issue under gssoc'23

**Comment by kunjgit** [comment]
Hey @Anshika-Jain02 , You can't have another issue before completing the previous one 😀 
 you already have the following 1 open issues 👀 ! : 
#1566

**Comment by kunjgit** [comment]
Hey @Anshika-Jain02 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @Anshika-Jain02 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by kunjgit** [comment]
Hey @Anshika-Jain02! 🙂 
 It seems like you are not following proper guidelines !! 👀 
 Read documentation properly !!🙏 
 If you have any queries reach out to us on [Discord🕹️](https://discord.gg/fgwk4XZfxG) .

**Comment by Anshika-Jain02** [comment]
> Hey @Anshika-Jain02 , You can't have another issue before completing the previous one 😀 you already have the following 1 open issues 👀 ! : #1566

Sir, as #1566 is completed can i start working on this?
