### ISSUE TITLE
[Bug]: Website does not have proper meta tags

### ISSUE THREAD

**Issue by Avinash905** [kunjgit/GameZone#1571]
### Give a brief about the bug ✍️

The website does not have meta tags with descriptions. This means that the website is not as visible in search results, and users are less likely to click on the website's links.

### What is the expected behavior? 🤔

The website should contain important meta tags. This will help the website rank higher in search results and attract more visitors.

### Provide step by step information reproduce the bug 📄

Add meta tags like keywords, description, open graph, twitter, etc.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Avinash905 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by Avinash905** [comment]
@kunjgit Could you please assign labels to it?

**Comment by kunjgit** [comment]
Hey @Avinash905 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
