### ISSUE TITLE
[New game]: Bulls Eye Game [GSSoC'23]

### ISSUE THREAD

**Issue by Avdhesh-Varshney** [kunjgit/GameZone#1573]
### 🎮 Game Request

Game logic and basic description

- This is multi player game
- This is made by using HTML, CSS and JS languages
- This is best suited to get the feel of archery
- Just hit the target and get the points

### Point down the features

Game points

- If just hit the board, +1 point
- If hit the bulls eye of the board, +1 ( +1 for bonus point )

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Avdhesh-Varshney , You can't have another issue before completing the previous one 😀 
 you already have the following 1 open issues 👀 ! : 
#1572

**Comment by kunjgit** [comment]
Hey @Avdhesh-Varshney ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)
