### ISSUE TITLE
Rock paper Scissor[New game]: 

### ISSUE THREAD

**Issue by lakhan06** [kunjgit/GameZone#158]
### 🎮 Game Request

In this game a person need to select one option out of rock ,Paper And scissor and then computer select Randomly a option out of these three .so if a person win he will get +1 point and if he loss then he will get -1 point and if match draws then he will get 0 points .

### Point down the features

Game points:
winning ->+1points
Loosing->-1Points
draw->0points

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @lakhan06 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by lakhan06** [comment]
assign

**Comment by lakhan06** [comment]
assign

**Comment by kunjgit** [comment]
Hey @lakhan06 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by lakhan06** [comment]
ok sir .
thankyou 
i will continue my contributions in game zone and will like to do more things together in future
