### ISSUE TITLE
[New game] [Insect Catch Game]: 

### ISSUE THREAD

**Issue by JadavShraddha** [kunjgit/GameZone#1580]
### 🎮 Game Request

<h2>Game logic and basic description:</h2>

<li>This game is created with the help of html, css and javascript.</li>
<li>In this game first you can choose your favorite insect.The objective of the game is to catch as many insects as possible within a given time limit.</li>
<li>The insects come in various shapesand they move quickly and unpredictably across the screen.</li>
<li>The catchers must be quick and agile to track the insects' movements and snatch them out of the air.</li>

### Point down the features

<h2>Game points</h2>

<ol>
<li>change the insect type</li>
<li>show user points and time on screen</li>
<li>sound feature</li>
</ol>

### Select The Game Type

Single Player

### Pictures
![1st](https://github.com/GameSphere-MultiPlayer/GameSphere/assets/95160083/8b854179-a1bc-44bc-951d-2728594cb287)
<br>
![2nd](https://github.com/GameSphere-MultiPlayer/GameSphere/assets/95160083/0bbf1cff-1956-43ca-bac0-afc23daa77d8)

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by JadavShraddha** [comment]
assign

**Comment by kunjgit** [comment]
Hey @JadavShraddha ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
