### ISSUE TITLE
[New game]: Space Invader Game with an easter egg.

### ISSUE THREAD

**Issue by Pin4sf** [kunjgit/GameZone#159]
### 🎮 Game Request

# Game description 🕹️.
Space Invader is an old school **Arcade Game** developed by Tomohiro Nishikado and is considered an iconic game in the industry with the likes of Pac-Man , Donkey kong and Mario.

### GamePlay 🀄

The game is a shooter where the **player controls a laser cannon at the bottom** of the screen and tries to destroy waves of aliens that move horizontally and vertically. The player can move the cannon left and right and fire one shot at a time. The aliens also fire back at the player and can destroy the cannon with a single hit. The game has four bunkers that the player can use for cover, but they are gradually destroyed by the alien shots. The _game ends when the aliens reach the bottom of the screen_ _or when the player runs out of lives._ 
![bg-main-menu](https://github.com/kunjgit/GameZone/assets/83578233/d872fefe-af8d-4d85-9ba6-ff6f268e5c16)

### Point down the features

# Game Logic 🤖
> For Alien Waves 👾
- Here we are using **Canvas** to run our game.
- A function will change the x and y - velocity according to their direction and will update the enemy movement
- We will create a function to enable alien troops to shoot bullets.

>For Player  🧑🏽‍✈️
- Player will only move in X direction.
- Player will have a Shooting Mechanics.

# Game points 🔮
-You will have a dedicated menu to control and customize your spaceships.
-A difficulty Bar controlling enemy Speed.

>Much more customization........

## A Easter Egg is awaiting you.
![th](https://github.com/kunjgit/GameZone/assets/83578233/28a22383-8cee-4681-a51f-5f36b88a88e3)

Hope you like the project.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Pin4sf ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Sounds interesting @Pin4sf !! ❤️‍🔥 
You can start working on the issue !!

**Comment by REC-1104** [comment]
I would also like to work on this issue .

**Comment by Pin4sf** [comment]
> I would also like to work on this issue .

It will be really helpful if we collaborate on this project.
@kunjgit can you please assign this project to @REC-1104 I want to work along with him on this game.

**Comment by kunjgit** [comment]
Hey @Pin4sf 👋!
 
  @kunjgit here, 
 We have this annoucement to make 📢!! 
 We have updated our README 🚀 
 Make sure you follow proper guideline to raise your next issues !! 
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG) if you haven't 😇 
  Thank you 💗!

**Comment by kunjgit** [comment]
Hello @Pin4sf, Time's Uppp!⏰ 
 Sorry for closing your issue! 
 But it's more than a week since we haven't received anything from your side 😢 . 
 Come up with new ideas, create a new issue and make sure you finish it within a week! 🔥 
 All the best! 🚀 
 Happy Hacking! 💗

**Comment by kunjgit** [comment]
Hey @Pin4sf ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
