### ISSUE TITLE
[New game]: Magic Tiles

### ISSUE THREAD

**Issue by Keyuri-19** [kunjgit/GameZone#1591]
### 🎮 Game Request

Game logic and basic description
It is a special game in different genres of piano games and wonderful gameplay.
The game will be made with html css and javascript and here the player will have to touch the moving tiles and have to collect the points and will have the good music feature.

### Point down the features

Game points
Real music feeling when tapping the black tiles.
The more number of tiles are touched the points will be increased.
songs with great vocals are updated.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by Keyuri-19** [comment]
@kunjgit please assign these issue to me

**Comment by kunjgit** [comment]
Hello @Keyuri-19, Time's Uppp!⏰ 
 Sorry for closing your issue! 
 But it's more than a week since we haven't received anything from your side 😢 . 
 Come up with new ideas, create a new issue and make sure you finish it within a week! 🔥 
 All the best! 🚀 
 Happy Hacking! 💗

**Comment by kunjgit** [comment]
Hey @Keyuri-19 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
