### ISSUE TITLE
[New game]: Color Fill - A Challenging Puzzle Game[ChromoRush]

### ISSUE THREAD

**Issue by anandpiyush1521** [kunjgit/GameZone#1608]
### 🎮 Game Request

Game logic and basic description

Color Fill is an engaging 2D adventure game that tests your strategic thinking and puzzle-solving skills. Your objective is to fill the game board with a single color before exhausting your limited number of moves. With its simple yet addictive gameplay, Color Fill will keep you entertained and engaged for hours.

![Screenshot (1652)](https://github.com/kunjgit/GameZone/assets/75721333/a14506b9-57b3-483f-9971-b73af9c2acd4)

### Point down the features

Game points

- Randomly Appearing Moles
- Score Tracking
- Moves are Limited
- Interactive Gameplay Through Mouse Clicks
- Game Over Alert with Final Score
- Improve number of color
- Feature for improving board size

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @anandpiyush1521 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hello @anandpiyush1521, Time's Uppp!⏰ 
 Sorry for closing your issue! 
 But it's more than a week since we haven't received anything from your side 😢 . 
 Come up with new ideas, create a new issue and make sure you finish it within a week! 🔥 
 All the best! 🚀 
 Happy Hacking! 💗

**Comment by kunjgit** [comment]
Hey @anandpiyush1521 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
