### ISSUE TITLE
[New game]: Tic Tac Toe

### ISSUE THREAD

**Issue by Kwamecody** [kunjgit/GameZone#161]
### 🎮 Game Request

This is a Tic Tac Toe game with three different game options. Users can either play with another  user or play with AI

### Point down the features

- Users can enter their name
- Users can choose to play against another user locally
- User can play the game it an Easy Ai
- Users can play the game against an unbeatable AI.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Kwamecody ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by Kwamecody** [comment]
Thanks you Sir

**Comment by Kwamecody** [comment]
Well noted with thanks

**Comment by kunjgit** [comment]
Hello @Kwamecody, Time's Uppp!⏰ 
 Sorry for closing your issue! 
 But it's more than a week since we haven't received anything from your side 😢 . 
 Come up with new ideas, create a new issue and make sure you finish it within a week! 🔥 
 All the best! 🚀 
 Happy Hacking! 💗

**Comment by kunjgit** [comment]
Hey @Kwamecody ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by Kwamecody** [comment]
@kunjgit Sorry for the delay, I will like to make a rock paper scissors game .
