### ISSUE TITLE
[New game]: Guess the Correct Logo

### ISSUE THREAD

**Issue by shruti-2412** [kunjgit/GameZone#1610]
### 🎮 Game Request

The game contains logos of the same company with slight differences in them. We have to select the correct logo from the two.
There is a total of 30 seconds to play the game and for each correct answer user will get 1 point and the score will be displayed at the end after the time is over

### Point down the features

* Player will have to choose the correct logo from the two
* Time limit is 30 sec for playing the game
* Score will be shown at the end of the game

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @shruti-2412 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @shruti-2412 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
