### ISSUE TITLE
[New game]: Defuse the Bomb

### ISSUE THREAD

**Issue by nagachandu2003** [kunjgit/GameZone#1614]
### 🎮 Game Request

This is a puzzle game which consists of a grid of letters where used is asked to find the words present inside the grid.
Puzzle games like word search are popular for their simplicity, accessibility, and ability to entertain and engage players of all ages. If the user is able to find all the words present in the grid then user will win that round and get 50 points. Otherwise, user will lose the round.

Tech Stacks used : HTML, CSS and JS

### Point down the features

A timer will be set for every new game of 5 minutes.
The hidden words should have to find by the user to attain some points.
A score board will be maintained to track the user progress.

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @nagachandu2003 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hello @nagachandu2003, Time's Uppp!⏰ 
 Sorry for closing your issue! 
 But it's more than a week since we haven't received anything from your side 😢 . 
 Come up with new ideas, create a new issue and make sure you finish it within a week! 🔥 
 All the best! 🚀 
 Happy Hacking! 💗

**Comment by kunjgit** [comment]
Hey @nagachandu2003 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
