### ISSUE TITLE
Racing moto[New game]: 

### ISSUE THREAD

**Issue by Rekhathakur8** [kunjgit/GameZone#1617]
### 🎮 Game Request

There is a car in this game moving on the road. It hit some coins and gets points and so many features are available in it.
There is a loading page that loads the overall game. 

### Point down the features

This game is completely based on HTML, CSS, and javascript. 

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Rekhathakur8 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by Rekhathakur8** [comment]
I am working on it. I want some time for it because my college exams are going on. 
could you please give me some time?

**Comment by Rekhathakur8** [comment]
assign

**Comment by vk20july** [comment]
@kunjgit sir i want to work on this issue under gssoc'23

**Comment by kunjgit** [comment]
Hello @Rekhathakur8, Time's Uppp!⏰ 
 Sorry for closing your issue! 
 But it's more than a week since we haven't received anything from your side 😢 . 
 Come up with new ideas, create a new issue and make sure you finish it within a week! 🔥 
 All the best! 🚀 
 Happy Hacking! 💗

**Comment by kunjgit** [comment]
Hey @Rekhathakur8 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
