### ISSUE TITLE
[New game]: Memory Game

### ISSUE THREAD

**Issue by midhun-developer** [kunjgit/GameZone#162]
### 🎮 Game Request

1.Developing a memory game where players have to match pairs of cards within a time limit
2.The code shuffles and displays a grid of cards, allowing players to flip and match pairs within a time limit.

Tech Stack Used: HTML, CSS, JS.

### Point down the features

1. The game shuffles card symbols, creating a randomized order for each session.
2. Players click on cards to reveal their symbols and match pairs on the dynamically created game board.
3. Matching cards increase the player's score, while non-matching cards are flipped back over after a delay.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @midhun-developer ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @midhun-developer ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
