### ISSUE TITLE
[Enhancement]: Addition of home icon to the games page

### ISSUE THREAD

**Issue by KanchandeepK** [kunjgit/GameZone#1620]
### Is your enhancement request related to a problem? Please describe.➕
There could be some functionalities which could be improved in the games .

###Functionalities like: 
As for now ,whenever we choose a game we are directed to that game .But we need to use the arrow on the top to direct back to the homepage of the website.
![gameissue](https://github.com/kunjgit/GameZone/assets/116509506/bae47a91-6173-4b3a-9aaa-55492cbd2ae4)

### Describe the solution you'd like

Solution steps: Addition of home icon to the games  pages so that by hovering over the home icon we should be directed back to the home page .

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @KanchandeepK ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @KanchandeepK ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
