### ISSUE TITLE
[New game]: Frogger

### ISSUE THREAD

**Issue by Nilesh9106** [kunjgit/GameZone#163]
### 🎮 Game Request

Frogger is a simple yet challenging arcade game in which the player controls a frog that must cross a busy road and a river to reach its home. The game is played on a grid, and the frog can move left, right, up, and down. The player must avoid cars, trucks, and logs on the road. The player can earn points by crossing the road and river without being killed. The game ends when the player has successfully crossed the river.

### Point down the features

- the frog can move in any direction by avoiding all obstacles.
- The player can earn points by crossing the road and river without being killed.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Nilesh9106 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
