### ISSUE TITLE
[New game]: Shooting Ninja Game

### ISSUE THREAD

**Issue by Nishitbaria** [kunjgit/GameZone#1634]
### 🎮 Game Request

Its is Ninja Shooting Game with also Nina Maze Game

### Point down the features

1. On the top left corner your score will be displayed.
2. On the top right corner you can see your registered Name.
3. When game starts you have two types of target :-a). Ballon b). Man
4. You have to shoot only ballon using your mouse. if you shoot Man then your game will be over
<p align="center">
    <img src="https://github.com/kunjgit/GameZone/assets/85815172/33531306-a5ba-4603-8538-9366480a1217" width="250" alt="Game3">
    <img src="https://github.com/kunjgit/GameZone/assets/85815172/45720012-e1f2-4a21-a440-a80ae1403805" width="250" alt="Game2">
    <img src="https://github.com/kunjgit/GameZone/assets/85815172/e528e230-90bd-4fa3-97f8-9e0b53e71138" width="250" alt="Game1">
</p>

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Nishitbaria ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @Nishitbaria ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
