### ISSUE TITLE
[Documentation Bug]:  I want to add icon toggle button for dark/light theme

### ISSUE THREAD

**Issue by HimanshuNarware** [kunjgit/GameZone#1639]
### Describe the bug ✍️

Describe your bug here

The toggle button is not match with the UI of the website.

### Provide step by step information reproduce the bug 📄

Description

I want to add icon based toggle button.

##Screenshot
![11](https://github.com/kunjgit/GameZone/assets/83147410/c2379d31-3c2c-49a5-9398-330611a8a123)

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @HimanshuNarware ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by HimanshuNarware** [comment]
assign

**Comment by Kapileswar-Moharana** [comment]
I have already worked on this type of issue under GSSoC'23 on Dev-Geeks of Pranjay Poddar sir under GSSoC'23.I will fix this issue better .So assign this issue to me under GSSoC'23

**Comment by vk20july** [comment]
@kunjgit sir i want to work on this issue under gssoc'23

**Comment by kunjgit** [comment]
Hello @HimanshuNarware, Time's Uppp!⏰ 
 Sorry for closing your issue! 
 But it's more than a week since we haven't received anything from your side 😢 . 
 Come up with new ideas, create a new issue and make sure you finish it within a week! 🔥 
 All the best! 🚀 
 Happy Hacking! 💗

**Comment by kunjgit** [comment]
Hey @HimanshuNarware ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by HimanshuNarware** [comment]
> Hello @HimanshuNarware, Time's Uppp!⏰ Sorry for closing your issue! But it's more than a week since we haven't received anything from your side 😢 . Come up with new ideas, create a new issue and make sure you finish it within a week! 🔥 All the best! 🚀 Happy Hacking! 💗

Because i do not get assign this issue. That is why I was waiting to get an assign
