### ISSUE TITLE
Snake Game

### ISSUE THREAD

**Issue by Aryan5464** [kunjgit/GameZone#164]
### 🎮 Game Request

The player controls a long, thin creature, resembling a snake, which roams around on a bordered plane, picking up food (or some other item), trying to avoid hitting its own tail or the edges of the playing area. Each time the snake eats a piece of food, its tail grows longer, making the game increasingly difficult.

### Point down the features

   Following are the rules of the game:
1. You will start the game with the score 0.
2. After eating the food the score will be incremented by +1.
3. If the collision with the outer border then the game will over.
4. If the snake eats itself then the game will be over.

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Aryan5464 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by Aryan5464** [comment]
assign in comment

**Comment by kunjgit** [comment]
Hey @Aryan5464 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by Aryan5464** [comment]
Since, I by mistake closed the issue before adding the game, so i reopened the issue and now with this comment I am closing the isuue 
how will i get the GSSOC tag ??
thankyou

**Comment by kunjgit** [comment]
Hey @Aryan5464 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
