### ISSUE TITLE
[Enhancement]: Word_Scramble_Game

### ISSUE THREAD

**Issue by ritik48** [kunjgit/GameZone#1640]
### Is your enhancement request related to a problem? Please describe.➕

Game enhancement

In the the game, when a correct word is guessed, next word is shown only when the user clicks on 'Next Word' button. It should not happen , instead next word should automatically be displayed as soon as the word is guessed right.

![gamezone scramble issue](https://github.com/kunjgit/GameZone/assets/84488726/6124b261-4279-4549-929f-b622f2391ba4)

### Describe the solution you'd like

Solution steps

To solve the above issue: 
I would initialise the game every time when a correct word is chosen. This will give us a fresh word after every correct guess.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @ritik48 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @ritik48 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
