### ISSUE TITLE
[New game]: Avoider Game

### ISSUE THREAD

**Issue by shubhisingh184** [kunjgit/GameZone#1642]
### 🎮 Game Request

Avoider is a vertical box game, where you must avoid other attacking balls of different colors. 
Tech Stack Used : HTML, CSS & JavaScript

### Point down the features

Game points
1. In this game, you have to save your ball by avoiding other attacking balls.
2. You can use right/ left keys to move the move according to the situation.
3. After successfully avoiding each attacking ball, you get one point.
4. Points will get reflected on the scoreboard.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @shubhisingh184 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @shubhisingh184 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
