### ISSUE TITLE
[New game]: Dots and Boxes Game [GSSoC'23]

### ISSUE THREAD

**Issue by Avdhesh-Varshney** [kunjgit/GameZone#1646]
### 🎮 Game Request

Game logic and basic description

- Dots and Boxes is a classic pencil-and-paper game played on a grid of dots.
- Players take turns connecting two adjacent dots with a horizontal or vertical line to form a box.
- When a player completes a box, they put their initial inside it and get an extra turn. The player with the most boxes at the end wins.

### Point down the features

Game points

- The players who have the more boxes will win the game

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Avdhesh-Varshney ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @Avdhesh-Varshney ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
