### ISSUE TITLE
[Enhancement]: Add Instructions alert when game start in Snake game

### ISSUE THREAD

**Issue by MisterMickey** [kunjgit/GameZone#1649]
### Is your enhancement request related to a problem? Please describe.➕

When I was exploring GameZone website games, I found a snake game and when I clicked on it, It redirected  me to the main game and after click on a circle the game automatically started and I had no idea how to play.

I want to add an alert which will tell the user how to play the game.

### Describe the solution you'd like

add an alert on window load which specify how to play the game.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @MisterMickey , You can't have another issue before completing the previous one 😀 
 you already have the following 1 open issues 👀 ! : 
#1647

**Comment by kunjgit** [comment]
Hey @MisterMickey ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by kunjgit** [comment]
Hey @MisterMickey ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)
