### ISSUE TITLE
[New game]: Trivia Card

### ISSUE THREAD

**Issue by shreyaslax** [kunjgit/GameZone#1651]
### 🎮 Game Request

It contains a grid of cards. When you click on the card, you get a question with 2 options. You can't click another card until you answer the question. If the option chosen is right, then the points on the card get added to your score and the background-color of the card  changes from red to green. If its wrong, then no points are added to the score and the background-color of the card stays as red. 

### Point down the features

Game points
Questions with 2 options
Correct answer changes card color from Red to Green and adds points to the final score
Wrong answer doesn't change the color and the card color stays Red and no points are added to the final score

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @shreyaslax ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @shreyaslax ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
