### ISSUE TITLE
[New game]: Math Game

### ISSUE THREAD

**Issue by vishalkumarmahto** [kunjgit/GameZone#1653]
### 🎮 Game Request

This is a game based on simple mathematics.

### Point down the features

On clicking the start button on the screen shown to the user, the user will get a mathematical equation with a blank space. The user has to fill that blank space with appropriate integers or operators. Then a user clicks the submit button after entering their response.
After clicking the submit button, a result screen is shown. On the result screen, we display the result and a restart button.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @vishalkumarmahto ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @vishalkumarmahto ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
