### ISSUE TITLE
[New game]: A new Pong Game

### ISSUE THREAD

**Issue by akankshachanana1** [kunjgit/GameZone#1663]
### 🎮 Game Request

Game logic and basic description
A simple table tennis-like game where players control paddles to hit a ball back and forth across the screen.
It is a classic arcade game where two players control paddles on opposite sides of the screen, trying to hit a ball back and forth. The objective is to score points by making the ball pass the opponent's paddle.
The game starts with the ball positioned in the center of the canvas, and each player's paddle positioned on their respective sides. The players can control their paddles using keyboard inputs or mouse movements.
To control the paddles, the players can move them up or down within the boundaries of the canvas. When the ball collides with a paddle, it changes direction based on the angle of impact.

### Point down the features

Game points
The game keeps track of the score for each player, incrementing it whenever the ball passes the opponent's paddle and goes off the screen. The players can see their scores displayed on the screen.

The game continues until one player reaches a predefined score limit, typically 10 or 15 points. When a player wins, a message is displayed on the screen, and the game can be reset to play again.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @akankshachanana1 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @akankshachanana1! 
We are already having a similar game request in #1608 👀 
Make sure you come up with a cool unique idea 😀 
 Waiting for your new game idea 💗.

**Comment by kunjgit** [comment]
Hey @akankshachanana1 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by akankshachanana1** [comment]
okie
