### ISSUE TITLE
[New game]: A new Sudoku game

### ISSUE THREAD

**Issue by akankshachanana1** [kunjgit/GameZone#1664]
### 🎮 Game Request

Game logic and basic description
Sudoku is a popular logic-based puzzle game that involves filling a 9x9 grid with digits. The objective is to place the numbers 1 to 9 in each cell of the grid so that each column, each row, and each of the nine 3x3 subgrids (also known as boxes or regions) contains all the numbers from 1 to 9 without repetition.

### Point down the features

Game points
 The game starts with a partially filled Sudoku grid where some cells already contain numbers. The initial grid can be generated randomly or retrieved from a pre-defined set of puzzles.
The player interacts with the game by clicking on empty cells and entering the numbers from the keyboard. The input is validated to ensure it adheres to the Sudoku rules. Incorrect entries may be highlighted or shown with an error message.
When the player fills all the cells correctly and satisfies all the Sudoku rules, the game recognizes the puzzle as solved and displays a congratulatory message.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @akankshachanana1! 
We are already having a similar game request in #1608 👀 
Make sure you come up with a cool unique idea 😀 
 Waiting for your new game idea 💗.

**Comment by kunjgit** [comment]
Hey @akankshachanana1 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by kunjgit** [comment]
Hey @akankshachanana1 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)
