### ISSUE TITLE
[New game]: snake-water-gun game [GSSOC'23]

### ISSUE THREAD

**Issue by Nikita06211** [kunjgit/GameZone#1667]
### 🎮 Game Request

I would like to create a simple snake water gun game.

game explanation:
the computer will make a random choice out of snake, water or gun and then the user gets to choose his/her choice.
Out of snake and water-> snake wins
out of snake and gun-> gun wins
out of gun and water-> water wins

### Point down the features

The game will have three buttons , the user will choose any one option and will play against the computer. At the end the score is printed 

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Nikita06211! 
We are already having a similar game request in #1646 👀 
Make sure you come up with a cool unique idea 😀 
 Waiting for your new game idea 💗.

**Comment by kunjgit** [comment]
Hey @Nikita06211 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
