### ISSUE TITLE
[New game]: Simple snake-water-gun game using HTML,CSS,JS

### ISSUE THREAD

**Issue by Nikita06211** [kunjgit/GameZone#1668]
### 🎮 Game Request

i would like to create a simple snake water gun game.
game explanation:
the computer will make a random choice out of snake, water or gun and then the user gets to choose his/her choice.
Out of snake and water-> snake wins
out of snake and gun-> gun wins
out of gun and water-> water wins

### Point down the features

The game will consist of 3 buttons namely , Snake, Water and Gun. the user must choose any one of these and play against the computer. Finally the score will be printed on the screen.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Nikita06211 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @Nikita06211 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
