### ISSUE TITLE
[Enhancement]: Improve Styling of Pagination Buttons Section 

### ISSUE THREAD

**Issue by NarendraKoya999** [kunjgit/GameZone#1671]
### Issue Description
- **In `Pagination section,` Improve Enhancement.**
- **Suppose, When `Click on Next And Previous Buttons`. That selected `Button & It's Pagination Number Background Color` is Not Much Attractive.**

### Describe the solution you'd like

Solution steps:
- **In `Pagination Number Digits`, Replace `Previous Color to Pure white Color`.**
- **It happens Only on Either Click on selected `Pagination Number` OR Click on `Previous or Next Buttons`.** 
- **` It's More attractive More Than Previous Color.`**

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @NarendraKoya999 , You can't have another issue before completing the previous one 😀 
 you already have the following 1 open issues 👀 ! : 
#1438

**Comment by kunjgit** [comment]
Hey @NarendraKoya999 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by kunjgit** [comment]
Hey @NarendraKoya999 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)
