### ISSUE TITLE
[Enhancement]: Improve Space between Games Projects List and Pagination Section

### ISSUE THREAD

**Issue by NarendraKoya999** [kunjgit/GameZone#1672]
### Issue Description:
- **In `Gamezone Website`, `Games Projects List `and ` Pagination Section` have Too Close To each Other.** 

### Screenshot
![gamezone-1](https://github.com/kunjgit/GameZone/assets/84512164/53d25f14-5ccc-4932-8b48-7e1cd5267d6c)

### Describe the solution you'd like

Solution steps:
- **Observing Above Sharing Screenshot.` Proper Margin is Not Set to Gamezone Projects List Section and Pagination Section.`**
- **I want to `Suggest Add and Modify Either Margin Top OR Margin Bottom Related to these above Sections.`**

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @NarendraKoya999 , You can't have another issue before completing the previous one 😀 
 you already have the following 1 open issues 👀 ! : 
#1438

**Comment by kunjgit** [comment]
Hey @NarendraKoya999 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by kunjgit** [comment]
Hey @NarendraKoya999 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)
