### ISSUE TITLE
[Enhancement]: Improve Advance Design for Pagination Section

### ISSUE THREAD

**Issue by NarendraKoya999** [kunjgit/GameZone#1673]
### Issue Description:
- **In` Gamezone Website,` Click on `Selected Pagination Number using Previous , Next OR Selected Pagination Number.`**
- **It's only addicted to `Bottom of The Pagination `Section.**

### Screenshot
![gamezone-2](https://github.com/kunjgit/GameZone/assets/84512164/98823ff3-79c0-4617-97fc-6610069ca682)

### Describe the solution you'd like

Solution steps:
- **`My Feature Design is When Click on Previous, Next OR Selected Pagination Number.`**
- **`Then , Particular Selected Pagination Number Page Directly Go To The Top Of The Games Projects List.`**

> Example: 

**Below Screenshot (I can Only Selected on Pagination Number 4 )**
![gamezone-3](https://github.com/kunjgit/GameZone/assets/84512164/34709778-8282-4a01-8407-d0eb6890507d)

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @NarendraKoya999 , You can't have another issue before completing the previous one 😀 
 you already have the following 1 open issues 👀 ! : 
#1438

**Comment by kunjgit** [comment]
Hey @NarendraKoya999 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by kunjgit** [comment]
Hey @NarendraKoya999 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)
