### ISSUE TITLE
[New game]: Asteroids

### ISSUE THREAD

**Issue by akankshachanana1** [kunjgit/GameZone#1682]
### 🎮 Game Request

Game logic and basic description
"Asteroids" is a arcade-style game where the player controls a spaceship and must navigate through a field of asteroids. The objective of the game is to survive as long as possible and earn a high score by destroying the asteroids while avoiding collisions.

The player controls a spaceship using keyboard inputs. The arrow keys are commonly used to rotate the ship and control its thrust. The spacebar is used to fire bullets.The game screen is filled with large and small asteroids that move in random directions.
If the ship collides with an asteroid, it is destroyed, and the player loses a life. The game usually provides the player with a limited number of lives. Collisions with asteroids also result in the destruction of the asteroid.

### Point down the features

Game points
The player can shoot bullets from the ship to destroy asteroids. When a bullet collides with an asteroid, both objects are destroyed, and the player earns points. Larger asteroids often break apart into smaller asteroids when hit, increasing the difficulty.
The player earns points for destroying asteroids. The score typically increases based on the size of the destroyed asteroid. The game may also reward bonus points for clearing all asteroids from the screen or achieving certain milestones.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @akankshachanana1 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @akankshachanana1 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
