### ISSUE TITLE
[New game]: The Boxing Game

### ISSUE THREAD

**Issue by PranjalSrivastava01** [kunjgit/GameZone#1684]
### 🎮 Game Request

Game logic and basic description: It is an exciting two-player boxing game where players step into the battle as Player 1 and Player 2. Each player possesses unique powers of attacking and healing, allowing them to engage in thrilling battles. The objective is to defeat the opponent by strategically combining punches and healing abilities.

### Point down the features

Game points:
Controls: Player 1 uses the keys "Q" to attack and "A" to heal, while Player 2 uses the keys "P" to attack and "L" to heal.
Attacking: Players can unleash powerful punches by pressing their respective attack keys. Well-timed attacks will deal more damage to the opponent.
Healing: When players feel the need to recover, they can use their healing powers by pressing the corresponding healing key. This action replenishes a portion of their HP.
Strategy: Players must carefully choose when to attack and when to heal, as both actions consume valuable resources. Balancing offense and defense is crucial for success.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @PranjalSrivastava01! 
We are already having a similar game request in #1679 👀 
Make sure you come up with a cool unique idea 😀 
 Waiting for your new game idea 💗.

**Comment by kunjgit** [comment]
Hey @PranjalSrivastava01 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by PranjalSrivastava01** [comment]
> Hey @PranjalSrivastava01! We are already having a similar game request in #1679 👀 Make sure you come up with a cool unique idea 😀 Waiting for your new game idea 💗.

hi :) The game in the issue #1679 is not similar to this , can you check once again?,thankyou:)
