### ISSUE TITLE
[New game]: Sliding Puzzle Game

### ISSUE THREAD

**Issue by adjascently** [kunjgit/GameZone#169]
### 🎮 Game Request

Game logic and basic description
The aim of this game is to use HTML, CSS and Javascript to create an interactive sliding puzzle.

### Point down the features

- Creating a grid-based puzzle board with movable puzzle pieces. Each piece should have a unique identifier and be initially jumbled.

-  Implementing drag and drop functionality to allow players to move puzzle pieces across the board. Users should be able to click and drag a piece, then drop it into a valid empty space on the board.

- Ensuring that the game is responsive and works well on various screen sizes, including desktop, tablets, and mobile devices.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @adjascently 👋!
 
  @kunjgit here, 
 We have this annoucement to make 📢!! 
 We have updated our README 🚀 
 Make sure you follow proper guideline to raise your next issues !! 
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG) if you haven't 😇 
  Thank you 💗!

**Comment by kunjgit** [comment]
Hello @adjascently, Time's Uppp!⏰ 
 Sorry for closing your issue! 
 But it's more than a week since we haven't received anything from your side 😢 . 
 Come up with new ideas, create a new issue and make sure you finish it within a week! 🔥 
 All the best! 🚀 
 Happy Hacking! 💗

**Comment by kunjgit** [comment]
Hey @adjascently ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
