### ISSUE TITLE
[New game]: Fruit Catching

### ISSUE THREAD

**Issue by Darkrider0007** [kunjgit/GameZone#1690]
### 🎮 Game Request

Game logic and basic description
This is a single-player game made of HTML CSS and javascript. The basic idea is the player uses A and D or <- and -> keys to move the bucket to catch the fruit. If they miss the game is over and the point is displayed. 

### Point down the features

Game points
The player catches as many fruits as they are rewarded with the same amount of points. 

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Darkrider0007 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
