### ISSUE TITLE
[Bug]: Preview 'Eye Button' is not showing up

### ISSUE THREAD

**Issue by kartikjoshi267** [kunjgit/GameZone#1691]
### Give a brief about the bug ✍️

If I hover over any project tile, the eye button to preview the game does not appear instead the alternate text `Eye` appears.
Attaching the Screenshot of the same:
![image](https://github.com/kunjgit/GameZone/assets/96565730/2f1555b7-9f2f-4b26-aeb4-021933f39bad)

### What is the expected behavior? 🤔

When hovering over the projects, the Preview button should appear in place of the alternate text!

### Provide step by step information reproduce the bug 📄

- Hover over any project tile.
- The eye button to preview the game does not appear instead the text `Eye` appears.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @kartikjoshi267 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)
