### ISSUE TITLE
[New game]: Crystals Collector

### ISSUE THREAD

**Issue by Vedansh-777** [kunjgit/GameZone#1697]
### 🎮 Game Request

Crystals Collector is a fun and interactive game where players collect crystals to earn points. The objective of the game is to gather as many crystals as possible within a given time or set of turns. The game usually features colorful and visually appealing crystals that players can click or interact with to collect.

### Point down the features

Collect colorful crystals of varying shapes and values.
Earn points based on the crystals collected.
Random placement of crystals for added challenge.
Track and display the player's score.
Leaderboards or high score tables.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Vedansh-777 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
