### ISSUE TITLE
[New game]: tambola/bingo

### ISSUE THREAD

**Issue by barkhaaroraa** [kunjgit/GameZone#1704]
### 🎮 Game Request

tambola/bingo is a very popular game played in multiple countries in which each player is given a ticket with x random numbers, theres 1 person called the 'caller' who is supposed to say random numbers in each round. every player who has the number that the caller has announced is supposed to strike that number off their tickets. the first person who strikes all of his numbers down wins. my code will do the same and instead turn it into a virtual game.

### Point down the features

Game points
1. one feature will be dedicated to generating tickets for each player with x digits
2. and one feature will be the "caller" and generate random numbers in each round
3. there will be another feature that would record the score board of each player

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @barkhaaroraa ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hello @barkhaaroraa, Time's Uppp!⏰ 
 Sorry for closing your issue! 
 But it's more than a week since we haven't received anything from your side 😢 . 
 Come up with new ideas, create a new issue and make sure you finish it within a week! 🔥 
 All the best! 🚀 
 Happy Hacking! 💗

**Comment by kunjgit** [comment]
Hey @barkhaaroraa ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
