### ISSUE TITLE
Enhance the ui of the website

### ISSUE THREAD

**Issue by Pragati-3003** [kunjgit/GameZone#1705]
### Give a brief about the bug ✍️

i would like to change the UI of the website to make it more attractive .

### What is the expected behavior? 🤔

Description
![Screenshot 2023-06-20 142802](https://github.com/kunjgit/GameZone/assets/132778037/f3e63dc3-68a7-40f3-a31a-1f3a528cfb31)

### Provide step by step information reproduce the bug 📄

I would like to adjust the margin padding .
Also would like to enhance the ui of the cards.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Pragati-3003 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @Pragati-3003! 🙂 
 It seems like you are not following proper guidelines !! 👀 
 Read documentation properly !!🙏 
 If you have any queries reach out to us on [Discord🕹️](https://discord.gg/fgwk4XZfxG) .

**Comment by kunjgit** [comment]
Hey @Pragati-3003 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
