### ISSUE TITLE
[New game]:  Tetris

### ISSUE THREAD

**Issue by lmalkam** [kunjgit/GameZone#1706]
### 🎮 Game Request

"TetraFall: The Block Stacking Challenge" is an addictive and fast-paced puzzle game inspired by the classic game of Tetris. In this game, players must strategically arrange falling blocks to create complete horizontal lines and prevent the blocks from stacking up to the top. With its intuitive gameplay and increasing difficulty, TetraFall offers hours of fun and challenges for players of all ages.

### Point down the features

The game will be created using HTML,CSS and javascript
Blocks will be falling from the top and the whole game will work as a standard Tetris falling block game.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @lmalkam ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
