### ISSUE TITLE
[New game]: Rat in a Maze

### ISSUE THREAD

**Issue by lmalkam** [kunjgit/GameZone#1710]
### 🎮 Game Request

"Maze Quest: The Rat's Adventure" is an exciting and challenging puzzle game that puts players in the paws of a clever and agile rat. The game takes place in a complex maze filled with obstacles, traps, and tempting rewards. As the rat, players must navigate through the maze, overcoming obstacles, avoiding dangers, and collecting valuable cheese. With its immersive gameplay and mind-bending puzzles, Maze Quest offers an engaging experience for players of all ages.

### Point down the features

I will create this game using HTML CSS and javascript
we have to navigate rat from start to end safely using controls

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @lmalkam , You can't have another issue before completing the previous one 😀 
 you already have the following 1 open issues 👀 ! : 
#1706

**Comment by kunjgit** [comment]
Hey @lmalkam ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by kunjgit** [comment]
Hey @lmalkam ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)
