### ISSUE TITLE
Improve UI

### ISSUE THREAD

**Issue by devWonderkind** [kunjgit/GameZone#1712]
heyy @kunjgit I want to add Light/Dark mode icon instead of text.

![LD](https://github.com/kunjgit/GameZone/assets/110322061/0863a980-93a2-4f8f-995f-263f70c4b0e1)

Please assign me this issue under GSSoC'23.

**Comment by kunjgit** [comment]
Hey @devWonderkind ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @devWonderkind! 🙂 
 It seems like you are not following proper guidelines !! 👀 
 Read documentation properly !!🙏 
 If you have any queries reach out to us on [Discord🕹️](https://discord.gg/fgwk4XZfxG) .

**Comment by kunjgit** [comment]
Hey @devWonderkind ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
