### ISSUE TITLE
[Bug]: Dice Showdown Game is not working!

### ISSUE THREAD

**Issue by sabhisharma-ise** [kunjgit/GameZone#1713]
### Give a brief about the bug ✍️

The Dice Showdown game added in the project is not working as it is supposed to be. 
I checked the link and found that it's just an image of the game but not the actual game.

Check the screenshot below:-
![image](https://github.com/kunjgit/GameZone/assets/100849696/244405c5-1ee7-459b-af92-4912ba92ccd8)

### What is the expected behavior? 🤔

Addition of working game the project will solve this issue!

### Provide step by step information reproduce the bug 📄

I would like to add the Dice game in the project, as the existing game does not works and links to an image, but not the game!

Can you please assign me this issue!

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @sabhisharma-ise ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @sabhisharma-ise ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
