### ISSUE TITLE
[Bug]: Interactive Quizzing game is not working!

### ISSUE THREAD

**Issue by sabhisharma-ise** [kunjgit/GameZone#1715]
### Give a brief about the bug ✍️

The Interactive Quizzing game which is added to this project does not works as it should be!

Check the Video Below:-

https://github.com/kunjgit/GameZone/assets/100849696/b3ff607f-19d4-4b9b-a96a-eb54c2dd9106

### What is the expected behavior? 🤔

The expected behavior would be that the user would be able to play the quiz without any error/alerts (which says the quiz is not ready yet!)

### Provide step by step information reproduce the bug 📄

I would love to add a Quiz Game in the Website, see the quiz working below

https://github.com/kunjgit/GameZone/assets/100849696/07ab4780-776d-4f6e-aebd-69bd46a4da23

Kindly Assign me this issue!

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @sabhisharma-ise , You can't have another issue before completing the previous one 😀 
 you already have the following 1 open issues 👀 ! : 
#1713

**Comment by kunjgit** [comment]
Hey @sabhisharma-ise ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by kunjgit** [comment]
Hey @sabhisharma-ise ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)
