### ISSUE TITLE
Pagination Redesigning 

### ISSUE THREAD

**Issue by Akanksha-202** [kunjgit/GameZone#1716]
To redesign the current pagination style, which is looking quite messy and taking up much more space.
![image](https://github.com/kunjgit/GameZone/assets/100708686/2c20a58c-a374-49b1-a418-1e2e696c74e0)

Below is an example which can further be styled acc to the website's UI.
![image](https://github.com/kunjgit/GameZone/assets/100708686/e95ca675-0ec6-4058-9bb8-f3a7a58b310e)

Please assign this issue to me under GSSoc'23 label :)

**Comment by kunjgit** [comment]
Hey @Akanksha-202! 🙂 
 It seems like you are not following proper guidelines !! 👀 
 Read documentation properly !!🙏 
 If you have any queries reach out to us on [Discord🕹️](https://discord.gg/fgwk4XZfxG) .

**Comment by kunjgit** [comment]
Hey @Akanksha-202 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @Akanksha-202 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by Akanksha-202** [comment]
Hey ! @kunjgit  
Is it because of not selecting a template?
