### ISSUE TITLE
[Bug]: Pagination styling is taking up quite a lot space

### ISSUE THREAD

**Issue by Akanksha-202** [kunjgit/GameZone#1719]
### Give a brief about the bug ✍️

Description:
![image](https://github.com/kunjgit/GameZone/assets/100708686/c167dbf2-862d-409d-8f2d-8b9b77405281)
![image](https://github.com/kunjgit/GameZone/assets/100708686/d56ed9c5-5ef8-45d7-9ddd-2a85697d503b)

This type of pagination styling is taking up a lot of space of the screen and also not looking that great and appealing to the eye.

### What is the expected behavior? 🤔

![Screenshot 2023-06-20 162157](https://github.com/kunjgit/GameZone/assets/100708686/639da5d0-eac5-4f5f-a514-0a5886ecada3)
An example of what we can instead use. We can further add colors and styles according to GameZone's UI. This will look much better and presentable.

### Provide step by step information reproduce the bug 📄

By fixing the styling of the Paginng component, this can be achieved! And this will beautify the website further.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Akanksha-202 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @Akanksha-202 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
