### ISSUE TITLE
[New game]: The Fearsome Three story based Game

### ISSUE THREAD

**Issue by Kalivarapubindusree** [kunjgit/GameZone#1720]
### 🎮 Game Request

This is an small Story Based game

### Point down the features

No points

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Kalivarapubindusree , You can't have another issue before completing the previous one 😀 
 you already have the following 1 open issues 👀 ! : 
#1679

**Comment by kunjgit** [comment]
Hey @Kalivarapubindusree ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
