### ISSUE TITLE
[New game]: 3x3 Puzzle Game

### ISSUE THREAD

**Issue by VSatwika** [kunjgit/GameZone#1723]
### 🎮 Game Request

 - I would like to contribute a 3x3 puzzle game. 
 - The game involves arranging tiles in the correct order within a 3x3 grid. 
 - This game can provide a fun and engaging experience for users.
 - Could this be assigned to me under GSSoC'23?

### Point down the features

 - Grid-based Gameplay: The game presents a 3x3 grid where players can arrange tiles.

 - Tile Shuffling: At the start of each game, the tiles are shuffled randomly to provide a new puzzle arrangement for the player to 
    solve.

 - Move Tracking: The game keeps track of the number of moves made by the player, allowing them to challenge themselves to complete the puzzle in the fewest possible moves.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @VSatwika! 
We are already having a similar game request in #1608 👀 
Make sure you come up with a cool unique idea 😀 
 Waiting for your new game idea 💗.

**Comment by kunjgit** [comment]
Hey @VSatwika ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
