### ISSUE TITLE
[New game]: JavaScript-based Quiz Game

### ISSUE THREAD

**Issue by sabhisharma-ise** [kunjgit/GameZone#1725]
### 🎮 Game Request

The game is based on answering some questions, which have 4 options for each question.
It is made using HTML, CSS, and JS!

### Point down the features

The user can start the game and at the end view their Score as well!

https://github.com/kunjgit/GameZone/assets/100849696/7c5e4983-0a0c-4ac6-94fb-e63384027c4b

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @sabhisharma-ise , You can't have another issue before completing the previous one 😀 
 you already have the following 1 open issues 👀 ! : 
#1713

**Comment by kunjgit** [comment]
Hey @sabhisharma-ise ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by kunjgit** [comment]
Hey @sabhisharma-ise! 
We are already having a similar game request in #981 👀 
Make sure you come up with a cool unique idea 😀 
 Waiting for your new game idea 💗.
