### ISSUE TITLE
[New game]: Doodle_Draw

### ISSUE THREAD

**Issue by Sheetal-05** [kunjgit/GameZone#1726]
### 🎮 Game Request

Game logic and basic description
The game will be implemented using Html, CSS, and Javascript.
Introduction:
Doodle Draw will unleash your creativity and create pixelated artwork on a virtual canvas. With various customization options and features, you can paint, draw, and experiment to your heart's content.
Let your imagination soar as you bring your ideas to life, one pixel at a time.

Game Logic:

Drawing: Use your mouse to navigate the grid and click on individual cells to paint them with your chosen color. The brush size determines the area covered by each click.

Clearing: To remove the entire drawing and start fresh, click the "Clear" button. This will erase all painted cells on the grid.

Resetting: If you want to restore the game to its default settings, click the "Reset" button. This will reset the colors, background, grid size, and other customizable elements.

Random and Rainbow: Toggling the "Random" or "Rainbow" buttons will generate random colors for the pixels. Each click will result in a different color, creating vibrant and lively artwork.

Toggle Transition: By enabling or disabling the "Toggle" option, you can gradually change the color of cells from black to white or vice versa. This can add a dynamic and evolving touch to your creations.

Eraser: Switch to the eraser tool to remove the color from specific cells. Click on the cells you want to clear, and they will return to their default color.

Fill Tool: Select the fill tool and click on any cell to fill a specified area with the chosen color. This makes it easy to create solid blocks or sections of color within your artwork.

Grid Size: Adjust the grid size to alter your artwork's resolution. A larger grid allows for more detail, while a smaller grid creates a pixelated effect.

Pencil and Background Colors: Customize the color of your pencil and the background to match your artistic vision. Experiment with different combinations to achieve the desired aesthetic.

Delete Grid Lines: If you wish to remove specific grid lines from your artwork, click the "Delete Grid Lines" button. This can help create unique shapes and patterns within your design.

There are additional features like undo/redo, save/load, sharing, gridlock, and zoom to enhance your creative experience. Have fun exploring the possibilities and enjoy the artistic journey with the Doodle Draw game!

### Point down the features

Game points

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Sheetal-05 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
