### ISSUE TITLE
[Enhancement]: Whack a Mole

### ISSUE THREAD

**Issue by ManavMalhotra** [kunjgit/GameZone#1727]
### Is your enhancement request related to a problem? Please describe.➕

The UI/UX of the game could be improved. Additionally, it would be helpful to have a sound effect and a different image when the mole is hit to indicate that the player has scored.

### Describe the solution you'd like

1. Improve the color scheme of the web page to make it more visually appealing.
2. Enhance the mole containers to make them more interactive and engaging.
3. Add sound effects and change the image when the mole is hit to provide better feedback to the player.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @ManavMalhotra ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hello @ManavMalhotra, Time's Uppp!⏰ 
 Sorry for closing your issue! 
 But it's more than a week since we haven't received anything from your side 😢 . 
 Come up with new ideas, create a new issue and make sure you finish it within a week! 🔥 
 All the best! 🚀 
 Happy Hacking! 💗

**Comment by kunjgit** [comment]
Hey @ManavMalhotra ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
