### ISSUE TITLE
[New game]: Add Pickle Rick Maze Game

### ISSUE THREAD

**Issue by Prajwal0225** [kunjgit/GameZone#1728]
### 🎮 Game Request

The game consists of a maze that the player needs to navigate to reach the goal. The maze is randomly generated using a depth-first search algorithm. The player controls a character and can move in four directions: north, south, east, and west. The goal is to reach the end of the maze, represented by the Pickle Rick character.

The game interface includes a menu section where the player can choose the difficulty level of the maze. There are four difficulty options: Easy, Medium, Hard, and Extreme. The player can select the desired difficulty by choosing the corresponding option from the dropdown menu.

Once the player selects the difficulty level and clicks the "Start" button, the maze is generated, and the player can begin navigating through it. The maze is displayed on the screen using a canvas element.

During the game, the player can make moves by swiping or pressing the arrow keys on the keyboard. The player's progress is shown on the screen as the number of steps taken.

When the player successfully reaches the end of the maze, a "Congratulations!" message is displayed, along with the number of steps taken to complete the maze. The player can close the message by clicking the "Cool!" button.

The game interface features a visually appealing background gradient that changes colors over time. The colors include shades of red, pink, blue, and green, creating an engaging and dynamic visual experience.

Overall, the Pickle Rick Maze Game provides an entertaining and challenging experience for players to test their maze-solving skills and reach the goal within the shortest number of steps.

### Point down the features

https://github.com/kunjgit/GameZone/assets/103810119/4fe79667-38a7-4380-8604-6cf2532e519d

Level medium ⤵️ 
![medium](https://github.com/kunjgit/GameZone/assets/103810119/3e951fe7-5087-4696-ad2b-b9cad62acccd)

Level Hard ⤵️ 
![hard level](https://github.com/kunjgit/GameZone/assets/103810119/1460c233-a169-4249-9d84-c0d0a2d9b7f6)

Level Extreme ⤵️ 
![Extream level](https://github.com/kunjgit/GameZone/assets/103810119/39528298-ff91-4431-b09e-4ec2cf86f9ee)

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Prajwal0225 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @Prajwal0225 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
