### ISSUE TITLE
[New game]: Target_Torrent

### ISSUE THREAD

**Issue by Sheetal-05** [kunjgit/GameZone#1729]
### 🎮 Game Request

Game logic and basic description

The game is implemented using Html, CSS, and javascript

game logic: 
To earn 750 points, you have 45 seconds.  
Use the arrow or WASD keys to move around, and the space bar to fire your missile. 
One projectile may only be sent at a time. 
Per hit, you receive about 35 points. 
The player will remain on the right side of the boundary while the opposition will remain to its left. 

### Point down the features

Game points

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Sheetal-05 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
