### ISSUE TITLE
[New game]: Guess the Color Game

### ISSUE THREAD

**Issue by vidhimakani74** [kunjgit/GameZone#173]
### 🎮 Game Request

Game logic and basic description
This is a game where you have given RGB value of color and bellow there are six color box. You have to guess that color box from given RGB value.

### Point down the features

Game points:
if you choose wrong color then this color box id disappeared
score given as per clicks
new game option

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @vidhimakani74 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by vidhimakani74** [comment]
thank you @kunjgit for assigning this issue to me.

**Comment by kunjgit** [comment]
Hey @vidhimakani74 👋!
 
  @kunjgit here, 
 We have this annoucement to make 📢!! 
 We have updated our README 🚀 
 Make sure you follow proper guideline to raise your next issues !! 
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG) if you haven't 😇 
  Thank you 💗!

**Comment by kunjgit** [comment]
Hey !! we are already having this game hope you come up with unique idea

**Comment by kunjgit** [comment]
Hey @vidhimakani74 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
