### ISSUE TITLE
[New game]: Guess The Movie By Emojis 

### ISSUE THREAD

**Issue by PR1YAM9** [kunjgit/GameZone#1733]
### 🎮 Game Request

Game logic and basic description: In this addictive game, your task is to decipher a secret word by carefully examining a sequence of emojis. These expressive pictographs hold the key to unlocking the hidden word, but it's up to you to unravel their cryptic messages. From common objects to famous places, movie titles, and even idioms, the emojis will encompass a wide range of subjects, ensuring an exciting and diverse gameplay experience.

### Point down the features

Game points: 1. Diverse Emoji Collection: Encounter a wide variety of emojis, ranging from common and popular ones to more obscure and challenging combinations.
2. Hint System: Stuck on a particularly challenging level? Utilize the hint system to get clues and boost your chances of guessing the word correctly.
3. Educational and Fun: Enhance your emoji recognition skills while having a great time guessing words and phrases associated with the emojis.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @PR1YAM9 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @PR1YAM9 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
