### ISSUE TITLE
[New game]: Hangman Game

### ISSUE THREAD

**Issue by slayerrr12** [kunjgit/GameZone#1735]
### 🎮 Game Request

Game logic and basic description:

**Setup**: The game begins by selecting a word or phrase that the player needs to guess. The chosen word is typically hidden from the player and represented by a series of blank spaces or underscores, with each space representing a letter in the word.

**Guessing Process**: The player starts guessing letters from the alphabet one at a time. If the guessed letter is present in the word, it is revealed in its corresponding position(s) within the hidden word. If the letter appears multiple times in the word, all occurrences are revealed.

**Incorrect Guesses**: If the guessed letter is not present in the word, it is considered an incorrect guess. The game keeps track of the number of incorrect guesses made by the player.

Hangman Drawing: For each incorrect guess, a portion of a "hangman" figure is drawn. The figure is typically drawn incrementally, adding body parts like the head, body, arms, and legs as the player makes more incorrect guesses. The hangman drawing represents the player's progress and serves as a visual indicator of how many incorrect guesses they have made.

**Win Condition**: The player wins the game if they successfully guess all the letters in the word before the entire hangman figure is completed. In this case, they have successfully "saved" the hangman.

**Lose Condition**: The player loses the game if they exceed a certain number of allowed incorrect guesses (usually represented by the completion of the hangman figure). In this case, the hangman is "hanged" and the player loses.

### Point down the features

Game 

Word Selection: A word or phrase is selected as the target word for the player to guess. This can be chosen randomly from a predetermined list or based on a specific theme or category.

Hidden Word Display: The target word is initially hidden from the player and represented by blank spaces or underscores. The number of letters in the word is typically indicated.

Letter Guessing: The player guesses individual letters of the target word by selecting them from the alphabet. The game validates the guess and checks if the letter is present in the target word.

Correct Guesses: If the player guesses a letter that is present in the target word, the game reveals the letter at its corresponding position(s) within the hidden word.

Incorrect Guesses: If the player guesses a letter that is not present in the target word, the game registers it as an incorrect guess and keeps track of the number of incorrect guesses made.

Hangman Figure: The game visually represents the player's progress and incorrect guesses through the drawing of a hangman figure. The figure is typically drawn incrementally, adding body parts for each incorrect guess.

Win Condition: The player wins the game if they successfully guess all the letters in the target word before reaching the maximum allowed incorrect guesses. Winning usually results in displaying a victory message and revealing the complete word.

Lose Condition: The player loses the game if they reach the maximum allowed incorrect guesses before guessing all the letters in the target word. Losing usually results in displaying a defeat message and revealing the complete word.

Scorekeeping: Some versions of the game keep track of the player's score based on factors like the number of correct guesses, time taken to complete the game, or difficulty level.

Difficulty Levels: The game may offer different difficulty levels, such as easy, medium, and hard. These levels can influence factors like the length of the target word, the maximum allowed incorrect guesses, or the complexity of the words used.

Hint System: Some versions of the game provide hints to the player to help them guess the target word. Hints can take the form of revealing a single letter, providing a category or topic related to the word, or offering clues about the word's meaning.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @slayerrr12 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hello @slayerrr12, Time's Uppp!⏰ 
 Sorry for closing your issue! 
 But it's more than a week since we haven't received anything from your side 😢 . 
 Come up with new ideas, create a new issue and make sure you finish it within a week! 🔥 
 All the best! 🚀 
 Happy Hacking! 💗

**Comment by kunjgit** [comment]
Hey @slayerrr12 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
