### ISSUE TITLE
[New game]:Anaconda  (a snake game )

### ISSUE THREAD

**Issue by Adityamishra9719** [kunjgit/GameZone#1738]
### 🎮 Game Request

It is a anaconda the snake game , there are food in betwewn the path of anaconda and you anaconda eats it and its length increases accordingly.
It  is made using html, css and javascript .

the ui of the game is as shown below.

![Screenshot 2023-06-20 200425](https://github.com/kunjgit/GameZone/assets/105539123/ccea0601-bc2a-4cd6-b89d-d054a2d49078)

### Point down the features

it consist of a score bored , game over message and a background music

### Select program in which you are contributing

GSSoC23, Other

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Adityamishra9719 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @Adityamishra9719 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
