### ISSUE TITLE
Add the prettier linter workflow 

### ISSUE THREAD

**Issue by metabiswadeep** [kunjgit/GameZone#1744]
Add the prettier linter to ensure proper and uniform linting of the codebase. As a project with multiple users contributing to it, it is essential to maintain a proper linting style to ensure better code readability by users. An excellent way to do this is by automatic linting checks using the prettier linter in GitHub actions.

I would like to work on this as a part of GSSoC 23.

**Comment by kunjgit** [comment]
Hey @metabiswadeep ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @metabiswadeep! 🙂 
 It seems like you are not following proper guidelines !! 👀 
 Read documentation properly !!🙏 
 If you have any queries reach out to us on [Discord🕹️](https://discord.gg/fgwk4XZfxG) .

**Comment by kunjgit** [comment]
Hey @metabiswadeep ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by metabiswadeep** [comment]
@kunjgit Can you check this out please. I am assuming the closing of this issue is due to a GitHub action. But since my issue did not match any of the templates mentioned, I chose to go with the no template option.
