### ISSUE TITLE
[New game]: tic tac toe

### ISSUE THREAD

**Issue by kumar11jr** [kunjgit/GameZone#1745]
### 🎮 Game Request

Game logic and basic description
In the game, Player-1 starts playing the game and both players make their moves in consecutive turns. The player who makes a straight 3-block chain wins the game. This game is built on the front-end using simple logic and validation checks only.

### Point down the features

Game point and rules
html file: This file contains the structure of the project.
css file: This file contains the styling of the application.
js file: This file contains the logic of the game.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @kumar11jr ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
