### ISSUE TITLE
[Enhancement]: Word_Guessing_Game

### ISSUE THREAD

**Issue by ritik48** [kunjgit/GameZone#1747]
### Is your enhancement request related to a problem? Please describe.➕

Game enhancement
In the the game, when a correct word is guessed, next word is shown only when the user clicks on 'Next Word' button. It should not happen , instead next word should automatically be displayed as soon as the word is guessed right.

![word guess issue](https://github.com/kunjgit/GameZone/assets/84488726/f1e5cd97-e447-4d92-901f-3d719200f40f)

### Describe the solution you'd like

Solution steps

To solve the above issue:
I would initialise the game every time when a correct word is chosen. This will give us a fresh word after every correct guess.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by ritik48** [comment]
\assign

**Comment by kunjgit** [comment]
Hey @ritik48 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
