### ISSUE TITLE
[Enhancement]: Page Number Section Design Improvement

### ISSUE THREAD

**Issue by iamRabia-N** [kunjgit/GameZone#1752]
### Is your enhancement request related to a problem? Please describe.➕

No. It's an enhancement in the existing design.

### Describe the solution you'd like

Working on the styling of this section, I can make it look even better.
**Current Design**

![gameworld-issue2 (2)](https://github.com/kunjgit/GameZone/assets/115794049/ce877a8f-54f5-4551-958e-259a4c13873d)

**Expected Updated Design**
![gameworld-issue2 (1)](https://github.com/kunjgit/GameZone/assets/115794049/beeb7210-9e24-495b-b6c4-081611eac25d)

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @iamRabia-N , You can't have another issue before completing the previous one 😀 
 you already have the following 1 open issues 👀 ! : 
#1740

**Comment by kunjgit** [comment]
Hey @iamRabia-N ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by iamRabia-N** [comment]
> Hey @iamRabia-N , You can't have another issue before completing the previous one 😀 you already have the following 1 open issues 👀 ! : #1740

Oh. Kindly review it so that I can work on this one.
