### ISSUE TITLE
[Enhancement]: Color Blast Game

### ISSUE THREAD

**Issue by lakhan06** [kunjgit/GameZone#1755]
### Is your enhancement request related to a problem? Please describe.➕

In this game player have to move a white box from left to right and need to shoot down the boxes of color above.
He need to be procted its self from the colors droping from above and if he heat by color 3 times then game over.
![image](https://github.com/kunjgit/GameZone/assets/119161467/a9ce3a54-ab5a-47c7-bc28-fcc646e9ffe5)

https://github.com/kunjgit/GameZone/assets/119161467/275ac6ed-ce07-46b9-895d-c6bacd33158b

### Describe the solution you'd like

- 
- It is a single player game.
- Player can move its boxes from left to right using 'A' and "D" or left and right arrow key
- Shooting can be done using space button.
- Fixes https://github.com/kunjgit/GameZone/issues/1681

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @lakhan06 , You can't have another issue before completing the previous one 😀 
 you already have the following 1 open issues 👀 ! : 
#1681

**Comment by kunjgit** [comment]
Hey @lakhan06 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
