### ISSUE TITLE
[New game]:Adding Color Blast Game

### ISSUE THREAD

**Issue by lakhan06** [kunjgit/GameZone#1759]
### 🎮 Game Request

In this game player have to move a white box from left to right and need to shoot down the boxes of color above.
He need to be procted its self from the colors droping from above and if he heat by color 3 times then game over.
![image](https://github.com/kunjgit/GameZone/assets/119161467/d1e40c77-6dda-4a44-9715-edff25092751)

### Point down the features

- It is a single player game.
- Player can move its boxes from left to right using 'A' and "D" or left and right arrow key
- Shooting can be done using space button.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @lakhan06 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @lakhan06 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
