### ISSUE TITLE
[New game]: Adventure Guy

### ISSUE THREAD

**Issue by its-me-abhishek** [kunjgit/GameZone#176]
### 🎮 Game Request

Game logic and basic description:
It will be a platform based game like super mario or adventure island, and would be playable by the keyboard.

### Point down the features

Game points
-Platformer based games for nostalgic vibes
-Various Levels that can be accessed on completing previous ones

### Select program in which you are contributing
GSSoC'23
### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @its-me-abhishek ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by its-me-abhishek** [comment]
Please add the GSSoC label to the issue. Thanks

**Comment by kunjgit** [comment]
Hey @its-me-abhishek 👋!
 
  @kunjgit here, 
 We have this annoucement to make 📢!! 
 We have updated our README 🚀 
 Make sure you follow proper guideline to raise your next issues !! 
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG) if you haven't 😇 
  Thank you 💗!

**Comment by kunjgit** [comment]
Hey @its-me-abhishek ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
