### ISSUE TITLE
[New game]: Bulls eye game

### ISSUE THREAD

**Issue by saikiranreddy201** [kunjgit/GameZone#1761]
### 🎮 Game Request

This is a basic archery game using SVG and animation. It allows the user to drag and release an arrow, simulating shooting at a target. The position and angle of the arrow are calculated based on the mouse movement, and the bow is animated accordingly. The code detects collisions between the arrow and the target using line segment intersection.

### Point down the features

It has a bow and arrow and a target
If the user misses the target then it shows its a "miss". 
if the user hits the board other than the center part of the target, it shows "hit".
If the user hits at the middle circle of the target then it's a bullseye.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @saikiranreddy201 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @saikiranreddy201 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
