### ISSUE TITLE
[New game]: Escape Room 

### ISSUE THREAD

**Issue by saikiranreddy201** [kunjgit/GameZone#1764]
### 🎮 Game Request

This escape room game utilizes only CSS and HTML to create a visually appealing and interactive experience. The game consists of multiple stages, and as the user progresses through each level, the difficulty gradually increases. Each stage must be successfully completed in order to advance to the next level. The challenges become more challenging with each level, presenting a greater test for the player.

### Point down the features

The user is trapped inside a room and should search for keys and hints inside the room for escaping it and advancing into next room with much more difficulty.
This game consists of 10 levels in total and levels are much harder as you advance to another one.

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @saikiranreddy201 , You can't have another issue before completing the previous one 😀 
 you already have the following 1 open issues 👀 ! : 
#1761

**Comment by kunjgit** [comment]
Hey @saikiranreddy201 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by kunjgit** [comment]
Hey @saikiranreddy201 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)
