### ISSUE TITLE
[New game]: Word Chain Game

### ISSUE THREAD

**Issue by dishamodi0910** [kunjgit/GameZone#1767]
### 🎮 Game Request

Game logic and basic description
Word Chain game will basically comprise of the words of your own choice.
Player has to form the chain of words that is the last letter of previous word should match with the first letter of next word.

### Point down the features

Game points
1. There will be the timer that within the time interval, player has to form the chain of words.
2. The number of words made available within the given time interval will be the score.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @dishamodi0910 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @dishamodi0910 , You can't have another issue before completing the previous one 😀 
 you already have the following 1 open issues 👀 ! : 
#1094

**Comment by kunjgit** [comment]
Hey @dishamodi0910 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
