### ISSUE TITLE
[New game]: Flappy Bird

### ISSUE THREAD

**Issue by Teddy1404** [kunjgit/GameZone#1768]
### 🎮 Game Request

Game logic and basic description
The HTML and CSS are used to structure and style the game interface, while JavaScript handles the game's logic and interactivity. JavaScript provides the necessary functionality to detect player input, control the bird's movement, calculate collisions, and update the game's state in real-time.

### Point down the features

Game points
The player uses button  or mouse to tap the bird to make it fly and avoid the obstacles in the path.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Teddy1404 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @Teddy1404 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
