### ISSUE TITLE
[New game]: Rubik's Cube Game

### ISSUE THREAD

**Issue by OMKAR-KALEPU** [kunjgit/GameZone#1769]
### 🎮 Game Request

The Cube Solver is a captivating puzzle game that challenges players to unravel the mysteries of a scrambled Rubik's Cube. Utilizing a seamless combination of HTML, CSS, and JavaScript, players can manipulate the virtual cube and strategically solve it, testing their spatial reasoning and problem-solving abilities. 

### Point down the features

Game points
- Realistic cube simulation
- User-Friendly controls
- Time tracking

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @OMKAR-KALEPU ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @OMKAR-KALEPU ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
