### ISSUE TITLE
[Enhancement]: add sound while clicking on the game 

### ISSUE THREAD

**Issue by NM2025** [kunjgit/GameZone#1775]
### Is your enhancement request related to a problem? Please describe.➕

please assign this task to me . I want to add sound while user click on the game . this makes it more attractive

### Describe the solution you'd like

Solution steps

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @NM2025 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by NM2025** [comment]
please assign this issue to me

**Comment by ManavMalhotra** [comment]
@kunjgit  Can I work on this issue? This seems interesting and also improves the user experience

**Comment by ManavMalhotra** [comment]
@kunjgit please review this PR #1891

**Comment by kunjgit** [comment]
Hey @NM2025 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
