### ISSUE TITLE
Important Checkboxes in issue template

### ISSUE THREAD

**Issue by parasss19** [kunjgit/GameZone#1778]
## Current
- Only code of conduct checkbox is present
- Which makes tough task for project admin to label the issues for GSSOC'23

## Change
- I want to add more checkbox so add it would be easy for project admin to label the issue
<img width="640" alt="Screenshot 2023-06-20 233055" src="https://github.com/kunjgit/GameZone/assets/101205226/d579f615-e913-4600-b4ce-a167c80d3842">

**Comment by kunjgit** [comment]
Hey @parasss19 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @parasss19! 🙂 
 It seems like you are not following proper guidelines !! 👀 
 Read documentation properly !!🙏 
 If you have any queries reach out to us on [Discord🕹️](https://discord.gg/fgwk4XZfxG) .

**Comment by kunjgit** [comment]
Hey @parasss19 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
