### ISSUE TITLE
[New game]: MARVLE WORD SCRAMBLE GAME

### ISSUE THREAD

**Issue by Soumyajit2825** [kunjgit/GameZone#1781]
### 🎮 Game Request

Over the past few years ,The Marvel Cinematic Universe (MCU) has put out a ton of great entertainment. Thus , we wanted to build a game that will create a twist on the classic word game ' Scramble' , based on MARVEL FILMS. We all love the MARVEL CINEMATIC UNIVERSE
This is a word scramble game where the player have to guess the answers by properly arranging the letters of the answers that are scrambled or jumbled up , related to the questions of the MARVEL FILMS .

Tech Stack used :

HTML
CSS
JavaScript

### Point down the features

Users have to guess right words based on the question provided from a MARVEL movie

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Soumyajit2825 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @Soumyajit2825 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
