### ISSUE TITLE
Alarm clock Game

### ISSUE THREAD

**Issue by ojKunal** [kunjgit/GameZone#179]
### 🎮 Game Request

The game is an "Alarm Clock Game" created using JavaScript. It combines the functionality of an alarm clock with a game that starts after the specified alarm time.

### Point down the features

Game points:
The game is presented in a web browser. The user interface includes an input field where the user can set the alarm time using a time picker. Once the desired alarm time is set, the user can click the "Set Alarm" button. When the "Set Alarm" button is clicked, the JavaScript code handles the functionality. It calculates the time difference between the current time and the alarm time set by the user. 
The game can be further enhanced by adding more features, graphics, sound effects, or levels of gameplay based on your imagination and programming skills.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @ojKunal ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by ojKunal** [comment]
I want to work in this issue . So can you assign me this issue.

**Comment by kunjgit** [comment]
Hey @ojKunal 👋!
 
  @kunjgit here, 
 We have this annoucement to make 📢!! 
 We have updated our README 🚀 
 Make sure you follow proper guideline to raise your next issues !! 
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG) if you haven't 😇 
  Thank you 💗!

**Comment by kunjgit** [comment]
Hello @ojKunal, Time's Uppp!⏰ 
 Sorry for closing your issue! 
 But it's more than a week since we haven't received anything from your side 😢 . 
 Come up with new ideas, create a new issue and make sure you finish it within a week! 🔥 
 All the best! 🚀 
 Happy Hacking! 💗

**Comment by kunjgit** [comment]
Hey @ojKunal ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
