### ISSUE TITLE
[New game]: Valorous Rabbit Game - 3D

### ISSUE THREAD

**Issue by abhinav-m22** [kunjgit/GameZone#1792]
### 🎮 Game Request

I want to add a new project using HTML, CSS and JavaScript which is a 3D game of a rabbit and a monster.

### Point down the features

1. The monster chases the rabbit and as a user you have to control the rabbit and save yourself from the monster. 
2. The rabbit jumps on click of the mouse and saves from the obstacles.
3. The game also has sound effects to provide a seamless experience to the user.
4. Overall 3D experience will be included along with levels.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @abhinav-m22 , You can't have another issue before completing the previous one 😀 
 you already have the following 1 open issues 👀 ! : 
#1791

**Comment by kunjgit** [comment]
Hey @abhinav-m22 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)
