### ISSUE TITLE
Gssoc'23 previous and next button do not work properly

### ISSUE THREAD

**Issue by aditya-stoic-sharma** [kunjgit/GameZone#1795]
### Give a brief about the bug ✍️

at last page of games after clicking next button it should go to the first page.
and at begining when you press previous button it should go to the last game page.
![image](https://github.com/kunjgit/GameZone/assets/109134266/04464a84-d729-483c-962a-e58fe64e5a3d)

### What is the expected behavior? 🤔

at last page of games after clicking next button it should go to the first page.
and at begining when you press previous button it should go to the last game page.

### Provide step by step information reproduce the bug 📄

assign it to me I will fix this issue 

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @aditya-stoic-sharma! 🙂 
 It seems like you are not following proper guidelines !! 👀 
 Read documentation properly !!🙏 
 If you have any queries reach out to us on [Discord🕹️](https://discord.gg/fgwk4XZfxG) .

**Comment by kunjgit** [comment]
Hey @aditya-stoic-sharma ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by kunjgit** [comment]
Hey @aditya-stoic-sharma ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)
