### ISSUE TITLE
[New game]: Pokemon game

### ISSUE THREAD

**Issue by SoarinSkySagar** [kunjgit/GameZone#1796]
### 🎮 Game Request

Game logic and basic description
A pokemon game to play with action packed fights and wild pokemon. Gotta catch 'em all! 

### Point down the features

Game points
Interactive, Responsive site, fun to play

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @SoarinSkySagar , You can't have another issue before completing the previous one 😀 
 you already have the following 1 open issues 👀 ! : 
#1558

**Comment by kunjgit** [comment]
Hey @SoarinSkySagar ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by kunjgit** [comment]
Hey @SoarinSkySagar ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)
