### ISSUE TITLE
[New game]: Complete The Line 

### ISSUE THREAD

**Issue by Durgesh4993** [kunjgit/GameZone#1797]
### 🎮 Game Request

Game logic and basic description
It is a multiplayer game.
Based on the lines connected, the boxes would be coloured.
The one with maximum number of boxes would be the winner.
The player has to select the lines. The one with the line at the last would fill the connecting boxes.
The player with the maximum boxes covered would be the winner.
The size of the board can be adjustable by user.
Players will switch after every turn. But the player who has filled the last box, will get one extra chance consecutively.

### Point down the features

Demo Vedio:
https://user-images.githubusercontent.com/114330097/246836493-293120ab-b1f0-48a8-af15-c05d49c65763.mp4

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Durgesh4993 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @Durgesh4993 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
