### ISSUE TITLE
[New game]: Tic Tac Toe

### ISSUE THREAD

**Issue by SimranLahrani842** [kunjgit/GameZone#18]
### 🎮 Game Request

I ll create the game skeleton of tic tac toe first and the logic for winning will be 3 X or 3 O diagonally or straight will win.This will be done in Html,css and Js

### Point down the features

This will be responsive that is can be played in any display size along with this there will be animation on winning.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey  @SimranLahrani842 ! Thank you for raising an issue 💗 You have been assigned this issue you can start working on the issue 🎮

**Comment by kunjgit** [comment]
Hey @SimranLahrani842 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
