### ISSUE TITLE
[New game]: Want to create a Tic-Tac-toe game with AI

### ISSUE THREAD

**Issue by AyishikD** [kunjgit/GameZone#1804]
### 🎮 Game Request

I want to add tictactoe game with AI mode and user mode both.
Rules for the game are same as normal TicTacToe

### Point down the features

It is made using React
Rules are same as normal TicTacToe
AI is made using minimax algorithm

### Select program in which you are contributing

GSSOC 23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @AyishikD ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by AyishikD** [comment]
@kunjgit Please can you also add the gssoc tag

**Comment by kunjgit** [comment]
Hey @AyishikD ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
