### ISSUE TITLE
[New game] : Color switcher

### ISSUE THREAD

**Issue by kumar11jr** [kunjgit/GameZone#1808]
### 🎮 Game Request

Game logic and basic description
In this game, the ball's color is initially set to red. When the "Switch Color" button is clicked, the color of the ball is changed randomly from the available colors (red, blue, green, yellow). The player needs to time their color switch so that the ball matches the color of the approaching barrier. If the colors match, a congratulations message is displayed. Otherwise, an alert is shown, and the game is reset with the ball color set back to red

### Point down the features

Game points
The objective of the game is to switch the color of the ball to match the color of the approaching barriers.
These are the core features of the "Color Switcher" game. You can expand upon this foundation and add more features like scoring, levels, time constraints, sound effects, and visual animations to enhance the gameplay experience.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @kumar11jr ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @kumar11jr ! , This issue is already assigned to @whiteknight16. 💗 
 You can work on other issues 🚀 
 If there is anything wrong you can contact us on [Discord🕹️](https://discord.gg/fgwk4XZfxG)👀

**Comment by kunjgit** [comment]
Hey @kumar11jr ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
