### ISSUE TITLE
[New game]: Pixel painter

### ISSUE THREAD

**Issue by Swapnil-2503** [kunjgit/GameZone#1811]
### 🎮 Game Request

Game logic and basic description

Pixel Painter is a JavaScript-based game that allows players to create pixel art on a virtual canvas. It provides a simple and intuitive interface for painting pixels with various colors, unleashing your creativity and artistic skills.

### Point down the features

Interactive canvas grid for pixel art creation.
- Limited color palette to choose from.
- Zoom functionality for precise pixel placement.
- Easy-to-use interface with a click-based painting mechanic.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Swapnil-2503 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)
