### ISSUE TITLE
[New game]: Color switcher

### ISSUE THREAD

**Issue by kumar11jr** [kunjgit/GameZone#1817]
### 🎮 Game Request

Game logic and basic description
The game container contains the score display and the color switcher element. When you click on the color switcher, it changes its background color randomly from a predefined set of colors. If the new color matches the previous color, the player's score increases, and the score display updates. If the colors don't match, the game is over, and the score resets to zero.

### Point down the features

Game points
The game container contains the score display and the color switcher element. When you click on the color switcher, it changes its background color randomly from a predefined set of colors. If the new color matches the previous color, the player's score increases, and the score display updates. If the colors don't match, the game is over, and the score resets to zero

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @kumar11jr ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @kumar11jr ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
