### ISSUE TITLE
[New game]: Super Mario Run

### ISSUE THREAD

**Issue by Vedansh-777** [kunjgit/GameZone#1823]
### 🎮 Game Request

Super Mario Run is a game that brings the classic side-scrolling platformer action of the Mario franchise to your fingertips. With simple touch controls, players guide Mario through levels filled with obstacles, enemies, and coins. The game combines precision jumping, power-ups, and engaging level design to offer a fun and challenging experience.

### Point down the features

* Endless Runner Gameplay: The game can feature an endless runner style where Mario continuously runs forward, and players must control his jumps and movements to navigate through levels and avoid obstacles.
* Level Editor: Create and customize your own Mario levels, placing platforms, enemies, and obstacles to design unique challenges.
* Score Leaderboard: Compete and strive to achieve the highest score in each level, aiming for the top spot on the leaderboard.
* Saved Levels Library: Access and play previously saved levels.
* Sound Effects: Immerse yourself in the game with lively sound effects that enhance the gameplay experience, making it more engaging and enjoyable.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Vedansh-777 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @Vedansh-777 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
