### ISSUE TITLE
[Enhancement]: Improving the UI of Snake Water Gun game

### ISSUE THREAD

**Issue by deepshikha2708** [kunjgit/GameZone#1824]
### Is your enhancement request related to a problem? Please describe.➕

Game enhancement
![image](https://github.com/kunjgit/GameZone/assets/80972038/ed490658-14c2-4f26-9b3f-28eb9918be97)
This game just has 3 options and we can only select and come to know if we win or lose.

### Describe the solution you'd like

Solution steps:

To improve the UI explaining about the game and showing computer's answers too

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @deepshikha2708 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)
