### ISSUE TITLE
[New game]: Pac-Man Doodle

### ISSUE THREAD

**Issue by OMKAR-KALEPU** [kunjgit/GameZone#1827]
### 🎮 Game Request

Pac-Man, an iconic arcade game released in 1980, continues to captivate players of all ages. Guide the hungry yellow protagonist through mazes filled with devious ghosts while devouring pellets and fruit. With its simple yet addictive gameplay, Pac-Man has become a timeless classic and an enduring symbol of video game history.

### Point down the features

Game points
- Classis gameplay
-  Responsive Controls
- Escape from Ghosts

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @OMKAR-KALEPU ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @OMKAR-KALEPU ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
