### ISSUE TITLE
[New game]: Save Doraemon

### ISSUE THREAD

**Issue by OMKAR-KALEPU** [kunjgit/GameZone#1829]
### 🎮 Game Request

Game logic and basic description
A maze like structure will be incoming at Doraemon who is initially placed at a corner and using mouse controls the user has to press the buttons present on the screen to save Doraemon from colliding into those maze like structures.

### Point down the features

Game points
- Mouse Controls
- Score Leaderboard
- Lives to play

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by RajeevDash007** [comment]
assign in

**Comment by kunjgit** [comment]
Hey @OMKAR-KALEPU ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
