### ISSUE TITLE
[New game]: Maze of Cables

### ISSUE THREAD

**Issue by VSatwika** [kunjgit/GameZone#1832]
### 🎮 Game Request

 - In Maze of Cables the player has to connect the the cable to the socket.
 - Could this issue be assigned to me under GSSoC'23?

 
<img width="960" alt="MazeofCabels" src="https://github.com/kunjgit/GameZone/assets/112561024/73b2439b-9237-4787-bd30-0a2db55a7068">

### Point down the features

 - Arrow keys are used to move inside the maze.
 - The player has to connect the cable to the socket before time runs out.
 - The player should also keep in mind the length of the cable. If the length exceeds, you lose.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @VSatwika ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
