### ISSUE TITLE
previous and next button do not work when pressed at the end page of project list 

### ISSUE THREAD

**Issue by aditya-stoic-sharma** [kunjgit/GameZone#1840]
### Give a brief about the bug ✍️

when we press the next button when project list last page is opened it does not do any thing . and same with previous when we press it at the first page

### What is the expected behavior? 🤔

After pressing the next button at the end of project list it should go to first page . and clicking previous at the first page it should go to the last page .

### Provide step by step information reproduce the bug 📄

Assign me this task and I will fix this issue but adding required javaScript

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @aditya-stoic-sharma ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @aditya-stoic-sharma! 🙂 
 It seems like you are not following proper guidelines !! 👀 
 Read documentation properly !!🙏 
 If you have any queries reach out to us on [Discord🕹️](https://discord.gg/fgwk4XZfxG) .

**Comment by kunjgit** [comment]
Hey @aditya-stoic-sharma ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
