### ISSUE TITLE
[New game]: Riddle Room

### ISSUE THREAD

**Issue by sabhisharma-ise** [kunjgit/GameZone#1843]
### 🎮 Game Request

It is a puzzle game where you must solve a series of puzzles in order to escape the room. The puzzles are all based on different programming concepts, such as HTML, CSS, and JavaScript.

### Point down the features

- **Challenging puzzles**: The puzzles in the game are designed to be challenging, but they are also fair. If you get stuck, you can always ask for help from the community.
- **Educational**: The puzzles in the game are based on different programming concepts, such as HTML, CSS, and JavaScript. This makes the game a great way to learn about these concepts.
- **Visually appealing**: The game is visually appealing and engaging. The puzzles are presented in a way that is both challenging and fun.
- **Social**: The game has a forum where you can discuss the puzzles with other players. This is a great way to get help if you are stuck, or to share your own solutions.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @sabhisharma-ise ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @sabhisharma-ise ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
