### ISSUE TITLE
Improving the UI of The Footer Section 

### ISSUE THREAD

**Issue by PIYUSH1525** [kunjgit/GameZone#1846]
Hey @kunjgit , 
I want to Improve the UI of the Footer section as it dosen't looks good with the page and dsen't have any proper alignment 
The Social links also need Proper scaling .
Describe the solution you'd like
**Solution steps:**

Creation Of Footer Section From Scratch Which will match the content in the website 
Rescaling and realignment of the social medial links and icons 

**Select program in which you are contributing**
GSSoC23

**Code of Conduct**
 I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

![image](https://github.com/kunjgit/GameZone/assets/120514593/59b92c02-1c2c-46f9-a641-aeeb790866ac)

**Comment by kunjgit** [comment]
Hey @PIYUSH1525 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @PIYUSH1525 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by PIYUSH1525** [comment]
Hey @kunjgit  can you help me with Raising the issue .
please tell me hoe to specifically raise this issue

**Comment by PIYUSH1525** [comment]
Can I work On this issue Now ? 
Will My PR Will be accepted ?
