### ISSUE TITLE
Drum Kit Game

### ISSUE THREAD

**Issue by HIMANSHU00KUMAR** [kunjgit/GameZone#185]
### 🎮 Game Request

Drum and Kit Game is a rhythm-based game where players simulate playing a virtual drum kit using input devices such as a keyboard or controller.
tech use:Html,css,javascript

### Point down the features

The game provides visual feedback in the form of on-screen prompts or notes that indicate when and which drum element to hit.
With increasing difficulty levels and varying music tracks, Drum and Kit Game offers an engaging and immersive experience for rhythm game enthusiasts.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @HIMANSHU00KUMAR ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by Roshnijeewani3457** [comment]
I want to work on this issue. Please Assign me this issue @kunjgit.

**Comment by kunjgit** [comment]
Hey @HIMANSHU00KUMAR 👋!
 
  @kunjgit here, 
 We have this annoucement to make 📢!! 
 We have updated our README 🚀 
 Make sure you follow proper guideline to raise your next issues !! 
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG) if you haven't 😇 
  Thank you 💗!

**Comment by kunjgit** [comment]
Hey @HIMANSHU00KUMAR ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
