### ISSUE TITLE
[New game]: Guess The Color

### ISSUE THREAD

**Issue by linga66** [kunjgit/GameZone#1853]
### 🎮 Game Request

GUESS THE COLOR
when the RGB value is given

### Point down the features

We will be having easy and hard level
Blocks of different colors are given
The RGB value is given and we need to guess the color and select the correct box

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @linga66 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @linga66! 
We are already having a similar game request in #1790 👀 
Make sure you come up with a cool unique idea 😀 
 Waiting for your new game idea 💗.

**Comment by kunjgit** [comment]
Hey @linga66 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by linga66** [comment]
> Hey @linga66 ! Thank you so much for your raising the issue💗 It’s all yours, you can come anytime again and make some contributions! 🚀 Alone, we can do little, but together we can do so much! 😇

No. This is different from that game @kunjgit . We will be giving RGB value i.e., RGB(3, 246, 84)
If the level is difficult it contains 6 blocks of colored squares, if easy only 3 
We need to guess the color given in the for of RGB(3, 246, 84)
