### ISSUE TITLE
[Enhancement]: Page Number Section Design Improvement

### ISSUE THREAD

**Issue by iamRabia-N** [kunjgit/GameZone#1858]
### Is your enhancement request related to a problem? Please describe.➕

No. It's an enhancement in the existing design.

### Describe the solution you'd like

Working on the styling of this section, I can make it look even better.
**Current Design**
![gameworld-issue2 (2)](https://github.com/kunjgit/GameZone/assets/115794049/4d69c880-fa4c-48a1-99e8-373096b93499)
**Expected Updated Design**
![gameworld-issue2 (1)](https://github.com/kunjgit/GameZone/assets/115794049/56584573-9678-4578-8a9a-df77e726a1bf)

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @iamRabia-N ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @iamRabia-N ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
