### ISSUE TITLE
[New game]: Shape Guesser Game [GSSoC'23]

### ISSUE THREAD

**Issue by Avdhesh-Varshney** [kunjgit/GameZone#1862]
### 🎮 Game Request

Game logic and basic description

- Showing the dotted picture of the shape
- Showing different options
- Also Adding 3 lives for 3 wrong answers only, otherwise game will be over
- Current and high score will be shown on the screen

### Point down the features

Game points

- (+1) on chosen of correct answer
- 0 for the wrong answer
- Game will be over when 3 lives are exhausted !

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Avdhesh-Varshney ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @Avdhesh-Varshney ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
