### ISSUE TITLE
[New game]: Spider Attack

### ISSUE THREAD

**Issue by SyedImtiyaz-1** [kunjgit/GameZone#1865]
### Game logic and basic description -
It's a spider game which I'm making using HTML, CSS & JavaScript.
It will contain Man with a Gun to shoot Spiders . 👍🏻 

### Point down the features

Game Includes Sounds, Gun, Spider, Man, Pop-Up and few more functionality.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @SyedImtiyaz-1 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @SyedImtiyaz-1 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
