### ISSUE TITLE
[New game]: GSSOC '23: Alien Shooting Game

### ISSUE THREAD

**Issue by sujanrupu** [kunjgit/GameZone#1867]
## Game logic and basic description:
Frontend game developed using HTML, CSS, JavaScript, Points will gained by the player by number of shoots.

## Game points:
- There will be alien flights and one rocket to the player
- Player can destroy flight by the rocket
- If one flight touches the ground, the game will be over
- The number of flights the player can destroy that points will be earned

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @sujanrupu ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @sujanrupu ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
