### ISSUE TITLE
[Bug]: Game Repetition

### ISSUE THREAD

**Issue by ritik48** [kunjgit/GameZone#1869]
### Give a brief about the bug ✍️

Description

#### Alien Shooter game is present twice. Both are the exact same game.

![aliedcv](https://github.com/kunjgit/GameZone/assets/84488726/db3adeab-e5b1-4a41-b6c3-ccb96f49f5a3)

Provide step by step information reproduce the bug 📄

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @ritik48 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by ritik48** [comment]
@kunjgit please assign this issue to me

**Comment by ritik48** [comment]
@kunjgit please assign this issue to me

**Comment by ritik48** [comment]
@kunjgit please assign this issue to me

**Comment by gobbledy-gook** [comment]
This issue looks already solved. It must be closed as the issue is already fixed.

**Comment by ritik48** [comment]
@gobbledy-gook ya it only make sense its solved as it's been more 14 days since I raised the issue.

**Comment by kunjgit** [comment]
Hey @ritik48 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
