### ISSUE TITLE
[New game]: Action game

### ISSUE THREAD

**Issue by baisnabi02** [kunjgit/GameZone#187]
### 🎮 Game Request

To build a Action Game using HTML ,CSS  and JavaScript.

### Point down the features

1. Move the  dragon  to protect from the enemy using html, css , JS.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @baisnabi02 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by Ks103** [comment]
i want to work on this issue , please assign it to me

**Comment by baisnabi02** [comment]
> ### 🎮 Game Request
> To build a Action Game using HTML ,CSS and JavaScript.
> 
> ### Point down the features
> 1. Move the  dragon  to protect from the enemy using html, css , JS.
> 
> ### Select program in which you are contributing
> GSSoC23
> 
> ### Code of Conduct
> * [x]  I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

Assigned

**Comment by baisnabi02** [comment]
> 

Assigned

**Comment by kunjgit** [comment]
Hello @baisnabi02, Time's Uppp!⏰ 
 Sorry for closing your issue! 
 But it's more than a week since we haven't received anything from your side 😢 . 
 Come up with new ideas, create a new issue and make sure you finish it within a week! 🔥 
 All the best! 🚀 
 Happy Hacking! 💗

**Comment by kunjgit** [comment]
Hey @baisnabi02 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
