### ISSUE TITLE
[Enhancement]: Improving GUI of Tic Tac Toe game 

### ISSUE THREAD

**Issue by Abhishek-Rajput-81** [kunjgit/GameZone#1879]
### Is your enhancement request related to a problem? Please describe.➕

It's an enhancement in the design of the webpage. The current GUI (Graphical User Interface) of the Tic Tac Toe game requires enhancement to provide a more intuitive and visually appealing user experience. 

### Describe the solution you'd like

The enhancement includes 
- Alignment of the Game Board to center
- Styling the Game Board
- Player Turn Indicator
- Interactive Background

I will use Bootstrap, a popular front-end framework, to make the game's interface more attractive and enjoyable.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Abhishek-Rajput-81 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @Abhishek-Rajput-81 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
