### ISSUE TITLE
Icons on the front page

### ISSUE THREAD

**Issue by Shreyans2004** [kunjgit/GameZone#188]
### Give a brief about the bug ✍️

In the front page the icons of twitter,linkedIn and github are small in size,which is making them difficult to read.

### What is the expected behavior? 🤔

Normally the icons are slightly bigger in size in  websites .But in the home page they are looking little smaller.

### Provide step by step information reproduce the bug 📄

I can increase the size of the icons and add some styling to them, so that they may look more catchy and attractive. Slight increase in the size of icon on hovering will make them more catchy.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Shreyans2004 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @Shreyans2004 👋!
 
  @kunjgit here, 
 We have this annoucement to make 📢!! 
 We have updated our README 🚀 
 Make sure you follow proper guideline to raise your next issues !! 
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG) if you haven't 😇 
  Thank you 💗!

**Comment by kunjgit** [comment]
Hello @Shreyans2004, Time's Uppp!⏰ 
 Sorry for closing your issue! 
 But it's more than a week since we haven't received anything from your side 😢 . 
 Come up with new ideas, create a new issue and make sure you finish it within a week! 🔥 
 All the best! 🚀 
 Happy Hacking! 💗

**Comment by kunjgit** [comment]
Hey @Shreyans2004 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
