### ISSUE TITLE
[Enhancement]: Addition of animations in title and game containers.

### ISSUE THREAD

**Issue by Dimple-01** [kunjgit/GameZone#1883]
### Is your enhancement request related to a problem? Please describe.➕

**Issue**

Addition of animations in title and game containers.

**Layout Enhancement**

I found that the tile of the page (GameZone) was not much attractive and user-engaging.
Also, the game container is quite clumsy. I felt that it needs some kind of border to flaunt them uniquely.

**Current Behavior**

![Screenshot (134)](https://github.com/kunjgit/GameZone/assets/114878264/6d9786a7-9695-4ddd-9960-b35677001693)

**Desired Behavior**

![Screenshot (131)](https://github.com/kunjgit/GameZone/assets/114878264/f2f21cfa-4fce-4f63-afe5-c6dc9688dca7)

![Screenshot (132)](https://github.com/kunjgit/GameZone/assets/114878264/d61a0b68-39e5-4a31-af07-1e4ef19a0ade)

![Screenshot (133)](https://github.com/kunjgit/GameZone/assets/114878264/63307ea1-0299-4294-9628-8d9dd325e061)

### Describe the solution you'd like

**Solution steps**

1. I would add some CSS and HTML to complete this work.
2.  I would apply different animation and check if it suits or not.

**I want to work on this issue.
Please this work to me.**

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Dimple-01 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by Dimple-01** [comment]
I consider this issue as assigned to me.

**Comment by kunjgit** [comment]
Hello @Dimple-01, Time's Uppp!⏰ 
 Sorry for closing your issue! 
 But it's more than a week since we haven't received anything from your side 😢 . 
 Come up with new ideas, create a new issue and make sure you finish it within a week! 🔥 
 All the best! 🚀 
 Happy Hacking! 💗

**Comment by kunjgit** [comment]
Hey @Dimple-01 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
