### ISSUE TITLE
[New game]: Hare's Hurdle

### ISSUE THREAD

**Issue by akhilender-bongirwar** [kunjgit/GameZone#1884]
### 🎮 Game Request

Game logic and basic description
In this exciting and challenging game, you control a courageous rabbit who must navigate through a perilous environment filled with snakes. The objective is to help the rabbit stay safe by jumping from snake to snake, avoiding their deadly bites. The game tests your reflexes, timing, and strategic thinking as you try to survive for as long as possible.

### Point down the features

Game points
1. It is very easy to play.
2. The game's goal is to have maximum points which you get if the rabbit doesn't get a snake bite.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @akhilender-bongirwar ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by akhilender-bongirwar** [comment]
Hey @kunjgit, should I close the issue if the PR is raised.

**Comment by kunjgit** [comment]
Hey @akhilender-bongirwar ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
