### ISSUE TITLE
[New game]: Dinosaur game ( Chrome's one _

### ISSUE THREAD

**Issue by Bhuvanchand26** [kunjgit/GameZone#1885]
### 🎮 Game Request

We all have played this game whenever our internet was down, this game is google chrome's very own dinosaur game
you just have to jump over those cactus plants and get saved from flying creatures. I thought this would be great to include in this repo.

### Point down the features

Jump when it is right and get saved from flying creatures.
![image](https://github.com/kunjgit/GameZone/assets/131843589/35e2b793-04da-4022-b890-e5a5df612698)

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Bhuvanchand26 , You can't have another issue before completing the previous one 😀 
 you already have the following 1 open issues 👀 ! : 
#1850

**Comment by kunjgit** [comment]
Hey @Bhuvanchand26 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by kunjgit** [comment]
Hey @Bhuvanchand26 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)
