### ISSUE TITLE
[New game]: Dinosaur game ( chrome's one )

### ISSUE THREAD

**Issue by Bhuvanchand26** [kunjgit/GameZone#1887]
### 🎮 Game Request

We all have played this many times whenever our network was down and this is google chrome's very own dinosaur game
Where we have Dinosaur which will be moving and has only one control which is to jump. Dinosaur just has to before it collides with cactus plants and gets saved from flying creatures.
I thought it would be great to have this game in this repo.

### Point down the features

You can only jump to a particular distance, you have to jump at the correct time to get saved from cactus plants and flying creatures. On moving forward speed will increase and it'll become difficult to jump

![image](https://github.com/kunjgit/GameZone/assets/131843589/ddf6676b-4237-46e4-aa8d-75920215fb8e)

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Bhuvanchand26 , You can't have another issue before completing the previous one 😀 
 you already have the following 1 open issues 👀 ! : 
#1850

**Comment by kunjgit** [comment]
Hey @Bhuvanchand26 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by kunjgit** [comment]
Hey @Bhuvanchand26 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)
