### ISSUE TITLE
React Tic Tac Toe Game

### ISSUE THREAD

**Issue by Ekam-Bitt** [kunjgit/GameZone#1888]
### 🎮 Game Request

A 2 player Tic Tac Toe game developed using react. Game auto stops when one player wins or the board is filled with no winner resulting in a Draw. It also has a Restart button to restart the game any time.
Simple minimalistic user interface with provides pleasing aesthetics.

## Game points
<img width="1552" alt="Screenshot 2023-06-23 at 2 03 34 AM" src="https://github.com/kunjgit/GameZone/assets/74407205/e7591ca3-512e-4dc3-ab3b-91f417e0586b">

- 2-player tic tac toe game
- Auto decides outcome of the game
- Restart button to start anew
- Minimalist and pleasing aesthetics

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Ekam-Bitt! 🙂 
 It seems like you are not following proper guidelines !! 👀 
 Read documentation properly !!🙏 
 If you have any queries reach out to us on [Discord🕹️](https://discord.gg/fgwk4XZfxG) .

**Comment by kunjgit** [comment]
Hey @Ekam-Bitt ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @Ekam-Bitt ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
