### ISSUE TITLE
[New game]:  Menja 

### ISSUE THREAD

**Issue by SALONI-AGGARWAL0304** [kunjgit/GameZone#189]
### 🎮 Game Request

Game logic and basic description
This game is similar to fruit ninja game , where instead of fruits it will be cubes and mouse will be acting as a knife to split the cubes into smaller cubes , and this will continue till you will be cutting those cubes , and after game finishes it will show you the highest score and the current score . 

### Point down the features

Game points
Number of cubes smashed 
Two modes to play the game ( Normal game and casual mode )
in casual mode game will not end , in normal game there will be scores 

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @SALONI-AGGARWAL0304 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @SALONI-AGGARWAL0304 👋!
 
  @kunjgit here, 
 We have this annoucement to make 📢!! 
 We have updated our README 🚀 
 Make sure you follow proper guideline to raise your next issues !! 
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG) if you haven't 😇 
  Thank you 💗!

**Comment by kunjgit** [comment]
Hey @SALONI-AGGARWAL0304 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
