### ISSUE TITLE
[New game]: Pig_Game

### ISSUE THREAD

**Issue by shraddha761** [kunjgit/GameZone#1892]
### 🎮 Game Request

Pig is a simple two player dice game.

### Point down the features

If the player rolls a 1, their current score gets zeroed and the other player takes turn.
If the player rolls any other number, it is added to their current score and the player's turn continues.
If a player chooses to "hold" the current score, their turn total is added to their score and the other player takes turn.
The first player to score 100 or more points wins.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @shraddha761 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @shraddha761 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
