### ISSUE TITLE
[Enhancement]: Improve the responsiveness of Fruit Ninja Game

### ISSUE THREAD

**Issue by Ekam-Bitt** [kunjgit/GameZone#1894]
### Is your enhancement request related to a problem? Please describe.➕

Game enhancement
<img width="1552" alt="Screenshot 2023-06-23 at 5 23 56 PM" src="https://github.com/kunjgit/GameZone/assets/74407205/97f89eeb-1690-41bf-b2ed-7e203aad723a">
The page is not responsive, leading to a bad user experience. I'm going to fix that.

### Describe the solution you'd like

Solution steps:
Fix the dimension & position of the game board and make the overall website responsive
<img width="1552" alt="Screenshot 2023-06-23 at 6 13 43 PM" src="https://github.com/kunjgit/GameZone/assets/74407205/4f1d43ec-8ff5-4a4a-a261-e662f3cad952">

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Ekam-Bitt ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hello @Ekam-Bitt, Time's Uppp!⏰ 
 Sorry for closing your issue! 
 But it's more than a week since we haven't received anything from your side 😢 . 
 Come up with new ideas, create a new issue and make sure you finish it within a week! 🔥 
 All the best! 🚀 
 Happy Hacking! 💗

**Comment by kunjgit** [comment]
Hey @Ekam-Bitt ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
