### ISSUE TITLE
[New game]: Color Matcher

### ISSUE THREAD

**Issue by Durgesh4993** [kunjgit/GameZone#1897]
### 🎮 Game Request

Game logic and basic description
Just tap on button and match all the colore,

Screenshort:
![image](https://github.com/kunjgit/GameZone/assets/98798977/3732a0d3-521a-4eb8-af8d-989bbca77a55)

### Point down the features

Demo Vedio:

https://github.com/kunjgit/GameZone/assets/98798977/f0bb8f49-2053-43cc-8d7f-49c5d537f09a

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Durgesh4993 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @Durgesh4993 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
