### ISSUE TITLE
[Enhancement]: Adding Favicons and media queries 

### ISSUE THREAD

**Issue by iriteshmishra** [kunjgit/GameZone#19]
### Is your enhancement request related to a problem? Please describe.➕

Icons were missing and media queries between 480px to 563px of simon game were not present. The icons should have be present at the tab and media queries were not proper between 480px to 563px.

### Describe the solution you'd like

I would like to add favicons which were missing in the GameZone and also add media query between 480px to 563px in simon game.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
@iriteshmishra I have already merged the PR !! 💗 
make sure you follow the guidelines from now thankyou soo much for contributing to GameZone 🎮
