### ISSUE TITLE
[New game]: Add Hextris Game

### ISSUE THREAD

**Issue by kartikjoshi267** [kunjgit/GameZone#1901]
### 🎮 Game Request

Hextris is like the upgraded version of the Tetris Game. The difference between Hextris and Tetris is that In Tetris Game, we have to move the blocks. However, In Hextris Game, we have to move the platform itself and combine the blocks with the same type of colors.

### Point down the features

![image](https://github.com/kunjgit/GameZone/assets/96565730/8cba742f-2766-49b6-99c1-5f7899d84848)

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @kartikjoshi267 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @kartikjoshi267 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
