### ISSUE TITLE
[New game]: Pumpkin Pursuit

### ISSUE THREAD

**Issue by akhilender-bongirwar** [kunjgit/GameZone#1906]
### 🎮 Game Request

Game logic and basic description
Welcome to "Pumpkin Pursuit," a thrilling memory game set in a spooky Halloween world.  It's up to you to uncover pairs of matching pumpkins while enjoying enchanting sounds that enhance the Halloween experience. Sharpen your memory, embrace the challenge.

### Point down the features

Game points
-The player is given 60 seconds to match all the cards.
-The players moves are also counted.
-The player has to select all the matching pairs within 1minute to win the game.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @akhilender-bongirwar , You can't have another issue before completing the previous one 😀 
 you already have the following 1 open issues 👀 ! : 
#1884

**Comment by kunjgit** [comment]
Hey @akhilender-bongirwar ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)
