### ISSUE TITLE
[New game]: ATLAS: Name the country 

### ISSUE THREAD

**Issue by AnkitaBarbora** [kunjgit/GameZone#1907]
### 🎮 Game Request

Game logic and basic description
This is a classic game where players take turns naming countries based on specific rules. It puts the player's geographical skills to a test.

The rules are: 
- The game starts with a predefined word, "atlas". The first player begins by saying the name of a country that starts with the last letter of the word "atlas," which is the letter "s." 
- The second player then responds with the name of a country that starts with the last letter of the country the first player mentioned. 
- The game continues back and forth with players taking turns until a predetermined condition (of 2 passes or 3 incorrect attempts by the player) is met.

### Point down the features

Game points
- In this version of the game, players play against a computer. The player enters a country name, and the computer responds with a country that starts with the last letter of the player's country. The player's objective is to keep the game going by entering valid country names. 
- The game aims to test the players' knowledge of country names, improve their vocabulary, and challenge their ability to think quickly and make associations based on word patterns. 
- It can be an enjoyable and educational game for individuals who are interested in geography or simply want to have fun with wordplay.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @AnkitaBarbora ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by Shaba1406** [comment]
can i work on this issue under GSSOC 2023
