### ISSUE TITLE
[New game]: Guess the flag

### ISSUE THREAD

**Issue by Swapnil-2503** [kunjgit/GameZone#1912]
### 🎮 Game Request

Game logic and basic description

A multiplayer game where players take turns guessing the country based on its flag.

### Point down the features

Game points

1. Open the game in a web browser.
2. The game will display a flag image.
3. Player 1 enters the name of the country they think the flag belongs to in the input field.
4. Player 1 clicks the **Submit** button to check their guess.
5. If Player 1's guess is correct, they will receive a congratulatory message.
6. If Player 1's guess is incorrect, they will be informed of the correct country.
7. Player 1 clicks the **Next** button to proceed to the next flag.
8. Player 2 then takes their turn by following steps 3-7.
9. The game continues with players taking turns guessing flags.
10. Enjoy playing and challenge each other to see who can guess the most flags correctly!

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Swapnil-2503 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @Swapnil-2503! 
We are already having a similar game request in #1790 👀 
Make sure you come up with a cool unique idea 😀 
 Waiting for your new game idea 💗.

**Comment by kunjgit** [comment]
Hey @Swapnil-2503 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
