### ISSUE TITLE
[New game]: Math Quiz Game

### ISSUE THREAD

**Issue by Vedansh-777** [kunjgit/GameZone#1915]
### 🎮 Game Request

A Simple Maths Quiz build purely on HTML, CSS and JavaScript. No API is used in generating question or Options. All the questions are generated randomly. The same way are the options.

### Point down the features

**TIMER**

Timer feature is now added. Each question will have a time limit(10s here). If the user is unable to pick the answer within that limit, next question will appear and scored for that question is counted zero.

**SCORING**

Time based feature added. The scores now will be generated on the basis of how much of time was left for that particular question. A simple linear function is used. (Ex : If the user finishes one question in 9s, the sore for that question will be 90%).

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Vedansh-777 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @Vedansh-777! 
We are already having a similar game request in #1653 👀 
Make sure you come up with a cool unique idea 😀 
 Waiting for your new game idea 💗.

**Comment by kunjgit** [comment]
Hey @Vedansh-777 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
