### ISSUE TITLE
[New game]: Throw 'n' Score

### ISSUE THREAD

**Issue by srujana-16** [kunjgit/GameZone#1918]
### 🎮 Game Request

Throw 'n' Score is a dice-rolling game where two players compete to reach a total score of 100 or more points. It will be implemented using HTML, CSS and Javascript. 

### Point down the features

- Interactive gameplay that allows players to make decisions on each turn.
- Randomized selection of the first player to add an element of unpredictability.
- Clear display of each player's current and total scores.
- Intuitive user interface for easy understanding and enjoyment.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @srujana-16 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @srujana-16 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
