### ISSUE TITLE
[Enhancement]: Tic Tac Toe game 

### ISSUE THREAD

**Issue by AvinashChourasia** [kunjgit/GameZone#1924]
### Is your enhancement request related to a problem? Please describe.➕

Game enhancement:
1. Want to add my design with better UI
2. Add animations on each steps.

### Describe the solution you'd like

Solution step :-
1. Want to create better UI
2. User-friendly game zone

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @AvinashChourasia ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by AvinashChourasia** [comment]
Old one 

![Screenshot (81)](https://github.com/kunjgit/GameZone/assets/97829396/b574f621-809f-4f2c-b12c-39c0da34a622)

New one

![Screenshot (83)](https://github.com/kunjgit/GameZone/assets/97829396/a7ade52f-4171-45c1-af13-0abb69021fc8)

**Comment by kunjgit** [comment]
Hey @AvinashChourasia ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by AvinashChourasia** [comment]
Hey @kunjgit. Can I enhance the UI of other games also by rasiang an issue.
