### ISSUE TITLE
Throw n score - Multiplayer game - GSSOC'23

### ISSUE THREAD

**Issue by soorjya** [kunjgit/GameZone#1926]
### 🎮 Game Request

Game Logic
[Throw n score] is an exciting and engaging game that offers players a unique gaming experience. The game revolves around [briefly describe the core game logic and mechanics]. Players will be challenged to [explain the main objective or goal of the game] and must use their skills and strategies to [describe how players can progress or succeed in the game].

Features
Immersive Gameplay: Experience a captivating and immersive gaming environment with stunning graphics and engaging audio effects.
Multiple Game Modes: Enjoy a variety of game modes that offer different challenges and gameplay variations to keep you entertained.
Progressive Difficulty: The game progressively increases in difficulty, providing a satisfying level of challenge and excitement for players of all skill levels.
Power-ups and Upgrades: Discover and utilize powerful in-game power-ups and upgrades to enhance your abilities and overcome obstacles.
Leaderboards and Achievements: Compete with friends and other players worldwide, earn achievements, and strive to reach the top of the leaderboards.
Social Integration: Connect with your friends, share your achievements on social media, and challenge them to beat your high scores.
Interactive Controls: Intuitive and responsive controls ensure a smooth and enjoyable gaming experience.

### Point down the features

Interactive gameplay that allows players to make decisions on each turn.
Randomized selection of the first player to add an element of unpredictability.
Clear display of each player's current and total scores.
Intuitive user interface for easy understanding and enjoyment.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @soorjya! 🙂 
 It seems like you are not following proper guidelines !! 👀 
 Read documentation properly !!🙏 
 If you have any queries reach out to us on [Discord🕹️](https://discord.gg/fgwk4XZfxG) .

**Comment by kunjgit** [comment]
Hey @soorjya ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @soorjya ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by soorjya** [comment]
assignee me this issue under gssoc'23
