### ISSUE TITLE
[New game]: Slice Storm

### ISSUE THREAD

**Issue by VSatwika** [kunjgit/GameZone#1933]
### 🎮 Game Request

 - Slice Storm is a fun game where players have to smash boxes using their slicing skills. 
 - Slice through them with precision, avoiding obstacles, and aim for the highest scores.
 - The game is built using JavaScript, HTML, and CSS, making it accessible and playable on various desktop as well as touch 
    screen platforms.

### Point down the features

 - **Points**: Players are rewarded with points for every box they skillfully slice, with the score progressively growing for each successful cut.
 - **Power-ups**: Throughout the game, players may encounter unique boxes that grant advantageous power-ups, such as reducing the speed at which boxes appear.
 - **Obstacles**: Occasionally, challenging boxes will emerge, demanding multiple hits to be obliterated compared to regular boxes.
 - **High Scores**: The game diligently records the player's best score, enabling them to engage in self-competition and strive for personal excellence.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @VSatwika ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @VSatwika ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
