### ISSUE TITLE
[New game]:  Roulette Game

### ISSUE THREAD

**Issue by Vedansh-777** [kunjgit/GameZone#1940]
### 🎮 Game Request

Roulette game in which players bet on which red or black numbered compartment of a revolving wheel a small ball (spun in the opposite direction) will come to rest within. Bets are placed on a table marked to correspond with the compartments of the wheel.

### Point down the features

The game begins when one of the croupiers (dealers) in attendance calls for the players to make their bets, which they do by placing chips on the spaces of the layout on any number, group, or classification they hope will win.

The croupier usually starts the wheel spinning in a counterclockwise direction and then spins a small ivory or plastic ball onto the bowl’s back track in the opposite direction. Players may continue to place bets while the wheel and ball are in motion until the ball slows down and is about to drop off the back track, at which time one of the croupiers announces that no more bets may be made.

When the ball falls and comes to rest between any two metal partitions of the wheel, it marks the winning number (or a 0 or 00), the winning colour, and any other permitted bet that pertains to a winning number or symbol. The dealer immediately announces the winning number and its colour and places a special marker on the corresponding number on the layout. He first collects all losing bets, not disturbing the chips that are resting on winning spaces, and then pays off any winning bets.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Vedansh-777! 
We are already having a similar game request in #1907 👀 
Make sure you come up with a cool unique idea 😀 
 Waiting for your new game idea 💗.

**Comment by kunjgit** [comment]
Hey @Vedansh-777 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @Vedansh-777 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
