### ISSUE TITLE
[New game]: Add a Checkers game

### ISSUE THREAD

**Issue by abhinav-m22** [kunjgit/GameZone#1942]
### 🎮 Game Request

I want to develop a Checkers game using HTML, CSS, and JavaScript to provide an interactive and engaging gaming experience. 

### Point down the features

Game Board: Design and implement a visually appealing game board using HTML and CSS, representing the checkered grid with alternating colors. The board should be responsive and adjust well to different screen sizes.

Piece Movement: Enable players to move their game pieces by selecting a valid piece and then selecting a valid destination on the game board. Implement logic to enforce the rules of Checkers, including capturing opponent's pieces and promoting pieces to kings upon reaching the opposite end of the board.

Game Logic: Implement the necessary game logic in JavaScript to handle turn-based gameplay, enforcing the rules of Checkers, determining valid moves and capturing opponent's pieces. Additionally, implement logic to detect game over conditions, such as when one player wins or a draw occurs.

Player Interaction: Provide a user-friendly interface that allows players to interact with the game using mouse or touch inputs. Highlight valid moves and provide visual feedback when pieces are captured or kings are promoted.

### Select program in which you are contributing

GSSoC23, Other

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @abhinav-m22 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @abhinav-m22 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
