### ISSUE TITLE
[New game]: creating a rock paper scissors game under GSSOC'23 using HTML CSS JS

### ISSUE THREAD

**Issue by Nikita06211** [kunjgit/GameZone#1947]
### 🎮 Game Request

Game logic and basic description
I would like to create a simple rock paper scissors game 

### Point down the features

This is a single player rock paper scissors game where the user will play against the computer.
Rules-:
Between rock and scissors-> rock wins
Between rock and paper-> paper wins
Between paper and scissors-> scissors wins

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Nikita06211 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @Nikita06211 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
