### ISSUE TITLE
[Enhancement]:  Add a custom scroll bar

### ISSUE THREAD

**Issue by komalioruganti** [kunjgit/GameZone#1949]
### Is your enhancement request related to a problem? Please describe.➕

I think the present scroll bar is the default scroll bar for all web applications. This is a little misaligned with the rest of the UI of the page.
<img width="960" alt="image" src="https://github.com/kunjgit/GameZone/assets/95839946/73bb0d82-9417-4426-b879-0df59f7e379f">

### Describe the solution you'd like

I would like to change the UI of scroll bar so that it would fit with the rest of the UI.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @komalioruganti ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hello @komalioruganti, Time's Uppp!⏰ 
 Sorry for closing your issue! 
 But it's more than a week since we haven't received anything from your side 😢 . 
 Come up with new ideas, create a new issue and make sure you finish it within a week! 🔥 
 All the best! 🚀 
 Happy Hacking! 💗

**Comment by kunjgit** [comment]
Hey @komalioruganti ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
