### ISSUE TITLE
[New game]: CSS Only Adventure Game

### ISSUE THREAD

**Issue by sabhisharma-ise** [kunjgit/GameZone#1956]
### 🎮 Game Request

This is a no-JS adventure game created using only CSS. The game is a simple text adventure, where the player can move around a grid of squares and interact with objects.
The game is controlled using the keyboard, and the player can move up, down, left, and right. The player can also interact with objects by clicking on them.

### Point down the features

The game is made up of a grid of squares, and the player can move around the grid using the keyboard.
It contains a few different objects, and the player can interact with objects by clicking on them.
It has a simple text-based interface, but it is still a fun and challenging experience.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @sabhisharma-ise ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @sabhisharma-ise ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
