### ISSUE TITLE
[New game]: 2048 Game

### ISSUE THREAD

**Issue by Sagar19129** [kunjgit/GameZone#196]
### 🎮 Game Request

I want to make this game.
The goal of this game is: 
2048 Game made using HTML, CSS, Javascript. 2048 is a puzzle Game in which you join tiles until you get 2048 score.
I eagerly want to contribute for this game.

### Point down the features

Game points

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Sagar19129 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by Sagar19129** [comment]
assign in

**Comment by kunjgit** [comment]
Hey @Sagar19129 👋!
 
  @kunjgit here, 
 We have this annoucement to make 📢!! 
 We have updated our README 🚀 
 Make sure you follow proper guideline to raise your next issues !! 
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG) if you haven't 😇 
  Thank you 💗!

**Comment by kunjgit** [comment]
Hey @Sagar19129 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
