### ISSUE TITLE
[New game]: Space Drifter

### ISSUE THREAD

**Issue by Killer2OP** [kunjgit/GameZone#1961]
### 🎮 Game Request

# Game logic and basic description
A pretty darn difficult asteroid shooter game with realistic inertia and unconventional controls.

### Point down the features

# Game points
- Hard to play but interesting.

### Select program in which you are contributing

GSSoC23, Other

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Killer2OP , You can't have another issue before completing the previous one 😀 
 you already have the following 1 open issues 👀 ! :

#1960

**Comment by kunjgit** [comment]
Hey @Killer2OP ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by kunjgit** [comment]
Hey @Killer2OP ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)
