### ISSUE TITLE
[New game]: Block Ninja

### ISSUE THREAD

**Issue by saikiranreddy201** [kunjgit/GameZone#1963]
### 🎮 Game Request

Block Ninja is a thrilling slicing game where you become a ninja warrior and slice floating blocks with precision. Test your reflexes, slice through blocks, and aim for high scores. Sharpen your blade and become the ultimate Block Ninja champion!
Even one miss of a block results in a game over.

### Point down the features

The user gets points when he correctly slices a block 
He loses the game if he misses it.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @saikiranreddy201 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @saikiranreddy201 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
