### ISSUE TITLE
[New game]: Fast fingers Keyboard Hero game

### ISSUE THREAD

**Issue by Bhuvanchand26** [kunjgit/GameZone#1968]
### 🎮 Game Request

We'll have played this type of game, this is not only a game this can be used to learn that typing skill.
In here keyboard is shown and some keys get highlighted the player has to type those and wait for another. the speed goes on increasing and the player must be able to catch the speed.The

### Point down the features

Type those letters which are shown by the monitor, get the speed too.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Bhuvanchand26 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @Bhuvanchand26 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
