### ISSUE TITLE
[Documentation Bug]: Improving the Project No. 248 bug

### ISSUE THREAD

**Issue by 5h0ov** [kunjgit/GameZone#1970]
### Describe the bug ✍️

Describe your bug here

![image](https://github.com/kunjgit/GameZone/assets/83227649/b456ea0d-d8d8-4766-9226-9b97b8463482)

I would like to fix it for GSSoC '23!

### Provide step by step information reproduce the bug 📄

Description

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @5h0ov , You can't have another issue before completing the previous one 😀 
 you already have the following 1 open issues 👀 ! :

#1969

**Comment by kunjgit** [comment]
Hey @5h0ov ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by kunjgit** [comment]
Hey @5h0ov ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)
