### ISSUE TITLE
[New game]: Pokemon Ball Finder game

### ISSUE THREAD

**Issue by abhinav-m22** [kunjgit/GameZone#1976]
### 🎮 Game Request

I want to add a Pokemon game using HTML, CSS, and JavaScript, where players control a character using arrow keys to search and collect Pokeballs, earning points to win the game. 
The game will offer an immersive and enjoyable experience to the user.

### Point down the features

Player Control: Player control using arrow keys to move the character across the game world. Allows smooth movement and responsive controls to provide an engaging gameplay experience.

Pokeball Collection: Pokeballs throughout the game world that players must collect to earn points. Logic to track the number of collected Pokeballs and update the player's score accordingly.

Obstacles and Challenges: Obstacles and challenges, such as obstacles that block the player's path or enemies that must be avoided. Colliding with obstacles or enemies results in appropriate consequences, such as losing points or health.

Power-ups and Bonuses: Power-ups and bonuses that players can collect to enhance their gameplay experience. Power-ups could include temporary invincibility, increased speed, or bonus points, adding excitement and strategic choices to the game.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @abhinav-m22 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @abhinav-m22 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
