### ISSUE TITLE
[New game]: Super Mario ( Classis game )

### ISSUE THREAD

**Issue by Bhuvanchand26** [kunjgit/GameZone#1980]
### 🎮 Game Request

Super Mario is a classic game played by Many of us.
here the play can be able to move forward and backward and can jump, player has job to collect coins and exacpe from some creatures

### Point down the features

controls are up , left and right and can jump

![image](https://github.com/kunjgit/GameZone/assets/131843589/3f6fb983-0438-4151-be8a-c9d11fd5e2d1)

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Bhuvanchand26 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @Bhuvanchand26 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
