### ISSUE TITLE
[New game]: Canvas Basketball Game

### ISSUE THREAD

**Issue by OMKAR-KALEPU** [kunjgit/GameZone#1981]
### 🎮 Game Request

Game logic and basic description
Test your shooting skills and aim to score as many baskets as possible within a time limit. Adjust your shot angle and power, beat your high score, and immerse yourself in the dynamic gameplay.

### Point down the features

Game points
- Collision Detection
- Animated Sprites after making three shots in a row
- Shot power based on time
- Shot trajectory based on indicated angle

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @OMKAR-KALEPU ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @OMKAR-KALEPU ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
