### ISSUE TITLE
[New game]: Guess The Movie

### ISSUE THREAD

**Issue by sabhisharma-ise** [kunjgit/GameZone#1983]
### 🎮 Game Request

"Guess The Movie" is a mini CSS game designed to test your knowledge of popular movies. The objective of the game is to correctly identify the title of the movie based on a series of visual clues displayed on the screen.

### Point down the features

Visual clues: The game relies on visual cues to represent different movies, challenging players to decipher the hints and guess the correct titles.
Grid-based gameplay: The movies are arranged in a grid format, providing a structured and organized interface for players to interact with.
Guessing mechanism: Players can input their guesses by clicking on a square and typing their answer, making it interactive and engaging.
Instant feedback: The game provides immediate feedback by revealing the correct movie title and indicating whether the guess was correct or incorrect.
Score tracking: The game keeps track of your score, allowing you to see how many movies you guessed correctly.
CSS-based design: The game's visuals and interactions are created using CSS (Cascading Style Sheets), showcasing the power of CSS in creating interactive experiences.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @sabhisharma-ise ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @sabhisharma-ise! 
We are already having a similar game request in #1790 👀 
Make sure you come up with a cool unique idea 😀 
 Waiting for your new game idea 💗.

**Comment by kunjgit** [comment]
Hey @sabhisharma-ise ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
