### ISSUE TITLE
[Pac-man Game]: 

### ISSUE THREAD

**Issue by Explorer003** [kunjgit/GameZone#199]
### 🎮 Game Request

- Pac-Man is a classic arcade game that was first released in 1980. 
- It revolves around a yellow character named Pac-Man who navigates through a maze, consuming pellets while avoiding ghosts. 
- The goal is to clear all the pellets on the screen and earn as many points as possible.
- The game constantly checks for collisions between Pac-Man and the maze walls, pellets, power pellets, and ghosts. When Pac-Man encounters a pellet, it is removed from the maze, and the player earns points
-  If Pac-Man consumes a power pellet, the ghosts become vulnerable, and Pac-Man can eat them for additional points. However, if a ghost touches Pac-Man without the effects of a power pellet, Pac-Man loses a life.
- The game continues until Pac-Man loses all lives or completes all levels, with the goal of achieving the highest score possible.

### Point down the features

Here are the key features and logic of the Pac-Man game:

- **Maze**: The game takes place in a maze consisting of walls and corridors. The maze layout remains the same throughout the game.

- **Pac-Man**: The player controls Pac-Man, a circular character that moves through the maze. Pac-Man can move in four directions: up, down, left, and right.
 
- **Pellets**: The maze contains small dots called pellets or Pac-dots. Pac-Man must eat all the pellets in the maze to complete a level. Each pellet consumed earns the player points.
 
- **Ghosts**: The maze is inhabited by four ghosts: Blinky (red), Pinky (pink), Inky (cyan), and Clyde (orange). The ghosts move around the maze, attempting to catch Pac-Man. If a ghost touches Pac-Man without the effects of a power pellet, Pac-Man loses a life.
 
- **Lives**: Pac-Man starts the game with a certain number of lives. Losing a life occurs when Pac-Man is caught by a ghost. If all lives are lost, the game is over. Extra lives can be earned by reaching a certain score threshold.

- **Score**: The player earns points throughout the game by eating pellets and ghosts. The score increases with each pellet eaten and increases significantly when consuming vulnerable ghosts.
 
- **Levels**: As the player clears all the pellets in a level, they progress to the next, which features a new maze layout. With each level, the game becomes progressively more challenging, with faster ghosts and more complex mazes.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Explorer003 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @Explorer003 👋!
 
  @kunjgit here, 
 We have this annoucement to make 📢!! 
 We have updated our README 🚀 
 Make sure you follow proper guideline to raise your next issues !! 
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG) if you haven't 😇 
  Thank you 💗!

**Comment by kunjgit** [comment]
Hey @Explorer003 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
