### ISSUE TITLE
[New game]: Enduro ( Retro car game )

### ISSUE THREAD

**Issue by Bhuvanchand26** [kunjgit/GameZone#1990]
### 🎮 Game Request

we all have played this game in our childhood, this is a simple game that uses a bit of js 
player get to control through his keyboard up, left and right. On colliding with other cars player's card get decreased.
This game doesn't need any description, because this was played by us.

### Point down the features

We have controls to move forward, left and right. Player has to avoid getting collided to other cars.

![image](https://github.com/kunjgit/GameZone/assets/131843589/4363e7ab-ee8d-41aa-9310-dc3055b8bf17)

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Bhuvanchand26 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @Bhuvanchand26 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
