### ISSUE TITLE
[New game]: Wault Master game

### ISSUE THREAD

**Issue by Vedansh-777** [kunjgit/GameZone#1992]
### 🎮 Game Request

- **Description**
A TailwindCSS based Javascript game in which the user must guess the completely random vault code in order to win.

- **Features**
Fully Responsive (Cross-platform)
Written in Tailwind and Pure JS.
IOS-Like design.
Dark mode. (no toggle, yet.)

### Point down the features

To play this game, keep the following in mind:

You have four attempts to guess a four-digit code.
For each 4-digit guess, you will get either No color, Blue, or Yellow.
If the number you provided contains a yellow digit, this indicates that the yellow digit EXISTS in the vault code but is not in the correct location.
On the other hand, if the number you supplied contains a blue digit, it signifies that the blue digit exists in the vault code and is in the correct location.
A no-color digit indicates that the digit does not exist in the vault code.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Vedansh-777 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @Vedansh-777 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
