### ISSUE TITLE
Make Raising_Fighting_Spirits game responsive[Bug]: 

### ISSUE THREAD

**Issue by rahulrana701** [kunjgit/GameZone#1993]
### Give a brief about the bug ✍️

The game is not responsive I would like to make it responsive for all devices
<img width="306" alt="Screenshot 2023-06-25 125450" src="https://github.com/kunjgit/GameZone/assets/123585591/8a0bbe88-eb61-4653-8a3c-36bdd9c6a5c9">

### What is the expected behavior? 🤔

The game should be responsive for all devices

### Provide step by step information reproduce the bug 📄

Description

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @rahulrana701 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @rahulrana701 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
