### ISSUE TITLE
[New game]:  Advanced Stone Paper Scissor ( AI -Based)

### ISSUE THREAD

**Issue by PatilHarshh** [kunjgit/GameZone#1995]
### 🎮 Game Request

Game logic and basic description
Strong AI based stone paper scissor project

### Point down the features

Game points camera based

https://github.com/kunjgit/GameZone/assets/120102234/59c7d858-358e-4f03-a8ef-3352d45762e4

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @PatilHarshh ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by PatilHarshh** [comment]
@kunjgit Please assign it brother

**Comment by kunjgit** [comment]
Hello @PatilHarshh, Time's Uppp!⏰ 
 Sorry for closing your issue! 
 But it's more than a week since we haven't received anything from your side 😢 . 
 Come up with new ideas, create a new issue and make sure you finish it within a week! 🔥 
 All the best! 🚀 
 Happy Hacking! 💗

**Comment by kunjgit** [comment]
Hey @PatilHarshh ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by PatilHarshh** [comment]
@kunjgit hello,  I was busy in end sem examination, sorry for delay, can I able to raise same issue
