### ISSUE TITLE
[Feature] : Filter method

### ISSUE THREAD

**Issue by PatilHarshh** [kunjgit/GameZone#1996]
### Is your enhancement request related to a problem? Please describe.➕

Game enhancement : adding filtering methods which filters the similar types of games 

### Describe the solution you'd like

Solution steps : adding javascript logic

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @PatilHarshh , You can't have another issue before completing the previous one 😀 
 you already have the following 1 open issues 👀 ! :

#1995

**Comment by kunjgit** [comment]
Hey @PatilHarshh ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by kunjgit** [comment]
Hey @PatilHarshh! 🙂 
 It seems like you are not following proper guidelines !! 👀 
 Read documentation properly !!🙏 
 If you have any queries reach out to us on [Discord🕹️](https://discord.gg/fgwk4XZfxG) .

**Comment by kunjgit** [comment]
Hey @PatilHarshh ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by PatilHarshh** [comment]
@gurjeetsinghvirdee and @kunjgit working on this issue now
