### ISSUE TITLE
[New game]: Melody Master

### ISSUE THREAD

**Issue by Atulsingh30** [kunjgit/GameZone#1999]
### 🎮 Game Request

"Melody Master" is an immersive piano frontend project that combines the joy of playing music with interactive gameplay. The game offers a realistic and visually appealing virtual piano interface, complete with authentic sound effects, to create an engaging and authentic musical experience.

### Point down the features

1. Interactive UI
2. Easy to use
3. Minimalist

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Atulsingh30 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hello @Atulsingh30, Time's Uppp!⏰ 
 Sorry for closing your issue! 
 But it's more than a week since we haven't received anything from your side 😢 . 
 Come up with new ideas, create a new issue and make sure you finish it within a week! 🔥 
 All the best! 🚀 
 Happy Hacking! 💗

**Comment by kunjgit** [comment]
Hey @Atulsingh30 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by kunjgit** [comment]
Hey @atulsingh30 ! , This issue is already assigned to @atulsingh30. 💗 
 You can work on other issues 🚀 
 If there is anything wrong you can contact us on [Discord🕹️](https://discord.gg/fgwk4XZfxG)👀
