### ISSUE TITLE
[New game]: Simon Game Challenge 

### ISSUE THREAD

**Issue by rajatnai49** [kunjgit/GameZone#2]
### 🎮 Game Request

Simon is a classic electronic memory game that was first introduced in the late 1970s. The game consists of a small handheld device with four colored buttons, which light up and emit sounds in a specific sequence. The player must replicate this sequence by pressing the buttons in the correct order. Each time the player successfully replicates the sequence, the game adds an additional step, making the sequence longer and more complex. The game continues until the player makes an incorrect move and loses.

### Point down the features

- Simple gameplay: The Simon game is easy to learn and can be played by people of all ages.
- Increasing difficulty: As the player progresses through the game, the sequences become longer and more complex, making it more challenging.
- Audio and visual feedback: The game provides both audio and visual feedback to the player, helping them to keep track of the sequence and their progress.
- Competitive gameplay: The game can be played solo or with friends, allowing for a competitive element to be added to the gameplay.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
@rajatnai49 you can work on this issue make sure you follow the guidelines properly .
Happy hacking 🔥
