### ISSUE TITLE
[New game]: Whack a Mole Game

### ISSUE THREAD

**Issue by anshulgupta48** [kunjgit/GameZone#20]
### 🎮 Game Request

I will create the game skeleton of Whack a Mole Game first and the logic of the Game is You Have to Whack the Mole again and again as Much as You Can in 30 Seconds .This will be done in HTML, CSS, JS.

### Point down the features

1. Your High Score will be stored after every game & you can come again and again to beat it.
2. This will be responsive that it can be played in any display size.
3. There will be Animation on winning also.
4. There will be some Background Audio when you start the game to make the game interesting.
5. There will be a Beaten Audio which will play when you Whack the Mole.
6. If You Beat the Previous High Score then Your High Score will also Update Simultaneously according to your Score.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by vaishnavi-3969** [comment]
I am interested in working on this issue under GSSoC'23

**Comment by kunjgit** [comment]
Hey @anshulgupta48  ! Thank you for raising an issue 💗 You have been assigned this issue you can start working on the issue 🎮

**Comment by kunjgit** [comment]
Hey @anshulgupta48 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
