### ISSUE TITLE
[Enhancement]: Tower of Hanoi Game

### ISSUE THREAD

**Issue by AvinashChourasia** [kunjgit/GameZone#2006]
### Is your enhancement request related to a problem? Please describe.➕

Game enhancement
It's an enhancement in the design of the webpage. The current UI of the Tower of Hanoi requires enhancement to provide a more intuitive and visually appealing user experience.

### Describe the solution you'd like

The enhancement includes

Alignment of the Game Board to center
Styling the Game Board
Player Turn Indicator
Interactive Background

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @AvinashChourasia , You can't have another issue before completing the previous one 😀 
 you already have the following 1 open issues 👀 ! :

#2001

**Comment by kunjgit** [comment]
Hey @AvinashChourasia ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by kunjgit** [comment]
Hey @AvinashChourasia ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by AvinashChourasia** [comment]
I completed the previous one.
