### ISSUE TITLE
[New game]: Pig Game

### ISSUE THREAD

**Issue by lmalkam** [kunjgit/GameZone#2008]
### 🎮 Game Request

Pig Game is a two-player dice game.

Every turn the player will roll the dice and he can either hold it take a risk to again roll the dice and add it to the score and if 1 occurs he will loose the sum and it will become zero and if he holds the score, the max score will be updated if greater and automatically the turn will be given to next person

### Point down the features

It will be created using HTML CSS and javascript.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @lmalkam , You can't have another issue before completing the previous one 😀 
 you already have the following 1 open issues 👀 ! :

#1925

**Comment by kunjgit** [comment]
Hey @lmalkam ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by kunjgit** [comment]
Hey @lmalkam ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @lmalkam! 
We are already having a similar game request in #1696 👀 
Make sure you come up with a cool unique idea 😀 
 Waiting for your new game idea 💗.
