### ISSUE TITLE
[Enhancement]: Light/Dark Theme controller button

### ISSUE THREAD

**Issue by kaashikaagrawal** [kunjgit/GameZone#2011]
### Is your enhancement request related to a problem? Please describe.➕

The theme controller button is a plain slider right now. I can change the icon to a better one that matches the theme of the website. Assign this issue to me. 

### Describe the solution you'd like

I will try and modify the theme controller to match the theme of the site. I will do this by changing it's css, adding an icon, etc.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @kaashikaagrawal ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @kaashikaagrawal ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
