### ISSUE TITLE
[New game]: Circus Charly

### ISSUE THREAD

**Issue by linga66** [kunjgit/GameZone#2014]
### 🎮 Game Request

One of the most common obstacles in Circus Charlie is the fire ring. These rings are located throughout the levels and Charlie must jump over them to avoid being burned. Another common obstacle is the ring of death. This ring is located at the end of each level and Charlie must jump through it to complete the level.
If Charlie gets hit by fire, he will lose a life. If he falls off the lion, he will also lose a life. The game ends when Charlie loses all of his lives.

### Point down the features

Circus Charly is another most popular Console Game in which the character is on the running Lion and we have to make the lion jump without getting collided with the Fire and Ring.

Assign me this 

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @linga66 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by linga66** [comment]
@kunjgit assign me

**Comment by kunjgit** [comment]
Hey @linga66 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
