### ISSUE TITLE
[New game]: slide puzzle game

### ISSUE THREAD

**Issue by SimranLahrani842** [kunjgit/GameZone#2015]
### 🎮 Game Request

Game logic and basic description
Given a puzzle u need to form the correct puzzle from given 9 pieces.

### Point down the features

Game points
After forming the puzzle the player wins the game.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @SimranLahrani842 , You can't have another issue before completing the previous one 😀 
 you already have the following 1 open issues 👀 ! :

#1692

**Comment by kunjgit** [comment]
Hey @SimranLahrani842 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by kunjgit** [comment]
Hey @SimranLahrani842 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @SimranLahrani842! 
We are already having a similar game request in #1944 👀 
Make sure you come up with a cool unique idea 😀 
 Waiting for your new game idea 💗.

**Comment by SimranLahrani842** [comment]
> Hey @SimranLahrani842! We are already having a similar game request in #1944 👀 Make sure you come up with a cool unique idea 😀 Waiting for your new game idea 💗.

This is a doreamon puzzle game and not number 
@kunjgit

**Comment by SimranLahrani842** [comment]
> Hey @SimranLahrani842! We are already having a similar game request in #1944 eyes Make sure you come up with a cool unique idea grinning Waiting for your new game idea heartpulse.

Assign me now @kunjgit
