### ISSUE TITLE
[New game]: GSSOC '23: Flag Guess Game

### ISSUE THREAD

**Issue by sujanrupu** [kunjgit/GameZone#2023]
## Game logic and basic description:
A multiplayer game where players take turns guessing the country based on its flag.
## Tech Used:
HTML, CSS, JavaScript

## Game points:
- Simple and intuitive gameplay for multiplayer fun.

- Flags from various countries to guess.
- Colorful and responsive design.
- Smooth transitions and hover effects for a visually appealing experience.
- Easy-to-understand instructions and feedback messages.
- The game can be easily customized by adding or modifying the flag list.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @sujanrupu ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @sujanrupu ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
