### ISSUE TITLE
[New game]: Crack-The-Code

### ISSUE THREAD

**Issue by pavitrachavda97** [kunjgit/GameZone#2027]
### 🎮 Game Request

# Game logic and basic description
A player has to guess the 3 numbers in order to win this game by using 5 simple hints. If player guess it correct than player will win else game restarted.

### Point down the features

# Game points
- Generate 3 number code
- Provide hints
- Player's guess
- Submit guess
- Check for correct submission
- If true win else loss
- Loop continues

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @pavitrachavda97 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @pavitrachavda97 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
