### ISSUE TITLE
[New game]: Fifteen puzzle game

### ISSUE THREAD

**Issue by srujana-16** [kunjgit/GameZone#2029]
### 🎮 Game Request

The Fifteen Puzzle is a classic sliding puzzle game where the goal is to rearrange the tiles in numerical order by sliding them into the empty space. This implementation of the game is built using HTML, CSS, and JavaScript.

### Point down the features

- The game consists of a 4x4 grid with fifteen numbered tiles and one empty space.
- To make a move, click on a tile adjacent to the empty space. The clicked tile will slide into the empty space.
- The goal is to arrange the tiles in numerical order, from 1 to 15, starting from the top-left corner and leaving the bottom-right cell empty.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @srujana-16 , You can't have another issue before completing the previous one 😀 
 you already have the following 1 open issues 👀 ! :

#1954

**Comment by kunjgit** [comment]
Hey @srujana-16 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by kunjgit** [comment]
Hey @srujana-16 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @srujana-16! 
We are already having a similar game request in #1944 👀 
Make sure you come up with a cool unique idea 😀 
 Waiting for your new game idea 💗.
