### ISSUE TITLE
[New game]: Add Pacman Game

### ISSUE THREAD

**Issue by abhinav-m22** [kunjgit/GameZone#2033]
### 🎮 Game Request

I want to add a Pacman game developed using HTML, CSS, and JavaScript, inspired by the classic arcade game. 
Players will control Pacman, guiding him through a maze to collect pellets and avoid ghosts. The objective is to clear the maze by eating all the pellets and earning a high score.

### Point down the features

**Player Control:** Responsive and smooth controls to allow players to navigate Pacman through the maze using arrow keys or on-screen touch controls. Precise and enjoyable movement mechanics.

**Pellet Collection:** The maze is filled with pellets that Pacman must consume to earn points. Differentiation between regular pellets and power pellets that enable Pacman to eat ghosts.

**Ghosts AI:** Intelligent ghost AI that chases Pacman through the maze. Different ghost behaviors, such as random movement, target chasing, or ambushing strategies. Challenging and dynamic ghost movements to create an engaging gameplay experience.

**Maze Layout and Level Design:** Visually appealing mazes with walls, corridors, and various obstacles.

**Score Tracking and High Scores:** A scoring system that tracks the player's score throughout the game.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @abhinav-m22 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @abhinav-m22! 
We are already having a similar game request in #1905 👀 
Make sure you come up with a cool unique idea 😀 
 Waiting for your new game idea 💗.

**Comment by kunjgit** [comment]
Hey @abhinav-m22 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
