### ISSUE TITLE
[New game]: Bit Maze - Platformer Maze

### ISSUE THREAD

**Issue by sabhisharma-ise** [kunjgit/GameZone#2034]
### 🎮 Game Request

"Bit Maze - Platformer Maze" is a game that combines elements of a platformer and a maze. The goal of the game is to navigate a character through a series of mazes and reach the exit point while avoiding obstacles.

### Point down the features

Platformer gameplay: The game incorporates the mechanics of a platformer, requiring the player to control a character's movements and jumps.
Arrow key controls: The character can be moved left and right using the arrow keys on the keyboard, providing a simple and intuitive control scheme.
Jumping ability: The character can jump to overcome gaps and avoid obstacles, adding an extra dimension to the gameplay.
Obstacles and hazards: The mazes contain hazards such as spikes and moving platforms that must be avoided to progress safely.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @sabhisharma-ise ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
