### ISSUE TITLE
[New game]: Pacman Game using Javascript

### ISSUE THREAD

**Issue by abhinav-m22** [kunjgit/GameZone#2035]
### 🎮 Game Request

I want to add a Pacman game developed using HTML, CSS, and JavaScript.
Player will control Pacman, guiding him through a path to collect pellets and avoid ghosts. 
The objective is to clear the path by eating all the pellets in the maze.

### Point down the features

Responsive and smooth controls to allow players to navigate Pacman through the maze using arrow keys or on-screen touch controls. Precise and enjoyable movement mechanics.
The maze is filled with pellets that Pacman must consume to earn points. Differentiation between regular pellets and power pellets that enable Pacman to eat ghosts.
Visually appealing mazes with walls and various obstacles will be present.

<img width="960" alt="Screenshot 2023-06-26 101321" src="https://github.com/abhinav-m22/GameZone/assets/113239388/6f54191b-41a7-474b-b78d-c561ea2039a9">

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @abhinav-m22 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @abhinav-m22 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
