### ISSUE TITLE
[New game]: Hold the Cloud

### ISSUE THREAD

**Issue by Durgesh4993** [kunjgit/GameZone#2045]
### 🎮 Game Request

Game logic and basic description
You junt need to hold the cloud between the both line on top and bottom

Screenshort:
![image](https://github.com/kunjgit/GameZone/assets/98798977/7fc0a39c-7493-430a-8553-9e593e10a1fd)

### Point down the features

Demo Vedio:

https://github.com/kunjgit/GameZone/assets/98798977/5112303a-bfbd-4cc0-bf3b-6a2890e2553f

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Durgesh4993 , You can't have another issue before completing the previous one 😀 
 you already have the following 1 open issues 👀 ! :

#1897

**Comment by kunjgit** [comment]
Hey @Durgesh4993 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
