### ISSUE TITLE
[New game]: T-rex Run

### ISSUE THREAD

**Issue by akankshachanana1** [kunjgit/GameZone#2049]
### 🎮 Game Request

Game logic and basic description
The game features a  Tyrannosaurus rex (T-Rex) character, which is controlled by the player. The T-Rex starts running automatically from the left side of the screen, and the objective is to help it avoid obstacles and survive for as long as possible.
The primary obstacle in the game is cacti, which are placed at varying heights along the ground. The player must time their jumps to make the T-Rex jump over these cacti. 

### Point down the features

Game points
The game's controls are straightforward and typically involve using the spacebar or up arrow key to make the T-Rex jump.
Timing is crucial to clear the obstacles successfully, as mistimed jumps or crouches will result in the T-Rex colliding with an obstacle and the game ending.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @akankshachanana1 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @akankshachanana1 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
