### ISSUE TITLE
[New game]: Cosmic Coin Collector

### ISSUE THREAD

**Issue by U-DAY-333** [kunjgit/GameZone#2051]
### 🎮 Game Request

Welcome to Cosmic Coin Collector, a thrilling space adventure where you embark on a mission to collect coins, dodge obstacles, and overcome hurdles while exploring a distant planet. Your goal is to gather as many coins as possible, destroy asteroids, and cover the maximum distance to achieve the highest score. Get ready to immerse yourself in an action-packed journey through the cosmos!

Game Logic:

Controls:

- Use the arrow keys or swipe gestures to navigate your spaceship.
- Press the spacebar or tap on the screen to shoot projectiles and destroy asteroids.

Gameplay:

- The game is set on a visually stunning planet with a variety of landscapes, including mountains, canyons, and forests.
- Coins will be scattered throughout the planet, appearing at random locations.
- As you traverse the planet, various hurdles and obstacles will come in your path, such as meteor showers, enemy spacecraft, or laser barriers.
- You must maneuver your spaceship skillfully to avoid collisions with the hurdles and collect as many coins as possible.
- Some coins may require precise movements or special maneuvers to reach.
- To destroy asteroids, aim and shoot projectiles by pressing the spacebar or tapping on the screen. Each destroyed asteroid adds to your score.

### Point down the features

Scoring:

- The score is calculated based on three factors: coins collected, asteroids destroyed, and total distance traveled.
- Each coin collected adds a certain number of points to your score.
- Destroying an asteroid grants additional points, depending on its size and difficulty.
- Distance traveled contributes to your score. The longer you survive and explore, the higher your score will be.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @U-DAY-333 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @U-DAY-333 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
