### ISSUE TITLE
[New game]: Jamie Coulter

### ISSUE THREAD

**Issue by Aryan5464** [kunjgit/GameZone#2056]
### 🎮 Game Request

Game logic and basic description

The logic behind it is actually relatively simple and uses a 7+-year-old technique.
By clicking on an arrow (in this case a label), it checks the relevant input, and then using the: checked pseudo selector, we can traverse down the DOM the correct amount of iterations and shift the entire viewport a whole 'segment' over. 
The lifts work entirely the same way except instead when we click down, we are actually checking the segment below.

### Point down the features

Game points
- The game works only with a mouse 
- The game is very easy and it is for 7+ years.

https://github.com/kunjgit/GameZone/assets/111825539/968081d2-3ed4-46df-882b-8deafe51059f

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Aryan5464 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by Aryan5464** [comment]
assign

**Comment by Aryan5464** [comment]
@kunjgit assign

**Comment by kunjgit** [comment]
Hello @Aryan5464, Time's Uppp!⏰ 
 Sorry for closing your issue! 
 But it's more than a week since we haven't received anything from your side 😢 . 
 Come up with new ideas, create a new issue and make sure you finish it within a week! 🔥 
 All the best! 🚀 
 Happy Hacking! 💗

**Comment by kunjgit** [comment]
Hey @Aryan5464 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
