### ISSUE TITLE
[New game]: Pikachu Volleyball

### ISSUE THREAD

**Issue by OMKAR-KALEPU** [kunjgit/GameZone#2058]
### 🎮 Game Request

Game logic and basic description
A 2 player volleyball game with player as pikachu's.
The game will end when one of the player reaches 21 points.

### Point down the features

Game points
- When ball falls down on one side of the court, the player in the other court is awarded one point.
- The first to reach 21 wins.
- The points can be extended in the settings menu.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @OMKAR-KALEPU ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @OMKAR-KALEPU ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
