### ISSUE TITLE
[New game]: Bullseye Game

### ISSUE THREAD

**Issue by Nishitbaria** [kunjgit/GameZone#2061]
### 🎮 Game Request

I would like to propose the addition of a new game called "Bullseye Target" to the website. This game challenges players to aim carefully and hit the bullseye target using an arrow bow. The game offers unlimited arrows, and there is no time limit, allowing players to focus on their aim and accuracy.
Gameplay Overview:
1. The game features a bullseye target displayed on the screen.
2. Players can control the direction and power of their shot by adjusting the angle and strength of the arrow bow.
3. The objective is to hit the bullseye, which is located at the center of the target.
4. Players can shoot as many arrows as they want to improve their accuracy and aim for a perfect bullseye.
5. The game provides visual feedback, such as a scoring system or animations, to indicate how close the arrow is to the bullseye.

### Point down the features

1. The game features a bullseye target displayed on the screen.
2. Players can control the direction and power of their shot by adjusting the angle and strength of the arrow bow.
3. The objective is to hit the bullseye, which is located at the center of the target.
4. Players can shoot as many arrows as they want to improve their accuracy and aim for a perfect bullseye.
5. The game provides visual feedback, such as a scoring system or animations, to indicate how close the arrow is to the bullseye.
Implementation Details:
To implement the "Bullseye Target" game, the following components will be required:
1. Visual assets: Design and create a visually appealing bullseye target, arrow bow, and arrow sprite or graphic elements.
2. Game logic: Develop the game mechanics, including arrow physics, aiming controls, and hit detection.
3. User interface: Design a user-friendly interface that provides instructions, score feedback, and an option to reset the game.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Nishitbaria ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @Nishitbaria ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
