### ISSUE TITLE
[New game]: Surds Game 

### ISSUE THREAD

**Issue by shubhisingh184** [kunjgit/GameZone#2062]
### 🎮 Game Request

Game logic and basic description
Surds game is a survival game where player need to stay alive in a battle game and the player should collect words that was in his mission.

### Point down the features

Game points

1. To begin the game, first you must fill the mission letters and the no. of enemies in the form.
2. Then you will enter in the game, and you have to dodge the enemies (red balls).
3. You can move the player by using Up, Down, Left and Right keys.
4. By using the movement, you have to collect the mission letters to complete your mission.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @shubhisingh184! 
We are already having a similar game request in #2028 👀 
Make sure you come up with a cool unique idea 😀 
 Waiting for your new game idea 💗.

**Comment by kunjgit** [comment]
Hey @shubhisingh184 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by kunjgit** [comment]
Hey @shubhisingh184 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)
