### ISSUE TITLE
[New game]:  Adding Firedog Adventure Game

### ISSUE THREAD

**Issue by Nishitbaria** [kunjgit/GameZone#2065]
### 🎮 Game Request

Are you ready to test your skills and have a good laugh at the same time? Look no further than "Firedog Adventure"!

In this exciting game, you take on the role of a courageous firedog soaring through the skies, facing a swarm of mischievous flaming ravens determined to stop you. These fiery avian foes come in various sizes and vibrant colors, leaving behind dazzling trails of sparks as they soar. As you navigate the skies, your mission is to skillfully maneuver, avoiding collisions with the ravens and aiming to achieve the highest score possible. Be alert and agile, dipping, diving, and dodging your way through the relentless flock of ravens.

But beware! If one of those sneaky ravens manages to hit you, get ready for an explosive and hilarious animation that will undoubtedly bring a smile to your face. Get back up, shake off the ashes, and continue your Firedog Adventure!

### Point down the features

Features
-Smooth gameplay
-Comical animations
-Variety of ravens
-Soundtrack
-High scores
https://github-production-user-asset-6210df.s3.amazonaws.com/85815172/248575377-4f03f119-3e83-4ae9-99e5-9f3b972b9d79.mp4

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Nishitbaria ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @Nishitbaria ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by kunjgit** [comment]
Hey @Nishitbaria ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
