### ISSUE TITLE
[Enhancement]: Error in script.js file of Tic Tac Toe game 

### ISSUE THREAD

**Issue by Abhishek-Rajput-81** [kunjgit/GameZone#2066]
## There are 2 errors in the script.js file :
 - First, the function "reset.addEventListener" does not have a closing parenthesis.
 
![image](https://github.com/kunjgit/GameZone/assets/96196696/826f1f18-e1dc-4e9c-8656-9b250684b53c)
- Second, the "excited.gif" does not disappear on clicking the Reset button. 

### Describe the solution you'd like

This can be achieved by improving the code of the js file.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Abhishek-Rajput-81 , You can't have another issue before completing the previous one 😀 
 you already have the following 1 open issues 👀 ! :

#1879

**Comment by kunjgit** [comment]
Hey @Abhishek-Rajput-81 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by kunjgit** [comment]
Hey @Abhishek-Rajput-81 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)
