### ISSUE TITLE
[Enhancement]: Adding Animated Particles in the Background of the Website

### ISSUE THREAD

**Issue by 5h0ov** [kunjgit/GameZone#2070]
### Is your enhancement request related to a problem? Please describe.➕

# Enhancement

I want to add animated floating particles in the background of the website to give it more life.

# Idea Example:

![particles](https://github.com/kunjgit/GameZone/assets/83227649/fe92f49a-2bf1-48dc-ba73-cec882e94751)

It would be great to contribute in this open source for GSSoC '23!!

### Describe the solution you'd like

# Solution steps:

- I would make a separate particle css file and link it to main index.html
- I will make it compatible with the Light/Dark Mode

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @5h0ov ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @5h0ov ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
