### ISSUE TITLE
[New game]: Chicken cannon

### ISSUE THREAD

**Issue by Bhuvanchand26** [kunjgit/GameZone#2071]
### 🎮 Game Request

The chickens have discovered a new invention... the CANNON. So obviously they load their comrades in and try to DESTROY humanity! In the name of science. The instructions are simple just have to release the chicken at certain projectile motion
a 

### Point down the features

How to play ?
▫ Click to launch your chicken out of the cannon.
▫ Hold down to use your rocket. (Don't run out of fuel)
▫ DESTROY everything in your way.

![image](https://github.com/kunjgit/GameZone/assets/131843589/616e36ad-70dd-4e04-86b7-6cc704a02ab5)

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Bhuvanchand26 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @Bhuvanchand26 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
