### ISSUE TITLE
[New game]: Guess the Pokémon

### ISSUE THREAD

**Issue by akhilender-bongirwar** [kunjgit/GameZone#2076]
### 🎮 Game Request

Game logic and basic description
"Guess the Pokémon" is an exciting game that challenges players to identify Pokémon based on their shadowy silhouettes. In this game, players are presented with a series of shadowy images representing different Pokémon species. The objective is to correctly guess the name of the Pokémon hidden behind the shadow within a limited number of attempts.

### Point down the features

Game points
This is a fun game.
The player gains points if he correctly guesses the name of the pokemon.
There will be a time limit of 10 seconds for each pokemon guess.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @akhilender-bongirwar ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @akhilender-bongirwar! 
We are already having a similar game request in #1790 👀 
Make sure you come up with a cool unique idea 😀 
 Waiting for your new game idea 💗.

**Comment by kunjgit** [comment]
Hey @akhilender-bongirwar ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
