### ISSUE TITLE
[New game]: Shadow PokeGuess

### ISSUE THREAD

**Issue by akhilender-bongirwar** [kunjgit/GameZone#2077]
### 🎮 Game Request

Game logic and basic description
"Shadow PokeGuess" is an exciting game that challenges players to identify Pokémon based on their shadowy silhouettes. In this game, players are presented with a series of shadowy images representing different Pokémon species. The objective is to correctly guess the name of the Pokémon hidden behind the shadow within a limited number of attempts.

### Point down the features

Game points
This is a fun game.
The player gains points if he correctly guesses the name of the pokemon.
There will be a time limit of 10 seconds for each pokemon guess.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @akhilender-bongirwar ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by akhilender-bongirwar** [comment]
Hey @kunjgit, I have a doubt not related to this game, can I add a game where I can use api to retrieve data for the game.
Please let me know... : )

**Comment by kunjgit** [comment]
Hey @akhilender-bongirwar ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
