### ISSUE TITLE
[New game]: Astray

### ISSUE THREAD

**Issue by linga66** [kunjgit/GameZone#2081]
### 🎮 Game Request

Astray is a 3D Adventure Game in which you have to move the ball inside the Maze and get out of it to reach the destination and win the game.

### Point down the features

Visuals: The game is presented in a 3D graphical environment, allowing players to experience immersive gameplay.
Controls: The controls are designed to provide a responsive and intuitive way for players to maneuver the ball through the maze.
Obstacles and Challenges: The maze may contain obstacles such as walls, moving platforms, gaps, locked doors, and other puzzles that require the player to solve them to progress.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @linga66 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @linga66 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
