### ISSUE TITLE
[New game]: Battleship Board Game

### ISSUE THREAD

**Issue by Vedansh-777** [kunjgit/GameZone#2082]
### 🎮 Game Request

Face against the computer in a daring game of chance as you attempt to locate and sink each other's ships.

Play on PC or mobile.

### Point down the features

Please select your ships on your board, then press "Start Game" and place your first guess on the guess board.

The computer will then automatically take a guess on your board and then you can guess again.

The game ends when either your or your opponent's ships are fully sunk.

Note: The locations of the computer's ships are logged to the console when "Start Game" is pressed if you are curious.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Vedansh-777 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @Vedansh-777 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by kunjgit** [comment]
Hello @Vedansh-777, Time's Uppp!⏰ 
 Sorry for closing your issue! 
 But it's more than a week since we haven't received anything from your side 😢 . 
 Come up with new ideas, create a new issue and make sure you finish it within a week! 🔥 
 All the best! 🚀 
 Happy Hacking! 💗

**Comment by kunjgit** [comment]
Hey @Vedansh-777 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by Vedansh-777** [comment]
> Hello @Vedansh-777, Time's Uppp!⏰
> Sorry for closing your issue!
> But it's more than a week since we haven't received anything from your side 😢 .
> Come up with new ideas, create a new issue and make sure you finish it within a week! 🔥
> All the best! 🚀
> Happy Hacking! 💗

@kunjgit @gurjeetsinghvirdee Why was this issue closed without merging my pull request ???

**Comment by kunjgit** [comment]
Hey @Vedansh-777 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
