### ISSUE TITLE
[New game]: 

### ISSUE THREAD

**Issue by sujitmemane** [kunjgit/GameZone#209]
### 🎮 Game Request

The game  I  have created is a fun and engaging mouse-clicking game with a time limit of 1 minute. The game logic involves a 3x3 grid layout with a total of 9 boxes. At the start of the game, a timer begins, and your lion logo is randomly placed in one of the boxes.
The objective of the game is to quickly locate and click on the box that contains the lion logo. Each time you successfully click on the correct box, you earn 1 point. After each successful click, the lion logo is randomly moved to another box within the grid.
The game continues for a duration of 1 minute, during which you aim to score as high as possible by clicking on the lion logo in each new location. The challenge lies in your ability to quickly identify the correct box before the lion logo moves again.

### Point down the features

Some key features of my game include:
1. Random placement of the lion logo: The lion logo is initially placed randomly in one of the boxes, ensuring each game session starts with a different configuration.
2. Time limit: The game is time-based, adding a sense of urgency and encouraging players to act swiftly.
3. Scoring system: Each successful click on the correct box earns the player 1 point, allowing for a competitive element and encouraging players to achieve high scores.
4. Dynamic movement: After every successful click, the lion logo is relocated to another random box, keeping the gameplay unpredictable and engaging.
5. Visual feedback: The game can provide visual feedback, such as highlighting the correct box or displaying a score counter, to enhance the player's experience and understanding of their progress.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @sujitmemane ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by sujitmemane** [comment]
Thank You Very Much for this opportunity

**Comment by kunjgit** [comment]
Hey @sujitmemane 👋!
 
  @kunjgit here, 
 We have this annoucement to make 📢!! 
 We have updated our README 🚀 
 Make sure you follow proper guideline to raise your next issues !! 
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG) if you haven't 😇 
  Thank you 💗!

**Comment by kunjgit** [comment]
Hello @sujitmemane, Time's Uppp!⏰ 
 Sorry for closing your issue! 
 But it's more than a week since we haven't received anything from your side 😢 . 
 Come up with new ideas, create a new issue and make sure you finish it within a week! 🔥 
 All the best! 🚀 
 Happy Hacking! 💗

**Comment by kunjgit** [comment]
Hey @sujitmemane ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
