### ISSUE TITLE
[New game]: Solitaire

### ISSUE THREAD

**Issue by AnkitaBarbora** [kunjgit/GameZone#2090]
### 🎮 Game Request

Solitaire is a classic card game that is played with a standard deck of 52 playing cards. The objective of the game is to organize all the cards into specific foundation piles, following certain rules and movements.

- The player starts by examining the face-up cards and moving them to build descending sequences of alternating colors. For example, a red 6 can be placed on a black 7.
- Aces (1s) are the foundation cards, and they can be moved to a foundation pile whenever they become available.
- Empty tableau spaces can be filled with any available card or a sequence of descending cards of alternating colors.
- Cards from the stock pile can be turned over one at a time and added to the tableau or foundation piles.
- If a face-down card is revealed in a tableau pile, it is turned face-up and becomes available for play.
- The player continues to build on the foundation piles, moving cards between tableau piles, and exposing face-down cards until no more moves are possible or the game is won.
- The game is won when all cards are successfully moved to the foundation piles according to their suits (hearts, diamonds, clubs, and spades) and in ascending order from Ace to King.

### Point down the features

Game points
- **Interactive Card Movement:** Enables players to interact with the cards by clicking and dragging them to move them between piles or to the foundation.
- **Timer:** A timer is added to track the player's progress and provide an element of challenge.
- **Scoring:** A scoring system is implemented based on the number of moves made, time taken, or a combination of both. Displaying the score to encourage players to beat their own records or compete with others.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @AnkitaBarbora ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hello @AnkitaBarbora, Time's Uppp!⏰ 
 Sorry for closing your issue! 
 But it's more than a week since we haven't received anything from your side 😢 . 
 Come up with new ideas, create a new issue and make sure you finish it within a week! 🔥 
 All the best! 🚀 
 Happy Hacking! 💗

**Comment by kunjgit** [comment]
Hey @AnkitaBarbora ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
