### ISSUE TITLE
[New game]: Ball_and_Glass

### ISSUE THREAD

**Issue by U-DAY-333** [kunjgit/GameZone#2095]
### 🎮 Game Request

Welcome to the Ball and Glass Challenge! Your task is to guide a ball into a series of glasses by strategically positioning a stopper. The ball moves in a two-dimensional space, bouncing up and down and left and right. Your goal is to stop the ball at the right moment and position so that it falls into the glass.

### Point down the features

Game pointsEach successful glass entry earns you a certain number of points based on the level's difficulty.
If you miss a glass or fail to position the stopper correctly, you don't earn any points for that round.
Your total score is calculated by summing up the points from each successful glass entry.
You can aim for a high score and challenge yourself to beat your previous record.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @U-DAY-333 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @U-DAY-333 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
