### ISSUE TITLE
[New Game] : Ludo game 

### ISSUE THREAD

**Issue by PriyankaTamhankar01** [kunjgit/GameZone#2099]
### 🎮 Game Request

Game logic and basic description
-  Implement the standard rules of Ludo, including the ability to send opponent tokens back to the starting area when landing on the same position.
-  Validate moves to ensure they adhere to the rules.
-  Handle special cases, such as rolling a 6 to get an extra turn.

### Point down the features

Game points

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @PriyankaTamhankar01 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by PriyankaTamhankar01** [comment]
please review my PR

**Comment by kunjgit** [comment]
Hey @PriyankaTamhankar01 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
