### ISSUE TITLE
[New game]: Ninety-nine

### ISSUE THREAD

**Issue by shishiro26** [kunjgit/GameZone#2100]
### 🎮 Game Request

"99" is a challenging game where you play against a computer opponent. The goal is to never reach a score of 99. Both you and the computer take turns choosing numbers from 1 to 10 to add to your scores. The computer uses a strategic algorithm to prevent you from winning. You must make careful choices to avoid reaching 99 while trying to outsmart the computer. It's a thought-provoking game that tests your decision-making skills and presents a unique challenge.

### Point down the features

Game points

Each player starts with a score of 0.
On each turn, both the player and the computer select a number from 1 to 10.
The chosen numbers are added to the respective scores of the player and the computer.
The scores are updated after each turn.
The objective is to avoid reaching a score of 99.
If a player's score reaches 99 exactly, they lose the game.
Here's an example to illustrate the scoring:

Player selects 6 and computer selects 3:

Player score: 6
Computer score: 3
Player selects 4 and computer selects 7:

Player score: 10
Computer score: 10
Player selects 2 and computer selects 9:

Player score: 12
Computer score: 19
The game continues in this manner until either the player or the computer reaches a score of 99 or higher, resulting in the player's loss.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @shishiro26 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hello @shishiro26, Time's Uppp!⏰ 
 Sorry for closing your issue! 
 But it's more than a week since we haven't received anything from your side 😢 . 
 Come up with new ideas, create a new issue and make sure you finish it within a week! 🔥 
 All the best! 🚀 
 Happy Hacking! 💗

**Comment by kunjgit** [comment]
Hey @shishiro26 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
