### ISSUE TITLE
[New game]: Skeleathon

### ISSUE THREAD

**Issue by Durgesh4993** [kunjgit/GameZone#2103]
### 🎮 Game Request

Game logic and basic description
A survival game where you kill enemies and build your skeleton army

Use arrows to move and jump. Use F to fire your deadly magic. Use R near a grave to raise a skeleton. The game never ends... how many waves are you able to survive?

Screenshort:
![image](https://github.com/kunjgit/GameZone/assets/98798977/db2bc34f-d829-44a5-b053-d8381fd667e5)

### Point down the features

Demo Vedio:

https://github.com/kunjgit/GameZone/assets/98798977/b6094459-b5da-4d87-8144-0e7cf5b3915d

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Durgesh4993 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @Durgesh4993 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
