### ISSUE TITLE
[New game]: Stick the Sticker

### ISSUE THREAD

**Issue by Tisha6661** [kunjgit/GameZone#2119]
### 🎮 Game Request

The game would include sticker in various pieces, the player has to connect the pieces to form the sticker. 

### Point down the features

It would be a fun game to join the curved, edged and different shaped pieces together.
The stickers would be catchy.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Tisha6661 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by Tisha6661** [comment]
@kunjgit I have created a pull request for this task, please review it, and merge it.

**Comment by Tisha6661** [comment]
@kunjgit Hey could you please verify and merge the game.

**Comment by Tisha6661** [comment]
@kunjgit I am closing this issue as it is merged.

**Comment by kunjgit** [comment]
Hey @Tisha6661 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by Tisha6661** [comment]
> Hey @Tisha6661 ! Thank you so much for your raising the issue💗 It’s all yours, you can come anytime again and make some contributions! 🚀 Alone, we can do little, but together we can do so much! 😇

Please open the Find the differences game now- #2291
