### ISSUE TITLE
[New game]: Squid Game

### ISSUE THREAD

**Issue by Tisha6661** [kunjgit/GameZone#2120]
### 🎮 Game Request

Referring to recent series Squid Game, it would be using the same doll. The players have to run and reach the end when the doll is not looking, if it catches them running then the player is out.

### Point down the features

It is a racing game in which 2 players can race and win.
It would have the eliminating element, the doll.
It would make it fun to run and stop.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Tisha6661 , You can't have another issue before completing the previous one 😀 
 you already have the following 1 open issues 👀 ! :

#2119

**Comment by kunjgit** [comment]
Hey @Tisha6661 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by kunjgit** [comment]
Hey @Tisha6661 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by Tisha6661** [comment]
Can I work on it after completing the first game?
