### ISSUE TITLE
[New game]: GSSOC '23: Archery Game

### ISSUE THREAD

**Issue by sujanrupu** [kunjgit/GameZone#2122]
## Game logic and basic description:
Archery game is frontend game developed using HTML, CSS, JavaScript.
In this game the player has to hit the target with the arrows provided and points will be gained according to the number targets hitting and accuracy of hitting.

## Game points:
- A specific number arrows will be provided to the player
- The player has to hit a specific target using those arrows
- If he hits a target successful, then points will be gained
- Points may also vary according to the accuracy of hitting
- If first level the target position will be fixed
- In the second level the target position will also vary.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @sujanrupu ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @sujanrupu ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
