### ISSUE TITLE
[New game]: Image Flash Quiz Game

### ISSUE THREAD

**Issue by shubhisingh184** [kunjgit/GameZone#2128]
### 🎮 Game Request

Game logic and basic description
Trivia games are a subcategory of quiz games that feature questions about trivial subjects
It is a game which consists of quizzes in which you have to answer those quizzes about specifically any particular topic/field.

### Point down the features

Game points
1. There will be multiple options for a particular question.
2. There will be a timer in which you have to answer the quiz question.
3. You can see you score on the scoreboard.
4. In order to win, you have to answer max correct questions.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @shubhisingh184 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by shubhisingh184** [comment]
\assign

**Comment by kunjgit** [comment]
Hello @shubhisingh184, Time's Uppp!⏰ 
 Sorry for closing your issue! 
 But it's more than a week since we haven't received anything from your side 😢 . 
 Come up with new ideas, create a new issue and make sure you finish it within a week! 🔥 
 All the best! 🚀 
 Happy Hacking! 💗

**Comment by kunjgit** [comment]
Hey @shubhisingh184 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by shubhisingh184** [comment]
@kunjgit I've already mentioned the pr, how can it be closed please look at this.
