### ISSUE TITLE
[New game]: the reaction teaser game

### ISSUE THREAD

**Issue by Sushilverma002** [kunjgit/GameZone#2130]
### 🎮 Game Request

the game is about to test your reaction like how fast you're.
It basically test the reflex of the player the was shown in the screen , and the player can do better at every next moment he/she tap on the blocks came on screen.

points:
the game consist of the rules and the benefits of playing the REACTION TESTER.

### Point down the features

Game points:

HOW IT BENEFICAL TO YOU?
Help improve cognitive skills such as attention, focus, and concentration.
Regularly playing reaction tester games can enhance your reflexes.
This can help improve your coordination and motor skills.

RULES:
Set up the game.
Prepare yourself.
Start the game.
Pay attention.
Check your reaction time every time.
Practice and improve your time.
Have fun!!!!!!

![image](https://github.com/kunjgit/GameZone/assets/114687502/1981efac-06e3-4547-98cc-baf27fc61894)

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Sushilverma002 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @Sushilverma002 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
