### ISSUE TITLE
[New game]: Typing_Speed_Test

### ISSUE THREAD

**Issue by vaibhavi-d18** [kunjgit/GameZone#2131]
### 🎮 Game Request

A typing speed test game is a website that measures and evaluates a player's typing speed and accuracy. It typically presents the player with a random set of words, phrases, or sentences that they need to type accurately within a certain time limit.

### Point down the features

- The player clicks the start button to initiate the game.
-  A random text snippet or set of words is displayed for the player to type. 
- As the player types, their input is compared to the expected text for accuracy.
-  Real-time feedback may be provided, such as highlighting correct and incorrect characters or words. 
- It will display time taken , typing speed(words per minute) and accuracy of the user

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hello @vaibhavi-d18, Time's Uppp!⏰ 
 Sorry for closing your issue! 
 But it's more than a week since we haven't received anything from your side 😢 . 
 Come up with new ideas, create a new issue and make sure you finish it within a week! 🔥 
 All the best! 🚀 
 Happy Hacking! 💗

**Comment by kunjgit** [comment]
Hey @vaibhavi-d18 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
