### ISSUE TITLE
[Documentation]: Adding a "Back to top" button in README.md 

### ISSUE THREAD

**Issue by Abhishek-Rajput-81** [kunjgit/GameZone#2132]
### Describe the bug ✍️

Currently, the README.md file lacks a "Back to top" button, resulting in inconvenient navigation for users. To enhance the user experience and provide easier access to important sections or links, it is necessary to add a "Back to top" button.

### Provide step by step information reproduce the bug 📄

Identify the appropriate location for the "Back to top" button to ensure it is easily visible and accessible and add it at that place.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Abhishek-Rajput-81! 🙂 
 It seems like you are not following proper guidelines !! 👀 
 Read documentation properly !!🙏 
 If you have any queries reach out to us on [Discord🕹️](https://discord.gg/fgwk4XZfxG) .

**Comment by kunjgit** [comment]
Hey @Abhishek-Rajput-81 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by kunjgit** [comment]
Hey @Abhishek-Rajput-81 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)
