### ISSUE TITLE
Geo-Guesser game

### ISSUE THREAD

**Issue by jaivsh** [kunjgit/GameZone#2135]
### 🎮 Game Request

The users would be presented with a random Street view(from google streetview api data). They would have to guess the location and mark that on a world map. The closer and more proximate they mark with respect to the true location, the more points they gonna earn. This game is similar to [geo-guesser](https://www.geoguessr.com) 

### Point down the features

- There would be a start button. 
- As the user would start the game, there would be a google street view expanded over whole screen, touchable and interactable, through which the user would attempt to guess the location(city/country) of this street view. 
- On a bottom corner would be a world map, where the user would pinpoint his/her guesses. 
- The user would be awarded a point based on how close the pinpointed guess is to the actual location of the street view. 
- This is the basic game architecture. New street views would emerge one after the other and users would guess their locations and earn points, creating high scores. 

**A few sample UI images of the game are as follows:**
![Screenshot_20230403_170047](https://github.com/kunjgit/GameZone/assets/93859359/c946e457-157e-4b90-863e-748f48e1b504)
![Screenshot_20230403_165239](https://github.com/kunjgit/GameZone/assets/93859359/c263285a-7535-40ef-ad09-ccc60911f46d)

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @jaivsh! 🙂 
 It seems like you are not following proper guidelines !! 👀 
 Read documentation properly !!🙏 
 If you have any queries reach out to us on [Discord🕹️](https://discord.gg/fgwk4XZfxG) .

**Comment by kunjgit** [comment]
Hey @jaivsh ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by kunjgit** [comment]
Hey @jaivsh ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)
