### ISSUE TITLE
[New game]: Geo-Guesser Game

### ISSUE THREAD

**Issue by jaivsh** [kunjgit/GameZone#2136]
### 🎮 Game Request

The users would be presented with a random Street view(from google streetview api data). They would have to guess the location and mark that on a world map. The closer and more proximate they mark with respect to the true location, the more points they gonna earn. In short, it would be a geography game which would take users to a journey around the world and would challenge their ability to recognize naive surroundings.

### Point down the features

- There would be a start button.
- As the user would start the game, there would be a google street view expanded over whole screen, touchable and interactable, through which the user would attempt to guess the location(city/country) of this street view.
- On a bottom corner would be a world map, where the user would pinpoint his/her guesses.
- The user would be awarded a point based on how close the pinpointed guess is to the actual location of the street view.
- This is the basic game architecture. New street views would emerge one after the other and users would guess their locations and earn points, creating high scores.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @jaivsh ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)
