### ISSUE TITLE
[New game]: word Blitz using HTML,CSS,JS [GSSOC'23]

### ISSUE THREAD

**Issue by Nikita06211** [kunjgit/GameZone#2140]
### 🎮 Game Request

Word Blitz
The user is supposed to guess maximum no of words from a given set of letters in limited time frame.

### Point down the features

The maximum no of words a user forms in 30 seconds from the given alphabets is going to be his/her maximum score. 

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Nikita06211 , You can't have another issue before completing the previous one 😀 
 you already have the following 1 open issues 👀 ! :

#2028

**Comment by kunjgit** [comment]
Hey @Nikita06211 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by kunjgit** [comment]
Hey @Nikita06211 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)
