### ISSUE TITLE
[Enhancement]: Escape Room game not found in GameData.json file

### ISSUE THREAD

**Issue by Swapnil-Singh-99** [kunjgit/GameZone#2142]
### Is your enhancement request related to a problem? Please describe.➕

The game is not listed in GameData.json file

### Describe the solution you'd like

I will be fixing search for some games not found

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Swapnil-Singh-99 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by Swapnil-Singh-99** [comment]
@kunjgit  The issue is not assigned to me /assign is not working

**Comment by gurjeetsinghvirdee** [comment]
Go ahead @Swapnil-Singh-99

**Comment by kunjgit** [comment]
Hey @Swapnil-Singh-99 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
