### ISSUE TITLE
[New game]: Blast 13 kilobytes

### ISSUE THREAD

**Issue by Durgesh4993** [kunjgit/GameZone#2143]
### 🎮 Game Request

Game logic and basic description
The goal is to protect the planet from asteroid impact. Click to shoot, aim at asteroids, have fun.

Should be compatible with all recent-ish browsers.

Screenshort:
![image](https://github.com/kunjgit/GameZone/assets/98798977/c19149d8-8bfb-4658-9e26-5a890acd6c6c)

### Point down the features

Demo Vedio:

https://github.com/kunjgit/GameZone/assets/98798977/9399b8cd-327d-4522-8be8-eea4d47001f4

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Durgesh4993 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by Durgesh4993** [comment]
@kunjgit @gurjeetsinghvirdee Please check out this game if you like that so assign me

**Comment by kunjgit** [comment]
Hey @Durgesh4993 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
