### ISSUE TITLE
[Bug]: Image not loading on website (wrong URL)

### ISSUE THREAD

**Issue by Swapnil-Singh-99** [kunjgit/GameZone#2144]
### Give a brief about the bug ✍️

The Image of number Guessing game is not loading

![image](https://github.com/kunjgit/GameZone/assets/85278243/a6927bdc-f02e-4a7e-8afc-0a1262ea5cc2)

![image](https://github.com/kunjgit/GameZone/assets/85278243/1b806846-665d-4a44-8f8b-5dae51761f87)

### What is the expected behavior? 🤔

The Url of the Image needs to be made correct in order to make it load

### Provide step by step information reproduce the bug 📄

I will be fixing the Image URL

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Swapnil-Singh-99 , You can't have another issue before completing the previous one 😀 
 you already have the following 1 open issues 👀 ! :

#2142

**Comment by kunjgit** [comment]
Hey @Swapnil-Singh-99 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by kunjgit** [comment]
Hey @Swapnil-Singh-99 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)
