### ISSUE TITLE
[Bug]: No recommendations for gibberish

### ISSUE THREAD

**Issue by Akanksha-202** [kunjgit/GameZone#2146]
### Give a brief about the bug ✍️

![Uploading image.png…]()

Nothing is displayed for a gibberish or mismatched propmt.

### What is the expected behavior? 🤔

It should display random games, to let user stick to the website

### Provide step by step information reproduce the bug 📄

To display random games from the list when a mismatched/wrong prompt is given.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hello @Akanksha-202, Time's Uppp!⏰ 
 Sorry for closing your issue! 
 But it's more than a week since we haven't received anything from your side 😢 . 
 Come up with new ideas, create a new issue and make sure you finish it within a week! 🔥 
 All the best! 🚀 
 Happy Hacking! 💗

**Comment by kunjgit** [comment]
Hey @Akanksha-202 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by Akanksha-202** [comment]
hey @kunjgit, i wasn't assigned to this issue, and therefore wasn't working over it, please assign it to me, then I'll start working over it
