### ISSUE TITLE
[New game]: Mortal Kombat

### ISSUE THREAD

**Issue by fantasticbuddy** [kunjgit/GameZone#2162]
### 🎮 Game Request

Game logic and basic description -
I previously made a game in python language which is 2 player fighting game. This game is to be played between 2 players on the same system. One has to beat the other to win. There are 3 rounds in this game. Both the opponents have energy levels which reduces every time it gets hit by another player.
This is a very user friendly and fun game to play when you and your roommate are being bored.

Here is a little overview of my game -
![image](https://github.com/kunjgit/GameZone/assets/114503561/c4d58d3d-3077-49e0-81b3-a79f042fc3ad)

### Point down the features

Game points -
 - 2-player game.
 - Played on same system.
 - 3 rounds. After 3 rounds the window automatically closes.
 - One player is - Wizard and other is -Warrior. Each player have two types of attacks.
 - You can also quit the game in between by pressing the quit button.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @fantasticbuddy ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by fantasticbuddy** [comment]
Thankyou @kunjgit

**Comment by kunjgit** [comment]
Hello @fantasticbuddy, Time's Uppp!⏰ 
 Sorry for closing your issue! 
 But it's more than a week since we haven't received anything from your side 😢 . 
 Come up with new ideas, create a new issue and make sure you finish it within a week! 🔥 
 All the best! 🚀 
 Happy Hacking! 💗

**Comment by fantasticbuddy** [comment]
Hey, @kunjgit 
I had a doubt, about the issue and is asked it, but I got no response so i did not make any PR.
