### ISSUE TITLE
[New game]: GSSOC '23: 3D Car Racing Game

### ISSUE THREAD

**Issue by sujanrupu** [kunjgit/GameZone#2163]
## Game logic and basic description:
It is a 3D racing game using HTML, CSS, and JavaScript. It sets up event listeners for keyboard input, initializes game variables and objects, and updates the game state in a loop. The game involves driving a car on a road,avoiding obstacles and other cars, and trying to complete laps as quickly as possible. The code also includes functionality for displaying a high score table and playing sound effects.

## Game points:
It is basically a normal race game where we see a screen in front of us and instructions below the screen  describing about how to play the game. It has all the sounds which a race game should have. The race begins on a track where there are multiple cars and we have to race against them. When we come infront of any other car our car's speed becomes zero and the car honks. 

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @sujanrupu ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hello @sujanrupu, Time's Uppp!⏰ 
 Sorry for closing your issue! 
 But it's more than a week since we haven't received anything from your side 😢 . 
 Come up with new ideas, create a new issue and make sure you finish it within a week! 🔥 
 All the best! 🚀 
 Happy Hacking! 💗

**Comment by kunjgit** [comment]
Hey @sujanrupu ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
