### ISSUE TITLE
[New game]: Star Trek Trivia

### ISSUE THREAD

**Issue by tayyab-ilyas** [kunjgit/GameZone#2165]
## Game logic and basic description

A fun trivia game centered around the famous Star Trek franchise, which would include the following:

1. Multiple Difficulty Levels: Different difficulty levels to cater to various levels of Star Trek knowledge. For example, an easy mode for general fans, a medium mode for more dedicated fans, and a hard mode for the ultimate Star Trek experts.

2. Variety of Questions: A diverse range of questions covering different aspects of Star Trek, such as characters, aliens, technology, quotes, and memorable moments. This ensures that the quiz appeals to a wide audience and offers a mix of challenging and easier questions.

3. Time Constraints: A time limit to answer each question, increasing the pressure and making the game more exciting. 

4. Winning Criteria = 100 points 

## Game points

On the basis of difficulty level:
-Easy =10 points
-Medium = 15 points
-Hard = 20 points

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @tayyab-ilyas ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hello @tayyab-ilyas, Time's Uppp!⏰ 
 Sorry for closing your issue! 
 But it's more than a week since we haven't received anything from your side 😢 . 
 Come up with new ideas, create a new issue and make sure you finish it within a week! 🔥 
 All the best! 🚀 
 Happy Hacking! 💗

**Comment by kunjgit** [comment]
Hey @tayyab-ilyas ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by tayyab-ilyas** [comment]
Hey @kunjgit can you re open this issue please? I got stuck with some work.. I have started working on this now.
