### ISSUE TITLE
[New game]: Death by Hamster

### ISSUE THREAD

**Issue by Durgesh4993** [kunjgit/GameZone#2168]
### 🎮 Game Request

Game logic and basic description
You can kill all animes by Tank

Screenshort:

![image](https://github.com/kunjgit/GameZone/assets/98798977/882d1aef-d55f-4d00-a53a-e80d78e158bc)

### Point down the features

Demo vedio:

https://github.com/kunjgit/GameZone/assets/98798977/71476643-8b79-4293-8eaa-0f65ee43f78d

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Durgesh4993 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @Durgesh4993 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by byemc** [comment]
Hey there, I believe the code here is plagiarised, this is identical to my 2022 JS13K entry except for a slight modification in the title screen. https://github.com/byemc/deathbyhamster

I don't mind the game being distributed but I don't appreciate someone else taking the credit for a month of my work without making any other changes.
