### ISSUE TITLE
Image is not rendering

### ISSUE THREAD

**Issue by hindu-muppala** [kunjgit/GameZone#217]
### Describe the bug ✍️

In redme,the image is not rendening
![image](https://github.com/kunjgit/GameZone/assets/120579608/e145bbad-e60e-421c-9c80-1811efc83a7e)

### Provide step by step information reproduce the bug 📄

Please replace the url with correct url.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @hindu-muppala ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by hindu-muppala** [comment]
@kunjgit ,can you able to share relavant images or should I add my own images for this issue.
