### ISSUE TITLE
[Documentation Bug]: Want to add Contribution.md Doc

### ISSUE THREAD

**Issue by silky-modi22** [kunjgit/GameZone#2170]
### Describe the bug ✍️

I think the Contribution.md file is missing here. I want to add it in which I'll explain step by step guide for contributing in this project. 

### Provide step by step information reproduce the bug 📄

Description

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @silky-modi22 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by silky-modi22** [comment]
Assign me this issue

**Comment by kunjgit** [comment]
Hello @silky-modi22, Time's Uppp!⏰ 
 Sorry for closing your issue! 
 But it's more than a week since we haven't received anything from your side 😢 . 
 Come up with new ideas, create a new issue and make sure you finish it within a week! 🔥 
 All the best! 🚀 
 Happy Hacking! 💗

**Comment by kunjgit** [comment]
Hey @silky-modi22 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by silky-modi22** [comment]
@kunjgit can you please reopen this issue I think you assign this to me then after only I can raise PR. That's why I not raise the PR. 
Please reopen this issue By today I raise the PR
