### ISSUE TITLE
[UI]: Add light/dark mode button as icons

### ISSUE THREAD

**Issue by rishuraj1** [kunjgit/GameZone#2174]
We might wan to add a light/dark mode toggle button which is modern looking instead of the existing button and text written over there.
It will improve user experience and look appealing.

<img width="907" alt="image" src="https://github.com/kunjgit/GameZone/assets/47839626/aa114ab8-e630-4ef0-a55c-de4973573e66">

please assign this task to me under GSSoC '23. Thank You !

**Comment by kunjgit** [comment]
Hey @rishuraj1! 🙂 
 It seems like you are not following proper guidelines !! 👀 
 Read documentation properly !!🙏 
 If you have any queries reach out to us on [Discord🕹️](https://discord.gg/fgwk4XZfxG) .

**Comment by kunjgit** [comment]
Hey @rishuraj1 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by rishuraj1** [comment]
@kunjgit is this issue supposed to be closed ?
I don't understand
