### ISSUE TITLE
[New game]: Othello/reversi

### ISSUE THREAD

**Issue by RitiChandak** [kunjgit/GameZone#2175]
### 🎮 Game Request

The game starts with an 8x8 board with two initial black and two initial white pieces placed in the center.
Players take turns placing their colored pieces on the board. A move is valid if it results in the flipping of at least one opponent's piece in a straight line (horizontally, vertically, or diagonally).
some of the features are :
-to flip the token
-cascading effects
-the corners and edges of the board have special strategic significance in Othello

### Point down the features

The features that make Othello a compelling and engaging game are that it combines tactical decision-making, spatial awareness, and the ability to adapt to changing board conditions.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @RitiChandak ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @RitiChandak ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
