### ISSUE TITLE
[New game]: Platform game

### ISSUE THREAD

**Issue by samhitaveluri** [kunjgit/GameZone#2178]
### 🎮 Game Request

Game logic and basic description: 
It is a game built using HTML,CSS and javascript.
A ball rolls on platforms where we should reach the end without dying.
![image](https://github.com/kunjgit/GameZone/assets/121224422/420106aa-3bf0-4e39-98ce-f09bb6f132e4) 

### Point down the features

Game points:
The left and right arrows are used to mive the ball to required direction.
Entering to the red area kills the ball.
After we win the game, we can reload the page to start a new game.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @samhitaveluri ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hello @samhitaveluri, Time's Uppp!⏰ 
 Sorry for closing your issue! 
 But it's more than a week since we haven't received anything from your side 😢 . 
 Come up with new ideas, create a new issue and make sure you finish it within a week! 🔥 
 All the best! 🚀 
 Happy Hacking! 💗

**Comment by kunjgit** [comment]
Hey @samhitaveluri ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
