### ISSUE TITLE
add: dark/light mode icons as buttons

### ISSUE THREAD

**Issue by rishuraj1** [kunjgit/GameZone#2184]
I want to add icons as button for light/dark mode toggle button.

Please assign me this task under GSSoC '23.
Thank You!

<img width="960" alt="image" src="https://github.com/kunjgit/GameZone/assets/47839626/fa703953-00ce-4de9-8088-99698127ccbe">

**Comment by kunjgit** [comment]
Hey @rishuraj1! 🙂 
 It seems like you are not following proper guidelines !! 👀 
 Read documentation properly !!🙏 
 If you have any queries reach out to us on [Discord🕹️](https://discord.gg/fgwk4XZfxG) .

**Comment by kunjgit** [comment]
Hey @rishuraj1 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @rishuraj1 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
