### ISSUE TITLE
[Enhancement]: add dark/light icons as buttons

### ISSUE THREAD

**Issue by rishuraj1** [kunjgit/GameZone#2185]
### Is your enhancement request related to a problem? Please describe.➕

I want to add light/dark toggle button as icons (sun for light mode/moon for dark mode).

Please assign me this task under GSSoC '23.
Thank You.

<img width="960" alt="image" src="https://github.com/kunjgit/GameZone/assets/47839626/5dfa07ce-2aab-4cf7-aea7-c68d74ac196b">

### Describe the solution you'd like

Instead of toggling the input, I want to icons.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @rishuraj1 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by rishuraj1** [comment]
hey @kunjgit , I see you closed the PR without merging, whats the update...

**Comment by kunjgit** [comment]
Hello @rishuraj1, Time's Uppp!⏰ 
 Sorry for closing your issue! 
 But it's more than a week since we haven't received anything from your side 😢 . 
 Come up with new ideas, create a new issue and make sure you finish it within a week! 🔥 
 All the best! 🚀 
 Happy Hacking! 💗

**Comment by kunjgit** [comment]
Hey @rishuraj1 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
