### ISSUE TITLE
[NEW GAME] Space Invaders

### ISSUE THREAD

**Issue by varshanim** [kunjgit/GameZone#2192]
### 🎮 Game Request

Space invaders is a game in which there are aliens in N-rows and they will increase with time and the bottom-most row of the aliens will keep shooting at you space ship. You will be in a spaceship and you can destroy the aliens by shooting at them with the help of your spaceship. When you shoot at an alien it dies(disappears).
This game can be developed by using JavaScript.

### Point down the features

You can shoot the Aliens by pressing the space bar and move from left to right to avoid the bullets being shot by the aliens using the left and right arrow keys. If you get shot by the aliens then it will display GAME OVER.

![IMG_5930](https://github.com/kunjgit/GameZone/assets/105119278/03cf95a5-a8e7-4dab-90bc-9721d0c0c54d)

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @varshanim ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hello @varshanim, Time's Uppp!⏰ 
 Sorry for closing your issue! 
 But it's more than a week since we haven't received anything from your side 😢 . 
 Come up with new ideas, create a new issue and make sure you finish it within a week! 🔥 
 All the best! 🚀 
 Happy Hacking! 💗

**Comment by kunjgit** [comment]
Hey @varshanim ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
