### ISSUE TITLE
[New game]: Poke-Guess Blitz

### ISSUE THREAD

**Issue by akhilender-bongirwar** [kunjgit/GameZone#2193]
### 🎮 Game Request

Game logic and basic description
Welcome to the exciting world of "Poke_Guess_Blitz" Can you prove your knowledge of Pokemon by guessing their names from obscured images?In this game, you'll be presented with an image of a Pokemon, but be careful! The image is partially hidden, making it a challenge to identify the Pokemon. Trust your knowledge of Pokemon and enter the name of the Pokemon through the text input

### Point down the features

Game points
If your guess is correct, congratulations! Your score increases, and the Pokemon's name and full image are revealed.
But if your guess is incorrect, don't worry! The Pokemon's name is revealed, allowing you to learn from your mistake and continue your Pokemon guessing journey.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @akhilender-bongirwar ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @akhilender-bongirwar ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
