### ISSUE TITLE
[New game]: Single Player Flappy Bird Game

### ISSUE THREAD

**Issue by AbhishekPSingh07** [kunjgit/GameZone#22]
### 🎮 Game Request

Build a Single Player Flappy Bird Game where user will COntrol the flappy bird with a key and has to cross obstacles to gain points and score.

### Point down the features

It Will have Scoring and LeaderBoard Functionality.Once Deployed many people would be able to play and compete via Leaderboard

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by rt-001** [comment]
I would like to work on this issue.

**Comment by kunjgit** [comment]
Hey @AbhishekPSingh07  ! Thank you for raising an issue 💗 You have been assigned this issue you can start working on the issue 🎮

**Comment by kunjgit** [comment]
Hey @AbhishekPSingh07 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
