### ISSUE TITLE
[New game]: Connect 4 game

### ISSUE THREAD

**Issue by Sameeksha-12** [kunjgit/GameZone#220]
### 🎮 Game Request

Game logic and basic description
The connect four game can be compared to two players building a wall with a different colour of brick for each participant. The rule is straightforward: drop one brick at a time from each individual. A brick cannot stand alone in the air, just like an actual wall, so the player must place one brick on top of another. When one of the two players can arrange their bricks in a connect-four pattern, which consists of four bricks laid out horizontally, vertically, or diagonally, they have won the game.

### Point down the features

Game points
The game has 21 checkers for each participant.
The game can be played between 2 players or a player and the cpu.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Sameeksha-12 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @Sameeksha-12 👋!
 
  @kunjgit here, 
 We have this annoucement to make 📢!! 
 We have updated our README 🚀 
 Make sure you follow proper guideline to raise your next issues !! 
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG) if you haven't 😇 
  Thank you 💗!

**Comment by kunjgit** [comment]
We are already having this game request in #112

**Comment by kunjgit** [comment]
Hey @Sameeksha-12 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
