### ISSUE TITLE
[Bug]: Game Duplication

### ISSUE THREAD

**Issue by anilkoduru** [kunjgit/GameZone#2201]
### Give a brief about the bug ✍️

Description
The game fruit ninja has 2 appearance in the first page itself.
![image](https://github.com/kunjgit/GameZone/assets/88759473/6bb09d62-3b82-45c9-9914-44130dfba82c)

### What is the expected behavior? 🤔

Description
I would like to delete the duplicate one and make it one.

### Provide step by step information reproduce the bug 📄

Description
Remove one of the game.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @anilkoduru ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @anilkoduru ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
