### ISSUE TITLE
[New game]: Bird shooter game

### ISSUE THREAD

**Issue by SimranLahrani842** [kunjgit/GameZone#2206]
### 🎮 Game Request

Game logic and basic description
Hit the birds and kill them to get the score.
Hit the birds at the centre.
A notification will appear that it is killed.

### Point down the features

Game points
Points increase as soon as you hit the bird.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @SimranLahrani842 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by SimranLahrani842** [comment]
> Hey @SimranLahrani842 ! Thank you for raising an issue heartpulse You can self assign the issue by commenting /assign in comment grinning Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 Don’t Forget to star our [GameZone🎮](https://github.com/kunjgit/GameZone) Make sure you join our [Discordjoystick](https://discord.gg/fgwk4XZfxG)

/assign

**Comment by kunjgit** [comment]
Hello @SimranLahrani842, Time's Uppp!⏰ 
 Sorry for closing your issue! 
 But it's more than a week since we haven't received anything from your side 😢 . 
 Come up with new ideas, create a new issue and make sure you finish it within a week! 🔥 
 All the best! 🚀 
 Happy Hacking! 💗

**Comment by kunjgit** [comment]
Hey @SimranLahrani842 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
