### ISSUE TITLE
[Bug]: Dark Mode Button

### ISSUE THREAD

**Issue by parasss19** [kunjgit/GameZone#2209]
### Give a brief about the bug ✍️

- Dark mode button is not fixed
- At the middle of the screen user not able to change the theme

### What is the expected behavior? 🤔

- It should be fixed so that it would be easy for user to change theme when they are at the middle of the screen

### Provide step by step information reproduce the bug 📄

- I will made it fixed at there position using correct CSS property

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @parasss19 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by parasss19** [comment]
hey @kunjgit can you assign me this issue

**Comment by kunjgit** [comment]
Hey @parasss19 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
