### ISSUE TITLE
[New game]:  Guess The Number

### ISSUE THREAD

**Issue by parasss19** [kunjgit/GameZone#2210]
### 🎮 Game Request

- The game is developed using Pure HTML CSS and JAVASCRIPT
- It uses random number generator 
- Uses audio files for sound effects

### Point down the features

- The game is Guess the number 
- Computer generate the random number
- User provided with two choices EASY MODE - 10 attempts and HARD MODE 5 attempts
- When user lose it show the correct answer with emoij
- It also has sound effects

## 1
<img width="960" alt="Screenshot 2023-07-01 210317" src="https://github.com/kunjgit/GameZone/assets/101205226/b3dcd20d-b69b-4b34-ae9d-c723aa83f8a8">

## 2
<img width="960" alt="Screenshot 2023-07-01 210338" src="https://github.com/kunjgit/GameZone/assets/101205226/fb026824-740a-40d3-945a-523abc18e2c0">

## 3
<img width="960" alt="Screenshot 2023-07-01 210300" src="https://github.com/kunjgit/GameZone/assets/101205226/18b38b3c-619c-4580-9cbf-856a5f28eb4f">

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @parasss19 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @parasss19! 
We are already having a similar game request in #2208 👀 
Make sure you come up with a cool unique idea 😀 
 Waiting for your new game idea 💗.

**Comment by kunjgit** [comment]
Hey @parasss19 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
