### ISSUE TITLE
[New game]: Atari Breakout

### ISSUE THREAD

**Issue by anilkoduru** [kunjgit/GameZone#2211]
### 🎮 Game Request

Game logic and basic description
A wall of brick will be there at the top of the screen and then a ball will be there which will be travelling between the wall and the board which is handled by the user.

### Point down the features

Game points
For each brick one point will be added to the user.
![image](https://github.com/kunjgit/GameZone/assets/88759473/7d3bc878-716c-4ebc-b39c-e2b0944188fd)
![image](https://github.com/kunjgit/GameZone/assets/88759473/7074ce55-3306-47b1-b65e-0d53aa55ec40)
This game actually shows in the list but the files are missing. So I would like to do this game.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @anilkoduru ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @anilkoduru ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
