### ISSUE TITLE
[Bug]: Atari breakout not working 

### ISSUE THREAD

**Issue by anilkoduru** [kunjgit/GameZone#2212]
### Give a brief about the bug ✍️

Description
It is not working due to the spelling mistake.

### What is the expected behavior? 🤔

Description
Game should work

### Provide step by step information reproduce the bug 📄

Description
Atari_Breakout to Atari_breakout 

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @anilkoduru ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)
