### ISSUE TITLE
[Bug]: Scrolling Behavior is Not Smooth and Up to The Mark in Main Page

### ISSUE THREAD

**Issue by NarendraKoya999** [kunjgit/GameZone#2224]
### Give a brief about the bug ✍️

Description:
- **Scrolling Behavior is not much Smooth in Main Page.**
- **Improving scrolling behavior Must Change to Smooth According to Browser Compatibilities Issues**

### What is the expected behavior? 🤔

Description:
- **Improving Scrolling Behavior from Bottom to Top in Main Page according to Browser Compatibilities Issues**

### Provide step by step information reproduce the bug 📄

Description:
- **Go To** 'https://kunjgit.github.io/GameZone/'
- **Scroll Down to Bottom**
- **Click on Using Either Scroller-Thumb OR Click on Scroll Arrow-Up Button**
- **See Error on Page. scrolling Behavior is not Much Smooth** 

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @NarendraKoya999 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by NarendraKoya999** [comment]
I can self Assign this @kunjgit

**Comment by kunjgit** [comment]
Hello @NarendraKoya999, Time's Uppp!⏰ 
 Sorry for closing your issue! 
 But it's more than a week since we haven't received anything from your side 😢 . 
 Come up with new ideas, create a new issue and make sure you finish it within a week! 🔥 
 All the best! 🚀 
 Happy Hacking! 💗

**Comment by kunjgit** [comment]
Hey @NarendraKoya999 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
