### ISSUE TITLE
[Enhancement]:  Improve Advance Design for Pagination Section in Main Page

### ISSUE THREAD

**Issue by NarendraKoya999** [kunjgit/GameZone#2225]
### Is your enhancement request related to a problem? Please describe.➕

Game enhancement:

 ### Issue Description:
- **In` Gamezone Website,` Click on `Selected Pagination Number using Previous , Next OR Selected Pagination Number.`**
- **It's only addicted to `Bottom of The Pagination `Section.**

### Describe the solution you'd like

Solution steps:
- **Go to** 'https://kunjgit.github.io/GameZone/'
- **Scroll Down to Pagination Section**
- **Click on that any Pagination Button, It directly Goes to the Above Bottom of the Pagination Section**

### For Reviewers
- **I want to Design Advancingly like When click on Any Pagination Button, then The Particular Page Directly Go to the Top of the Page showing.** 
- **`Example: GitHub Issues Pagination`**

### Screenshot (I expected this Behavior when click on Pagination Symbol)
![gamezone-3](https://github.com/kunjgit/GameZone/assets/84512164/41f2ddb7-40b5-4666-86fa-d93a6ec58e62)

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @NarendraKoya999 , You can't have another issue before completing the previous one 😀 
 you already have the following 1 open issues 👀 ! :

#2224

**Comment by kunjgit** [comment]
Hey @NarendraKoya999 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by kunjgit** [comment]
Hey @NarendraKoya999 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by NarendraKoya999** [comment]
**Ok. I complete First Issue Before Raising This Issue. Please Review that Issue #2224 @kunjgit . If Selected I work on that Issue**
