### ISSUE TITLE
[New game]: OTHELLO

### ISSUE THREAD

**Issue by prashanth772** [kunjgit/GameZone#2226]
### 🎮 Game Request

Title: Othello - Two-Player Strategy Board Game

Description:
Othello is a classic two-player strategy board game played on an 8x8 square board. This enhancement request aims to provide a clearer understanding of the game rules and objective.

### Point down the features

Objective:
The objective of Othello is to have the most disks of your color on the board when the game ends. The game concludes when no more legal moves can be made or when the entire board is filled with disks. The player with the majority of disks on the board at the end of the game is declared the winner.

Gameplay Mechanics:
Players take turns placing one disk of their color on the board. A disk can only be placed on a valid empty square that, when placed, will create a line (horizontal, vertical, or diagonal) of the opponent's disks between the newly placed disk and the player's previously placed disks. When such a line is created, all the opponent's disks in that line are flipped to the player's color. If a player has a valid move available, they must make a move; otherwise, they must pass their turn.

Disk Mechanics:
The game uses double-sided disks with one side black and the other side white. When a player places a disk and flips their opponent's disks, the flipped disks change color to match the player's color.

Endgame and Scoring:
Once the game ends, the final score is determined by counting the number of disks of each color on the board. The player with the highest score, indicating the most disks of their color, wins the game.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @prashanth772 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hello @prashanth772, Time's Uppp!⏰ 
 Sorry for closing your issue! 
 But it's more than a week since we haven't received anything from your side 😢 . 
 Come up with new ideas, create a new issue and make sure you finish it within a week! 🔥 
 All the best! 🚀 
 Happy Hacking! 💗

**Comment by kunjgit** [comment]
Hey @prashanth772 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
