### ISSUE TITLE
[New game]: Beyblade - Spinning Battle Game

### ISSUE THREAD

**Issue by abhinav-m22** [kunjgit/GameZone#2227]
### 🎮 Game Request

I would like to add a Beyblade game using HTML, CSS, and JavaScript. The game will simulate a spinning battle between two Beyblades, where players can launch their Beyblades and compete to earn a high score and determine the winner.

### Point down the features

1. Players can choose their Beyblade from a variety of options, each with unique characteristics and abilities.
2. Players can launch their Beyblade into the battle arena by clicking a launch button.
3. The Beyblade will spin continuously after being launched, creating an engaging visual effect.
4. The game will keep track of each player's score based on the performance of their Beyblade during the battle.
5. Each Beyblade will have a stamina value that decreases over time. The game will end when a Beyblade's stamina reaches zero.
6. The game will be designed to work on various screen sizes and devices, ensuring a seamless gaming experience.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @abhinav-m22 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @abhinav-m22 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
