### ISSUE TITLE
[New game]: BOW-AND-ARROW GAME

### ISSUE THREAD

**Issue by Roshnijeewani3457** [kunjgit/GameZone#223]
### 🎮 Game Request

This is a BOW-AND ARROW GAME made using HTML , CSS and JAVASCRIPT.

**Objective is to shoot monsters and save birds.**
1.Move the man with "arrow keys".
2.Shoot arrow with "space bar".

### Point down the features

**Can Shoot in both the directions(L/R).**

  +1 for hitting monster.

  -5 if monster reaches birds.

Game Over if score<0.

Monsters speed increases each level.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Roshnijeewani3457 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by Roshnijeewani3457** [comment]
I want to work on this issue. Please Assign me this task

**Comment by kunjgit** [comment]
Hey @Roshnijeewani3457 👋!
 
  @kunjgit here, 
 We have this annoucement to make 📢!! 
 We have updated our README 🚀 
 Make sure you follow proper guideline to raise your next issues !! 
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG) if you haven't 😇 
  Thank you 💗!

**Comment by kunjgit** [comment]
Hello @Roshnijeewani3457, Time's Uppp!⏰ 
 Sorry for closing your issue! 
 But it's more than a week since we haven't received anything from your side 😢 . 
 Come up with new ideas, create a new issue and make sure you finish it within a week! 🔥 
 All the best! 🚀 
 Happy Hacking! 💗

**Comment by kunjgit** [comment]
Hey @Roshnijeewani3457 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
