### ISSUE TITLE
[Bug]: Open links in a new tab

### ISSUE THREAD

**Issue by abansal15** [kunjgit/GameZone#2244]
### Give a brief about the bug ✍️

Description liks are opening in the same tab which is not user friendly
![image](https://github.com/kunjgit/GameZone/assets/120590200/c1af6a47-c42d-47d2-ba5d-f5e2eb443936)

### What is the expected behavior? 🤔

Description links should open in a new tab

### Provide step by step information reproduce the bug 📄

Description i will add the target 

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by abansal15** [comment]
hello i would like to work on the issue could you please assign it to me

**Comment by kunjgit** [comment]
Hey @abansal15 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by gobbledy-gook** [comment]
Is this issue still active ? I have already forked the repository and fixed the bug, by just adding one attribute in the ```anchor``` tag. I have opened a PR, could you please review it ...

**Comment by abansal15** [comment]
hey @gobbledy-gook i have already made the pr and this is my issue why you are interfering in the other issues you should have some etiquettes i am already assigned

**Comment by kunjgit** [comment]
Hey @abansal15 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
