### ISSUE TITLE
[New game]: Word_wrap

### ISSUE THREAD

**Issue by kumar11jr** [kunjgit/GameZone#2262]
### 🎮 Game Request

Game logic and basic description
In this game, players are presented with a scrambled word, and they need to unscramble the letters to form a valid word. They can type their answer into the input field and click the "Submit" button or press Enter to check if it matches the unscrambled word. If the word is correct, their score increases, and a new word is displayed. The game has a timer of 60 seconds, and when time runs out, the game ends, displaying the final score.

### Point down the features

Game points
each  correct  right word users get one point and there is no deduction for wrong answers.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @kumar11jr ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @kumar11jr ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
