### ISSUE TITLE
[Bug]: UNCAUGHT TYPERROR ON JAVASCRIPT DUE TO NULL VALUE 🪲

### ISSUE THREAD

**Issue by 0xabdulkhalid** [kunjgit/GameZone#2269]
### Give a brief about the bug ✍️

- The bug is about a null value, which means an element which has been declared is not present on the DOM Tree.
- So the script generates the `Uncaught TypeError` error.

### What is the expected behavior? 🤔

- The function is not need for the current UI of the website.
- Because the function and it's variables are only used on the old UI.

### Provide step by step information reproduce the bug 📄

- We can resolve that bug by simply removing those set of variables and functions mapped to used on old UI.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @0xabdulkhalid , You can't have another issue before completing the previous one 😀 
 you already have the following 1 open issues 👀 ! :

#2268

**Comment by kunjgit** [comment]
Hey @0xabdulkhalid ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by kunjgit** [comment]
Hey @0xabdulkhalid ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)
