### ISSUE TITLE
[New game]: Rock Paper Sicssor

### ISSUE THREAD

**Issue by utkarshjaulkar** [kunjgit/GameZone#227]
### 🎮 Game Request

**Game logic and basic description:-** 

#### This Rock Paper Scissors game is a web-based game created using HTML, CSS, and JavaScript. It allows the user to play against the computer in the classic game of Rock Paper Scissors.
<br>

- User vs Computer: Challenge yourself against the computer in an exciting game of Rock Paper Scissors. Test your strategy and luck as you try to outsmart the computer's choices.
- Clean and Responsive Design: The game features a clean and user-friendly interface created with HTML and CSS. The design is responsive, ensuring a seamless experience across different devices and screen sizes.
- Interactive Gameplay: Using JavaScript, the game allows the user to select their choice from Rock, Paper, or Scissors. The computer randomly generates its own choice, and the game updates the interface to display both choices.
- Real-time Results: After both the user and computer have made their choices, the game determines the winner based on the traditional Rock Paper Scissors rules. The outcome of each round, whether it's a win, loss, or a tie, is instantly displayed on the screen.
- Simple and Engaging: This game offers a straightforward and engaging experience. It's easy to understand and play, making it suitable for users of all ages. Challenge yourself or pass the time with this classic game.

### Point down the features

Game points:
The objective is to win against the computer in the Rock Paper Scissor Game.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @utkarshjaulkar ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @utkarshjaulkar 👋!
 
  @kunjgit here, 
 We have this annoucement to make 📢!! 
 We have updated our README 🚀 
 Make sure you follow proper guideline to raise your next issues !! 
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG) if you haven't 😇 
  Thank you 💗!

**Comment by kunjgit** [comment]
Hey @utkarshjaulkar ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
