### ISSUE TITLE
[New game]: Add "Tenzin Game" to the Repository

### ISSUE THREAD

**Issue by Nishitbaria** [kunjgit/GameZone#2272]
### 🎮 Game Request

I would like to propose the addition of a new game called "Tenzin Game" to the repository. Tenzin Game, also known as "Tenzies," is a simple yet addictive game where the objective is to make all the numbers on the board the same.

### Point down the features

Game Rules:

The game board consists of a square grid with various numbers.
The player's goal is to make all the numbers on the board the same.
The player can choose a number and apply it to any other number on the board.
When a number is chosen, it replaces the original number and spreads to adjacent cells, changing them to the chosen number as well.
The process continues until all the numbers on the board are the same.
The player wins the game when all numbers on the board become the same.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Nishitbaria ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @Nishitbaria ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
