### ISSUE TITLE
[New game]: Stickman Game

### ISSUE THREAD

**Issue by uzmaansari23** [kunjgit/GameZone#2281]
### 🎮 Game Request

Game logic and basic description
Goal of the game:

Get to the other end of the canvas or kill the enemy

Instructions:

Hold spacebar to throw sword further!
While the sword is flying you can throw knives with spacebar!
Arrow keys to move!

### Point down the features

Game points
As the player reach the other end of the canvas the next level will start or else the same level will repeat until the enemies got killed.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @uzmaansari23 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @uzmaansari23 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
