### ISSUE TITLE
[New game]: Adding a OFF THE LINE game

### ISSUE THREAD

**Issue by rohanmittal1163** [kunjgit/GameZone#2282]
### 🎮 Game Request

Game logic and basic description
Gaol of the game:
Kill the enemy 

Instructions:
arrow keys are used to move the player
and z x are used to fight and kill the enemy on the rope on which they are standing

### Point down the features

Game points:
this is one time play game. 
points will degrade the ux of the game
but we can have multiplayer game in order to have an engagements 

screenshort
![image](https://github.com/kunjgit/GameZone/assets/97821844/017adc4c-64d3-4ed9-8252-fb9a8c1b37dd)

### Select program in which you are contributing
GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @rohanmittal1163 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by rohanmittal1163** [comment]
hi @kunjgit pls see to this game

**Comment by rohanmittal1163** [comment]
hi @kunjgit pls see to this game

**Comment by kunjgit** [comment]
Hey @rohanmittal1163 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
