### ISSUE TITLE
[New game]: adding a audio dash

### ISSUE THREAD

**Issue by rohanmittal1163** [kunjgit/GameZone#2283]
### 🎮 Game Request

Game logic and basic description

the logic behind this game is to reach your audio to at max volume as you can.
by using space bar we can do this.

screenshorts
![image](https://github.com/kunjgit/GameZone/assets/97821844/86d75b54-42b8-4619-a40d-8fba07ce9565)

### Point down the features

Game points

One time play like flappy word
spacebar is used to control the audio in order to save from the waves 
the no. of saved waves will be the no. of poit alloted to each 

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @rohanmittal1163 , You can't have another issue before completing the previous one 😀 
 you already have the following 1 open issues 👀 ! :

#2282

**Comment by kunjgit** [comment]
Hey @rohanmittal1163 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by kunjgit** [comment]
Hey @rohanmittal1163 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)
