### ISSUE TITLE
[New game]: Know Your Country

### ISSUE THREAD

**Issue by KanchandeepK** [kunjgit/GameZone#2286]
### 🎮 Game Request

- It will be a quiz game having a photo of a famous places in India with some history related to the place.
- 4 options would be given accordingly.

### Point down the features

- Each correct would make score increase by 1.
- Game would have 5 hearts depicting the lifesavings
- One wrong would reduce the heart by 1 . After the heart count reaches 0 the game would end .
- The timer would be put on every question.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @KanchandeepK ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @KanchandeepK ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
