### ISSUE TITLE
[Enhancement]: Ludo Game

### ISSUE THREAD

**Issue by PriyankaTamhankar01** [kunjgit/GameZone#2287]
### Is your enhancement request related to a problem? Please describe.➕

**Game enhancement in Ludo Game**

### Describe the solution you'd like

Solution steps 
- In this Ludo game I aims to provide a visually appealing and user-friendly interface that immerses players into the game's virtual world. With the ability to see the dice in action, restart the game when desired, and cancel the ongoing game, you have greater control and flexibility over your gaming experience.

![Ludo King Game](https://github.com/kunjgit/GameZone/assets/90240653/6dc5e629-acc4-4541-857b-8c96312a10be)

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @PriyankaTamhankar01 , You can't have another issue before completing the previous one 😀 
 you already have the following 1 open issues 👀 ! :

#2099

**Comment by kunjgit** [comment]
Hey @PriyankaTamhankar01 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by kunjgit** [comment]
Hey @PriyankaTamhankar01 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)
