### ISSUE TITLE
[Enhancement]: Adding a circle of progress to Scroll To Top Button & Minor Fixes

### ISSUE THREAD

**Issue by 5h0ov** [kunjgit/GameZone#2288]
### Is your enhancement request related to a problem? Please describe.➕

# Website enhancement

- I would like to add a circular progress bar wrapping the scroll to top button. I would also animate it so that when the user hovers over the button it enlarges.
- I would also like to make the Next/Back buttons take the user to the top of the webpage on clicking.
- I will look for other minor fixes while i work on this

# Short Preview of The Progress Bar Concept:
![scrollbutton](https://github.com/kunjgit/GameZone/assets/83227649/db746dc6-dbe9-407c-9c54-f3616467feba)

### Describe the solution you'd like

# Solution steps

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @5h0ov , You can't have another issue before completing the previous one 😀 
 you already have the following 1 open issues 👀 ! :

#2156

**Comment by kunjgit** [comment]
Hey @5h0ov ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
