### ISSUE TITLE
[New game]: Keyboard Hero

### ISSUE THREAD

**Issue by uzmaansari23** [kunjgit/GameZone#229]
### 🎮 Game Request

Game logic and basic description

Keyboard Hero is an exciting game created using HTML, CSS, and JavaScript that tests your typing skills and challenges you to achieve high scores. Here's a description of how the game works:

1. The game interface is built using HTML elements. It typically includes a container div to hold all the game elements, a text area or input field to display the text that needs to be typed, a score counter, and a timer.

2. The game elements are styled using CSS to create an appealing visual design. The text area or input field may have a distinctive appearance, and the score counter and timer are styled to be easily readable and prominent on the screen. The container div and other components can be styled with background colors, gradients, and other visual effects to enhance the overall look and feel of the game.

3. Initialization: When the game starts, JavaScript initializes the score and timer to zero and loads a set of words or sentences into an array. It sets up event listeners to track the user's keyboard input.

4. Word Selection: JavaScript randomly selects a word from the array and displays it in the text area or input field.
Keyboard Input Event: As the user types on the keyboard, JavaScript listens for key presses and compares the input to the displayed word. It checks if the user's input matches the current word, character by character. If the input matches, the user's score is incremented, and a new word is selected. If the input doesn't match, no score is added or deducted, and the user can try again.

5. Timer: A timer function is implemented using JavaScript's setInterval() method. It updates the timer element every second, providing a countdown for the player. When the timer reaches zero, the game ends, and the player's final score is displayed.

### Point down the features

Game points
The player starts the game with a score of zero and a timer set to a specific duration, such as 60 seconds. A word is displayed in the text area or input field, and the player must type it correctly before the timer runs out. As the player successfully types words, the score increases, and new words are displayed for typing. The player's objective is to achieve the highest score possible within the given time limit.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @uzmaansari23 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @uzmaansari23 👋!
 
  @kunjgit here, 
 We have this annoucement to make 📢!! 
 We have updated our README 🚀 
 Make sure you follow proper guideline to raise your next issues !! 
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG) if you haven't 😇 
  Thank you 💗!

**Comment by kunjgit** [comment]
Hey @uzmaansari23 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
