### ISSUE TITLE
[Enhancement]: Enhance Atari breakout game

### ISSUE THREAD

**Issue by whiteknight16** [kunjgit/GameZone#2290]
### Is your enhancement request related to a problem? Please describe.➕

Will change the looks and a bit of js logic will remove useless elements from screen

### Describe the solution you'd like

Made using HTML CSS and JS

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @whiteknight16 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
