### ISSUE TITLE
[New game]: Find the Differences 

### ISSUE THREAD

**Issue by Tisha6661** [kunjgit/GameZone#2291]
### 🎮 Game Request

In this game 2 same images will be given with some slight differences. The user has to find those differences.

### Point down the features

- Find the Differences game challenges players to spot the discrepancies between two similar images.
- The game offers a wide variety of image sets with different themes and difficulty levels.
- Players need to have a keen eye for detail and observation skills to identify the subtle differences.
- The game provides a relaxing and immersive experience, perfect for leisure time or a quick brain exercise.
- It can be played solo or with friends, fostering a competitive spirit to see who can find all the differences first.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Tisha6661 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
