### ISSUE TITLE
[New game]: Type it Musically

### ISSUE THREAD

**Issue by 584aditya** [kunjgit/GameZone#23]
### 🎮 Game Request

Type it Musically is a Musical typing Platform consisting of Piano Keys playing on typing. It is a Platform where users can play music on their own while typing. User can Do more and more practise and do not get bored while typing.

The logic behind this is that they see a piano tile coming from the top at every mapped key. The user presses the key shown on the screen and will enjoy a Piano melody. It is like Piano music added to Typing. While the User interacts with Music it Likes the way of Typing and tries to do typing more time and it makes its accuracy faster.

### Point down the features

- Natural Piano Feel: The Game uses High quality of audio samples recorded from real acoustics to provide users a better enhanced, natural feel of piano while typing.

- Music Selection: The game may include a Music selection feature where using can select music according to their choice and play aroun that sound.

- Enhanced UI: The game provides user a better UI so that user will not get stuck at any point while using the game and use the Platorm More Efficiently.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey  @584aditya ! Thank you for raising an issue 💗 You have been assigned this issue you can start working on the issue 🎮
Your game is really interesting 😃 
Looking forward to have Type it Musically on GameZone 🎮

**Comment by kunjgit** [comment]
Hello @584aditya, Time's Uppp!⏰ 
 Sorry for closing your issue! 
 But it's more than a week since we haven't received anything from your side 😢 . 
 Come up with new ideas, create a new issue and make sure you finish it within a week! 🔥 
 All the best! 🚀 
 Happy Hacking! 💗

**Comment by kunjgit** [comment]
Hey @584aditya ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
