### ISSUE TITLE
Dark Mode Addition

### ISSUE THREAD

**Issue by 1TusharSharma1** [kunjgit/GameZone#230]
Description:
I have opened an issue to request the addition of a Dark Mode feature to the Video Game GameZone project.

Dark Mode is a popular user interface option that provides a darker color scheme for the application. It offers an alternative visual style that is easier on the eyes, especially in low-light environments. By introducing Dark Mode to the GameZone project, we can enhance the user experience and provide flexibility in choosing a preferred theme.

Here are some details regarding the implementation of the Dark Mode feature:

Toggle Switch: The Dark Mode feature should include a toggle switch that allows users to switch between the light and dark color schemes. This switch can be placed in a prominent position within the user interface for easy accessibility.

CSS Styling: To implement Dark Mode, we need to define a new set of CSS styles that apply the dark color scheme to the various elements of the project. This includes background colors, text colors, buttons, and other UI components. It is important to ensure that the dark theme maintains readability and usability.

**Comment by kunjgit** [comment]
Hey @1TusharSharma1 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @1TusharSharma1 👋!
 
  @kunjgit here, 
 We have this annoucement to make 📢!! 
 We have updated our README 🚀 
 Make sure you follow proper guideline to raise your next issues !! 
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG) if you haven't 😇 
  Thank you 💗!

**Comment by kunjgit** [comment]
Hello @1TusharSharma1, Time's Uppp!⏰ 
 Sorry for closing your issue! 
 But it's more than a week since we haven't received anything from your side 😢 . 
 Come up with new ideas, create a new issue and make sure you finish it within a week! 🔥 
 All the best! 🚀 
 Happy Hacking! 💗

**Comment by kunjgit** [comment]
Hey @1TusharSharma1 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
