### ISSUE TITLE
Knife Hit game

### ISSUE THREAD

**Issue by I-shika** [kunjgit/GameZone#2300]
### 🎮 Game Request

Game logic and basic description:
I want to make a game knife hit in which each level fixed no of knife would be given and you have to throw all the knifes to rotating board . If you are successful then you will be promoted to next level. With increase in level the difficulty also increases.
![Screenshot (108)](https://github.com/kunjgit/GameZone/assets/100770197/6c999d5d-d0b7-4671-9567-a1dff3bf12b5)

### Point down the features

Game points

On suffecfully hitting the board you are promoted to next level.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @I-shika ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @I-shika! 🙂 
 It seems like you are not following proper guidelines !! 👀 
 Read documentation properly !!🙏 
 If you have any queries reach out to us on [Discord🕹️](https://discord.gg/fgwk4XZfxG) .

**Comment by kunjgit** [comment]
Hey @I-shika ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by I-shika** [comment]
please open this issue as it is marked close
