### ISSUE TITLE
[New game]: The labyrinth of death

### ISSUE THREAD

**Issue by Durgesh4993** [kunjgit/GameZone#2304]
### 🎮 Game Request

Game logic and basic description
You are Isaac Newton and you are searching for it in the underworld. Defeat Hades and claim it!

Use WASD to move, Space for the sword (if you collected it) and Shift to switch to boomerang boomerang (once you collect it) and WASD to control it.

Screenshort:
![image](https://github.com/kunjgit/GameZone/assets/98798977/0784f5b1-2c7e-4f86-93e2-7c263bd58ceb)

### Point down the features

Demo Vedio:

https://github.com/kunjgit/GameZone/assets/98798977/11278da1-3488-4d63-90a2-0da1853d1b3a

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Durgesh4993 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @Durgesh4993 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
