### ISSUE TITLE
[Enhancement]: Ludo Game 

### ISSUE THREAD

**Issue by PriyankaTamhankar01** [kunjgit/GameZone#2309]
### Is your enhancement request related to a problem? Please describe.➕

**Game enhancement :**

In this Ludo game I aims to provide a visually appealing and user-friendly interface that immerses players into the game's virtual world. With the ability to see the dice in action, restart the game when desired, and cancel the ongoing game, you have greater control and flexibility over your gaming experience.

### Describe the solution you'd like

Solution steps:
- Game Modes: Players can choose from different game modes such as single-player against computer opponents, local multiplayer with friends on the same device, or online multiplayer with players from around the world.

- Multiplayer Support: The game allows multiple players to participate simultaneously, either on a single device or through online connectivity.

- Dice Rolling: The game includes a virtual dice that can be rolled with a simple tap or click. The dice roll generates a random number to determine the number of spaces a player can move their token.

- Token Movement: Players can select and move their tokens by tapping or dragging them across the board. The movement follows the rules of the traditional Ludo game, with tokens moving clockwise and capturing opponent's tokens when landing on the same space.

- Capturing and Sending Back Tokens: When a player's token lands on a space occupied by an opponent's token, the digital version can automatically capture and send back the opponent's token to their starting area.

![image](https://github.com/kunjgit/GameZone/assets/90240653/6dc5e629-acc4-4541-857b-8c96312a10be)

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @PriyankaTamhankar01 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by PriyankaTamhankar01** [comment]
@kunjgit 
`_Could you please review my pull request? Your insights and feedback are highly valuable for identifying any overlooked issues or areas that can be improved._`

**Comment by kunjgit** [comment]
Hey @PriyankaTamhankar01 ! , This issue is already assigned to @PriyankaTamhankar01. 💗 
 You can work on other issues 🚀 
 If there is anything wrong you can contact us on [Discord🕹️](https://discord.gg/fgwk4XZfxG)👀

**Comment by kunjgit** [comment]
Hey @PriyankaTamhankar01 👋!
 
 @kunjgit here, 
 Hope you are doing extremely well 😇 
 It's confirmed 🥳, GameZone is taking part in hacktoberfest and ready to have another 💥 
 Ready to have some amazing contributions once again also thank you for you support in GSSoC23 you have took us on top 5 ❤️‍🔥 
 if you still haven't joined us join us on ⁠[Discord](https://discord.gg/fgwk4XZfxG) 
 See you soon 😊

**Comment by kunjgit** [comment]
Hello @PriyankaTamhankar01, Time's Uppp!⏰ 
 Sorry for closing your issue! 
 But it's more than a week since we haven't received anything from your side 😢 . 
 Come up with new ideas, create a new issue and make sure you finish it within a week! 🔥 
 All the best! 🚀 
 Happy Hacking! 💗

**Comment by kunjgit** [comment]
Hey @PriyankaTamhankar01 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
