### ISSUE TITLE
[New game]: MineSweeper

### ISSUE THREAD

**Issue by KanchanBora** [kunjgit/GameZone#2311]
### 🎮 Game Request

Game logic and basic description
Minesweeper is a classic puzzle game where players must uncover hidden mines on a grid-based board without detonating any of them. The objective is to reveal all non-mine cells using numerical clues provided by neighboring cells. Players can mark suspected mine locations with flags. The game ends if a mine is clicked, resulting in a loss, or when all non-mine cells are revealed, resulting in a win. It requires logical reasoning and deduction skills.

### Point down the features

Game points
Left click to reveal, right-click for flag.
A flag can't be revealed. Right-click again to undo.
Auto-reveal all cells surrounding an empty cell.
Stop game when mine is hit.
Difficulty and size selection by the user (currently by fixed values).
Shows how many mines are left (according to marked flags).
Show timer.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @KanchanBora ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @KanchanBora ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
