### ISSUE TITLE
[New game]: PiggyGame

### ISSUE THREAD

**Issue by KanchanBora** [kunjgit/GameZone#2312]
### 🎮 Game Request

The Pig game is a two-player dice game where players take turns rolling a die. The goal is to be the first player to reach 100 or more points. On each turn, players accumulate points by rolling the die and adding the numbers rolled to their score. However, if a player rolls a 1, their score is reset to 0, and their turn ends. Players have the choice to either continue rolling to accumulate more points or hold their current score. The game combines luck and decision-making, as players must strategize when to take risks and when to play it safe. The first player to reach the target score wins the game.

### Point down the features

If the player rolls a 1, their current score gets zeroed and the other player takes turn.
If the player rolls any other number, it is added to their current score and the player's turn continues.
If a player chooses to "hold" the current score, their turn total is added to their score and the other player takes turn.
The first player to score 100 or more points wins.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @KanchanBora ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
