### ISSUE TITLE
[Enhancement]: Adding a Congratulations Animation in Tic Tac Toe game.

### ISSUE THREAD

**Issue by Abhishek-Rajput-81** [kunjgit/GameZone#2314]
### Is your enhancement request related to a problem? Please describe.➕

Currently, the Tic Tac Toe game lacks a visual feedback mechanism to celebrate and congratulate the winning player. This enhancement aims to address this issue by incorporating a congratulations animation that triggers when a player successfully achieves a winning condition.

### Describe the solution you'd like

By making changes in the CSS and JS files.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Abhishek-Rajput-81 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @Abhishek-Rajput-81 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
