### ISSUE TITLE
[Enhancement]: Make play & have fun text clearly visible 

### ISSUE THREAD

**Issue by MisterMickey** [kunjgit/GameZone#2315]
### Is your enhancement request related to a problem? Please describe.➕

Make play & have fun text clearly visible by adding background color white and text color to black

### Describe the solution you'd like

I will make the paragraph background white and it's text color black with some border radius like this: 

![Screenshot from 2023-07-06 19-49-39](https://github.com/kunjgit/GameZone/assets/93720428/a9b0dc37-e0f2-4581-8475-67f7b213649c)

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @MisterMickey ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @MisterMickey ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
