### ISSUE TITLE
[Bug]: Pagination bug

### ISSUE THREAD

**Issue by krutikajichkar** [kunjgit/GameZone#2320]
### Give a brief about the bug ✍️

Pagination should not be visible at the time of searching

### What is the expected behavior? 🤔

whenever search result is shown pagination should disapper , please assign me this under gssoc'23

### Provide step by step information reproduce the bug 📄

I will make the pagination to disapper when search process is active

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @krutikajichkar , You can't have another issue before completing the previous one 😀 
 you already have the following 1 open issues 👀 ! :

#2318

**Comment by kunjgit** [comment]
Hey @krutikajichkar ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by kunjgit** [comment]
Hey @krutikajichkar ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by krutikajichkar** [comment]
@kunjgit you have closed this issue
