### ISSUE TITLE
[New game]: Trash Dash 

### ISSUE THREAD

**Issue by anjaliSilawat** [kunjgit/GameZone#2328]
### 🎮 Game Request

Game logic and basic description
The game is based on garbage bin collection. In this game, there will be floating dustbins displayed on the screen. The objective is to collect these dustbins, and for each collected bin, players will earn points. However, if even one bin is missed, the game will be considered lost.

![image](https://github.com/kunjgit/GameZone/assets/108583230/315a3bcd-ee7e-4371-a6e4-0b6eacce1b12)

I would like to work on this , please assign it to me @kunjgit 

### Point down the features

Game points

Players will earn points based on the number of dustbins they successfully collect. Each collected bin will add to their point total. However, if a bin is missed, no points will be awarded, and the game will end with a loss.

### Select program in which you are contributing

There are several game types that can be considered for the garbage bin collection game. Here are a few options:

Time-based challenge: Players have a limited amount of time to collect as many dustbins as possible. The faster they collect, the more points they earn.

Level-based progression: The game consists of multiple levels, each with an increasing difficulty. Players need to collect a certain number of dustbins within each level to progress to the next one.
### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @anjaliSilawat ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by anjaliSilawat** [comment]
> Hey @anjaliSilawat ! Thank you for raising an issue 💗 You can self assign the issue by commenting /assign in comment 😀 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone) Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

okay @kunjgit 😊

**Comment by kunjgit** [comment]
Hey @anjaliSilawat 👋!
 
 @kunjgit here, 
 Hope you are doing extremely well 😇 
 It's confirmed 🥳, GameZone is taking part in hacktoberfest and ready to have another 💥 
 Ready to have some amazing contributions once again also thank you for you support in GSSoC23 you have took us on top 5 ❤️‍🔥 
 if you still haven't joined us join us on ⁠[Discord](https://discord.gg/fgwk4XZfxG) 
 See you soon 😊

**Comment by kunjgit** [comment]
Hey @anjaliSilawat 👋!
 
 @kunjgit here, 
 Hope you are enjoying this hacktober 😀 
 We are excited to share that we are opening issue from our side where you will be going to add games on our website 🚀 
 Work on this [issue](https://github.com/kunjgit/GameZone/issues/2944) 🔥 
 and help us building GameZone 💗 
 if you still haven't joined us join us on ⁠[Discord](https://discord.gg/fgwk4XZfxG) 
 See you soon 😊

**Comment by kunjgit** [comment]
Hello @anjaliSilawat, Time's Uppp!⏰ 
 Sorry for closing your issue! 
 But it's more than a week since we haven't received anything from your side 😢 . 
 Come up with new ideas, create a new issue and make sure you finish it within a week! 🔥 
 All the best! 🚀 
 Happy Hacking! 💗

**Comment by kunjgit** [comment]
Hey @anjaliSilawat ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
