### ISSUE TITLE
[Enhancement]: Enhancing Social Anchor Accessibility in Footers

### ISSUE THREAD

**Issue by Avinash905** [kunjgit/GameZone#2330]
### Is your enhancement request related to a problem? Please describe.➕

This feature aims to improve the accessibility of social anchors within the footer by implementing a comprehensive solution for screen reader users.

### Describe the solution you'd like

To accomplish this, the issue involves implementing the addition of the aria attributes for social anchors, within the footer element. This attribute allows for the provision of a descriptive label specifically designed to be read aloud by screen readers. By doing so, we ensure that users receive additional context about the purpose of these elements.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by Avinash905** [comment]
Please assign me this issue so that I can work on this issue under **GSSOC'23**.

**Comment by kunjgit** [comment]
Hey @Avinash905 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @Avinash905 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
