### ISSUE TITLE
[Enhancement]: 'Whack a Mole' Game Boxes Design Enhancement

### ISSUE THREAD

**Issue by iamRabia-N** [kunjgit/GameZone#2334]
### Is your enhancement request related to a problem? Please describe.➕

No. It's an enhancement in the existing design.

### Describe the solution you'd like

Working on the styling of the boxes.

Current Design
![gamezone (1)](https://github.com/kunjgit/GameZone/assets/115794049/a414d59f-ebec-4c12-975c-1bf54487d03d)

Expected Updated Design
![gamezone (2)](https://github.com/kunjgit/GameZone/assets/115794049/6f2976fa-63c4-4916-9f4d-540295ae2f45)

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @iamRabia-N ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by iamRabia-N** [comment]
Assign me this issue

**Comment by iamRabia-N** [comment]
@gurjeetsinghvirdee Kindly closed this issue as done so that I can rise next issue.

**Comment by kunjgit** [comment]
Hey @iamRabia-N ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
