### ISSUE TITLE
[New game]: BreakOut

### ISSUE THREAD

**Issue by Deepanshu0703** [kunjgit/GameZone#2337]
### 🎮 Game Request

Breakout, a classic arcade game,
Smash bricks with a ball, your aim.
Keep the ball in play with the paddle's might,
Clear levels, secure your lives, for gaming delight!(You will be having 3 life in each game and you life will be revive to 3 again after clearing the level)

This what game is all About

### Point down the features

Game points

In the captivating realm of Breakout, every brick demolished is a gateway to points galore.
As the ball dances across the screen, the player's objective is clear - smash through the vibrant barrier. With each successful collision, the player is rewarded with 10 points. It's a race against time to dismantle the bricks, while keeping the ball in play and accumulating a formidable score.  Also the Points will be increased by 10 according to the level.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Deepanshu0703 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @Deepanshu0703 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
