### ISSUE TITLE
[New game]: Save Princess

### ISSUE THREAD

**Issue by sabhisharma-ise** [kunjgit/GameZone#2340]
### 🎮 Game Request

This is a JavaScript game implemented using the HTML5 Canvas element. It is a platformer game where the player controls a character and tries to save the princess while avoiding enemies and navigating through the terrain.

### Point down the features

The player character is represented by a square with a specified color. The player can move left and right using the arrow keys or 'A' and 'D' keys, jump using the up arrow key or 'W' key, and shoot by pressing the spacebar.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @sabhisharma-ise ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @sabhisharma-ise ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
