### ISSUE TITLE
[New game]: Lamb_Lane

### ISSUE THREAD

**Issue by akhilender-bongirwar** [kunjgit/GameZone#2341]
### 🎮 Game Request

Game logic and basic description
"Lamb Lane" is an exciting game where you control a sheep crossing multiple lanes filled with moving vehicles and obstacles. Your objective is to navigate the sheep safely across the road, avoiding collisions and acquiring more points.
- Move the chicken forward, backward, left, or right.
- Dodge cars and trucks as you cross the lanes.
- Immersive gameplay with a 3D environment created using Three.js.

### Point down the features

Game points
1. Start at one end of the cross lanes.
2. Experience the 3D moving trucks and cars.
3. Dodge them properly to gain more points.
4. If you collide with any vehicle then your game gets stopped.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @akhilender-bongirwar ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @akhilender-bongirwar ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
