### ISSUE TITLE
[New game]: Guess the game flag. [gssoc23]

### ISSUE THREAD

**Issue by thevirengarg** [kunjgit/GameZone#2344]
### 🎮 Game Request

Game logic and basic description

## **Description 📃** 
- This program is designed to learn the flags of different countries
- So that everyone can identify the flag of different countries and boost your knowledge

### Point down the features

Game points
## **functionalities** 
- Press the start button to start the game
- Drag the flag of respective country and put into their box
- Finally, enjoy the grand congratulation of winning

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @thevirengarg ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @thevirengarg ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
