### ISSUE TITLE
[New Feature]: add workflow to lock new issues [gssoc23]

### ISSUE THREAD

**Issue by harmeetsingh11** [kunjgit/GameZone#2348]
**Is your feature request related to a problem? Please describe.**
This repository has 85+ opened issues. 
Issues receive more comments as a whole. As a result, the number of desktop and mobile notifications rises, making their management challenging for repository maintainers, admins. 

**Describe the solution you'd like**
I will add the github action workflow, which will lock new new issues. This means that, when the new issue is created, it will be locked. The issue will be unlocked when the maintainer/admin will add `status: ready for dev` label to it. The admins and maintainers would greatly benefit from this, and it would also reduce notifications.

**Record**
- [x] I agree to follow project's contribution guidelines and code of conduct.
- [x] I'm a GSSoC'23 contributor.
- [x] I want to work on this issue.

Thanks

**Comment by kunjgit** [comment]
Hey @harmeetsingh11 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @harmeetsingh11! 🙂 
 It seems like you are not following proper guidelines !! 👀 
 Read documentation properly !!🙏 
 If you have any queries reach out to us on [Discord🕹️](https://discord.gg/fgwk4XZfxG) .

**Comment by kunjgit** [comment]
Hey @harmeetsingh11 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
