### ISSUE TITLE
[Enhancement]: Adding sound to the keyboard whenever they type something during the game "Master Typing" GSSOC'23 Contributor

### ISSUE THREAD

**Issue by SnigdhaP2022** [kunjgit/GameZone#235]
### Is your enhancement request related to a problem? Please describe.➕

Game enhancement. I would like to add sound for the game which makes game more interactive for the gamer.

### Describe the solution you'd like

Solution steps using Html and external Js, we can add the different sounds for typing different keys for the game. I would like to work on this.
<img width="1437" alt="Screenshot 2023-05-22 at 1 58 06 PM" src="https://github.com/kunjgit/GameZone/assets/102572480/a2ada86b-559c-43bd-8425-e0c8399cb7b2">

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @SnigdhaP2022 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @SnigdhaP2022 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by Harshvardhan-Dubey-Github** [comment]
please assign me this issue

**Comment by kunjgit** [comment]
Hello @SnigdhaP2022, Time's Uppp!⏰ 
 Sorry for closing your issue! 
 But it's more than a week since we haven't received anything from your side 😢 . 
 Come up with new ideas, create a new issue and make sure you finish it within a week! 🔥 
 All the best! 🚀 
 Happy Hacking! 💗

**Comment by kunjgit** [comment]
Hey @SnigdhaP2022 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
