### ISSUE TITLE
[New game]: Baseball Blitz Game

### ISSUE THREAD

**Issue by abhinav-m22** [kunjgit/GameZone#2359]
### 🎮 Game Request

I want to add new baseball game using HTML, CSS, and JavaScript. This game aims to provide an immersive and enjoyable experience for players. 

### Point down the features

1. Baseball gameplay mechanics, including pitching, hitting, fielding, and baserunning. 
2. Introduce a multiplayer mode that allows players to compete against each other online.
3. Multiple difficulty levels to cater to players of different skill levels.
4. Track and display comprehensive game statistics and score.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @abhinav-m22 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @abhinav-m22 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
