### ISSUE TITLE
[Documentation Bug]:  Updating  README file for Pokedex game

### ISSUE THREAD

**Issue by SnigdhaP2022** [kunjgit/GameZone#2364]
### Describe the bug ✍️

Describe your bug here

Would like to add  readme file to pokedex game

### Provide step by step information reproduce the bug 📄

Description

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @SnigdhaP2022 , You can't have another issue before completing the previous one 😀 
 you already have the following 1 open issues 👀 ! :

#2363

**Comment by kunjgit** [comment]
Hey @SnigdhaP2022 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)
