### ISSUE TITLE
[New game]: Colour wheel

### ISSUE THREAD

**Issue by invigorzz313** [kunjgit/GameZone#2369]
### 🎮 Game Request

This game contains a colour wheel and a shooter which shoots coloured balls towards it.

### Point down the features

A wheel with many colours keeps on rotating.
User operates a shooter gun that gets random coloured ball in each try.
Cursor or spacebar clicking will shoot the colour ball towards the wheel.
If the colour matches, user scores a point.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @invigorzz313 , You can't have another issue before completing the previous one 😀 
 you already have the following 1 open issues 👀 ! :

#2367

**Comment by kunjgit** [comment]
Hey @invigorzz313 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by kunjgit** [comment]
Hey @invigorzz313 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by invigorzz313** [comment]
@kunjgit can this issue be opened now? as I have no other open issues.
