### ISSUE TITLE
[New game]: Shoot and Destroy

### ISSUE THREAD

**Issue by Swa-stika** [kunjgit/GameZone#2373]
### 🎮 Game Request

Game logic and basic description:

"Shoot and Destroy" is an engaging ball shooting game where your objective is to aim and eliminate the incoming balls before they reach the base line. Your goal is to successfully eliminate all the balls to win the game. However, if any of the balls touch the base line, you lose. The game controls are intuitive and straightforward - you can use the arrow keys to control the direction of your shooter and also move the shooter across the screen. Put your aiming and reflex skills to the test and see if you can emerge victorious in this challenging ball shooting game.

### Point down the features

Game points:
- Aim and Shoot: The game allows you to aim and shoot at the incoming balls to eliminate them before they reach the base line.
- Win Condition: Your objective is to successfully eliminate all the balls to win the game.
- Lose Condition: If any of the balls touch the base line, you lose the game.
- Intuitive Controls: You can control the shooting direction of your shooter as well as its movement using the arrow keys.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Swa-stika , You can't have another issue before completing the previous one 😀 
 you already have the following 1 open issues 👀 ! :

#2207

**Comment by kunjgit** [comment]
Hey @Swa-stika ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by Swa-stika** [comment]
@kunjgit I would like  you to open this issue , and assign me this issue.
