### ISSUE TITLE
[Documentation Bug]: Broken link in Contributing Guidelines

### ISSUE THREAD

**Issue by jfmartinz** [kunjgit/GameZone#2377]
### Describe the bug ✍️

In the `contributing_guideline.md`. In section `Need some help regarding the basics?🤔` , there is a broken link which you can see once you click it. The broken link is in 5th bullet point: 
![image](https://github.com/kunjgit/GameZone/assets/129386460/998857ec-f67d-4a20-b507-b85382fbbb83)

When the link is clicked, This is the output displayed: 
![image](https://github.com/kunjgit/GameZone/assets/129386460/815e7528-1f8e-4a16-90cc-a3b1837aa370)

I want to add an alternative resource that we can put instead of the old one. If you like this idea, can anyone give me an alternative resource or i'm just going to find a related topic for the broken link? Please let me know :)

### Provide step by step information reproduce the bug 📄

1. Go find `.github/`
2. Inside `.github/`, go to `[CONTRIBUTING_GUIDELINE.md` file.
3. Look for the section `Need some help regarding the basics?🤔` 
4. Check the fifth bullet point which is `Learn GitHub from Scratch`
5. Click the link

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @jfmartinz , You can't have another issue before completing the previous one 😀 
 you already have the following 1 open issues 👀 ! :

#2371

**Comment by kunjgit** [comment]
Hey @jfmartinz ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)
