### ISSUE TITLE
[New game]: Be with 1

### ISSUE THREAD

**Issue by jaivsh** [kunjgit/GameZone#2381]
### 🎮 Game Request

   **In** this game, the goal of the user would be to remain as close to 1 as possible. There would be a 2-d square matrix, with numbers as element-boxes inside of it. And on top of it would be another box with some number written on it. The user would use arrow keys to manuver the top box to the bottommost level. As the user would descend into numeric boxes, their score is gonna add up as per the numeric value of the box. During this process, the user would try to be as close to 1 as possible to gain maximum points and to advance to next rounds. 

**Rules:**
During this traversal process, 

    - If your number encounters a factor, it will be divided by that factor.
    - All other numbers will add to your number.

### Point down the features

- Levels would be generated post each round automatically.
- Some levels would not have an opportunity for players to get 1. In such cases, the solution would be to find the most optinum score. 

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @jaivsh ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @jaivsh ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
