### ISSUE TITLE
[New game]: Gravity game

### ISSUE THREAD

**Issue by kumar11jr** [kunjgit/GameZone#2382]
### 🎮 Game Request

Game logic and basic description
In this game, the player controls a red character by shifting the gravity direction using the arrow keys. The goal is to avoid colliding with the gray obstacle. The JavaScript code handles the character movement, collision detection, and game loop.

## Game Features

- Real-time gravity shifting based on arrow key inputs: Players can control the character's movement by shifting the gravity in different directions using the arrow keys.

- Simple and intuitive controls: The game provides easy-to-understand controls, making it accessible to players of all skill levels.

- Dynamic obstacle placement: The game features dynamically placed obstacles that challenge players to navigate through the maze strategically.

- Game over alert when colliding with an obstacle: If the player collides with an obstacle, a game over alert is displayed, indicating the end of the game.

- Game reset functionality: Players can reset the game by clicking the "Start" button, allowing them to play again and attempt to improve their performance.

- Engaging gameplay: Gravity Shift offers a unique gameplay experience that requires quick reflexes, strategic thinking, and precise control to navigate through the maze successfully.

- Challenging levels: The game can be extended with multiple levels of increasing difficulty, offering players new challenges as they progress.

- Responsive design: The game interface is built with responsive design principles, allowing it to adapt to different screen sizes and devices.

- Visual feedback: The game provides visual feedback to indicate the character's movement and the impact of gravity shifting, enhancing the overall gaming experience.

- Customizable elements: The game can be customized by modifying the maze layout, obstacle design, character appearance, or other visual elements to suit individual preferences or thematic variations.

- Addictive and replayable: Gravity Shift's unique gameplay mechanics and challenging nature make it an addictive and replayable game, enticing players to aim for high scores and improve their performance.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @kumar11jr ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @kumar11jr 👋!
 
 @kunjgit here, 
 Hope you are doing extremely well 😇 
 It's confirmed 🥳, GameZone is taking part in hacktoberfest and ready to have another 💥 
 Ready to have some amazing contributions once again also thank you for you support in GSSoC23 you have took us on top 5 ❤️‍🔥 
 if you still haven't joined us join us on ⁠[Discord](https://discord.gg/fgwk4XZfxG) 
 See you soon 😊

**Comment by kunjgit** [comment]
Hey @kumar11jr 👋!
 
 @kunjgit here, 
 Hope you are enjoying this hacktober 😀 
 We are excited to share that we are opening issue from our side where you will be going to add games on our website 🚀 
 Work on this [issue](https://github.com/kunjgit/GameZone/issues/2944) 🔥 
 and help us building GameZone 💗 
 if you still haven't joined us join us on ⁠[Discord](https://discord.gg/fgwk4XZfxG) 
 See you soon 😊

**Comment by kunjgit** [comment]
Hey @kumar11jr ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
