### ISSUE TITLE
[Bug]: "Missing cursor property in code snippet."

### ISSUE THREAD

**Issue by GauriBhandari** [kunjgit/GameZone#2384]
### Give a brief about the bug ✍️

Description:

I noticed that in the provided code snippet, the cursor property is missing for the label element. This property is important as it determines the appearance of the cursor when hovering over an interactive element.

### What is the expected behavior? 🤔

Description

To improve the user experience and provide visual feedback, I suggest adding the "cursor: pointer;" CSS property to the inline style of the label element. This will change the cursor to a pointer shape, indicating that the label is clickable.

### Provide step by step information reproduce the bug 📄

Description: 

Including the cursor property will enhance the usability and intuitiveness of the code snippet. I believe this small addition will significantly improve the user interaction with the theme toggle feature.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @GauriBhandari ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by GauriBhandari** [comment]
I have self-assigned this issue and will be working on it. Thank you for your attention to this matter.

**Comment by GauriBhandari** [comment]
@kunjgit Could you please add the respective labels to the issue.

**Comment by GauriBhandari** [comment]
@kunjgit  @Arun9739  Could you please assign me this issue so that I can create the PR with link to  the relevant issue

**Comment by kunjgit** [comment]
Hey @GauriBhandari 👋!
 
 @kunjgit here, 
 Hope you are doing extremely well 😇 
 It's confirmed 🥳, GameZone is taking part in hacktoberfest and ready to have another 💥 
 Ready to have some amazing contributions once again also thank you for you support in GSSoC23 you have took us on top 5 ❤️‍🔥 
 if you still haven't joined us join us on ⁠[Discord](https://discord.gg/fgwk4XZfxG) 
 See you soon 😊

**Comment by kunjgit** [comment]
Hey @GauriBhandari 👋!
 
 @kunjgit here, 
 Hope you are enjoying this hacktober 😀 
 We are excited to share that we are opening issue from our side where you will be going to add games on our website 🚀 
 Work on this [issue](https://github.com/kunjgit/GameZone/issues/2944) 🔥 
 and help us building GameZone 💗 
 if you still haven't joined us join us on ⁠[Discord](https://discord.gg/fgwk4XZfxG) 
 See you soon 😊

**Comment by kunjgit** [comment]
Hello @GauriBhandari, Time's Uppp!⏰ 
 Sorry for closing your issue! 
 But it's more than a week since we haven't received anything from your side 😢 . 
 Come up with new ideas, create a new issue and make sure you finish it within a week! 🔥 
 All the best! 🚀 
 Happy Hacking! 💗

**Comment by kunjgit** [comment]
Hey @GauriBhandari ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
