### ISSUE TITLE
[New game]:  Pokemon card Game

### ISSUE THREAD

**Issue by SnigdhaP2022** [kunjgit/GameZone#2387]
### 🎮 Game Request

Game logic and basic description

This is a game which we used to play offline during our childhood. Now, I have come up making this as online game. It ressembles just as offline with same rules. But the give away is we can see our card in BIG Screen. Isn't it fun.

### Point down the features

Game points

Coming to the technical aspect, It can be built using simple HTML, CSS and JavaScript.
After, hitting live server button, we can see one participant cards on the screen. This project can be extended further.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @SnigdhaP2022 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @SnigdhaP2022 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
