### ISSUE TITLE
[New game]: Word Scramble

### ISSUE THREAD

**Issue by pavitrachavda97** [kunjgit/GameZone#239]
### 🎮 Game Request

Game logic and basic description
A word is given to player with random position of character and player have to guess that word and if player will guess it correctly then player score will increase and if player guess it wrong then there are only 8 guesses and then game will start again. Level will increases according to player points.

### Point down the features

Game points
if user will guess correct then score will increase
else score will decrease
if score will be at some point according to level score requirement then level will increase and word length will also increase accordingly.
If player can not guess word in given attempt then game will end and start again

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @pavitrachavda97 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by pavitrachavda97** [comment]
Thank you @kunjgit for assigning this issue to me.

**Comment by kunjgit** [comment]
Hey @pavitrachavda97 👋!
 
  @kunjgit here, 
 We have this annoucement to make 📢!! 
 We have updated our README 🚀 
 Make sure you follow proper guideline to raise your next issues !! 
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG) if you haven't 😇 
  Thank you 💗!

**Comment by kunjgit** [comment]
Hey @pavitrachavda97 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
