### ISSUE TITLE
[Bug]: Scrolling Behavior is Not Smooth and Up to The Mark in Main Page

### ISSUE THREAD

**Issue by NarendraKoya999** [kunjgit/GameZone#2391]
### Give a brief about the bug ✍️

Description: 
- **Much Need for Scrolling Behavior improving in Main Page**

### What is the expected behavior? 🤔

Description;
- **Expecting Scrolling Behavior smooth**

### Provide step by step information reproduce the bug 📄

Description:
- Go to the https://kunjgit.github.io/GameZone/
- Checking the Scrolling Behavior using Scroll Up Icon.
- Checking with any Browser Compatibility Issues happening OR Not.
- If happening, the Required changes in our Project Codebase

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @NarendraKoya999 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)
