### ISSUE TITLE
[New game]: Solitaire

### ISSUE THREAD

**Issue by Deepanshu0703** [kunjgit/GameZone#2392]
### 🎮 Game Request

Solitaire is a popular single-player card game played with a standard deck. The objective is to arrange the cards in a specific manner, typically by suit and in ascending order. Players make moves by rearranging the cards on the tableau or foundation piles according to specific rules. The game requires strategic thinking and problem-solving skills to create sequences and free up cards. Solitaire is enjoyed by many as a challenging and relaxing pastime.

### Point down the features

It's a simple game just on completing it and thus changing the level and gives points on completing each level.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Deepanshu0703 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @Deepanshu0703 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
