### ISSUE TITLE
[New Game]: Astray Game 

### ISSUE THREAD

**Issue by vamshi726** [kunjgit/GameZone#2394]
### Game logic and basic description

In this game player use the arrow keys to control the movement of a ball within a maze and their objective is to find the exit. Here's a possible implementation of the game logic using arrow keys for movement:

When an arrow key is pressed, check the adjacent cell in the corresponding direction to see if it's a valid move.
 • If the adjacent cell is a path (not a wall), move the ball to that cell.
 • If the adjacent cell is the exit point, the player wins the game.
 • If the adjacent cell is a wall, ignore the movement.

If the player reaches the exit, then player move to next Level.

### Screenshot of the game
![image](https://github.com/kunjgit/GameZone/assets/63087230/244ec945-6385-4648-a668-3809503a2efb)

### Game points

Points are awarded for completing specific objectives/levels within the game. By, reaching the exit point in each level of a maze game could reward the player with points.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @vamshi726! 
We are already having a similar game request in #2387 👀 
Make sure you come up with a cool unique idea 😀 
 Waiting for your new game idea 💗.

**Comment by kunjgit** [comment]
Hey @vamshi726 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @vamshi726 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
