### ISSUE TITLE
[New game]: Space Invaders

### ISSUE THREAD

**Issue by varshanim** [kunjgit/GameZone#24]
### 🎮 Game Request

Game logic and basic description: 
Space invaders is a game in which there are aliens in N-rows and they will increase with time and the bottom-most row of the aliens will keep shooting at you space ship. You will be in a spaceship and you can destroy the aliens by shooting at them with the help of your spaceship. When you shoot at an alien it dies(disappears).
This game can be developed by using JavaScript.

### Point down the features

Game points:
Everytime you shoot at an alien you will awarded 10 pts and everytime you get shot by an alien your lives will be decreased by 1. You will be given 3 lives per games and when all the lives have been exhausted the game ends. I have attached a sample of what the game would look like after developement.

### Select program in which you are contributing

GSSoC'23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.
![Screenshot 2023-05-20 at 10 12 00 AM](https://github.com/kunjgit/GameZone/assets/105119278/59d47202-0e82-4e35-9e0e-98113cdf69da)

**Comment by kunjgit** [comment]
Hey @varshanim  ! Thank you for raising an issue 💗 You have been assigned this issue you can start working on the issue 🎮

**Comment by kunjgit** [comment]
Hello @varshanim, Time's Uppp!⏰ 
 Sorry for closing your issue! 
 But it's more than a week since we haven't received anything from your side 😢 . 
 Come up with new ideas, create a new issue and make sure you finish it within a week! 🔥 
 All the best! 🚀 
 Happy Hacking! 💗

**Comment by kunjgit** [comment]
Hey @varshanim ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by varshanim** [comment]
Hey @kunjgit Can i proceed on this now? I'm sorry I couldn't get back to you as I haven't been feeling quite well for the past month but i'm better now and i would love to work on this issue again under GSSoC'23
