### ISSUE TITLE
[New game]: Lights Out 

### ISSUE THREAD

**Issue by Vishalqw78** [kunjgit/GameZone#240]
### 🎮 Game Request

Game logic and basic description

I want to contribute with a Lights Out Game.

The Lights Out game is a puzzle game that involves a grid of lights, usually arranged in a square pattern. The goal of the game is to turn off all the lights on the grid. The challenge arises from the fact that toggling a light not only changes its own state but also affects the neighboring lights, requiring the player to carefully plan their moves to achieve the objective of turning off all the lights in the grid.

### Point down the features

Game points

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Vishalqw78 👋!
 
  @kunjgit here, 
 We have this annoucement to make 📢!! 
 We have updated our README 🚀 
 Make sure you follow proper guideline to raise your next issues !! 
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG) if you haven't 😇 
  Thank you 💗!

**Comment by kunjgit** [comment]
Hey @Vishalqw78 👋!
 
  @kunjgit here, 
 We have this annoucement to make 📢!! 
 During the time of PR don't alter main index file ! 🙂 
 In main Readme file just use * as a game number during the time we are merging we will add number !! 👀 
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG) if you haven't 😇 
  Thank you 💗!

**Comment by Harshvardhan-Dubey-Github** [comment]
please assign me this issue

**Comment by kunjgit** [comment]
Hey @Vishalqw78 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
