### ISSUE TITLE
[New game]:  Asteroids 3D

### ISSUE THREAD

**Issue by sabhisharma-ise** [kunjgit/GameZone#2400]
### 🎮 Game Request

Implementing a 3D software renderer for rendering asteroids. 

### Point down the features

The game features a player-controlled spaceship that can move and shoot bullets. The goal of the game is to destroy the asteroids by shooting them with bullets. The asteroids move around the screen and can collide with the player's spaceship. The game also includes explosions and visual effects.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @sabhisharma-ise ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @sabhisharma-ise ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
