### ISSUE TITLE
[Enhancement]: Adding Reset Button and Score Feature to 3D Box Game

### ISSUE THREAD

**Issue by Abhishek-Rajput-81** [kunjgit/GameZone#2412]
### Is your enhancement request related to a problem? Please describe.➕

I have identified two key features that would greatly enhance the user experience of our 3D Box game: a reset button and a score system. Currently, players are unable to reset the game or track their performance, limiting their engagement. To address these issues, I propose the implementation of a reset button and score feature, which will improve gameplay and provide players with a more enjoyable and competitive experience.

### Describe the solution you'd like

1. Adding a Reset Button
2. Introducing a Score System
3. User Interface Design

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Abhishek-Rajput-81 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)
