### ISSUE TITLE
[New game]: Etch-a-Sketch Game

### ISSUE THREAD

**Issue by Avdhesh-Varshney** [kunjgit/GameZone#2415]
### 🎮 Game Request

Game logic and basic description

- This game is a beginner friendly game.
- Also a beginner friendly project.
- Create so many images just hovering over the blocks of the grid or touch the blocks of the grid.
- Create as much large grid as you want.

### Point down the features

Game points

- Create emojis and different pictures
- Enjoy the game !

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Avdhesh-Varshney ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @Avdhesh-Varshney ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
