### ISSUE TITLE
[Documentation Bug]: README.md file enhancement

### ISSUE THREAD

**Issue by DivyanshiNarang** [kunjgit/GameZone#2417]
### Describe the bug ✍️

<img width="609" alt="Screenshot 2023-07-14 112934" src="https://github.com/kunjgit/GameZone/assets/74779601/8c99519d-2210-4cbd-a0e2-faf4238b27a7">

Official documentation links are not added to these buttons.

### Provide step by step information reproduce the bug 📄

We can add official documentation links of the respective technologies used so that it will be helpful for new contributors.

*Please assign this issue to me under gssoc23* @kunjgit 

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @DivyanshiNarang ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @DivyanshiNarang ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by kunjgit** [comment]
Hey @DivyanshiNarang ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
