### ISSUE TITLE
[New game]: Tech Quiz Game 

### ISSUE THREAD

**Issue by DivyanshiNarang** [kunjgit/GameZone#2418]
### 🎮 Game Request

In this tech quiz game, A question with 3 options will be given out of which one is the correct answer and player has to answer in the given time frame. the 

### Point down the features

This game will help players to learn new things in an interactive way.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @DivyanshiNarang , You can't have another issue before completing the previous one 😀 
 you already have the following 1 open issues 👀 ! :

#2417

**Comment by kunjgit** [comment]
Hey @DivyanshiNarang ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by kunjgit** [comment]
Hey @DivyanshiNarang ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)
