### ISSUE TITLE
[Enhancement]: Improving Theme Toggler Button

### ISSUE THREAD

**Issue by dishamodi0910** [kunjgit/GameZone#2428]
### Is your enhancement request related to a problem? Please describe.➕

Game enhancement

- The entire GameZone looks quite aesthetic. But the theme toggler isn't looking that awesome in styling.

### Describe the solution you'd like

Solution steps
- I would like to modify the theme toggler designing based on some of the neon designs.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @dishamodi0910 , You can't have another issue before completing the previous one 😀 
 you already have the following 1 open issues 👀 ! :

#2376

**Comment by kunjgit** [comment]
Hey @dishamodi0910 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by kunjgit** [comment]
Hey @dishamodi0910 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)
