### ISSUE TITLE
[New game]: Dhoom Bike race

### ISSUE THREAD

**Issue by vamshi726** [kunjgit/GameZone#2433]
### 🎮 Game Request

Game logic and basic description:
The objective of the game is usually to complete various levels or challenges by successfully executing Race, jumps, flips, and tricks while maintaining balance and control of the bike. And for each and every jump the score will increases.

### Point down the features

Game points:
- Bike Controls: Players can control the bike's speed, acceleration, braking, and direction using on-screen left, top , right , bottom keyboard inputs. T

- This allows them to navigate through the game's environment and perform jumps and tricks.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @vamshi726 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @vamshi726 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
