### ISSUE TITLE
[New game]: Hangman_Game

### ISSUE THREAD

**Issue by vaibhavi-d18** [kunjgit/GameZone#244]
### 🎮 Game Request

Game logic and basic description
Hangman is a word-guessing game built using HTML , CSS and JavaScript where players try to uncover a secret word by guessing letters. The game starts with a blank representation of the word, and players must guess one letter at a time. If the guessed letter is correct, it is revealed in the corresponding positions. However, if the guessed letter is incorrect, a part of the hangman's body is drawn. The game continues until the word is guessed correctly or the hangman is fully drawn, resulting in a loss. It's a challenging and fun game that tests players' word knowledge and deduction skills.

### Point down the features

Game points
If entered letter is guessed correctly then it is seen in its corresponding position 
If entered letter is incorrect , a part of hangman body is drawn for each incorrect guess
If body of hangman gets completed then player will loose the game
If player guessed the word before the hangman body gets complete he/she will win

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @vaibhavi-d18 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @vaibhavi-d18 👋!
 
  @kunjgit here, 
 We have this annoucement to make 📢!! 
 We have updated our README 🚀 
 Make sure you follow proper guideline to raise your next issues !! 
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG) if you haven't 😇 
  Thank you 💗!

**Comment by kunjgit** [comment]
Hey @vaibhavi-d18 👋!
 
  @kunjgit here, 
 We have this annoucement to make 📢!! 
 During the time of PR don't alter main index file ! 🙂 
 In main Readme file just use * as a game number during the time we are merging we will add number !! 👀 
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG) if you haven't 😇 
  Thank you 💗!

**Comment by kunjgit** [comment]
Hello @vaibhavi-d18, Time's Uppp!⏰ 
 Sorry for closing your issue! 
 But it's more than a week since we haven't received anything from your side 😢 . 
 Come up with new ideas, create a new issue and make sure you finish it within a week! 🔥 
 All the best! 🚀 
 Happy Hacking! 💗

**Comment by kunjgit** [comment]
Hey @vaibhavi-d18 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
