### ISSUE TITLE
[New game]: Dinoffline

### ISSUE THREAD

**Issue by Durgesh4993** [kunjgit/GameZone#2441]
### 🎮 Game Request

Game logic and basic description
This is a 3D remake of the famous Chrome Dino Game. Run as far as possible or race with one of your friends, but be careful not to bumb into any obsticles!

The game inculdes:
-Day-Night Cycles
-Co-op Multiplayer

### Point down the features

ScreenSort:
![image](https://github.com/kunjgit/GameZone/assets/98798977/58b98b6d-8dc9-4750-8e75-f0f5e090c05a)

Demo Vedio:

https://github.com/kunjgit/GameZone/assets/98798977/5b1e0ff0-9509-4382-a348-599a29015162

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Durgesh4993 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @Durgesh4993 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
