### ISSUE TITLE
[Bug]: Game name and play and have fun is not visible

### ISSUE THREAD

**Issue by Ashasindhu** [kunjgit/GameZone#2447]
### Give a brief about the bug ✍️

In light mode the game name and play and have fun is not visible.

### What is the expected behavior? 🤔

Description 
In order to make visible we need to change the color of both texts in light theme.

### Provide step by step information reproduce the bug 📄

Description
on the light mode  the game is not visible.
<img width="380" alt="Screenshot 2023-07-15 182009" src="https://github.com/kunjgit/GameZone/assets/97841424/3aa9af2b-fcfd-4f3f-82d0-4f33727873d9">

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Ashasindhu ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)
