### ISSUE TITLE
[New game]: Tennis Showdown

### ISSUE THREAD

**Issue by abhinav-m22** [kunjgit/GameZone#2449]
### 🎮 Game Request

I have developed a tennis game using HTML, CSS, and JavaScript and I would like to contribute it to the project. The game is designed to provide an interactive and enjoyable gaming experience for tennis enthusiasts.

### Point down the features

1. The game allows two players to control the tennis rackets using keyboard inputs or touch controls. The controls are intuitive, providing an easy and engaging experience.
2. The ball reacts to player hits, bounces off the walls and rackets accurately.
3. The game implements a scoring system similar to traditional tennis rules. It keeps track of each player's score, displays it on the screen, and determines the winner. 
4. The game is designed to be responsive on different devices.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @abhinav-m22 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @abhinav-m22 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
