### ISSUE TITLE
[Enhancement]: Re-Add the Floating Particles In Background

### ISSUE THREAD

**Issue by 5h0ov** [kunjgit/GameZone#2457]
### Is your enhancement request related to a problem? Please describe.➕

Game enhancement

I want to re-add the floating particles in background that got removed by a recent PR.

It was similar to this:
![particlesdemo](https://github.com/kunjgit/GameZone/assets/83227649/a79565b2-9e9a-4de0-bc85-b6b2504c2a7e)

### Describe the solution you'd like

Solution steps

Re-Add particles.css file and integrate it with dark mode

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @5h0ov ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @5h0ov ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
