### ISSUE TITLE
[Enhancement]: 'Snake Game' Design Enhancement

### ISSUE THREAD

**Issue by iamRabia-N** [kunjgit/GameZone#2464]
### Is your enhancement request related to a problem? Please describe.➕

No. It's an enhancement in the existing design of the game.

**Screenshots**

Current Design
![snake-game (2)](https://github.com/kunjgit/GameZone/assets/115794049/8474e0fa-f248-4f60-af6a-52ecab3cb090)

Expected Updated Design
![snake-game (1)](https://github.com/kunjgit/GameZone/assets/115794049/2d421d35-a4e4-4f1f-a7f2-f5e02d000ee7)

### Describe the solution you'd like

Working on the styling properties of the game in order to improve its design.
Improving the colors, margin, padding, etc. of the game.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @iamRabia-N , You can't have another issue before completing the previous one 😀 
 you already have the following 1 open issues 👀 ! :

#2334

**Comment by kunjgit** [comment]
Hey @iamRabia-N ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by kunjgit** [comment]
Hey @iamRabia-N ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)
