### ISSUE TITLE
[Enhancement]: 'Snake Game' Design Enhancement

### ISSUE THREAD

**Issue by iamRabia-N** [kunjgit/GameZone#2465]
### Is your enhancement request related to a problem? Please describe.➕

Is your enhancement request related to a problem? Please describe.➕
No. It's an enhancement in the existing design of the game.

**Screenshots**

Current Design
![snake-game (2)](https://github.com/kunjgit/GameZone/assets/115794049/a94fa7fb-ac53-4a60-8237-102abb10b0ba)

Expected Updated Design
![snake-game (1)](https://github.com/kunjgit/GameZone/assets/115794049/08c43ff7-565f-4a14-8f3b-4081df4e807d)

### Describe the solution you'd like

Working on the styling properties of the game in order to improve its design.
Improving the colors, margin, padding, etc. of the game.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @iamRabia-N ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @iamRabia-N ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
