### ISSUE TITLE
[Enhancement]: Fix The Website

### ISSUE THREAD

**Issue by 5h0ov** [kunjgit/GameZone#2470]
### Is your enhancement request related to a problem? Please describe.➕

Game enhancement

I would like to fix the website that was changed by a recent PR made by someone.

## Preview
![image](https://github.com/kunjgit/GameZone/assets/83227649/d1a56cc4-7623-4245-a445-6094c3339d7d)

### Describe the solution you'd like

Solution steps
- Fix the index.html

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @5h0ov ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @5h0ov ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
