### ISSUE TITLE
[New game]: Snail Game

### ISSUE THREAD

**Issue by sabhisharma-ise** [kunjgit/GameZone#2471]
### 🎮 Game Request

The Snail Game is a simple web-based board game designed for complete beginners to have fun and engage in a friendly competition. The game involves racing colorful snails to reach the finish line first. Each snail is represented by a specific color, and players take turns rolling a virtual die to advance their snails on the track. The first snail to cross the finish line wins the game.

## Features of the Game:

- Objective: The objective of the game is to race your snail to the finish line before your opponents do.

- Board Layout: The game board consists of multiple tracks, each corresponding to a different colored snail. Each track has 12 squares, and the snails start from the first square.

- Snails: There are six snails in total, each represented by a different color - red, blue, green, yellow, purple, and orange.

- Rolling the Die: To move your snail on the track, you click the "Roll Die" button. A virtual die is rolled, and a random color is displayed as the result.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @sabhisharma-ise ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @sabhisharma-ise ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
