### ISSUE TITLE
[New game]: Floor Thirteen

### ISSUE THREAD

**Issue by Durgesh4993** [kunjgit/GameZone#2477]
### 🎮 Game Request

Game logic and basic description
You just killed Mr. Johnson. There are multiple levels.

Screenshort:
![image](https://github.com/kunjgit/GameZone/assets/98798977/629ae1f4-0c7e-480d-8f6f-6f7b8d50b792)

### Point down the features

Demo Vedio:

https://github.com/kunjgit/GameZone/assets/98798977/5b56c91a-9911-442c-b0d4-05f481e1d54c

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Durgesh4993 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @Durgesh4993 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
