### ISSUE TITLE
Update Json file

### ISSUE THREAD

**Issue by Samriddhi15** [kunjgit/GameZone#2478]
### Describe the bug ✍️

Some of the new games are not visible in project website

### Provide step by step information reproduce the bug 📄

So, I will add games in json file so it will be visible in website

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Samriddhi15! 🙂 
 It seems like you are not following proper guidelines !! 👀 
 Read documentation properly !!🙏 
 If you have any queries reach out to us on [Discord🕹️](https://discord.gg/fgwk4XZfxG) .
