### ISSUE TITLE
[Enhancement]: Enhancing Lighthouse Score for Improved Website Performance

### ISSUE THREAD

**Issue by Avinash905** [kunjgit/GameZone#2482]
### Is your enhancement request related to a problem? Please describe.➕

Currently, our website's Lighthouse score falls short of the desired standards, which can affect its accessibility, speed, and overall usability. 

### Describe the solution you'd like

The solution aims to address the existing performance gaps and enhance the website's Lighthouse score to provide a smoother and more engaging experience for our visitors.

The current lighthouse score looks like this:

![Screenshot (622)](https://github.com/kunjgit/GameZone/assets/56786344/6cd7581f-2439-47b1-accb-0d280230892a)

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by Avinash905** [comment]
Please assign me this issue so that I can work on this issue under **GSSOC'23**.

**Comment by kunjgit** [comment]
Hey @Avinash905 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @Avinash905 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
