### ISSUE TITLE
[Bug]: Improving Footer Section in Main Page for Enhancement {Point of View}

### ISSUE THREAD

**Issue by NarendraKoya999** [kunjgit/GameZone#2485]
### Give a brief about the bug ✍️

Description:
- Improving needs for Footer Section in Main Page.

### Screenshot
![gamezone-4](https://github.com/kunjgit/GameZone/assets/84512164/34b443d2-db77-449a-b6a5-0218ec30e20b)

### What is the expected behavior? 🤔

Description:
- I want to expect Footer Full Sentence needs Some Padding. Because of, It's very too close to Left side of the Screen
- Along with Observing in Right side of the Footer Section has So Widened Space. I can expect to these added Social Links little moves to the Right Spacing off Left Scroll Button area .Observe in above Screenshot

### Provide step by step information reproduce the bug 📄

Description:
- Go to the "https://kunjgit.github.io/GameZone/"
- Scroll Down to the "Footer Section"
- Observing Left side Portion of Content and Too Much free Space area placed in Right side .
- Due to Resolve these things, I can Improve Better Enhancement gives to Footer Section

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @NarendraKoya999 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @NarendraKoya999 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
