### ISSUE TITLE
[Enhancement]: Games Title and Description Styling Enhancement

### ISSUE THREAD

**Issue by iamRabia-N** [kunjgit/GameZone#2486]
### Is your enhancement request related to a problem? Please describe.➕

Working on the design of the title and description of each game. 

**Screenshot**

Current Design
![ip (8)](https://github.com/kunjgit/GameZone/assets/115794049/18df84fd-ad3d-4c34-a039-5fe5ddabe1bb)

Expected Updated Design
![ip (7)](https://github.com/kunjgit/GameZone/assets/115794049/d7f7b7a0-b93f-4eb2-b5d5-283b960283db)

### Describe the solution you'd like

Adjusting the styling properties of the title and description area to improve their design.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @iamRabia-N ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by iamRabia-N** [comment]
Kindly assign me this issue.
