### ISSUE TITLE
[New game]: T-Rex Run

### ISSUE THREAD

**Issue by Arka2708** [kunjgit/GameZone#249]
### 🎮 Game Request

The T-Rex Run project is a dinosaur-themed running game that gained popularity for its simplicity and addictive gameplay. Initially developed as an Easter egg for the Google Chrome browser's "No Internet" page, the game features a T-Rex character running endlessly through a desert landscape.

The objective of the game is to guide the T-Rex and help it avoid obstacles, such as cacti and birds, by jumping or ducking at the right time. The gameplay is straightforward and easy to understand, making it accessible to players of all ages and skill levels.

### Point down the features

In the T-Rex Run game, the point system is used to track and reward the player's progress and performance. The primary goal is to accumulate the highest score possible by successfully navigating the T-Rex through the obstacles.

The scoring in T-Rex Run is based on the distance covered. As the T-Rex runs through the desert, the player earns points for every meter or distance unit traveled. The score is constantly increasing as long as the T-Rex continues to move forward.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Arka2708 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @Arka2708 👋!
 
  @kunjgit here, 
 We have this annoucement to make 📢!! 
 During the time of PR don't alter main index file ! 🙂 
 In main Readme file just use * as a game number during the time we are merging we will add number !! 👀 
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG) if you haven't 😇 
  Thank you 💗!

**Comment by Arka2708** [comment]
can you please add the label 'level' to it so that I understand if the change is useful or not...

**Comment by kunjgit** [comment]
Hey @Arka2708 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
