### ISSUE TITLE
[Enhancement]: 'Chrome Dinosaur Game' Styling

### ISSUE THREAD

**Issue by iamRabia-N** [kunjgit/GameZone#2490]
### Is your enhancement request related to a problem? Please describe.➕

No. It's an enhancement in the existing design of the game.

**Screenshots**

Current Design
![ip (10)](https://github.com/kunjgit/GameZone/assets/115794049/e1a15fb1-1804-44d7-be8e-1799b907ac7e)

Expected Updated Design
![ip (9)](https://github.com/kunjgit/GameZone/assets/115794049/3e1a9a28-9a03-4234-aa21-aa566c288ad6)

### Describe the solution you'd like

Adjusting the styling of the game to improve its design.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @iamRabia-N ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @iamRabia-N ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
