### ISSUE TITLE
[Enhancement]: 'Memory Game' Design Enhancement

### ISSUE THREAD

**Issue by iamRabia-N** [kunjgit/GameZone#2492]
### Is your enhancement request related to a problem? Please describe.➕

No. It's an enhancement in the existing design. 

### Describe the solution you'd like

By working on the styling of the game, I can improve its design.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @iamRabia-N ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
