### ISSUE TITLE
[New game]: Digit Dilemma 

### ISSUE THREAD

**Issue by srujana-16** [kunjgit/GameZone#2494]
### 🎮 Game Request

This is a logic-based puzzle game where your objective is to fill a grid with the numbers 1 through 9, ensuring that the calculations formed by the numbers in the grid equal the given target numbers.

Add the numbers 1 through 9 into the grid (only use 1 of each number) so the calculations work out and equal the numbers off the grid.

### Point down the features

- Random Number Generation: A random number within a specified range is generated for each game session, providing a unique challenge every time.

- Interactive Interface: The game provides an interactive interface where you can input your guesses and receive feedback on each guess.

- Visual Feedback: The interface visually highlights whether your guess is higher or lower than the target number, helping you refine your subsequent guesses.

- Winning Celebration: When you guess the correct number, the game celebrates your victory with a winning message and prompts you to play again.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @srujana-16 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)
