### ISSUE TITLE
[New game]: Angry_Birds

### ISSUE THREAD

**Issue by akankshachanana1** [kunjgit/GameZone#2496]
### 🎮 Game Request

Game logic and basic description
In Angry Birds, players control a group of colorful birds with different abilities who are seeking revenge on a group of green pigs that have stolen their eggs. The objective of the game is to launch the birds from a slingshot and strategically destroy various structures and obstacles in order to eliminate the pigs and retrieve the stolen eggs.

### Point down the features

Game points
Player has to remove all the pigs from tha slab
![image](https://github.com/kunjgit/GameZone/assets/127978268/2ec471ec-868b-4662-96e2-469b9bdabe35)

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @akankshachanana1 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
