### ISSUE TITLE
[New game]: Cat Trap Game

### ISSUE THREAD

**Issue by Avdhesh-Varshney** [kunjgit/GameZone#2499]
### 🎮 Game Request

Game logic and basic description

- This game is a single player game
- User will try entrap the cat inside a box
- If cat moves outside the box, user will lose the game

### Point down the features

Game points

- If user is able to entrap the cat inside the box and no move left for the cat, user will be the winner
- otherwise user loses the game

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Avdhesh-Varshney ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
