### ISSUE TITLE
[New game]: planet defense game

### ISSUE THREAD

**Issue by SimranLahrani842** [kunjgit/GameZone#25]
### 🎮 Game Request

Game logic and basic description: There is a planet in centre along with a gun for shoot , if any stones or meteroids come close to planet we need to hit them with a gun.Score will be displayed as  how many we have shot.

### Point down the features

Game points:Gui will be good and responsive and score will be displayed.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
@SimranLahrani842 can you please elaborate the features !!
It is looking interesting but we want to know more about the features 😃

**Comment by SimranLahrani842** [comment]
> @SimranLahrani842 can you please elaborate the features !! It is looking interesting but we want to know more about the features smiley

Sure sir..So the gun can rotate 360° and can hit and stone or meteroid coming close to earth.The stones can come more than one at a time,the level of game increases if more stones appear closer to earth.If the gun can't hit stone then the game is over.The score will be displayed of total hitting stones.

**Comment by kunjgit** [comment]
Hey @SimranLahrani842 ! Thank you for raising an issue 💗 You have been assigned this issue you can start working on the issue 🎮
Thank you for elaborating !! 🚀 
Looking forward to have your game on GameZone

**Comment by kunjgit** [comment]
Hey @SimranLahrani842 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
