### ISSUE TITLE
[Bug]: Images not loading and some missing games not visible on website

### ISSUE THREAD

**Issue by Swapnil-Singh-99** [kunjgit/GameZone#2502]
### Give a brief about the bug ✍️

Some games are not visible on the website and some images are not loading 

### What is the expected behavior? 🤔

Correct Image loads and games present

### Provide step by step information reproduce the bug 📄

Description

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by gurjeetsinghvirdee** [comment]
Go ahead @Swapnil-Singh-99

**Comment by kunjgit** [comment]
Hey @Swapnil-Singh-99 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
