### ISSUE TITLE
[Documentation Bug]: incomplete statement in code_of_conduct.md

### ISSUE THREAD

**Issue by PurviSaini** [kunjgit/GameZone#2505]
### Describe the bug ✍️

There is a statement in code_of_conduct.md where some information is not present, perhaps the statement should be provided with a contact information like a gmail id or something.
I would add the required information there.

### Provide step by step information reproduce the bug 📄

![Screenshot (115)](https://github.com/kunjgit/GameZone/assets/101940722/07666696-9db0-4ea4-a422-0ced176e9fd4)

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @PurviSaini ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @PurviSaini ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
