### ISSUE TITLE
[New game]: Slime attack [GSSOC'23]

### ISSUE THREAD

**Issue by apu52** [kunjgit/GameZone#2509]
### 🎮 Game Request

Hello Sir,
I want to add a project of a game of Simple slime attack.

### Point down the features

Here it's a simple shooting game. Where the slime in spaceship is wandering in the screen very fast & we have to heat it with our gun.
Please assign me this issue under GSSOC'23.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @apu52 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
