### ISSUE TITLE
[New game]: DOODLE JUMP

### ISSUE THREAD

**Issue by MohnishK7** [kunjgit/GameZone#251]
### 🎮 Game Request

Game logic and basic description
a character named "Doodler" who jumps on platforms to climb as high as possible while avoiding obstacles. The game's logic can be broken down into several key components:

Character and Platform Generation:

The game starts by generating the Doodler character at the bottom of the screen and a series of platforms above it.
Platforms can be generated randomly or using a predetermined pattern.
The position and spacing between platforms should allow the player to jump from one platform to another.
Player Input:

The player controls the Doodler's movement by tilting their device or using on-screen buttons.
The player's input determines the horizontal movement of the Doodler.
Jumping Mechanics:

The Doodler jumps automatically when standing on a platform.
The height and distance of the jump can be determined by the length of time the player holds the jump button or tilts their device.
Gravity and Falling:

The Doodler is affected by gravity, causing it to fall if it's not standing on a platform.
The falling speed can be constant or increase gradually as the player climbs higher.

### Point down the features

Game pointsScoring:

The player earns points as they climb higher.
Points can be awarded based on the distance climbed, platforms jumped on, or other achievements.
Power-Ups and Obstacles:

Power-ups can appear on platforms or floating in the air, providing temporary abilities or boosts.
Obstacles such as monsters, UFOs, or moving platforms can hinder the player's progress.
Colliding with obstacles usually results in game over, but power-ups may help the player overcome or destroy them.
Game Over:

The game ends when the Doodler falls off the bottom of the screen.
The player's score is recorded and displayed, allowing them to compare their performance with previous attempts.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @MohnishK7 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @MohnishK7 👋!
 
  @kunjgit here, 
 We have this annoucement to make 📢!! 
 During the time of PR don't alter main index file ! 🙂 
 In main Readme file just use * as a game number during the time we are merging we will add number !! 👀 
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG) if you haven't 😇 
  Thank you 💗!

**Comment by kunjgit** [comment]
Hey @MohnishK7 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
