### ISSUE TITLE
[New game]: Illusion

### ISSUE THREAD

**Issue by dhruv1108git** [kunjgit/GameZone#2512]
### 🎮 Game Request

In this game, a rotating illusion pattern is displayed on the screen, and the player has to guess the direction of rotation. "C" for clockwise and "A" for counterclockwise. 

### Point down the features

Illusion Pattern Display:

The game displays a rotating illusion pattern on the screen.
The rotation direction of the pattern is randomized.

User Input and Scoring:

Users can input their guesses for the rotation direction using the "C" key for clockwise and the "A" key for counterclockwise.
The program checks if the user's guess matches the actual rotation direction and updates the score accordingly.
The score is displayed on the screen.

Game Loop and Timing:

The game runs in a loop, allowing continuous gameplay until the player quits.
The rotation direction changes every 2 seconds.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @dhruv1108git ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @dhruv1108git ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
