### ISSUE TITLE
[New game]: Add Arkanoid Game

### ISSUE THREAD

**Issue by tayyab-ilyas** [kunjgit/GameZone#2514]
### 🎮 Game Request

Game logic and basic description

The player controls a paddle-like craft known as the Vaus, and the objective is to clear a formation of colorful blocks by deflecting a ball towards them without letting the ball leave the bottom edge of the playfield. 

### Point down the features

Game points

- The player controls the Vaus, which is a paddle-like craft that can be moved left or right.
- The ball is initially released at the top of the screen and bounces around the playfield.
- The player can deflect the ball by moving the Vaus.
- When the ball hits a block, the block breaks and the player scores points.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @tayyab-ilyas! 
We are already having a similar game request in #2272 👀 
Make sure you come up with a cool unique idea 😀 
 Waiting for your new game idea 💗.

**Comment by kunjgit** [comment]
Hey @tayyab-ilyas ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @tayyab-ilyas ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by tayyab-ilyas** [comment]
> Hey @tayyab-ilyas! We are already having a similar game request in #2272 👀 Make sure you come up with a cool unique idea 😀 Waiting for your new game idea 💗.

Hey @kunjgit I checked out, it's not same at all!

**Comment by tayyab-ilyas** [comment]
@gurjeetsinghvirdee can you re open this please?
