### ISSUE TITLE
[Bug]: no image for country_Guesser_Game

### ISSUE THREAD

**Issue by khadar1020** [kunjgit/GameZone#2515]
### Give a brief about the bug ✍️

no image is there for country_Guesser_Game
![Screenshot (428)](https://github.com/kunjgit/GameZone/assets/124120102/76239bb5-2323-4d10-931b-115b2dfa488c)

### What is the expected behavior? 🤔

we can add an image of the world.

### Provide step by step information reproduce the bug 📄

by img tag, we can add images and set the path correctly

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by khadar1020** [comment]
please assign me this issue @kunjgit

**Comment by kunjgit** [comment]
Hey @khadar1020 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by khadar1020** [comment]
can you please add gssoc label also

**Comment by khadar1020** [comment]
can you please add gssoc label also @kunjgit

**Comment by khadar1020** [comment]
can you please add @kunjgit

**Comment by khadar1020** [comment]
can you please add gssoc label also @kunjgit

**Comment by khadar1020** [comment]
the 76 and 286 games are same @gurjeetsinghvirdee I will remove one and change numbering in readme also both are country guesser games only

**Comment by gurjeetsinghvirdee** [comment]
> the 76 and 286 games are same @gurjeetsinghvirdee I will remove one and change numbering in readme also both are country guesser games only

go ahead if games are same then you can remove the duplicate one & change the serial numbers according to that

**Comment by kunjgit** [comment]
Hey @khadar1020 👋!
 
 @kunjgit here, 
 Hope you are doing extremely well 😇 
 It's confirmed 🥳, GameZone is taking part in hacktoberfest and ready to have another 💥 
 Ready to have some amazing contributions once again also thank you for you support in GSSoC23 you have took us on top 5 ❤️‍🔥 
 if you still haven't joined us join us on ⁠[Discord](https://discord.gg/fgwk4XZfxG) 
 See you soon 😊

**Comment by kunjgit** [comment]
Hey @khadar1020 👋!
 
 @kunjgit here, 
 Hope you are enjoying this hacktober 😀 
 We are excited to share that we are opening issue from our side where you will be going to add games on our website 🚀 
 Work on this [issue](https://github.com/kunjgit/GameZone/issues/2944) 🔥 
 and help us building GameZone 💗 
 if you still haven't joined us join us on ⁠[Discord](https://discord.gg/fgwk4XZfxG) 
 See you soon 😊

**Comment by kunjgit** [comment]
Hey @khadar1020 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
