### ISSUE TITLE
[New game]: Tower of Blocks

### ISSUE THREAD

**Issue by Yashika-Agrawal** [kunjgit/GameZone#2521]
### 🎮 Game Request

Game logic and basic description:
Tower of Blocks is a casual stacking game where the objective is to build a tower by precisely placing blocks on top of each other. The player's goal is to achieve the highest possible score by aligning the blocks perfectly.
It will look something like this:
![image](https://github.com/kunjgit/GameZone/assets/97408966/46b378f2-f40e-4f3c-9b52-09a212ecd23e)

### Point down the features

Features:

Block Stacking: The game involves stacking blocks on top of each other. Each block is placed directly above the previous block, and the player must ensure a stable tower structure.

Block Sliding: Blocks slide horizontally across the screen from one side to another, making the gameplay dynamic and challenging.

User Input: The player can interact with the game using either the spacebar or the mouse click to place the sliding block on top of the previous block.

Precision Placement: To maximize their score, the player must align the sliding block accurately with the previous block. If the new block partially extends beyond the previous one, the excess portion is cut off, and the remaining portion becomes the foundation for the next block.

Scoring System: The score increases with each successful block placement. Perfectly aligned blocks yield higher scores.

Game Over Condition: If the sliding block is not placed correctly, causing the tower to become unstable and collapse, the game ends. The player can then view their final score and attempt to beat their high score.

Visual Feedback: The game provides visual cues to help players align the blocks, such as highlighting the correct alignment position or indicating when a block is precisely aligned.

Progressive Difficulty: As the game progresses, the sliding blocks may become smaller, making the stacking process more challenging and engaging.

High Score: The game keeps track of the player's highest score achieved, motivating them to beat their own records.

Restart Option: After a game over, the player has the option to restart the game to try again.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Yashika-Agrawal ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by Yashika-Agrawal** [comment]
Assign

**Comment by Yashika-Agrawal** [comment]
> Hey @Yashika-Agrawal ! Thank you for raising an issue 💗 You can self assign the issue by commenting /assign in comment 😀 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone) Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

/assign

**Comment by kunjgit** [comment]
Hey @Yashika-Agrawal ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
