### ISSUE TITLE
[New game]: 3D racing game

### ISSUE THREAD

**Issue by akankshachanana1** [kunjgit/GameZone#2522]
### 🎮 Game Request

Game logic and basic description
3d racing game
 In this game, player take control of car and compete against AI opponents or other players in multiplayer mode.

### Point down the features

Game points
Try to finish as many as laps before the time runs out

https://github.com/kunjgit/GameZone/assets/127978268/f546c6ce-4e7c-43ec-8cca-5a92c9c05c53

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @akankshachanana1 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @akankshachanana1 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
