### ISSUE TITLE
[New game]: Code Breaker

### ISSUE THREAD

**Issue by Yashika-Agrawal** [kunjgit/GameZone#2526]
### 🎮 Game Request

Game logic and basic description:
Code Breaker is a challenging guessing game where the player must crack a randomly generated 4-digit code within 10 attempts. The game provides feedback on each guess to help the player narrow down the correct code.

### Point down the features

Features:
Random Code Generation: The game generates a secret 4-digit code at the start of each game. The code is randomly generated, making each playthrough unique.

Player Input: The player can make guesses by entering a 4-digit numeric code using the game's input system.

Valid Guess Checking: The game validates each guess to ensure it consists of exactly 4 numeric characters. If the guess doesn't meet this requirement, the player is prompted to enter a valid guess.

Feedback System: After each guess, the game provides feedback on the accuracy of the guess based on the secret code. The feedback consists of four symbols:

✔️: Indicates a number is in the correct position.
✳️: Indicates a number is part of the code but not in the right position.
❌: Indicates a number is not part of the code.
🟦: Doesn't consider how many times a number exists in the code.
Winning Condition: The player wins the game if they correctly guess the 4-digit code within 10 attempts.

Losing Condition: If the player fails to guess the correct code within 10 attempts, they lose the game.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Yashika-Agrawal , You can't have another issue before completing the previous one 😀 
 you already have the following 1 open issues 👀 ! :

#2521

**Comment by kunjgit** [comment]
Hey @Yashika-Agrawal ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by Yashika-Agrawal** [comment]
/assign

> Hey @Yashika-Agrawal ! Thank you for raising an issue 💗 You can self assign the issue by commenting /assign in comment 😀 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone) Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

//assign
