### ISSUE TITLE
[New game]: Add Archery Game

### ISSUE THREAD

**Issue by abhinav-m22** [kunjgit/GameZone#2534]
### 🎮 Game Request

I have developed an Archery Challenge game using HTML, CSS, and JavaScript. It's a fun and engaging game where players can test their archery skills by aiming and shooting arrows at targets.

### Point down the features

1. Implemented a realistic arrow shooting mechanism using JavaScript, allowing players to aim and shoot arrows with a smooth transition and trajectory.
2. Utilized CSS Grid to create a scalable and responsive game layout, ensuring user experience across various screen sizes and devices.
3.  Integrated a score system to keep track of players' performance. 

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @abhinav-m22 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @abhinav-m22! 
We are already having a similar game request in #2272 👀 
Make sure you come up with a cool unique idea 😀 
 Waiting for your new game idea 💗.

**Comment by kunjgit** [comment]
Hey @abhinav-m22 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
