### ISSUE TITLE
[New game]: Archery Challenge

### ISSUE THREAD

**Issue by abhinav-m22** [kunjgit/GameZone#2535]
### 🎮 Game Request

In this game, you can use your mouse to aim and then click the "Shoot Arrow" button to shoot arrows at the targets. The closer your arrow hits to the center of the target, the higher your score will be.

### Point down the features

1. You'll feel like a real archer as you aim and shoot with smooth animations.
2. There are multiple levels to keep you challenged.
3. Try to hit the bullseye for high scores!
4. Responsive on different device sizes.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @abhinav-m22 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)
