### ISSUE TITLE
Attention Here

### ISSUE THREAD

**Issue by gurjeetsinghvirdee** [kunjgit/GameZone#2539]
### You know how hard it is to make a 2d pixel games even a experienced Developer can't make this in a week and You guys simply copying & pasting other's game here

I mean why? That is not a open source contribution copying & pasting 
It would be a contribution if you add your own changes on that code like you can change the design, add some more logics on gameplay but nope just copying & pasting  

I have noted some names that doing same thing, Last warning to those guys either you will be disqualified like this guys
<img width="700" alt="image" src="https://github.com/kunjgit/GameZone/assets/73753957/20059d9b-c3b4-4d29-86f2-8163ebc22860">

**Comment by kunjgit** [comment]
Hey @gurjeetsinghvirdee! 🙂 
 It seems like you are not following proper guidelines !! 👀 
 Read documentation properly !!🙏 
 If you have any queries reach out to us on [Discord🕹️](https://discord.gg/fgwk4XZfxG) .

**Comment by kunjgit** [comment]
Hey @gurjeetsinghvirdee ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by kunjgit** [comment]
Hey @gurjeetsinghvirdee ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @gurjeetsinghvirdee ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
