### ISSUE TITLE
[Bug]: Menja game is not working

### ISSUE THREAD

**Issue by Yashika-Agrawal** [kunjgit/GameZone#2543]
### Give a brief about the bug ✍️

Description:
![image](https://github.com/kunjgit/GameZone/assets/97408966/e0dec052-e94e-4502-91fb-fcf7b24ac6db)
The game is not displaying

### What is the expected behavior? 🤔

Description:
I will make the code workable by correcting the code.

### Provide step by step information reproduce the bug 📄

Description:
Search Menga game 
See the bug

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Yashika-Agrawal , You can't have another issue before completing the previous one 😀 
 you already have the following 1 open issues 👀 ! :

#2521

**Comment by kunjgit** [comment]
Hey @Yashika-Agrawal ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by kunjgit** [comment]
Hey @Yashika-Agrawal ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)
