### ISSUE TITLE
[Enhancement]: 'Catch me game' Design Enhancement

### ISSUE THREAD

**Issue by iamRabia-N** [kunjgit/GameZone#2544]
### Is your enhancement request related to a problem? Please describe.➕

No. It's an enhancement in the existing design. By working on the styling properties of this game, I can improve its design.

**Screenshots**

Current Design
![ip (12)](https://github.com/kunjgit/GameZone/assets/115794049/1143207f-9da9-4300-ae91-f4c7ba6addd4)

Expected Updated Design
![ip (2)](https://github.com/kunjgit/GameZone/assets/115794049/19172336-8e71-4059-aa07-0acc462fcd21)

### Describe the solution you'd like

Adding and adjusting styling properties to improve design of this game.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @iamRabia-N ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by iamRabia-N** [comment]
@gurjeetsinghvirdee Kindly check this design and share your feedback on whether further changes are required in updated design or no changes are required in its current design.

**Comment by iamRabia-N** [comment]
> @gurjeetsinghvirdee Kindly check this design and share your feedback on whether further changes are required in updated design or no changes are required in its current design.

@gurjeetsinghvirdee

**Comment by gurjeetsinghvirdee** [comment]
Yeah go ahead @iamRabia-N

**Comment by kunjgit** [comment]
Hey @iamRabia-N ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
