### ISSUE TITLE
 "Overflow Issue: Scrolling Causes Page to Move."

### ISSUE THREAD

**Issue by Tharun-nennavath** [kunjgit/GameZone#2546]
I would like to report an issue where scrolling causes the entire page to move due to an overflow problem. This behavior is unexpected and disrupts the user experience , this won't make user-friendly website.
![Screenshot 2023-07-21 150036](https://github.com/kunjgit/GameZone/assets/124525175/07f25b73-409e-4e93-b0c7-0a75500a33fb)
![Screenshot 2023-07-21 150611](https://github.com/kunjgit/GameZone/assets/124525175/8ed90bf7-e221-437e-9b7e-040793f45d88)

**Comment by kunjgit** [comment]
Hey @Tharun-nennavath , You can't have another issue before completing the previous one 😀 
 you already have the following 1 open issues 👀 ! :

#2303

**Comment by kunjgit** [comment]
Hey @Tharun-nennavath ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by kunjgit** [comment]
Hey @Tharun-nennavath! 🙂 
 It seems like you are not following proper guidelines !! 👀 
 Read documentation properly !!🙏 
 If you have any queries reach out to us on [Discord🕹️](https://discord.gg/fgwk4XZfxG) .

**Comment by kunjgit** [comment]
Hey @Tharun-nennavath ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by Tharun-nennavath** [comment]
assign
