### ISSUE TITLE
[Enhancement]: Memory Game

### ISSUE THREAD

**Issue by akankshachanana1** [kunjgit/GameZone#2547]
### Is your enhancement request related to a problem? Please describe.➕

Game enhancement
The background color and the card color are too distracting for the player.
![Screenshot 2023-07-21 150826](https://github.com/kunjgit/GameZone/assets/127978268/dd8d11fa-feea-4622-9699-f81f173b02f1)

![Screenshot 2023-07-21 150813](https://github.com/kunjgit/GameZone/assets/127978268/f65b576f-8af5-4d5a-b8d6-8ef2e1bca396)

### Describe the solution you'd like

Solution steps
.I want to change it to a different color

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @akankshachanana1 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @akankshachanana1 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
