### ISSUE TITLE
[New game]: Dice game

### ISSUE THREAD

**Issue by Babunshil** [kunjgit/GameZone#255]
### 🎮 Game Request

This is a web-based dice game created using HTML, CSS, and JavaScript. The objective of the game is to score as many points as possible by rolling two dice and accumulating points based on the number rolled. The game is designed to be played by two players, with each player taking turns to roll the dice. The game keeps track of the score, and the player with the highest score at the end of the game is declared the winner.

### Point down the features

![229280340-e09cb722-f7db-4fc9-bb1b-f00017076063](https://github.com/kunjgit/GameZone/assets/106283743/b17ff391-2183-48c3-b29d-886d1c930b52)

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Babunshil ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @Babunshil 👋!
 
  @kunjgit here, 
 We have this annoucement to make 📢!! 
 We have updated our README 🚀 
 Make sure you follow proper guideline to raise your next issues !! 
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG) if you haven't 😇 
  Thank you 💗!

**Comment by kunjgit** [comment]
Hey @Babunshil 👋!
 
  @kunjgit here, 
 We have this annoucement to make 📢!! 
 During the time of PR don't alter main index file ! 🙂 
 In main Readme file just use * as a game number during the time we are merging we will add number !! 👀 
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG) if you haven't 😇 
  Thank you 💗!

**Comment by Babunshil** [comment]
Thank you. I was waiting for the announcement,now I am going to make my PR

**Comment by Lavesh12** [comment]
Hello,
I hope you're doing well. I am interested in contributing to this project as part of GSSoC. It aligns with my skills and interests, and I believe I can make a meaningful contribution to the project Could you please assign this task to me? 
Looking forward to hearing from you.
Thank you,
Lavesh Vishwakarma

**Comment by kunjgit** [comment]
Hey @Babunshil ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
