### ISSUE TITLE
[New game]: Multiplayer Tic-Tac-Toe game

### ISSUE THREAD

**Issue by PUJAmangale1221** [kunjgit/GameZone#2550]
### 🎮 Game Request

Game logic and basic description
The multiplayer tic-tac-toe game is played on a 3x3 grid where two players take turns placing their symbols ("X" and "O") in empty cells. The first player to get three of their symbols in a row (horizontal, vertical, or diagonal) wins. If all cells are filled and no player has won, the game is a draw.

### Point down the features

Game points
1. You can create a room or join a room
2. Join a Room with Unique ID
3. Chat while playing
4. Player making the first move will get an 'X'
5. Each player gets a chance alternatively
6. Smooth and responsive 

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @PUJAmangale1221 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @PUJAmangale1221! 
We are already having a similar game request in #2333 👀 
Make sure you come up with a cool unique idea 😀 
 Waiting for your new game idea 💗.

**Comment by kunjgit** [comment]
Hey @PUJAmangale1221 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
