### ISSUE TITLE
[New game]: The Impossible Game

### ISSUE THREAD

**Issue by uzmaansari23** [kunjgit/GameZone#2552]
### 🎮 Game Request

Game logic and basic description
It is a simple game based on HTML, CSS and JavaScript in which the player has to press space to begin. Press the space key to uplift the box whenever the obstacle come.

### Point down the features

Game points
Any mistake will result in instant death and a respawn at the beginning of the level. With an awesome soundtrack synced to the game you'll quickly become addicted!

SCREENSHOT!
![Uploading Screenshot (82).png…]()

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @uzmaansari23! 
We are already having a similar game request in #2497 👀 
Make sure you come up with a cool unique idea 😀 
 Waiting for your new game idea 💗.

**Comment by kunjgit** [comment]
Hey @uzmaansari23 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @uzmaansari23 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
