### ISSUE TITLE
[New game]: Rock Paper Scissors Lizard Spock

### ISSUE THREAD

**Issue by tayyab-ilyas** [kunjgit/GameZone#2556]
### 🎮 Game Request

"Rock, Paper, Scissors, Lizard, Spock" is an expanded version of the classic hand game "Rock Paper Scissors, popularized by the TV show "The Big Bang Theory." In this game, two players simultaneously choose one of the five options: Rock, Paper, Scissors, Lizard, or Spock.

### Point down the features

- Rock crushes Scissors and crushes Lizard.
- Paper covers Rock and disproves Spock.
- Scissors cut Paper and decapitate Lizard.
- Lizard eats Paper and is poisoned by Spock.
- Spock smashes Scissors and vaporizes Rock.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @tayyab-ilyas ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)
