### ISSUE TITLE
[Enhancement]: Adding Home Icons to More Games And Fixing the link to Home

### ISSUE THREAD

**Issue by 5h0ov** [kunjgit/GameZone#2559]
### Is your enhancement request related to a problem? Please describe.➕

Games Enhancement:

I would like to **add** more home icons to more of the new games and **fix** all the links of the home icons as they dont work(refer to the short clip below).

This is going to be time consuming but i will try to finish as quickly as i can!

Clip of Issue of Home Button:
![homeerror](https://github.com/kunjgit/GameZone/assets/83227649/26d68250-8182-4073-92be-6b1b1f39c64d)

### Describe the solution you'd like

Solution steps

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @5h0ov ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @5h0ov ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
