### ISSUE TITLE
[Enhancement]:Trivia game enhancement 

### ISSUE THREAD

**Issue by akankshachanana1** [kunjgit/GameZone#2561]
### Is your enhancement request related to a problem? Please describe.➕

Game enhancement
The background of game is really distracting I want to work on this issue

https://github.com/kunjgit/GameZone/assets/127978268/59c75d4e-7e18-4dd3-8b8e-3fbfbd75a8f5

### Describe the solution you'd like

Solution steps

Changing background and adding other hover effect  on button

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @akankshachanana1 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @akankshachanana1 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
