### ISSUE TITLE
Grammatical Error in README.md file

### ISSUE THREAD

**Issue by IfeoluwaAroboto** [kunjgit/GameZone#2566]
### Describe the bug ✍️

In the sentence "Raise and issue to add new game or to enhancement for a game (Have a look at few things you have to take care during raising issue ). There are a couple of errors in the sentence.
In the sentence "I will review your code and I will merge your code to the main branch of this repository and you will notified for the same,"

### Provide step by step information reproduce the bug 📄

 "Raise and issue" should be "Raise an issue," 
"enhancement" should be "enhance a game" 
 "you will notified" should be "you will be notified."

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @IfeoluwaAroboto! 🙂 
 It seems like you are not following proper guidelines !! 👀 
 Read documentation properly !!🙏 
 If you have any queries reach out to us on [Discord🕹️](https://discord.gg/fgwk4XZfxG) .

**Comment by kunjgit** [comment]
Hey @IfeoluwaAroboto ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @IfeoluwaAroboto ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by IfeoluwaAroboto** [comment]
Thank you.
