### ISSUE TITLE
[New game]: Keyboard Hero

### ISSUE THREAD

**Issue by Deepanshu0703** [kunjgit/GameZone#2569]
### 🎮 Game Request

Keyboard Hero is a rhythm-based game where players match musical notes by pressing corresponding keys on their keyboards, aiming to achieve a high score. The game's logic involves syncing the notes with the beat of the music, providing an engaging and challenging experience for players of all skill levels. The faster and more accurately the keys are hit, the higher the score, making precision and timing crucial for success.

### Point down the features

In Keyboard Hero, players earn points for successfully hitting the correct keys in sync with the music's rhythm.

The game's scoring system rewards accuracy and timing, encouraging players to improve their skills and achieve higher scores with practice.

Accumulating points unlocks new levels or songs, adding a layer of progression and motivation for players to continue honing their keyboard hero skills.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Deepanshu0703 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @Deepanshu0703 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
