### ISSUE TITLE
[New game]: The Cube

### ISSUE THREAD

**Issue by Deepanshu0703** [kunjgit/GameZone#2570]
### 🎮 Game Request

The Cube is a mind-bending puzzle game where players navigate through a series of interconnected, cubic rooms, each presenting unique challenges. To progress, participants must solve intricate puzzles, manipulate the environment, and uncover hidden clues. With its perplexing and immersive gameplay, The Cube tests players' logic, lateral thinking, and problem-solving abilities in an intense and unpredictable setting.

### Point down the features

"The Cube" is an intense time-based game where players face a series of challenges inside a mysterious cube. Each challenge must be completed within a strict time limit, adding a thrilling sense of urgency to the gameplay. The game tests players' wit, agility, and decision-making skills as they race against the clock to survive and progress through the enigmatic Cube's levels.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Deepanshu0703 , You can't have another issue before completing the previous one 😀 
 you already have the following 1 open issues 👀 ! :

#2569

**Comment by kunjgit** [comment]
Hey @Deepanshu0703 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by kunjgit** [comment]
Hey @Deepanshu0703 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)
