### ISSUE TITLE
[New game]: Falling Ball Game

### ISSUE THREAD

**Issue by khushimarothi** [kunjgit/GameZone#2574]
### 🎮 Game Request

Game logic and basic description

Instruction for Falling Ball Game:

Tilt your device or use arrow keys to control the paddle at the bottom.
Catch the falling balls with the paddle to earn points.
Avoid missing any balls, as each miss will cost you a life. Try to achieve the highest score possible!

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @khushimarothi ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by gurjeetsinghvirdee** [comment]
PR #2577

**Comment by kunjgit** [comment]
Hey @khushimarothi ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
