### ISSUE TITLE
[New game]: The Spaceships War

### ISSUE THREAD

**Issue by Kavya-chitipotu-05** [kunjgit/GameZone#258]
### 🎮 Game Request

Game logic and basic description:

This game has 2 spaceships that have to hit each other by firing bullets. and a border will be present in the middle where each spaceship couldn't cross it.
Two players can simultaneously play this game on the keyboard 

### Point down the features

Game points:

 A spaceship that hits the other one 10 times first wins the game. 

SPACESHIPS can escape from each other bullets and pressing arrow keys by one player and  W, A, S, and D keys by another player
and can fire bullets by pressing the control button

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Kavya-chitipotu-05 👋!
 
  @kunjgit here, 
 We have this annoucement to make 📢!! 
 We have updated our README 🚀 
 Make sure you follow proper guideline to raise your next issues !! 
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG) if you haven't 😇 
  Thank you 💗!

**Comment by kunjgit** [comment]
Hey @Kavya-chitipotu-05 👋!
 
  @kunjgit here, 
 We have this annoucement to make 📢!! 
 During the time of PR don't alter main index file ! 🙂 
 In main Readme file just use * as a game number during the time we are merging we will add number !! 👀 
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG) if you haven't 😇 
  Thank you 💗!

**Comment by kunjgit** [comment]
Hello @Kavya-chitipotu-05, Time's Uppp!⏰ 
 Sorry for closing your issue! 
 But it's more than a week since we haven't received anything from your side 😢 . 
 Come up with new ideas, create a new issue and make sure you finish it within a week! 🔥 
 All the best! 🚀 
 Happy Hacking! 💗

**Comment by kunjgit** [comment]
Hey @Kavya-chitipotu-05 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
