### ISSUE TITLE
[Enhancement]: Enlist all the contributors

### ISSUE THREAD

**Issue by Avdhesh-Varshney** [kunjgit/GameZone#2580]
### Is your enhancement request related to a problem? Please describe.➕

Game enhancement

- Enlist all the contributors on the main website
- Showcase them into a hexagonal grid structure of all the contributors

### Describe the solution you'd like

Solution steps

- Using Javascript, fetching all the data of the contributors
- using css, maintain their styling and giving them a hexagonal grid structure of all the profiles

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Avdhesh-Varshney ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @Avdhesh-Varshney ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
