### ISSUE TITLE
[New game]: Sudoko 

### ISSUE THREAD

**Issue by MohanaSrinivas** [kunjgit/GameZone#2586]
### 🎮 Game Request

This game needs only a single person.
Technologies Used:
           1.Html
            2.Css
            3.Javascript

### Point down the features

[ ]Need to fill numbers from (1 to 9) in the square boxes.
[ ] No rows and no columns numbers is fiiled with same number.
[ ]After filling all the Numbers for required boxes your sudoko is completed.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @MohanaSrinivas , You can't have another issue before completing the previous one 😀 
 you already have the following 1 open issues 👀 ! :

#2583

**Comment by kunjgit** [comment]
Hey @MohanaSrinivas ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by kunjgit** [comment]
Hey @MohanaSrinivas ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by MohanaSrinivas** [comment]
open this issue
