### ISSUE TITLE
[New game]: Survivor 

### ISSUE THREAD

**Issue by AbhishekPSingh07** [kunjgit/GameZone#2592]
### 🎮 Game Request

A playable HTML + CSS + JavaScript remake of a space-based "shoot-'em-up" arcade game for Atari / Commodore 64 from 1982, including a level editor and design tool.

## Controls
Arrow Keys drive the ship. shift or control can be used to fire.Use Spacebar to fire smart bombs which will kill any bad guys chasing you.
## How To Play
The goal : Destroy The bases by shooting out the turrets attached to them. When all Turrets are destroyed the base will explode.
Avoid Crashing into "spaceballs' (green Slime Ball Like Things), And shoot or steer of bad guys

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @AbhishekPSingh07 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @AbhishekPSingh07 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
