### ISSUE TITLE
[New game]: Tower blocks game

### ISSUE THREAD

**Issue by SimranLahrani842** [kunjgit/GameZone#26]
### 🎮 Game Request

Game logic and basic description:We need to form the tower with the help of blocks.Block should be placed upon block with same size else size of block goes on reducing.

### Point down the features

Game points:Score will be displayed as how long our tower block is.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
@SimranLahrani842 Make sure you elaborate about how you will achieve it and also the features 💗 
It is interesting but we would like to know something more about it 😃

**Comment by SimranLahrani842** [comment]
Do basically it is a common and trending gme which all popeole like ,the blocks are colorful and are placed one upon another if the size of the block is less than the size of the block placed the block is cut .The blocks are moving blocks.This is the logic behind the code.The game continue till the size of the block become least and can be placed further.In the way the block tower is made,like the stack of blocks.

**Comment by SimranLahrani842** [comment]
> @SimranLahrani842 Make sure you elaborate about how you will achieve it and also the features heartpulse It is interesting but we would like to know something more about it smiley

So basically it is a common and trending gme which all popeole like ,the blocks are colorful and are placed one upon another if the size of the block is less than the size of the block placed the block is cut .The blocks are moving blocks.This is the logic behind the code.The game continue till the size of the block become least and can be placed further.In the way the block tower is made,like the stack of blocks.

**Comment by kunjgit** [comment]
Hey  @SimranLahrani842 ! Thank you for raising an issue 💗 You have been assigned this issue you can start working on the issue 🎮

**Comment by kunjgit** [comment]
Hello @SimranLahrani842, Time's Uppp!⏰ 
 Sorry for closing your issue! 
 But it's more than a week since we haven't received anything from your side 😢 . 
 Come up with new ideas, create a new issue and make sure you finish it within a week! 🔥 
 All the best! 🚀 
 Happy Hacking! 💗

**Comment by kunjgit** [comment]
Hey @SimranLahrani842 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
