### ISSUE TITLE
[New game]: Elephant Taco Game

### ISSUE THREAD

**Issue by uzmaansari23** [kunjgit/GameZone#2604]
### 🎮 Game Request

Game logic and basic description
This game is built with React, SVG, and GreenSock. It's about a hipster elephant who wants to get tacos but his friends keep trying to change plans .

Once there was an elephant. He was excited to go out with his friends and get tacos, but they kept texting him to change the plans. Help the elephant get all the tacos and avoid flakey text messages to get to delicious glory!
![elephant](https://github.com/kunjgit/GameZone/assets/113499701/c7d00577-d6fe-4015-b2e0-443b56a1ac42)

### Point down the features

Game points
Player has to use up, down, left, right arrow keys to move elephant to get the nuts and avoid the obstacles.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @uzmaansari23 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by uzmaansari23** [comment]
please add the level  @kunjgit .

**Comment by kunjgit** [comment]
Hey @uzmaansari23 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
