### ISSUE TITLE
[Enhancement]: Fixing The Scroll To Top Button not being displayed & Fixing Overlapping Contributor Cards

### ISSUE THREAD

**Issue by 5h0ov** [kunjgit/GameZone#2605]
### Is your enhancement request related to a problem? Please describe.➕

Problem:

The scroll to top button is not appearing anymore in the website due to a recent PR. I would like to fix it.
I would also like to reduce the overlap between each contributor picture to make it look better!

### Describe the solution you'd like

Solution steps
- Try to find the problem in the JS or CSS file

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @5h0ov ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
