### ISSUE TITLE
[Enhancement]: Sudoku Game

### ISSUE THREAD

**Issue by akankshachanana1** [kunjgit/GameZone#2606]
### Is your enhancement request related to a problem? Please describe.➕

Game enhancement
Currently the size of the game board and the buttons is not interactive with the player
![Screenshot 2023-07-26 171906](https://github.com/kunjgit/GameZone/assets/127978268/5e3a6ad4-915b-43a8-90dd-6340d5ecbb5d)

### Describe the solution you'd like

Solution steps
I want to work on this issue and make it user friendly

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @akankshachanana1 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @akankshachanana1 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
