### ISSUE TITLE
[Enhancement]: Animal Match Game

### ISSUE THREAD

**Issue by Avdhesh-Varshney** [kunjgit/GameZone#2612]
### Is your enhancement request related to a problem? Please describe.➕

Game enhancement

- Game is not working as expected

<br>

https://github.com/kunjgit/GameZone/assets/114330097/cc2f5e3c-a908-46df-960a-cffff9b87f8f

### Describe the solution you'd like

Solution steps

- Fixing the issue
- Adding more attractiver user interface

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Avdhesh-Varshney ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @Avdhesh-Varshney ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
