### ISSUE TITLE
[Enhancement]: improving background and style of the Typing_test_game

### ISSUE THREAD

**Issue by Sushilverma002** [kunjgit/GameZone#2616]
### Is your enhancement request related to a problem? Please describe.➕

1.the live background
2. the header part border .
3. the color contrast.

### Describe the solution you'd like

final look like this

https://github.com/kunjgit/GameZone/assets/114687502/33a9884f-9da0-494c-8304-204968629248

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Sushilverma002 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by Sushilverma002** [comment]
@kunjgit have a look sir.

**Comment by kunjgit** [comment]
Hey @Sushilverma002 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
