### ISSUE TITLE
[Bug]: footer logo

### ISSUE THREAD

**Issue by BhartiNagpure** [kunjgit/GameZone#2617]
### Give a brief about the bug ✍️

Description

I would like to add logo in footer.

### What is the expected behavior? 🤔

Description

As project aspects logo in footer is always needed.

### Provide step by step information reproduce the bug 📄

Description

Go to footer component
Add logo 

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @BhartiNagpure , You can't have another issue before completing the previous one 😀 
 you already have the following 1 open issues 👀 ! :

#2453

**Comment by kunjgit** [comment]
Hey @BhartiNagpure ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by kunjgit** [comment]
Hey @BhartiNagpure ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)
