### ISSUE TITLE
[Enhancement]: Improve Footer UI in Main Page

### ISSUE THREAD

**Issue by NarendraKoya999** [kunjgit/GameZone#2618]
### Issue Description:
- Alignment of Footer Text above Social Icons in Footer Section
- I want to modify Text of Footer Section Totally above the Social Links.
### Actual Behavior:
![gamezone-4](https://github.com/kunjgit/GameZone/assets/84512164/3fe31347-85cc-4acb-af20-25b8105609ae)

### Expected Behavior
![gamezone-5](https://github.com/kunjgit/GameZone/assets/84512164/4f56a1ed-0595-4c77-aa98-82bfb428e76c)

**Comment by kunjgit** [comment]
Hey @NarendraKoya999 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @NarendraKoya999 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
