### ISSUE TITLE
[New game]: Typing Speed Test Game

### ISSUE THREAD

**Issue by code-gen21** [kunjgit/GameZone#262]
### 🎮 Game Request

A typing speed game is a computer or online game designed to improve and test a player's typing skills and speed. These games are often interactive and engaging, offering a fun and challenging way to practice typing while aiming to achieve higher speeds and accuracy.

### Point down the features

The main objective of a typing speed game is to complete the given task within a specified time limit or to achieve the highest typing speed possible.
Typing speed games often provide feedback to players, such as displaying their words per minute (WPM) or accuracy percentage. This feedback allows players to track their improvement over time and encourages them to practice and refine their typing skills.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @code-gen21 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @code-gen21 👋!
 
  @kunjgit here, 
 We have this annoucement to make 📢!! 
 During the time of PR don't alter main index file ! 🙂 
 In main Readme file just use * as a game number during the time we are merging we will add number !! 👀 
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG) if you haven't 😇 
  Thank you 💗!
