### ISSUE TITLE
[Bug]: Invalid  "Heading h7 Tag"  used in index.html Code base[]

### ISSUE THREAD

**Issue by NarendraKoya999** [kunjgit/GameZone#2620]
### Give a brief about the bug ✍️

Description:
- **Invalid  `"Heading h7 Tag"  used in index.html Code base`[Observe Screenshots]**
- **According to `W3C.org and MDN Web Docs, <h1> is the Highest Level and <h6> is the Lowest Level Headings`.**

### What is the expected behavior? 🤔

Description:
- **We can expect to rectify this Problem using One of the `<h1> to <h6> Level of Headings with comfortable Designs in Footer Section`**

### Provide step by step information reproduce the bug 📄

Description:
- Go To `"index.html" in Our Code Base`
- Scroll Down to` Footer Section`
- See Error like `<h7> Tag is used. According to MDN Web Docs and W3C.org` . This is not Recommended.
- Instead of using `<h7>, We can utilizing One of the <h1> to <h6> Level of Headings with additionally add whatever comfortable fit design in Footer Section`

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @NarendraKoya999 , You can't have another issue before completing the previous one 😀 
 you already have the following 1 open issues 👀 ! :

#2618

**Comment by kunjgit** [comment]
Hey @NarendraKoya999 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by kunjgit** [comment]
Hey @NarendraKoya999 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)
