### ISSUE TITLE
[New game]: QuickType game 

### ISSUE THREAD

**Issue by srujana-16** [kunjgit/GameZone#2626]
### 🎮 Game Request

QuickType, a thrilling typing game that tests your typing speed and accuracy. Race against the clock to type the given paragraph within 60 seconds, and see how fast and accurately you can type. 

### Point down the features

The game provides real-time feedback on your progress, including Words Per Minute (WPM), Characters Per Minute (CPM), and the number of mistakes you make. Use the backspace key to correct any errors and aim for the highest score!

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @srujana-16 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @srujana-16! 
We are already having a similar game request in #2598 👀 
Make sure you come up with a cool unique idea 😀 
 Waiting for your new game idea 💗.

**Comment by kunjgit** [comment]
Hey @srujana-16 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by srujana-16** [comment]
@kunjgit hey! the game you've mentioned is completely different from the one I have raised to implement. Please check
