### ISSUE TITLE
[Documentation Bug]: Adding a socials section and badges to that section in the readme

### ISSUE THREAD

**Issue by 1Shubham7** [kunjgit/GameZone#2628]
### Describe the bug ✍️

We should have a socials section in the readme. Example -

![image](https://github.com/NageshMandal/Engineering-Notes-Website/assets/116020663/be1693e2-2172-4b6a-9237-810d7082600e)

This would help you improve your project react and your social media profile as well.
Please assign me this issue under GSSoC'23

### Provide step by step information reproduce the bug 📄

just go to readme

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by 1Shubham7** [comment]
Please assign me this issue under GSSoC'23

**Comment by kunjgit** [comment]
Hey @1Shubham7 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @1Shubham7 ! , This issue is already assigned to @nitin-pandita. 💗 
 You can work on other issues 🚀 
 If there is anything wrong you can contact us on [Discord🕹️](https://discord.gg/fgwk4XZfxG)👀

**Comment by 1Shubham7** [comment]
But its my issue. Give it to me!!

**Comment by kunjgit** [comment]
Hey @1Shubham7 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
