### ISSUE TITLE
[New game]: Color switch challenger

### ISSUE THREAD

**Issue by Nikita06211** [kunjgit/GameZone#2631]
### 🎮 Game Request

Game logic and basic description
The objective of the game is to navigate the ball through obstacles that match its color, while avoiding obstacles with different colors. The obstacles are circular in shape and are divided into segments, each with a distinct color.

The ball starts with the color red and can switch colors to green, blue, and yellow by pressing the spacebar. The segments of the obstacles also change colors continuously, creating a dynamic and challenging gameplay experience.

### Point down the features

Game points
The objective of the game is to navigate the ball through obstacles that match its color, while avoiding obstacles with different colors. The obstacles are circular in shape and are divided into segments, each with a distinct color.

The ball starts with the color red and can switch colors to green, blue, and yellow by pressing the spacebar. The segments of the obstacles also change colors continuously, creating a dynamic and challenging gameplay experience.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Nikita06211 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
