### ISSUE TITLE
[New game]: Haunted Mansion Mystery

### ISSUE THREAD

**Issue by abhinav-m22** [kunjgit/GameZone#2633]
### 🎮 Game Request

**Haunted Mansion Mystery** is an interactive text-based adventure game. Players will experience on a thrilling journey to explore the mansion, solve puzzles, and uncover the haunting mysteries hidden within its walls.

### Point down the features

1. The game will feature multiple rooms within the haunted mansion, each with its unique description and choices for players to make. 
2. Players can decide which path to take, leading to different outcomes and challenges.
3. The game will have an intriguing and immersive storyline that unfolds as players progress through the mansion.
4. Players will encounter ghostly figures, hidden passages, ancient books, and other elements that contribute to the captivating narrative.
5. The game is developed with a responsive design.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @abhinav-m22 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @abhinav-m22 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
