### ISSUE TITLE
[New game]: Recycling Game Challenge

### ISSUE THREAD

**Issue by Mahitej28** [kunjgit/GameZone#2635]
### 🎮 Game Request

Designing a game where the player must sort various items into the correct recycling bins within a time limit. 
Hello, I am Mahima Churi, a proud contributor to GSSoC ' 23. If you think this issue is valid then do assign me this issue with a level of PR as well under GSSoC ' 23.

### Point down the features

Feature of Game would be :
1. Different Recycling Challenges
2. Educational Information
3. Visual Effects
4. Undo Options

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Mahitej28 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @Mahitej28! 
We are already having a similar game request in #2631 👀 
Make sure you come up with a cool unique idea 😀 
 Waiting for your new game idea 💗.

**Comment by kunjgit** [comment]
Hey @Mahitej28 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
