### ISSUE TITLE
[New game]: Sky Dodge

### ISSUE THREAD

**Issue by tayyab-ilyas** [kunjgit/GameZone#2637]
### 🎮 Game Request

Game Description:
"Sky Dodge" is an exhilarating arcade-style game where you take control of a nimble flying object soaring through the sky. Your mission is to deftly navigate through the sky while avoiding the rain of falling blocks. Show off your piloting skills as you dodge and weave through the blocks to stay safe and achieve the highest score possible. Be cautious, as the challenge intensifies with each passing moment. How long can you last in the sky without a collision?

Game Logic:

- Player Control: The player controls a flying object using left and right arrow keys or A and D keys to move horizontally across the screen.

- Falling Blocks: Blocks of various shapes and sizes descend from the top of the screen towards the player's flying object at random intervals.

- Dodging Mechanism: The player must navigate the flying object left or right to avoid colliding with the falling blocks. Each successful dodge increases the player's score.

- Game Over: The game continues until the player's flying object collides with a falling block. Upon a collision, the game ends, and the player is presented with their score and whether they have beaten their previous high score.

- Play Again: After a game over, the player has the option to play again. If they choose to play again, the game resets, and a new round starts after a brief delay.

- Difficulty: Player can adjust the difficulty level during game.

### Point down the features

Game points

- Score and High Score: The game keeps track of the player's score, and it also records the highest score achieved as the player's "High Score." The High Score is stored in the browser's local storage to persist across sessions.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @tayyab-ilyas ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @tayyab-ilyas ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
