### ISSUE TITLE
Next Number In The Sequence

### ISSUE THREAD

**Issue by sairam9966** [kunjgit/GameZone#2643]
### 🎮 Game Request

Objective:
The objective of the game is to test your ability to identify the next number in a given number sequence. You will be presented with a series of numbers, and your task is to figure out the pattern or rule behind the sequence and predict the next number in that series.

Gameplay:
1. When you start the game, you will see a "Start Game" button. Click on this button to begin the challenge.

2. Once the game starts, a number sequence will be displayed on the screen. The sequence will consist of a set of numbers in a specific order.

3. Your task is to observe the pattern in the sequence and predict the next number that should logically follow.

4. Enter your predicted number in the input field provided and click on the "Check" button to submit your answer.

5. If your answer is correct, a "Correct!" message will be displayed, and the game will automatically show the next number sequence for you to solve.

6. If your answer is incorrect, a "Wrong answer" message will be displayed, along with the correct answer. Don't worry; learn from your mistake and try again!

7. The game will continue to present new number sequences one after another until you decide to stop playing.

8. If you want to stop the game, click on the "Stop Playing" button. After stopping, you will see a summary of your performance, including the number of correct answers, the number of wrong answers, the total number of sequences played, and the time taken to complete the challenge.

9. You can play the game again by clicking the "Start Game" button, and the statistics will reset for a new round.

### Point down the features

Rules:
1. There are no time limits for answering each sequence, so take your time to analyze the pattern and provide your answer.

2. You can only submit one answer per sequence. If your answer is correct, the next sequence will be shown automatically.

3. The game will keep track of the number of correct answers, wrong answers, the total number of sequences played, and the time taken during the session.

4. Challenge yourself to improve your performance and identify the patterns quickly and accurately.

The "Number Sequence Challenge" is an exciting and brain-teasing game that tests your analytical skills and ability to recognize number patterns. Have fun playing and improving your number sense!

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @sairam9966! 🙂 
 It seems like you are not following proper guidelines !! 👀 
 Read documentation properly !!🙏 
 If you have any queries reach out to us on [Discord🕹️](https://discord.gg/fgwk4XZfxG) .

**Comment by kunjgit** [comment]
Hey @sairam9966 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by kunjgit** [comment]
Hey @sairam9966 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)
