### ISSUE TITLE
[New game]: Memory Card Game

### ISSUE THREAD

**Issue by blindaks** [kunjgit/GameZone#2645]
### 🎮 Game Request

A basic memory game in which the trick is to remember which cards are where.

### Point down the features

A user-friendly game to enhance the user's memory.

Tech Stack Used:
HTML5
CSS3
JavaScript

![image](https://github.com/kunjgit/GameZone/assets/128223364/3e285381-8093-411d-8129-4397b58e324b)

### Select program in which you are contributing

GSSoC23, Other

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @blindaks! 
We are already having a similar game request in #2581 👀 
Make sure you come up with a cool unique idea 😀 
 Waiting for your new game idea 💗.

**Comment by kunjgit** [comment]
Hey @blindaks ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @blindaks ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
