### ISSUE TITLE
[New game]: Tile game

### ISSUE THREAD

**Issue by shivansh745** [kunjgit/GameZone#265]
### 🎮 Game Request

the will contain the following languages.
1. HTML.
2. CSS
3. Javascript

### Point down the features

the game contains the following logic:
1.game contain various tiles with multiple point 
2.it will contain one bomb tile , on clicking it will end the game.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @shivansh745 👋!
 
  @kunjgit here, 
 We have this annoucement to make 📢!! 
 During the time of PR don't alter main index file ! 🙂 
 In main Readme file just use * as a game number during the time we are merging we will add number !! 👀 
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG) if you haven't 😇 
  Thank you 💗!

**Comment by kunjgit** [comment]
Hey @shivansh745 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
