### ISSUE TITLE
[New game]: Add Pig Game

### ISSUE THREAD

**Issue by kanishkasah20** [kunjgit/GameZone#2659]
### 🎮 Game Request

Pig is a simple two player dice game.

Each turn, a player repeatedly rolls a dice. The player may decide to hold the score and change turn or addup with another roll.

### Point down the features

Game points:-

~If the player rolls a 1, their current score gets zeroed and the other player takes turn.
~If the player rolls any other number, it is added to their current score and the player's turn continues.
~If a player chooses to "hold" the current score, their turn total is added to their score and the other player takes turn.
~The first player to score 100 or more points wins.

Demo Screenshot:-
<img width="925" alt="image" src="https://github.com/kunjgit/GameZone/assets/114860158/895ca611-9f8e-4c04-94cd-2945fc61ee98">

please assign me this under gssoc'23 @kunjgit 

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @kanishkasah20! 
We are already having a similar game request in #2272 👀 
Make sure you come up with a cool unique idea 😀 
 Waiting for your new game idea 💗.

**Comment by kunjgit** [comment]
Hey @kanishkasah20 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @kanishkasah20 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by kanishkasah20** [comment]
I checked out, it's not same ! can u reopen it please @kunjgit
