### ISSUE TITLE
[New game]: Tilting Maze!

### ISSUE THREAD

**Issue by jshobhit11** [kunjgit/GameZone#266]
### 🎮 Game Request

 I’m going to make how to simulate ball movement in a maze with JavaScript as we go through parts of a JavaScript game. We quickly go through how the game layout is created, then we see how to tilt the maze and how that affects the ball movements. And finally, we are going to discuss how can we use trigonometry to figure out how the balls should behave once they hit a wall.

### Point down the features

Game points
My game features is moving the ball in the circle at the same time!
and we are trying to move 4 balls through arrow feature!

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @jshobhit11 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @jshobhit11 👋!
 
  @kunjgit here, 
 We have this annoucement to make 📢!! 
 During the time of PR don't alter main index file ! 🙂 
 In main Readme file just use * as a game number during the time we are merging we will add number !! 👀 
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG) if you haven't 😇 
  Thank you 💗!

**Comment by kunjgit** [comment]
Hey @jshobhit11 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
