### ISSUE TITLE
[New game]: Bash a mole game

### ISSUE THREAD

**Issue by kanishkasah20** [kunjgit/GameZone#2660]
### 🎮 Game Request

This is a simple arcade game in which you Whack the Moles.
 Moles keep on coming and you have to kill them with your hammer. 

### Point down the features

Game points:
Whack as many moles as you can, within 60 seconds.

### Select program in which you are contributing
GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @kanishkasah20 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kanishkasah20** [comment]
Thankyou for assigning me under gssoc'23

**Comment by kunjgit** [comment]
Hey @kanishkasah20 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
