### ISSUE TITLE
[New game]: A amazing game to roll and freeze the selcted dice to make all dice same in minimum time and to beat our best score

### ISSUE THREAD

**Issue by abansal15** [kunjgit/GameZone#2683]
### 🎮 Game Request

Game logic and basic description
A amazing game to roll and freeze the selcted dice to make all dice same in minimum time and to beat our best score

### Point down the features

Game points
will have best time, time taken to play the game , sound in the game and total no. of rolls

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by abansal15** [comment]
![image](https://github.com/kunjgit/GameZone/assets/120590200/6dcad672-0639-4b14-a2dc-fe5e6f0c328e)

**Comment by abansal15** [comment]
please assign it to me

**Comment by kunjgit** [comment]
Hey @abansal15 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)
