### ISSUE TITLE
[New game]: Puzzle Game (Avengers)

### ISSUE THREAD

**Issue by SnigdhaP2022** [kunjgit/GameZone#2684]
### 🎮 Game Request

Game logic and basic description

I would like to add puzzle game which works by moving pixels in the picture and need assemble it in right manner

### Point down the features

Game points

We can use mouse to select and move the puzzle cards
<img width="1440" alt="Screenshot 2023-07-31 at 2 07 28 PM" src="https://github.com/kunjgit/GameZone/assets/102572480/68094b59-c970-4095-b458-016be7c05908">

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @SnigdhaP2022 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)
