### ISSUE TITLE
[New game]: rock paper scissor game

### ISSUE THREAD

**Issue by abansal15** [kunjgit/GameZone#2686]
### 🎮 Game Request

Game logic and basic description
: rock paper scissor game

### Point down the features

Game points will play with computer
![image](https://github.com/kunjgit/GameZone/assets/120590200/b43f22c7-f0eb-422f-a642-ae7957c825d5)

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by abansal15** [comment]
please assign it to me

**Comment by kunjgit** [comment]
Hey @abansal15 , You can't have another issue before completing the previous one 😀 
 you already have the following 1 open issues 👀 ! :

#2683

**Comment by kunjgit** [comment]
Hey @abansal15 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by kunjgit** [comment]
Hey @abansal15 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)
