### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by r-sain** [kunjgit/GameZone#2689]
### Give a brief about the bug ✍️

The search-container is bigger than the actual input field which leaves a lot of dead space if the user clicks on it the input doesnt activate, we can improve the ux by allowing to click anywhere on the container and the input box is activated

https://github.com/kunjgit/GameZone/assets/102957043/a6268b6d-e5b6-432c-8ce9-51869d31dab9

### What is the expected behavior? 🤔

The input box should activate and be ready for typing on clicking anywhere on whole search-container as on the UI it is the searchbox.

### Provide step by step information reproduce the bug 📄

1. click on the search icon or on the far left of the search box ,it doesnt activate the input box
2. type in something after you click on the actual input box and click on the far left or right of the container, its not active anymore

These UX issues can be improved.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @r-sain ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @r-sain ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
