### ISSUE TITLE
[New game]: Word Blitz

### ISSUE THREAD

**Issue by Nikita06211** [kunjgit/GameZone#2690]
### 🎮 Game Request

Game logic and basic description
The game randomly selects a set of alphabets and displays them to the player. The player needs to enter words using those alphabets into the input field and click the "Check" button. If the word is present in the list of words for that alphabet set, the player's score is incremented, and the word is added to the list of correct words displayed on the page.

### Point down the features

Game points
The game randomly selects a set of alphabets and displays them to the player. The player needs to enter words using those alphabets into the input field and click the "Check" button. If the word is present in the list of words for that alphabet set, the player's score is incremented, and the word is added to the list of correct words displayed on the page.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Nikita06211 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @Nikita06211 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
