### ISSUE TITLE
[Enhancement]: Display the games in aplhabetical order

### ISSUE THREAD

**Issue by deepshikha2708** [kunjgit/GameZone#2694]
### Is your enhancement request related to a problem? Please describe.➕

Enhancement in the website 

### Describe the solution you'd like

Solution steps

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @deepshikha2708 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by hansupadhyay007** [comment]
Hello @kunjgit I wanted to contribute in this task, could you please assign task to me.
