### ISSUE TITLE
[New game]: Chopsticks

### ISSUE THREAD

**Issue by DyuthiVivek** [kunjgit/GameZone#2697]
### 🎮 Game Request

Game logic and basic description

Each player has one point on each hand and in each turn a player can attack or split. For attack: a player can add their points to another player's hand. For split: a player can redistribute their points among both hands. If the number of points on one hand reaches five or greater than five, the player loses a hand. The player loses the game if both hands are lost.

### Point down the features

Game points

A player can add points from one hand of theirs to their opponent's hand. A player can also re-distribute the points they have. A player cannot skip a turn

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @DyuthiVivek ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @DyuthiVivek ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
