### ISSUE TITLE
[New game]: Action game with music and animation.

### ISSUE THREAD

**Issue by baisnabi02** [kunjgit/GameZone#27]
### 🎮 Game Request

Game logic and basic description: This game will be made by using  pure html, CSS, JavaScript without using external library.

### Point down the features

This game has featured with music and animation also will calculate  the score points of the game.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
@baisnabi02 Please give your game a sweet and simple name and also make sure you elaborate the features and how you will be going  to conquer that !!

**Comment by baisnabi02** [comment]
ok....so I will give action game  is it correct?

**Comment by Lavesh12** [comment]
Hello,
I hope you're doing well. I am interested in contributing to this project as part of GSSoC. It aligns with my skills and interests, and I believe I can make a meaningful contribution to the project Could you please assign this task to me? 
Looking forward to hearing from you.
Thank you,
Lavesh Vishwakarma

**Comment by kunjgit** [comment]
Hello @baisnabi02, Time's Uppp!⏰ 
 Sorry for closing your issue! 
 But it's more than a week since we haven't received anything from your side 😢 . 
 Come up with new ideas, create a new issue and make sure you finish it within a week! 🔥 
 All the best! 🚀 
 Happy Hacking! 💗

**Comment by kunjgit** [comment]
Hey @baisnabi02 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
