### ISSUE TITLE
[New game]: Beautiful UI and Responsive Quizzing Application

### ISSUE THREAD

**Issue by ann29-tdk** [kunjgit/GameZone#270]
### 🎮 Game Request

The Simple Quiz Application is a web-based application built using JavaScript that allows users to take quizzes and test their knowledge on various topics. It provides an interactive and engaging way to assess and improve one's understanding of different subjects.

### Point down the features

1.) User-Friendly Interface: The application offers a clean and intuitive user interface, making it easy for users to navigate through the quiz and select their answers.

2.) Multiple Choice Questions: The quiz consists of multiple-choice questions, where users are presented with a question and a set of answer options. Users can choose the correct answer by clicking on the respective option.

3.) Score Tracking: As users progress through the quiz, the application keeps track of their score in real-time. The score is incremented when the user selects the correct answer and remains unchanged for incorrect answers.

4.) Restart and Retake: Users have the option to restart the quiz or retake it if they wish to improve their score or try different sets of questions.

5.) Responsive Design: The application is designed to be responsive and compatible with different screen sizes, allowing users to access and enjoy the quiz on various devices such as desktops, laptops, tablets, and smartphones.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @ann29-tdk 👋!
 
  @kunjgit here, 
 We have this annoucement to make 📢!! 
 During the time of PR don't alter main index file ! 🙂 
 In main Readme file just use * as a game number during the time we are merging we will add number !! 👀 
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG) if you haven't 😇 
  Thank you 💗!

**Comment by kunjgit** [comment]
Hey @ann29-tdk ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
