### ISSUE TITLE
[Enhancement]: Black Jack new game

### ISSUE THREAD

**Issue by abansal15** [kunjgit/GameZone#2703]
### Is your enhancement request related to a problem? Please describe.➕

Game enhancement

### Describe the solution you'd like

Solution steps i would like to contribute my new game named blackjack

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by abansal15** [comment]
![image](https://github.com/kunjgit/GameZone/assets/120590200/16bbf572-99d7-47ef-95bf-8fba6d363bbb)

**Comment by kunjgit** [comment]
Hey @abansal15 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @abansal15 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
