### ISSUE TITLE
[Enhancement]: Chrome_Dinosaur_Game

### ISSUE THREAD

**Issue by samratghosh291** [kunjgit/GameZone#2706]
### Is your enhancement request related to a problem? Please describe.➕

Modification:
- control the speed of the cactus coming forward.
- specify the color of the border of the canvas.
- add sound effect during collision, socre (1000*n) and jumping.
- control the height of the dino diring jumping.
- make it almost like a real game.

### Describe the solution you'd like

Solution steps:

- control the height and the of the cactus by modifying the js file.
- for modifying the sound effect first, download the sound effects and insert it inside the html file.
  - now make a function to play the sounds and call it accordingly.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @samratghosh291 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @samratghosh291 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
