### ISSUE TITLE
[New game]: Claw Crane

### ISSUE THREAD

**Issue by vbhosale11** [kunjgit/GameZone#2707]
### 🎮 Game Request

"Claw Crane" is a classic arcade game where players control a claw using a joystick to grab prizes inside a glass enclosure. Aim for the desired prize, descend the claw, and try to grab it. Successfully drop the prize into the collection bin for points. The game gets harder with each level.

### Point down the features

Players use a joystick to move the claw horizontally and position it over the desired prize. The game progressively increases in difficulty with each level, making it more challenging to catch prizes. The game progressively increases in difficulty with each level, making it more challenging to catch prizes.  Successfully catching and dropping a prize into the collection bin rewards players with points.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @vbhosale11 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @vbhosale11 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
