### ISSUE TITLE
[Enhancement]: Enhancing Snake water game

### ISSUE THREAD

**Issue by akankshachanana1** [kunjgit/GameZone#2709]
### Is your enhancement request related to a problem? Please describe.➕

Game enhancement
Currently background of snake water game is not that user friendly.I want to work on this issue.

https://github.com/kunjgit/GameZone/assets/127978268/8f71e49d-b40d-4d6c-9bbd-86d80b1a9978

### Describe the solution you'd like

Solution steps
I will change the css of this project to make it more user friendly

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @akankshachanana1 , You can't have another issue before completing the previous one 😀 
 you already have the following 1 open issues 👀 ! :

#2622

**Comment by kunjgit** [comment]
Hey @akankshachanana1 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)
