### ISSUE TITLE
[Documentation Bug]: Many entries in README.md were duplicate and was not according to the latest update

### ISSUE THREAD

**Issue by thevirengarg** [kunjgit/GameZone#2712]
### Describe the bug ✍️

Describe your bug here
Many duplicate entries and the order of the entries was also not in sequence.

### Provide step by step information reproduce the bug 📄

Description

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @thevirengarg ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
