### ISSUE TITLE
[Question]: How do the games get displayed on the html page

### ISSUE THREAD

**Issue by deepshikha2708** [kunjgit/GameZone#2714]
### Describe your question or ask for support.❓

Description
![image](https://github.com/kunjgit/GameZone/assets/80972038/7867067a-4d69-444d-8f09-48d06c2c6e28)
wanted to know how the games are getting imported on the html web page

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @deepshikha2708 , You can't have another issue before completing the previous one 😀 
 you already have the following 1 open issues 👀 ! :

#2694

**Comment by kunjgit** [comment]
Hey @deepshikha2708 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by deepshikha2708** [comment]
@kunjgit @gurjeetsinghvirdee plz help
