### ISSUE TITLE
[New game]: Color Blast Game

### ISSUE THREAD

**Issue by SnigdhaP2022** [kunjgit/GameZone#2715]
### 🎮 Game Request

Game logic and basic description

I would like to introduce new game i.e Color Blast

### Point down the features

Game points

It includes features as Scores and Lives and needs to play accordingly. It has only one player capacity game

# View
<img width="1440" alt="Screenshot 2023-08-02 at 11 50 54 AM" src="https://github.com/kunjgit/GameZone/assets/102572480/7ea647ab-1593-4861-ae5b-ea4808f51eea">

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @SnigdhaP2022 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @SnigdhaP2022 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
