### ISSUE TITLE
[New game]: Snake And Apple

### ISSUE THREAD

**Issue by MohanaSrinivas** [kunjgit/GameZone#2716]
### 🎮 Game Request

# Snake and Apple Game

Snake and Apple is a classic arcade-style game where the player controls a snake that moves around the screen to eat apples and grow longer. The game ends if the snake collides with the screen boundaries or itself.

## How to Play

1. Use the arrow keys (up, down, left, right) to control the snake's movement.
2. The snake will move continuously in the direction indicated by the arrow keys.
3. Your goal is to eat the red apples (represented by red squares) that appear on the screen.
4. Each time the snake eats an apple, it will grow longer.
5. The game ends if the snake collides with the screen boundaries or itself.

## Getting Started

To play the Snake and Apple Game, follow these steps:

1. Clone the repository or download the ZIP file.
2. Open the `index.html` file in your web browser.
3. Use the arrow keys to control the snake's movement.
4. Eat the red apples to grow longer and increase your score.
5. Avoid colliding with the screen boundaries or the snake's body.

![Screenshot 2023-08-02 120055](https://github.com/kunjgit/GameZone/assets/128175768/a6704fe9-76f5-4ecd-9f8f-bb54fac1fcac)

### Point down the features

![image](https://github.com/kunjgit/GameZone/assets/128175768/56bbf725-b45e-4109-828b-1ec1a080dbbc)

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @MohanaSrinivas , You can't have another issue before completing the previous one 😀 
 you already have the following 1 open issues 👀 ! :

#2608

**Comment by kunjgit** [comment]
Hey @MohanaSrinivas ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by kunjgit** [comment]
Hey @MohanaSrinivas ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)
