### ISSUE TITLE
[New game]: Emoji Guessing Game

### ISSUE THREAD

**Issue by MohanaSrinivas** [kunjgit/GameZone#2718]
### 🎮 Game Request

# Emoji Guess Game

![Screenshot 2023-08-02 121314](https://github.com/kunjgit/GameZone/assets/128175768/84dcfcae-0806-491f-9a91-620cc83cd66b)

Emoji Guess is a fun and unexpected game where the computer will randomly select an emoji, and the player needs to guess its name or meaning. The game will provide hints and keep track of the player's score based on the number of correct guesses.

## How to Play

1. The computer will display an emoji to the player.
2. Enter your guess for the name or meaning of the emoji in the input field provided.
3. Click the "Submit" button to check your guess.
4. If your guess is correct, you will receive a congratulatory message, and your score will increase.
5. If your guess is incorrect, the correct answer will be shown, and you can proceed to the next emoji.
6. Keep guessing the emojis correctly to achieve a high score!

## Getting Started

To play the Emoji Guess Game, follow these steps:

1. Clone the repository or download the ZIP file.
2. Open the `index.html` file in your web browser.
3. The game will start automatically with an emoji displayed on the screen.
4. Enter your guess in the input field and click the "Submit" button to check your guess.
5. The game will provide feedback on whether your guess was correct or not.
6. Continue playing by guessing the names or meanings of different emojis.

### Point down the features

# Emoji Guess Game

Emoji Guess is a fun and unexpected game where the computer will randomly select an emoji, and the player needs to guess its name or meaning. The game will provide hints and keep track of the player's score based on the number of correct guesses.

## How to Play

1. The computer will display an emoji to the player.
2. Enter your guess for the name or meaning of the emoji in the input field provided.
3. Click the "Submit" button to check your guess.
4. If your guess is correct, you will receive a congratulatory message, and your score will increase.
5. If your guess is incorrect, the correct answer will be shown, and you can proceed to the next emoji.
6. Keep guessing the emojis correctly to achieve a high score!

## Getting Started

To play the Emoji Guess Game, follow these steps:

1. Clone the repository or download the ZIP file.
2. Open the `index.html` file in your web browser.
3. The game will start automatically with an emoji displayed on the screen.
4. Enter your guess in the input field and click the "Submit" button to check your guess.
5. The game will provide feedback on whether your guess was correct or not.
6. Continue playing by guessing the names or meanings of different emojis.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @MohanaSrinivas , You can't have another issue before completing the previous one 😀 
 you already have the following 1 open issues 👀 ! :

#2608

**Comment by kunjgit** [comment]
Hey @MohanaSrinivas ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by kunjgit** [comment]
Hey @MohanaSrinivas ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by MohanaSrinivas** [comment]
why you are closing my issue please make as open my issue
@kunjgit
