### ISSUE TITLE
[New game]: Rocket Game

### ISSUE THREAD

**Issue by abhi87374** [kunjgit/GameZone#2721]
### 🎮 Game Request

1. The game is a simple avoidance and bonus-clicking challenge.
2. Move the cursor to control the player's position.
3. Avoid collisions with enemy ships to survive.
4. Click on bonuses to increase your score.
5. Enjoy the game and beat your high score!

### Point down the features

The game is based on timing not on points you can play it to the maximum of 50 and there is different points for different collisions.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @abhi87374 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)
