### ISSUE TITLE
[New game]: Coloron

### ISSUE THREAD

**Issue by pxiy-a** [kunjgit/GameZone#2728]
### 🎮 Game Request

Coloron is a interactive game where players control a bouncing ball, matching its color with a moving bar (Red, Yellow, Purple) by tapping to switch colors. The objective is to maintain matching colors and avoid mismatching, earning points for each successful match. The game becomes progressively more challenging, testing reaction times and coordination. It's a simple yet addictive game suitable for all ages.

### Point down the features

Players control a bouncing ball and must tap to switch the color of the bar to match the color of the ball as it bounces back and forth.The bar changes colors between Red, Yellow, and Purple, requiring quick and accurate taps to keep up with the ball's color.As the game progresses, the ball's speed and the frequency of color changes increase, providing a challenging and engaging experience.The game records and displays the player's highest color-matching streak, encouraging replayability and friendly competition among friends.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @pxiy-a! 
We are already having a similar game request in #2715 👀 
Make sure you come up with a cool unique idea 😀 
 Waiting for your new game idea 💗.
