### ISSUE TITLE
[Flappy Bird Game]: 

### ISSUE THREAD

**Issue by Vikash0122** [kunjgit/GameZone#273]
### 🎮 Game Request

Logic:- The player controls a bird that must navigate through a series of pipes without hitting them.
Flappy Bird is a simple and addictive side-scrolling game featuring challenging gameplay, and a minimalist scoring system.

### Point down the features

Features:- Simple gameplay, addictive nature, scoring system, challenging difficulty, etc.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Vikash0122! 🙂 
 It seems like you are not following proper guidelines !! 👀 
 Read documentation properly !!🙏 
 If you have any queries reach out to us on [Discord🕹️](https://discord.gg/fgwk4XZfxG) .

**Comment by kunjgit** [comment]
Hey @Vikash0122 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
