### ISSUE TITLE
[Documentation Bug]: workflow to add labels by analyzing titles of PR/Issues

### ISSUE THREAD

**Issue by Anmol-Baranwal** [kunjgit/GameZone#2732]
### Describe the bug ✍️

Reference: https://github.com/hoho4190/issue-pr-labeler

Suppose there is `fix` or `feat` or `chore` or `Feature` in the title, the workflow would automatically add the corresponding labels.

<hr>

I will separate this workflow into two files to improve code readability and labels will be in the trigger file.

By analyzing the titles of PRs, it will automatically assign appropriate labels based on predefined criteria such as status, goals, and aspects. It will use `regexs`, `events`, `targets`.

I will add detailed instructions in the PR description, so that you can easily review the PR.

I will add the labels, based on the repository and will mention if a new label is used for the purpose like `build`.

### Provide step by step information reproduce the bug 📄

If you want to see an example, I have contributed the same workflow in another repository.

You can take a look at the recent PR here: `https://github.com/Opentek-Org/opentek/pull/569`

> Based on the title
![image](https://github.com/kunjgit/GameZone/assets/74038190/34390302-e029-41e2-b6d7-fa49723e8835)

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Anmol-Baranwal ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @Anmol-Baranwal ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
