### ISSUE TITLE
[New game]: CSS crossword

### ISSUE THREAD

**Issue by KanchandeepK** [kunjgit/GameZone#2734]
### 🎮 Game Request

CSS Crossword is a captivating web-based puzzle game that challenges players to solve crossword puzzles using their CSS knowledge. With a grid of clues and a stylesheet editor, participants must apply CSS properties and selectors to reveal hidden words. The game offers a fun and interactive way for aspiring web developers to sharpen their CSS skills while enjoying the thrill of solving mind-bending puzzles. As players progress, they uncover stunning visual designs, making it an engaging and visually rewarding experience.

### Point down the features

Utilize CSS grid to create a responsive and organized crossword layout, allowing for easy placement and alignment of the crossword cells and clues. Apply custom CSS styles to highlight selected cells, clues, and the crossword as a whole, enhancing the overall visual appeal and user experience .Implement media queries and flexible sizing units like percentages to ensure the crossword adapts smoothly to various screen sizes and devices.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @KanchandeepK ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @KanchandeepK ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
