### ISSUE TITLE
[Enhancement]: Enhancing Snake water game

### ISSUE THREAD

**Issue by akankshachanana1** [kunjgit/GameZone#2736]
### Is your enhancement request related to a problem? Please describe.➕

Game enhancement
Game enhancement
Currently background of snake water game is not that user friendly.I want to work on this issue.

https://github.com/kunjgit/GameZone/assets/127978268/d3fde565-6b5f-491f-8964-7f33c9179dc3

### Describe the solution you'd like

Solution steps
Solution steps
I will change the css of this project to make it more user friendly

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @akankshachanana1 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @akankshachanana1 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
