### ISSUE TITLE
[New game]: Memorization cards

### ISSUE THREAD

**Issue by Vedansh-777** [kunjgit/GameZone#2743]
### 🎮 Game Request

Game Concept:
Memorization Cards is a challenging and engaging card game designed to test and improve players' memory skills. The game is suitable for players of all ages and can be played individually or in small groups.

Objective:
The objective of the game is to match pairs of cards with identical images or patterns on them. The catch is that all cards are initially face-down, requiring players to rely on their memory to remember the placement of cards as they flip them over one by one.

### Point down the features

<img width="1224" alt="Screenshot 2023-08-03 at 8 34 35 PM" src="https://github.com/kunjgit/GameZone/assets/86073818/75c5a3e3-41ba-4011-a08d-6b771274c792">

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Vedansh-777 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @Vedansh-777 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
