### ISSUE TITLE
[New game]: Connect Four multiplayer game

### ISSUE THREAD

**Issue by Swapnil-2503** [kunjgit/GameZone#2745]
### 🎮 Game Request

Game logic and basic description:

Connect Four is a classic two-player board game where the objective is to connect four of your colored pieces in a row, column, or diagonal before your opponent does.

This project is a simple implementation of the Connect Four game using HTML, CSS, and JavaScript.

### Point down the features

Game points:

The game starts with the "red" player. Click on any of the seven columns at the top of the game board to drop a red piece into that column.

The red piece will fall to the lowest available row in the selected column. The "red" player's turn is now over.

The game will automatically switch to the "yellow" player's turn. Click on any of the remaining columns to drop a yellow piece into that column.

The yellow piece will fall to the lowest available row in the selected column. The "yellow" player's turn is now over.

Players take turns dropping their respective colored pieces until one player successfully connects four of their pieces in a row, column, or diagonal.

If a player connects four pieces, an alert will pop up to declare that player as the winner.

If neither player connects four pieces and the board is full, the game will end in a draw.

To play again, simply refresh the web page to reset the game board and start a new game.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Swapnil-2503 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @Swapnil-2503 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
