### ISSUE TITLE
[New game]: Continuously Rotating Elements

### ISSUE THREAD

**Issue by tanujbordikar** [kunjgit/GameZone#2748]
### `GSSOC'23`
The game logic is quite simple, you click on a circle which then rotates 90deg clockwise and if the white pipe get’s connected with surrounding ones, these will rotate the same way.
If you watch these little circles, after clicking on one, you can see that they rotate continuously. These circles have four states; 0, 90, 180 or 270 degrees rotated clockwise. These states are represented by a CSS selector (in this case a attribute selector).

### Point down the features

Game points:

Rotating single element will give you points and reduce points accordingly.
![rotating elements](https://github.com/kunjgit/GameZone/assets/91179998/0e8728dc-deb4-4acb-b7bf-a82c70e8b788)

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @tanujbordikar ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @tanujbordikar ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
