### ISSUE TITLE
sea battle

### ISSUE THREAD

**Issue by ninadkadu10** [kunjgit/GameZone#275]
### 🎮 Game Request

Sea Battle Plato is a strategic naval warfare game that draws inspiration from the classic game of Battleship. It is played on a square grid board, with each player having their own grid on which they position their fleet of ships. The objective of the game is to strategically locate and sink the opponent's ships before they can sink yours.

### Point down the features

Players must use their wits and tactical thinking to outmaneuver their opponents and sink their ships while protecting their own fleet. The element of surprise and the process of elimination are key factors in achieving victory.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @ninadkadu10! 🙂 
 It seems like you are not following proper guidelines !! 👀 
 Read documentation properly !!🙏 
 If you have any queries reach out to us on [Discord🕹️](https://discord.gg/fgwk4XZfxG) .

**Comment by kunjgit** [comment]
Hey @ninadkadu10 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
