### ISSUE TITLE
[New game]: Flappy bubble_sofa game

### ISSUE THREAD

**Issue by kanishkasah20** [kunjgit/GameZone#2757]
### 🎮 Game Request

Game logic and basic description

An animated and fun version of the popular 2048 game. Built with HTML, CSS and Javascript.

How to play
Move the bubbles with your mouse and add up the same numbers. After adding up two bubbles, two more drop and will not return if they fall over the sofa.

You can turn off the music and sound effects from the home page and also choose the quality of game.
### Point down the features

Game points

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @kanishkasah20 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
