### ISSUE TITLE
[New game]: Rocket Showdown

### ISSUE THREAD

**Issue by tanujbordikar** [kunjgit/GameZone#2759]
### 🎮 Game Request

Game logic and basic description:
### `Under GSSOC'23`
This game is about the epic showdown between two rockets in a war amongst the stars and there can be only one winner! Shoot, blast and even bump your way to victory!
You can choose option whether to play against a computer or human player on the starting screen.

### Point down the features

Game points:

- The blue rocket is controlled with AWD and shoot with Z. 
- The red rocket is controlled with the Arrow Keys and shoot with Spacebar.
- Now the rocket has been upgraded with a shield, every shot on target is worth 1% but crashing into asteroids causes more damage and bumping into your opponent causes mutual damage.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @tanujbordikar , You can't have another issue before completing the previous one 😀 
 you already have the following 1 open issues 👀 ! :

#2748

**Comment by kunjgit** [comment]
Hey @tanujbordikar ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)
