### ISSUE TITLE
[New game]: sea battle

### ISSUE THREAD

**Issue by ninadkadu10** [kunjgit/GameZone#276]
### 🎮 Game Request

Sea Battle Plato is a strategic naval warfare game that draws inspiration from the classic game of Battleship. It is played on a square grid board, with each player having their own grid on which they position their fleet of ships. The objective of the game is to strategically locate and sink the opponent's ships before they can sink yours.

### Point down the features

Game Setup: Each player receives a grid board, typically consisting of a 10x10 square grid, although variations with larger grids are possible. Each player's grid is divided into rows and columns, forming a coordinate system.

Fleet Placement: Before the game begins, players secretly position their fleet of ships on their own grid. The fleet typically includes several different types of ships, such as aircraft carriers, battleships, cruisers, destroyers, and submarines. The size and number of ships may vary depending on the specific version of the game being played.

Turn-based Gameplay: The game proceeds in a turn-based fashion, with players taking alternating turns.

Coordinate Selection: On their turn, a player selects a coordinate on the opponent's grid to launch an attack. They specify a row and column combination, such as "B4" or "H10," to target a specific location on the grid.

Hit or Miss: After selecting a coordinate, the attacking player is informed whether their attack resulted in a hit or a miss. If a ship was present at the targeted location, it is considered a hit. Otherwise, it's a miss. Players typically mark the hits and misses on their own grid to keep track of their attacks.

Sinking Ships: When a player successfully hits an opponent's ship, they announce that they have hit a ship and may continue to target adjacent locations to sink the ship. The attacking player continues their turn until they miss or sink a ship. The opponent must truthfully declare if a ship has been sunk.

Communication and Strategy: Throughout the game, players can try to deduce the positions of the opponent's ships based on the hits and misses. They can also use strategy and logic to determine the best locations to attack.

Game End: The game continues until one player successfully sinks all of the opponent's ships, declaring victory.

Sea Battle Plato is a game of skill, deduction, and careful planning. Players must use their wits and tactical thinking to outmaneuver their opponents and sink their ships while protecting their own fleet. The element of surprise and the process of elimination are key factors in achieving victory.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @ninadkadu10 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @ninadkadu10 👋!
 
  @kunjgit here, 
 We have this annoucement to make 📢!! 
 During the time of PR don't alter main index file ! 🙂 
 In main Readme file just use * as a game number during the time we are merging we will add number !! 👀 
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG) if you haven't 😇 
  Thank you 💗!

**Comment by kunjgit** [comment]
Hello @ninadkadu10, Time's Uppp!⏰ 
 Sorry for closing your issue! 
 But it's more than a week since we haven't received anything from your side 😢 . 
 Come up with new ideas, create a new issue and make sure you finish it within a week! 🔥 
 All the best! 🚀 
 Happy Hacking! 💗

**Comment by kunjgit** [comment]
Hey @ninadkadu10 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
