### ISSUE TITLE
[New game]: Reaction – A Response Game

### ISSUE THREAD

**Issue by Deepanshu0703** [kunjgit/GameZone#2770]
### 🎮 Game Request

"Reaction" is a fast-paced response game that challenges players' reflexes and decision-making abilities. With various visual, auditory, and interactive cues, it keeps players engaged and on their toes. The game features progressively challenging levels, fostering healthy competition as players aim for high scores and rankings. "Reaction" offers an adrenaline-pumping experience, appealing to players of all ages and skill levels, seeking an exciting and responsive gaming challenge.

### Point down the features

In "Reaction," players earn points by responding swiftly and accurately to the presented cues. Each successful reaction grants points based on the level of difficulty. Players can achieve bonus points for consecutive correct responses or achieving high scores. Points can be used to unlock new levels or rewards, encouraging players to improve their skills and challenge themselves. The game's point system adds an element of competitiveness, motivating players to strive for higher scores and dominate the leaderboards.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Deepanshu0703 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @Deepanshu0703 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
