### ISSUE TITLE
[Enhancement]: Stick Dark Theme Switch To The Top Left & Add Hover Effect To Contributors

### ISSUE THREAD

**Issue by 5h0ov** [kunjgit/GameZone#2772]
### Is your enhancement request related to a problem? Please describe.➕

Website enhancement:

I would like to stick the dark mode switch to the top left even if the user scrolls the website as well as changing cursor to pointer and i would like to add a glow to each contributor avatar which would appear on hovering over each avatar.

### Describe the solution you'd like

Solution steps

- Edit styles.css
- Might need to edit JavaScript file for contributors

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @5h0ov ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @5h0ov ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
