### ISSUE TITLE
[Bug]: Contributors Are not aligned/Responsivness

### ISSUE THREAD

**Issue by parasss19** [kunjgit/GameZone#2773]
### Give a brief about the bug ✍️

Description
-  Right now the contribution section is not aligned
-  As we changed the screen size it align to left 

## Screenshots
<img width="960" alt="Screenshot 2023-08-05 175829" src="https://github.com/kunjgit/GameZone/assets/101205226/ee5ca1d7-be71-4c36-851d-bc9870e66c03">

### What is the expected behavior? 🤔

- IT should be align properly in different screen sizes

### Provide step by step information reproduce the bug 📄

Description

- It write proper css to align the contributors in different screen size

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @parasss19 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by parasss19** [comment]
Hey @kunjgit Please review ASAP so that i complete it today only

**Comment by kunjgit** [comment]
Hey @parasss19 ! , This issue is already assigned to @shivdevop. 💗 
 You can work on other issues 🚀 
 If there is anything wrong you can contact us on [Discord🕹️](https://discord.gg/fgwk4XZfxG)👀

**Comment by parasss19** [comment]
@kunjgit I raised this issue but i didnt know its self assigned so please assign me because i created this issue

**Comment by shivdevop** [comment]
@kunjgit I have resolved the issue and merged the pr. Kindly close the issue. Thankyou.

**Comment by shivdevop** [comment]
![WhatsApp Image 2023-08-08 at 17 38 48](https://github.com/kunjgit/GameZone/assets/72686438/561cc43d-48fa-46b5-9fd0-b3fa8895ce97)

**Comment by kunjgit** [comment]
Hey @parasss19 👋!
 
 @kunjgit here, 
 Hope you are doing extremely well 😇 
 It's confirmed 🥳, GameZone is taking part in hacktoberfest and ready to have another 💥 
 Ready to have some amazing contributions once again also thank you for you support in GSSoC23 you have took us on top 5 ❤️‍🔥 
 if you still haven't joined us join us on ⁠[Discord](https://discord.gg/fgwk4XZfxG) 
 See you soon 😊

**Comment by kunjgit** [comment]
Hey @parasss19 👋!
 
 @kunjgit here, 
 Hope you are enjoying this hacktober 😀 
 We are excited to share that we are opening issue from our side where you will be going to add games on our website 🚀 
 Work on this [issue](https://github.com/kunjgit/GameZone/issues/2944) 🔥 
 and help us building GameZone 💗 
 if you still haven't joined us join us on ⁠[Discord](https://discord.gg/fgwk4XZfxG) 
 See you soon 😊

**Comment by kunjgit** [comment]
Hello @parasss19, Time's Uppp!⏰ 
 Sorry for closing your issue! 
 But it's more than a week since we haven't received anything from your side 😢 . 
 Come up with new ideas, create a new issue and make sure you finish it within a week! 🔥 
 All the best! 🚀 
 Happy Hacking! 💗

**Comment by kunjgit** [comment]
Hey @parasss19 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
