### ISSUE TITLE
[New game]: PathPlex

### ISSUE THREAD

**Issue by srujana-16** [kunjgit/GameZone#2789]
### 🎮 Game Request

An exhilarating 3D maze game where players take control of a rolling ball, navigating through a complex labyrinth made of bricks and obstacles. The objective is to guide the ball to the exit, strategically maneuvering through the maze's twists and turns to reach freedom. 

### Point down the features

The game features stunning visuals, challenging puzzles, and an immersive experience that will test players' skills, patience, and problem-solving abilities.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @srujana-16 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @srujana-16 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
