### ISSUE TITLE
[New game]: Your favorite photo's jigsaw puzzle

### ISSUE THREAD

**Issue by daydreamer15** [kunjgit/GameZone#279]
### 🎮 Game Request

This game would work like a simple jigsaw puzzle game.

But, the catch is, that it would allow the user to choose their favorite photos from their respective galleries and convert it into a jigsaw puzzle. This would turn out to be a really interesting game.

### Point down the features

Game points

>>The user gets to choose a picture from their gallery and convert it into a puzzle and then solve it.

>>The user gets to select the number of pieces, according to his capability.

>>The feature of cool songs being played in the background will also be enabled.(A continuous loop of pre-recorded songs, written in the code).

>>A cool message displayed on winning the game, and overall a fun experience.

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @daydreamer15 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @daydreamer15 👋!
 
  @kunjgit here, 
 We have this annoucement to make 📢!! 
 During the time of PR don't alter main index file ! 🙂 
 In main Readme file just use * as a game number during the time we are merging we will add number !! 👀 
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG) if you haven't 😇 
  Thank you 💗!

**Comment by kunjgit** [comment]
Hello @daydreamer15, Time's Uppp!⏰ 
 Sorry for closing your issue! 
 But it's more than a week since we haven't received anything from your side 😢 . 
 Come up with new ideas, create a new issue and make sure you finish it within a week! 🔥 
 All the best! 🚀 
 Happy Hacking! 💗

**Comment by kunjgit** [comment]
Hey @daydreamer15 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
