### ISSUE TITLE
[New game]: Guess the Number

### ISSUE THREAD

**Issue by anshulgupta48** [kunjgit/GameZone#28]
### 🎮 Game Request

I will create the game skeleton of Guess the Number Game first and the logic of the Game is that :-
1. When You Start the Game, the Computer will assign you a Random Number between 1 & 20 and You Have to guess that Number in Least Number of Chances.
2. If You Guess that Random Number, You Have Won the Game otherwise Computer will tell you Your Guessed Number is bigger or smaller than the Random Number.
3. Then, You Need to again Guess the Random Number.
4. You Have Total 8 Chances to Guess the Number, If You Failed to Guess that Number. You Have Lost the Game.

This will be done in HTML, CSS, JS.

### Point down the features

1. Your High Score will be stored after every game & you can come again and again to beat it.
2. This will be responsive that it can be played in any display size.
3. There will be Animation on winning also.
4. There will be some Background Audio when you start the game to make the game interesting.
5. There will be some Audio if you have Entered the Wrong Number.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @anshulgupta48  ! Thank you for raising an issue 💗 You have been assigned this issue you can start working on the issue 🎮

**Comment by kunjgit** [comment]
Hey @anshulgupta48 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
