### ISSUE TITLE
[New game]: Flip the coin

### ISSUE THREAD

**Issue by whiteknight16** [kunjgit/GameZone#2802]
### 🎮 Game Request

Made using HTML CSS and JS. Flip the coin helps you in decision making

### Point down the features

-Made using HTML CSS and JS
-Have sound options and animations

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @whiteknight16 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
