### ISSUE TITLE
[New game]: Start Reactor game

### ISSUE THREAD

**Issue by kanishkasah20** [kunjgit/GameZone#2806]
### 🎮 Game Request

Game logic and basic description

Start Reactor is a game made with javscript and jquery Just tap on the keys as shown in the left side of the reactor to win the game

### Point down the features

Game points

-When the player opens the a black screen will appear on the left while nine squares appear on the right.
-The player must memorize the order of the blue squares appearing on the left screen and then replicate it using the keypad on the right. 
-The player will have to memorize the five patterns. 
-The first pattern to replicate will be a single square, and the second will be two squares, and so on until the maximum of five squares
.- Each pattern builds on the previous pattern. For example, the second pattern will always start with the blue square from the first pattern.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @kanishkasah20 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @kanishkasah20 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
