### ISSUE TITLE
[New game]: 2048 GAME

### ISSUE THREAD

**Issue by hansi-2305** [kunjgit/GameZone#281]
### 🎮 Game Request

Game logic and basic description
The game's objective is to slide numbered tiles on a grid to combine them to create a tile with the number 2048.
The tiles can contain only integer values starting from 2, and that are a power of two, like 2, 4, 8, 16, 32, and so on. Ideally, the player should reach the 2048 tile within the smallest number of steps.

### Point down the features

Game points
As you reach the new levels your score will keep on increasing. As soon as you fail to do so, your final score will be displayed on the screen.

It is created using HTML,CSS,JAVASCRIPT.

Please assign me this issue.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @hansi-2305 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @hansi-2305! 
We are already having a similar game request in #196 👀 
Make sure you come up with a cool unique idea 😀 
 Waiting for your new game idea 💗.

**Comment by hansi-2305** [comment]
Please assign me this issue.

**Comment by kunjgit** [comment]
Hey @hansi-2305 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by hansi-2305** [comment]
please give me a chance, may be it come out differently.

**Comment by kunjgit** [comment]
Hey @hansi-2305 ! you can do enhancement if you want once the game is on GameZone 🎮 !!
