### ISSUE TITLE
[New game]: Picture Puzzle Game

### ISSUE THREAD

**Issue by Avdhesh-Varshney** [kunjgit/GameZone#2813]
### 🎮 Game Request

Game logic and basic description

- Showing a picture to you.
- Along side also showing a grid of puzzle through the parts of the picture.
- Solve that picture and join images by matching the complete image.

### Point down the features

Game points

- Timer will be available for you.
- How much time will you take to solve the challenge.
- This is just a time race and enjoy the game.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Avdhesh-Varshney ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
