### ISSUE TITLE
[New game]: CRIMINAL CASE

### ISSUE THREAD

**Issue by hansi-2305** [kunjgit/GameZone#282]
### 🎮 Game Request

Game logic and basic description
Creating a full-fledged "Criminal Case" game with HTML, CSS, and JavaScript would be quite complex, as it involves multiple scenes, characters, dialogues, clues, investigations, and more. However, this is a simplified version of a text-based "Criminal Case" game where the player has to solve a murder mystery by making choices.

### Point down the features

Game points

There will be statement containing multiple choice answers ,leading to next steps, and at the end result is showcased.
If the detective successfully solves the game then he will be awarded.

Please assign me this issue.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @hansi-2305 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by hansi-2305** [comment]
Please assign me this issue.

**Comment by kunjgit** [comment]
Hey @hansi-2305 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
