### ISSUE TITLE
[New game]: Typing Game

### ISSUE THREAD

**Issue by Ishan-77** [kunjgit/GameZone#2820]
### 🎮 Game Request

Game logic and basic description:

The basic idea of the project is that Thre user will be given a type space in which the user will type the sentence displayed.The game will then score the user on the words per minute he/she has written.

### Point down the features

Game points:

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by Ishan-77** [comment]
I have requested merge issue #2820 please merge it.This is my first time contributing in GSSOC

**Comment by gurjeetsinghvirdee** [comment]
#2822

**Comment by kunjgit** [comment]
Hey @Ishan-77 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
