### ISSUE TITLE
[New game]: Crossy Road

### ISSUE THREAD

**Issue by tanujbordikar** [kunjgit/GameZone#2824]
### 🎮 Game Request

**Game logic and basic description**
"Crossy Road" is a endless arcade game that challenges players to guide a character safely across a busy road filled with various obstacles, such as moving vehicles and water bodies, while aiming to achieve the highest possible score.

**SS:**
![crossy-road](https://github.com/kunjgit/GameZone/assets/91179998/031861bf-d432-4b3d-be49-af2277efa106)

**Basic Logic:**
1. Character Movement: The player controls the character's movement using buttons (or keys). Common movements include moving forward, backward, left, and right.
2. Lane-Based Movement: The road is divided into lanes, each containing various obstacles such as vehicles (cars, trucks). The character can only move along these lanes.
3. Obstacle Patterns: Vehicles move horizontally within their respective lanes at varying speeds. 
4. Timed Movements: Obstacles move according to a timed pattern. For example, vehicles move at a certain speed.
5. Obstacle Interaction: If the character collides with a vehicle the game ends. The player's score is displayed, and they can choose to restart the game.

### Point down the features

Game points
1. Objective: The main objective is to navigate the character across the road and other obstacles without getting hit by vehicles or falling into water.
2. Scoring: Players earn points for each successful move they make(Scores one point for each step forward). The farther the character goes, the higher the score.
3. Endless Runner: The game has an "endless runner" format, meaning there is no fixed endpoint. The goal is to survive and score as much as possible before getting hit.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @tanujbordikar ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)
