### ISSUE TITLE
[Feature request]: Making the contributors section dynamic.

### ISSUE THREAD

**Issue by Viveksati5143** [kunjgit/GameZone#2825]
### Describe the bug ✍️

Making the contributors section dynamic in Readme.md

### Provide step by step information reproduce the bug 📄

The svg will look something like this with limit upto 54 contributors & will move from right to left.

![image](https://github.com/kunjgit/GameZone/assets/100852245/b4b652e5-81ab-4bf0-a668-975b1ef34e20)

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Viveksati5143 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @Viveksati5143 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
