### ISSUE TITLE
[New game]: Duck Hunting Game

### ISSUE THREAD

**Issue by Saurabhrajput1234** [kunjgit/GameZone#283]
### 🎮 Game Request

The Duck Hunting Game is a classic popular game that have fun between peoples and this is developed using HTML, CSS, & JavaScript.

The game starts with a single play button which make the game more clear and fun to the player because he/she going to direct step into the game, also have a count section to count the numbers of wins of the player in the correct order.

### Point down the features

Game points
1.Game start with pointsPress the "Play" button to start the game.
2.The game will play as hunting Ducks  and will play a sound. Repeat to earn more points.
3.If there is something issue with the device then it will pop-up "Please refresh the page."
Press the "Play" button again or continue the game.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Saurabhrajput1234 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by Saurabhrajput1234** [comment]
sir ,  I want to work on this game development please assign me this as (GSSoC23).
thanks you .

**Comment by kunjgit** [comment]
Hey @Saurabhrajput1234 👋!
 
  @kunjgit here, 
 We have this annoucement to make 📢!! 
 During the time of PR don't alter main index file ! 🙂 
 In main Readme file just use * as a game number during the time we are merging we will add number !! 👀 
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG) if you haven't 😇 
  Thank you 💗!

**Comment by kunjgit** [comment]
Hello @Saurabhrajput1234, Time's Uppp!⏰ 
 Sorry for closing your issue! 
 But it's more than a week since we haven't received anything from your side 😢 . 
 Come up with new ideas, create a new issue and make sure you finish it within a week! 🔥 
 All the best! 🚀 
 Happy Hacking! 💗

**Comment by kunjgit** [comment]
Hey @Saurabhrajput1234 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
