### ISSUE TITLE
[New game]: Numeral Whiz

### ISSUE THREAD

**Issue by Nikita06211** [kunjgit/GameZone#2834]
### 🎮 Game Request

Game logic and basic description
Numeral Whiz is an exciting and challenging memory game that will put your memory skills to the test. In this fast-paced game, you'll be shown a sequence of random digits for a short period. Your task is to remember the digits and quickly input them in the correct order once they disappear.

### Point down the features

Game points
The game starts with a one-digit sequence, and as you successfully recall the numbers, the complexity increases with each round. For every correct sequence, your score will increase, and the number of digits in the sequence will grow, making the game progressively more challenging.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Nikita06211 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @Nikita06211 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
