### ISSUE TITLE
Adding a link to repo on the main page add where its written to start it on github

### ISSUE THREAD

**Issue by Its-manpreet** [kunjgit/GameZone#2840]
nothing much just adding a link here -
            <p style="font-size: 20px; font-style:cursive;cursor: pointer;color: rgb(215, 213, 85);">Make sure you
              checkout
              my
              socials and also
              ⭐ GameZone on
              github</p>

**Comment by kunjgit** [comment]
Hey @Its-manpreet ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @Its-manpreet! 🙂 
 It seems like you are not following proper guidelines !! 👀 
 Read documentation properly !!🙏 
 If you have any queries reach out to us on [Discord🕹️](https://discord.gg/fgwk4XZfxG) .

**Comment by kunjgit** [comment]
Hey @Its-manpreet ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
