### ISSUE TITLE
[New game]: 2048

### ISSUE THREAD

**Issue by yashyvs** [kunjgit/GameZone#285]
### 🎮 Game Request

"2048" is a puzzle game where the player slides numbered tiles on a grid to combine them and create a tile with the number 2048. It offers a challenging and addictive gameplay experience that would be a great addition to the existing game collection on the website.

Benefits:
- Increased engagement: Adding "2048" to the gaming website will attract more players and increase user engagement.
- Diverse game collection: Including "2048" will diversify the game selection, catering to a broader range of player preferences.
- Competitive aspect: "2048" allows players to compete for high scores.

### Point down the features

Players will have the opportunity to earn points by actively participating in games on the website. Points can be awarded for  achieving high scores

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @yashyvs ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @yashyvs! 
We are already having a similar game request in #196 👀 
Make sure you come up with a cool unique idea 😀 
 Waiting for your new game idea 💗.

**Comment by kunjgit** [comment]
Hey @yashyvs ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
