### ISSUE TITLE
[New game]: 3D SpaceCraft

### ISSUE THREAD

**Issue by killerraj369** [kunjgit/GameZone#2857]
### 🎮 Game Request

Game logic and basic description
1.) This is a cool game made on the concept of Temple Run but it's a Planet Ball and the Environment is our Universe.
2.) Collect coins and complete missions.
3.) Use Left, Right arrows keys to change the lane.
4.) Use Up Key to jump and Down key to make the ball smaller.
5.) Avoid obstacles and asteroids.
6.) Explore the Universe to find New Planets.

### Point down the features

Game points
![2023-08-09](https://github.com/kunjgit/GameZone/assets/87773889/f91984a0-500f-4186-8989-8ff71cdf4d3f)
![2023-08-09 (2)](https://github.com/kunjgit/GameZone/assets/87773889/ef5c4ff3-7c89-4072-9f38-1569a0b23119)

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @killerraj369 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @killerraj369 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
