### ISSUE TITLE
[New game]: Pokemon Generator

### ISSUE THREAD

**Issue by killerraj369** [kunjgit/GameZone#2868]
### 🎮 Game Request

Game logic and basic description
We are all die-hard fans of Pokémon and its world. This game enables you to encounter both the familiar Pokémon you know and the ones you have yet to discover. 
Click the button to meet your new Pokémon companion that's waiting for you !!!

### Point down the features

Game points
![2023-08-10](https://github.com/kunjgit/GameZone/assets/87773889/ff4fc28c-ebeb-4fff-ab58-1496cf9de820)
![2023-08-10 (3)](https://github.com/kunjgit/GameZone/assets/87773889/d9de2d18-9351-4eae-a185-b167c8f41e4e)
![2023-08-10 (2)](https://github.com/kunjgit/GameZone/assets/87773889/855c05f2-04fa-4dbb-9ae6-8413f9efde2c)
![2023-08-10 (1)](https://github.com/kunjgit/GameZone/assets/87773889/9f2d2516-a17b-44d5-b40f-a9f442206271)

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @killerraj369 , You can't have another issue before completing the previous one 😀 
 you already have the following 1 open issues 👀 ! :

#2857

**Comment by kunjgit** [comment]
Hey @killerraj369 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by kunjgit** [comment]
Hey @killerraj369 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)
