### ISSUE TITLE
[Documentation Bug]: Making columns of games

### ISSUE THREAD

**Issue by Viveksati5143** [kunjgit/GameZone#2870]
### Describe the bug ✍️

A readme is the first impression of any project.
So make the readme more readable

### Provide step by step information reproduce the bug 📄

Make columns of all the games instead of long-long unreadable list

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Viveksati5143 , You can't have another issue before completing the previous one 😀 
 you already have the following 1 open issues 👀 ! :

#2826

**Comment by kunjgit** [comment]
Hey @Viveksati5143 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by kunjgit** [comment]
Hey @Viveksati5143 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by Viveksati5143** [comment]
Hey @Viveksati5143 , You can't work on another issue before completing the previous one 😀
Our community encourages everyone to get started with Open-source & make contribution 🚀
You already are assigned on this open issue 👀 ! : https://github.com/1Spirit1/Learn-Linux/issues/48

**Comment by Viveksati5143** [comment]
Hey @Viveksati5143 , You can't work on another issue before completing the previous one 😀
Our community encourages everyone to get started with Open-source & make contribution 🚀
You already are assigned on this open issue 👀 ! : https://github.com/1Spirit1/Learn-Linux/issues/48

**Comment by Viveksati5143** [comment]
Hey @Viveksati5143 , You can't work on another issue before completing the previous one 😀
Our community encourages everyone to get started with Open-source & make contribution 🚀

You already are assigned on this open issue 👀 ! : https://github.com/kunjgit/GameZone/issues/2963

**Comment by Viveksati5143** [comment]
Hi Eddie - I would like to work on this issue..

Hey @Viveksati5143 , You can't work on another issue before completing the previous one 😀
Our community encourages everyone to get started with Open-source & make contribution 🚀

You already are assigned on this open issue 👀 ! : https://github.com/kunjgit/GameZone/issues/2963
