### ISSUE TITLE
[New game]: Add the game, Blocks Tower

### ISSUE THREAD

**Issue by Vaibhav203** [kunjgit/GameZone#2895]
### **Game logic and basic description**
A game in which, player needs to stack automatically moving blocks one over another to make a never ending tower.

### **Game points**
Simply click on right time to stack the block on one another.

### Select program in which you are contributing

Other

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Vaibhav203 , You can't have another issue before completing the previous one 😀 
 you already have the following 1 open issues 👀 ! :

#2894

**Comment by kunjgit** [comment]
Hey @Vaibhav203 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by kunjgit** [comment]
Hey @Vaibhav203 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)
