### ISSUE TITLE
[New game]: Word Scramble Game

### ISSUE THREAD

**Issue by dishamodi0910** [kunjgit/GameZone#29]
### 🎮 Game Request

Game logic and basic description : 
The game will have a set of scrambled alphabets, and within the given timer value, the user has to guess the correct word using the given alphabets and the score will be assigned for the same.  

Tech Stacks that will be used: HTML, CSS, JavaScript

### Point down the features

Game points : 
1. It would responsive in nature so it can be played on any display size.
2. The buttons for clearing and refreshing the word would be given so that the user can manage to play in case he/she by mistake enters the wrong word.
3. There will be background audio to make the game even more interesting.
4. User will be provided with chances to guess the word, the timer will be reset and the score would be given as per the guess of the word after every try. 

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by dishamodi0910** [comment]
Sir, I hope that you would assign me this issue. I will try my best!!

**Comment by kunjgit** [comment]
Hey @dishamodi0910  ! Thank you for raising an issue 💗 You have been assigned this issue you can start working on the issue 🎮
Sounds interesting 😃 💗 !!

**Comment by kunjgit** [comment]
Hey @dishamodi0910 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
