### ISSUE TITLE
[New game]: Dice Roll Game

### ISSUE THREAD

**Issue by Teddy1404** [kunjgit/GameZone#290]
### 🎮 Game Request

Game logic and basic description
This game has a simple user interface with a heading, a paragraph explaining the game, a "Roll Dice" button, and a div to display the dice result. When the user clicks the "Roll Dice" button, the rollDice function is called. Inside this function, a random number between 1 and 6 is generated using Math.random() and Math.floor(). The dice result is then displayed in the diceResult div.

### Point down the features

Game points
Two Player can play against each other .

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Teddy1404 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @Teddy1404! 
We are already having a similar game request in #255 👀 
Make sure you come up with a cool unique idea 😀 
 Waiting for your new game idea 💗.

**Comment by kunjgit** [comment]
Hey @Teddy1404 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
