### ISSUE TITLE
[New game]: Wild Tic Tac Toe

### ISSUE THREAD

**Issue by Rohan0305** [kunjgit/GameZone#2909]
### 🎮 Game Request

Tic Tac Toe variation with a 5 by 5 grid, and an option to use the X or O at each turn. Player to first reach 3 in a row either vertically, horizontally, or diagonally wins. 

### Point down the features

A "Select Option" button so players can choose either X or O at each turn. A "Reset" button to start the game over. 

### Select program in which you are contributing

Other

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Rohan0305 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by psykat1116** [comment]
Can you assign me this under hacktoberfest

**Comment by ShivankAw07** [comment]
Hey ,I am interested in this assignment of tic tac toe game. Could you please assign me this task..

**Comment by Rohan0305** [comment]
/assign

I already finished this contribution via vscode. Looking to push changes.

**Comment by kunjgit** [comment]
Hey @Rohan0305 👋!
 
 @kunjgit here, 
 Hope you are enjoying this hacktober 😀 
 We are excited to share that we are opening issue from our side where you will be going to add games on our website 🚀 
 Work on this [issue](https://github.com/kunjgit/GameZone/issues/2944) 🔥 
 and help us building GameZone 💗 
 if you still haven't joined us join us on ⁠[Discord](https://discord.gg/fgwk4XZfxG) 
 See you soon 😊

**Comment by kunjgit** [comment]
Hello @Rohan0305, Time's up!⏰ 
 Sorry for closing your issue! 
 But it's more than a week since we haven't received anything from your side 😢 . 
 Come up with new ideas, create a new issue and make sure you finish it within a week! 🔥 
 All the best! 🚀 
 Happy Hacking! 💗

**Comment by kunjgit** [comment]
Hey @Rohan0305 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
