### ISSUE TITLE
[Documentation Bug]: I want to add CODE_OF_CONDUCT.md

### ISSUE THREAD

**Issue by sb-decoder** [kunjgit/GameZone#2910]
### Describe the bug ✍️

Your repo has no CODE_OF_CONDUCT.md, I want to add one, and if you want I can also add a contributors section in your README.md, which is automatically updating when someone contributing in your project

### Provide step by step information reproduce the bug 📄

I will add a markdown code to add contributor section and also add CODE_OF_CONDUCT.md

### Select program in which you are contributing

hacktoberfest

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @sb-decoder ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by sb-decoder** [comment]
ok!

**Comment by sb-decoder** [comment]
@kunjgit assign me this

**Comment by sb-decoder** [comment]
@kunjgit still not get assigned

**Comment by kunjgit** [comment]
Hey @sb-decoder 👋!
 
 @kunjgit here, 
 Hope you are enjoying this hacktober 😀 
 We are excited to share that we are opening issue from our side where you will be going to add games on our website 🚀 
 Work on this [issue](https://github.com/kunjgit/GameZone/issues/2944) 🔥 
 and help us building GameZone 💗 
 if you still haven't joined us join us on ⁠[Discord](https://discord.gg/fgwk4XZfxG) 
 See you soon 😊

**Comment by abhisar-yadav** [comment]
please assign me this issue

**Comment by kunjgit** [comment]
Hello @sb-decoder, Time's up!⏰ 
 Sorry for closing your issue! 
 But it's more than a week since we haven't received anything from your side 😢 . 
 Come up with new ideas, create a new issue and make sure you finish it within a week! 🔥 
 All the best! 🚀 
 Happy Hacking! 💗

**Comment by kunjgit** [comment]
Hey @sb-decoder ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
