### ISSUE TITLE
[Question]: Need help pushing changed. Getting error 403. 

### ISSUE THREAD

**Issue by Rohan0305** [kunjgit/GameZone#2914]
### Describe your question or ask for support.❓

rohanvallapalli@rohans-air GameZone % cd /Users/rohanvallapalli/Desktop/GameZone
rohanvallapalli@rohans-air GameZone % git checkout wild-tic-tac-toe-game
Already on 'wild-tic-tac-toe-game'
rohanvallapalli@rohans-air GameZone % git push origin wild-tic-tac-toe-game
remote: Permission to kunjgit/GameZone.git denied to Rohan0305.
fatal: unable to access 'https://github.com/kunjgit/GameZone.git/': The requested URL returned error: 403

this is what it looks like for me.

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Rohan0305 , You can't have another issue before completing the previous one 😀 
 you already have the following 1 open issues 👀 ! :

#2909

**Comment by kunjgit** [comment]
Hey @Rohan0305 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by kunjgit** [comment]
Hey @Rohan0305 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)
