### ISSUE TITLE
[Enhancement]: Making Things Easier to Read in Light Mode

### ISSUE THREAD

**Issue by 5h0ov** [kunjgit/GameZone#2917]
### Do you want to have the enhancement of existing game ? 😀 Describe yourself..

Website enhancement:

- I would like to change the selected areas in the website given below to make it easier to read the text i light mode. 
- I would also like to fix the game preview images getting a different contrast of colours when switched the light mode.

![image](https://github.com/kunjgit/GameZone/assets/83227649/34b15e27-9ff5-45ad-8318-2e1d2c967bae)

### Describe the solution you'd like

Solution steps

Edit the HTML and CSS and JS Files.

### Select program in which you are contributing

hacktoberfest

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @5h0ov ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @5h0ov 👋!
 
 @kunjgit here, 
 Hope you are enjoying this hacktober 😀 
 We are excited to share that we are opening issue from our side where you will be going to add games on our website 🚀 
 Work on this [issue](https://github.com/kunjgit/GameZone/issues/2944) 🔥 
 and help us building GameZone 💗 
 if you still haven't joined us join us on ⁠[Discord](https://discord.gg/fgwk4XZfxG) 
 See you soon 😊

**Comment by 5h0ov** [comment]
Sir, I will try to solve the UI Issue later. For now i am closing this PR. Thanks !

**Comment by kunjgit** [comment]
Hey @5h0ov ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
