### ISSUE TITLE
[New game]:  Puzzel Winner

### ISSUE THREAD

**Issue by Durgesh4993** [kunjgit/GameZone#2919]
### 🎮 Game Request

Game logic and basic description

In this game you can upload you image and play puzzle 

Screenshot:

![image](https://github.com/kunjgit/GameZone/assets/98798977/5012ff8b-b3dd-476e-a0db-71468106b35b)

### Point down the features

Demo vedio

https://github.com/kunjgit/GameZone/assets/98798977/2bc67ea6-9b93-4135-bed5-8297b417d4ff

### Select program in which you are contributing

hacktoberfest

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Durgesh4993 , You can't have another issue before completing the previous one 😀 
 you already have the following 1 open issues 👀 ! :

#2589

**Comment by kunjgit** [comment]
Hey @Durgesh4993 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by kunjgit** [comment]
Hey @Durgesh4993 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)
