### ISSUE TITLE
[Enhancement]: WANT TO CHANGE UI/UX AND QUESTING OF HANG MAN 

### ISSUE THREAD

**Issue by Sushilverma002** [kunjgit/GameZone#2927]
### Do you want to have the enhancement of existing game ? 😀 Describe yourself..

the questions are limited and they way of question asking is not to much effective the user can't directly understand want goona ask by the game.

### Describe the solution you'd like

![image](https://github.com/kunjgit/GameZone/assets/114687502/f4148155-e2e8-422d-b6e9-e08d1447bfb4)

### Select program in which you are contributing

hacktoberfest

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Sushilverma002 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @Sushilverma002 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by kunjgit** [comment]
Hey @Sushilverma002 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
