### ISSUE TITLE
[Enhancement]: UI/UX improvement in alien_shooters

### ISSUE THREAD

**Issue by Moracus** [kunjgit/GameZone#2930]
### Do you want to have the enhancement of existing game ? 😀 Describe yourself..

Game enhancement: 
1.There's no start or end screen on the game.
2.Player can only control the space ship using arrow keys.

### Describe the solution you'd like

Solution steps:
1. I'll make a proper startscreen, with ui elements. so the game doesn't automatically start whenver the Player runs it.
2. Proper endscreen which displays the score and give options to retry and quit
3. add the functionality to control the spaceship using w,a,s,d keys as well as arrow keys.

### Select program in which you are contributing

hacktoberfest

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Moracus ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @Moracus ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
