### ISSUE TITLE
[Bug]: UI enhancement of the project 

### ISSUE THREAD

**Issue by trishit78** [kunjgit/GameZone#2935]
### Description
The bug is that when the website is on light mode, 'play and have fun  is written in white, so it is not visible clearly
if I change the color , it will be more visible

<img width="960" alt="image" src="https://github.com/kunjgit/GameZone/assets/90523629/f893d0f4-6b18-4f04-85de-bb5e1d5c1dbc">

### Description

Because of the bug, the visibility is getting low
If someone looks there, that something is written, it is hard to read
else it will show as a blank space 

### Provide step by step information reproduce the bug 📄

###Description
I think just changing the paragraph tag color would help and giving it a bit of styling would enhance the visibility

### Select program in which you are contributing

hacktoberfest, Other

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @trishit78 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @trishit78 👋!
 
 @kunjgit here, 
 Hope you are enjoying this hacktober 😀 
 We are excited to share that we are opening issue from our side where you will be going to add games on our website 🚀 
 Work on this [issue](https://github.com/kunjgit/GameZone/issues/2944) 🔥 
 and help us building GameZone 💗 
 if you still haven't joined us join us on ⁠[Discord](https://discord.gg/fgwk4XZfxG) 
 See you soon 😊

**Comment by rahul0x00** [comment]
@kunjgit Hi, it seems trishit is not working on this issue,could you assign it me?

Thanks

**Comment by kunjgit** [comment]
Hello @trishit78, Time's up!⏰ 
 Sorry for closing your issue! 
 But it's more than a week since we haven't received anything from your side 😢 . 
 Come up with new ideas, create a new issue and make sure you finish it within a week! 🔥 
 All the best! 🚀 
 Happy Hacking! 💗

**Comment by kunjgit** [comment]
Hey @trishit78 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
