### ISSUE TITLE
[New game]: Playable Piano Virtual

### ISSUE THREAD

**Issue by SnigdhaP2022** [kunjgit/GameZone#294]
### 🎮 Game Request

Game logic and basic description
Recursive Arts Virtual Piano simulator is the ultimate online piano app that everyone can play. Enjoy the beautiful sound of a world-class Grand Piano. On desktop/laptop computers, you can play notes using your keyboard or mouse. 

### Point down the features

Game points
Tech Stack includes :
HTML,CSS,Java Script
Using piano tunes, we can build virtual piano for users. It helps to create their own tune and get lost in the music for some time.It brings peace out of it.
<img width="1437" alt="Screenshot 2023-05-23 at 12 48 11 PM" src="https://github.com/kunjgit/GameZone/assets/102572480/ce6ec3d3-4c16-4b8a-b186-039440a3c8f0">

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @SnigdhaP2022 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @SnigdhaP2022 👋!
 
  @kunjgit here, 
 We have this annoucement to make 📢!! 
 During the time of PR don't alter main index file ! 🙂 
 In main Readme file just use * as a game number during the time we are merging we will add number !! 👀 
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG) if you haven't 😇 
  Thank you 💗!

**Comment by kunjgit** [comment]
Hey @SnigdhaP2022 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
