### ISSUE TITLE
[New game]: Pong

### ISSUE THREAD

**Issue by rahul0x00** [kunjgit/GameZone#2955]
#### A simple Pong game with two paddles and a bouncing ball.

This code sets up a basic Pong game where two paddles are controlled using the "w" and "s" keys for the left paddle and the "Up" and "Down" arrow keys for the right paddle. The ball bounces between the paddles, and when it goes out of bounds, it resets to the center.

### Point down the features

    Objective: The objective of Pong is to prevent the ball from passing your paddle while trying to make the ball pass your opponent's paddle.

    Two Players: Pong is a two-player game where each player controls a paddle.

    Paddle Control: Players control their paddles using a keyboard or controller. The most common controls are up and down arrow keys or similar keys.

    Bouncing Ball: The game features a bouncing ball that moves back and forth between the two paddles.

    Continuous Play: The game continues indefinitely until one player fails to return the ball.

    No Scores: Traditionally, Pong doesn't keep track of scores or points as a fundamental game element. The focus is on ball control and avoiding misses.

    Ball Speed: In many versions of Pong, the ball's speed gradually increases as the game progresses, making it more challenging.

    Game Over: The game typically ends when a player fails to return the ball, allowing it to pass their paddle. The opposing player is declared the winner of that round.

    Restart: After a point or round is scored, the game can be reset, and play resumes with the player who didn't score serving the ball.

    Optional Features: While traditional Pong is minimalistic, you can add optional features like scores, multiple rounds, and visual effects to enhance gameplay.

    Nostalgia: Pong is a classic arcade game that holds historical significance as one of the earliest video games, contributing to the gaming industry's development.

### Select program in which you are contributing

hacktoberfest

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @rahul0x00 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hello @rahul0x00, Time's up!⏰ 
 Sorry for closing your issue! 
 But it's more than a week since we haven't received anything from your side 😢 . 
 Come up with new ideas, create a new issue and make sure you finish it within a week! 🔥 
 All the best! 🚀 
 Happy Hacking! 💗

**Comment by kunjgit** [comment]
Hey @rahul0x00 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
