### ISSUE TITLE
[New game]: Gun_From_Sound

### ISSUE THREAD

**Issue by psykatsamanta** [kunjgit/GameZone#2961]
### 🎮 Game Request

There will be a sound of gun firing. You have to guess the gun name from that. 

### Point down the features

For Every time there will be five different sounds. From that you have to identify the gun name.
You will have 3 chances for each guess. 
The more you take chance the less will be your score.

### Select program in which you are contributing

hacktoberfest

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hello @psykatsamanta, Time's up!⏰ 
 Sorry for closing your issue! 
 But it's more than a week since we haven't received anything from your side 😢 . 
 Come up with new ideas, create a new issue and make sure you finish it within a week! 🔥 
 All the best! 🚀 
 Happy Hacking! 💗

**Comment by kunjgit** [comment]
Hey @psykatsamanta ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
