### ISSUE TITLE
[Enhancement]: UI/UX improvement in Platform_Game

### ISSUE THREAD

**Issue by Moracus** [kunjgit/GameZone#2963]
### Do you want to have the enhancement of existing game ? 😀 Describe yourself..

1. current version of the game barely have any UI expect the game play itself.
2. There's no start or end screen in the game.
3. Only arrow keys can be used for controls. Some players prefer using A,W,S,D keys as well.

### Describe the solution you'd like

# Solution steps
1.Add a startScreen  with instructions to play.
2. Add an endscreen with  total time taken to complete the game.
3. Add, A,W,S,D keys functionality

### Select program in which you are contributing

hacktoberfest

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Moracus ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hello @Moracus, Time's up!⏰ 
 Sorry for closing your issue! 
 But it's more than a week since we haven't received anything from your side 😢 . 
 Come up with new ideas, create a new issue and make sure you finish it within a week! 🔥 
 All the best! 🚀 
 Happy Hacking! 💗

**Comment by kunjgit** [comment]
Hey @Moracus ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
