### ISSUE TITLE
[New game]:  add new game

### ISSUE THREAD

**Issue by Swadeshit27** [kunjgit/GameZone#2964]
### 🎮 Game Request

I want to make a  dice game where two player throw a dice if plyer 1 get the higher number than player 2 then he win the match.

### Point down the features

I want to make a  dice game where two player throw a dice if plyer 1 get the higher number than player 2 then he win the match.

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by Swadeshit27** [comment]
assign me this task

**Comment by kunjgit** [comment]
Hey @Swadeshit27! 
We are already having a similar game request in #2952 👀 
Make sure you come up with a cool unique idea 😀 
 Waiting for your new game idea 💗.

**Comment by kunjgit** [comment]
Hey @Swadeshit27 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)
