### ISSUE TITLE
[Game Enhancement]: Making Brick Breaker Playable on Mobile Screens

### ISSUE THREAD

**Issue by 5h0ov** [kunjgit/GameZone#2969]
### Game enhancement

I would like to fix the issue where the brick breaker game becomes unplayable and broken in phone:

![brickresponissue1](https://github.com/kunjgit/GameZone/assets/83227649/e80e59ec-ea41-4fee-a289-361028632e11)

![brickresponissue2](https://github.com/kunjgit/GameZone/assets/83227649/9c293a80-3add-4ab6-8dbf-d1c963be0d4b)

### Describe the solution you'd like

Solution steps

- Edit the Javascript and CSS to add Responsiveness and add a Touch Event Listener to Move the Paddle with touch instead of only mouse.

### Select program in which you are contributing

hacktoberfest

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @5h0ov ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hello @5h0ov, Time's up!⏰ 
 Sorry for closing your issue! 
 But it's more than a week since we haven't received anything from your side 😢 . 
 Come up with new ideas, create a new issue and make sure you finish it within a week! 🔥 
 All the best! 🚀 
 Happy Hacking! 💗

**Comment by kunjgit** [comment]
Hey @5h0ov ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
