### ISSUE TITLE
[New game]: Snake and Ladders

### ISSUE THREAD

**Issue by akhilender-bongirwar** [kunjgit/GameZone#297]
### 🎮 Game Request

Game logic and basic description:
It is a 2 player fun game. The players will have to roll the dice and the coins on the board will move itself according to the number they have got on the dice. It is like the traditional snakes and ladder game which we have played in our childhood.

### Point down the features

Game points:
The one who reaches the end of the board first will be the winner of the game.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @akhilender-bongirwar 👋!
 
  @kunjgit here, 
 We have this annoucement to make 📢!! 
 During the time of PR don't alter main index file ! 🙂 
 In main Readme file just use * as a game number during the time we are merging we will add number !! 👀 
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG) if you haven't 😇 
  Thank you 💗!

**Comment by kunjgit** [comment]
Hey @akhilender-bongirwar ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
