### ISSUE TITLE
[Bug]: the lizard spock game (game number 282) is showing error 404

### ISSUE THREAD

**Issue by abhisar-yadav** [kunjgit/GameZone#2983]
### Give a brief about the bug ✍️

The lizard spock game is not working

### What is the expected behavior? 🤔

The game is supposed to work as usual but It is showing error 404, file not found.

### Provide step by step information reproduce the bug 📄

open the GameZone website 
scroll down to game number 282
click on the LIZARD SPOCK GAME
[Screenshot (14)](https://github.com/kunjgit/GameZone/assets/112550486/95504344-84cd-46e9-9f1c-49bcd7e7664b)

### Select program in which you are contributing

hacktoberfest

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @abhisar-yadav , You can't have another issue before completing the previous one 😀 
 you already have the following 1 open issues 👀 ! :

#2844

**Comment by kunjgit** [comment]
Hey @abhisar-yadav ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by kunjgit** [comment]
Hey @abhisar-yadav ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by abhisar-yadav** [comment]
PLEASE ASSIGN ME THIS ISSUE
