### ISSUE TITLE
[Enhancement]: UI/UX in race_car

### ISSUE THREAD

**Issue by Moracus** [kunjgit/GameZone#2985]
### Do you want to have the enhancement of existing game ? 😀 Describe yourself..

Game enhancement
1. The game play screen would look better centered on the screen.
2. Game instructions should be part of UI on the start scrreen and disappear when the game starts.
3. A,W,S,D controls should also be present instead of just arrow keys.

### Describe the solution you'd like

Solution steps:
1. I'll center the game play screen
2. Will make a proper startscreen UI
3. will add A,W,S,D controls to enhance ux.

### Select program in which you are contributing

hacktoberfest

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Moracus , You can't have another issue before completing the previous one 😀 
 you already have the following 1 open issues 👀 ! :

#2963

**Comment by kunjgit** [comment]
Hey @Moracus ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by kunjgit** [comment]
Hey @Moracus ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)
