### ISSUE TITLE
[New game]: Tic-Toc-Toe Game

### ISSUE THREAD

**Issue by pabitra0011** [kunjgit/GameZone#2986]
### 🎮 Game Request

Game Setup:
Tic-Tac-Toe is played on a 3x3 grid, making a total of 9 cells.
Two players take turns, one using "X" and the other using "O."

Starting the Game:
Decide who goes first, often done by flipping a coin or another random method.
The first player places their mark ("X" or "O") on any empty cell on the grid.

Taking Turns:
Players take turns placing their marks on empty cells.
Once a cell is marked, it cannot be used again in the game.

Winning the Game:
A player wins the game if they get three of their marks in a row, horizontally, vertically, or diagonally.
The game ends as soon as a player wins, and they are declared the winner.

Restart the Game:
After A player wining A restart button is visible, wher user click restart button it start a new game.

### Point down the features

We need two player to play this game.

### Select program in which you are contributing

hacktoberfest

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by pabitra0011** [comment]
Please assing me this issue , so I can work on this.

**Comment by kunjgit** [comment]
Hey @pabitra0011 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @pabitra0011! 
We are already having a similar game request in #2333 👀 
Make sure you come up with a cool unique idea 😀 
 Waiting for your new game idea 💗.

**Comment by kunjgit** [comment]
Hey @pabitra0011 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
