### ISSUE TITLE
[New game]: Age_Calculator

### ISSUE THREAD

**Issue by Keshab1113** [kunjgit/GameZone#2990]
### 🎮 Game Request

Frontend game developed using HTML, CSS, JavaScript. Here user can see his/her age.
functions->
- Chose your date of birth.
- Click Age Button.
- And see your age.
![Screenshot (89)](https://github.com/kunjgit/GameZone/assets/110785343/2c2063f6-9582-41b9-89ad-b75a4fd4c52b)

### Point down the features

Frontend game developed using HTML, CSS, JavaScript. Here user can see his/her age.
functions->
- Chose your date of birth.
- Click Age Button.
- And see your age.

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by 29deepanshutyagi** [comment]
i want to work on this issue ,kindly assign me this issue @kunjgit , if this issue is open under IWOC

**Comment by Keshab1113** [comment]
Show me, what will you Change or update in this website.

**Comment by suhanachaudhary** [comment]
Hi ,I want to work on this project.Please assign it tome

**Comment by shuhaki** [comment]
i have very good experience in fronted part, i did some good projects related to fronted so, could you please assaign it to me i will do it

**Comment by kunjgit** [comment]
Hello @Keshab1113, Time's up!⏰ 
 Sorry for closing your issue! 
 But it's more than a week since we haven't received anything from your side 😢 . 
 Come up with new ideas, create a new issue and make sure you finish it within a week! 🔥 
 All the best! 🚀 
 Happy Hacking! 💗

**Comment by kunjgit** [comment]
Hey @Keshab1113 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
