### ISSUE TITLE
[New game]: Flip and match cards

### ISSUE THREAD

**Issue by Shivansh175** [kunjgit/GameZone#2991]
### 🎮 Game Request

Game logic and basic description

This is a game where several cards containing different image are laid upside down. User picks any of the cards and then another one, if both of them contain same image both the cards are removed otherwise turned upside down again. User has to memorize the position of cards in order to open correct card and match them out. As soon as all the cards are removed user wins the game.

### Point down the features

Game points

This will be a pokemon theme based game
There will be three difficulty levels - Easy, Medium and Difficult

### Select program in which you are contributing

hacktoberfest

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hello @Shivansh175, Time's up!⏰ 
 Sorry for closing your issue! 
 But it's more than a week since we haven't received anything from your side 😢 . 
 Come up with new ideas, create a new issue and make sure you finish it within a week! 🔥 
 All the best! 🚀 
 Happy Hacking! 💗

**Comment by kunjgit** [comment]
Hey @Shivansh175 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
