### ISSUE TITLE
[New game]: Virtual Piano

### ISSUE THREAD

**Issue by Chirag-04** [kunjgit/GameZone#30]
### 🎮 Game Request

The Virtual Piano Project is an exciting digital platform that provides users with a realistic and immersive piano-playing experience. With a lifelike keyboard interface ,users of all skill levels can enjoy playing the piano from the comfort of their computer or mobile device. Whether you're a beginner or an experienced pianist, the Virtual Piano Project offers a convenient and inspiring way to explore and express your musical talents.
![Piano sample](https://github.com/kunjgit/GameZone/assets/95089015/7303012b-b3d9-4658-84f2-371a7cadbfc2)

### Point down the features

High Quality sounds: The game uses high-quality sounds of a real drum kit, providing a realistic playing experience.
Sample Song : The game provides you with a selection of sample songs that you can use to practice playing the piano.
Recording Feature : The game allows you to record your piano lessons.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by Chirag-04** [comment]
I am highly enthusiastic about working on this project, so if you find my idea appealing, I would be delighted if you assign me the task.

**Comment by kunjgit** [comment]
Hey @Chirag-04 ! Thank you for raising an issue 💗 You have been assigned this issue you can start working on the issue 🎮

**Comment by Chirag-04** [comment]
> Hey @Chirag-04 ! Thank you for raising an issue 💗 You have been assigned this issue you can start working on the issue 🎮

**Comment by Chirag-04** [comment]
Thank you sir for assigning the task to me .

**Comment by Chirag-04** [comment]
@kunjgit Heya Sir, could you please provide me with guidance on what to do next? I've finished the task assigned to me.

**Comment by kunjgit** [comment]
Hello @Chirag-04, Time's Uppp!⏰ 
 Sorry for closing your issue! 
 But it's more than a week since we haven't received anything from your side 😢 . 
 Come up with new ideas, create a new issue and make sure you finish it within a week! 🔥 
 All the best! 🚀 
 Happy Hacking! 💗

**Comment by kunjgit** [comment]
Hey @Chirag-04 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
