### ISSUE TITLE
[New game]: Adding a topG game 

### ISSUE THREAD

**Issue by ShivangRawat30** [kunjgit/GameZone#300]
### 🎮 Game Request

Game logic and basic description 
This is a parody game in which you are provided with a character named TopG and you have to prevent getting in contact with the opponent more like mario game.

### Point down the features

Game points
Points counter, fun UI

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @ShivangRawat30 👋!
 
  @kunjgit here, 
 We have this annoucement to make 📢!! 
 During the time of PR don't alter main index file ! 🙂 
 In main Readme file just use * as a game number during the time we are merging we will add number !! 👀 
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG) if you haven't 😇 
  Thank you 💗!

**Comment by kunjgit** [comment]
Hey @ShivangRawat30 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
