### ISSUE TITLE
[New game]: 

### ISSUE THREAD

**Issue by Darkrider0007** [kunjgit/GameZone#3004]
### 🎮 Game Request

Create a game window and ball object. Handle user input for movement. Implement physics for ball motion, gravity, and collisions with platforms. Design platforms as rectangles. Track and display the score. End the game when the ball falls off the screen. Implement a game loop for continuous updates. Optionally, add graphics and sound effects for a better gaming experience.

### Point down the features

- **Game Window:** Set up a display interface for the game.
- **Ball Object:** Create a movable ball with properties like position and speed.
- **User Input:** Enable user interaction for controlling the ball's movement.
- **Physics:** Implement gravity and collision detection for realistic ball behavior.
- **Platforms:** Design surfaces for the ball to bounce on.
- **Scoring:** Keep track of points earned during gameplay.
- **Game Over:** End the game when the ball falls off the screen.
- **Game Loop:** Continuously update game elements for seamless gameplay.
- **Graphics/Sound:** Enhance the experience with visual and audio effects.

### Select program in which you are contributing

hacktoberfest

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Darkrider0007 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @Darkrider0007! 
We are already having a similar game request in #2996 👀 
Make sure you come up with a cool unique idea 😀 
 Waiting for your new game idea 💗.

**Comment by kunjgit** [comment]
Hey @Darkrider0007 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
