### ISSUE TITLE
[New game]: Ball Fall Game 

### ISSUE THREAD

**Issue by Rajiiee** [kunjgit/GameZone#3018]
### 🎮 Game Request

Game logic and basic description : the game basically revolves around a ball which need to be continuously made to fall through the random holes in the platform and prevented to touch the ceiling of screen/canvas.[
![ss1](https://github.com/kunjgit/GameZone/assets/113358696/a742868f-0a42-40a2-8f09-bb38dca74f0a)
![ss2](https://github.com/kunjgit/GameZone/assets/113358696/8001e166-9538-44f2-ae58-7487679641cd)

### Point down the features

Game points : 
1. Level implementation
2. Both windows and android friendly
3. Score calculation
4. Auto refresh

### Select program in which you are contributing

hacktoberfest

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Rajiiee ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hello @Rajiiee, Time's up!⏰ 
 Sorry for closing your issue! 
 But it's more than a week since we haven't received anything from your side 😢 . 
 Come up with new ideas, create a new issue and make sure you finish it within a week! 🔥 
 All the best! 🚀 
 Happy Hacking! 💗

**Comment by kunjgit** [comment]
Hey @Rajiiee ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
