### ISSUE TITLE
[New game]: Keyboard kit Game

### ISSUE THREAD

**Issue by ayushlohmod** [kunjgit/GameZone#3021]
### 🎮 Game Request

A website To play keyboard sounds in your browser.

### Point down the features

Game consists of following functionalities :

User can play diffrent drum sounds by the keyboard keys written on the drum
User can play many sounds at a time
Diffrent sounds like kick,tom,crash and snare has been included.

### Select program in which you are contributing

hacktoberfest

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @ayushlohmod , You can't have another issue before completing the previous one 😀 
 you already have the following 1 open issues 👀 ! :

#2925

**Comment by kunjgit** [comment]
Hey @ayushlohmod ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by kunjgit** [comment]
Hey @ayushlohmod! 
We are already having a similar game request in #2925 👀 
Make sure you come up with a cool unique idea 😀 
 Waiting for your new game idea 💗.

**Comment by kunjgit** [comment]
Hey @ayushlohmod ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)
