### ISSUE TITLE
[Enhancement]: Update UI of snake game for Improved User Experience

### ISSUE THREAD

**Issue by rishiofficial** [kunjgit/GameZone#3022]
### Do you want to have the enhancement of existing game ? 😀 Describe yourself..

Game enhancement
![Screenshot (8)](https://github.com/kunjgit/GameZone/assets/109091515/d3765d19-e7d1-4cb7-9f46-14dc2f6edfb7)
The current user interface (UI) of the application could benefit from an update to enhance the user experience. This issue is created to track and discuss the necessary changes and improvements to the UI.

### Describe the solution you'd like

Solution steps

### Select program in which you are contributing

hacktoberfest

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @rishiofficial ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hello @rishiofficial, Time's up!⏰ 
 Sorry for closing your issue! 
 But it's more than a week since we haven't received anything from your side 😢 . 
 Come up with new ideas, create a new issue and make sure you finish it within a week! 🔥 
 All the best! 🚀 
 Happy Hacking! 💗

**Comment by kunjgit** [comment]
Hey @rishiofficial ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
