### ISSUE TITLE
QUIZ MASTER 

### ISSUE THREAD

**Issue by dprasuna** [kunjgit/GameZone#3024]
### 🎮 Game Request

"I want to create a quiz game where users can play against the computer. Players will have 25 seconds to answer each question. The game will challenge them with various questions."

### Point down the features

User-friendly Interface: An intuitive interface for easy navigation and a smooth user experience.

Quiz Categories: Multiple categories to choose from, ensuring diverse topics for players to engage with.

Time-bound Questions: Each question is timed, giving players 25 seconds to provide their answer, adding a thrilling challenge.

Single/Multiplayer Modes: Option to play against the computer or compete with friends in multiplayer mode.

Scoring and Leaderboards: Keeping track of scores and displaying them on leaderboards, encouraging competition and a sense of achievement.

Hints and Lifelines: Offering hints or lifelines to assist players if they get stuck on a question.

Progress Saving: Allowing players to save their progress and resume the game at their convenience.

Dynamic Difficulty: Adjusting question difficulty based on the player's performance, ensuring an engaging experience for all skill levels.

Sound and Visual Effects: Engaging audio and visual elements to enhance the gaming experience.

### Select program in which you are contributing

hacktoberfest, GSSoC23, Other

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by dprasuna** [comment]
Assign This task to me

**Comment by kunjgit** [comment]
Hey @dprasuna ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @dprasuna! 🙂 
 It seems like you are not following proper guidelines !! 👀 
 Read documentation properly !!🙏 
 If you have any queries reach out to us on [Discord🕹️](https://discord.gg/fgwk4XZfxG) .

**Comment by kunjgit** [comment]
Hey @dprasuna ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
