### ISSUE TITLE
[Enhancement]: README.md Enhancement, Add the More Detailed Instructions on How to Play the 3d Snake Game.

### ISSUE THREAD

**Issue by akhilrocz** [kunjgit/GameZone#3026]
### Do you want to have the enhancement of existing game ? 😀 Describe yourself..

The READ.ME File does not have detailed instructions of how to play the game,controls,tips to how to play the game etc.

### Describe the solution you'd like

Solution steps:

1.Game Tilte and how it is built and what technologies are used.

2.Gameplay:Detailed description of the game.

3.Controls.

4.Detailed game rules.

5.How to Play

6.Tips

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @akhilrocz ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by akhilrocz** [comment]
When i try to push the updated file it says access denied to me.

**Comment by akhilrocz** [comment]
I linked a PR that solves the issue please check the maintainers and merge it if it relly solves the issue.

**Comment by kunjgit** [comment]
Hello @akhilrocz, Time's up!⏰ 
 Sorry for closing your issue! 
 But it's more than a week since we haven't received anything from your side 😢 . 
 Come up with new ideas, create a new issue and make sure you finish it within a week! 🔥 
 All the best! 🚀 
 Happy Hacking! 💗

**Comment by kunjgit** [comment]
Hey @akhilrocz ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
