### ISSUE TITLE
[Enhancement]: In the Aim_Training website,UI is not looking good and attractive and there is no stop buton to stop the game,and there are no difficulty levels like easy,medium,hard.

### ISSUE THREAD

**Issue by akhilrocz** [kunjgit/GameZone#3028]
### Do you want to have the enhancement of existing game ? 😀 Describe yourself..

Game enhancement for Aim_Training Website make sure the game is attractive to the new users who are playing,enhance the ui design and add more options like buttons,menus and add difficulty levels like easy medium hard.

### Describe the solution you'd like

Add better ui design and add menus,buttons etc.

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @akhilrocz , You can't have another issue before completing the previous one 😀 
 you already have the following 1 open issues 👀 ! :

#3026

**Comment by kunjgit** [comment]
Hey @akhilrocz ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by kunjgit** [comment]
Hey @akhilrocz ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)
