### ISSUE TITLE
[Bug]: Inconsistent Games Preview on Home Page

### ISSUE THREAD

**Issue by JiyaGupta-cs** [kunjgit/GameZone#3035]
### Give a brief about the bug ✍️

**Description**
The user cannot see the games preview properly on the Home Page as you can see in the screenshot

![image](https://github.com/kunjgit/GameZone/assets/140608790/05bc4b40-ba4c-4567-81e5-7fd4710b9e39)

### What is the expected behavior? 🤔

The Games should have a proper preview

### Provide step by step information reproduce the bug 📄

Description
Navigate to the Home Page and see the Games Preview from serial 287 up to the end and many are left in between also. 

### Select program in which you are contributing

IWOC 2.0

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @JiyaGupta-cs ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by JiyaGupta-cs** [comment]
@kunjgit  Please assign me this issue under IWOC and also add labels of "iwoc2024" and "medium"/"hard" etc.

**Comment by JiyaGupta-cs** [comment]
@kunjgit Please review the PR

**Comment by kunjgit** [comment]
Hello @JiyaGupta-cs, Time's up!⏰ 
 Sorry for closing your issue! 
 But it's more than a week since we haven't received anything from your side 😢 . 
 Come up with new ideas, create a new issue and make sure you finish it within a week! 🔥 
 All the best! 🚀 
 Happy Hacking! 💗

**Comment by kunjgit** [comment]
Hey @JiyaGupta-cs ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
