### ISSUE TITLE
[New game]: ladoo_catcher 

### ISSUE THREAD

**Issue by hemant933** [kunjgit/GameZone#3036]
### 🎮 Game Request

in this game we have edible and non-edible items , and we need no catch edible items to get the points , if we catch non-edible it will deduct our points if our points reach negative , the game will over.

### Point down the features

Game points - +10 for edible catch
 -5 for non-edibles

### Select program in which you are contributing

IWOC 2.0

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by hemant933** [comment]
assign it to me

**Comment by kunjgit** [comment]
Hey @hemant933 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by hemant933** [comment]
Thanks, I will.

**Comment by kunjgit** [comment]
Hello @hemant933, Time's up!⏰ 
 Sorry for closing your issue! 
 But it's more than a week since we haven't received anything from your side 😢 . 
 Come up with new ideas, create a new issue and make sure you finish it within a week! 🔥 
 All the best! 🚀 
 Happy Hacking! 💗

**Comment by kunjgit** [comment]
Hey @hemant933 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
