### ISSUE TITLE
new game -rock paper scissor

### ISSUE THREAD

**Issue by Tusharjoshi1703** [kunjgit/GameZone#3048]
### 🎮 Game Request

Game logic and basic description

### Point down the features

Game points

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Tusharjoshi1703 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by eeshsaxena** [comment]
Can i get his issue ?? First issue for me. I would like to give it a try

**Comment by kunjgit** [comment]
@Jithendranath8 it's already on GameZone!

**Comment by kunjgit** [comment]
Hey @Tusharjoshi1703 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
