### ISSUE TITLE
Typing Speed Test

### ISSUE THREAD

**Issue by iamvtyagi** [kunjgit/GameZone#3050]
### 🎮 Game Request

Description:
In the Typing Speed Test game, players are presented with a passage of text. They must type the passage as quickly and accurately as possible. The game calculates their typing speed in words per minute (WPM) and accuracy percentage.

Game Logic:
1.Display a passage of text for the player to type.
2.Start a timer when the player begins typing.
3.Track the number of correct words typed and calculate typing speed (WPM).
4.Calculate accuracy by comparing the typed text with the original passage.
5.Stop the timer when the player completes typing.
6.Display the player's WPM and accuracy percentage.

### Point down the features

it will give your typing speed in wpm and it also calculate the accuracy of the typed text 

### Select program in which you are contributing

Other

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @iamvtyagi ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @iamvtyagi! 🙂 
 It seems like you are not following proper guidelines !! 👀 
 Read documentation properly !!🙏 
 If you have any queries reach out to us on [Discord🕹️](https://discord.gg/fgwk4XZfxG) .
