### ISSUE TITLE
[New game]: MemBox

### ISSUE THREAD

**Issue by abdulshahvez** [kunjgit/GameZone#3051]
### 🎮 Game Request

Game logic and basic description: MemBox is a memory based fun game with infinite levels each getting tougher ever level.
It has 4 boxes all different colors. 
level 1: 1 box will glow for a sec .
level 2 : now 2 boxes
level 3 : now 3 boxes and so on.
Your duty is to remember the pattern of that glow and click it in the same order.
The game doesn't have end its just about when your memory power gives up.

### Point down the features

MemBox is a memory based fun game with infinite levels each getting tougher ever level.
It has 4 boxes all different colors. 
level 1: 1 box will glow for a sec .
level 2 : now 2 boxes
level 3 : now 3 boxes and so on.
Your duty is to remember the pattern of that glow and click it in the same order.
The game doesn't have end its just about when your memory power gives up.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @abdulshahvez ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by anirudh-why** [comment]
Please assign me this issue under GSSOC'24

**Comment by kunjgit** [comment]
Hey @abdulshahvez ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
