### ISSUE TITLE
[New game]: Snake

### ISSUE THREAD

**Issue by VirendraVerma1274** [kunjgit/GameZone#3053]
### 🎮 Game Request

Game logic and basic description<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Snake Game</title>
    <link rel="stylesheet" href="styles.css">
</head>
<body>
    <div id="game-area">
        
    </div>

    <script src="script.js"></script>
</body>
</html>

### Point down the features

Game points

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @VirendraVerma1274 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by bhavanishanker-png** [comment]
Please allocate this task to me. I'm capable of tackling it as I possess all the requisite skills to address the matter at hand.

**Comment by SohaFarhana** [comment]
Helloo
I am a contributor of Girl Script 2024 
I would like to work on this area

**Comment by ananyag309** [comment]
Hi, I hope this message finds you well.

I am writing to express my interest in contributing to the issue. I am enthusiastic about participating in GSSoC'24 and believe that working on this issue will allow me to make a meaningful contribution to the project.

Could you please assign this issue to me under GSSoC'24?

Thank you for considering my request. (also please add gssoc label)

**Comment by ishita-43** [comment]
Hello @VirendraVerma1274 let me know if you are working on the issue or not
if not be will proceed further  by assigning it to the next person.!!

**Comment by ishita-43** [comment]
> Please allocate this task to me. I'm capable of tackling it as I possess all the requisite skills to address the matter at hand.

I am assigning this task to you। Start working on the issue..

**Comment by kunjgit** [comment]
Hello @VirendraVerma1274, Time's up!⏰ 
 Sorry for closing your issue! 
 But it's more than a week since we haven't received anything from your side 😢 . 
 Come up with new ideas, create a new issue and make sure you finish it within a week! 🔥 
 All the best! 🚀 
 Happy Hacking! 💗

**Comment by kunjgit** [comment]
Hey @VirendraVerma1274 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
