### ISSUE TITLE
[New game]: The classic Flappy Bird Game

### ISSUE THREAD

**Issue by BagchiShreya** [kunjgit/GameZone#3054]
### 🎮 Game Request

Game logic and basic description-The gameplay begins when the player clicks the space bar key. The bird needs to cross poles both above and below to score 1 point. Both the poles are assigned with 0.5 points therefore, crossing both would get the player 1 point. If the bird hits either of the poles, the game is over. The game can be restarted by clicking the space bar key again or the restart button.

### Point down the features

Game points-The score of the player will be shown on the top of the screen

### Select program in which you are contributing

Other

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @BagchiShreya ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
@BagchiShreya it's already on GameZone please make sure  you are properly looking at existing games and coming up with something creative !

**Comment by kunjgit** [comment]
Hey @BagchiShreya ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
