### ISSUE TITLE
simon game

### ISSUE THREAD

**Issue by suhanachaudhary** [kunjgit/GameZone#3055]
### Do you want to have the enhancement of existing game ? 😀 Describe yourself..

Hi .I am Suhana Chaudhary .I am having good knowledge of web development. I want to do some changes in Simon game to make more attractive and responsive like instruction block and level button.Please give me permission to work on this project.

### Describe the solution you'd like

Solution steps:
firstly I try to improve or make responsive level block.
second instruction detail's block improve and add some functionality.
set all project position which looks better

### Select program in which you are contributing

IWOC2024

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by suhanachaudhary** [comment]
Hii.please give me a chance to work on this project

**Comment by kunjgit** [comment]
Hey @suhanachaudhary! 🙂 
 It seems like you are not following proper guidelines !! 👀 
 Read documentation properly !!🙏 
 If you have any queries reach out to us on [Discord🕹️](https://discord.gg/fgwk4XZfxG) .

**Comment by kunjgit** [comment]
Hey @suhanachaudhary ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @suhanachaudhary ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by suhanachaudhary** [comment]
So i start work on this project
