### ISSUE TITLE
Missing Code of Conduct File in Repository

### ISSUE THREAD

**Issue by anshgautam-github** [kunjgit/GameZone#3056]
### Describe the bug ✍️

Currently, the repository lacks a Code of Conduct file, which is an essential component for fostering a healthy and inclusive open-source community. A Code of Conduct serves as a guideline for expected behavior, ensuring that contributors and participants feel safe, respected, and valued within our community space.

Kindly assign me this issue, so i can work towards it under GSSOC 24

### Provide step by step information reproduce the bug 📄

I need to create a Code of Conduct file and integrate it into our repository. This file should outline expected behaviors, consequences for violating the Code of Conduct, and procedures for reporting incidents. Additionally, it should align with recognized open-source community standards, such as the Contributor Covenant, to ensure comprehensiveness and inclusivity.

Tasks:

Research and select an appropriate Code of Conduct template (e.g., Contributor Covenant, Citizen Code of Conduct).
Adapt the selected template to fit the specific needs and values of our community.
Create a new file named "CODE_OF_CONDUCT.md" or similar in the repository root directory.
Populate the file with the finalized Code of Conduct content.
Update the repository documentation and contributing guidelines to reference the Code of Conduct.
Communicate the implementation of the Code of Conduct to the community through appropriate channels (e.g., README.md, community forums, social media).

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @anshgautam-github ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @anshgautam-github! 🙂 
 It seems like you are not following proper guidelines !! 👀 
 Read documentation properly !!🙏 
 If you have any queries reach out to us on [Discord🕹️](https://discord.gg/fgwk4XZfxG) .

**Comment by kunjgit** [comment]
Hey @anshgautam-github ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
