### ISSUE TITLE
[Bug]: The search bar needs to be improved.

### ISSUE THREAD

**Issue by Ashray-A** [kunjgit/GameZone#3058]
### Give a brief about the bug ✍️

The search bar has a bad UX and is not very intuitive to use. It goes out of focus when the cursor moves away. It needs improvement

### What is the expected behavior? 🤔

The search bar actually has to work like when we even move the cursor away from it after typing something then it should not disappear. The text should remain.

### Provide step by step information reproduce the bug 📄

Move to the search box and type something and move the cursor away from the search box. The text will disappear and reappears only when we move the cursor again to the search box.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by Ashray-A** [comment]
Please assign me this issue and I will improve the search bar functionality and UX

**Comment by IP80808080** [comment]
👋 Hello! I'd be happy to help with this issue. Could you please assign it to me? Additionally, could you please label it for the appropriate level? Thank you! 🚀

**Comment by FatemaBaig** [comment]
Hello sir,
i would like to work on this project. Please assign it to me under GSSOC-24

**Comment by abhishekpandey26** [comment]
i would like to do the work please assign this task to me..

**Comment by Ashray-A** [comment]
> > Please assign me this issue under GSSOC'24 and I will improve the search bar functionality and UX
> 
> Hi there! The task is already assigned to you ,let me know how much work ,time you need to complete the issue. If you are not working on this issue I will assign the task to the next person 

>Hey I won't be able to work on this issue. Please assign it to the next person.

**Comment by ishita-43** [comment]
> @kunjgit Kindly assign it to me under GSSOC'24 i can make ui of search bar better

Hi this task is now assigned to you now you can start working on this issue

**Comment by ishita-43** [comment]
Due to Inactivity assignment is removed

**Comment by kunjgit** [comment]
Hello @Ashray-A, Time's up!⏰ 
 Sorry for closing your issue! 
 But it's more than a week since we haven't received anything from your side 😢 . 
 Come up with new ideas, create a new issue and make sure you finish it within a week! 🔥 
 All the best! 🚀 
 Happy Hacking! 💗

**Comment by kunjgit** [comment]
Hey @Ashray-A ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
