### ISSUE TITLE
[Bug]: 16.Number Guessing Game

### ISSUE THREAD

**Issue by suma30** [kunjgit/GameZone#3059]
### The Bug
![Screenshot 2024-05-09 195804](https://github.com/kunjgit/GameZone/assets/112741893/48b030ca-00cc-4ab9-8080-2feed9d92081)
The main game panel is colliding with Home icon

### What is the expected behavior? 🤔

The panel should have a proper spacing from the home icon for an appealing look

### Provide step by step information reproduce the bug 📄

I will adjust the spacing between the two elements for a good look,
Please assign me this issue @kunjgit

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by sys-atasi** [comment]
Please assign me this issue under gssoc24

**Comment by suma30** [comment]
@sys-atasi you can check the website again thoroughly and you too can open your own issues :)

**Comment by IP80808080** [comment]
👋 Hello! I'd be happy to help with this issue. Could you please assign it to me? Additionally, could you please label it for the appropriate level? Thank you! 🚀

**Comment by Saumyasrivastava24** [comment]
I can fix this issue as I have worked on a similar type of game before also. Kindly assign me this issue so that I can contribute in this._

**Comment by suma30** [comment]
@kunjgit Please can you assign me this issue and also add GSSOC labels for this issue

**Comment by Vinayakkh** [comment]
\assign

**Comment by suma30** [comment]
@kunjgit Actually, I created the issue, may I know the reason why I wasn't assigned the issue but someone else got assigned to this issue??

**Comment by kunjgit** [comment]
Hey @suma30 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
