### ISSUE TITLE
flappy_bird[Enhancement]: 

### ISSUE THREAD

**Issue by sidhigrover** [kunjgit/GameZone#3060]
### Do you want to have the enhancement of existing game ? 😀 Describe yourself..

Game enhancement

<img width="1440" alt="Screenshot 2024-05-10 at 2 29 40 PM" src="https://github.com/kunjgit/GameZone/assets/123989540/b99879a6-ca46-4fe9-8fc7-074bf42543ff">

changes in right side css text (how to play........press space or arrowup key to restart)
present css of text is not looking good.

### Describe the solution you'd like

Solution steps

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by Bhumika1312** [comment]
**Do you want to have the enhancement of existing game ? 😀 Describe yourself..**
Game enhancement

![image](https://github.com/kunjgit/GameZone/assets/115869626/feb490c4-e4c5-45b0-ae9f-269197c52d1a)

changes in right side css text (how to play........press space or arrowup key to restart)
present css of text is not looking good.

**Describe the solution you'd like**
Solution Steps
Positions the "how to play" text on the right side of the screen with some padding from the top and right edges. Uses a semi-transparent black background for the text box to make it stand out without obstructing the game. Will apply any text colour for better contrast against the background. will be adding some  padding and border-radius to make the text box visually appealing.  Will add some line height for better readability. It will be including a media query for smaller screens to adjust font size and padding accordingly to make it more responsive.

**Select program in which you are contributing**

GSSoC24

**Code of Conduct**

- [ ] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by IP80808080** [comment]
👋 Hello! I'd be happy to help with this issue. Could you please assign it to me? Additionally, could you please label it for the appropriate level? Thank you! 🚀

**Comment by kunjgit** [comment]
Hello @sidhigrover, Time's up!⏰ 
 Sorry for closing your issue! 
 But it's more than a week since we haven't received anything from your side 😢 . 
 Come up with new ideas, create a new issue and make sure you finish it within a week! 🔥 
 All the best! 🚀 
 Happy Hacking! 💗

**Comment by kunjgit** [comment]
Hey @sidhigrover ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
