### ISSUE TITLE
No High Score display in the Alien shooters game

### ISSUE THREAD

**Issue by Varnika2526** [kunjgit/GameZone#3061]
Hi, 
Adding a **High Score** to the **Alien Shooters** game could result in engaging gameplay.
I will create a High Score format for the game.
Please assign me this issue @kunjgit

I will follow CONTRIBUTING_GUIDELINE.md

**Comment by kunjgit** [comment]
Hey @Varnika2526! 🙂 
 It seems like you are not following proper guidelines !! 👀 
 Read documentation properly !!🙏 
 If you have any queries reach out to us on [Discord🕹️](https://discord.gg/fgwk4XZfxG) .

**Comment by kunjgit** [comment]
Hey @Varnika2526 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
