### ISSUE TITLE
[Bug]: UI of pagination

### ISSUE THREAD

**Issue by shilpashingnapure** [kunjgit/GameZone#3062]
### Give a brief about the bug ✍️

UI of pagination , we can improve that more
<img width="1373" alt="Screenshot 2024-05-10 at 4 00 31 PM" src="https://github.com/kunjgit/GameZone/assets/69167064/8f0b1070-93b5-4da3-b129-c6d773cb3567">

### What is the expected behavior? 🤔

1. alignment of buttons.
2. for page numbers , in future if we have more page that number will increase , so we can make it better

### Provide step by step information reproduce the bug 📄

1. alignment between the buttons.
2. for page number UI , we can discuss

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by Aiko002** [comment]
@shilpashingnapure I want to contribute to fix this issue

**Comment by IP80808080** [comment]
👋 Hello! I'd be happy to help with this issue. Could you please assign it to me? Additionally, could you please label it for the appropriate level? Thank you! 🚀

**Comment by shilpashingnapure** [comment]
@Aiko002 Im not a admin of this repo , I have raise this issue to work on

**Comment by shilpashingnapure** [comment]
hi @kunjgit I have started to work on this , if you want to discuss please let me know , and please assign task to me under gssoc'24 , so i could understand I'm only working on this issue.

**Comment by kunjgit** [comment]
Hello @shilpashingnapure, Time's up!⏰ 
 Sorry for closing your issue! 
 But it's more than a week since we haven't received anything from your side 😢 . 
 Come up with new ideas, create a new issue and make sure you finish it within a week! 🔥 
 All the best! 🚀 
 Happy Hacking! 💗

**Comment by kunjgit** [comment]
Hey @shilpashingnapure ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
