### ISSUE TITLE
[New game]: Snake Game for catching fruits

### ISSUE THREAD

**Issue by Jagpreet153** [kunjgit/GameZone#3063]
### 🎮 Game Request

Game logic and basic description
A snake move in a maze and by catching fruits its length increases . The game gets over if it strikes itself or boundary of maze

### Point down the features

Game points
The points increase if it catches fruits and high score is recorded for upcoming matches . It is enabled with level change (easy , medium , hard) and sound features

### Select program in which you are contributing

GSSoC'24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by Jagpreet153** [comment]
Kindly assign this task to me under GSSoC'24

**Comment by JYWSally** [comment]
Please assign this task to me, thanks!

**Comment by aditi-sharma-2004** [comment]
Hi, Aditi Sharma this side , I would love to work on this game. GSSoC'24

**Comment by Jagpreet153** [comment]
@kunjgit I have updated readme file kindly have a look

**Comment by kunjgit** [comment]
Hey @Jagpreet153 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
