### ISSUE TITLE
More Social media links should be added ,like of  Instagram, Facebook which are no there for better marketing and socialising.

### ISSUE THREAD

**Issue by Suvam3456** [kunjgit/GameZone#3065]
### Give a brief about the bug ✍️

Hello PA.
Your project has only 3 social of your's, which are Twitter, github and Linkedn.

![image](https://github.com/kunjgit/GameZone/assets/99579881/60818dac-b5f6-4b70-aaa0-09eeb93a383d)

### What is the expected behavior? 🤔

I guess users of facebook and instagram are  more and adding those will cause better socialising and people can share their experiences in those social as well.

### Provide step by step information reproduce the bug 📄

I can add social media icons of instagram, facebook which will be directing to your respective accounts,
Please assign me this issue @kunjgit under GSSOC'24 .

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Suvam3456! 🙂 
 It seems like you are not following proper guidelines !! 👀 
 Read documentation properly !!🙏 
 If you have any queries reach out to us on [Discord🕹️](https://discord.gg/fgwk4XZfxG) .

**Comment by kunjgit** [comment]
Hey @Suvam3456 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by Suvam3456** [comment]
@kunjgit ,I am sorry if i did anything wrong, this is my first time in open source I am still unaware what i did'nt followed, please let me know
