### ISSUE TITLE
Add copyright label to footer section.

### ISSUE THREAD

**Issue by Suvam3456** [kunjgit/GameZone#3066]
### Give a brief about the bug ✍️

Hello PA, 
The footer section of  website is missing the copyright label. 

### What is the expected behavior? 🤔

We need to add a copyright notice to comply with legal requirements and protect our content.

### Provide step by step information reproduce the bug 📄

I will add a copyright notice similiar to below image of a random website.
![image](https://github.com/kunjgit/GameZone/assets/99579881/374c7e13-140d-4ed3-9a97-8ce2095aa90a)

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Suvam3456! 🙂 
 It seems like you are not following proper guidelines !! 👀 
 Read documentation properly !!🙏 
 If you have any queries reach out to us on [Discord🕹️](https://discord.gg/fgwk4XZfxG) .

**Comment by kunjgit** [comment]
Hey @Suvam3456 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
