### ISSUE TITLE
[New game]: Solve the puzzle

### ISSUE THREAD

**Issue by Pranav-Rastogi1** [kunjgit/GameZone#3068]
### 🎮 Game Request

Game logic and basic description
It is a classic sliding puzzle game where the objective is to rearrange the numbered tiles by sliding them into the empty space. 
There is a single empty space from where you slide and rearrange the complete puzzle .The game is implemented using HTML, CSS, and JavaScript.

### Point down the features

Game points
There is timer in which you have to complete the puzzle. 

### Select program in which you are contributing

Assign me this issue under gssoc 2024.

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by JYWSally** [comment]
Please assign this task to me, thanks!

**Comment by Prathamesshh** [comment]
I would be glad to contribute in this project . please assign this task to me :) .

**Comment by IP80808080** [comment]
👋 Hello! I'd be happy to help with this issue. Could you please assign it to me? Additionally, could you please label it for the appropriate level? Thank you! 🚀

**Comment by kunjgit** [comment]
Hello @Pranav-Rastogi1, Time's up!⏰ 
 Sorry for closing your issue! 
 But it's more than a week since we haven't received anything from your side 😢 . 
 Come up with new ideas, create a new issue and make sure you finish it within a week! 🔥 
 All the best! 🚀 
 Happy Hacking! 💗

**Comment by kunjgit** [comment]
Hey @Pranav-Rastogi1 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
