### ISSUE TITLE
Mouse Transition Effect on GameZone frontend

### ISSUE THREAD

**Issue by MitulSonagara** [kunjgit/GameZone#3069]
As GameZone main website frontend is so lightning and colorful. It will look too good if we add some mouse transition effect on whole website. It will look like where ever mouse pointer will go colors of GameZone will flow out from there. Please assign me this issue so that i can start working on this.

I am contributing under GSSOC'2024.

**Comment by kunjgit** [comment]
Hey @MitulSonagara! 🙂 
 It seems like you are not following proper guidelines !! 👀 
 Read documentation properly !!🙏 
 If you have any queries reach out to us on [Discord🕹️](https://discord.gg/fgwk4XZfxG) .

**Comment by kunjgit** [comment]
Hey @MitulSonagara ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
