### ISSUE TITLE
Hover Effect on Game cards

### ISSUE THREAD

**Issue by MitulSonagara** [kunjgit/GameZone#3070]
I will add hover effect on the game card which will look like search bar outline on hover. By doing this it will match the allover UI of GameZone website.

**Comment by kunjgit** [comment]
Hey @MitulSonagara! 🙂 
 It seems like you are not following proper guidelines !! 👀 
 Read documentation properly !!🙏 
 If you have any queries reach out to us on [Discord🕹️](https://discord.gg/fgwk4XZfxG) .

**Comment by kunjgit** [comment]
Hey @MitulSonagara ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
