### ISSUE TITLE
[Documentation Bug]: Button name should be more clear it should be NUMBER 

### ISSUE THREAD

**Issue by sys-atasi** [kunjgit/GameZone#3071]
### Describe the bug ✍️

Describe your bug here

### Provide step by step information reproduce the bug 📄

Description

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hello @sys-atasi, Time's up!⏰ 
 Sorry for closing your issue! 
 But it's more than a week since we haven't received anything from your side 😢 . 
 Come up with new ideas, create a new issue and make sure you finish it within a week! 🔥 
 All the best! 🚀 
 Happy Hacking! 💗

**Comment by kunjgit** [comment]
Hey @sys-atasi ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
