### ISSUE TITLE
Enhancement of UI of Footer Section 

### ISSUE THREAD

**Issue by VedantAnand17** [kunjgit/GameZone#3072]
**Is your feature request related to a problem? Please describe.**
![Screenshot_2024-05-10-20-44-02-41_40deb401b9ffe8e1df2f1cc5ba480b12.jpg](https://github.com/kunjgit/GameZone/assets/136731196/4dd8b6c6-f68d-4e2d-bc9a-21ef03d22e26)

![Screenshot_2024-05-10-20-44-06-37_40deb401b9ffe8e1df2f1cc5ba480b12.jpg](https://github.com/kunjgit/GameZone/assets/136731196/a5020c9d-b051-4a6d-ab4e-74e19e875685)

In this image you can see the buttons and text fonts are not very appealing 

**Describe the solution you'd like**
The text and buttons interface should be changed in such a way that it looks appealing

**Describe alternatives you've considered**
For the solution I can change the look of the footer texts and buttons which will match the great footer animation such that it looks very appealing hence leading to a great User Interface. 

**Additional context (Mandatory )**
I'd like if you could assign this issue to me as I have made several projects and won a hackathon and would love to contribute in this too…

***Are you contributing under any open-source program ?***
GSSoC'24

**Comment by IP80808080** [comment]
👋 Hello! I'd be happy to help with this issue. Could you please assign it to me? Additionally, could you please label it for the appropriate level? Thank you! 🚀

**Comment by dishathakurata** [comment]
All the contributor icons are not aligned and the font family is not that appealing.

Assign this issue to me under GSSoC '24 to help you with these.

**Comment by VedantAnand17** [comment]
I've already raised this issue to get it assigned to me please find some other issues if possible. Thank you!!

**Comment by kunjgit** [comment]
Hello @VedantAnand17, Time's up!⏰ 
 Sorry for closing your issue! 
 But it's more than a week since we haven't received anything from your side 😢 . 
 Come up with new ideas, create a new issue and make sure you finish it within a week! 🔥 
 All the best! 🚀 
 Happy Hacking! 💗

**Comment by kunjgit** [comment]
Hey @VedantAnand17 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
