### ISSUE TITLE
[New game]: Drumkit

### ISSUE THREAD

**Issue by SwanandD121** [kunjgit/GameZone#3073]
### 🎮 Game Request

A fully functional drumkit game using JavaScript, where different sounds in drum set are played whenever you press the keys A to L on the keyboard. I believe it would be a valuable addition to your platform.
The game is fully developed and ready for integrate in your website.
![image](https://github.com/kunjgit/GameZone/assets/117746995/adfe54fb-ffcd-4089-b0bb-68ef47bab176)

### Point down the features

- The game features a visually appealing drumkit interface, complete with various drum components such as clap, snare, bass drum, hi-hat, boom, and more.
- Each drum component is mapped to a specific key from 'A' to 'L'
- High-quality sound samples are integrated into the game, ensuring that each drum component produces authentic sounds just like a real drum kit.

### Select program in which you are contributing

GSSoC'24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by aditi-sharma-2004** [comment]
Hi, Aditi Sharma this side , I would love to work on this game too. GSSoC'24

**Comment by SwanandD121** [comment]
> Hi, Aditi Sharma this side , I would love to work on this game too. GSSoC'24

Hey Aditi, this game has been already developed by me and is ready for integration on the platform.

**Comment by SwanandD121** [comment]
Hey @ishita-43, thanks for assigning this issue to me. Please add the **level** label to the issue.

**Comment by kunjgit** [comment]
Hello @SwanandD121, Time's up!⏰ 
 Sorry for closing your issue! 
 But it's more than a week since we haven't received anything from your side 😢 . 
 Come up with new ideas, create a new issue and make sure you finish it within a week! 🔥 
 All the best! 🚀 
 Happy Hacking! 💗

**Comment by kunjgit** [comment]
Hey @SwanandD121 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
