### ISSUE TITLE
[New game]: DOTS

### ISSUE THREAD

**Issue by vedanshipathak** [kunjgit/GameZone#3074]
### 🎮 Game Request

The game mechanics include a central player character firing projectiles towards dynamically spawning enemies.
![dot](https://github.com/kunjgit/GameZone/assets/141757766/6532a203-50e0-434f-a895-902a1764cef1)

### Point down the features

 Leveraging JavaScript’s animation Frame for fluid movement and user interaction, the game provides an engaging
experience.
 This project highlights my proficiency in front-end development, JavaScript programming, and game design

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hello @vedanshipathak, Time's up!⏰ 
 Sorry for closing your issue! 
 But it's more than a week since we haven't received anything from your side 😢 . 
 Come up with new ideas, create a new issue and make sure you finish it within a week! 🔥 
 All the best! 🚀 
 Happy Hacking! 💗

**Comment by kunjgit** [comment]
Hey @vedanshipathak ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
