### ISSUE TITLE
[Bug]: Add copyright label to footer section.

### ISSUE THREAD

**Issue by Suvam3456** [kunjgit/GameZone#3075]
### Give a brief about the bug ✍️

Hello PA,
The footer section of website is missing the copyright label.

### What is the expected behavior? 🤔

We need to add a copyright notice to comply with legal requirements and protect our content.

### Provide step by step information reproduce the bug 📄

I will add a copyright notice similiar to below image of a random website.
![329570271-374c7e13-140d-4ed3-9a97-8ce2095aa90a](https://github.com/kunjgit/GameZone/assets/99579881/296f4eac-fd0a-48d7-9e50-cf081ea80626)

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by Suvam3456** [comment]
Please assign me this issue under GSSOC'24

**Comment by Rish-tech1** [comment]
I would like to work on this issue. Pls assign me this!!

**Comment by Anjankumarkamalapur** [comment]
#3075 I'm really interested in making it more efficient
Please assign me this issue under GSSoC24

**Comment by maniranjan2023** [comment]
Please assign me this issue under GSSOC'24

**Comment by kunjgit** [comment]
Hello @Suvam3456, Time's up!⏰ 
 Sorry for closing your issue! 
 But it's more than a week since we haven't received anything from your side 😢 . 
 Come up with new ideas, create a new issue and make sure you finish it within a week! 🔥 
 All the best! 🚀 
 Happy Hacking! 💗

**Comment by kunjgit** [comment]
Hey @Suvam3456 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
