### ISSUE TITLE
[New game]: Cosmic Blast

### ISSUE THREAD

**Issue by vansh-codes** [kunjgit/GameZone#3076]
### 🎮 Game Request

A game about saving the planet earth from the incoming asteroids by clicking by blasting the asteroids. Asteroids are spawned randomly from the top of the screen and move towards the bottom of the screen where our planet Earth is located. Destroy the asteroids before reaching and colliding with the Earth to increase your score.

### Point down the features

Random spawn of asteroids, on clicking the asteroids, they are blasted increasing the score of the player. Blasting the asteroids everytime gives a background music of blasting. User-friendly addictive game. Can you beat the high score? Let's begin!

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by maverickcodex18** [comment]
Hey mentor, i can complete this task.
I want to know more about your idea so that i can plan my work accordingly

**Comment by vansh-codes** [comment]
> Hey mentor, i can complete this task. I want to know more about your idea so that i can plan my work accordingly

I have already made this game and it is ready to integrate. Would love to collaborate with some new ideas!

**Comment by kunjgit** [comment]
Hey @vansh-codes ! , This issue is already assigned to @vansh-codes. 💗 
 You can work on other issues 🚀 
 If there is anything wrong you can contact us on [Discord🕹️](https://discord.gg/fgwk4XZfxG)👀

**Comment by kunjgit** [comment]
Hey @vansh-codes ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
