### ISSUE TITLE
Sign Up and Login page

### ISSUE THREAD

**Issue by Syed0206** [kunjgit/GameZone#3078]
I would like to add Sign Up and Login Page to the website @kunjgit please assign me this issue under GSSOC'24

**Comment by kunjgit** [comment]
Hey @Syed0206! 🙂 
 It seems like you are not following proper guidelines !! 👀 
 Read documentation properly !!🙏 
 If you have any queries reach out to us on [Discord🕹️](https://discord.gg/fgwk4XZfxG) .

**Comment by kunjgit** [comment]
Hey @Syed0206 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
