### ISSUE TITLE
[New game]: Sudoku

### ISSUE THREAD

**Issue by roysammy123** [kunjgit/GameZone#3079]
### 🎮 Game Request

# Sudoku Game Description

## Game Logic:
Sudoku is a logic-based number puzzle where the objective is to fill a 9x9 grid with digits so that each column, each row, and each of the nine 3x3 subgrids contain all of the digits from 1 to 9. The puzzle starts with some cells filled in with numbers, and the player must fill in the remaining cells while adhering to the rules.

## Sudoku Game Features:
- **Random Puzzle Generation**: Each time the game starts or the player resets the board, a new Sudoku puzzle is randomly generated.
- **Difficulty Levels**: The game offers three difficulty levels (easy, medium, hard) which determine the number of pre-filled cells in the puzzle.
- **Interactive Gameplay**: Players can input their answers by clicking on the cells and typing the numbers from 1 to 9.
- **Solution Checking**: Players can check their solution against the correct solution to determine if they have solved the puzzle correctly.
- **Timer**: The game features a timer that tracks the time taken by the player to solve the puzzle.
- **Reset Board**: Players can reset the board at any time to start a new game or if they want to try a different approach.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by Rish-tech1** [comment]
I would like to work on this issue. Pls assign me this!!

**Comment by ronak187** [comment]
Hey, I would like to tackle up with this issue . I would really appreciate I you would assign me this issue . Moreover I would like you to label it for the levels.

**Comment by Anjankumarkamalapur** [comment]
#3079 I'm really interested in adding up of this sudoku game in this project can you pls assign this work for me.

**Comment by revathishine** [comment]
I would like to work on this issue .I ad worked as a web developer at IITM RESEARCH PARK .With my knowledge i believe that i complte this project.Please assign to me.

**Comment by roysammy123** [comment]
@kunjgit gentle reminder. Please assign me this issue on FCFS basis

**Comment by ananyag309** [comment]
Hi, I hope this message finds you well.

I am writing to express my interest in contributing to the issue. I am enthusiastic about participating in GSSoC'24 and believe that working on this issue will allow me to make a meaningful contribution to the project.

Could you please assign this issue to me under GSSoC'24?

Thank you for considering my request. (also add gssoc label)

**Comment by kunjgit** [comment]
Hello @roysammy123, Time's up!⏰ 
 Sorry for closing your issue! 
 But it's more than a week since we haven't received anything from your side 😢 . 
 Come up with new ideas, create a new issue and make sure you finish it within a week! 🔥 
 All the best! 🚀 
 Happy Hacking! 💗

**Comment by kunjgit** [comment]
Hey @roysammy123 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
