### ISSUE TITLE
[New game]: 2048 game

### ISSUE THREAD

**Issue by Ananya-Bhardwaj** [kunjgit/GameZone#308]
### 🎮 Game Request

Game logic and basic description

2048 is a single-player sliding tile puzzle video game. In this, the player is required to merge tiles with equal numbers which then combine to become a single tile. 

Goal: To merge tiles until the user gets a tile with 2048.

### Point down the features

Tech Stack Used: HTML, CSS, Javascript

Game points
- Single-player game
- Shows current score 
- 2-d layout and UI 

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Ananya-Bhardwaj ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @Ananya-Bhardwaj! 
We are already having a similar game request in #196 👀 
Make sure you come up with a cool unique idea 😀 
 Waiting for your new game idea 💗.

**Comment by Ananya-Bhardwaj** [comment]
Thanks! Will take care in future before raising a issue!
