### ISSUE TITLE
UI enhancement

### ISSUE THREAD

**Issue by dishathakurata** [kunjgit/GameZone#3080]
I can make the website UI look much better and appealing
The search bar and heading are close to each other, where the search bar and  two buttons (Previous and Next) below should be close. The header and contributor sections are one the same page, if they are on different pages that would look better. 

I already started working on these issues. Please assign this to me under GSSoC '24.
And also suggest some more UI enhancement ideas.

**Comment by kunjgit** [comment]
Hey @dishathakurata ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
