### ISSUE TITLE
Adding Home Button: 

### ISSUE THREAD

**Issue by madhurima316** [kunjgit/GameZone#3083]
### Do you want to have the enhancement of existing game ? 😀 Describe yourself..

Some of the games need HOME button for better user experience . 

### Describe the solution you'd like

I would like to add HOME button to all the games , which do not have it .

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @madhurima316! 🙂 
 It seems like you are not following proper guidelines !! 👀 
 Read documentation properly !!🙏 
 If you have any queries reach out to us on [Discord🕹️](https://discord.gg/fgwk4XZfxG) .

**Comment by kunjgit** [comment]
Hey @madhurima316 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by madhurima316** [comment]
Please assign me this issue under GSSoC24.
