### ISSUE TITLE
[Enhancement]: Adding Home button

### ISSUE THREAD

**Issue by madhurima316** [kunjgit/GameZone#3084]
### Do you want to have the enhancement of existing game ? 😀 Describe yourself..

Some of the games need HOME button for better user experience . 

### Describe the solution you'd like

I would like to add HOME button to all the games , which do not have it .

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by madhurima316** [comment]
Please assign me this issue under GSSoC24

**Comment by madhurima316** [comment]
Please assign me this issue under GSSoC24

**Comment by abhishekpandey26** [comment]
please assign this task to me ...

**Comment by Divya-1612-reddy** [comment]
Please assign this task to me

**Comment by GauriGA** [comment]
@kunjgit Could you please assign this issue to me under the GSSOC'24 label?

**Comment by kunjgit** [comment]
Hello @madhurima316, Time's up!⏰ 
 Sorry for closing your issue! 
 But it's more than a week since we haven't received anything from your side 😢 . 
 Come up with new ideas, create a new issue and make sure you finish it within a week! 🔥 
 All the best! 🚀 
 Happy Hacking! 💗

**Comment by kunjgit** [comment]
Hey @madhurima316 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
