### ISSUE TITLE
Dark mode/Light mode functionality

### ISSUE THREAD

**Issue by Ramsey99** [kunjgit/GameZone#3089]
I wan to add dark mode and light mode functionality

**Comment by kunjgit** [comment]
Hey @Ramsey99! 🙂 
 It seems like you are not following proper guidelines !! 👀 
 Read documentation properly !!🙏 
 If you have any queries reach out to us on [Discord🕹️](https://discord.gg/fgwk4XZfxG) .

**Comment by kunjgit** [comment]
Hey @Ramsey99 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
