### ISSUE TITLE
[New game]: Block Ninja

### ISSUE THREAD

**Issue by SumitKumar-17** [kunjgit/GameZone#3090]
### 🎮 Game Request

Game logic and basic description
The Block Nnija game comprises a floating box, in which the user slices the blocks with their fingers. also, it includes some bonus points.

### Point down the features

Game points

1. Block Stacking Mechanics: Players stack blocks strategically to build tall towers, employing physics-based principles to maintain stability.

2. Multiple Game Modes: Offers various modes like endless, timed, and multiplayer, catering to different preferences and providing diverse challenges.

3. Power-Ups and Special Blocks: Introduces power-ups and special blocks for temporary advantages, adding excitement and variety to gameplay.

4. Dynamic Environments: Presents dynamic elements such as moving platforms and rotating obstacles to intensify challenges and keep gameplay engaging.

5. Achievements and Leaderboards: Tracks player progress with achievements and global leaderboards, fostering competition and encouraging players to aim for higher scores.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by SumitKumar-17** [comment]
@kunjgit  I would like to add this game .Could you assign this issue to me

**Comment by kunjgit** [comment]
Hey @SumitKumar-17 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
