### ISSUE TITLE
[Bug]: Favicon missing for Tilting Maze game.

### ISSUE THREAD

**Issue by rahul-p19** [kunjgit/GameZone#3092]
### Give a brief about the bug ✍️

The favicon for the Tilting Maze game doesn't load properly, instead the default favicon for the browser is displayed.

### What is the expected behavior? 🤔

A proper favicon relevant to the game should be displayed.

### Provide step by step information reproduce the bug 📄

type="image/x-icon" -- this attribute is missing in the link statement that is supposed to render the favicon. I will add it and it should work.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @rahul-p19 , You can't have another issue before completing the previous one 😀 
 you already have the following 1 open issues 👀 ! :

#3091

**Comment by kunjgit** [comment]
Hey @rahul-p19 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
