### ISSUE TITLE
Missing Code of Conduct File in Repository

### ISSUE THREAD

**Issue by Ambika03p** [kunjgit/GameZone#3093]
Hey @kunjgit 
Ambika here , Contributor@GSSoc'24
repo currently lacks a codeofconduct.md file, which is an important resource for guiding potential contributors on how to engage with the project effectively. A Code_Of_Conduct.md file outlines the contribution guidelines, coding standards, and procedures for submitting pull requests, thus streamlining the contribution process and ensuring consistency across contributions.

could you please assign this to me ?

**Comment by kunjgit** [comment]
Hey @Ambika03p! 🙂 
 It seems like you are not following proper guidelines !! 👀 
 Read documentation properly !!🙏 
 If you have any queries reach out to us on [Discord🕹️](https://discord.gg/fgwk4XZfxG) .

**Comment by kunjgit** [comment]
Hey @Ambika03p ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
