### ISSUE TITLE
[Bug]: Change Twitter logo to X

### ISSUE THREAD

**Issue by shreyyq** [kunjgit/GameZone#3096]
### Give a brief about the bug ✍️

Description
![ss x](https://github.com/kunjgit/GameZone/assets/77058866/ff39cda5-1fbe-4b7b-a6b8-adaffd365814)

As seen in the screenshot, the twitter logo needs to be updated with X logo. Please assign this issue to me under Gssoc24.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @shreyyq ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by Rish-tech1** [comment]
I would like to work on this issue. Pls assign me this!!

**Comment by abhishekpandey26** [comment]
please assign me this task i have completed the task just need to raise the pr..

**Comment by Divya-1612-reddy** [comment]
Please assign me this issue

**Comment by Paavni-Goyal** [comment]
Hey, I would like to work on the same. Can you please assign this to me.

**Comment by kunjgit** [comment]
Hey @shreyyq ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
