### ISSUE TITLE
[New game]: Bear, Hunter, Ninja

### ISSUE THREAD

**Issue by Niyatizzz** [kunjgit/GameZone#3097]
### 🎮 Game Request

Bear, Hunter, Ninja: In this game, players use the gestures of a bear, a hunter, and a ninja. The rules are as follows:
- Bear beats hunter (bear mauls hunter).
- Hunter beats ninja (hunter shoots ninja).
- Ninja beats bear (ninja kills bear).

### Point down the features

Game points

### Select program in which you are contributing

GSSoC'24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Niyatizzz ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by Niyatizzz** [comment]
Sure! I am happy to contribute under Gssoc'24

**Comment by kunjgit** [comment]
Hey @Niyatizzz ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
