### ISSUE TITLE
[New game]: Bubble Hit #3100

### ISSUE THREAD

**Issue by prachi-kurmi** [kunjgit/GameZone#3098]
### 🎮 Game Request

Game logic and basic description:

The objective of the game, "Bubble Hit," is to pop as many bubbles as possible within a 60-second time limit to earn points.
Bubbles will appear randomly on the screen, and players must click or tap on them to pop them.

### Point down the features

Game points:
1) Time Limit: Built-in 60-second timer adds urgency to gameplay.
2) Scoring System: Earn 10 points per bubble hit, motivating players to achieve high scores.
3) Responsive Design: Compatible with various devices for seamless gaming experience.
4) Visual Feedback: Immediate feedback enhances player engagement.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @prachi-kurmi ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hello @prachi-kurmi, Time's up!⏰ 
 Sorry for closing your issue! 
 But it's more than a week since we haven't received anything from your side 😢 . 
 Come up with new ideas, create a new issue and make sure you finish it within a week! 🔥 
 All the best! 🚀 
 Happy Hacking! 💗

**Comment by kunjgit** [comment]
Hey @prachi-kurmi ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by prachi-kurmi** [comment]
@kunjgit, I apologize for the delay—I had some issues that kept me from contributing on time. This was my first time contributing, and I learned a lot. Thank you for all your support and guidance. 😇

I’m looking forward to bring new ideas in future and will complete them on time. ⏰
