### ISSUE TITLE
[Enhancement]: Mouse Transition Effect on GameZone frontend 

### ISSUE THREAD

**Issue by MitulSonagara** [kunjgit/GameZone#3099]
### Do you want to have the enhancement of existing game ? 😀 Describe yourself..

As GameZone main website frontend is so lightning and colorful. It will look too good if we add some mouse transition effect on whole website. It will look like where ever mouse pointer will go colors of GameZone will flow out from there. Please assign me this issue so that i can start working on this.

### Describe the solution you'd like

I have very good knowledge of mouse trailing effects and also i contributed to many projects in this in different open source contribution. 
I am contributing under GSSOC'24.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @MitulSonagara ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @MitulSonagara ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
