### ISSUE TITLE
[New game]: Typing game

### ISSUE THREAD

**Issue by vaishnavi-3969** [kunjgit/GameZone#31]
### 🎮 Game Request

Game logic and basic description
1. The game randomly selects a word from an array of words.
2. The selected word is displayed on the screen.
3. Players need to type the displayed word accurately and quickly.
4. If the typed word matches the displayed word, the player earns a point, and a new word is shown.
5. If the typed word is incorrect, no points are awarded, and the player can try again.
6. The game has a countdown timer, and players must complete as many words as possible within the given time limit.
7. After the timer reaches zero, the game ends, and the player's score is displayed.

The Typing Game is a fast-paced typing challenge where players test their typing skills and speed. Words are displayed on the screen, and players must accurately type each word within a limited time frame. The goal is to type as many words as possible before the time runs out.

To start the game, players are presented with a word and a text input field. As they type, the game checks if the typed word matches the displayed word. If the typed word is correct, the player earns a point, and a new word is shown. If the typed word is incorrect, no points are awarded, and the player can try again.

The game features a countdown timer that adds excitement and urgency. Players must complete as many words as possible before the timer reaches zero. Once the timer runs out, the game ends, and the player's final score is displayed.

The Typing Game is a great way to improve typing speed, accuracy, and concentration. It provides a challenging and engaging experience for players of all skill levels.

Languages: HTML, CSS, JS

### Point down the features

Game points
Features of the Game:

Word Selection: The game randomly selects words from an array, ensuring a varied and challenging experience for each playthrough.
Typing Accuracy: The player's accuracy is crucial in earning points. Only correctly typed words are counted towards the score.
Speed Challenge: The game encourages players to type quickly to maximize their score before the timer runs out.
Countdown Timer: A visible timer adds excitement and a sense of urgency, increasing the challenge and intensity of the game.
Score Tracking: The game keeps track of the player's score, incrementing it for each correctly typed word.
Feedback System: The game provides immediate feedback, indicating whether the typed word is correct or incorrect.
Dynamic Gameplay: With each correctly typed word, a new word is displayed, maintaining an engaging and continuously changing experience.
Final Score Display: After the timer reaches zero, the player's final score is prominently shown, allowing them to assess their performance.
Replayability: The game is designed for repeated play, allowing players to challenge themselves and improve their typing skills over time.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @vaishnavi-3969  ! Thank you for raising an issue 💗 You have been assigned this issue you can start working on the issue 🎮

**Comment by kunjgit** [comment]
Hello @vaishnavi-3969, Time's Uppp!⏰ 
 Sorry for closing your issue! 
 But it's more than a week since we haven't received anything from your side 😢 . 
 Come up with new ideas, create a new issue and make sure you finish it within a week! 🔥 
 All the best! 🚀 
 Happy Hacking! 💗

**Comment by kunjgit** [comment]
Hey @vaishnavi-3969 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
