### ISSUE TITLE
[Enhancement]: Hover Effect on Game cards

### ISSUE THREAD

**Issue by MitulSonagara** [kunjgit/GameZone#3100]
### Do you want to have the enhancement of existing game ? 😀 Describe yourself..

Currently all the game cards are stable on hover any border lightings are not there.

### Describe the solution you'd like

I will add hover effect on the game card which will look like search bar outline on hover. By doing this it will match the allover UI of GameZone website.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @MitulSonagara , You can't have another issue before completing the previous one 😀 
 you already have the following 1 open issues 👀 ! :

#3099

**Comment by kunjgit** [comment]
Hey @MitulSonagara ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by kunjgit** [comment]
Hey @MitulSonagara ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)
