### ISSUE TITLE
[Enhancement]: Keyboard Event Listener for Smooth Music Playback

### ISSUE THREAD

**Issue by shubhanshukaintura** [kunjgit/GameZone#3102]
### Do you want to have the enhancement of existing game ? 😀 Describe yourself..

Currently, our game requires users to move the mouse cursor to trigger music playback, which can disrupt the flow of gameplay. To address this, I suggest implementing a keyboard event listener that allows users to play music seamlessly without the need to interact with the mouse.

By adding this feature, players can enjoy uninterrupted gameplay while effortlessly controlling the music using keyboard buttons. This enhancement not only enhances user convenience but also contributes to a smoother and more immersive gaming experience overall.

### Describe the solution you'd like

1. First, I will add event listeners for specific keyboard buttons (e.g., spacebar, enter key) in the game's codebase. These event listeners will detect when the designated keys are pressed by the user.

2. Next, I will integrate the functionality to play music within the game. This may involve creating a function or method specifically for music playback, or utilizing existing audio-related features within the game's code.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by shubhanshukaintura** [comment]
Please assign me this issue under GSSoC24

**Comment by kunjgit** [comment]
Hey @shubhanshukaintura ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by Suryapratapsingh26** [comment]
I want to work on this issue under GSSOC 2024. Assign me this

**Comment by kunjgit** [comment]
Hello @shubhanshukaintura, Time's up!⏰ 
 Sorry for closing your issue! 
 But it's more than a week since we haven't received anything from your side 😢 . 
 Come up with new ideas, create a new issue and make sure you finish it within a week! 🔥 
 All the best! 🚀 
 Happy Hacking! 💗

**Comment by kunjgit** [comment]
Hey @shubhanshukaintura ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
