### ISSUE TITLE
[Bug]: No custom 404 page

### ISSUE THREAD

**Issue by Programmer-Arvind** [kunjgit/GameZone#3104]
### Give a brief about the bug ✍️

Currently, there is no custom 404 page. The 404 page that comes on manipulating the url results in a github default 404 page.

### What is the expected behavior? 🤔

It is expected to provide a custom 404 page with a random game recommendation.

### Provide step by step information reproduce the bug 📄

Manipulate the URL for example go to https://kunjgit.github.io/GameZone/jk
![image](https://github.com/kunjgit/GameZone/assets/96773379/f1e02b01-bdb0-4798-a9bb-97fee4d47a43)
You will see this which is not very good.
Say if someone sends a link to a friend with wrong spelling then the friend might think the whole website is down which might not be the case and he will exit the website not looking at any other games.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Programmer-Arvind ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by Programmer-Arvind** [comment]
Can you please assign the level 1,2, 3 label for this issue?

**Comment by AmrutaJayanti** [comment]
Could You please assign me this task @kunjgit

**Comment by Programmer-Arvind** [comment]
@AmrutaJayanti I am working on it already

**Comment by Programmer-Arvind** [comment]
Please assign the level 1,2, 3 label for this issue so I could complete this issue.

**Comment by kunjgit** [comment]
Hello @Programmer-Arvind, Time's up!⏰ 
 Sorry for closing your issue! 
 But it's more than a week since we haven't received anything from your side 😢 . 
 Come up with new ideas, create a new issue and make sure you finish it within a week! 🔥 
 All the best! 🚀 
 Happy Hacking! 💗

**Comment by kunjgit** [comment]
Hey @Programmer-Arvind ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
