### ISSUE TITLE
Too much space between the hero section and the games section

### ISSUE THREAD

**Issue by r7projects-shayan** [kunjgit/GameZone#3105]
##Issue Description

There is too much space between the first heading and the games section 

This causes inconsistency in the website and may limit user reach by repelling users away from it. At first glance it seems like a blank website

##Steps to Reproduce

Lower the gap between the hero section heading and the next section of games

Bring the search bar a bit closer to the heading so that users can see it as the first thing when they visit the website.

##Screenshots

![Screenshot 2024-05-11 132510](https://github.com/kunjgit/GameZone/assets/167475552/726a47a4-d843-4f3c-b8d0-9961e5644881)

**Comment by kunjgit** [comment]
Hey @r7projects-shayan ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by r7projects-shayan** [comment]
@kunjgit Kindly assign this issue to me. As a full Stack developer I can fix this issue and some other issues mentioned as well

**Comment by kunjgit** [comment]
Hey @r7projects-shayan! 🙂 
 It seems like you are not following proper guidelines !! 👀 
 Read documentation properly !!🙏 
 If you have any queries reach out to us on [Discord🕹️](https://discord.gg/fgwk4XZfxG) .

**Comment by kunjgit** [comment]
Hey @r7projects-shayan ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
