### ISSUE TITLE
[Bug]: There is too much space between the hero section and the games section

### ISSUE THREAD

**Issue by r7projects-shayan** [kunjgit/GameZone#3107]
### Give a brief about the bug ✍️

There is too much space between the first heading in the website and the games section. This causes inconsistency between the users, since the first thing that they see is a blank website. 

### What is the expected behavior? 🤔

The gap should be a bit less so that the search bar for the games is visible.

### Provide step by step information reproduce the bug 📄

Lower the gap between the hero section and the games section. 

The search bar for the games should be visible on the first visit of the website

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @r7projects-shayan ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by Divya-1612-reddy** [comment]
please assign me this issue

**Comment by shnwz-solves** [comment]
Hey PA, I would like to work on this issue. Please assign it to me. Thankyou!
![Screenshot 2024-05-12 115536](https://github.com/kunjgit/GameZone/assets/126380641/df405cd4-563f-4b3e-a385-821608d34401)

**Comment by kunjgit** [comment]
Hey @r7projects-shayan ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
