### ISSUE TITLE
[Enhancement]: Update in Alphabet_Learning_Game

### ISSUE THREAD

**Issue by Singh-Divyansh** [kunjgit/GameZone#3108]
### Do you want to have the enhancement of existing game ? 😀 Describe yourself..

i want to enhance the "Alphabet_Learning_Game",mainly script.js file. there are many deprecated functions and the code has repeated lines which i will optimize

### Describe the solution you'd like

I would firstly update the deprecated functions with the active ones. then after i would try to optimize the code for redudancy.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Singh-Divyansh ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by ronak187** [comment]
Hey, I would like to tackle up with this issue . I would really appreciate I you would assign me this issue . Moreover I would like you to label it for the levels.

**Comment by kunjgit** [comment]
Hey @Singh-Divyansh ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
