### ISSUE TITLE
[Enhancement]: UI improvement according to UI/UX principles.

### ISSUE THREAD

**Issue by shaurya35** [kunjgit/GameZone#3110]
### Do you want to have the enhancement of existing game ? 😀 Describe yourself..

**Proposals:**

```
- Improvement in overall UI.
- Add margin and Padding wherever required.
- Change the color scheme.
- Add sufficient whitespace for better user experiene.
```

### Describe the solution you'd like

_**Pros:**_ 

- Fully optimized website for all devices.
- Increase in SEO ranking.

_**Cons:**_

- Can take some time to implement.
- Some properties needs to be fully changed to optimize some particular sections including font units etc.

### Select program in which you are contributing

Gssoc

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @shaurya35 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by shaurya35** [comment]
Hi @kunjgit 
Thanks for the information.
I request you to assign the `gssoc` and `level` labels so that I can start working according to the guidelines provided by Gssoc

**Comment by kunjgit** [comment]
Hello @shaurya35, Time's up!⏰ 
 Sorry for closing your issue! 
 But it's more than a week since we haven't received anything from your side 😢 . 
 Come up with new ideas, create a new issue and make sure you finish it within a week! 🔥 
 All the best! 🚀 
 Happy Hacking! 💗

**Comment by kunjgit** [comment]
Hey @shaurya35 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
