### ISSUE TITLE
[New game]: Simonsays2.0(enhanced UI and memes  sound effects)

### ISSUE THREAD

**Issue by pandeyji711** [kunjgit/GameZone#3113]
### 🎮 Game Request

Simon Says Game Description The Simon Says Game is a classic memory game where players must repeat a sequence of colors in the same order as presented by the game. It's a fun way to challenge your memory skills and enjoy some nostalgic gameplay.

Installation: To play the Simon Says Game, simply clone this repository to your local machine or download the ZIP file. Then, open the index.html file in your web browser. Usage Once you've opened the game in your browser, click the "Start" button to begin. Simon will show a sequence of colors by lighting up the corresponding buttons. Pay close attention to the sequence! After Simon has finished, it's your turn to repeat the sequence by clicking the buttons in the same order. If you succeed, Simon will add another color to the sequence and the game continues. If you make a mistake, Simon will let you know and the game will restart.

Features: Classic Simon Says gameplay Colorful and engaging user interface Sound effects to enhance the gaming experience Contributing Contributions to the Simon Says Game are welcome! If you'd like to contribute, please follow these steps:

### Point down the features

**Each Correct Sequence**: You earn one point for every sequence that you correctly replicate.

**Increasing Difficulty:** Each round, the sequence becomes longer and more complex, increasing the difficulty and the potential to score more points as you progress

**High Score Tracking:** Some versions of the game may keep track of the high score, which is updated if the game that just ended had the largest sequence of correct matches since the game was turned  on.

Remember, the key to scoring high in Simon Says is a good memory and quick reflexes to match the sequences accurately as they get longer. Keep practicing, and you might just set a new high score! Good luck! 🌟

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @pandeyji711 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by pandeyji711** [comment]
thankyou fo assining ,please lable Gssoc 2024

**Comment by kunjgit** [comment]
Hey @pandeyji711 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by pandeyji711** [comment]
add lable Gssoc2024

**Comment by kunjgit** [comment]
Hey @pandeyji711 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
