### ISSUE TITLE
[Enhancement]: Whack-a-Mole

### ISSUE THREAD

**Issue by AtharvaShinde253** [kunjgit/GameZone#3116]
### Do you want to have the enhancement of existing game ? 😀 Describe yourself..

It has a very simle UI.I can make it more attractive and add tiles from which the mole and piranha plants appear .So when you click on the plant the game is lost .

### Describe the solution you'd like

I can ad 9 tiles/buckets form which the mole and the piranha plant will peak .I can add an interactive UI which will enable users to enjoy it more.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @AtharvaShinde253 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @AtharvaShinde253 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
