### ISSUE TITLE
Increasing the Gap between Icons

### ISSUE THREAD

**Issue by lodhivishalcoder28** [kunjgit/GameZone#3117]
### Do you want to have the enhancement of existing game ? 😀 Describe yourself..

The spacing between icons is very less, by increasing the gap between the icons will make the website more impressive and better looking , also the spacing around the icons is less. So need to Increasing the spacing. 

I would like to resolve this issue , as a GSSoc'24 contributor

![Screenshot 2024-05-11 144641](https://github.com/kunjgit/GameZone/assets/145546912/b7be2197-926d-47ae-9295-74943b7e065c)

### Describe the solution you'd like

Increasing the Spacing between icons will resolve the issue. 

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @lodhivishalcoder28 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @lodhivishalcoder28! 🙂 
 It seems like you are not following proper guidelines !! 👀 
 Read documentation properly !!🙏 
 If you have any queries reach out to us on [Discord🕹️](https://discord.gg/fgwk4XZfxG) .

**Comment by kunjgit** [comment]
Hey @lodhivishalcoder28 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
