### ISSUE TITLE
[Enhancement]: Snake Game not working.

### ISSUE THREAD

**Issue by karishmaaa101** [kunjgit/GameZone#3118]
### Do you want to have the enhancement of existing game ? 😀 Describe yourself..

Game enhancement
The snake game is not working.You can hear the background music and instructions are given,but you cannot see the **SNAKE**

### Describe the solution you'd like

Solution steps
The snake must be visible in the game.Because ultimately it is the snake's game.

![image](https://github.com/kunjgit/GameZone/assets/104766763/c08b0560-37d5-48c9-bb6c-f39fef2216e4)

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @karishmaaa101 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @karishmaaa101 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
