### ISSUE TITLE
[Enhancement]: 

### ISSUE THREAD

**Issue by VesperAkshay** [kunjgit/GameZone#3122]
### Description
The website currently has an outdated and non-responsive user interface (UI). We need to redesign the UI to be modern, visually appealing, and fully reactive to provide a seamless experience across different devices and screen sizes.

In addition to the UI overhaul, we also require the implementation of extra functionality to enhance the user experience and add new features to the website.

### Describe the solution you'd like

Solution steps

### Objectives
1. **Redesign the UI**:
   - Create a new, visually appealing design for the website's UI.
   - Ensure the UI is fully responsive and adapts to different screen sizes and devices.
   - Improve the overall user experience and ease of navigation.

2. **Implement Extra Functionality**:
   - Identify and prioritize additional features that can enhance the website's capabilities.
   - Implement the identified extra functionality to expand the website's offerings.
   - Ensure the new functionality is seamlessly integrated with the existing system.

### Acceptance Criteria
- The new UI design is modern, visually appealing, and responsive across all devices.
- The website's navigation and user experience are significantly improved.
- The identified extra functionality is successfully implemented and integrated with the existing system.
- The website's overall performance and user satisfaction are enhanced.

### Tasks
1. Research and analyze the current UI and user experience.
2. Develop a new UI design concept and mockups.
3. Implement the new UI design using the latest front-end technologies.
4. Ensure the UI is fully responsive and adapts to different screen sizes.
5. Identify and prioritize the extra functionality requirements.
6. Implement the prioritized extra functionality.
7. Test the new UI and extra functionality thoroughly.
8. Deploy the updated website to the production environment.

### Timeline
- UI redesign: 4 weeks
- Extra functionality implementation: 6 weeks
- Testing and deployment: 2 weeks

### Labels
- `enhancement`
- `frontend`
- `GSsoc`

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @VesperAkshay ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @VesperAkshay ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
