### ISSUE TITLE
[Enhancement]: Tower of Hanoi UI improvement

### ISSUE THREAD

**Issue by triggereddown** [kunjgit/GameZone#3123]
### Do you want to have the enhancement of existing game ? 😀 Describe yourself..

Game enhancement: 
1. UI needs improvement for users to get good feel
2. Font style can be improved 
3. Spacing between the play button and bottom footer is not proper and can be optimised

### Describe the solution you'd like

Solution steps
1. Improve UI design for better user experience.
2. Enhance text fonts for readability.
3. Add  spacing between "Play Game" button and bottom footer  for easy access.
I'm willing to contribute to these enhancements.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @triggereddown ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @triggereddown ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by kunjgit** [comment]
Hey @triggereddown ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
