### ISSUE TITLE
[Bug]: Whack a Hole - Game Button Functionality and Styling Issue

### ISSUE THREAD

**Issue by Sujith-Srikar** [kunjgit/GameZone#3124]
## Description

The game button functionality in the "Whack a Hole" game is not working properly. Specifically, during the game start, both the game button and pause buttons are unresponsive. Additionally, when clicking on the buttons, there is stretching observed in the interface.

## Expected Behavior

* The game button should start the game when clicked.
* The pause button should pause the game when clicked.
* Clicking on any button should not cause any stretching or distortion in the interface.

## Priority:
This issue is affecting the usability and functionality of the game, so it should be addressed with high priority.

## Labels:

* bug
* game
* interface
* usability

### Provide step by step information reproduce the bug 📄

Video Preview

https://github.com/kunjgit/GameZone/assets/136736119/2ad2ac84-7f3b-4067-a354-2a0d0f8bf70f

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Sujith-Srikar ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @Sujith-Srikar ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
