### ISSUE TITLE
Contra

### ISSUE THREAD

**Issue by Pragyan004** [kunjgit/GameZone#3125]
### 🎮 Game Request

we all know what contra is or the people who has played this legendary game knows how exciting and fun it was to play in our small console that we have to connect to our old CRT tv's, I want to build the game or the objective is to bring out that nostalgic feeling to the millenniums to bring their memories back and want  to give this current generation an experience what it was to play games like that

### Point down the features

So coming to the features of this game, the appearance and feel would be same as the original one (not violating any emotions)but would include some modern touches , like upgrading the arsenal/weapons, give checkpoints so that we don't have to play from the very start,(old one gives this pain😭) and include some powerups to give it a modern feel , and some miscellaneous items

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Pragyan004 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @Pragyan004! 🙂 
 It seems like you are not following proper guidelines !! 👀 
 Read documentation properly !!🙏 
 If you have any queries reach out to us on [Discord🕹️](https://discord.gg/fgwk4XZfxG) .

**Comment by kunjgit** [comment]
Hey @Pragyan004 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by Pragyan004** [comment]
> Hey @Pragyan004! 🙂 It seems like you are not following proper guidelines !! 👀 Read documentation properly !!🙏 If you have any queries reach out to us on [Discord🕹️](https://discord.gg/fgwk4XZfxG) .
