### ISSUE TITLE
Simon_Game_Challenge[Enhancement]: 

### ISSUE THREAD

**Issue by Ancha2003** [kunjgit/GameZone#3126]
### Do you want to have the enhancement of existing game ? 😀 Describe yourself..

It should be in only one page because the starting button is very small in it, so it is not visible.

### Describe the solution you'd like

add  height : 100vh;
increase Start button size

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Ancha2003 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by 6388387145** [comment]
I would like to work on this issues.

**Comment by T1rth1** [comment]
i would like to work upon this issue..so can you please assign me because i had made this game already so i guess i would be best fit for solving this issue
Thank you @kunjgit

**Comment by Anushk255** [comment]
I would like to work on this issues.so please assign me.

**Comment by kunjgit** [comment]
Hey @Ancha2003 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
