### ISSUE TITLE
[New game]: Catch_The_Colour

### ISSUE THREAD

**Issue by pandeyji711** [kunjgit/GameZone#3127]
### 🎮 Game Request

the colour are falling from top , your task is to match the falling colour in its colour basket .

### Point down the features

**Scoring System:** Each successful basket scores you 1 point.

**Level Advancement:** For every 10 points you score, you’ll advance to the next level. As you level up, the speed of the descending colors will increase, challenging you to keep up with the pace.

**Objective:** The game is designed to test and improve your reaction time and mental focus.

Wishing you the best of luck—enjoy the challenge!

I would like to take ownership of this issue as a contributor for GSSoC 2024. Please consider assigning it to me. Thank you!
![Screenshot 2024-05-11 164741](https://github.com/kunjgit/GameZone/assets/154527778/1aa2cf9a-aa0d-4de2-a508-562968addd1a)

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @pandeyji711 , You can't have another issue before completing the previous one 😀 
 you already have the following 1 open issues 👀 ! :

#3113

**Comment by kunjgit** [comment]
Hey @pandeyji711 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by kunjgit** [comment]
Hey @pandeyji711 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by pandeyji711** [comment]
I have completed privious one please assign this to me
under Gssoc 24
