### ISSUE TITLE
[New game]: StackUp

### ISSUE THREAD

**Issue by Github-RiyaGupta** [kunjgit/GameZone#3128]
### 🎮 Game Request

The objective of the game "StackUp" is to stack the blocks on top of each other in such a way that you reach to the pinnacle by getting one on the top of another and secure a win.

### Point down the features

1. The blocks will be rolling down freely in horizontal manner you have to be specific with the time and put them up on each other.
2. No time limit.
3. If not be able to put the block on the lower one then "GAME OVER".

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Github-RiyaGupta ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by Github-RiyaGupta** [comment]
please add GSSOC label too.

**Comment by kunjgit** [comment]
Hello @Github-RiyaGupta, Time's up!⏰ 
 Sorry for closing your issue! 
 But it's more than a week since we haven't received anything from your side 😢 . 
 Come up with new ideas, create a new issue and make sure you finish it within a week! 🔥 
 All the best! 🚀 
 Happy Hacking! 💗

**Comment by kunjgit** [comment]
Hey @Github-RiyaGupta ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
