### ISSUE TITLE
[New game]: Catch_The_Colour

### ISSUE THREAD

**Issue by pandeyji711** [kunjgit/GameZone#3129]
### 🎮 Game Request

🎮 Game Request
the colour are falling from top , your task is to match the falling colour in its colour basket .
 if you fail to do so Game over !!

![Screenshot 2024-05-11 164741](https://github.com/kunjgit/GameZone/assets/154527778/1f948d65-a0e7-4716-ae13-fe72d61de48b)

### Point down the features

**Scoring System**: Each successful basket scores you 1 point.

**Level Advancement:** For every 10 points you score, you’ll advance to the next level. As you level up, the speed of the descending colors will increase, challenging you to keep up with the pace.

**Objective**: The game is designed to test and improve your reaction time and mental focus.

Wishing you the best of luck—enjoy the challenge!
I would like to take ownership of this issue as a contributor for GSSoC 2024. Please consider assigning it to me. Thank you!

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @pandeyji711 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hello @pandeyji711, Time's up!⏰ 
 Sorry for closing your issue! 
 But it's more than a week since we haven't received anything from your side 😢 . 
 Come up with new ideas, create a new issue and make sure you finish it within a week! 🔥 
 All the best! 🚀 
 Happy Hacking! 💗

**Comment by kunjgit** [comment]
Hey @pandeyji711 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
