### ISSUE TITLE
[New game]: Dinosaur jump 

### ISSUE THREAD

**Issue by Abhinavcode13** [kunjgit/GameZone#313]
### 🎮 Game Request

Game logic and basic description

The game consist of a dinosaur who is running and escape from different objects.

### Point down the features

Game points
It is rating based game and calculates the high score of individual.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Abhinavcode13 👋!
 
  @kunjgit here, 
 We have this annoucement to make 📢!! 
 During the time of PR don't alter main index file ! 🙂 
 In main Readme file just use * as a game number during the time we are merging we will add number !! 👀 
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG) if you haven't 😇 
  Thank you 💗!

**Comment by Abhinavcode13** [comment]
can you assign me this??

**Comment by Abhinavcode13** [comment]
@kunjgit

**Comment by Charu-2718** [comment]
Can I work on this issue as a contributor under GSSoC23?

**Comment by Lavesh12** [comment]
Hello,
I hope you're doing well. I am interested in contributing to this project as part of GSSoC. It aligns with my skills and interests, and I believe I can make a meaningful contribution to the project Could you please assign this task to me? 
Looking forward to hearing from you.
Thank you,
Lavesh Vishwakarma

**Comment by Abhinavcode13** [comment]
I'm already working on it guys chill
