### ISSUE TITLE
[New game]: DotConnect

### ISSUE THREAD

**Issue by shambhaveesrivastava12** [kunjgit/GameZone#3131]
### 🎮 Game Request

DotConnect is a captivating puzzle game that challenges players to connect dots without crossing lines. The objective is simple: fill the entire game board by connecting all the dots in a continuous path

### Point down the features

-> Using HTML,CSS and Javascript
-> Dot graph
-> At most two players can play
-> The user has to make order of 4
-> The order can be created in any direction(top,bottom,left,right)

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @shambhaveesrivastava12 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @shambhaveesrivastava12 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
