### ISSUE TITLE
[New game]: carrom 

### ISSUE THREAD

**Issue by harsh160311** [kunjgit/GameZone#3132]
### 🎮 Game Request

Game logic and basic description
[README.md](https://github.com/kunjgit/GameZone/files/15283226/README.md)

### Point down the features

Game points 
[README.md](https://github.com/kunjgit/GameZone/files/15283224/README.md)

### Select program in which you are contributing

GSSoC24            can assign me the project

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @harsh160311 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by harsh160311** [comment]
assign

**Comment by harsh160311** [comment]
assign nhi hua app kr do

**Comment by kunjgit** [comment]
Hello @harsh160311, Time's up!⏰ 
 Sorry for closing your issue! 
 But it's more than a week since we haven't received anything from your side 😢 . 
 Come up with new ideas, create a new issue and make sure you finish it within a week! 🔥 
 All the best! 🚀 
 Happy Hacking! 💗
