### ISSUE TITLE
[New game]: Mancala

### ISSUE THREAD

**Issue by manishh12** [kunjgit/GameZone#3136]
### 🎮 Game Request

Game logic and basic descriptionMancala is a two-player board game that has been played for centuries across various cultures. The game typically consists of a wooden board with 12 small pits or cups, arranged in two rows, with a larger scoring pit at each end called the "mancala". Each player controls the six cups on their side of the board, and the goal is to collect the most stones or seeds in your mancala by the end of the game.

### Point down the features

Game points
Multiplayer modes
Engaging visuals and animations

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @manishh12 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @manishh12 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
