### ISSUE TITLE
[Enhancement]: Vault master game need a proper instruction of how to play. and a better background.

### ISSUE THREAD

**Issue by Nehayp21242929** [kunjgit/GameZone#3137]
### Do you want to have the enhancement of existing game ? 😀 Describe yourself..

Game enhancement: I think we can improve this game by adding some instructions of how to play and adding a appealing background. please assign this task to me, I will make this game exceptional.

### Describe the solution you'd like

Solution steps

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Nehayp21242929 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)
