### ISSUE TITLE
[Enhancement]: Simon Game Enhancement

### ISSUE THREAD

**Issue by T1rth1** [kunjgit/GameZone#3145]
### Do you want to have the enhancement of existing game ? 😀 Describe yourself..

In simon game i added the functionality when user press any key then game automatically start and when user guess the wrong square then beep the buzzer with red background effect and game stop and tell user to press any key to restart.

### Describe the solution you'd like

I already created this game..as per the steps needed to enhance this game

### Select program in which you are contributing

GSSOC'24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @T1rth1 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by T1rth1** [comment]
okay so i would like to work upon this issue..so can you please assign me because i had made this game already so i guess i would be best fit for solving this issue 
thank you @kunjgit

**Comment by T1rth1** [comment]
hello sir.. i have solved this problem and enhance the GUI..but it show this erro when i try to create a pull request
remote: Permission to kunjgit/GameZone.git denied to T1rth1.
fatal: unable to access 'https://github.com/kunjgit/GameZone.git/': The requested URL returned error: 403
so can you please tell me why is this error?

**Comment by kunjgit** [comment]
Hey @T1rth1 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
