### ISSUE TITLE
[New game]: Puzzle Slider

### ISSUE THREAD

**Issue by HIMANSHU00KUMAR** [kunjgit/GameZone#315]
### 🎮 Game Request

Puzzle Slider is a game where players rearrange scrambled puzzle pieces to form a complete image. The game starts with a shuffled grid of puzzle pieces, and players can slide adjacent pieces to empty spaces until the original image is restored. The objective is to solve the puzzle in the fewest number of moves or within a given time limit. JavaScript handles the logic of checking for a solved puzzle and tracking the number of moves or time taken. Tailwind CSS can be used to style the game interface.
tech use:html,tailwind,javascript

### Point down the features

Create a sliding puzzle game where players rearrange scrambled pieces to form a complete image.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @HIMANSHU00KUMAR ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @HIMANSHU00KUMAR 👋!
 
  @kunjgit here, 
 We have this annoucement to make 📢!! 
 During the time of PR don't alter main index file ! 🙂 
 In main Readme file just use * as a game number during the time we are merging we will add number !! 👀 
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG) if you haven't 😇 
  Thank you 💗!

**Comment by kunjgit** [comment]
Hello @HIMANSHU00KUMAR, Time's Uppp!⏰ 
 Sorry for closing your issue! 
 But it's more than a week since we haven't received anything from your side 😢 . 
 Come up with new ideas, create a new issue and make sure you finish it within a week! 🔥 
 All the best! 🚀 
 Happy Hacking! 💗

**Comment by kunjgit** [comment]
Hey @HIMANSHU00KUMAR ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
