### ISSUE TITLE
[Documentation Bug]: Adventure_Game

### ISSUE THREAD

**Issue by Bindusree1515** [kunjgit/GameZone#3150]
### Describe the bug ✍️

The image is not getting displayed in the README file, instead it is displaying code.
Here is the image of it:
![image](https://github.com/kunjgit/GameZone/assets/91887086/cf2b4bde-21e3-48e9-b549-d480a896782d)

### Provide step by step information reproduce the bug 📄

1. Go through the Adventure_Game README file.
2. Scroll down you can find the bug.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by Bindusree1515** [comment]
I want to work on this issue, please assign this issue to me.

**Comment by kunjgit** [comment]
Hey @Bindusree1515 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by Bindusree1515** [comment]
i solved #3151 sir
please check and approve sir.

**Comment by kunjgit** [comment]
Hey @Bindusree1515 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
