### ISSUE TITLE
[Bug]:  Input Box 

### ISSUE THREAD

**Issue by sivaprasath2004** [kunjgit/GameZone#3154]
### Give a brief about the bug ✍️

- The search box not be proper to the `placeholder` and Entered text  can be align  nearby center.
- Right side can many more of the spaces.

### What is the expected behavior? 🤔

- The `input` element can be left side align `1rem` space expected the solution.

### Provide step by step information reproduce the bug 📄

![Screenshot from 2024-05-12 08-59-01](https://github.com/kunjgit/GameZone/assets/121082414/998b2f35-db7a-495f-8cf1-6b1c859c7d2e)

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @sivaprasath2004 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by sivaprasath2004** [comment]
@kunjgit please assign me...

**Comment by anshdeep0504** [comment]
Hey, allow me to work on this under GSSOC' 2024

**Comment by maniranjan2023** [comment]
@kunjgit please assign me...

**Comment by kunjgit** [comment]
Hey @sivaprasath2004 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
