### ISSUE TITLE
[New game]: Pop My Balloon

### ISSUE THREAD

**Issue by Nayanika1402** [kunjgit/GameZone#3155]
### 🎮 Game Request

Game logic and basic description:The basic concept of the game is that there will be a range of numbers from which players can choose a number. If the manage to guess the randomly chosen number, the balloon will pop and they lose. If they manage to avoid the lucky number, the range decreases such that their guess either becomes the new lower bound or new upper bound, and the balloon inflates just a little bit more.

### Point down the features

Game points:
Easy Level: The range starts off as 0-100 and players can guess any number within the range.
Harder Level: The range starts off as 0-84, and players can only guess numbers that are either from the lower bound (LB) to LB+12 or from the upper bound (UB) to UB-12.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Nayanika1402 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by Nayanika1402** [comment]
@kunjgit Kindly assign me this task.

**Comment by kunjgit** [comment]
Hey @Nayanika1402 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
