### ISSUE TITLE
[Documentation Bug]: Aim_Training

### ISSUE THREAD

**Issue by Bindusree1515** [kunjgit/GameZone#3156]
### Describe the bug ✍️

In the README.md file of Aim_Training game instead of screenshot code is placed.
please assign me this issue to work under gssoc'24.
here is the screenshot:
![image](https://github.com/kunjgit/GameZone/assets/91887086/12a8e7cb-e602-445a-852d-eb549e5436f8)

### Provide step by step information reproduce the bug 📄

1. Go to the README.md file.
2. check the screenshot section.
3. Resolve the issue

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Bindusree1515 , You can't have another issue before completing the previous one 😀 
 you already have the following 1 open issues 👀 ! :

#3150

**Comment by kunjgit** [comment]
Hey @Bindusree1515 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by kunjgit** [comment]
Hey @Bindusree1515 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by Bindusree1515** [comment]
@kunjgit sir I have made the pull request for my previous issue, i solved it. But it was not merged.

> Hey @Bindusree1515 , You can't have another issue before completing the previous one 😀 you already have the following 1 open issues 👀 ! :
> 
> #3150

**Comment by Bindusree1515** [comment]
Hello Sir,

I issue was closed telling that I can't raise an issue without clearing the
before issue, but I resolved it and also I made a pull request.

Can I please know why the issue was closed ?
I am unable to raise another issues when though I resolved previous issues
by making pull requests.

Please help me out sir.

Thank you !
