### ISSUE TITLE
[Enhancement]: Fruit Ninja Game Styling and Interface Fixing

### ISSUE THREAD

**Issue by T1rth1** [kunjgit/GameZone#3157]
### Do you want to have the enhancement of existing game ? 😀 Describe yourself..

When user clicked on the game from the Home page he/she head over to the page then there is no logo is visible and also the alignment of the all items are not quite good yet
Also when game starts, that page's css should also change to make it's more attractive and user friendly

### Describe the solution you'd like

1. Change the Dashboard page of the game ( Alignment, styling etc...)
2. Change the CSS of the game ( Like background color, font color, font style, etc...)

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @T1rth1 , You can't have another issue before completing the previous one 😀 
 you already have the following 1 open issues 👀 ! :

#3145

**Comment by kunjgit** [comment]
Hey @T1rth1 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by kunjgit** [comment]
Hey @T1rth1 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by T1rth1** [comment]
okay sir @kunjgit 
Thanks for Informing me
