### ISSUE TITLE
[Bug]: User navigation missing in hero section

### ISSUE THREAD

**Issue by shnwz-solves** [kunjgit/GameZone#3160]
### Give a brief about the bug ✍️

Description:
When a user visits this page, they may not be able to find the game section. So there needs to be one button or nav link so that users can easily go to gamezone.

### What is the expected behavior? 🤔

Description:
It should show users a button or a card like link to navigate to game zone.

### Provide step by step information reproduce the bug 📄

Description:
When a user visits the website, it shows a blank website with game zone and an icon in left, so users may get confused.
This needs to be fixed by adding a button on the hero section, also we can integrate navbar(if PA allows me) to make it User friendly.

### Screenshot

![Screenshot 2024-05-12 115536](https://github.com/kunjgit/GameZone/assets/126380641/3611258d-6c48-4929-b4b7-252b6b81e40b)

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @shnwz-solves ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hello @shnwz-solves, Time's up!⏰ 
 Sorry for closing your issue! 
 But it's more than a week since we haven't received anything from your side 😢 . 
 Come up with new ideas, create a new issue and make sure you finish it within a week! 🔥 
 All the best! 🚀 
 Happy Hacking! 💗
