### ISSUE TITLE
[Enhancement]: UI responsiveness of Guess_the_number game

### ISSUE THREAD

**Issue by Vinayakkh** [kunjgit/GameZone#3163]
### Do you want to have the enhancement of existing game ? 😀 Describe yourself..

This game is not responsive when change display size elements collides with each other no clear visibility and touch on element

### Describe the solution you'd like

I make it responsive for every device
![Screenshot (42)](https://github.com/kunjgit/GameZone/assets/94226258/abac6022-1768-423d-b76c-0ef1975d083d)

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Vinayakkh ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @Vinayakkh ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
