### ISSUE TITLE
Search Results Display

### ISSUE THREAD

**Issue by Vemurinikitha** [kunjgit/GameZone#3164]
### Do you want to have the enhancement of existing game ? 😀 Describe yourself..

When searching for a game, the website either displays the matching game or shows a blank page when there are no matches. This inconsistency in displaying search results needs to be fixed.
![Screenshot_2024-05-12-12-56-50-233_com android chrome](https://github.com/kunjgit/GameZone/assets/163434910/8f9e79cb-10f8-45e4-a7ce-c870f97e8200)

### Describe the solution you'd like

Fix the search functionality to consistently display results for all valid queries, ensuring users always receive relevant information when using the search feature.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Vemurinikitha ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @Vemurinikitha! 🙂 
 It seems like you are not following proper guidelines !! 👀 
 Read documentation properly !!🙏 
 If you have any queries reach out to us on [Discord🕹️](https://discord.gg/fgwk4XZfxG) .

**Comment by kunjgit** [comment]
Hey @Vemurinikitha ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by Vemurinikitha** [comment]
Ok sir @kunjgit thankyou
