### ISSUE TITLE
[Enhancement]: Search Functionality Enhancement

### ISSUE THREAD

**Issue by Vemurinikitha** [kunjgit/GameZone#3168]
### Do you want to have the enhancement of existing game ? 😀 Describe yourself..

The website's search results lack consistency, displaying matching games inconsistently and sometimes showing a blank page when no matches are found. This inconsistency diminishes user satisfaction and needs rectification.
![IMG_20240512_134547](https://github.com/kunjgit/GameZone/assets/163434910/2b11b9a7-c29d-4155-ba1d-02dbba87d463)

### Describe the solution you'd like

Solution steps

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Vemurinikitha ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hello @Vemurinikitha, Time's up!⏰ 
 Sorry for closing your issue! 
 But it's more than a week since we haven't received anything from your side 😢 . 
 Come up with new ideas, create a new issue and make sure you finish it within a week! 🔥 
 All the best! 🚀 
 Happy Hacking! 💗
