### ISSUE TITLE
[Bug]: Guess_the_number take 2 guess with 1 input

### ISSUE THREAD

**Issue by Vinayakkh** [kunjgit/GameZone#3171]
### Give a brief about the bug ✍️

On giving one input it takes 2 as the same number which reduces the guess chance as guess chance is 10 but it make copy of 1 input and give it as 2 input provided

### What is the expected behavior? 🤔

It should take 1 input as 1 input only so the user can play it correctly

### Provide step by step information reproduce the bug 📄

Make changes in javascript code which makes it 2 times readable

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Vinayakkh ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @Vinayakkh ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
