### ISSUE TITLE
[New game]: Tic Tac Toe Game

### ISSUE THREAD

**Issue by RazaAli313** [kunjgit/GameZone#3173]
### 🎮 Game Request

It would be a two Players Game who would play tic tac toe with cross and dot symbols the person who has three consecutive matches of his corresponding symbol either horizontally,verticallt,diagonally wins the game,if no person matches till last game draws .
Game would have  also captivating sound effects...
@kunjgit Sir Kindly Assign me this Project !!!

### Point down the features

Game points
User Friendly UI
Captivating Sound and Music Effects
Win Sound
Tech Stack: HTML,CSS,JS,Tailwind

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @RazaAli313 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by RazaAli313** [comment]
@kunjgit  /assign

**Comment by ananyag309** [comment]
Hi, I hope this message finds you well.

I am writing to express my interest in contributing to the issue. I am enthusiastic about participating in GSSoC'24 and believe that working on this issue will allow me to make a meaningful contribution to the project.

Could you please assign this issue to me under GSSoC'24?

Thank you for considering my request.

**Comment by kunjgit** [comment]
Hello @RazaAli313, Time's up!⏰ 
 Sorry for closing your issue! 
 But it's more than a week since we haven't received anything from your side 😢 . 
 Come up with new ideas, create a new issue and make sure you finish it within a week! 🔥 
 All the best! 🚀 
 Happy Hacking! 💗
