### ISSUE TITLE
[New game]: Simon Types

### ISSUE THREAD

**Issue by VijaySamant4368** [kunjgit/GameZone#3174]
### 🎮 Game Request

- **Start Game**: The game begins with a start button or an initial prompt inviting the player to begin.

- **Simon's Turn**: Simon, the virtual character or system, randomly selects a letter from the alphabet and displays it to the player.

- **Player's Turn**: The player has a limited time (e.g., 0.5 seconds) to type the letter Simon displayed.

- **Check Input**: The game checks whether the player typed the correct letter within the time limit.

- **Feedback**: If the player types the correct letter, Simon acknowledges it, and the game proceeds to the next turn. If the player fails to type the correct letter or does not type it within the time limit, the game ends.

- **Increasing Difficulty**: As the game progresses, Simon adds more letters to the sequence, making it longer and more challenging.

- **End Game**: The game ends when the player makes a mistake or decides to stop playing. The player can then see their final score and optionally choose to play again.

### Point down the features

- **Scoring System**: Implement a scoring system to track the player's performance, such as the number of correct letters typed in a row or the total number of letters typed correctly before making a mistake.

- **Progressive Difficulty**: Increase the complexity of the game over time by adding more letters to the sequence or reducing the time limit for typing.

- **Visual and Auditory Feedback**: Provide visual and auditory cues to indicate whether the player's input was correct or incorrect.

- **High Score Tracking**: Optionally, track the player's highest score achieved in a single session or overall.

- **Customization Options**: Allow players to customize aspects of the game, such as the time limit for typing or the appearance of Simon.

- **Learning Mode**: Include a learning mode where players can practice typing without time pressure, helping them improve their skills before tackling the timed challenges.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @VijaySamant4368 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by VijaySamant4368** [comment]
I have previously worked in Javascript games, and new game can be made by me, if you assign it to me under GSSoC '24

**Comment by VijaySamant4368** [comment]
> Hey @VijaySamant4368 ! Thank you for raising an issue 💗 You can self assign the issue by commenting /assign in comment 😀 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone) Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

I am sorry, but I am not able to self-assign by the method you mentioned. Can you please help me further? I would be thankful

**Comment by VijaySamant4368** [comment]
Can you please mention the level under GSSoc '24?

**Comment by kunjgit** [comment]
Hey @VijaySamant4368 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
