### ISSUE TITLE
[New game]:  Touch the ball game

### ISSUE THREAD

**Issue by rajvaidyanath27** [kunjgit/GameZone#3176]
### 🎮 Game Request

Game logic and basic description:
The UI of "Touch the Ball" is designed to be intuitive and engaging, providing players with a visually appealing and interactive experience.

At the center of the screen is the game board, a square area with a white background and a black border. This is where the action takes place. Balls of varying sizes and colors appear randomly on the game board. Each ball represents a target for the player to touch.

### Point down the features

Game points:
My game will have points for the users when touched the ball.

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @rajvaidyanath27 , You can't have another issue before completing the previous one 😀 
 you already have the following 1 open issues 👀 ! :

#3162

**Comment by kunjgit** [comment]
Hey @rajvaidyanath27 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by kunjgit** [comment]
Hey @rajvaidyanath27 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)
