### ISSUE TITLE
[New game]: Bubble shooting game

### ISSUE THREAD

**Issue by codewithganeshhh** [kunjgit/GameZone#3177]
### 🎮 Game Request

Game logic and basic description : It's a Bubble Shooter Game, made using HTML,CSS,JS . The Code is Responsive and here Player has given some random balls and he/she has to shoot similar colored balls to increase Score.
@kunjgit Sir Kindly Assign me this Project !!!

### Point down the features

High Score Tracking: Optionally, track the player's highest score achieved in a single session or overall.
Progressive Difficulty: Increase the complexity of the game over time by adding more letters to the sequence or reducing the time limit for typing.

**Tech Stack: HTML,CSS,JS**

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @codewithganeshhh ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @codewithganeshhh! 
We are already having a similar game request in #3098 👀 
Make sure you come up with a cool unique idea 😀 
 Waiting for your new game idea 💗.

**Comment by kunjgit** [comment]
Hey @codewithganeshhh ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
