### ISSUE TITLE
[New game]:  POP the baloon with your mouse cursor 

### ISSUE THREAD

**Issue by codewithganeshhh** [kunjgit/GameZone#3178]
### 🎮 Game Request

Game logic and basic description : It's a baloon pop  Game, made using HTML,CSS,JS . The Code is Responsive and here Player has given some rando baloons in their screen  and he/she has to pop the baloons
@kunjgit Sir Kindly Assign me this Project !!!

### Point down the features

**Tech Stack: HTML,CSS,JS**

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @codewithganeshhh ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by codewithganeshhh** [comment]
Hey I Push my code but that was close ? #3235

**Comment by kunjgit** [comment]
Hey @codewithganeshhh ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
