### ISSUE TITLE
[Bug]: Website is not fully responsive.

### ISSUE THREAD

**Issue by singh-anushka** [kunjgit/GameZone#318]
### Give a brief about the bug ✍️

Description
The website becomes fully zoomed in at a certain size (Somewhere in between 1000px to 1100px). So this means that it is not fully responsive.

### What is the expected behavior? 🤔

Description
Instead of getting into 2 projects per row, the website gets zoomed in.
<hr>

Here's a picture describing that:
<img width="1440" alt="Screenshot 2023-05-23 at 8 55 01 PM" src="https://github.com/kunjgit/GameZone/assets/93376863/46797b9b-6d42-4e26-956e-44fe0772e969">

### Provide step by step information reproduce the bug 📄

Description
By looking into the class project-list. I can resolve the bug. Kindly assign me this issue under GSSoC23.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @singh-anushka 👋!
 
  @kunjgit here, 
 We have this annoucement to make 📢!! 
 During the time of PR don't alter main index file ! 🙂 
 In main Readme file just use * as a game number during the time we are merging we will add number !! 👀 
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG) if you haven't 😇 
  Thank you 💗!

**Comment by kunjgit** [comment]
Hey @singh-anushka ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
