### ISSUE TITLE
[New game]: Mine Sweeper by using pure css

### ISSUE THREAD

**Issue by neel815** [kunjgit/GameZone#3183]
### 🎮 Game Request

Game logic and basic description: It is implementation of the popular puzzle game Minesweeper. Built with [CSS and little bit of HTML]. We need to sweep through grid of tiles, avoiding hidden mines.
@kunjgit sir kindly assign me this project!!

### Point down the features

Game points
Tech Stack:HTML,CSS

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @neel815 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by vaishnavip27** [comment]
Hey I can work on this issue. As  have build a minesweeper game using pure css in the past. Please assign me this issue . Looking forward for the approval

**Comment by kunjgit** [comment]
Hello @neel815, Time's up!⏰ 
 Sorry for closing your issue! 
 But it's more than a week since we haven't received anything from your side 😢 . 
 Come up with new ideas, create a new issue and make sure you finish it within a week! 🔥 
 All the best! 🚀 
 Happy Hacking! 💗
