### ISSUE TITLE
[New game]: Bulls and Cows game could be added

### ISSUE THREAD

**Issue by Ankitapanda25** [kunjgit/GameZone#3184]
### 🎮 Game Request

Game logic and basic description

One player, the Chooser, thinks of a four-letter word and the other player, the Guesser, tries to guess it.

At each turn the Guesser tries a four-letter word, and the Chooser says how close it is to the answer by giving:

The number of Bulls - letters correct in the right position.
The number of Cows - letters correct but in the wrong position.
The Guesser tries to guess the answer in the fewest number of turns.

If either word has repeated letters the rule is that each letter can only count towards the score once, and Bulls are counted before Cows.

can be done against computer

### Point down the features

Playing against computer is one of the features.

@kunjgit can you assign me this

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Ankitapanda25 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)
