### ISSUE TITLE
[Bug]: Master typing -start/restart button non-functionality bug

### ISSUE THREAD

**Issue by Tasnuva12** [kunjgit/GameZone#3198]
### Give a brief about the bug ✍️

The start and restart buttons within the game interface are unresponsive, rendering the game unplayable upon launch or restart.

### What is the expected behavior? 🤔

Upon clicking the start or restart button, the game should initiate or restart the gameplay session respectively.

### Provide step by step information reproduce the bug 📄

- [x] Launch the game application.
- [x] -  Navigate to the main menu or game interface where the start/restart button is located.
- [x] - Attempt to click on the start or restart button.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Tasnuva12 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @Tasnuva12 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
