### ISSUE TITLE
[New game]: Pong

### ISSUE THREAD

**Issue by vaishnavi-3969** [kunjgit/GameZone#32]
### 🎮 Game Request

Game Logic:

The game starts with a canvas where the player controls a paddle at the left side and competes against an AI-controlled paddle at the right side.
A ball is placed at the center of the canvas and starts moving towards a random direction.
The player's objective is to prevent the ball from reaching their side by using the paddle to hit the ball back towards the AI paddle.
The AI paddle also moves vertically to track the ball's position and tries to hit the ball back towards the player's side.
The ball bounces off the paddles and the top/bottom walls of the canvas, changing direction accordingly.
Each time the player successfully hits the ball back to the AI paddle, their score increases.
If the ball crosses the AI paddle and reaches the player's side, the player loses a life. The game continues until the player runs out of lives.
The game ends when the player loses all their lives or chooses to exit the game.
Features of the Game:

Player Controls: The player controls a paddle using the mouse to hit the ball and prevent it from crossing their side.
AI Opponent: The AI paddle moves vertically to track the ball's position and attempts to hit it back towards the player's side.
Ball Movement: The ball moves in a random direction at the start and changes direction when it collides with paddles or walls.
Scoring: The player earns points for successfully hitting the ball back to the AI paddle.
Lives: The player has a limited number of lives, and they lose a life each time the ball crosses their side.
Game Over: The game ends when the player loses all their lives or chooses to exit the game.
Visual Feedback: The game provides visual feedback through animations, such as the movement of the paddles and the ball, to enhance the gaming experience.
Responsive Design: The game adapts to different screen sizes and device orientations, ensuring a consistent experience across devices.
Sound Effects: Optional sound effects can be added to enhance the gameplay, such as paddle-ball collisions or game over sounds.
Replayability: Players can aim to beat their previous high scores or challenge themselves to improve their gameplay skills.

### Point down the features

Player Controls: The player can control the paddle using keyboard keys or mouse input.
AI Opponent: The AI-controlled paddle moves strategically to challenge the player.
Ball Physics: Realistic ball physics, including speed, direction, and bouncing off walls and paddles.
Power-ups: Special items that appear during gameplay and provide temporary advantages to the player, such as increasing paddle size or slowing down the ball.
Multiplayer Mode: Support for multiplayer, allowing two players to compete against each other on the same device or over the network.
Difficulty Levels: Different levels of difficulty, allowing players to choose between easy, medium, and hard modes.
Score Tracking: Keep track of the player's score throughout the game and display it on the screen.
High Scores: Store and display a list of the highest scores achieved by players.
Sound Effects: Engaging sound effects for paddle-ball collisions, scoring points, and game events.
Visual Effects: Animations and visual effects to enhance the gaming experience, such as particle effects or screen shake on intense actions.
Customization: Allow players to customize the appearance of the game, including paddle color, ball design, or background themes.
Pause and Resume: Provide a pause feature that allows players to pause the game and resume it later.
Game Over Screen: Display a game over screen with the final score and an option to restart or return to the main menu.
Responsive Design: Ensure the game is responsive and playable on different screen sizes, including mobile devices.
Tutorial or Instructions: Provide a tutorial or instructions on how to play the game for new players.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @vaishnavi-3969  ! Thank you for raising an issue 💗 You have been assigned this issue you can start working on the issue 🎮
Thank you soo much for contributing to our repository ! 
It's sounds really interesting 😃 
Looking forward to have Pong on GameZone 🎮

**Comment by kunjgit** [comment]
Hello @vaishnavi-3969, Time's Uppp!⏰ 
 Sorry for closing your issue! 
 But it's more than a week since we haven't received anything from your side 😢 . 
 Come up with new ideas, create a new issue and make sure you finish it within a week! 🔥 
 All the best! 🚀 
 Happy Hacking! 💗

**Comment by kunjgit** [comment]
Hey @vaishnavi-3969 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by vaishnavi-3969** [comment]
I'm almost done with both the games only small part of the game is remaining can I still please submit it?
