### ISSUE TITLE
[New game]: Soduku

### ISSUE THREAD

**Issue by Ananya-Bhardwaj** [kunjgit/GameZone#320]
### 🎮 Game Request

Game logic and basic description

Sudoku is a logic-based, number-placement puzzle. The goal of the user is to fill a 9x9 grid which is divided into 3x3 subgrids. The numbers are to be placed in an already partially filled grid such that no number is repeated in a row, column, or 3x3 subgrid. 

### Point down the features

Tech stack used: HTML, CSS, Javascript

Game points
- 9 x 9 grid 
- Colorful background
- 2d layout
- Error counter: This counts the number of wrong moves made by the user i.e. the number of moves the user places the number in the wrong place
- Select numbers from 1 to 9 from a list below the grid
- Place the selected number in the correct position 

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Ananya-Bhardwaj 👋!
 
  @kunjgit here, 
 We have this annoucement to make 📢!! 
 During the time of PR don't alter main index file ! 🙂 
 In main Readme file just use * as a game number during the time we are merging we will add number !! 👀 
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG) if you haven't 😇 
  Thank you 💗!

**Comment by kunjgit** [comment]
Hello @Ananya-Bhardwaj, Time's Uppp!⏰ 
 Sorry for closing your issue! 
 But it's more than a week since we haven't received anything from your side 😢 . 
 Come up with new ideas, create a new issue and make sure you finish it within a week! 🔥 
 All the best! 🚀 
 Happy Hacking! 💗

**Comment by kunjgit** [comment]
Hey @Ananya-Bhardwaj ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
