### ISSUE TITLE
[New game]: Dice game

### ISSUE THREAD

**Issue by abdulshahvez** [kunjgit/GameZone#3200]
### 🎮 Game Request

Game logic and basic description: In our dice game, the objective is to be the first player to reach 100 points. Players accumulate points by rolling combinations of dice that correspond to different scoring categories.

### Point down the features

Game points

### Select program in which you are contributing
_GSSOC_

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by anshdeep0504** [comment]
Hey, allow me to work on this under GSSOC' 2024

**Comment by kunjgit** [comment]
Hello @abdulshahvez, Time's up!⏰ 
 Sorry for closing your issue! 
 But it's more than a week since we haven't received anything from your side 😢 . 
 Come up with new ideas, create a new issue and make sure you finish it within a week! 🔥 
 All the best! 🚀 
 Happy Hacking! 💗
