### ISSUE TITLE
[New game]: Tic Tac Toe

### ISSUE THREAD

**Issue by surya1926** [kunjgit/GameZone#3211]
### 🎮 Game Request

Game description :-
Its an two player game has 3X3 grid format each player has an different symbol "X" and "O". If the "X" appears  consecutively in any way then "X" wins the game same for "O".

### Point down the features

Game points:-
The game has an good background music and also with clicking sound on the grid,
The  game has animated stickers.
and it displays winner name and with msg "congratulations" with an Sticker same for lose.
with good UI and also with responsive.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @surya1926 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @surya1926! 
We are already having a similar game request in #3173 👀 
Make sure you come up with a cool unique idea 😀 
 Waiting for your new game idea 💗.

**Comment by kunjgit** [comment]
Hey @surya1926 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
