### ISSUE TITLE
[New game]: Verlet Physics Engine

### ISSUE THREAD

**Issue by mdazfar2** [kunjgit/GameZone#3213]
### 🎮 Game Request

Verlet integration is a numerical method used to integrate Newton’s equations of motion. It is frequently used to calculate trajectories of particles in molecular dynamics simulations and computer graphics. The algorithm was first used in 1791 by Delambre and has been rediscovered many times since then, most recently by Loup Verlet in the 1960s for use in molecular dynamics.

### Point down the features
Have you ever wondered if you can make your own physics engine in JavaScript? If so, you have come to the right place. We are going to build a Physics engine from scratch in JavaScript.

## Screenshots -

![image](https://github.com/kunjgit/GameZone/assets/100375390/73a63e40-9444-4aad-b072-1fbec37086fc)

![image](https://github.com/kunjgit/GameZone/assets/100375390/9bb89b2d-1b72-43d4-925a-93ff8f0e5f3b)

![image](https://github.com/kunjgit/GameZone/assets/100375390/a82646bc-ba00-44e5-bc0c-c8efb7ed1fbc)

![image](https://github.com/kunjgit/GameZone/assets/100375390/6ba0c968-e394-43d1-84ea-dc70b3151b22)

![image](https://github.com/kunjgit/GameZone/assets/100375390/036d5a48-ad70-42fa-9393-c2a622a2b2fe)

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @mdazfar2 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hello @mdazfar2, Time's up!⏰ 
 Sorry for closing your issue! 
 But it's more than a week since we haven't received anything from your side 😢 . 
 Come up with new ideas, create a new issue and make sure you finish it within a week! 🔥 
 All the best! 🚀 
 Happy Hacking! 💗
