### ISSUE TITLE
[New game]: Knife Game

### ISSUE THREAD

**Issue by sharmi4590** [kunjgit/GameZone#3216]
### 🎮 Game Request

In this game the user has to click on the knife and it will go to the board , if two knives collapse the game will end. It has 4 different levels and each level has different strategy. If a player loses a level it will automatically goto the first level. I am a GSSoC'24 contributor.

### Point down the features

![Screenshot (369)](https://github.com/kunjgit/GameZone/assets/102676949/c2118beb-386f-4e63-9cd7-c4e27fb06dce)
It has 4 levels and after clearing 1 level only the user can go to another level. 
There will only be particular number of knives and it will decrease on each throw.
It will look as follow.
![Screenshot (368)](https://github.com/kunjgit/GameZone/assets/102676949/abede4d3-3c97-43cb-ad6e-3e2e204641c2)

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @sharmi4590 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by sharmi4590** [comment]
Assign

**Comment by kunjgit** [comment]
Hey @sharmi4590 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
