### ISSUE TITLE
[New game]: Guess the number

### ISSUE THREAD

**Issue by surya1926** [kunjgit/GameZone#3217]
### 🎮 Game Request

Game basic description:-
Here we should guess the number between the given the range

### Point down the features

Game points:-
It was easy and time pass game,
The kid's will like this game more.
it has good UI and responsive 
Please assign me this game, i will make it.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by surya1926** [comment]
Please assign me this game sir

**Comment by kunjgit** [comment]
Hey @surya1926 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by surya1926** [comment]
Sir how to do self assign please say

**Comment by khushi497** [comment]
Will you assign the issue?
