### ISSUE TITLE
Playable Piano

### ISSUE THREAD

**Issue by Akshatakapare** [kunjgit/GameZone#3218]
### 🎮 Game Request

**Game logic and basic description**
we can add the Playable Piano, which will make sounds similar to the real Piano when we play the keys of the Piano. The 

### Point down the features

**Game points**
1]It plays the sound of the specific key when we play that key.
2]It sounds similar to the original Piano.
3]it will show a shadow effect when we press the key of the Piano.
4]It has a switching button between show keys/don't
![piano](https://github.com/kunjgit/GameZone/assets/156576791/90f3bdc4-8386-43e9-85d3-2c91b4c1cfce)
 show keys on the Piano.
5]We can regulate the sound intensity with the slide key. 

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Akshatakapare ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @Akshatakapare! 🙂 
 It seems like you are not following proper guidelines !! 👀 
 Read documentation properly !!🙏 
 If you have any queries reach out to us on [Discord🕹️](https://discord.gg/fgwk4XZfxG) .

**Comment by kunjgit** [comment]
Hey @Akshatakapare ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by Akshatakapare** [comment]
can you tell me how can I push my code repository?
