### ISSUE TITLE
my sweeper

### ISSUE THREAD

**Issue by muskan1707github** [kunjgit/GameZone#322]
I want to contribute to this.
My implementation of a web-based mine-sweeper game.
They are created using HTML, CSS, and JavaScript.Please assign me this.

**Comment by kunjgit** [comment]
Hey @muskan1707github ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
