### ISSUE TITLE
[New game]: Musical Instrument Game 

### ISSUE THREAD

**Issue by Jagpreet153** [kunjgit/GameZone#3220]
### 🎮 Game Request

Game logic and basic description
There would be some musical instruments which would be played to produce music 

### Point down the features

Game points
by clicking on keys on keyboard as well as clicking on the instruments , music will be played

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Jagpreet153 , You can't have another issue before completing the previous one 😀 
 you already have the following 1 open issues 👀 ! :

#3063

**Comment by kunjgit** [comment]
Hey @Jagpreet153 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by kunjgit** [comment]
Hey @Jagpreet153 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)
