### ISSUE TITLE
[Bug]: Master typing -Timer Functionality Failure Bug

### ISSUE THREAD

**Issue by Tasnuva12** [kunjgit/GameZone#3221]
### Give a brief about the bug ✍️

The timer feature within the game fails to initiate upon starting the game as intended, resulting in the absence of time tracking during gameplay sessions.

### What is the expected behavior? 🤔

Upon starting the game, the timer should begin counting elapsed time from the moment gameplay commences, providing a measure of time throughout the session.

### Provide step by step information reproduce the bug 📄

- [ ] Launch the game application.
- [ ] Navigate to the main menu or game interface where the timer is expected to start.
- [ ] Start the game by clicking on the designated start button or initiating gameplay.

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Tasnuva12 , You can't have another issue before completing the previous one 😀 
 you already have the following 1 open issues 👀 ! :

#3198

**Comment by kunjgit** [comment]
Hey @Tasnuva12 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by kunjgit** [comment]
Hey @Tasnuva12 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by Tasnuva12** [comment]
Sorry about that !
