### ISSUE TITLE
[Question]: Creating login and signup for this page. 

### ISSUE THREAD

**Issue by SrijaVuppala295** [kunjgit/GameZone#3222]
### Describe your question or ask for support.❓

 Hi @kunjgit !!! I would like to contribute for this issue of creating a login and sign up page with unique design I already have experience in website development using html and css so, I can make it in a most effective and unique way.Looking forward for your approval. 

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @SrijaVuppala295 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by SrijaVuppala295** [comment]
assign

**Comment by SrijaVuppala295** [comment]
Issue #3222 ,
@Kunj Patel, You have'nt assigned me for the raised issue.
I have done the login and signup pages...
#Screenshot of the issue !!
And it is saying to complete authorization in your browser....But i created
only pages using html and css..

**Comment by SrijaVuppala295** [comment]
Hello Kunjgit/Gamezone,
Can you help me with his.
I was a error of permission denied .
please checkout the issue , i have kept in the screenshot

**Comment by SrijaVuppala295** [comment]
Sir login and signup buttons are added and pages are also done.
Please add label to it . 
I want to close this issue.
Please merge it sir, everything is in good condition

**Comment by SrijaVuppala295** [comment]
Please add level label to it

**Comment by kunjgit** [comment]
Hey @SrijaVuppala295 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by SrijaVuppala295** [comment]
Add level label to it Sir

**Comment by kunjgit** [comment]
Hey @SrijaVuppala295 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
