### ISSUE TITLE
[New game]: 2048 game

### ISSUE THREAD

**Issue by SrijaVuppala295** [kunjgit/GameZone#3224]
### 🎮 Game Request

"2048" is an addictive and challenging puzzle game that tests the player's strategic thinking and planning abilities. With its simple yet engaging gameplay mechanics, players must carefully plan their moves to create larger numbers while preventing the grid from filling up too quickly. The game's minimalist design and intuitive controls make it accessible to players of all ages, yet mastering it requires patience, concentration, and foresight.

### Point down the features

Game points

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @SrijaVuppala295 , You can't have another issue before completing the previous one 😀 
 you already have the following 1 open issues 👀 ! :

#3222

**Comment by kunjgit** [comment]
Hey @SrijaVuppala295 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by kunjgit** [comment]
Hey @SrijaVuppala295 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by SrijaVuppala295** [comment]
assign
