### ISSUE TITLE
[Bug]: favicon is not present for hang man game 

### ISSUE THREAD

**Issue by nagamukesh** [kunjgit/GameZone#3228]
### Give a brief about the bug ✍️

A relevant favicon is missing for hang man game

### What is the expected behavior? 🤔

a valid favicon can be added to hang man game so that it will enhance the website

### Provide step by step information reproduce the bug 📄

I can add a relevant favicon for hang man game 
please assign me this issue under gssoc 2024

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @nagamukesh , You can't have another issue before completing the previous one 😀 
 you already have the following 1 open issues 👀 ! :

#3147

**Comment by kunjgit** [comment]
Hey @nagamukesh ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by kunjgit** [comment]
Hey @nagamukesh ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)
