### ISSUE TITLE
[New game]: Mines Game

### ISSUE THREAD

**Issue by avneetsingh154** [kunjgit/GameZone#3231]
### Game logic and basic description:
**1.GameBoard Initialization.**
**2.Gameplay Mechanics.**
**3.Winning Conditions:**

> The player wins when all non-mine cells are uncovered.
> Display a message indicating victory.

 **4.Losing Conditions:**

> The player loses when they uncover a cell containing a mine.
> Display a message indicating defeat.

### Point down the features

**User Interface:**

> Design a user-friendly interface displaying the game board and necessary controls.
> Include features such as a timer, mine counter, and reset button.
> Ensure responsiveness for different screen sizes and devices.

**>Scoring System:**

> Implement a scoring system based on time taken and number of moves.
> Store high scores locally or on a server if multiplayer functionality is implemented.

**Customization Options:**

> Allow players to customize game settings such as grid size, number of mines, and difficulty level.
> Implement different themes or visual styles to enhance player experience.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @avneetsingh154 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @avneetsingh154! 
We are already having a similar game request in #3183 👀 
Make sure you come up with a cool unique idea 😀 
 Waiting for your new game idea 💗.

**Comment by kunjgit** [comment]
Hey @avneetsingh154 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
