### ISSUE TITLE
[New game]: Crossword puzzle 

### ISSUE THREAD

**Issue by sakshiiiii26** [kunjgit/GameZone#3238]
### 🎮 Game Request

Game logic and basic description
Fill the word on basis of clue

### Point down the features

Game point 
1)Word related clues will be given
2)Identify words fill in the board 
3)There will be time limit
![Crossword-Puzzle-1-Solved-(1)](https://github.com/kunjgit/GameZone/assets/157235573/6d742126-a9fe-4ec6-8be3-116c3e01a9c0)

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @sakshiiiii26 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by sakshiiiii26** [comment]
Hello @kunjgit I'm contributor under GSSoC 24 I want to add this game please assign me this task.

**Comment by kunjgit** [comment]
Hello @sakshiiiii26, Time's up!⏰ 
 Sorry for closing your issue! 
 But it's more than a week since we haven't received anything from your side 😢 . 
 Come up with new ideas, create a new issue and make sure you finish it within a week! 🔥 
 All the best! 🚀 
 Happy Hacking! 💗
