### ISSUE TITLE
[New game]: Mystic Maze

### ISSUE THREAD

**Issue by sakshiiiii26** [kunjgit/GameZone#3239]
### 🎮 Game Request

Game logic and basic description
A maze-solving game with a twist.

### Point down the features

Game points
where players navigate through mystical environments filled with traps and illusions.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @sakshiiiii26 , You can't have another issue before completing the previous one 😀 
 you already have the following 1 open issues 👀 ! :

#3238

**Comment by kunjgit** [comment]
Hey @sakshiiiii26 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by kunjgit** [comment]
Hey @sakshiiiii26 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by sakshiiiii26** [comment]
> Hey @sakshiiiii26 , You can't have another issue before completing the previous one 😀 you already have the following 1 open issues 👀 ! :
> 
> #3238

Yeah I opened that but after that I found that Crossword Puzzle game has already merged

**Comment by sakshiiiii26** [comment]
So want to add this game can you please assign me this
