### ISSUE TITLE
[New game]: Table Tennis

### ISSUE THREAD

**Issue by jayesh2474** [kunjgit/GameZone#3248]
### 🎮 Game Request

🎮 Game Request

**Game Title:** Table Tennis

**Game Logic and Basic Description:**

Table Tennis, also known as Ping Pong, is a sport in which two or four players hit a lightweight ball, also known as the ping-pong ball, back and forth across a table using small solid rackets. The game takes place on a hard table divided by a net. The players must allow a ball played toward them to bounce once on their side of the table and must return it so that it bounces on the opposite side. A point is scored when a player fails to return the ball within the rules. 

### Point down the features

**Features:**
1. **Responsive Design:** Ensures the game adapts to different screen sizes.
2. **Interactive Gameplay:** Users can control the paddles using keyboard keys or touch gestures.
3. **Realistic Physics:** Simulates the bounce and movement of the ball realistically.
4. **Single Player and Multiplayer Modes:** Players can choose to play against the computer or with friends.
5. **Score Tracking:** Displays scores for each player or team.
6. **Customizable Settings:** Users can adjust game settings such as ball speed, paddle size, and difficulty level.
7. **Sound Effects:** Adds immersive sound effects for ball hits and scoring events.
8. **Pause and Resume:** Allows players to pause the game and resume later.

**Game Points:**
- Enhances hand-eye coordination
- Improves reflexes and concentration
- Provides enjoyable physical activity
- Promotes friendly competition and social interaction

**Select Program in Which You Are Contributing:**
GSSoC24

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @jayesh2474 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by jayesh2474** [comment]
@kunjgit /assign

**Comment by kunjgit** [comment]
Hello @jayesh2474, Time's up!⏰ 
 Sorry for closing your issue! 
 But it's more than a week since we haven't received anything from your side 😢 . 
 Come up with new ideas, create a new issue and make sure you finish it within a week! 🔥 
 All the best! 🚀 
 Happy Hacking! 💗
