### ISSUE TITLE
[New game]: into the space

### ISSUE THREAD

**Issue by sush123-mita** [kunjgit/GameZone#3252]
### 🎮 Game Request

Game logic and basic description: in the game into the space the player will be in rocket and first it has to selct the destination like where he want to head. then it will take off in outer space encountering the obstacles like asteroids lanets etc. and have to land safely on the selected destination. 

### Point down the features

Interplanetary Journey:

The main objective is to travel from one planet to another.
Each planet represents a level or stage, with increasing difficulty.
Planets can vary in size, gravity, and environmental hazards.
Spacecraft Customization:

Allow players to customize their spacecraft with different designs and upgrades.
Upgrades can include engines for speed, shields for protection, and weapons for defense.
Obstacle Course:

Design obstacles such as asteroids, meteor showers, space debris, and gravitational fields.
Each obstacle requires different strategies to navigate.
Resource Management:

Include a resource management system where players need to manage fuel, oxygen, and energy levels.
Collect resources from space debris or planets to replenish supplies.
Navigation Challenges:

Introduce navigation challenges such as asteroid belts, black holes, and wormholes.
Players need to plot their course carefully to avoid hazards and reach their destination.
Physics-based Controls:

Implement realistic physics for spacecraft movement, including inertia and gravitational forces.
Provide intuitive controls for acceleration, deceleration, and maneuvering.
Exploration and Discovery:

Include hidden planets or space stations that players can discover for bonus rewards.
Encourage exploration by adding secrets and Easter eggs throughout the game.
Mission Objectives:

Create mission objectives for each level, such as reaching a certain speed, collecting artifacts, or rescuing stranded astronauts.
Completing objectives earns rewards and unlocks new content.
Dynamic Environments:

Add dynamic elements like space storms, solar flares, and planetary rings that affect gameplay.
These elements can change the environment and introduce new challenges.
Enemy Encounters: like alien 
Visual and Audio Effects:

Use stunning visuals and audio effects to create immersive space environments.
Visual effects can include particle effects, lighting, and dynamic backgrounds.
Leaderboards and Achievements:

Implement leaderboards to track players' progress and high scores.
Include achievements for completing challenges and milestones.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @sush123-mita ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by sush123-mita** [comment]
kindly asign me this issue raised..

**Comment by sush123-mita** [comment]
please assign me this issue

**Comment by sush123-mita** [comment]
> ### 🎮 Game Request
> Game logic and basic description: in the game into the space the player will be in rocket and first it has to selct the destination like where he want to head. then it will take off in outer space encountering the obstacles like asteroids lanets etc. and have to land safely on the selected destination.
> 
> ### Point down the features
> Interplanetary Journey:
> 
> The main objective is to travel from one planet to another. Each planet represents a level or stage, with increasing difficulty. Planets can vary in size, gravity, and environmental hazards. Spacecraft Customization:
> 
> Allow players to customize their spacecraft with different designs and upgrades. Upgrades can include engines for speed, shields for protection, and weapons for defense. Obstacle Course:
> 
> Design obstacles such as asteroids, meteor showers, space debris, and gravitational fields. Each obstacle requires different strategies to navigate. Resource Management:
> 
> Include a resource management system where players need to manage fuel, oxygen, and energy levels. Collect resources from space debris or planets to replenish supplies. Navigation Challenges:
> 
> Introduce navigation challenges such as asteroid belts, black holes, and wormholes. Players need to plot their course carefully to avoid hazards and reach their destination. Physics-based Controls:
> 
> Implement realistic physics for spacecraft movement, including inertia and gravitational forces. Provide intuitive controls for acceleration, deceleration, and maneuvering. Exploration and Discovery:
> 
> Include hidden planets or space stations that players can discover for bonus rewards. Encourage exploration by adding secrets and Easter eggs throughout the game. Mission Objectives:
> 
> Create mission objectives for each level, such as reaching a certain speed, collecting artifacts, or rescuing stranded astronauts. Completing objectives earns rewards and unlocks new content. Dynamic Environments:
> 
> Add dynamic elements like space storms, solar flares, and planetary rings that affect gameplay. These elements can change the environment and introduce new challenges. Enemy Encounters: like alien Visual and Audio Effects:
> 
> Use stunning visuals and audio effects to create immersive space environments. Visual effects can include particle effects, lighting, and dynamic backgrounds. Leaderboards and Achievements:
> 
> Implement leaderboards to track players' progress and high scores. Include achievements for completing challenges and milestones.
> 
> ### Select program in which you are contributing
> GSSoC24
> 
> ### Code of Conduct
> * [x]  I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

assign me this issue

**Comment by sush123-mita** [comment]
> Hey @sush123-mita ! Thank you for raising an issue 💗 You can self assign the issue by commenting /assign in comment 😀 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone) Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

assign level to it

**Comment by kunjgit** [comment]
Hello @sush123-mita, Time's up!⏰ 
 Sorry for closing your issue! 
 But it's more than a week since we haven't received anything from your side 😢 . 
 Come up with new ideas, create a new issue and make sure you finish it within a week! 🔥 
 All the best! 🚀 
 Happy Hacking! 💗
