### ISSUE TITLE
[Enhancement]: Space Invaders Game not working

### ISSUE THREAD

**Issue by vedanshipathak** [kunjgit/GameZone#3254]
### Do you want to have the enhancement of existing game ? 😀 Describe yourself..

@kunjgit Currently ,when we click on the space invaders game it is not working ,i can create a complete space invaders using html, css & js. Please assign me this issue under GSSOC'24

### Describe the solution you'd like

Solution steps:
1)downloading the assets for the game
2)use canvas tag to create the board matrix
3)adding variables for ship. For instance for size of the ship and the movement .
4)creating a function for the game loop ,for alien and ship movement.
5)at the corner i will create  a point section where killing each alien will get the ship some points

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @vedanshipathak , You can't have another issue before completing the previous one 😀 
 you already have the following 1 open issues 👀 ! :

#3074

**Comment by kunjgit** [comment]
Hey @vedanshipathak ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by kunjgit** [comment]
Hey @vedanshipathak ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by vedanshipathak** [comment]
@kunjgit sorry i thought you haven't assigned me that .
