### ISSUE TITLE
[Bug]: Alien shooter game not working as intended 

### ISSUE THREAD

**Issue by krishkh** [kunjgit/GameZone#3256]
### Give a brief about the bug ✍️

The https://kunjgit.github.io/GameZone/Games/Alien_Shooters/ alienshooter game.

it does not even work close to as how it should be working.

### What is the expected behavior? 🤔

the expecterd behavior should be for the rocket to shoot the moving targets. and the target dies. and then we get to the next level.
but something mysterious happens which is.
whenever any control is used the moving targets in the space gets faster and faster and they keep getting closer to you? idk why that functionality exists but i dont think that is how the alien shooter game is.

the overall game seems to be very broken

### Provide step by step information reproduce the bug 📄

Just playing the game normally would reproduce the bug. by clicking on any controls lets say spacebar for destroying the targets.
the targest will keep getting faster and will hit you very instantly

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hello @krishkh, Time's up!⏰ 
 Sorry for closing your issue! 
 But it's more than a week since we haven't received anything from your side 😢 . 
 Come up with new ideas, create a new issue and make sure you finish it within a week! 🔥 
 All the best! 🚀 
 Happy Hacking! 💗

**Comment by kunjgit** [comment]
Hey @krishkh ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
