### ISSUE TITLE
Whack a mole game

### ISSUE THREAD

**Issue by Sunainabhave** [kunjgit/GameZone#3257]
The game is set in a grid of holes, and the objective is to “whack” or hit the moles that randomly pop up from these holes.
Tech-stack used: HTML,CSS and javascript.
@kunjgit please assign me this task under GSSOC'24.
Thankyou!

**Comment by kunjgit** [comment]
Hey @Sunainabhave ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @Sunainabhave ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by Sunainabhave** [comment]
Sorry, why is this issue closed? i couldnt understand
is there a game already? i am unable to reach you out on discord. 
Please let me know how to reach you out.
please help me out as i am very new to open source contribution
