### ISSUE TITLE
[Bug]: Color guessing game, all same colors issue at easy mode

### ISSUE THREAD

**Issue by krishkh** [kunjgit/GameZone#3259]
### Give a brief about the bug ✍️

Description
![image](https://github.com/kunjgit/GameZone/assets/51072063/c3da60df-e649-4778-a67f-f5bdcfad55a3)
all colors are same and when clicked they dont work
![image](https://github.com/kunjgit/GameZone/assets/51072063/2537b6d2-c1d6-4f23-b89e-a645f26af26e)

and there are some erros in console too

### What is the expected behavior? 🤔

the expected behavior is to get different colors and also the click should work. and there is error in console there should not be any errors in console

### Provide step by step information reproduce the bug 📄

open the game at https://kunjgit.github.io/GameZone/Games/Colour_Guessing_Game/
and play it at easy for a while and you will see that all colors will appear the same if you do it a few times and the gamne will freeze as the color buttons wont work anymore

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by krishkh** [comment]
This issue also occurs for hard mode

**Comment by kunjgit** [comment]
Hey @krishkh , You can't have another issue before completing the previous one 😀 
 you already have the following 1 open issues 👀 ! :

#3256

**Comment by kunjgit** [comment]
Hey @krishkh ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by kunjgit** [comment]
Hey @krishkh ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)
