### ISSUE TITLE
[Enhancement]: Whack-a-mole speed slider for difficulty

### ISSUE THREAD

**Issue by Ritax2003** [kunjgit/GameZone#3266]
### Do you want to have the enhancement of existing game ? 😀 Describe yourself..

Game enhancement

### Describe the solution you'd like

Will add a slider element in html file before starting of the game, then in mole.js file i will make a variable speed with default value of 2500 ms. then on windows.onload i will get the input of range from user by getelementByid , as the range will be in integer, so i will make change in the speed by speed = 3000 - speed slider value *500. in setinterval function i will send the speed value. the higher the slider , the mole will appear with more speed. Also will change the titile form 'Whac-a-mole' to 'Whack-a-mole'.
![Screenshot 2024-05-14 081655](https://github.com/kunjgit/GameZone/assets/82272821/41662aad-491c-47ca-b0d3-ef61736f3642)

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Ritax2003 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @Ritax2003 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
