### ISSUE TITLE
Rock paper scissor

### ISSUE THREAD

**Issue by meetarora10** [kunjgit/GameZone#3269]
### 🎮 Game Request

Rock-paper-scissors game built using HTML,CSS,JavaScript.
In this game we can select any one of rock,paper or scissor and the computer randomly select any of the three.
![Screenshot (411)](https://github.com/kunjgit/GameZone/assets/143121854/30c07bec-37f1-4a47-94bc-edd99537e14c)
![Screenshot (412)](https://github.com/kunjgit/GameZone/assets/143121854/cf835086-331c-4d0f-8b33-05356efebb51)

### Point down the features

As soon as anything is selected by the user ,the score can be displayed on the screen and then further scores will be added.
This also includes the reset score button to reset the scores and an auto play button to which randomly selects and plays from both sides and it is continued until stop play button is pressed.

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @meetarora10 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @meetarora10! 🙂 
 It seems like you are not following proper guidelines !! 👀 
 Read documentation properly !!🙏 
 If you have any queries reach out to us on [Discord🕹️](https://discord.gg/fgwk4XZfxG) .

**Comment by kunjgit** [comment]
Hey @meetarora10 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by meetarora10** [comment]
@kunjgit I am contributing under ggsoc'24
