### ISSUE TITLE
[New game]: DoraeonRun

### ISSUE THREAD

**Issue by SrijaVuppala295** [kunjgit/GameZone#3272]
### 🎮 Game Request

Doraemon Run is an adventurous game where players will be able to navigate through through top,left,right,bottom .Players must navigate Doraemon through obstacles like mazes while collecting cakes and avoiding traps. It offers engaging gameplay with intuitive controls and increasing difficulty levels. As Doraemon  dashes through challenging mazes to devour delicious Dora cakes ,it will loose his score and health . It will track the high Score and Score and as soon as it health reaches 0 or it will crash to the boundary line , the game will end.

### Point down the features

In "Doraemon Run," players earn game points for every Dora cake Doraemon consumes during his adventurous run through the mazes. Each cake adds to the player's overall score, encouraging them to collect as many cakes as possible. Additionally, players may receive bonus points for collecting cakes in quick succession or for completing special challenges within the game. These points contribute to the player's overall score, allowing them to compete for high scores on the game's leaderboards.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @SrijaVuppala295 , You can't have another issue before completing the previous one 😀 
 you already have the following 1 open issues 👀 ! :

#3222

**Comment by kunjgit** [comment]
Hey @SrijaVuppala295 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by SrijaVuppala295** [comment]
I have already completed the previous one.

**Comment by SrijaVuppala295** [comment]
Sir, the issue is closed, is it okay to work on it. I have completed the PR for the previous issue.

**Comment by SrijaVuppala295** [comment]
Please open this issue
