### ISSUE TITLE
[Stone paper siccors game not working]: 

### ISSUE THREAD

**Issue by Yashgabani845** [kunjgit/GameZone#3275]
### When i open this game and start the game the first view that i got is looking like :
![image](https://github.com/kunjgit/GameZone/assets/127788321/1fb984f6-ea06-42df-9ba4-d392b4556588

### What is the expected behavior? 🤔

the images should lbe visible and game should work smoother

### Provide step by step information reproduce the bug 📄

images and their path are not given correctly 

i can provide new images which support in every browser and link it correctly

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by Yashgabani845** [comment]
please assign me this issue

**Comment by kunjgit** [comment]
Hey @Yashgabani845 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @Yashgabani845! 🙂 
 It seems like you are not following proper guidelines !! 👀 
 Read documentation properly !!🙏 
 If you have any queries reach out to us on [Discord🕹️](https://discord.gg/fgwk4XZfxG) .

**Comment by kunjgit** [comment]
Hey @Yashgabani845 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
