### ISSUE TITLE
[Documentation Bug]: Bird_game

### ISSUE THREAD

**Issue by Bindusree1515** [kunjgit/GameZone#3278]
### Describe the bug ✍️

There is a bug in the README.md file of Bird_game , where instead of screenshot there is code placed, which is not understandable. I can place the screenshot of the game.
**Sreenshot** of the bug:
![image](https://github.com/kunjgit/GameZone/assets/91887086/7c30ae2a-ece5-4c0d-9b51-087d7eaed56d)

### Provide step by step information reproduce the bug 📄

1. go to the Bird_game
2. In the screenshot section you can see code instead of screenshot
3. Resolve the issue

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Bindusree1515 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @Bindusree1515 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
