### ISSUE TITLE
[Enhancement]: exiting and pausing the game

### ISSUE THREAD

**Issue by Shravani-A-Kulkarni** [kunjgit/GameZone#3288]
### Do you want to have the enhancement of existing game ? 😀 Describe yourself..

Game enhancement:      There is no option in any game to return back to home page or to exit or  pause the game .There should be option that takes the user back to the home page if he/she wants to exit any game. Also he wants to take a pause while playing the game. 

### Describe the solution you'd like

Solution steps: Add a option at the top to pause, or exit a game . When the player clicks on exit a game we will link that button with the home page link, so player will be directed to home page.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Shravani-A-Kulkarni ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by Shravani-A-Kulkarni** [comment]
assign the issue to me

**Comment by kunjgit** [comment]
Hello @Shravani-A-Kulkarni, Time's up!⏰ 
 Sorry for closing your issue! 
 But it's more than a week since we haven't received anything from your side 😢 . 
 Come up with new ideas, create a new issue and make sure you finish it within a week! 🔥 
 All the best! 🚀 
 Happy Hacking! 💗

**Comment by kunjgit** [comment]
Hey @Shravani-A-Kulkarni ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
