### ISSUE TITLE
[New game]:  Maze_Game

### ISSUE THREAD

**Issue by CoderUzumaki** [kunjgit/GameZone#3289]
### 🎮 Game Request

Game Logic:

- Character Movement: Players can move "Jerry" up, down, left, or right within the maze using keyboard arrow keys or on-screen touch controls.

- Collision Detection: The game logic includes collision detection to ensure that "Jerry" does not pass through walls or obstacles. If "Jerry" encounters a wall or obstacle, the movement is restricted in that direction.

- Win Condition: When "Jerry" successfully reaches the "Cheese" at the end of the maze, the game concludes, displaying a victory message or transitioning to the next level depending on the chosen difficulty.

### Point down the features

Features of Maze_Game:

- Difficulty Levels: The game offers four difficulty levels - easy, medium, hard, and extreme. Each level presents a progressively challenging maze layout, with more complex paths and obstacles.

- Responsive Design: The game is designed to be responsive, ensuring optimal gameplay experience across different devices and screen sizes. Players can enjoy the game on desktops, laptops, tablets, and mobile devices seamlessly.

- Interactive Maze: The maze consists of walls, pathways that players navigate through to reach the end goal. Users can control the character "Jerry" using keyboard arrow keys or touch controls, depending on the device used.

- Objective: The primary objective of the game is to guide "Jerry" (the movable character) from one end of the maze to the other end where "Cheese" is located. Players need to strategize and find the correct path through the maze, avoiding dead ends and obstacles along the way.

- Level Progression: With increasing difficulty levels, the maze complexity and the number of obstacles increase, challenging players' problem-solving skills and spatial awareness. Progressing through levels unlocks new challenges and rewards.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @CoderUzumaki ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by CoderUzumaki** [comment]
Thanks @kunjgit!
I'll follow all necessary steps and would take care not to violate any guidelines.

/assign
