### ISSUE TITLE
[Enhancement]: Connect 4 game

### ISSUE THREAD

**Issue by AtharvaShinde253** [kunjgit/GameZone#3291]
### Do you want to have the enhancement of existing game ? 😀 Describe yourself..

The game doesnt have a player turn popup to address the player's turn.
I will also add a winner pop-up to address the winner.
Also adding  a start game feature so that we can play consecutively without re-running the code

### Describe the solution you'd like

Adding a player turn pop-up
Adding winner description as player1 win or player2 win
Adding a button to start the game multiple times.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @AtharvaShinde253 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @krati234 ! , This issue is already assigned to @AtharvaShinde253. 💗 
 You can work on other issues 🚀 
 If there is anything wrong you can contact us on [Discord🕹️](https://discord.gg/fgwk4XZfxG)👀

**Comment by kunjgit** [comment]
Hey @AtharvaShinde253 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
