### ISSUE TITLE
[Documentation Bug]: Documentation issue 

### ISSUE THREAD

**Issue by msifran** [kunjgit/GameZone#3292]
### Describe the bug ✍️

I hope this message finds you well. I wanted to bring to your attention a minor issue regarding the document titled word blitz . Upon review, it has come to my notice that there is read me file which is empty.

To ensure the accuracy and clarity of the document, I kindly request your assistance in addressing this matter promptly. Your attention to detail and collaboration in resolving this issue are greatly appreciated.

Please feel free to reach out if you need any further clarification or assistance. Thank you for your cooperation.

## Overview
Wirtd Blitz is a fast-paced word game where players compete to create words from a set of letters within a time limit. This README provides rules and tutorials for playing Wirtd Blitz.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @msifran ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by msifran** [comment]
Thanks @kunjgit!
I'll follow all necessary steps and would take care not to violate any guidelines.

**Comment by kunjgit** [comment]
Hey @msifran ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
