### ISSUE TITLE
[Enhancement]: Adding About Section for GameZone

### ISSUE THREAD

**Issue by jency1** [kunjgit/GameZone#3293]
### Do you want to have the enhancement of existing game ? 😀 Describe yourself..

Adding an "About" section to your website is vital for informing users about the purpose and offerings of your platform. This section serves as a gateway for users to understand what your website is all about, who is behind it, and what they can expect to find. By providing a brief overview of your website's mission, vision, and objectives, users can quickly grasp its value proposition and relevance to their interests.
Including any unique features, services, or content that sets your website apart further entices users to explore and engage with your platform. Overall, the "About" section plays a crucial role in defining your website's identity and encouraging user interaction and participation.

### Describe the solution you'd like

1. Define the purpose.
2. Gather content.
3. Choose a format.
4. Select visuals.
5. Design layout.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @jency1 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by jency1** [comment]
assign

**Comment by jency1** [comment]
Please add the level label.

**Comment by kunjgit** [comment]
Hey @jency1 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by jency1** [comment]
Please add the level label.

**Comment by jency1** [comment]
@kunjgit Please add the level label as soon as possible.
