### ISSUE TITLE
[Bug]: Squid Game added 2 times (Game no. 372 & 375)

### ISSUE THREAD

**Issue by MrPC7** [kunjgit/GameZone#3299]
### Give a brief about the bug ✍️

Description
It seems there's a duplication error in your list. Squid Game is listed twice, as Game No. 372 and Game No. 375. To correct this, simply remove one of the duplicate entries.

![image](https://github.com/kunjgit/GameZone/assets/91939963/2f6ae042-c607-445f-962b-18af235531ca)

### What is the expected behavior? 🤔

Description

### Provide step by step information reproduce the bug 📄

Description

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @MrPC7 , You can't have another issue before completing the previous one 😀 
 you already have the following 1 open issues 👀 ! :

#3212

**Comment by kunjgit** [comment]
Hey @MrPC7 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by kunjgit** [comment]
Hey @MrPC7 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)
