### ISSUE TITLE
[Bug]: Tilting Maze is not responsive in  Mobile

### ISSUE THREAD

**Issue by Mudassirkhan2** [kunjgit/GameZone#33]
### Give a brief about the bug ✍️

Tilting Maze Game  is not responsive in  Mobile Devices

### What is the expected behavior? 🤔

Description Should be Responsive 

### Provide step by step information reproduce the bug 📄

![Screenshot 2023-05-20 110652](https://github.com/kunjgit/GameZone/assets/106579572/174bf512-b6f4-42a0-9e74-dce0369e16a2)

i Would like to work on this issue under GSSOC 2023

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Mudassirkhan2 the issue you are raising comes under game enhancement and make sure you give us surety by describing more that how you will be going to fix that !! 😃 
For now I am closing this issue open new game enhancement issue with proper description
