### ISSUE TITLE
[Enhancement]: Improving UI-The search icon should be a bit above. 

### ISSUE THREAD

**Issue by SIM-RAITANI** [kunjgit/GameZone#3300]
### Do you want to have the enhancement of existing game ? 😀 Describe yourself..

Game enhancement : The search icon is placed really at bottom, if the search bar is placed a bit above, it will improve its UI.

### Describe the solution you'd like

I can solve this problem. By placing the search bar at right location.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @SIM-RAITANI ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by anshdeep0504** [comment]
Hey, allow me to work on this under GSSOC' 2024

**Comment by ISHWARISD** [comment]
Please assign the issue to me

**Comment by SIM-RAITANI** [comment]
I would like to resolve the issue myself. 
/assign

**Comment by kunjgit** [comment]
Hello @SIM-RAITANI, Time's up!⏰ 
 Sorry for closing your issue! 
 But it's more than a week since we haven't received anything from your side 😢 . 
 Come up with new ideas, create a new issue and make sure you finish it within a week! 🔥 
 All the best! 🚀 
 Happy Hacking! 💗

**Comment by kunjgit** [comment]
Hey @SIM-RAITANI ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
