### ISSUE TITLE
[Enhancement]: Add a stop and resume feature to the game run and jump

### ISSUE THREAD

**Issue by Roshr2211** [kunjgit/GameZone#3301]
### Do you want to have the enhancement of existing game ? 😀 Describe yourself..

Game enhancement
# issue
the game run and jump wasn't pausing.

https://github.com/kunjgit/GameZone/assets/136987759/e11ffe0e-1f49-4d87-8371-aa05fd690e42

### Describe the solution you'd like

# Solution steps
- added a 'stop and pause' button to stop and resume the game and it updates the score from where it stopped.

https://github.com/kunjgit/GameZone/assets/136987759/e4c2c958-79b9-481b-b355-dce09ae3d883

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Roshr2211 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @Roshr2211 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
