### ISSUE TITLE
𝐌𝐚𝐭𝐜𝐡 𝐌𝐚𝐤𝐢𝐧𝐠 

### ISSUE THREAD

**Issue by Kiran-pro2001** [kunjgit/GameZone#3303]
### Feature
I created a new game, called  "𝐌𝐚𝐭𝐜𝐡 𝐌𝐚𝐤𝐢𝐧𝐠", in this game, there is a Hit Value, which ranges from 0 to 9, and every time the value of the hit gets changed.

Now the task is to match the hit value to all the options, here options are also changing every time. And there is a time constraint for 60 Seconds.

If you can match it, you will get 10 Points, if not then the game gets ended. 

### Game points 

For Correct Matching -  +10 Points.
For Incorrect Matching - Game Over.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Kiran-pro2001 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @Kiran-pro2001! 🙂 
 It seems like you are not following proper guidelines !! 👀 
 Read documentation properly !!🙏 
 If you have any queries reach out to us on [Discord🕹️](https://discord.gg/fgwk4XZfxG) .

**Comment by kunjgit** [comment]
Hey @Kiran-pro2001 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
