### ISSUE TITLE
[Enhancement]: ADD "INSTRUCTIONS"  and DISPLAY "GAME TITLE" before game starts in MASTER TYPING game

### ISSUE THREAD

**Issue by TusharChamlikar** [kunjgit/GameZone#3308]
### Do you want to have the enhancement of existing game ? 😀 Describe yourself..

1. The TITLE  of game is  not displayed anywhere inside,if it is displayed it will promote game well.
2. There are no instructions given about "HOW TO PLAY".

### Describe the solution you'd like

1. I will make changes to display title of game before starting.
2. i will add a page which consists of instructions about "how to play". 

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @TusharChamlikar ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by TusharChamlikar** [comment]
thankyou for your quick response

**Comment by kunjgit** [comment]
Hey @TusharChamlikar ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
