### ISSUE TITLE
[New game]: Pong

### ISSUE THREAD

**Issue by samhitaveluri** [kunjgit/GameZone#331]
### 🎮 Game Request

Game logic and basic description:
Pong is a single player game where there are 2 paddles and a ball. One paddle is in our(player) control where the other is side is played by computer. We use the up and down arrows to move our paddle. The random color generator is used to change background colors for each round.
This game is developed mostly using javascript.

### Point down the features

Game points:
1) When the computer(our opponent here) misses our ball hit by our paddle, we score a point and vice versa.
2)After scoring the nth point we progress to next round.
3)For each round the speed of ball and computer controlled paddle increases. 
4)In final level if we score the required points the winner message appears on the screen.
 ["C:\Users\samhi\OneDrive\Pictures\Screenshots\Screenshot 2023-05-23 225054.png"](url)
["C:\Users\samhi\OneDrive\Pictures\Screenshots\Screenshot 2023-05-23 230443.png"](url) 

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @samhitaveluri ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @samhitaveluri! 
We are already having a similar game request in #221 👀 
Make sure you come up with a cool unique idea 😀 
 Waiting for your new game idea 💗.
