### ISSUE TITLE
[Enhancement]: attractive 

### ISSUE THREAD

**Issue by msifran** [kunjgit/GameZone#3313]
### Do you want to have the enhancement of existing game ? 😀 Describe yourself..

Game enhancement for attractiveness, Content and colour grading. 

### Describe the solution you'd like

 -[ ] colour grading 

- [x] All the work is put in a box ( border ) 
- [x] Easy to use in every platform 
- [x] correction in code like spelling
- [x] Use the code in a static manner 

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @msifran ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @msifran ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
