### ISSUE TITLE
[Documentation Bug]:  Empty readme file 

### ISSUE THREAD

**Issue by msifran** [kunjgit/GameZone#3314]
### Describe the bug ✍️

Describe your bug here, there is no tutorial or overview of the work . 

### Provide step by step information reproduce the bug 📄

- [ ] Descriptions
- [ ] Introduction
- [ ] Tutorial
- [ ] Scoring
- [ ] restart 
- [ ] Clue / hint
- [ ] Play again

 
 
 
 

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @msifran , You can't have another issue before completing the previous one 😀 
 you already have the following 1 open issues 👀 ! :

#3313

**Comment by kunjgit** [comment]
Hey @msifran ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)
