### ISSUE TITLE
[New game]: Memory Game

### ISSUE THREAD

**Issue by JPV2207** [kunjgit/GameZone#332]
### 🎮 Game Request

The Memory Game is a simple game made using HTML, CSS and Javascript. It is a great game in enhancing the memory power of an individual. The game comprises of fruits which are hidden initially with each fruit having a duplicate image. After clicking on the Start button, the player has to click on any two random random fruits. If the clicked fruits are the same the images of the fruits gets freezed there, otherwise the fruits flip again to their hidden state. Player wins the game once he/she has found all the pairs of individual fruits.

### Point down the features

• The game is simple and beginner friendly and is made on a 4*4 matrix.
• There is a Start button which is provided in order to start the game. 
• Also there is a Timer in the game in order to keep a track of the time taken by an individual.
• All the fruits are hidden at first and the player needs to click on any two random fruits in order to check for the same pair of fruits.
• The game gets ended as soon as all the pairs of the fruits have been found.
• One can restart the game then by either clicking on the Refresh button on the top-left side of the website or by pressing the Ctrl+R button on the keyboard.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @JPV2207! 
We are already having a similar game request in #268 👀 
Make sure you come up with a cool unique idea 😀 
 Waiting for your new game idea 💗.

**Comment by kunjgit** [comment]
Hey @JPV2207 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by JPV2207** [comment]
Thank you so much for assigning me the issue!
