### ISSUE TITLE
[Enhancement]: Add better alerting system while pausing and restarting game

### ISSUE THREAD

**Issue by Roshr2211** [kunjgit/GameZone#3320]
### Do you want to have the enhancement of existing game ? 😀 Describe yourself..

# Game enhancement
- As seen here the game uses the built in alert system which can seem less appealing 
![image](https://github.com/kunjgit/GameZone/assets/136987759/8d3acdfd-1c00-4c68-9587-af86433f47c1)

# Other issues
- UI enhancement can be done
- ReadMe can be improvised

### Describe the solution you'd like

# Solution steps

- Better alert system while pausing the game and restarting it
- Better UI
- docs: A informative ReadME

https://github.com/kunjgit/GameZone/assets/136987759/b3cdf062-85af-4825-bbca-86290446dd76

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Roshr2211 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @Roshr2211 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
