### ISSUE TITLE
[Enhancement]: No repetation in Word guessing game

### ISSUE THREAD

**Issue by VijaySamant4368** [kunjgit/GameZone#3322]
### Do you want to have the enhancement of existing game ? 😀 Describe yourself..

While playing the **Word-Guessing-Game**, it sometimes asks the same question to in the same round, which should be avoided for better user experience. Furthermore, there are only 30 words to choose from, which basically means only 3 rounds, and the game won't be playable again.

### Describe the solution you'd like

Somme possible solutions would be:
- Creating an array of the words that the user has guessed, and make sure the new word is not in that array.
- Adding a lot of new words for more possible game rounds for all

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @VijaySamant4368 , You can't have another issue before completing the previous one 😀 
 you already have the following 1 open issues 👀 ! :

#3174

**Comment by kunjgit** [comment]
Hey @VijaySamant4368 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by kunjgit** [comment]
Hey @VijaySamant4368 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)
