### ISSUE TITLE
[Enhancement]: Tennis field size

### ISSUE THREAD

**Issue by VijaySamant4368** [kunjgit/GameZone#3323]
### Do you want to have the enhancement of existing game ? 😀 Describe yourself..

The rackets in the **Tennis** game covers almost all of the width of the field, making it a very easy to play, and hence a very boring, game.

![image](https://github.com/kunjgit/GameZone/assets/145102345/b8a74d11-1f78-458f-b676-a4201529fc7e)
As can be seen, it covers almost 70-80% of the width.

### Describe the solution you'd like

I propose that the width of the field should increase a lot, along with its length, furthermore, due to these changes, the speed of the ball should also increase.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @VijaySamant4368 , You can't have another issue before completing the previous one 😀 
 you already have the following 1 open issues 👀 ! :

#3174

**Comment by kunjgit** [comment]
Hey @VijaySamant4368 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by kunjgit** [comment]
Hey @VijaySamant4368 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)
