### ISSUE TITLE
[Enhancement]: A portal including all available games with attractive UI.

### ISSUE THREAD

**Issue by Flashl3opard** [kunjgit/GameZone#3328]
### Do you want to have the enhancement of existing game ? 😀 Describe yourself..

Will help the users the easily find all games from a single page creating less fuss and much more effecient.

### Describe the solution you'd like

Creating attractive logo for each game and linking it to a static webpage (Home page).
Please assign this task to me.
Thank you.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Flashl3opard ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by vipinmishra0852** [comment]
Hey @kunjgit please assign me this issue

**Comment by nishant0708** [comment]
assign me this issue under gssoc24

**Comment by Deepthi-Ramineni** [comment]
Please assign this issue to me. I would like to work on it.

**Comment by Soujanya2004** [comment]
hi, I have been following your project and would love to contribute, please assign me the issue.

**Comment by kunjgit** [comment]
Hello @Flashl3opard, Time's up!⏰ 
 Sorry for closing your issue! 
 But it's more than a week since we haven't received anything from your side 😢 . 
 Come up with new ideas, create a new issue and make sure you finish it within a week! 🔥 
 All the best! 🚀 
 Happy Hacking! 💗

**Comment by kunjgit** [comment]
Hey @Flashl3opard ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
