### ISSUE TITLE
[Bug]: Game cards are not of same height

### ISSUE THREAD

**Issue by Ayushmaanagarwal1211** [kunjgit/GameZone#3332]
### Give a brief about the bug ✍️

Those cards who doesn't have any game image having lesser height  then the cards having image .

![Screenshot 2024-05-16 135523](https://github.com/kunjgit/GameZone/assets/118350936/862edd3e-1698-40bf-9b79-2e261d7f5958)

### What is the expected behavior? 🤔

The height of all cards should be same 

### Provide step by step information reproduce the bug 📄

This can be done by adding min-height to the card 
If found it suitable i would like to work on that .

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Ayushmaanagarwal1211 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by vaishnavip27** [comment]
Hey @kunjgit I can work on the enhancement of the page as a designer and a developer. Please assign this issue to me. Looking forward for your approval

**Comment by kunjgit** [comment]
Hey @Ayushmaanagarwal1211 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
