### ISSUE TITLE
Doodle jump

### ISSUE THREAD

**Issue by rajvaidyanath27** [kunjgit/GameZone#3334]
### 🎮 Game Request

The objective of Doodle Jump is simple: keep jumping as high as possible while avoiding obstacles and enemies. The higher you jump, the higher your score.

GAMEPLAY:
1.The game begins with a simple character, often a small doodle-like creature
2.As the character jumps upward, the screen scrolls vertically, revealing new platforms.
3.The player's goal is to keep jumping from platform to platform without falling off the screen.

### Point down the features

Game points:

1.Jumping: Each successful jump adds points to the player's score. The higher the jump, the more points earned.
2. Simply surviving for a longer time without falling or hitting obstacles can gradually increase the player's score.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @rajvaidyanath27 , You can't have another issue before completing the previous one 😀 
 you already have the following 1 open issues 👀 ! :

#3185

**Comment by kunjgit** [comment]
Hey @rajvaidyanath27 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by kunjgit** [comment]
Hey @rajvaidyanath27 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by rajvaidyanath27** [comment]
but you have not assign me the previous issue

**Comment by rajvaidyanath27** [comment]
> Hey @rajvaidyanath27 , You can't have another issue before completing the previous one 😀 you already have the following 1 open issues 👀 ! :
> 
> #3185

but you have not assigned me the previous issue
