### ISSUE TITLE
[Enhancement]: Emoji Bingo New Game

### ISSUE THREAD

**Issue by Parth20GitHub** [kunjgit/GameZone#3337]
### Do you want to have the enhancement of existing game ? 😀 Describe yourself..

Game enhancement

### Describe the solution you'd like

Solution steps

would add Card image of game no 384 according to the game

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Parth20GitHub ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by Parth20GitHub** [comment]
please add **gssoc** label

Thnaks

**Comment by Parth20GitHub** [comment]
done

**Comment by kunjgit** [comment]
Hey @Parth20GitHub ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by Parth20GitHub** [comment]
it is not seen in leaderboard , PLEASE add GSSOC and LEVEL label

**Comment by kunjgit** [comment]
Hey @Parth20GitHub ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by kunjgit** [comment]
Hello @Parth20GitHub, Time's up!⏰ 
 Sorry for closing your issue! 
 But it's more than a week since we haven't received anything from your side 😢 . 
 Come up with new ideas, create a new issue and make sure you finish it within a week! 🔥 
 All the best! 🚀 
 Happy Hacking! 💗

**Comment by kunjgit** [comment]
Hey @Parth20GitHub ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
