### ISSUE TITLE
[New game]: Diglet Whack a mole

### ISSUE THREAD

**Issue by PriyankaTamhankar01** [kunjgit/GameZone#334]
### 🎮 Game Request

🎮 Game Logic: 

1. Gameplay Setup: The game is typically played on a screen, such as a mobile device or computer, with the Diglet holes displayed in a grid-like pattern.
2. Diglet Pop-Up: Diglets randomly pop up from their holes at different intervals.
3. Whack Action: Players use their finger or a designated control (e.g., mouse click) to tap or "whack" the Diglet as quickly as possible.
4. Scoring: Each successful hit on a Diglet earns the player points. The faster the player reacts, the higher the score.
5. Time Limit: The game typically has a time limit, encouraging players to whack as many Diglets as possible within that time frame.
6. Game Over: The game ends when the time limit expires. 

### Point down the features

🎮 Features:

1. Time Pressure: The inclusion of a time limit adds excitement and encourages players to act quickly.
2. Visual and Audio Effects: The game may incorporate appealing graphics, animations, and sound effects to enhance the overall gaming experience.
![image](https://github.com/kunjgit/GameZone/assets/90240653/350b1ad1-7cce-4c8b-ac83-902c7d34dfbf)

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @PriyankaTamhankar01 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @PriyankaTamhankar01! 
We are already having a similar game request in #232 👀 
Make sure you come up with a cool unique idea 😀 
 Waiting for your new game idea 💗.

**Comment by kunjgit** [comment]
Hey @PriyankaTamhankar01 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
