### ISSUE TITLE
Zombie Shooting game

### ISSUE THREAD

**Issue by Vanshikaxxa** [kunjgit/GameZone#3345]
### 🎮 Game Request

A simple zombie shooting game that has:
Player Movement: Allow the player to move horizontally using the arrow keys or by clicking/tapping on the screen.
Zombie Spawn: Spawn zombies randomly on the screen at regular intervals.
Zombie Movement: Zombies move towards the player's position.
Shooting Mechanism: Enable the player to shoot bullets towards the zombies.
Collision Detection: Detect collisions between bullets and zombies to remove them from the screen.
Scoring: Keep track of the player's score by counting the number of zombies shot.
Game Over: End the game if a zombie reaches the player or if the player's health reaches zero.
Restart: Allow the player to restart the game after it's over.

### Point down the features

 Animations for player movement, shooting, and zombie movements to make the game more engaging.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Vanshikaxxa ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @Vanshikaxxa! 🙂 
 It seems like you are not following proper guidelines !! 👀 
 Read documentation properly !!🙏 
 If you have any queries reach out to us on [Discord🕹️](https://discord.gg/fgwk4XZfxG) .

**Comment by kunjgit** [comment]
Hey @Vanshikaxxa ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
