### ISSUE TITLE
[New game]:  Zombie Apocalypse Shooter

### ISSUE THREAD

**Issue by Vanshikaxxa** [kunjgit/GameZone#3346]
### 🎮 Game Request

Game logic and basic description:
Involves player movement, zombie spawning and movement, shooting mechanism with collision detection, health management, scoring, game over handling, and visuals for an engaging experience.

### Point down the features

Game points
Allow the player to move horizontally using the arrow keys or by clicking/tapping on the screen.
Spawn zombies randomly on the screen at regular intervals.
Zombies move towards the player's position.
Enable the player to shoot bullets towards the zombies.
Detect collisions between bullets and zombies to remove them from the screen.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by Vanshikaxxa** [comment]
add gssoc lebel please

**Comment by kunjgit** [comment]
Hey @Vanshikaxxa ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hello @Vanshikaxxa, Time's up!⏰ 
 Sorry for closing your issue! 
 But it's more than a week since we haven't received anything from your side 😢 . 
 Come up with new ideas, create a new issue and make sure you finish it within a week! 🔥 
 All the best! 🚀 
 Happy Hacking! 💗

**Comment by kunjgit** [comment]
Hey @Vanshikaxxa ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
