### ISSUE TITLE
[Enhancement]: Add an alert when last 10 seconds are remaining in Master Typing Game

### ISSUE THREAD

**Issue by theashikagupta** [kunjgit/GameZone#3347]
### Do you want to have the enhancement of existing game ? 😀 Describe yourself..

I want to add an alert that "Type fast! last 10 secs remaining " when last 10 seconds are remaining .

### Describe the solution you'd like

I would like to add an alert for last 10 seconds which appears a message :"Type fast! last 10 secs remaining "

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @theashikagupta ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by theashikagupta** [comment]
OK , So kindly assign me this issue @kunjgit 
after completing this one I will raise another one .May I ?

**Comment by kunjgit** [comment]
Hey @theashikagupta ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
