### ISSUE TITLE
[Feact] :Add clear icon on search bar.

### ISSUE THREAD

**Issue by theashikagupta** [kunjgit/GameZone#3348]
### Do you want to have the enhancement of existing game ? 😀 Describe yourself..

Problem: Like if user search any game on search bar he/she have to use backspace for clear that.

### Describe the solution you'd like

Solution steps:
If we add a clear button to clear the search bar it can enhance the quality of website.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @theashikagupta , You can't have another issue before completing the previous one 😀 
 you already have the following 1 open issues 👀 ! :

#3347

**Comment by kunjgit** [comment]
Hey @theashikagupta ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by kunjgit** [comment]
Hey @theashikagupta ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @theashikagupta! 🙂 
 It seems like you are not following proper guidelines !! 👀 
 Read documentation properly !!🙏 
 If you have any queries reach out to us on [Discord🕹️](https://discord.gg/fgwk4XZfxG) .
