### ISSUE TITLE
[Feacture] Add clear icon on search bar

### ISSUE THREAD

**Issue by theashikagupta** [kunjgit/GameZone#3349]
### Do you want to have the enhancement of existing game ? 😀 Describe yourself..

Game enhancement
like user search any game on search bar so they have to use backspace for clear that.

### Describe the solution you'd like

Solution steps
We should add a clear icon so that it can enhance the website
![Uploading Screenshot 2024-05-16 204842.png…]()

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @theashikagupta , You can't have another issue before completing the previous one 😀 
 you already have the following 1 open issues 👀 ! :

#3347

**Comment by kunjgit** [comment]
Hey @theashikagupta ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by kunjgit** [comment]
Hey @theashikagupta! 🙂 
 It seems like you are not following proper guidelines !! 👀 
 Read documentation properly !!🙏 
 If you have any queries reach out to us on [Discord🕹️](https://discord.gg/fgwk4XZfxG) .
