### ISSUE TITLE
[Documentation Bug]: Anime_Clicker

### ISSUE THREAD

**Issue by Bindusree1515** [kunjgit/GameZone#3350]
### Describe the bug ✍️

Currently, the README.md file of the Anime_Clicker project includes a link instead of an embedded screenshot, which could be improved for better user experience and presentation. It would be beneficial to replace this link with an actual screenshot of the game.

**Steps to Resolve:**

- Capture a screenshot of the Anime_Clicker game.
- Update the README.md file to embed this screenshot directly.
- Ensure the screenshot is clear and representative of the game.

**Screenshot:**
![Screenshot 2024-05-16 202736](https://github.com/kunjgit/GameZone/assets/91887086/f67580a6-38d3-44a0-b7d0-1f4564027b1d)

Please assign me this issue under gssoc'24.

### Provide step by step information reproduce the bug 📄

- Steps to Reproduce the Bug
- Clone Repository
- Navigate to Repository Directory
- Open README.md
- Identifying the Issue
- Locate Screenshot Link
- Steps to Fix the Issue
- Capture Game Screenshot
- Add Screenshot to Repository
- Update README.md
- Finalizing Changes
- Save and Commit

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Bindusree1515 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @Bindusree1515 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
