### ISSUE TITLE
[New game]: Colour_Generator

### ISSUE THREAD

**Issue by DCharishma199** [kunjgit/GameZone#3352]
### 🎮 Game Request

This new innovative game named as Colour_Generator, aimed to be generate a new version of colours at every time. I am developed this code using html, css, javascript. So , coming to the point , firstly open the web and it shows you some random versions of colours , and colour naming codes are also available near that certain colour , what there mentioned . These colours are changed after every refreshing process. So , the advantage of this game is to gain best version of colours which are useful for build some certain web pages, mainly in css applications. So this is the main motive of this game , and logic is mentioned as above. Thank You!!!

### Point down the features

This game points  are 10 out of 10 , because it is not a joy game , it is most required game for developers
![Screenshot 2024-05-16 211529](https://github.com/kunjgit/GameZone/assets/165278939/7abe0898-2f47-4058-8ee2-0feae5deb957)
Look this.... you may got a general idea about this project

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @DCharishma199 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @DCharishma199 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
