### ISSUE TITLE
[New game]:  Tic Tac Toe

### ISSUE THREAD

**Issue by NAVJOT-786** [kunjgit/GameZone#3353]
### 🎮 Game Request

🎮 Game Request: Tic Tac Toe

1: Game Logic Description
Tic Tac Toe is a simple, two-player game that is played on a 3x3 grid. The game logic involves the following steps:

2: Initialization:

The game board is represented as a 3x3 grid.
Two players are identified, Player 1 and Player 2, who will take turns to play.

3: Player Turns:

Players take turns placing their symbol (Player 1 uses "X" and Player 2 uses "O") in an empty cell on the grid.
The game starts with Player 1.

4: Winning Condition:

The game checks for a win after each move. A player wins if they have three of their symbols in a row, column, or diagonal.

5:Draw Condition:

The game ends in a draw if all cells are filled and no player has achieved a winning condition.

6: End of Game:

The game announces the winner or a draw and provides an option to start a new game.

### Point down the features

Features of the Game

1: Player Name Input:

Players can input their names before starting the game, which will be displayed during their turn.

2: Turn Indicator:

The game displays a message indicating whose turn it is.

3: Dynamic Game Board:

The game board is dynamically rendered, and players can click on cells to place their symbols.

4: Winning and Draw Notification:

A modal pop-up announces the winner or a draw at the end of the game.

5: New Game Option:

Players can start a new game by clicking a "New Game" button after the current game ends.

6: Responsive Design:

The game is designed to be responsive and can be played on various screen sizes, including mobile devices.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @NAVJOT-786 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @NAVJOT-786! 
We are already having a similar game request in #3173 👀 
Make sure you come up with a cool unique idea 😀 
 Waiting for your new game idea 💗.

**Comment by kunjgit** [comment]
Hey @NAVJOT-786 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
