### ISSUE TITLE
[Enhancement]: Searchbar AutoSuggestion while typing

### ISSUE THREAD

**Issue by Pratik2401** [kunjgit/GameZone#3354]
### Do you want to have the enhancement of existing game ? 😀 Describe yourself..

To add game names to autsuggestion while typing I have already done it for one project
![Screenshot 2024-05-16 193906](https://github.com/kunjgit/GameZone/assets/105542579/f79ec0ae-279f-4451-9cf9-8581393d390f)

### Describe the solution you'd like

Add object of all game_name
And add it to auto suggestion

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Pratik2401 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by Pratik2401** [comment]
assign

**Comment by kunjgit** [comment]
Hey @Pratik2401 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by Pratik2401** [comment]
Can you pls assign me these I have completed but not assigned
