### ISSUE TITLE
[New game]: Path Finder Puzzle

### ISSUE THREAD

**Issue by Harleen-786** [kunjgit/GameZone#3355]
### 🎮 Game Request

🎮 Game Request: Path Finder Puzzle

Game Logic Description

Path Finder Puzzle is a grid-based game where players must find the shortest path from a start point to an end point. The game uses pathfinding algorithms like A* or Dijkstra's to teach and challenge players with increasing complexity.

1: Initialization:

The game board is a grid of cells.
Players can set the start and end points.
Obstacles can be placed on the grid to create barriers.

2: Player Interaction:

Players can click on cells to set the start point, end point, and obstacles.
A "Find Path" button initiates the pathfinding algorithm.

3: Pathfinding Algorithm:

The game uses pathfinding algorithms like A* or Dijkstra's to find the shortest path.
The algorithm visualizes the pathfinding process step by step.
4: Game End:

The game highlights the found path and displays the path length.
Players can reset the grid to try different configurations.

### Point down the features

Features of the Game

Interactive Grid:

Players can interact with the grid to set start and end points and place obstacles.

Algorithm Visualization:

Real-time visualization of the pathfinding algorithm.
Step-by-step animation showing how the algorithm explores the grid.

Difficulty Levels:

Multiple levels with varying grid sizes and obstacle densities.
Customizable grid for user-generated challenges.

Educational Aspect:

Explanation of the pathfinding algorithms used.
Option to switch between different algorithms to compare their performance.

Reset and Replay:

Button to reset the grid and start a new puzzle.
Option to save and share custom puzzles.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Harleen-786 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by Harleen-786** [comment]
hey please add the lable for gssoc24
