### ISSUE TITLE
[Enhancement]: Give chance again if 6 in dice in snake and ladder

### ISSUE THREAD

**Issue by Pratik2401** [kunjgit/GameZone#3356]
### Do you want to have the enhancement of existing game ? 😀 Describe yourself..

Game enhancement:When user gets a six give chance again to user

### Describe the solution you'd like

Solution steps:
1.check condition if user gets 6
2.give extra chance to user

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Pratik2401 , You can't have another issue before completing the previous one 😀 
 you already have the following 1 open issues 👀 ! :

#3354

**Comment by kunjgit** [comment]
Hey @Pratik2401 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by kunjgit** [comment]
Hey @Pratik2401 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)
