### ISSUE TITLE
[Documentation Bug]: Colour_generator

### ISSUE THREAD

**Issue by DCharishma199** [kunjgit/GameZone#3358]
### Describe the bug ✍️

My code is relatively about colours content. It is almost useful for every single developer.
So bugs are rarely occured in this , almost no bugs are found.
Look into my code once........

 

### Provide step by step information reproduce the bug 📄

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Random Color Generator</title>
    <link rel="stylesheet" href="s.css">
</head>
<body>
    <h1 class="header">Random Color Generator</h1>
    <div class="container">
        
    </div>

    <script src="m.js"></script>
</body>
</html>

/*-------------------- CSS --------------------*/

* {
    margin: 0;
    padding: 0;
    box-sizing: border-box;
}
body {
    min-width: 100vh;
}
.header {
    text-align: center;
    font-size: 40px;
    font-weight: bold;
    color: #000000;
    font-family: Verdana, Geneva, Tahoma, sans-serif;
    margin: 30px;
}

.container {
    width: 100%;
    display: flex;
    justify-content: center;
    /* align-items: center; */
    gap: 20px;
    flex-wrap: wrap;
    padding: 20px;
}

.color {
    width: 200px;
    height: 150px;
    border-radius: 3px;
    background: red;
    font-family: 'Trebuchet MS', 'Lucida Sans Unicode', 'Lucida Grande', 'Lucida Sans', Arial, sans-serif;
    position: relative;
    cursor: pointer;
}

.color .hex-code {
    position: absolute;
    color: white;
    padding: 3px;
    background: #0002;
    left: 0;
    bottom: 0;
    opacity: 0.3;
    text-transform: uppercase;
}
.color:hover .hex-code {
    opacity: 1;
}

//-------------------- Java Script --------------------//

let container = document.querySelector(".container");

for (let i = 0; i < 48; i++) {
    container.innerHTML += `
    <div class="color">
            <span class="hex-code">#1324df</span>
        </div>
    `
}

let colors = document.querySelectorAll(".color");

colors.forEach((color)=>{
    function ranRed(){
        return Math.floor(Math.random() * 255);
    }
    function ranGreen(){
        return Math.floor(Math.random() * 255);
    }
    function ranblue(){
        return Math.floor(Math.random() * 255);
    }
    function rgbToHex(r, g, b) {
        var hexR = r.toString(16).padStart(2, "0");
        var hexG = g.toString(16).padStart(2, "0");
        var hexB = b.toString(16).padStart(2, "0");

        return "#" + hexR + hexG + hexB;
    }

    let hexColor = rgbToHex(ranRed(), ranGreen(),ranblue());
    // console.log(hexColor);
    color.style.backgroundColor = hexColor;
    let hexCode = color.querySelector(".hex-code");
    hexCode.textContent = hexColor;

    // copy code function 
    color.addEventListener("click", (box)=>{
        box.target.style.opacity = 0.8;
        setTimeout(()=>{
            box.target.style.opacity = 1;
        }, 100);
        let hexCode = box.target.querySelector(".hex-code");
        
        if(hexCode.textContent != "copied"){
            let code = hexCode.textContent;
            hexCode.textContent = "copied";
            setTimeout(()=>{
                hexCode.textContent = code;
            }, 1000);
            copyCode(code);
        }

        
    })
});

function copyCode(text) {
    var textarea = document.createElement("textarea");
    textarea.value = text;
    document.body.appendChild(textarea);
    textarea.select();
    document.execCommand("copy");
    document.body.removeChild(textarea);
}

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @DCharishma199 , You can't have another issue before completing the previous one 😀 
 you already have the following 1 open issues 👀 ! :

#3352

**Comment by kunjgit** [comment]
Hey @DCharishma199 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by DCharishma199** [comment]
I am a beginner for this , so please provide me some guidelines.I got a
mail that you closed an issue
So , what's happen??
Is there no chance to me to continue this challenge??
