### ISSUE TITLE
[New game]: HTML5 Controller tester

### ISSUE THREAD

**Issue by Ritax2003** [kunjgit/GameZone#3359]
### 🎮 Game Request

After connecting any gamepad or joystick in computer, user can test the functionalities, including vibration. As of now, gyroscope checking is not available.
![1](https://github.com/kunjgit/GameZone/assets/82272821/68d7fcae-28b6-49af-91e6-f8cb46e3bda9)

### Point down the features

Controller button check
joystick check
Analog trigger check
vibration check

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Ritax2003 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @Ritax2003 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
