### ISSUE TITLE
[New game]: Space Invaders Game

### ISSUE THREAD

**Issue by PriyankaTamhankar01** [kunjgit/GameZone#336]
### 🎮 Game Request

The Space Invaders game is a classic arcade game where the player controls a spaceship at the bottom of the screen and must shoot down waves of descending aliens while avoiding their projectiles. Here's a simplified version of the game logic:

1. Initialize the game:

- Set up the game screen with the player's spaceship at the bottom and a grid of alien invaders at the top.

- Set the score to 0 and the number of lives to a predefined value.

2. Handle player input:

- Listen for player input, typically left/right arrow keys for movement and spacebar for shooting.

- Move the player's spaceship horizontally based on the input.

- If the player presses the spacebar, create a bullet entity and launch it towards the aliens.

3.Update game state:

- Move the alien invaders as a group horizontally and vertically.

- If an alien reaches the edge of the screen, move the entire group down and change their direction.

- Move the player's bullets upward and check for collisions with the aliens.

- Move the alien bullets (if any) downward and check for collisions with the player.

- Update the score based on the number of aliens destroyed.

### Point down the features

Game points

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @PriyankaTamhankar01 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @PriyankaTamhankar01 👋!
 
  @kunjgit here, 
 We have this annoucement to make 📢!! 
 During the time of PR don't alter main index file ! 🙂 
 In main Readme file just use * as a game number during the time we are merging we will add number !! 👀 
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG) if you haven't 😇 
  Thank you 💗!

**Comment by kunjgit** [comment]
Hello @PriyankaTamhankar01, Time's Uppp!⏰ 
 Sorry for closing your issue! 
 But it's more than a week since we haven't received anything from your side 😢 . 
 Come up with new ideas, create a new issue and make sure you finish it within a week! 🔥 
 All the best! 🚀 
 Happy Hacking! 💗

**Comment by kunjgit** [comment]
Hey @PriyankaTamhankar01 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by PriyankaTamhankar01** [comment]
Can I continue working in this issue ?
