### ISSUE TITLE
[Enhancement]: Add Highscore feature for the game 'run and jump'

### ISSUE THREAD

**Issue by Roshr2211** [kunjgit/GameZone#3362]
### Do you want to have the enhancement of existing game ? 😀 Describe yourself..

# Game enhancement
Currently there's no feature to store and display highscore

### Describe the solution you'd like

# Solution steps
- Add a feature to store and display highscore which gets updated once a highscore is reached
![image](https://github.com/kunjgit/GameZone/assets/136987759/3a8d71bb-5e98-4e15-8bb2-abc46f791d5a)

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Roshr2211 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @Roshr2211 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
