### ISSUE TITLE
[Enhancement]: 3D snake game

### ISSUE THREAD

**Issue by Harleen-786** [kunjgit/GameZone#3364]
### Do you want to have the enhancement of existing game ? 😀 Describe yourself..

Describe yourself:

I am a software developer contributing to the GameZone open source project. I have a keen interest in enhancing user experiences and adding valuable features to existing games.

Enter a brief description about the enhancement you need:

The current 3D Snake Game on the website displays only the score. To improve the game's interface and user experience, I propose adding a heading that shows "Total Score" above the current score display. This enhancement will make it clearer to players what the displayed number represents, improving the overall clarity and aesthetic of the game interface.

### Describe the solution you'd like

Describe the solution you'd like:
To enhance the 3D Snake Game, I would like to add a heading above the current score display that reads "Total Score". This change will involve modifying the HTML structure and possibly updating some CSS styles to ensure the heading integrates seamlessly with the existing game interface.

Give steps in which you will solve it:

Review the Current Codebase:

Analyze the existing HTML, CSS, and JavaScript code for the 3D Snake Game to understand how the score is currently displayed.

Modify the HTML:

Add an HTML element for the "Total Score" heading above the current score display element.

Update the CSS:

Ensure the new heading is styled consistently with the rest of the game interface.
Adjust any necessary styles to maintain a clean and visually appealing layout.

Update JavaScript (if needed):

Ensure the JavaScript code properly references the new heading element if any dynamic updates are needed.

Testing:

Test the game to ensure the new "Total Score" heading displays correctly across different browsers and devices.
Verify that the score updates as expected during gameplay and that the overall user experience is enhanced.

Submit the Enhancement:

Commit the changes to the repository.

Submit a pull request with a detailed description of the enhancements made.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Harleen-786 , You can't have another issue before completing the previous one 😀 
 you already have the following 1 open issues 👀 ! :

#3355

**Comment by kunjgit** [comment]
Hey @Harleen-786 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by kunjgit** [comment]
Hey @Harleen-786 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)
