### ISSUE TITLE
[Enhancement]: Rabbit Rush Game

### ISSUE THREAD

**Issue by Changingthegame** [kunjgit/GameZone#3369]
### Do you want to have the enhancement of existing game ? 😀 Describe yourself..

Actually, I was playing the Rabbit Rush game, I liked it but there are some enhancements required in that game such as there is no pause, resume button in it , also there is no catchy background in it which should be there and also there is no best score feature in it .

### Describe the solution you'd like

Firstly , I would like to improve the UI of the game  so that there comes a light colored background and also I want to change the distance score color from red to green and then I want to add on  some new features like Best/High score, resume, pause buttons.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Changingthegame ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by Changingthegame** [comment]
Hello @kunjgit , I have done necessary changes and pull request has been approved and merged. I am closing this issue as I am unable to get assigned and work on another issue in your project.

**Comment by kunjgit** [comment]
Hey @Changingthegame ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
