### ISSUE TITLE
[Enhancement]: Guess the correct logo

### ISSUE THREAD

**Issue by Changingthegame** [kunjgit/GameZone#3371]
### Do you want to have the enhancement of existing game ? 😀 Describe yourself..

I played "Guess the correct logo" game and I found that it needs  a lot of improvements such as when we click on the game to play there comes instructions which are only in white background and black letters it's the first step of game which should be catchy , then there comes the main page of the game in which there is only black background and the game name in white color which should be changed . Also there are only a few logos in this game ; so the logos should be increased and finally there is no replay or restart button in it probably due to lack in the number of logos.

### Describe the solution you'd like

Firstly, I would like to improve the UI of all of the parts I have discussed above and then I will add the remaining features which should be in the game such as the restart button, logo box border designs etc.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Changingthegame , You can't have another issue before completing the previous one 😀 
 you already have the following 1 open issues 👀 ! :

#3369

**Comment by kunjgit** [comment]
Hey @Changingthegame ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by kunjgit** [comment]
Hey @Changingthegame ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by Changingthegame** [comment]
please add label gssoc24
