### ISSUE TITLE
[Bug]:  Dino Runner :  Game starts automatically and  The dinosour can  not be seen on the screen if it  jumps and crosses the barriar of screen

### ISSUE THREAD

**Issue by Tasnuva12** [kunjgit/GameZone#3372]
### Give a brief about the bug ✍️

There should be a start button to start the game when the user wants 
If the dino  jumps and it goes off the screen, it can not be back in the screen 
After game over, the timer of 3 seconds should be live on the screen 

### What is the expected behavior? 🤔

- a start button will be on the screen to start the game 
- if the dino jumps, it wont go off the screen  or there will be an option to get it back on the screen
- the timer   should  be seen running on the screen after game over 

### Provide step by step information reproduce the bug 📄

-open the relevant js and html file 
-modify them to fix the bugs 

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Tasnuva12 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by Tasnuva12** [comment]
i could not tag this issue as gsoc . please consider it as a contribution of this program

**Comment by kunjgit** [comment]
Hey @Tasnuva12 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
