### ISSUE TITLE
[Enhancement]: Add "RATING / FEEDBACK" in the MASTER TYPING game when the game ends.

### ISSUE THREAD

**Issue by ShristiiSharma** [kunjgit/GameZone#3380]
### Do you want to have the enhancement of existing game ? 😀 Describe yourself..

Game enhancement
1.  The "Rating/Feedback" prompt is not displayed when the game ends , if it is displayed then it will add a professional and user-  friendly feature, making players feel their feedback is valued.
2.  Collects valuable player feedback for game improvement.
3.  Encourages continued player interaction and engagement with the game.

### Describe the solution you'd like

Solution steps
1.  I will add a "RATING/FEEDBACK" prompt structure when the game ends.
2.  I will add a logic to display the rating prompt, select a rating, and handle submission or cancellation.
3.  Allows players to rate the game from 1 to 5 stars. On submitting the rating it will show a thankyou message.
4.  Canceling the rating will hide the prompt without saving feedback.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @ShristiiSharma ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @ShristiiSharma ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
