### ISSUE TITLE
[New game]: Letter Sleuth-Word Guesser Game

### ISSUE THREAD

**Issue by swetha5157** [kunjgit/GameZone#3383]
### 🎮 Game Request

Game logic and basic description:
The Word Guesser Game captivates players with its random word challenges and real-time feedback. Guess letters to reveal the hidden word, tracking your progress and remaining attempts. Win or lose messages keep the excitement high, and the restart button ensures endless fun and new challenges every time. 

### Point down the features

Game points:

- **Random Word Challenges:** The game selects a random word from a predefined list, providing a fresh challenge each time you play.
- **Interactive Letter Input:** Players guess one letter at a time, with validation to ensure only valid and new guesses are accepted.
- **Real-Time Progress Display:** Correctly guessed letters are revealed in the word display, with underscores indicating the remaining letters.
- **Attempt Tracking:** The game keeps track of and displays the number of remaining attempts, adding a strategic element.
- **Win/Lose Feedback and Restart Option:** The game displays messages when players win or lose and includes a restart button for continuous play and new word challenges.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @swetha5157 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by swetha5157** [comment]
Please assign to me sir @swetha5157 
thank you

**Comment by kunjgit** [comment]
Hello @swetha5157, Time's up!⏰ 
 Sorry for closing your issue! 
 But it's more than a week since we haven't received anything from your side 😢 . 
 Come up with new ideas, create a new issue and make sure you finish it within a week! 🔥 
 All the best! 🚀 
 Happy Hacking! 💗

**Comment by kunjgit** [comment]
Hey @swetha5157 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
