### ISSUE TITLE
[Bug]: CHESS, The White bishops can't be seen.

### ISSUE THREAD

**Issue by VijaySamant4368** [kunjgit/GameZone#3385]
### Give a brief about the bug ✍️

![image](https://github.com/kunjgit/GameZone/assets/145102345/c9485214-eb1d-46aa-a4c0-29066a01f2d7)
As can be seen in the above image of the chess board, neither of the white images can be seen. It is because there is no image for White Bishop in the assets/image folder

### What is the expected behavior? 🤔

The white bishops should be visible, unless they are taken out by other pieces.

### Provide step by step information reproduce the bug 📄

This bug can be seen, as soon as the game starts.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @VijaySamant4368 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by VijaySamant4368** [comment]
Please also add the level label
