### ISSUE TITLE
[Enhancement]: Adding Animations on Scrolling and Loading

### ISSUE THREAD

**Issue by MHusain22** [kunjgit/GameZone#3398]
### Do you want to have the enhancement of existing game ? 😀 Describe yourself..

Adding animations on scrolling down.

### Describe the solution you'd like

Adding animations library and css animations

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @MHusain22 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by nitish9966** [comment]
@kunjgit I am GSSoC Contributor. Can you assign this issue to me

**Comment by Ankit389** [comment]
you assign this issue to me 

I follow [CONTRIBUTING GUIDELINE] of this project.

**Comment by MHusain22** [comment]
@kunjgit I have joined the discord and please assign me this issue

**Comment by Ankit389** [comment]
All ready join for discord  please assign me issue

**Comment by jayanththalla** [comment]
please assign me

**Comment by MHusain22** [comment]
@kunjgit I have joined the discord and please assign me this issue

**Comment by MHusain22** [comment]
@kunjgit please add the label of gssoc

**Comment by kunjgit** [comment]
Hey @MHusain22 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
