### ISSUE TITLE
[New game]:  Flip - card memory game

### ISSUE THREAD

**Issue by Haricharan0310** [kunjgit/GameZone#34]
### 🎮 Game Request

Game logic and basic description : Flip is a timed card memory game. Uncover two matching symbols in a row to eliminate them from the game. Eliminate all cards as fast as you can to win the game.

### Point down the features

Game points : 
- When starting a level, there's a red bar on top of the screen that shows how much time you have left.
- Click the green cards to see what symbol they uncover and try to find the matching symbol underneath the other cards.
- Uncover two matching symbols in a row to eliminate them from the game.
- Eliminate all cards as fast as you can to win the game.
- The game will save your stats locally, via localStorage.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Haricharan0310 Thank you for raising an issue ❤️ 
But already we are having the similar game request in #14 !!
