### ISSUE TITLE
[New game]: Rock, Paper, Scissor, Spock and Lizard

### ISSUE THREAD

**Issue by prrockzed** [kunjgit/GameZone#340]
### 🎮 Game Request

Rock, paper and scissor was a fun game to play. But rock, paper, scissor, spock and lizard is a more advanced variation of the game and much more fun to play.
The game logic is as follows

![rock___paper___scissors___lizard___spock_by_scificat-d4u389n-741447488](https://github.com/kunjgit/GameZone/assets/97661506/9fc315c3-9127-4a89-83e3-20e74054ba44)

### Point down the features

Game played between two players, and here the other player will be the computer. The game will ask the user to input a character(based on the thing he wants to choose) and computer will randomly choose one of the options. Based on logic implemented in the code, winner will be declared. One can play as much as one wants to. The points of the user will be noted down in the top left.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @prrockzed ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @prrockzed 👋!
 
  @kunjgit here, 
 We have this annoucement to make 📢!! 
 During the time of PR don't alter main index file ! 🙂 
 In main Readme file just use * as a game number during the time we are merging we will add number !! 👀 
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG) if you haven't 😇 
  Thank you 💗!

**Comment by kunjgit** [comment]
Hello @prrockzed, Time's Uppp!⏰ 
 Sorry for closing your issue! 
 But it's more than a week since we haven't received anything from your side 😢 . 
 Come up with new ideas, create a new issue and make sure you finish it within a week! 🔥 
 All the best! 🚀 
 Happy Hacking! 💗

**Comment by kunjgit** [comment]
Hey @prrockzed ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
