### ISSUE TITLE
[New game]: Tic Tac Toe Remix

### ISSUE THREAD

**Issue by dsyste20** [kunjgit/GameZone#3407]
### 🎮 Game Request

I propose to contribute to the GameZone by developing a unique variation of the classic Tic Tac Toe game. This version adds a strategic twist by limiting each player to only three pieces on the board at a time, requiring the first piece placed to be removed once the fourth piece is placed, and so on, until a player wins. 

- Game concept: 'Tic Tac Toe Remix'
- Description: Tic Tac Toe Remix is an innovative take on the traditional Tic Tac Toe game. Players must place their pieces strategically, as each player can only have three pieces on the board at any time. Once a player places their fourth piece, their first piece is automatically removed , adding an extra layer of strategy and challenge to the game.

### Point down the features

Game points
3-piece limit
Classic Tic Tac Toe Rules
User Friendly UI
Sound and Music Effects
Win Sound

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @dsyste20 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @dsyste20! 
We are already having a similar game request in #3173 👀 
Make sure you come up with a cool unique idea 😀 
 Waiting for your new game idea 💗.

**Comment by kunjgit** [comment]
Hey @dsyste20 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
