### ISSUE TITLE
[New game]: Gobblet

### ISSUE THREAD

**Issue by dsyste20** [kunjgit/GameZone#3410]
### 🎮 Game Request

Gobblet is a strategic game where players place and stack pieces to form a line of five. The twist is that players can "gobble" their opponent's pieces by placing a larger piece over a smaller one, creating a dynamic and strategic game.
Gobblet Rule: Players can place their pieces on the board or stack them over their opponent's smaller pieces, effectively taking control of that spot.
Objective: The goal is to form a line of five pieces of your color in any direction (horizontally, vertically, or diagonally) to win the game.
You have different 4 sizes and 2 of each

### Point down the features

Game points

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @dsyste20 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @dsyste20 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
