### ISSUE TITLE
[New game]: Memory Match

### ISSUE THREAD

**Issue by MohanaSrinivas** [kunjgit/GameZone#3413]
### 🎮 Game Request

Game logic and basic description
Technologies used 
1.Html
2.CSS
3.Javascript

### Point down the features

Game points
One Point for Each Match
![Screenshot 2024-05-18 065155](https://github.com/kunjgit/GameZone/assets/128175768/e438e2a4-4334-485e-ab1b-69b991fd4cd6)

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @MohanaSrinivas , You can't have another issue before completing the previous one 😀 
 you already have the following 1 open issues 👀 ! :

#3368

**Comment by kunjgit** [comment]
Hey @MohanaSrinivas ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by kunjgit** [comment]
Hey @MohanaSrinivas ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)
