### ISSUE TITLE
[New game]: Shape Guess Game

### ISSUE THREAD

**Issue by codewithganeshhh** [kunjgit/GameZone#3420]
### 🎮 Game Request

**Game logic and basic description**

- This project is built on a basic web tech stacks such as HTML, CSS and Javascript.
- This is a single-player game.
- The player will tell the shape formed using dots.
- Options are given in the game.
- If player reaches to 10 points will win the game.
- If player looses all the 5 lifes will lose the game.

### Point down the features

**Game points**
- Displaying the current score of the player.
- Implementing a graphical user interface (GUI) for a more interactive experience.
- Adding a background music so that user will not bored from the game as this game is for minded people.
![Screenshot 2024-05-18 090713](https://github.com/kunjgit/GameZone/assets/139307139/e2517523-7c66-4ae7-910d-e81839816edc)

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @codewithganeshhh ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @codewithganeshhh! 
We are already having a similar game request in #3383 👀 
Make sure you come up with a cool unique idea 😀 
 Waiting for your new game idea 💗.

**Comment by kunjgit** [comment]
Hey @codewithganeshhh ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
