### ISSUE TITLE
[New game]: Falling ball game 

### ISSUE THREAD

**Issue by AshishPandey04** [kunjgit/GameZone#3423]
### 🎮 Game Request

Game logic and basic description

- HTML, CSS, and Javascript are used in the creation of this project.
- One player may play this game by using the keyboard's arrow keys.
- The player's score will be kept track of until the player loses.
- If the ball touches the top bar, the player will lose the game.

### Point down the features

Game points

- When a player loses a game, the score will be shown 👍
- The player's greatest score will be stated.
- Putting graphic user interface (GUI) into practice to create a more interactive experience. 
![Screenshot 2024-05-18 102233](https://github.com/kunjgit/GameZone/assets/147474800/149bd120-b0a9-4ad2-90f3-0c5c025692c0)

- The game is still in development phase, will improve the UI of the game. 

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @AshishPandey04 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by mishikagithub** [comment]
I want to do work assign it.

**Comment by kunjgit** [comment]
Hey @AshishPandey04 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
