### ISSUE TITLE
[New game]: Bubble Game !

### ISSUE THREAD

**Issue by Vikranthraosb** [kunjgit/GameZone#3426]
### 🎮 Game Request

Game logic and basic description -

Random numbers are present in each bubble.
A timer is set for 30 seconds.
A target number is given to the player.
Find and click the bubble containing the target number.
Score increases by 10 points and all bubbles refresh.
At the end of the timer, the final score is displayed.
![Screenshot (234)](https://github.com/kunjgit/GameZone/assets/102306707/9dff163a-e898-4e85-b06b-cb3c5a6d35bd)
 

### Point down the features

Game points
Mobile Responsive
Simple UI

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Vikranthraosb ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @PallaviGudupallavi ! , This issue is already assigned to @Vikranthraosb. 💗 
 You can work on other issues 🚀 
 If there is anything wrong you can contact us on [Discord🕹️](https://discord.gg/fgwk4XZfxG)👀

**Comment by kunjgit** [comment]
Hello @Vikranthraosb, Time's up!⏰ 
 Sorry for closing your issue! 
 But it's more than a week since we haven't received anything from your side 😢 . 
 Come up with new ideas, create a new issue and make sure you finish it within a week! 🔥 
 All the best! 🚀 
 Happy Hacking! 💗

**Comment by kunjgit** [comment]
Hey @Vikranthraosb ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
