### ISSUE TITLE
[Enhancement]:  simon game popup and make random play one is computer and other is user

### ISSUE THREAD

**Issue by jayanththalla** [kunjgit/GameZone#3428]
### Do you want to have the enhancement of existing game ? 😀 Describe yourself..

Game enhancement
- I am already done Simon game and experienced.
- I will make attractive game and favicon to Simon game.  
-Simon game instructions are displaying behind. I will make good like as popup

### Describe the solution you'd like

Solution steps 
- Simon game is attractive 
- Two players will play one is computer and other is user
- Popup of the instructions 
- display beside the instructions as button when we press the button will display.
![image](https://github.com/kunjgit/GameZone/assets/121346142/43edfde7-2135-46ef-9784-0dbadf4373b4)
![image](https://github.com/kunjgit/GameZone/assets/121346142/9fe59ca3-b327-4950-a8a0-a612ed2bc3f2)
please assign me @kunjgit @amelia2802 
please assign @pa

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @jayanththalla ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @jayanththalla ! , This issue is already assigned to @mishikagithub. 💗 
 You can work on other issues 🚀 
 If there is anything wrong you can contact us on [Discord🕹️](https://discord.gg/fgwk4XZfxG)👀

**Comment by kunjgit** [comment]
Hey @jayanththalla ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
