### ISSUE TITLE
[Enhancement]: Buttons and description make attractive

### ISSUE THREAD

**Issue by jayanththalla** [kunjgit/GameZone#3430]
### Do you want to have the enhancement of existing game ? 😀 Describe yourself..

Game enhancement
- I am have skills in front end and backend development .
- I have simon game  and others web project 

### Describe the solution you'd like

Solution steps
- Make attractive buttons and description .
- Add title behind the home button
- Add icon to the main page 

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @jayanththalla , You can't have another issue before completing the previous one 😀 
 you already have the following 1 open issues 👀 ! :

#3428

**Comment by kunjgit** [comment]
Hey @jayanththalla ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by kunjgit** [comment]
Hey @jayanththalla ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by jayanththalla** [comment]
please assign me the last one u have assigned me and give to the other one please assign me @kunjgit Please assign me the last task you assigned and gave to someone else. Also, please assign me to @kunjgit.
