### ISSUE TITLE
[New game]: SlideMaster Puzzle

### ISSUE THREAD

**Issue by pani2004** [kunjgit/GameZone#3432]
### 🎮 Game Request

The Tile Slider Puzzle, also known as the sliding puzzle, sliding block puzzle, or sliding tile puzzle, is a combination puzzle that challenges a player to slide pieces along certain routes (usually on a board) to establish a certain end-configuration. The game is often made up of a 3x3 grid where 8 tiles are numbered from 1 to 8, and one slot is left empty, allowing the adjacent tiles to be moved into the empty space.

### Point down the features

Tile Movement: Players can click tiles adjacent to an empty space to move them, aiming to arrange the tiles in numerical order.
Shuffle Function: A button allows players to shuffle the tiles randomly, providing a new challenge each time it's pressed.
Initialization and Setup: On page load, the game initializes and randomly shuffles the tiles to start the game.
User Interface:
Clear Instructions: The game includes a description explaining the objective and how to play, aiding new players.
Interactive Feedback: Tiles respond visually to interactions, with hover effects and scaling animations to indicate active selection.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @pani2004 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by pani2004** [comment]
@kunjgit  can u assign me this?

**Comment by mishikagithub** [comment]
I want to work on this project can you assign it

**Comment by kunjgit** [comment]
Hey @kashisharora9462 ! , This issue is already assigned to @pani2004. 💗 
 You can work on other issues 🚀 
 If there is anything wrong you can contact us on [Discord🕹️](https://discord.gg/fgwk4XZfxG)👀

**Comment by kashisharora9462** [comment]
okay sure!

**Comment by pani2004** [comment]
@kunjgit I have created the PR please review it https://github.com/kunjgit/GameZone/pull/3434#issue-2304047356

**Comment by kunjgit** [comment]
Hey @pani2004 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
