### ISSUE TITLE
[New game]: Technical Mind game 

### ISSUE THREAD

**Issue by Yashgabani845** [kunjgit/GameZone#3435]
### Game logic and basic description
it is similar to mind game which we usually play but there is one more enhancement 
we will use pictures of  diiferent technologies and frameworks we use in software development like node js , express,react,html,vite ,vue etc.

### basic look of this game will be :
![Screenshot (56)](https://github.com/kunjgit/GameZone/assets/127788321/5ea6e409-9388-4379-b58d-2a70158a60c2)

### Game points
each right guess has +5 point and each wrong guess has -1 point 
and each level has fix number of oves which user can play to clear current round and go to next round 

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Yashgabani845 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @Yashgabani845 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
