### ISSUE TITLE
[New game]: Memory Card Flip

### ISSUE THREAD

**Issue by VesperAkshay** [kunjgit/GameZone#3437]
### 🎮 Game Request

Game logic and basic description

# Memory Card Game

## Game Description
Memory card game is a classic matching game where players try to find pairs of identical cards by flipping over two cards at a time. The game is played with a deck of cards that have identical pairs, with the pairs being hidden face-down on a grid. The objective is to find all the matching pairs by remembering the locations of the cards.

### 1. Setup:
- Create a deck of cards with identical pairs. The number of cards depends on the size of the game board.
- Shuffle the deck and place the cards face-down on a grid, forming the game board.

### 2. Player's Turn:
- The player selects two cards by clicking or tapping on them to flip them over and reveal their faces.
- If the two revealed cards match, the player scores a point and the cards are removed from the game board.
- If the two revealed cards do not match, the cards are flipped back over, and the player's turn ends.

### 3. Scoring:
- Each time a player finds a matching pair, they score one point.
- The goal is to find all the matching pairs to accumulate the highest score.

### 4. Game End:
- The game ends when all the matching pairs have been found, and the player with the highest score wins.

### 5. Gameplay Mechanics:
- The player can only reveal two cards at a time.
- The player must remember the locations of the cards they have already revealed to find matching pairs.
- If the two revealed cards do not match, they are flipped back over, and the player's turn ends.
- The game can be designed with different grid sizes and card quantities to adjust the difficulty level.

### 6. Additional Features:
- Time limit: The game can be timed, and the player with the fastest time to find all the matching pairs wins.
- Leaderboard: The game can keep track of high scores and display a leaderboard for players to compete against each other.
- Difficulty levels: The game can offer different difficulty levels by adjusting the grid size and the number of cards.

This is a basic implementation of the memory card game. You can further enhance the game by adding sound effects, visual animations, and other interactive features to make the gameplay more engaging and enjoyable for the players.

### Point down the features

Game points

#### Time Limit:
- The game can be timed, and the player with the fastest time to find all the matching pairs wins.
- Game Points: 5 bonus points for the fastest time to find all matching pairs.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by VesperAkshay** [comment]
Assign me this issue for Gsso24

**Comment by kunjgit** [comment]
Hey @VesperAkshay ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @VesperAkshay ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
