### ISSUE TITLE
[New game]: Add New Game BlackJack

### ISSUE THREAD

**Issue by codewithishu** [kunjgit/GameZone#3447]
### 🎮 Game Request

Game Logic:
Objective: The primary goal in Blackjack is to have a hand value closer to 21 than the dealer's hand without exceeding 21.

Card Values:

Number cards (2-10) are worth their face value.
Face cards (Jack, Queen, King) are each worth 10 points.
Aces can be worth either 1 or 11 points, depending on which value benefits the hand most.
Gameplay:

.Initial Deal: Each player and the dealer are dealt two cards. Players’ cards are usually dealt face up, while the dealer has one card face up (the "Up Card") and one card face down (the "hole card").

.Player Decisions:
Hit: Take another card from the dealer.
Stand: Keep the current hand and end the turn.

Double Down: Double the initial bet and take exactly one more card.

Split: If the first two cards are of the same value, the player can split them into two separate hands, each with its own bet. Players then play each hand individually.

Surrender: Forfeit half the bet and end the hand immediately (only available as the first decision of the hand).
Dealer Rules: After all players have finished their turns, the dealer reveals the hole card. The dealer must hit until their cards total 17 or higher (some casinos require the dealer to hit on a "soft 17," which is a hand containing an Ace counted as 11).
Winning:

A player wins if their hand total is higher than the dealer's hand total without exceeding 21.
A player wins with a "Blackjack" (an Ace and a 10-value card) if the dealer does not also have a Blackjack.
If the dealer busts (exceeds 21), all remaining players win.
If a player busts, they lose regardless of the dealer’s outcome.

### Point down the features

Game Points:
Points Calculation:

The total value of a player's hand is the sum of the individual card values.
If a player's hand includes an Ace, it can be counted as 1 or 11, depending on which value keeps the hand total under or equal to 21.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @codewithishu ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by codewithishu** [comment]
@kunjgit please assign this to me

**Comment by kunjgit** [comment]
Hey @codewithishu ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by kunjgit** [comment]
Hey @codewithishu ! , This issue is already assigned to @codewithishu. 💗 
 You can work on other issues 🚀 
 If there is anything wrong you can contact us on [Discord🕹️](https://discord.gg/fgwk4XZfxG)👀

**Comment by kunjgit** [comment]
Hey @codewithishu ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
