### ISSUE TITLE
[Bug]: Search Box should take less space with the logo

### ISSUE THREAD

**Issue by codewithishu** [kunjgit/GameZone#3448]
### Give a brief about the bug ✍️

Description:
Search box takes a huge gap with the logo which reduces the beauty of UI/UX

### What is the expected behavior? 🤔

Description:
Search Box should take less space with the logo for the enhancement of user interface and user experience

### Provide step by step information reproduce the bug 📄

Description:
It will  reduce the gap using
1. [position :absolute/relative] feature
2. Marging 
3. Padding 

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @codewithishu , You can't have another issue before completing the previous one 😀 
 you already have the following 1 open issues 👀 ! :

#3447

**Comment by kunjgit** [comment]
Hey @codewithishu ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by kunjgit** [comment]
Hey @codewithishu ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)
