### ISSUE TITLE
[New game]: Color Blast 

### ISSUE THREAD

**Issue by AtharvaShinde253** [kunjgit/GameZone#3451]
### 🎮 Game Request

Game logic and basic description
Color Blast is an exciting web-based game created using HTML, CSS, and JavaScript. The game is set in a vibrant, fast-paced environment where the player controls an object that must navigate left and right by dodging and firing at incoming threats. The game emphasizes quick reflexes and strategic movement, providing an engaging experience for players of all ages.

### Point down the features

Game points
1.Implement lives in the game, means when you get hit you lose a live.
2.Can pause the game by clicking on the screen.
3.Have live score by which you can compete with your friends.
4.Require quick reflexes to dodge as well as fire bullets.
5.Very engaging and fun game.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @AtharvaShinde253 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @AtharvaShinde253 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
