### ISSUE TITLE
[New game]: Rat Hammer Game

### ISSUE THREAD

**Issue by cxde-Sujal** [kunjgit/GameZone#3455]
### 🎮 Game Request

Game logic and basic description
The Rat Hammer game is a fast-paced, fun-filled game where players use a hammer to hit rats that pop up from holes. The goal is to hit as many rats as possible within a given time frame to score points.
How to Play:

Start the Game: 
The game begins when the player presses the start button.
Rats Appear: Rats randomly pop up from the holes on the game board.
Hit the Rats: The player uses the hammer to hit the rats before they disappear back into the holes.
Scoring Points: Each rat hit by the player will earn points. The game continues until the timer runs out.
End of Game: When the time is up, the game stops, and the final score is displayed.

### Point down the features

Game points
Scoring Points in the Rat Hammer Game
Basic Scoring Rules:

Each rat hit earns the player a certain number of points.
Points per rat can vary based on the type or speed of the rat.
Point Allocation:

Regular Rat: 10 points each
Speedy Rat: 20 points each (these rats appear and disappear quickly)
Golden Rat: 50 points each (rare and valuable, harder to hit)
Bonus Points:

Combo Hits: Hitting multiple rats in quick succession may earn bonus points (e.g., hitting 3 rats within 5 seconds might give an extra 30 points).
Streak Bonus: Maintaining a hit streak (hitting a rat without missing for a certain number of times) can provide additional points.
Deductions:

Missed Hits: Some games might deduct points for hitting holes without rats, encouraging accuracy (e.g., -5 points for each miss).
Advanced Features:

Level Progression: As the player scores more points, the game can increase in difficulty by making rats pop up faster or appear more sporadically.
Time Bonuses: Extra time can be awarded for reaching certain score thresholds during the game, allowing for more opportunities to score points.
Example Scoring Scenario
The player hits 15 regular rats (15 x 10 = 150 points).
The player hits 5 speedy rats (5 x 20 = 100 points).
The player hits 1 golden rat (1 x 50 = 50 points).
The player gets a combo bonus for hitting 3 rats within 5 seconds twice (+60 points).
Total score = 150 + 100 + 50 + 60 = 360 points.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @cxde-Sujal , You can't have another issue before completing the previous one 😀 
 you already have the following 1 open issues 👀 ! :

#3454

**Comment by kunjgit** [comment]
Hey @cxde-Sujal ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by kunjgit** [comment]
Hey @cxde-Sujal ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by cxde-Sujal** [comment]
which issue am i attached to for now
