### ISSUE TITLE
[Enhancement]: Time control for master Typing and little UI Changes

### ISSUE THREAD

**Issue by anisharma07** [kunjgit/GameZone#3457]
### Do you want to have the enhancement of existing game ? 😀 Describe yourself..

Game enhancement - Master Typing
The existing game master typing allows user to type for 1:00 min fixed time.. but if they want timer of their choice, that is not possible at the frontend...... so I want to include that feature, so game could become more engaging.

### Describe the solution you'd like

Solution steps:
1. use javascript and Html for time selection.
2. use better css for typing result popup

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @anisharma07 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @anisharma07 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
