### ISSUE TITLE
[Enhancement]: simon game popup and icon to title of the page

### ISSUE THREAD

**Issue by jayanththalla** [kunjgit/GameZone#3458]
### Do you want to have the enhancement of existing game ? 😀 Describe yourself..

Game enhancement
I have skills in front-end and backend development.
I have Simon game and other web project
back-end

### Describe the solution you'd like

Solution steps
-I am already done Simon's game and experienced.
-I will make an attractive game and favicon to Simon's game.
-Simon's game instructions are displayed behind. I will make good like a popup
Popup of the instructions
-display beside the instructions as a button when we press the button.
![image](https://github.com/kunjgit/GameZone/assets/121346142/fd02ec3c-0564-4cb9-bfd2-737a9371973b)
![image](https://github.com/kunjgit/GameZone/assets/121346142/90e93183-bfdc-41af-a52c-8e0c95f5c7b8)

please assign me @kunjgit @amelia2802Simon's

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @jayanththalla , You can't have another issue before completing the previous one 😀 
 you already have the following 1 open issues 👀 ! :

#3428

**Comment by kunjgit** [comment]
Hey @jayanththalla ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by kunjgit** [comment]
Hey @jayanththalla ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)
