### ISSUE TITLE
[New game]: dice roller

### ISSUE THREAD

**Issue by Vipullakum007** [kunjgit/GameZone#3460]
### 🎮 Game Request

Game logic and basic description : we have one dice or many dices of different no of sides. we use the dice for play different games which needs dice to roll.

### Point down the features

Game points : roll the dice
we can add more dices of diff no of sides

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Vipullakum007 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by Vipullakum007** [comment]
assign issue to me as GSSOC'24

**Comment by kunjgit** [comment]
Hey @Vipullakum007 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
