### ISSUE TITLE
[Enhancement]: Master Typing Score Keeper

### ISSUE THREAD

**Issue by KrishnaKalra** [kunjgit/GameZone#3464]
### Do you want to have the enhancement of existing game ? 😀 Describe yourself..

The game does not provide the user with data on the number of keys that were correctly or incorrectly pressed. We can also give the user information about the key that was pressed incorrectly the most number of times at the end of game.

### Describe the solution you'd like

Solution steps
1. Changes in CSS and HTML to add new counters to keep track of the scores for correct and incorrect key presses.
2. Changes in JavaScript to update the counters and turn the keys red that were pressed incorrectly the most number of times at the end of the game.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @KrishnaKalra ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @KrishnaKalra ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
