### ISSUE TITLE
[New game]: Dinosaur Game

### ISSUE THREAD

**Issue by Yashgabani845** [kunjgit/GameZone#3465]
### 🎮 Game Request

Game logic and basic description

i know everyone has played game of dainosour which comes in chrome after intenet connection failed 
i want to add that game in thia gamezone
![images](https://github.com/kunjgit/GameZone/assets/127788321/2068c2d3-b7d0-4135-bda0-92a08d3b464d)

### Point down the features

Game points
-this will be simulator game
- points wil be incrsed by time
-you will have your best score which will updated

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Yashgabani845 , You can't have another issue before completing the previous one 😀 
 you already have the following 1 open issues 👀 ! :

#3435

**Comment by kunjgit** [comment]
Hey @Yashgabani845 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by kunjgit** [comment]
Hey @Yashgabani845 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @Yashgabani845! 
We are already having a similar game request in #3244 👀 
Make sure you come up with a cool unique idea 😀 
 Waiting for your new game idea 💗.
