### ISSUE TITLE
[New game]: Word_Guessing_Game

### ISSUE THREAD

**Issue by SJ-Kumar** [kunjgit/GameZone#347]
### 🎮 Game Request

Game logic and basic description

The game randomly selects a word from a list and provides the player with eight attempts to guess the word. After each guess, the player is informed if the guessed letter is correct or not. On the fourth guess, the player has the option to request a clue revealing the first and last letter of the word. At the end, the player can guess the entire word, and if correct, they win; otherwise, the correct word is displayed.

### Point down the features

Game points

Random Word Selection: A word is randomly chosen from a predefined list of words for each game session.
Limited Attempts: The player is given a specific number of attempts (8 in this case) to guess the word correctly.
Single Letter Guesses: The player can guess a single letter at a time and is provided feedback on whether the letter is present in the word.
Clue System: After the player's fourth guess, they have the option to request a clue, which reveals the first and last letter of the word.
Whole Word Guess: The player can make a final guess by entering the entire word, and if correct, they win the game.
Feedback and Display: The game provides feedback on each guess, displays the letters guessed correctly so far, and reveals the correct word if the player fails to guess it.
User Interaction: The game prompts the player for their name, welcomes them, and allows them to interact by entering inputs.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @SJ-Kumar ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hello @SJ-Kumar, Time's Uppp!⏰ 
 Sorry for closing your issue! 
 But it's more than a week since we haven't received anything from your side 😢 . 
 Come up with new ideas, create a new issue and make sure you finish it within a week! 🔥 
 All the best! 🚀 
 Happy Hacking! 💗

**Comment by kunjgit** [comment]
Hey @SJ-Kumar ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
