### ISSUE TITLE
[New game]: Mole Game

### ISSUE THREAD

**Issue by bhaveshnegi** [kunjgit/GameZone#3471]
### 🎮 Game Request

Overview

The Mole Game is a simple, interactive whack-a-mole type game built using JavaScript, HTML, and CSS. The objective of the game is to click on the moles that appear randomly on a 3x3 grid to score points, while avoiding clicking on the plants, which will end the game.

### Point down the features

Features

- Interactive Gameplay: Click on moles to gain points.
- Random Tile Generation: Moles and plants appear in random tiles at set intervals.
- Score Tracking: Your score is updated in real-time as you click on moles.
- Game Over: Clicking on a plant ends the game and displays your final score.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @bhaveshnegi ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @bhaveshnegi! 
We are already having a similar game request in #3338 👀 
Make sure you come up with a cool unique idea 😀 
 Waiting for your new game idea 💗.

**Comment by kunjgit** [comment]
Hey @bhaveshnegi ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
