### ISSUE TITLE
[New game]: Tower Builder Game

### ISSUE THREAD

**Issue by bhaveshnegi** [kunjgit/GameZone#3474]
### 🎮 Game Request

This is a simple Tower Builder game built using HTML, CSS, and JavaScript. The objective of the game is to build a tower as high as possible by stacking blocks on top of each other. The player earns points for each successful block placement.

How to Play

- Click anywhere on the game area to drop a block.
- Stack blocks on top of each other to build a tower.
- Earn points for each successful block placement.
- Be careful not to miss the tower, as dropping a block off the tower ends the game.

### Point down the features

Features

- Simple and intuitive gameplay.
- Responsive design suitable for various screen sizes.
- Score display to track the player's progress.
- Game over alert with final score.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @bhaveshnegi! 
We are already having a similar game request in #3427 👀 
Make sure you come up with a cool unique idea 😀 
 Waiting for your new game idea 💗.

**Comment by kunjgit** [comment]
Hey @bhaveshnegi ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by bhaveshnegi** [comment]
hello @kunjgit i have check out #3473 game which is different from my game
