### ISSUE TITLE
[New game ] : Tic fac toe game 

### ISSUE THREAD

**Issue by msifran** [kunjgit/GameZone#3475]
### 🎮 Game Request

The Tic Tac Toe game is a two-player game where players take turns marking spaces in a 3x3 grid. The player who succeeds in placing three of their marks in a horizontal, vertical, or diagonal row wins the game. If all nine spaces are filled without a winner, the game ends in a draw.

### Point down the features

- [ ] Initial Setup
- [ ]  Player Turns
- [ ] Marking the Grid
- [ ] Check for Win or Draw
- [ ] Resetting the Game
- [ ] Interactive Grid
- [ ] Player Indicators
- [ ] Win and Draw Detection
- [ ] Responsive Design
- [ ] Reset Button
- [ ] Stylish UI:

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @msifran , You can't have another issue before completing the previous one 😀 
 you already have the following 1 open issues 👀 ! :

#3313

**Comment by kunjgit** [comment]
Hey @msifran ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by kunjgit** [comment]
Hey @msifran ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)
