### ISSUE TITLE
[New game]: Block Building

### ISSUE THREAD

**Issue by bhaveshnegi** [kunjgit/GameZone#3476]
### 🎮 Game Request

Game logic and basic description
- Focuses on traditional Block-building gameplay without dynamic environments.

### Point down the features

Game points

- Precision and Timing: Emphasizes precision and timing in placing blocks to maintain stability and height.
- Stability Challenge: Challenges players to carefully place each block to prevent the tower from collapsing.
- Simplicity: Provides a straightforward gameplay experience without additional obstacles or power-ups.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @bhaveshnegi ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by bhaveshnegi** [comment]
PR Number #3488 please merge this PR

**Comment by kunjgit** [comment]
Hey @bhaveshnegi ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
