### ISSUE TITLE
[Bug]: Mobile responsiveness of search bar

### ISSUE THREAD

**Issue by anisharma07** [kunjgit/GameZone#3479]
### Give a brief about the bug ✍️

Thereis a bug in seach bar which makes the home page unresponsive for mobile... I know about mobile responsiveness... so please assign me this issue

### What is the expected behavior? 🤔

website should be properly visible in mobile

### Provide step by step information reproduce the bug 📄

use of css media queries will be helpful

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @anisharma07 , You can't have another issue before completing the previous one 😀 
 you already have the following 1 open issues 👀 ! :

#3457

**Comment by kunjgit** [comment]
Hey @anisharma07 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by kunjgit** [comment]
Hey @anisharma07 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)
