### ISSUE TITLE
[Enhancement]: Add Copyright Line to Footer Section

### ISSUE THREAD

**Issue by jency1** [kunjgit/GameZone#3480]
### Do you want to have the enhancement of existing game ? 😀 Describe yourself..

The website currently does not have a copyright line in the footer section. Adding this line will provide important legal information and establish ownership of the website content.

I am GSSOC'24 contributor and would like to contribute in this project, so assign this task to me.

### Describe the solution you'd like

1. Add HTML
2. Add CSS (if necessary)
3. Testing

Ensure the copyright line is visible and correctly styled across different browsers and devices.
Verify that the addition does not affect the existing footer layout and content.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @jency1 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @jency1 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
