### ISSUE TITLE
[New game]: Bottle Flip Game

### ISSUE THREAD

**Issue by VaibhavS0710** [kunjgit/GameZone#3484]
### 🎮 Game Request

Game logic and basic description
So basically the logic behind this game is that when the user click on the bottle the bottle will flip on its respective position. If it lands correctly then the user will get one point and if it doesn't lands correctly then there will be an option of restart.

### Point down the features

Game points
1. Animated Bottle Flip:
    Enhance the flip animation to include rotation and smooth transition effects.

2. Landing Check:
   Implement a more realistic physics-based check to determine if the bottle lands correctly.

3. Scoreboard:
   Display the current score and the highest score achieved in the session.

4. Sound Effects:
   Add sound effects for successful flips and failed attempts.

5. Background Music:
   Play background music that can be toggled on or off.

6. Responsive Design:
   Ensure the game works well on different screen sizes, including mobile devices.

7. Flip Count and Timer:
   Track the number of flips and display a timer for timed challenges.

8. Difficulty Levels:
   Add different difficulty levels that change the success probability or flip dynamics.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @VaibhavS0710 , You can't have another issue before completing the previous one 😀 
 you already have the following 1 open issues 👀 ! :

#3148

**Comment by kunjgit** [comment]
Hey @VaibhavS0710 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by kunjgit** [comment]
Hey @VaibhavS0710 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)
