### ISSUE TITLE
[Enhancement]: Add clear icon and clear feature on search bar of website .

### ISSUE THREAD

**Issue by theashikagupta** [kunjgit/GameZone#3486]
### Do you want to have the enhancement of existing game ? 😀 Describe yourself..

Game enhancement
Enhancement of search bar to add clear icon on it.

### Describe the solution you'd like

Solution steps
Javascript function to clear the search bar on clicking the clear icon.
![Screenshot 2024-05-19 194928](https://github.com/kunjgit/GameZone/assets/136061047/0f6b7f00-e17e-4d9d-89cb-babbce831cc3)
 

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @theashikagupta ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @theashikagupta ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
