### ISSUE TITLE
[Enhancement]: CHESS game

### ISSUE THREAD

**Issue by VijaySamant4368** [kunjgit/GameZone#3489]
### Do you want to have the enhancement of existing game ? 😀 Describe yourself..

![image](https://github.com/kunjgit/GameZone/assets/145102345/c9485214-eb1d-46aa-a4c0-29066a01f2d7)
As can be seen in the above image of the chess board, neither of the white images can be seen. It is because there is no image for White Bishop in the assets/image folder

### Describe the solution you'd like

I will add images of white bishop of the same style to match with the overall game experience.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @VijaySamant4368 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @VijaySamant4368 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
