### ISSUE TITLE
[New game]: Coloron

### ISSUE THREAD

**Issue by AtharvaShinde253** [kunjgit/GameZone#3490]
### 🎮 Game Request

Game logic and basic description
In Coloron, players are immersed in a vibrant and fast-paced game where precision and quick thinking are key. The main objective is simple yet addictive: guide a bouncing ball as it traverses across a series of tiles, ensuring that the color of the tile matches the color of the ball at each bounce.You have to tap at the tiles to change its color in order to stay alive in the game.

### Point down the features

Game points
1.The ball changes its color per bounce.
2.Adding 3 colors namely red,yellow and violet.
3.1 point per correct color match.
4.If you fail to match the color of ball and tile you lose.
5.You can play with your share as well as share your score on the twitter.
6.You can click on play again button to play.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @AtharvaShinde253 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @AtharvaShinde253 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
