### ISSUE TITLE
Tic-Tac-Toe

### ISSUE THREAD

**Issue by Sindhu-2004** [kunjgit/GameZone#3496]
### 🎮 Game Request

Tic Tac Toe is a classic two-player game played on a 3x3 grid. Players take turns marking the empty spaces in the grid with an "X" or "O" (usually chosen beforehand).

The objective is to be the first player to get three of your marks in a horizontal, vertical, or diagonal row. The game can also end in a tie if all nine squares are filled and no player has achieved a winning row.

The logic:

* Turns alternate between players.
* Each turn, a player chooses an empty square on the grid and marks it with their symbol.
* The game checks after every turn if the current player has created a winning row.
* If a winning row is found, the game ends and the current player is declared the winner.
* If all squares are filled and no winning row is found, the game ends in a tie.

The simplicity of the rules and the small grid make it a perfect game for beginners, but there's also some strategy involved in trying to block your opponent's moves and setting yourself up for a winning row.

### Gameplay:
  
- **Two Player Mode:** 
  - Play against an opponent.
  - Challenge a friend on the same device.

- **Visual Board:** 
  - Clear and customizable 3x3 grid to track the game.
  - High-resolution graphics and smooth animations.

- **Turn Indicators:** 
  - Show whose turn it is to play (X or O).
  - Visual cues to indicate the player's turn.

- **Win Detection:** 
  - Automatically identify winning rows and declare the victor.
  - Highlight the winning combination.

- **Tie Detection:** 
  - Recognize a full board with no winner.
  - Display a message for a draw and offer a rematch option.

- **Match Statistics:** 
  - Track your wins, losses, and ties.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Sindhu-2004! 🙂 
 It seems like you are not following proper guidelines !! 👀 
 Read documentation properly !!🙏 
 If you have any queries reach out to us on [Discord🕹️](https://discord.gg/fgwk4XZfxG) .

**Comment by kunjgit** [comment]
Hey @Sindhu-2004 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @Sindhu-2004 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
