### ISSUE TITLE
[New game]: Color Blast

### ISSUE THREAD

**Issue by Roshnijeewani3457** [kunjgit/GameZone#35]
### 🎮 Game Request

The Color Blast is a game about colorful enemies attacking the main character, that is the player. 

To win the game, the player has to dodge the colorful bullets while firing them with white ones. There will be enemies attacking from all the top sections and you have to defeat them all single-handedly. However, each time you get hit by an enemy, you will lose a life and after a few seconds, you will respawn. But after four such attacks, the game will be over.

**How to Control the Game:**
 A - Move to the left.
 D - Move to the right.
 Spacebar - Firing at the enemies.

This can be done using Html,css and js

### Point down the features

**Safety is First**
The main priority of this game is to save yourself from the dozens of enemies attacking you at once. The enemies will keep shooting continuously which increases the chances of you getting hit. Thus, save yourself first and then attack the enemies to last longer in the game.

**Keep Firing Blindly**
Once you see that you are safe from the attacks, attack blindly at the opponents. No matter if any shot is missed, some will still be hit and the enemies will be gone. This will increase the chance of destroying the opponents and scoring maximum points.

**Focus on Controls**
To gain the highest score possible, focus on all the controls, move left or right as needed and shoot the opponent to destroy them all.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Roshnijeewani3457  ! Thank you for raising an issue 💗 You have been assigned this issue you can start working on the issue 🎮

**Comment by Roshnijeewani3457** [comment]
Thank you @kunjgit for assigning me this task!!

**Comment by kunjgit** [comment]
Hello @Roshnijeewani3457, Time's Uppp!⏰ 
 Sorry for closing your issue! 
 But it's more than a week since we haven't received anything from your side 😢 . 
 Come up with new ideas, create a new issue and make sure you finish it within a week! 🔥 
 All the best! 🚀 
 Happy Hacking! 💗

**Comment by kunjgit** [comment]
Hey @Roshnijeewani3457 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
