### ISSUE TITLE
[Enhancement]: Adding Sleek and Classy custom fonts for thew website homepage

### ISSUE THREAD

**Issue by Winter262005** [kunjgit/GameZone#3504]
### Do you want to have the enhancement of existing game ? 😀 Describe yourself..

I want to enhance the look of the website homepage by adding custom fonts which will make it look welcoming.

### Describe the solution you'd like

I will be working on the CSS of the website and will add custom web open font files (.woff) files to the website code which will add new fonts to the site.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Winter262005 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by toodiv** [comment]
I can contribute to the issue with a clean and efficient code. Kindly accept my issue under GSSOC'24.

**Comment by kunjgit** [comment]
Hey @Winter262005 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
