### ISSUE TITLE
[New game]: Contra

### ISSUE THREAD

**Issue by VesperAkshay** [kunjgit/GameZone#3505]
### 🎮 Game Request

Game logic and basic description

# Contra

## Overview

Contra is a classic side-scrolling action game developed and published by Konami in 1987. It is known for its challenging gameplay, intense action, and iconic run-and-gun mechanics.

## Gameplay

In Contra, players take on the role of either Bill Rizer or Lance Bean, highly skilled commandos tasked with infiltrating and defeating an alien invasion force known as the Red Falcon Organization. The game features fast-paced, run-and-gun gameplay where players must navigate through a series of side-scrolling levels, eliminating enemies and obstacles while avoiding hazards and powerful bosses.

The game's signature feature is the ability to execute a "Spread Shot", a devastating weapon that fires multiple projectiles in a wide arc, allowing players to mow down hordes of enemies with ease. Players can also collect various power-ups and weapon upgrades throughout the game to enhance their firepower and survivability.

## Legacy

Contra is considered a landmark in the run-and-gun genre and has had a lasting impact on video game history. It has spawned numerous sequels and spin-offs, and its influence can be seen in many modern action-packed games. The game's iconic status and challenging gameplay have made it a beloved classic for generations of gamers.

### Point down the features

Game points

## Key Features

- **Intense Action**: Contra is renowned for its lightning-fast and relentless action, with waves of enemies, challenging boss battles, and intricate level designs that test the player's reflexes and skill.

- **Iconic Weapons**: The "Spread Shot" is the game's most iconic weapon, allowing players to unleash a barrage of bullets and clear the screen of foes.

- **Co-op Gameplay**: Contra supports two-player co-op, allowing players to team up and tackle the alien threat together.

- **Challenging Difficulty**: Contra is known for its high level of difficulty, requiring players to master the game's mechanics and patterns to progress through the levels.

- **Memorable Soundtrack**: The game's driving, synth-heavy soundtrack, composed by Hidenori Maezawa and Takashi Yoshioka, is a cherished part of Contra's legacy.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @VesperAkshay ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @VesperAkshay ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
