### ISSUE TITLE
Pallindrome Guessing Game

### ISSUE THREAD

**Issue by Damini2004** [kunjgit/GameZone#3508]
### 🎮 Game Request

The Palindrome Guessing Game is a simple game where the computer generates a random palindrome, and the player has to guess the palindrome within a certain number of attempts. Here's a basic description of the game logic:

1.The computer generates a random palindrome.
2.The player is asked to guess the palindrome.
3.If the player's guess is correct, they win the game.
4.If the player's guess is incorrect, they are given a hint about the palindrome (e.g., the first and last letter of the palindrome).
5.The player is given a certain number of attempts to guess the palindrome. If they run out of attempts, they lose the game.

### Point down the features

- The game involves generating a random palindrome of a given length.
- The player is asked to guess the palindrome within a certain number of attempts.
- If the player's guess is correct, they win the game.
- If the player's guess is incorrect, they are given a hint about the first and last letter of the palindrome.
- The game can be customized by changing the length of the palindrome and the number of attempts allowed.
- The game can be implemented using a programming language such as Javascript.
- The game can be used as a fun and educational way to teach players about palindromes and programming concepts such as loops and input/output.
- The game can be extended by adding additional features such as scorekeeping, time limits, or multiple rounds.
- The game can be adapted for different age groups and skill levels by adjusting the length of the palindrome and the number of attempts allowed.
- The game can be played by a single player or in a multiplayer setting, where each player takes turns guessing the palindrome.

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Damini2004! 🙂 
 It seems like you are not following proper guidelines !! 👀 
 Read documentation properly !!🙏 
 If you have any queries reach out to us on [Discord🕹️](https://discord.gg/fgwk4XZfxG) .

**Comment by kunjgit** [comment]
Hey @Damini2004 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @Damini2004 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
