### ISSUE TITLE
[New game]: Air bomb game

### ISSUE THREAD

**Issue by tanvigarg264** [kunjgit/GameZone#351]
### 🎮 Game Request

Game logic and basic description: In this game aeroplanes will fligh and the mission is to bomb them by clicking over them. only 15seconds are provided to the player

### Point down the features

Game points 1 good background
                      2 responsive game
                      3 timer
                      4 score board

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @tanvigarg264 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @tanvigarg264! 
We are already having a similar game request in #259 👀 
Make sure you come up with a cool unique idea 😀 
 Waiting for your new game idea 💗.
