### ISSUE TITLE
[New game]: Anagram checker Game

### ISSUE THREAD

**Issue by Damini2004** [kunjgit/GameZone#3510]
### 🎮 Game Request

Game logic and basic description
The game generates two random words from a list of English words.
The game scrambles the letters of each word to create two anagrams.
The player is presented with the two anagrams and asked to unscramble them to form a valid English word pair.
If the player's guess is correct, they win the game.
If the player's guess is incorrect, they are given a hint about the possible word pair.
The player is given a certain number of attempts to guess the correct word pair. If they run out of attempts, they lose the game.

### Point down the features

Game points
The game involves generating two random words and scrambling their letters to create anagrams.
The player is asked to unscramble the anagrams to form a valid English word pair.
The game can be customized by changing the list of English words used to generate the anagrams.
The game can be implemented using a programming language such as Javascript.
The game can be used as a fun and educational way to teach players about anagrams and English vocabulary.
The game can be extended by adding additional features such as scorekeeping, time limits, or multiple rounds.
The game can be adapted for different age groups and skill levels by adjusting the length and difficulty of the words used to generate the anagrams.
The game can be played by a single player or in a multiplayer setting, where each player takes turns guessing the correct word pair.
The game can be integrated with a dictionary API or database to validate the player's guesses and provide hints.
The game can be made more challenging by increasing the number of anagrams or by adding a time limit for each guess.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Damini2004 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by Damini2004** [comment]
Kindly assign this issue to me under GSSOC24 under proper level.

**Comment by kunjgit** [comment]
Hey @Damini2004 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
