### ISSUE TITLE
Beat_a_mole

### ISSUE THREAD

**Issue by chakrabortydeep** [kunjgit/GameZone#3512]
### 🎮 Game Request

The Beat_a_Mole game is a classic arcade game implemented using HTML, CSS, and JavaScript. Players must hit moles that randomly pop up on the screen but if you hit the plant the game will be over. The game features a simple and intuitive user interface with responsive design elements.

I have created this game and made it ready for contributing by considering the rules as pr given.

### Point down the features

In this game we have to hit the mole and get points. But if we hit the plant the game will be over.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @chakrabortydeep ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @chakrabortydeep ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
