### ISSUE TITLE
[New game]: Tic Tac Toe

### ISSUE THREAD

**Issue by ShrutiGuptaaa** [kunjgit/GameZone#3514]
### 🎮 Game Request

I would like to propose the addition of a Tic Tac Toe game to the GameZone website. This classic game would be a valuable addition to our collection of games, providing users with a fun and engaging experience.

### Point down the features

Game points
A player wins the game by aligning three of their marks (either 'X' or 'O') in a horizontal, vertical, or diagonal row.
A player loses the game if the opponent aligns three of their marks (either 'X' or 'O') in a horizontal, vertical, or diagonal row before they do.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @ShrutiGuptaaa! 
We are already having a similar game request in #3173 👀 
Make sure you come up with a cool unique idea 😀 
 Waiting for your new game idea 💗.

**Comment by kunjgit** [comment]
Hey @ShrutiGuptaaa ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @ShrutiGuptaaa ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
