### ISSUE TITLE
[New game]: Flames

### ISSUE THREAD

**Issue by ShrutiGuptaaa** [kunjgit/GameZone#3515]
### 🎮 Game Request

The "FLAMES" game is a popular and lighthearted game often played to determine the compatibility or relationship status between two individuals.

### Point down the features

If a player correctly guesses the relationship status predicted by the FLAMES algorithm, they earn points.
Players who reach the correct guess within a limited time frame may earn additional points
Assign different point values based on the rarity or difficulty of the predicted relationship status.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @ShrutiGuptaaa ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by Damini2004** [comment]
Can You assign this game to me

**Comment by Yuvraj960** [comment]
@kunjgit Please assign this issue to me under GSSoC24

**Comment by ShrutiGuptaaa** [comment]
I want to work on this issue

**Comment by ShrutiGuptaaa** [comment]
@kunjgit

**Comment by ananyag309** [comment]
Hi, I hope this message finds you well.

I am writing to express my interest in contributing to the issue. I am enthusiastic about participating in GSSoC'24 and believe that working on this issue will allow me to make a meaningful contribution to the project.

Could you please assign this issue to me under GSSoC'24?

Thank you for considering my request.

**Comment by kunjgit** [comment]
Hello @ShrutiGuptaaa, Time's up!⏰ 
 Sorry for closing your issue! 
 But it's more than a week since we haven't received anything from your side 😢 . 
 Come up with new ideas, create a new issue and make sure you finish it within a week! 🔥 
 All the best! 🚀 
 Happy Hacking! 💗

**Comment by kunjgit** [comment]
Hey @ShrutiGuptaaa ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
