### ISSUE TITLE
[New game]: Carrom

### ISSUE THREAD

**Issue by Kalyan9064** [kunjgit/GameZone#3518]
### Game Request: Carrom

Basic Description
Carrom is a tabletop game that involves flicking a striker disc to pocket small discs called carrom men into corner pockets on a square board. The objective is to pocket all of your assigned carrom men (either black or white) and the red queen before your opponent does. The game is known for its strategic gameplay, precision shots, and competitive nature.

Game Logic
1. Setup:
   - Place nine black and nine white carrom men in the center of the board in a compact formation, with the red queen positioned in the middle.
   - Players choose their carrom men color (black or white).

2. Turns:
   - Players take turns striking the striker disc from their baseline to hit and pocket carrom men into any of the four corner pockets.
   - The striker must be placed within the player's baseline circle for each shot.

3. Pocketing Carrom Men:
   - If a player pockets one of their carrom men, they get another turn.
   - If they pocket an opponent's carrom man, their turn ends, and the opponent’s piece is returned to the center of the board.

4. Pocketing the Queen:
   - A player can pocket the queen at any time but must follow this by pocketing one of their own carrom men in the same turn to cover the queen.
   - If the queen is not covered, it is returned to the center of the board.

5. Winning the Game:
   - The game ends when a player has pocketed all their carrom men and successfully covered the queen.
   - Points are awarded based on the carrom men pocketed and the queen, with the player or team with the highest points declared the winner.

6. Techniques:
   - Straight Shots: Directly aiming at carrom men to pocket them.
   - Rebound Shots: Using the board edges to bounce the striker to reach difficult positions.
   - Combination Shots: Hitting multiple carrom men in one strike using precise angles.

Carrom blends strategic planning with skillful execution, making it a timeless game enjoyed by people of all ages.

#### Features

1. **Strategic Gameplay**
   - Requires careful planning and precision to pocket carrom men and the queen.
   - Players must think several moves ahead to outmaneuver their opponents.

2. **Skillful Shots**
   - Straight Shots: Directly aim at carrom men to pocket them.
   - Rebound Shots: Use the board edges to bounce the striker for difficult shots.
   - Combination Shots: Hit multiple carrom men in one strike using precise angles.

3. **Multiplayer Fun**
   - Supports both singles and doubles play.
   - Ideal for social gatherings and competitive play.

4. **Precision and Control**
   - Emphasizes accurate aiming and striking to successfully pocket pieces.
   - Players need to control the strength and direction of their shots.

5. **Cultural Heritage**
   - Rich cultural heritage, especially popular in South Asia.
   - Enjoyed by people of all ages and backgrounds.

6. **Engaging and Competitive**
   - The game’s competitive nature keeps players engaged and challenged.
   - Offers a mix of offense (pocketing carrom men) and defense (strategically blocking opponents).

7. **Variety of Techniques**
   - Players can use different techniques to improve their chances of winning.
   - Encourages learning and mastering various shot techniques.

Carrom is a timeless game that combines strategic planning and skillful execution, providing endless fun and challenges for players of all ages.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Kalyan9064 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hello @Kalyan9064, Time's up!⏰ 
 Sorry for closing your issue! 
 But it's more than a week since we haven't received anything from your side 😢 . 
 Come up with new ideas, create a new issue and make sure you finish it within a week! 🔥 
 All the best! 🚀 
 Happy Hacking! 💗

**Comment by kunjgit** [comment]
Hey @Kalyan9064 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
