### ISSUE TITLE
[New game]: 

### ISSUE THREAD

**Issue by kashisharora9462** [kunjgit/GameZone#3519]
### 🎮 Game Request

Game logic and basic description
Kill Monster is an engaging game that combines elements of luck and strategy. The objective is to outlast the monster by strategically selecting from three available options until either the player or the monster is defeated. Here’s a detailed description of the game play and logic:

Game Overview

    Objective: Defeat the monster before it defeats you.
    Game play: Players choose one of three actions in each turn: Attack, Strong Attack, or Heal.
    Winning Condition: The game ends when either the player or the monster's health reaches zero. The surviving entity is declared     the winner.

### Point down the features

Game points

Player Actions:

    Attack: Inflicts a moderate amount of damage to the monster.
    Strong Attack: Inflicts a higher amount of damage but has a lower chance of success.
    Heal: Restores a portion of the player’s health.

Strategic Considerations

    Players must decide when to attack and when to heal, balancing their offensive and defensive strategies.
    Choosing the right action at the right time can significantly influence the game's outcome.

By blending luck with strategic decision-making, Kill Monster provides an exciting and unpredictable gaming experience.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @kashisharora9462 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @kashisharora9462! 
We are already having a similar game request in #3503 👀 
Make sure you come up with a cool unique idea 😀 
 Waiting for your new game idea 💗.

**Comment by kunjgit** [comment]
Hey @kashisharora9462 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by kashisharora9462** [comment]
My game idea is completely diffrent from #3503 
I am attatching a screenshot of how my game look like and logic i had described above 
![Uploading Screenshot 2024-05-20 075901.png…]()
