### ISSUE TITLE
[Bug]: Improving search bar UI and back-end 

### ISSUE THREAD

**Issue by gaddevinay** [kunjgit/GameZone#3522]
### Give a brief about the bug ✍️

Search bar is not responsive for Mobile view.
And javascript to search bar to display related games.

### What is the expected behavior? 🤔

Search bar is responsive.
After searching displaying only related games.
![Screenshot_20240520-085050](https://github.com/kunjgit/GameZone/assets/128584849/9a572699-2790-450c-bb51-80eb48f556f9)

### Provide step by step information reproduce the bug 📄

Using javascript and css.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @gaddevinay ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @gaddevinay ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
