### ISSUE TITLE
[Documentation Bug]: Alphabet

### ISSUE THREAD

**Issue by Bindusree1515** [kunjgit/GameZone#3526]
### Describe the bug ✍️

The README.md file of the Alphabet project includes a link instead of an embedded screenshot, which could be improved for better user experience and presentation. It would be beneficial to replace this link with an actual screenshot of the game.

**Screenshot:**
![image](https://github.com/kunjgit/GameZone/assets/91887086/d246b6d4-c4ad-4ae6-bfdf-1876c8e7d3a2)

@kunjgit please assign me this issue under gssoc

### Provide step by step information reproduce the bug 📄

- Steps to Reproduce the Bug
- Clone Repository
- Navigate to Repository Directory
- Open README.md
- Identifying the Issue
- Locate Screenshot Link
- Steps to Fix the Issue
- Capture Game Screenshot
- Add Screenshot to Repository
- Update README.md
- Finalizing Changes
- Save and Commit

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Bindusree1515 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @Silentman87 ! , This issue is already assigned to @Bindusree1515. 💗 
 You can work on other issues 🚀 
 If there is anything wrong you can contact us on [Discord🕹️](https://discord.gg/fgwk4XZfxG)👀

**Comment by kunjgit** [comment]
Hey @Bindusree1515 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by Silentman87** [comment]
okay then , i look for something else..
