### ISSUE TITLE
[Bug]: Refresh button in Dice Showdown game

### ISSUE THREAD

**Issue by meetarora10** [kunjgit/GameZone#3527]
### Give a brief about the bug ✍️

Refresh button is not visible on the screen which is used to start the game again.

### What is the expected behavior? 🤔

A refresh button properly aligned on the screen will make sure that on click of this button will restart the game without clicking the reload icon from top-left.

### Provide step by step information reproduce the bug 📄

I can make changes in the CSS file to address this issue.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @meetarora10 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @meetarora10 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
