### ISSUE TITLE
[New game]: " Shrek Vs Wild " game added

### ISSUE THREAD

**Issue by shuvadeepmondal** [kunjgit/GameZone#3531]
### 🎮 Game Request

This is the remake of classic Zombie apocalypse game with a twists of Shrek. In this game, Shrek is the main protagonist who fights against the Zombies and other Monsters . This game provides you an experience  of classical Zombie game with an interesting UI & Sound tracks. With Shrek , it will be fun ride to fight against the Monsters. Enjoy my game .

### Point down the features

1. By using the arrow keys , move the main character and defend him from the monsters.
2. By using the space key , you can shoot  or fight with the monsters.
3. Game Music intensifies your gaming experience.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @shuvadeepmondal ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @shuvadeepmondal ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
