### ISSUE TITLE
[New game]: Egg Catcher Game

### ISSUE THREAD

**Issue by Damini2004** [kunjgit/GameZone#3534]
### 🎮 Game Request

Game logic and basic description
The Egg Catcher game is a sub-game in the Kirby series, debuting in Kirby's Adventure. The game logic is simple: Kirby falls down into Dedede Arena, where King Dedede will begin throwing eggs and bombs at him. The player's goal is to catch the eggs by pressing any button to open Kirby's mouth and releasing the button to close it. The player must avoid catching bombs, as they will end the game.

### Point down the features

Game points
Here are the features of the game:

1.Catch eggs thrown by King Dedede to score bonus points and extra lives
2.Avoid catching bombs, which will end the game
3.The number of extra lives rewarded depends on how many eggs Kirby eats
4.In Kirby's Return to Dream Land Deluxe, the game features split-screen multiplayer competition
5.Players can play as different characters, including Kirby, King Dedede, Meta Knight, and Bandana Waddle Dee, each with their own way of catching eggs
6.If Kirby catches all the eggs, the player will be rewarded three lives
7.If Kirby does not catch any eggs, he will stand in the ring sadly in the result screen
8.Unused screens of an Egg Catcher-style sub-game can be found in Kirby Mass Attack's coding
9.Egg Catcher appears as a challenge in NES Remix 2, where Kirby must eat a certain number of eggs to clear the stage.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Damini2004 , You can't have another issue before completing the previous one 😀 
 you already have the following 1 open issues 👀 ! :

#3510

**Comment by kunjgit** [comment]
Hey @Damini2004 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by kunjgit** [comment]
Hey @Damini2004 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by Damini2004** [comment]
Why did you close this issue ??
Kindly open this issue
