### ISSUE TITLE
[New game]: Endless Runner Game

### ISSUE THREAD

**Issue by Damini2004** [kunjgit/GameZone#3535]
### 🎮 Game Request

Game logic and basic description
An Endless Runner Game is a type of game where the player controls a character that runs continuously, and the objective is to avoid obstacles that come in the character's way. The game gets progressively harder as the player goes further, hence the name "endless."

### Point down the features

Game points
Here are some features of an Endless Runner Game implemented in Python or JavaScript:

The player controls a character that runs automatically.
The player can make the character jump or slide to avoid obstacles.
The game generates new obstacles at regular intervals.
The obstacles can take various forms, such as gaps in the ground, moving objects, or enemies.
The player's score increases as they go further in the game.
The game gets progressively faster and more challenging as the player's score increases.
The game can have various themes, such as running through a city, a forest, or a fantasy world.
The game can have power-ups that give the player temporary abilities, such as invincibility or a speed boost.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Damini2004 , You can't have another issue before completing the previous one 😀 
 you already have the following 1 open issues 👀 ! :

#3510

**Comment by kunjgit** [comment]
Hey @Damini2004 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by kunjgit** [comment]
Hey @Damini2004 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @Damini2004! 
We are already having a similar game request in #3331 👀 
Make sure you come up with a cool unique idea 😀 
 Waiting for your new game idea 💗.
