### ISSUE TITLE
[New game]: Space shooter

### ISSUE THREAD

**Issue by VesperAkshay** [kunjgit/GameZone#3536]
### 🎮 Game Request

Game logic and basic description

# Space Shooter

Space Shooter is an action-packed, arcade-style space shooting game where you pilot a formidable spacecraft through treacherous cosmic landscapes. Your mission is to navigate a perilous galaxy, destroy waves of alien enemies, and defend your home planet from an impending invasion.

## Gameplay

- Pilot a heavily armed spacecraft through diverse and dangerous space environments.
- Dodge enemy projectiles, asteroids, and other hazards using precise controls and quick reactions.
- Unleash a barrage of powerful weapons, including rapid-fire lasers, homing missiles, and devastating bomb payloads.
- Collect power-ups and upgrades to enhance your ship's firepower, defense, and mobility.
- Defeat increasingly challenging waves of alien ships, fighters, and colossal boss enemies.
- Engage in epic boss battles that test your skill and determination to the limit.
- Progress through multiple levels and stages, each with its own unique visual style and challenges.

## Features

- Intense, fast-paced arcade-style shooting action
- Stunning, visually-striking space environments with detailed backgrounds
- A diverse arsenal of upgradable weapons and special abilities
- Intense boss battles that require careful strategy and execution
- Challenging difficulty that tests the reflexes and skills of players
- Leaderboards and scoring system for competitive play
- Smooth, responsive controls optimized for both keyboard and gamepad

Space Shooter offers a thrilling, adrenaline-fueled experience for shoot 'em up fans and casual gamers alike. Pilot your spacecraft through the hazardous reaches of space, annihilate legions of alien invaders, and become the ultimate defender of your home world.

### Point down the features

Game points

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @VesperAkshay , You can't have another issue before completing the previous one 😀 
 you already have the following 1 open issues 👀 ! :

#3505

**Comment by kunjgit** [comment]
Hey @VesperAkshay ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by kunjgit** [comment]
Hey @VesperAkshay ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)
