### ISSUE TITLE
[Enhancement]:  Master typing -start/restart button functions need to upgrade 

### ISSUE THREAD

**Issue by Tasnuva12** [kunjgit/GameZone#3537]
### Do you want to have the enhancement of existing game ? 😀 Describe yourself..

The letters should popup only after pressing start button and  the restart button should be named reset  because the button is clearing the timer and also the game's state.

### Describe the solution you'd like

- [ ] -  Launch the game application.
- [ ]  - Navigate to the main menu or game interface where the start/restart button is located.
- [ ]  - Attempt to click on the start or restart button.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Tasnuva12 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @Tasnuva12 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
