### ISSUE TITLE
[Enhancement]: Master typing game and snake game

### ISSUE THREAD

**Issue by Tasnuva12** [kunjgit/GameZone#3539]
### Do you want to have the enhancement of existing game ? 😀 Describe yourself..

Master Typing game (https://kunjgit.github.io/GameZone/Games/Master_Typing/)
-change of the functionality of button start(when the button is pressed only that time the timer will start and the letter will pop up
- renaming  the button restart to reset as it resets the game in its primary state 
Snake Game (https://kunjgit.github.io/GameZone/Games/Snake_Game/)
-changing  the theme of the change (made some change in the colors ) to  make it more beautiful to look at 
-Someone changed the alignment of the elements in this page , so it's necessary to fix it  .

### Describe the solution you'd like

 - Launch the game application.
 - Navigate to the main menu or game interface where the change is needed 
 - make the necessary change

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Tasnuva12 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @Tasnuva12 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
