### ISSUE TITLE
[Enhancement]: TIC TAC TOE GAME WITH SOUND EFFECT DURING WIN OR LOSS

### ISSUE THREAD

**Issue by ashutoshgithubs** [kunjgit/GameZone#354]
### Is your enhancement request related to a problem? Please describe.➕

Game enhancement
hi @kunjgit, I think that if we add a sound effect to the TIC TAC TOE game during a win or loss, it will look awesome.
I can develop this effect as I mode this game with proper sound effects. 
So please assign this enhancement part.

### Describe the solution you'd like

Solution steps
Just adding sound effects using JS, I will use event listener with proper formatting.
For example, to add audio to the game when a player wins, I will add a listener to the game board that checks if a player has won.
If a player wins, I will run a function that triggers audio file like this: 

document.addEventListener("win", function(){
  var audio = new Audio('audio path');
  audio.play();
});

Similarly, I will add a listen to the game board in order to play a separate audio file when a player loses.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @ashutoshgithubs ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hello @ashutoshgithubs, Time's Uppp!⏰ 
 Sorry for closing your issue! 
 But it's more than a week since we haven't received anything from your side 😢 . 
 Come up with new ideas, create a new issue and make sure you finish it within a week! 🔥 
 All the best! 🚀 
 Happy Hacking! 💗

**Comment by kunjgit** [comment]
Hey @ashutoshgithubs ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
