### ISSUE TITLE
[New game]: Pictionary

### ISSUE THREAD

**Issue by Niyatizzz** [kunjgit/GameZone#3547]
### 🎮 Game Request

Game logic and basic description
Hey there!
I would like to add a pictionary game that allows users to draw, guess what has been drawn and give respective output(correct or wrong) and also clear the drawing board. It is a multiplayer game and person with the most correct guesses will win.
The game can easily be integrated into any browser, it is a game that targets all types of audience and a clean UI will enhance it further!

### Point down the features

Game points
It is decided based on number of correct guesses.
Point increment for each correct guess
No negative points

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Niyatizzz , You can't have another issue before completing the previous one 😀 
 you already have the following 1 open issues 👀 ! :

#3097

**Comment by kunjgit** [comment]
Hey @Niyatizzz ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by kunjgit** [comment]
Hey @Niyatizzz ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)
