### ISSUE TITLE
[New game]: Catch me if you can

### ISSUE THREAD

**Issue by Khaleeq01** [kunjgit/GameZone#355]
### 🎮 Game Request

I will be using mouse event for the assignment.
Create a box whose size changes dynamically according to viewport size. Now when you hover over the box, it should change its position randomly inside the viewport.
You can put box initially at any position inside the viewport; just make sure that it does not move out of the viewport at any given time.
The box will look like this -https://ninjasfiles.s3.amazonaws.com/0000000000001861.png
Gif for this problem is -https://ninjasfiles.s3.amazonaws.com/0000000000001878.gif

### Point down the features

Feature of the game is if some one want to catch box then he will not catch the box.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Khaleeq01 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by Khaleeq01** [comment]
assign

**Comment by Lavesh12** [comment]
Hello,
I hope you're doing well. I am interested in contributing to this project as part of GSSoC. It aligns with my skills and interests, and I believe I can make a meaningful contribution to the project Could you please assign this task to me? 
Looking forward to hearing from you.
Thank you,
Lavesh Vishwakarma

**Comment by Khaleeq01** [comment]
@kunjgit will you assign me this issue so i will start working

**Comment by kunjgit** [comment]
Hello @Khaleeq01, Time's Uppp!⏰ 
 Sorry for closing your issue! 
 But it's more than a week since we haven't received anything from your side 😢 . 
 Come up with new ideas, create a new issue and make sure you finish it within a week! 🔥 
 All the best! 🚀 
 Happy Hacking! 💗

**Comment by kunjgit** [comment]
Hey @Khaleeq01 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
