### ISSUE TITLE
[Bug]:  Overflow in x

### ISSUE THREAD

**Issue by tanu-agarwal0101** [kunjgit/GameZone#3554]
### Give a brief about the bug ✍️

There is overflow in x direction because of the alignment of the search bar

### What is the expected behavior? 🤔

In mobile view as well the search bar should be in the centre for there to be no overflow.
Please assign me to fix this under gssoc'24

### Provide step by step information reproduce the bug 📄

![image](https://github.com/kunjgit/GameZone/assets/162132053/df1f82f2-554d-46d7-b8d8-8f57a4b9a3f3)

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @tanu-agarwal0101 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hello @tanu-agarwal0101, Time's up!⏰ 
 Sorry for closing your issue! 
 But it's more than a week since we haven't received anything from your side 😢 . 
 Come up with new ideas, create a new issue and make sure you finish it within a week! 🔥 
 All the best! 🚀 
 Happy Hacking! 💗

**Comment by kunjgit** [comment]
Hey @tanu-agarwal0101 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
