### ISSUE TITLE
[New game]: Catch_The_Circle

### ISSUE THREAD

**Issue by pallasivasai** [kunjgit/GameZone#3567]
### 🎮 Game Request

this is game we have to catch the Circle

### Point down the features

+1 points for catch
no negative points

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @pallasivasai ! , This issue is already assigned to @pallasivasai. 💗 
 You can work on other issues 🚀 
 If there is anything wrong you can contact us on [Discord🕹️](https://discord.gg/fgwk4XZfxG)👀

**Comment by kunjgit** [comment]
Hey @pallasivasai ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
