### ISSUE TITLE
[New game]: Space Invaders Redux

### ISSUE THREAD

**Issue by SaiKishor66** [kunjgit/GameZone#3568]
### 🎮 Game Request

**Overview**
"Space Invaders Redux" is a modern take on the classic arcade game "Space Invaders." Players control a spaceship and defend Earth from waves of descending aliens. The game will feature enhanced graphics, power-ups, multiple levels, and responsive controls.

**Detailed Description**
"Space Invaders Redux" aims to recreate the excitement of the original "Space Invaders" game with modern enhancements. Players will navigate their spaceship left and right to shoot at alien invaders, preventing them from reaching the bottom of the screen. The game will include various types of aliens, each with unique behaviors and movement patterns. As players progress, they will face increasingly challenging waves of invaders and boss battles.

**Target Audience**
The target audience includes fans of classic arcade games, as well as new players who enjoy fast-paced, action-packed gameplay. Suitable for ages 10 and up.

### Responsive Controls: 
Smooth and precise controls for moving the spaceship and shooting.
### Enhanced Graphics: 
Modern, pixel-art-inspired visuals with smooth animations.
### Power-Ups: 
Collect power-ups to upgrade weapons, increase speed, or gain temporary shields.
### Multiple Levels: 
Progress through different levels, each with unique challenges and alien formations.
### Boss Battles: 
Face off against powerful bosses at the end of certain levels.
### Score System: 
Earn points for each alien defeated, with bonuses for accuracy and speed.
### Sound Effects and Music: 
Engaging sound effects and background music to enhance the gameplay experience.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @SaiKishor66 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hello @SaiKishor66, Time's up!⏰ 
 Sorry for closing your issue! 
 But it's more than a week since we haven't received anything from your side 😢 . 
 Come up with new ideas, create a new issue and make sure you finish it within a week! 🔥 
 All the best! 🚀 
 Happy Hacking! 💗

**Comment by kunjgit** [comment]
Hey @SaiKishor66 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
