### ISSUE TITLE
[Enhancement]: Adding new animations for footer icons

### ISSUE THREAD

**Issue by Winter262005** [kunjgit/GameZone#3573]
### Do you want to have the enhancement of existing game ? 😀 Describe yourself..

I want to add some nice animations to the footer icons.

### Describe the solution you'd like

i will use CSS to add animations to the icons
![image](https://github.com/kunjgit/GameZone/assets/151992419/a0d75e38-972b-4a24-8274-c8fef255e47e)

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Winter262005 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by SaiKishor66** [comment]
Can you pls assign this I wanted to contribute?

**Comment by kunjgit** [comment]
Hey @Winter262005 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by kunjgit** [comment]
Hey @Winter262005 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
