### ISSUE TITLE
[Enhancement]: Add music to Run and Jump game

### ISSUE THREAD

**Issue by Roshr2211** [kunjgit/GameZone#3574]
### Do you want to have the enhancement of existing game ? 😀 Describe yourself..

Game enhancement
- Adding background music will be more fun to play

### Describe the solution you'd like

Solution steps
- Add background music

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Roshr2211 , You can't have another issue before completing the previous one 😀 
 you already have the following 1 open issues 👀 ! :

#3482

**Comment by kunjgit** [comment]
Hey @Roshr2211 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by kunjgit** [comment]
Hey @Roshr2211 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)
