### ISSUE TITLE
Add Background Music

### ISSUE THREAD

**Issue by SaiKishor66** [kunjgit/GameZone#3576]
### Do you want to have the enhancement of existing game ? 😀 Describe yourself..

Yes want to enhance the existing 3 d snake game

### Describe the solution you'd like

**Select Background Music:** 
Choose a suitable background music track that fits the theme and atmosphere of the game.
**Integrate Music Player:** 
Implement a simple music player within the game interface to play the selected background music.
**Toggle Functionality:**
Allow players to toggle the background music on and off, giving them control over their audio experience.
**Optimize Performance:** 
Ensure that the music player does not significantly impact game performance, especially on low-end devices.

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @SaiKishor66 , You can't have another issue before completing the previous one 😀 
 you already have the following 1 open issues 👀 ! :

#3568

**Comment by kunjgit** [comment]
Hey @SaiKishor66 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by kunjgit** [comment]
Hey @SaiKishor66 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @SaiKishor66! 🙂 
 It seems like you are not following proper guidelines !! 👀 
 Read documentation properly !!🙏 
 If you have any queries reach out to us on [Discord🕹️](https://discord.gg/fgwk4XZfxG) .
