### ISSUE TITLE
[Enhancement]: Adding Navbar to the Homepage for better user experience

### ISSUE THREAD

**Issue by HarshitGupta1511** [kunjgit/GameZone#3577]
### Do you want to have the enhancement of existing game ? 😀 Describe yourself..

I want to add Navbar with features like home, contact us, contributors,user manual, and feedback

### Describe the solution you'd like

Solution steps - for this task I will use HTML & CSS with its required properties to create a Navbar and will also add hover effect to make it more attractive.Please assign me this task @kun

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @HarshitGupta1511 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @thisismevri ! , This issue is already assigned to @HarshitGupta1511. 💗 
 You can work on other issues 🚀 
 If there is anything wrong you can contact us on [Discord🕹️](https://discord.gg/fgwk4XZfxG)👀

**Comment by kunjgit** [comment]
Hey @HarshitGupta1511 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
