### ISSUE TITLE
[New game]: Adding Word Association Game 

### ISSUE THREAD

**Issue by Aditi22Bansal** [kunjgit/GameZone#3578]
### 🎮 Game Request

Game logic and basic description

In this game, the player has to enter a word that begins with the last letter of the previously entered word. If the word is valid and follows the rules, the game continues. If not, an error message is displayed. It's a fun and challenging game that tests both vocabulary and quick thinking!

### Point down the features

Game points

Word Validation: The game checks whether the word entered by the player is valid according to predefined rules, such as being a real word and starting with the last letter of the previous word.

Real-time Feedback: The game provides immediate feedback to the player after each word entry, indicating whether it's valid or not.

Word Database: The game utilizes a word database or dictionary to verify the validity of entered words.

Hints: The game may provide hints or suggestions for valid words if a player is stuck, helping to keep the game moving and encouraging players to expand their vocabulary.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Aditi22Bansal ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @Aditi22Bansal ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
