### ISSUE TITLE
[New game]: Currency converter

### ISSUE THREAD

**Issue by kashisharora9462** [kunjgit/GameZone#3584]
### 🎮 Game Request

Game logic and basic description
I am planning to develop an educational and entertaining currency converter game. This game will serve as a fun and interactive tool for users to learn about the currencies of different countries. 

### Point down the features

Game points
The currency converter game will present users with various challenges and tasks related to currency conversion. Players will need to convert amounts from one currency to another, identify the correct currencies for different countries, and perhaps even engage in scenarios simulating international travel or trade.

Gameplay Examples

    Conversion Challenges: Players might be given an amount in one currency and asked to convert it to another currency within a time limit.
    Currency Identification: Users might be shown a list of countries and asked to match them with their correct currencies.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @kashisharora9462 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kashisharora9462** [comment]
can you please close this task as i dont want to work on this game.

**Comment by kunjgit** [comment]
Hey @kashisharora9462 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by kunjgit** [comment]
Hey @kashisharora9462 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by kashisharora9462** [comment]
@kunjgit  Please close this i dont what error happened ,but i cannot resolve i am a beginner i dont know about these errors.Please close it so i can work on other part of your website to make it better

**Comment by kunjgit** [comment]
Hey @kashisharora9462 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
