### ISSUE TITLE
[New game]: Steampunk Theme Flappy bird

### ISSUE THREAD

**Issue by Sypher0Dronzer** [kunjgit/GameZone#3587]
### 🎮 Game Request

Game logic and basic description
the game is a simple flappy bird game except it is Steampunk themed

### Point down the features

Game points
The player has to avoid obstacles in order to gain points. 
the player can press spacebar to fly and control to boost
![image](https://github.com/kunjgit/GameZone/assets/83546205/e94bc546-4b48-4980-be12-4e7194118695)

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Sypher0Dronzer ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @Sypher0Dronzer ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
