### ISSUE TITLE
[New game]: Automated Rock paper scissor

### ISSUE THREAD

**Issue by Sypher0Dronzer** [kunjgit/GameZone#3590]
### 🎮 Game Request

Game logic and basic description
The game follows the idea of a normal rock paper scissor game, what makes it different is that your previous saved score still remains intact along with an auto play feature.

### Point down the features

Game points
It follows the basic rules for rock paper scissor
![image](https://github.com/kunjgit/GameZone/assets/83546205/bdb41a5c-0bce-4746-8975-4ed586f40177)

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Sypher0Dronzer , You can't have another issue before completing the previous one 😀 
 you already have the following 1 open issues 👀 ! :

#3587

**Comment by kunjgit** [comment]
Hey @Sypher0Dronzer ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by kunjgit** [comment]
Hey @Sypher0Dronzer ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)
