### ISSUE TITLE
[New game]: color matcher

### ISSUE THREAD

**Issue by 1911aditi** [kunjgit/GameZone#3597]
### 🎮 Game Request

Game logic and basic description:-This game presents the player with a color displayed on the screen. They need to choose a color using the color picker input that matches the displayed color. If they match the color correctly, a success message is shown; otherwise, they are prompted to try again. 

### Point down the features

Game points

### Select program in which you are contributing
GSSoc

_No response_

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @1911aditi ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by 1911aditi** [comment]
hii i m contributing under GSSoC

**Comment by kunjgit** [comment]
Hey @1911aditi ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
