### ISSUE TITLE
[New game]: Two-Three matches

### ISSUE THREAD

**Issue by manishh12** [kunjgit/GameZone#3599]
### 🎮 Game Request

The 2-3 Matches game is a simple two-player game played with a certain number of matches (or any other objects) arranged on a table. 
Strategy:
The key to winning the game often involves leaving the opponent with a specific number of matches that guarantees your victory on the next turn.
Players can employ various strategies to manipulate the number of matches left on the table, making it harder for the opponent to force a win.

### Point down the features

Game points
Setup:
A certain number of matches are placed on the table (for example, 20 matches to start with).
Gameplay:
Players take turns to remove 2 or 3 matches from the table.
The players can't skip their turns; they must remove either 2 or 3 matches on their turn.
Objective:
The player who removes the last match from the table loses the game.
Winning:
The player who forces their opponent to pick up the last match wins.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @manishh12 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @manishh12 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
