### ISSUE TITLE
[New game]: Word Guessing Game

### ISSUE THREAD

**Issue by dishamodi0910** [kunjgit/GameZone#36]
### 🎮 Game Request

Game logic and basic description : 
The game will be having a word that would be having some missing alphabets in it. Corresponding to the user's vocabulary, he/she has to guess the word using the hint given for the word. A number of guesses would be given and on the correct guess within the given number of guesses, the user would win the game.

### Point down the features

Game points : 
1. It will responsive so it can be used on any display size.
2. Certain number of guesses would be there within which one will have to guess the word correctly. 
3. The track of wrongly guessed alphabets would be shown so that the user doesn't commit the same mistake again.
4. The hint would be provided for every word.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by aniketburman014** [comment]
I would like to work on this project. Please assign it to me.

**Comment by kunjgit** [comment]
Hey @dishamodi0910  ! Thank you for raising an issue 💗 You have been assigned this issue you can start working on the issue 🎮
This one also sounds really interesting 💗 !
Really curious to have your game on GameZone ❤️

**Comment by kunjgit** [comment]
Hey @dishamodi0910 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
