### ISSUE TITLE
[New game]: Cube Smasher

### ISSUE THREAD

**Issue by Anshika-17** [kunjgit/GameZone#3604]
### 🎮 Game Request

Game logic and basic description

# Cube Smasher Game

## Game Description
Cube Smasher is a simple, yet addictive, game where the player's goal is to smash as many cubes as possible within a given time limit. The game field is a grid of cubes that randomly appear and disappear, and the player must click on them before they vanish to score points.

## Game Logic

1. **Set up the game:**
   - Create a grid container in HTML with a specified number of rows and columns.
   - Dynamically generate cube elements within the grid using JavaScript.
   - Set up a timer to keep track of the game duration.
   - Initialize the game score to 0.

2. **Game Loop:**
   - Randomly select a cube in the grid to be "active".
   - Display the active cube with a distinctive style (e.g., different color, size, or animation).
   - Start a timer for the active cube, with a predetermined time limit before it disappears.
   - If the player clicks on the active cube before the time limit, increase the game score and remove the cube.
   - If the time limit is reached and the player has not clicked the active cube, remove the cube and decrease the game score.

3. **Scoring and Difficulty:**
   - Each successful cube smash should increase the player's score by a predefined value.
   - As the game progresses, increase the difficulty by:
     - Reducing the time limit for active cubes.
     - Increasing the number of active cubes on the grid.
     - Introducing special cube types (e.g., cubes that move, cubes that are harder to click).

4. **Game Over and Restart:**
   - When the game timer reaches zero, display a "Game Over" message and the final score.
   - Provide a button or option for the player to restart the game.

5. **User Interface:**
   - Display the current game score and the remaining time in the game.
   - Optionally, include a "Highscore" display to show the player's best score.
   - Style the game elements with CSS to create an engaging and visually appealing experience.

Remember to break down the implementation into smaller, manageable tasks and tackle them one by one to ensure a well-structured and functional game.

### Point down the features

Game points

## Additional Features
You can further enhance the game by adding features such as:
- Leaderboards and sharing scores
- Power-ups or special cubes
- Responsive design for different screen sizes
- Sound effects and background music
- Difficulty settings or levels

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Anshika-17 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @Anshika-17 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
