### ISSUE TITLE
[Enhancement]: to get a feature for returning directly to homepage

### ISSUE THREAD

**Issue by thisismevri** [kunjgit/GameZone#3605]
### Do you want to have the enhancement of existing game ? 😀 Describe yourself..

Game enhancement
Game enhancement
after selecting a game and playing it, we can by clicking an arrow we are back to the home page for easiness of the user rather than closing the tab as a whole.

### Describe the solution you'd like

Solution steps
<a href="GameZone.html">Home</a>

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @thisismevri ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by thisismevri** [comment]
good afternoon sir @kunjgit, I request you to please let me work on this issue i will be highly grateful to you,

**Comment by thisismevri** [comment]
Sir please assign me this issue @kunjgit sir

**Comment by tanyagupta01** [comment]
@kunjgit sir please assign this issue to me.

**Comment by thisismevri** [comment]
assign

**Comment by thisismevri** [comment]
sir this issue was raised by be and you have assigned to some other person?

**Comment by thisismevri** [comment]
assign

**Comment by kunjgit** [comment]
Hey @thisismevri ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by thisismevri** [comment]
i have raised this issue but the admin assigned it to some other person.
