### ISSUE TITLE
[Enhancement]: To add a proper look to the home screen.

### ISSUE THREAD

**Issue by Tushar-Vij** [kunjgit/GameZone#3606]
### Do you want to have the enhancement of existing game ? 😀 Describe yourself..

Game enhancement 
We need to add a background image to the home screen, in order to make it more presentable.

### Describe the solution you'd like

Solution steps 
<img src="https://marketplace.canva.com/EAE98IQlC5E/1/0/1600w/canva-purple-simple-gaming-background-futuristic-game-zone-desktop-wallpaper-iC5A8PGB4t0.jpg">

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Tushar-Vij ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by Tushar-Vij** [comment]
Good Afternoon Sir @kunjgit 
I request you to please let me work on this issue i will be highly obliged to you.

**Comment by Tushar-Vij** [comment]
Sir please assign me this issue @kunjgit .

**Comment by tanyagupta01** [comment]
@kunjgit please assign me this issue.

**Comment by Tushar-Vij** [comment]
I have raised this issue but the admin assigned it to , please may i know the reason?

**Comment by kunjgit** [comment]
Hey @Tushar-Vij ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
