### ISSUE TITLE
[New game]: Balloon Buster

### ISSUE THREAD

**Issue by manishh12** [kunjgit/GameZone#3607]
### 🎮 Game Request

Balloon Buster is a simple aiming and timing game where the player's objective is to pop as many balloons as possible within a given time limit. Balloons will appear randomly on the screen, and the player must click on them to pop them. Each popped balloon earns the player points, and the game keeps track of the player's highest score.

### Point down the features

1. **Popping Balloons**: The primary way to earn points in the game is by popping balloons. When a player clicks on a balloon, it pops, and the player earns one point. This encourages players to aim accurately and quickly click on balloons as they appear on the screen.

2. **Score Display**: The player's current score is displayed prominently on the screen. As the player pops balloons, the score increases accordingly. This provides immediate feedback to the player about their progress and performance in the game.

3. **High Score**: The game also tracks the player's highest score achieved in a single game session. This adds an element of challenge and motivation for players to try to surpass their previous best performance. The high score is updated whenever the player achieves a new high score during gameplay.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @manishh12 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @manishh12 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
