### ISSUE TITLE
[Documentation Bug]: Asteroids_3D

### ISSUE THREAD

**Issue by Bindusree1515** [kunjgit/GameZone#3608]
### Describe the bug ✍️

The README.md file of the Asteroids_3D project includes a link instead of an embedded screenshot, which could be improved for better user experience and presentation. It would be beneficial to replace this link with an actual screenshot of the game.

Screenshot of the bug:
![image](https://github.com/kunjgit/GameZone/assets/91887086/8239c92f-8f8d-4b51-9fe2-d140498ad8c0)

please assign me this issue for better user experience.

### Provide step by step information reproduce the bug 📄

- Steps to Reproduce the Bug
- Clone Repository
- Navigate to Repository Directory
- Open README.md
- Identifying the Issue
- Locate Screenshot Link
- Steps to Fix the Issue
- Capture Game Screenshot
- Add Screenshot to Repository
- Update README.md
- Finalizing Changes
- Save and Commit

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Bindusree1515 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @Bindusree1515 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
