### ISSUE TITLE
[New game]:Joke Generator  

### ISSUE THREAD

**Issue by manishh12** [kunjgit/GameZone#3611]
### 🎮 Game Request

In this entertaining game, you'll be treated to a variety of jokes at the click of a button. Whether you need a quick laugh or want to share a joke with friends, the Joke Generator is here to brighten your day. Simply click the "Generate Joke" button and enjoy a new joke every time!

### Point down the features

Generate Joke Button:
Clicking this button fetches a new joke from the joke database.
Displays the joke in a designated area on the screen.

Joke Display:
Shows the generated joke to the user.
Automatically updates with each new joke.

Copy Joke:
Provides a button to copy the current joke to the clipboard.
Makes it easy to share jokes with friends via text or social media.

Responsive Design:
The game adjusts its layout to fit different screen sizes, ensuring a good experience on both desktop and mobile devices

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @manishh12 , You can't have another issue before completing the previous one 😀 
 you already have the following 1 open issues 👀 ! :

#3607

**Comment by kunjgit** [comment]
Hey @manishh12 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by kunjgit** [comment]
Hey @manishh12 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)
