### ISSUE TITLE
[Documentation Bug]: empty ream me file 

### ISSUE THREAD

**Issue by msifran** [kunjgit/GameZone#3617]
### Describe the bug ✍️

documentaion is empty

### Provide step by step information reproduce the bug 📄

- [x] Description 
- [x] how to play 
- [x] Proper display

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @msifran ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by Yuvraj960** [comment]
@kunjgit Please assign this issue to me under GSSoC24

**Comment by kunjgit** [comment]
Hey @msifran ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
