### ISSUE TITLE
[New game]: Blackjack or 21

### ISSUE THREAD

**Issue by codewithishu** [kunjgit/GameZone#3618]
### 🎮 Game Request

Game logic and basic description:

Blackjack, also known as 21, is a popular and engaging card game often played in casinos around the world. The game's objective is simple yet thrilling: players aim to have a hand value closer to 21 than the dealer's hand without exceeding this total.

How to Play
Deck: Blackjack is typically played with one or more standard 52-card decks. In most casinos, multiple decks are used, often shuffled together.

Card Values:

Number cards (2-10) are worth their face value.
Face cards (Kings, Queens, and Jacks) are worth 10 points each.
Aces can be worth 1 or 11 points, depending on which value benefits the hand more.

Gameplay:

Initial Deal: Each player is dealt two cards, usually one face-up and one face-down. The dealer also receives two cards, with one card face-up and the other face-down.

Player's Turn: Players decide how to play their hands, choosing to "hit" (take another card) or "stand" (keep their current hand). Other options may include "double down" (doubling the bet and taking one more card), "split" (if the first two cards are of the same value, split them into two hands), or "surrender" (forfeit half the bet and end the round).

Dealer's Turn: Once all players have finished their turns, the dealer reveals the face-down card. The dealer must hit until their total is at least 17. If the dealer exceeds 21, they bust, and all remaining players win.

Winning: Players win if their hand total is higher than the dealer's without going over 21, or if the dealer busts. A hand totaling exactly 21 with the initial two cards (an Ace and a 10-value card) is called a "Blackjack" and typically pays out 3:2.

### Point down the features

Game points:
Blackjack, also known as 21, is a classic card game that combines luck and strategy. Here are the key points to understand and enjoy the game:

Objective:

Aim to have a hand value closer to 21 than the dealer's hand without exceeding 21.
Card Values:

Number cards (2-10): Worth their face value.
Face cards (Jack, Queen, King): Worth 10 points each.
Ace: Worth 1 or 11 points, whichever benefits the hand more.
Setup:

Played with one or more standard 52-card decks.
Multiple players compete against the dealer, not each other.
Initial Deal:

Each player and the dealer receive two cards.
Players' cards: One face-up and one face-down.
Dealer's cards: One face-up and one face-down (hole card).
Player Actions:

Hit: Take another card to increase the hand's total.

Stand: Keep the current hand and end the turn.

Double Down: Double the initial bet and receive exactly one more card.

Split: If the first two cards are of the same value, split them into two separate hands with an additional bet.

Surrender: Forfeit half the bet and end the round immediately (option varies by casino).

Dealer's Turn:

The dealer reveals the hole card and must hit until the total is at least 17.
If the dealer's hand exceeds 21 (busts), all remaining players win.
Winning and Payouts:

Players win by having a hand value higher than the dealer's without busting or if the dealer busts.
A hand totaling exactly 21 with the initial two cards (an Ace and a 10-value card) is called a "Blackjack" and typically pays 3:2.
Standard wins usually pay 1:1.

![Screenshot 2024-05-21 165650](https://github.com/kunjgit/GameZone/assets/146975269/c7d6714d-29ea-4cbc-9f80-a9f9c24da4c7)

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @codewithishu , You can't have another issue before completing the previous one 😀 
 you already have the following 1 open issues 👀 ! :

#3447

**Comment by kunjgit** [comment]
Hey @codewithishu ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
