### ISSUE TITLE
[New game]: Brick n Ball 

### ISSUE THREAD

**Issue by Yuvraj960** [kunjgit/GameZone#3619]
### 🎮 Game Request

It is the classic game in which a ball destroys the bricks displayed in the game. And we have to save the ball when it comes down on the floor by moving the slider.

### Point down the features

-> It will record the game points according to bricks destroyed.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Yuvraj960 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by Yashgabani845** [comment]
i wouls like to amke this game please assign mt this game
/assign

**Comment by kunjgit** [comment]
Hey @Yuvraj960 ! , This issue is already assigned to @Yashgabani845. 💗 
 You can work on other issues 🚀 
 If there is anything wrong you can contact us on [Discord🕹️](https://discord.gg/fgwk4XZfxG)👀

**Comment by Yuvraj960** [comment]
@kunjgit I have raised this issue so technically it should be assigned to me

**Comment by Yuvraj960** [comment]
@Yashgabani845 Hey bro please leave this issue. You can create your own issues. Don't self assign and claim on other's ideas or issues.

**Comment by Yashgabani845** [comment]
@Yuvraj960  bro  i had already coded this game before i just have to add it so i self-assign this issue ,please you make another issue

**Comment by Yashgabani845** [comment]
i am unassigning this isssue if you really want to work but consider my pull request i have submitted whole game

**Comment by kunjgit** [comment]
Hey @Yuvraj960 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
