### ISSUE TITLE
[Enhancement]: Increase size of tilting maze and instruction text.

### ISSUE THREAD

**Issue by theashikagupta** [kunjgit/GameZone#3622]
### Do you want to have the enhancement of existing game ? 😀 Describe yourself..

Game enhancement
The size of instruction text and tiling maze is very small .We should zoom in full screen.

### Describe the solution you'd like

Solution steps
Update CSS style for tilting maze and text to zoom it in full screen.
![Screenshot 2024-05-21 232011](https://github.com/kunjgit/GameZone/assets/136061047/375e9819-c14a-44a7-967f-63e98cc71709)

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @theashikagupta ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @theashikagupta ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
