### ISSUE TITLE
[New Game]: Color Matcher

### ISSUE THREAD

**Issue by PoulasthaMukherjee** [kunjgit/GameZone#363]
### 🎮 Game Request

Description:
I would like to request the addition of a new game called "Color Matcher" to the Games collection. This game is designed to be unique and simple, providing an engaging matching experience for players.

### Point down the features

Game Logic and Basic Description:

- The Color Matching Game was created using HTML, CSS, and JavaScript.
- This is a user-friendly kind of application that can be easily modified to be used in your on working projects.
- The application is a simple Matching type game that can be played by a single-player.
- The player can play the game using the Mouse, you only just need to use the Left Mouse Button to interact the game.
- The gameplay is very simple all you have to do is to match the same color you will see within 30 seconds.
- Each color you matched will disappear and you to need to proceed to other colors.
- Try to match all the colors before the time runs out.

Features:

- Timer: Display a countdown timer to indicate the remaining time for the player to make matches.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @PoulasthaMukherjee ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @PoulasthaMukherjee ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
