### ISSUE TITLE
[New game]: Adding the Catching the falling stars game

### ISSUE THREAD

**Issue by Aditi22Bansal** [kunjgit/GameZone#3630]
### 🎮 Game Request

Game logic and basic description

Catch the Falling Stars is a simple web game where the player controls a basket to catch falling stars. The game is built using HTML, CSS, and JavaScript.

### Point down the features

Game points
- **Basket Movement**: The basket can be moved left and right using the arrow keys.
- **Star Generation**: Stars are generated at random horizontal positions and fall vertically.
- **Score Tracking**: The score increases by 10 points for each star caught.
- **Game Over Condition**: The game stops after missing three stars, and the final score is displayed.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Aditi22Bansal ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @Aditi22Bansal ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
