### ISSUE TITLE
[New game]:  classic chess.com

### ISSUE THREAD

**Issue by Yashgabani845** [kunjgit/GameZone#3632]
### 🎮 Game Request

Game logic and basic description

i want to put game of chess.com dashboard 
current chess game have many issue s and insensitive moves i want to make full working proper clone of chess.com 

### Point down the features

Game points
basic ches game
will follow all chess rules
and give vibes of oficial chess 
can play multiplayer

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Yashgabani845 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
