### ISSUE TITLE
[Bug]: Adventure_Game contains an unclickable bugged folder.

### ISSUE THREAD

**Issue by Winter262005** [kunjgit/GameZone#3634]
### Give a brief about the bug ✍️

**Description**

The folder "Pokemon_Stats_Card" inside "Adventure_Game" is creating problems with commits for other contributors.
![Screenshot 2024-05-21 001419](https://github.com/kunjgit/GameZone/assets/151992419/4dd26362-7e22-4d5c-988a-8b066fe10c32)

### What is the expected behavior? 🤔

**Description**

It should contain the URL for the folder at the frontend.

### Provide step by step information reproduce the bug 📄

**Description**

Terminating the Folder is the only solution here.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Winter262005 , You can't have another issue before completing the previous one 😀 
 you already have the following 1 open issues 👀 ! :

#3573

**Comment by kunjgit** [comment]
Hey @Winter262005 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by kunjgit** [comment]
Hey @Winter262005 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)
