### ISSUE TITLE
[Bug]: Game "Adventure_Game" contains a bugged folder

### ISSUE THREAD

**Issue by Winter262005** [kunjgit/GameZone#3635]
### Give a brief about the bug ✍️

Description

"Adventure_Game" contains a folder named "Pokemon_Stats_Card" which is bugged and unclickable.
Also it is disrupting commits of other contributors.
![Screenshot 2024-05-21 001419](https://github.com/kunjgit/GameZone/assets/151992419/4db80ad7-965d-4ba8-bff9-3b020f933366)

### What is the expected behavior? 🤔

Description
The URL of the folder should be properly linked to the backend and frontend.

### Provide step by step information reproduce the bug 📄

Description

Termination of the folder is the most reasonable task here till it is properly fixed by the author of the game.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Winter262005 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @Winter262005 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
