### ISSUE TITLE
[Bug]: Puzzel Winner and emoji intruder doesn't have images

### ISSUE THREAD

**Issue by bhumika-1127** [kunjgit/GameZone#3641]
### Give a brief about the bug ✍️

@kunjgit Kindly assign me this issue 
![image](https://github.com/kunjgit/GameZone/assets/137604220/5c7a70fa-94cb-4cb5-a780-4bb40dfe5093)

### What is the expected behavior? 🤔

.

### Provide step by step information reproduce the bug 📄

.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @bhumika-1127 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by bhumika-1127** [comment]
assign

**Comment by kunjgit** [comment]
Hey @bhumika-1127 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
