### ISSUE TITLE
{New Game]: Adding  2048_win: 

### ISSUE THREAD

**Issue by VidhiSaxenaa** [kunjgit/GameZone#3646]
### 🎮 Game Request

Game logic and basic description
2048 is a simple game built using HTML, CSS, and JavaScript where the player matches the tiles with the same number and when the two tiles touch, they merge into one. Once the player gets 2048 in any square, they win. 
![Screenshot 2024-05-22 171130](https://github.com/kunjgit/GameZone/assets/170200783/7418cb8f-6e6c-4b2e-a2e9-9f6daf38de9f)

### Point down the features

Game points

- Tile Movement: Tiles can be moved by clicking arrow keys in the desired direction.
- Tile Generation: A new 2 digit tile will be generated after every move. 
- Score Tracking: The score increases by the sum of total tiles merged in one click.
- Game Over Condition: Once the player gets 2048 in any square, they win and the game is over
- Difficulty level: The level increases with increasing tiles making it highly difficult for the person to achieve 2048. 

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @VidhiSaxenaa ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by VidhiSaxenaa** [comment]
Thank you!

**Comment by kunjgit** [comment]
Hey @VidhiSaxenaa ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
