### ISSUE TITLE
[Enhancement]: Basketball

### ISSUE THREAD

**Issue by NAVJOT-786** [kunjgit/GameZone#3647]
### Do you want to have the enhancement of existing game ? 😀 Describe yourself..

Description:

This enhancement aims to improve the user experience in the Basketball game by modifying the instructions display. The current implementation shows the instructions at the bottom of the screen. We will update this to display the instructions at the top of the screen in bold text for better visibility and emphasis.

Objectives:

Move the instructions from the bottom to the top of the screen.
Display the instructions in bold text.

Implementation Plan:

Locate the code where the instructions are currently rendered.
Modify the code to change the position of the instructions from the bottom to the top.
Apply styling to the instructions to make them bold.

Expected Outcome:

Players will have a clearer view of the game instructions, enhancing their overall gaming experience.

### Describe the solution you'd like

Solution Description

Title: Improve Instruction Display in Basketball Game

*Description:

This solution will enhance the user experience by moving the game instructions from the bottom to the top of the screen and making the text bold. This will ensure that the instructions are immediately visible and clearly emphasized.

*Steps to Implement the Solution:

*Locate the Code for Instructions Display:

Identify the file and the specific part of the code where the instructions are currently being displayed at the bottom of the screen.

*Move Instructions to the Top:

Modify the positioning of the instructions so that they appear at the top of the screen instead of the bottom.
Ensure that the new position is consistent across different screen sizes and resolutions.

*Apply Bold Styling to Instructions:

Add CSS or inline styling to make the instructions text bold.
Ensure that the styling does not interfere with the readability or overall design of the game.

*Test the Changes:

Run the game and verify that the instructions are displayed at the top and in bold.
Test across different browsers and devices to ensure compatibility.

*Submit the Changes:

Commit the changes to your local repository.
Push the changes to the remote repository.
Create a pull request for the maintainers to review and merge your enhancement.

I am contributing in behave of Gssoc24

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @NAVJOT-786 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @NAVJOT-786 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
