### ISSUE TITLE
[New game]: Flip card memory game

### ISSUE THREAD

**Issue by SimranLahrani842** [kunjgit/GameZone#365]
### 🎮 Game Request

Game logic and basic description
Basically there are three levels in game : casual ,medium and hard.
We need to select one box and try to remeber it's symbol ,we get again same symbol ie a pair they both nullify ,similarly we need to form pairs by remembering where is each symbol...

### Point down the features

Game points
The player will pass or fail ie pass if he can flip within the given chances and fail if he cannot.
This will test the memory of the person.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @SimranLahrani842 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @SimranLahrani842 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
