### ISSUE TITLE
[Enhancement]: Making the background and buttons of "Memory_game" attractive and adding instructions.

### ISSUE THREAD

**Issue by TusharChamlikar** [kunjgit/GameZone#3650]
### Do you want to have the enhancement of existing game ? 😀 Describe yourself..

Game enhancement
1. The display background of the game("memory game") is very simple.
2. The font used in the game is very simple.
3. No instructions are given about how to play the game.

### Describe the solution you'd like

Solution steps
I will change the background of the game
I will change the fonts of the game.
I will add an instructions option displaying all the instructions about "HOW TO PLAY".

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @TusharChamlikar ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @TusharChamlikar ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
