### ISSUE TITLE
[New game]: Automated Rock Paper scissor Game

### ISSUE THREAD

**Issue by Sypher0Dronzer** [kunjgit/GameZone#3651]
### 🎮 Game Request

Game logic and basic description
It is like a normal rock paper scissors game with a change that theres is an option to auto play the game for you 

### Point down the features

Game points
It follows the rules of rock paper scissors
![image](https://github.com/kunjgit/GameZone/assets/83546205/ffe42ab9-86df-470d-b6bc-3db0c1e16e07)

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Sypher0Dronzer ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @Sypher0Dronzer ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
