### ISSUE TITLE
[New game]: Added Tiny Fishing 

### ISSUE THREAD

**Issue by Pujan-sarkar** [kunjgit/GameZone#3652]
## Game logic and basic description
It is a fun game to play for kids and children. This game gives you a very nice experience of fishing game , in this game you can catch the many fishes and level up of your equipment . there is a bonus section where you can get bonus prizes.

## Game points
1. you can your mouse or arrow keys for moving the fishing rod .
2. The music give you a very fun vibe .

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Pujan-sarkar ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @Pujan-sarkar ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
