### ISSUE TITLE
[New game]: Darts

### ISSUE THREAD

**Issue by VijaySamant4368** [kunjgit/GameZone#3654]
### 🎮 Game Request

The Darts game allows the player to aim and throw darts at a dartboard to score points. The goal is to hit the bullseye or get as close to it as possible. 

### Point down the features

The player can click on the dartboard to throw a dart, and the score will be calculated based on where the dart lands.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @VijaySamant4368 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by kunjgit** [comment]
Hey @VijaySamant4368 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
