### ISSUE TITLE
[Question]:  Would u like to add preloader to ur index page?

### ISSUE THREAD

**Issue by Anjaliavv51** [kunjgit/GameZone#3656]
### Describe your question or ask for support.❓

Description
Preloader : gives idea to the user to the user that page is still loading.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by Anjaliavv51** [comment]
@kunjgit which preloader gif u would like to have in your repo?

**Comment by Anjaliavv51** [comment]
@kunjgit would u like to add this as loader style

![8735372d-510d-493c-996b-396464636730_carw_202x158x640](https://github.com/kunjgit/GameZone/assets/154777864/d9dea371-087b-4e0e-b697-df0bc83b578d)

**Comment by Anjaliavv51** [comment]
@kunjgit please review PR #3661

**Comment by Anjaliavv51** [comment]
@kunjgit please review PR #3661

**Comment by Anjaliavv51** [comment]
@kunjgit please review PR #3661

**Comment by kunjgit** [comment]
Hey @Anjaliavv51 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by Anjaliavv51** [comment]
@kunjgit please review PR https://github.com/kunjgit/GameZone/pull/3661

**Comment by kunjgit** [comment]
Hey @Anjaliavv51 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
