### ISSUE TITLE
[Question]: Would u like to add share button instead of link in footer section?

### ISSUE THREAD

**Issue by Anjaliavv51** [kunjgit/GameZone#3659]
### Describe your question or ask for support.❓

Description
Addition of Share button.

https://github.com/kunjgit/GameZone/assets/154777864/54c64af9-9413-4744-aadc-b7008375a07c

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Anjaliavv51 , You can't have another issue before completing the previous one 😀 
 you already have the following 1 open issues 👀 ! :

#3656

**Comment by kunjgit** [comment]
Hey @Anjaliavv51 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by Anjaliavv51** [comment]
> Hey @Anjaliavv51 , You can't have another issue before completing the previous one 😀 you already have the following 1 open issues 👀 ! :
> 
> #3656

okay
