### ISSUE TITLE
[New game]: Smash Cubes

### ISSUE THREAD

**Issue by hiteshhhh007** [kunjgit/GameZone#3670]
### 🎮 Game Request

The game starts by setting up the Three.js scene, including the camera, renderer, and lights. It also initializes important things like the level, score, and how many targets there are. 🚀 Colorful cubes spin around in the scene, giving it a lively feel. 🎨 Players can click on the screen, and the game will figure out if they've clicked on one of the cubes. When they do, the cube disappears in a big explosion of particles going everywhere. 💥 The game keeps track of how many cubes players have hit, updating their score and showing it on the screen. 📊 As players do well and move through levels, the game gets harder by making the cubes spin faster and adding more of them. 📈 After beating a level, players get encouraging messages and can choose to start again for more fun. 🏆✨

## Features:
- 🎮 Interactive 3D gameplay with clickable cubes.
- 🌈 Colorful spinning cubes for visual appeal.
- 💥 Explosive particle effects for click feedback.
- 📈 Progressive difficulty with multiple levels.
- 🎉 Victory message upon completing all levels.
- 🔄 Option to restart the game for endless fun.
- 🖥️ Responsive design for various screen sizes.
- 🎨 Stylish HUD for displaying score and level information.
- 🎵 Ambient lighting and spotlights for atmospheric effects.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by hiteshhhh007** [comment]
@kunjgit If you can assign this issue to me, I would to work on it under GSSoC'24.

**Comment by kunjgit** [comment]
Hey @hiteshhhh007 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @hiteshhhh007! 
We are already having a similar game request in #3604 👀 
Make sure you come up with a cool unique idea 😀 
 Waiting for your new game idea 💗.

**Comment by kunjgit** [comment]
Hey @hiteshhhh007 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
