### ISSUE TITLE
[Question]: Would like to replace media links to share button?

### ISSUE THREAD

**Issue by Anjaliavv51** [kunjgit/GameZone#3673]
### Describe your question or ask for support.❓

Description
Addition of Share button.

https://github.com/kunjgit/GameZone/assets/154777864/54c64af9-9413-4744-aadc-b7008375a07c

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Anjaliavv51 , You can't have another issue before completing the previous one 😀 
 you already have the following 1 open issues 👀 ! :

#3656

**Comment by kunjgit** [comment]
Hey @Anjaliavv51 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by kunjgit** [comment]
Hey @Anjaliavv51 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by Anjaliavv51** [comment]
assign
