### ISSUE TITLE
[New game]: dragon tower game

### ISSUE THREAD

**Issue by Vipullakum007** [kunjgit/GameZone#3676]
### 🎮 Game Request

Game logic and basic description : Dragon Tower is an engaging and strategic game where players navigate through a tower filled with hidden treasures and traps. The objective is to reach the top of the tower while collecting as many eggs as possible and avoiding deadly mines. Each decision can lead to a valuable reward or a sudden game over, making every move crucial.

### Point down the features

Game points : 
1 . Dynamic Gameplay:
Randomized positions of eggs and mines in each game ensure a unique experience every time.
2 . Interactive Interface:
Intuitive UI with horizontal rows and three columns.
Visually appealing design with animations and beautiful backgrounds.
3 . Hidden Items Mechanic:
Items are initially hidden and revealed only when a tile is selected, adding suspense and strategy.
4 .Scoring System and Alerts:
Points are awarded for collecting eggs, and a 'Game Over' alert appears when a mine is selected.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Vipullakum007 , You can't have another issue before completing the previous one 😀 
 you already have the following 1 open issues 👀 ! :

#3582

**Comment by kunjgit** [comment]
Hey @Vipullakum007! 
We are already having a similar game request in #3427 👀 
Make sure you come up with a cool unique idea 😀 
 Waiting for your new game idea 💗.

**Comment by kunjgit** [comment]
Hey @Vipullakum007 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
