### ISSUE TITLE
[New game]: The simon Game

### ISSUE THREAD

**Issue by Babunshil** [kunjgit/GameZone#368]
### 🎮 Game Request

The Simon Game is a classic memory game that tests your ability to remember and repeat a sequence of colors and sounds. This version of the game was built using HTML, CSS, and JavaScrip

### Point down the features

>Watch and listen carefully as the game plays a sequence of colors and sounds.
>Repeat the sequence by clicking on the colored buttons in the correct order.
>If you get the sequence right, the game will play another sequence, this time with one extra color and sound.
>Keep repeating the sequences correctly to advance through the levels.
>If you make a mistake, the game will end and you'll have to start over from the beginning
![230716289-3986ce43-1c8f-4db1-a649-a029fb1114ce](https://github.com/kunjgit/GameZone/assets/106283743/62a6a5e1-d27a-4db8-9597-b820b99db7e2)

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Babunshil ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @Babunshil! 
We are already having a similar game request in #348 👀 
Make sure you come up with a cool unique idea 😀 
 Waiting for your new game idea 💗.
