### ISSUE TITLE
[Enhancement]: Adding a 10 seconds alert and improving the UI of the " AIM TRAINING " game

### ISSUE THREAD

**Issue by ShristiiSharma** [kunjgit/GameZone#3680]
### Do you want to have the enhancement of existing game ? 😀 Describe yourself..

Game enhancement
1. I will add a 10 seconds countdown alert to the game.  It will keep players informed about the remaining time, helping them manage their strategies and efforts more effectively.
2. Knowing the game is about to end can motivate players to make a final push, potentially leading to higher scores and a more satisfying game experience.
3. I will enhance the UI of the game. 
4. Enhancing the UI of the game leads to a more immersive, enjoyable, and memorable gaming experience for players.

### Describe the solution you'd like

Solution steps
1.  A pop-up alert message will appear every second from 10 seconds left to 1 second left, displaying the remaining time, and the alert will automatically disappear after 1 second. 
2.  I will enhance the UI of the game by adding background color, hover effects, styling the title etc.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @ShristiiSharma ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @ShristiiSharma ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
