### ISSUE TITLE
[New game]: Guess the number

### ISSUE THREAD

**Issue by manishh12** [kunjgit/GameZone#3682]
### 🎮 Game Request

Guess the Number" is a simple number guessing game where the player tries to guess a randomly generated number within a specified range. The player is informed whether their guess is too high or too low after each attempt. The game continues until the player guesses the correct number, at which point they are congratulated and informed of the number of attempts made. The player can then choose to play again or end the game.

### Point down the features

1. **Correct Guess**: 
   - When the player correctly guesses the number, they earn a certain number of points. This could be a fixed amount or based on factors such as the range of numbers or the number of attempts taken.

2. **Number of Attempts**:
   - Points could be awarded based on the number of attempts it takes for the player to guess the correct number. Fewer attempts could result in more points, incentivizing efficient guessing.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @manishh12 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @manishh12 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
