### ISSUE TITLE
[New game]: Dragon Run 

### ISSUE THREAD

**Issue by codewithganeshhh** [kunjgit/GameZone#3683]
### 🎮 Game Request

Game logic and basic description

- This is a retro styled 2D game in which you have to tackle the enemy by jumping in air, and the muskic makes it even more funnier ; `)`

### Point down the features

Game points:
- Easy to play
- Exciting sound effects to immerse you and keep you engaged. 
- Scoring system so that you can compare points with your fellow friends
- 
![Screenshot 2024-05-23 213033](https://github.com/kunjgit/GameZone/assets/139307139/8b05be1f-0f41-48a2-9bf9-22d796f6e626)

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @codewithganeshhh ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @codewithganeshhh ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
