### ISSUE TITLE
[New game]: Space Explorer

### ISSUE THREAD

**Issue by Aditi22Bansal** [kunjgit/GameZone#3685]
### 🎮 Game Request

Game logic and basic description
In this game, the player controls a spaceship that navigates through an asteroid field. The player must avoid asteroids and collect stars for points. 

### Point down the features

Game points
## Key Features

1. **Spaceship Control:**
   - Smooth left and right movement using arrow keys or 'A' and 'D' keys.
   - Responsive gameplay with collision detection.

2. **Asteroid Obstacles:**
   - Randomly spawning asteroids that fall downwards.
   - Players must avoid collisions to stay alive.

3. **Collectible Stars:**
   - Randomly appearing stars that fall downwards.
   - Collecting stars increases the player's score.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Aditi22Bansal ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @Aditi22Bansal ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
