### ISSUE TITLE
[Bug]: Background music is not audible in Animal Match Game

### ISSUE THREAD

**Issue by meetarora10** [kunjgit/GameZone#3687]
### Give a brief about the bug ✍️

Background music is not audible in the game which makes it unclear that whether the player has finally won or not.

### What is the expected behavior? 🤔

Different background music should be audible while winning and losing.

### Provide step by step information reproduce the bug 📄

I can attach different audio files in the java script so that different music is played  while winning or losing.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @meetarora10 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)
