### ISSUE TITLE
[New game]: General Knowledge Quiz

### ISSUE THREAD

**Issue by isha-dutta** [kunjgit/GameZone#3689]
### 🎮 Game Request

Are you ready to put your programming knowledge to the test? Whether you're a seasoned developer or just starting your coding journey, a General Knowledge Quiz for programmers can be both fun and educational.

Dive into an engaging quiz game crafted with HTML, CSS, and JavaScript. Challenge yourself with a series of questions, each with a strict 15-second time limit. Correct answers are crucial as there's no going back—question navigation is disabled to keep the game fast-paced and thrilling.

### Point down the features

Time Challenge: Each question must be answered within 15 seconds, adding a layer of excitement and urgency.
No Navigation: Players must think quickly and answer on the spot—no going back to previous questions.
Interactive Design: Enjoy a visually appealing interface with smooth transitions and animations.
Score Tracking: Keep track of your performance and strive to improve with each attempt.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by isha-dutta** [comment]
@kunjgit can you assign me this

**Comment by kunjgit** [comment]
Hey @isha-dutta ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
