### ISSUE TITLE
[New game]: DJ drum game 

### ISSUE THREAD

**Issue by Babunshil** [kunjgit/GameZone#369]
### 🎮 Game Request

This is a virtual DJ drum created using HTML, CSS, and JavaScript. It allows users to create beats and rhythms using various drum sounds and effects, making it a convenient tool for musicians and DJs to experiment with and create their own music.

### Point down the features

*7 different drum sounds, including kick, snare, hi-hat, cymbals, and more.
*Interactive UI with clickable drum pads and buttons.
*Effects such as delay and reverb to add depth and texture to your beats. *Responsive design that works on desktop and mobile devices.
![229629941-00a11afc-a57d-4648-852e-d3e060437263](https://github.com/kunjgit/GameZone/assets/106283743/49580ab0-e23a-4993-b7e0-38c8bfe7a1d8)

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by Babunshil** [comment]
kindly add the GSSoc23 label

**Comment by Lavesh12** [comment]
Hello,
I hope you're doing well. I am interested in contributing to this project as part of GSSoC. It aligns with my skills and interests, and I believe I can make a meaningful contribution to the project Could you please assign this task to me? 
Looking forward to hearing from you.
Thank you,
Lavesh Vishwakarma

**Comment by Babunshil** [comment]
@Lavesh12 currently I am working on it. You can make a PR with your unique idea if you want to contribute

**Comment by kunjgit** [comment]
Hey @Babunshil ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
