### ISSUE TITLE
[Enhancement]: There is no bridge between similar games(for Example MOVIE GUESSING GAME, WORD GUESSING GAME,MUSIC GUESSING GAME and FLAG GUESSING GAME.

### ISSUE THREAD

**Issue by TusharChamlikar** [kunjgit/GameZone#3690]
### Do you want to have the enhancement of existing game ? 😀 Describe yourself..

Game enhancement
I want to connect these similar games via a switch so that user can easily switch between these games.
I also want to change the background of movie guessing game

### Describe the solution you'd like

Solution steps
I will make changes in movie guessing games.
I will add a button of three other similar  games(1. Flag Guessing Game, 2. Word Guessing Game, 3. Music Guessing Game) in Movie guessing games.
I will also change the background of movie guessing game.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @TusharChamlikar ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @TusharChamlikar ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
