### ISSUE TITLE
[New game]:  Math Game 

### ISSUE THREAD

**Issue by codewithganeshhh** [kunjgit/GameZone#3698]
### 🎮 Game Request

**Game logic and basic description:**

- Basic math Calculation.
- Single player Game.
- Timer Mode 

### Point down the features

Game points:
Each solution has new point 
Each correct solution increase time.
![Screenshot 2024-05-24 132554](https://github.com/kunjgit/GameZone/assets/139307139/2f74968e-5cc2-4031-be0e-121f4bfb13ce)

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @codewithganeshhh ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @codewithganeshhh ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
