### ISSUE TITLE
[Number Gussing Game]: 

### ISSUE THREAD

**Issue by Chayandev** [kunjgit/GameZone#37]
### 🎮 Game Request

Game logic and basic description
One random number will be genarated by computer itself , player have to guess it within 10 chances , for every wrong guess one chance and pint will be lost and also the range of the exact number will be shown as a hint .

### Point down the features

Game points

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by Chayandev** [comment]
@kunjgit please give me the opportunity to contribute this project...

**Comment by kunjgit** [comment]
Hey @Chayandev thank you for having your interest to contribute to GameZone 🎮 
But it is looking too much simple add some more features and also elaborate about them here !!

**Comment by Chayandev** [comment]
Ig you want to take look into the game I can share the link ,, just 2 mins u see it and then if u think more features or more work needs to improve it then I will definitely add some more features and will add it ..

**Comment by Lavesh12** [comment]
Hello,
I hope you're doing well. I am interested in contributing to this project as part of GSSoC. It aligns with my skills and interests, and I believe I can make a meaningful contribution to the project Could you please assign this task to me? 
Looking forward to hearing from you.
Thank you,
Lavesh Vishwakarma

**Comment by kunjgit** [comment]
Hey @Chayandev ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
