### ISSUE TITLE
[New game]: Magic Square

### ISSUE THREAD

**Issue by JPV2207** [kunjgit/GameZone#370]
### 🎮 Game Request

The Magic Square is a game made using HTML, CSS and Javascript where there are numbers from 1-9 and there are 3 basic math operations (+, -, *) which one need to do in order to get the answer. The game is easy to play and will help in improving the math skills of a player.

### Point down the features

• The game is based on a 5*5 matrix where there are empty spaces which are provided to fill in the number.
• Along with that after every empty square there is a math operation which is provided for doing the particular operation.
• The pattern is followed in each row and column.
• The game gets over as soon as the player fills all the empty spaces with right numbers.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @JPV2207 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by JPV2207** [comment]
Thank you for assigning me this issue!

**Comment by Harshvardhan-Dubey-Github** [comment]
please assign me this issue

**Comment by kunjgit** [comment]
Hello @JPV2207, Time's Uppp!⏰ 
 Sorry for closing your issue! 
 But it's more than a week since we haven't received anything from your side 😢 . 
 Come up with new ideas, create a new issue and make sure you finish it within a week! 🔥 
 All the best! 🚀 
 Happy Hacking! 💗

**Comment by kunjgit** [comment]
Hey @JPV2207 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
