### ISSUE TITLE
[Enhancement]: Adding two modes options light/dark mode

### ISSUE THREAD

**Issue by zalabhavy** [kunjgit/GameZone#3705]
### Do you want to have the enhancement of existing game ? 😀 Describe yourself..

Hello, Kunj. I am a student at Nirma University from Kapadwanj. I am starting my contribution journey in GSSoC '24. I have created many web development projects and now want to contribute to various projects.

### Describe the solution you'd like

I'll add a mode indicator picture in the top right corner, using JavaScript for dynamic updates and HTML/CSS for fixed positioning, enhancing user experience by providing clear mode information.

![iambhavy](https://github.com/kunjgit/GameZone/assets/126322584/decdf45d-8626-4ad9-86b7-a7201b6a5b08)

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @zalabhavy ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @zalabhavy ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
