### ISSUE TITLE
[Bug]:  pig game doesnot have instructions before

### ISSUE THREAD

**Issue by jahnaviyallamelli** [kunjgit/GameZone#3709]
### Give a brief about the bug ✍️

Description:
every player requires instructions about how to play without that they dont show much intrest so 
many of the games doesnt have instructions before one of them is pig game.

### What is the expected behavior? 🤔

Description:
alerting the player how to play before game starts!

### Provide step by step information reproduce the bug 📄

Description: before starting the game one alert should come with all proper instructions about how to play.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by jahnaviyallamelli** [comment]
assign this task to me

**Comment by kunjgit** [comment]
Hey @jahnaviyallamelli ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by jahnaviyallamelli** [comment]
can you assign this task to me i want to work on it

**Comment by Saketh1714** [comment]
Hey can you assign this task to me I want to work on this.

**Comment by Deepthi-Ramineni** [comment]
I would to work on this. can you please assign this to me...???

**Comment by shaklan2001** [comment]
I would to work on this. can you please assign this to me...???

**Comment by kunjgit** [comment]
Hey @jahnaviyallamelli ! , This issue is already assigned to @shaklan2001. 💗 
 You can work on other issues 🚀 
 If there is anything wrong you can contact us on [Discord🕹️](https://discord.gg/fgwk4XZfxG)👀

**Comment by kunjgit** [comment]
Hey @jahnaviyallamelli ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
