### ISSUE TITLE
[New game]: Chrome Dinosaur Game

### ISSUE THREAD

**Issue by its-kritika** [kunjgit/GameZone#3716]
### 🎮 Game Request

In this game I will create Chrome Dinosaur game using HTML, CSS, and JavaScript. It involves building a simple, offline game where a dinosaur character runs across a desert landscape, jumping over obstacles to avoid collisions. The objective is to achieve the highest score possible by running for as long as one can without hitting any obstacles.

Similar to this SS
![chrome-dino](https://github.com/kunjgit/GameZone/assets/144522556/5c8a69ed-9c34-434f-9f96-a98145cc5715)

### Point down the features

- Character Movement: Use keyboard controls to make the dinosaur jump.
- Obstacle Generation: Dynamically create and move obstacles across the screen.
- Collision Detection: Detect collisions between the dinosaur and obstacles to end the game.
- Score Keeping: Update and display the score based on the time survived.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @its-kritika! 
We are already having a similar game request in #3242 👀 
Make sure you come up with a cool unique idea 😀 
 Waiting for your new game idea 💗.

**Comment by kunjgit** [comment]
Hey @its-kritika ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
