### ISSUE TITLE
[Enhancement]:  Add home screen button in the Master Typing gamr

### ISSUE THREAD

**Issue by dharshini2022** [kunjgit/GameZone#3717]
### Do you want to have the enhancement of existing game ? 😀 Describe yourself..

Game enhancement. The addition of a button to navigate back to the home screen will enhance the navigability of the game
![Screenshot 2024-05-25 100439](https://github.com/kunjgit/GameZone/assets/123349807/9d6c3a18-ebf4-4933-b340-20c9ce5431f5)

### Describe the solution you'd like

Solution steps: A button that will navigate the user back to the home screen when clicked

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @dharshini2022 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by dvnshi** [comment]
please assign this issue to me

**Comment by dharshini2022** [comment]
Assign @dharshini2022

**Comment by dharshini2022** [comment]
Hello sir, could pls help me self-assigning the issue? I don't know how to
do it. I would be grateful if you assist me in this regard. Thank you

**Comment by kunjgit** [comment]
Hello @dharshini2022, Time's up!⏰ 
 Sorry for closing your issue! 
 But it's more than a week since we haven't received anything from your side 😢 . 
 Come up with new ideas, create a new issue and make sure you finish it within a week! 🔥 
 All the best! 🚀 
 Happy Hacking! 💗

**Comment by kunjgit** [comment]
Hey @dharshini2022 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
