### ISSUE TITLE
Tower Stack[New game]: 

### ISSUE THREAD

**Issue by Manish15559** [kunjgit/GameZone#3719]
### 🎮 Game Request

Game logic and basic description

- HTML, CSS, and Javascript are used in the creation of this game.
- The main objective of the Tower Stack game is to build the tallest possible tower by stacking blocks on top of each other as accurately as possible.

### Point down the features

**Gameplay Mechanics**

 Starting the Game:
- The game begins with a single block placed at the center of the screen or playing area.

Moving Blocks:
- New blocks move horizontally across the screen from left to right or right to left.
- The speed of the moving blocks can vary, typically increasing as the game progresses.

Stacking Blocks:
- The player must tap the screen (or press a key, depending on the platform) to drop the moving block directly onto the stack.
- The goal is to align the new block perfectly with the block beneath it.
- If the block is not aligned perfectly, the portion of the block that hangs over the edge is cut off, and only the remaining aligned part is added to the stack.

End of the Game:
- The game ends when a block is so misaligned that it falls off the stack completely, or when the player fails to stack a block within a certain time limit.
- The height of the tower at the point the game ends is the player's score

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Manish15559 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hello @Manish15559, Time's up!⏰ 
 Sorry for closing your issue! 
 But it's more than a week since we haven't received anything from your side 😢 . 
 Come up with new ideas, create a new issue and make sure you finish it within a week! 🔥 
 All the best! 🚀 
 Happy Hacking! 💗

**Comment by kunjgit** [comment]
Hey @Manish15559 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
