### ISSUE TITLE
[New game]: Fruit Catch Game

### ISSUE THREAD

**Issue by its-kritika** [kunjgit/GameZone#3724]
### 🎮 Game Request

The player controls a basket at the bottom of the screen to catch fruits falling from the top. The game ends when the player misses 5 fruits. 
![source](https://github.com/kunjgit/GameZone/assets/144522556/65912e92-52f7-4395-82ea-0877c506ce28)

### Point down the features

- Levels and Difficulty: Increase the speed and frequency of falling fruits as the player's score increases.
-  Different Fruit Types: There will be different types of fruits.
- Friendly user interface

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @its-kritika ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @its-kritika ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
