### ISSUE TITLE
[New game]: HIT YOUR FRIEND

### ISSUE THREAD

**Issue by 18Venus** [kunjgit/GameZone#3726]
### 🎮 Game Request

There will be 2 players and 1 ball. Each player will alternatively get a chance to hit the other player with the ball with buildings being an obstacle. The one who hits the other first, wins!

### Point down the features

1. You may drag the ball more to increase its velocity.
2. The buildings shall serve as your obstacles.
3. You may reload the page to bring changes into the heights of the buildings!
4. Simple, easy to play, two players game.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @18Venus ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @18Venus ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
