### ISSUE TITLE
[New game]: Touch-No-Fire-Fame

### ISSUE THREAD

**Issue by Anjaliavv51** [kunjgit/GameZone#3727]
### 🎮 Game Request

Game logic and basic description
Game Rules!
* Eat the food to gain score
* Do not touch the fire
* The fire multiplies once with even scores
* If you stay idle, the fire won't do anything
* Do not touch the moving fire
* Please play using arrow keys

## Screenshot Section

![image](https://github.com/GameSphere-MultiPlayer/GameSphere/assets/154777864/8835bbe2-13a4-43d5-b986-bb30442f833c)

## Demo Video Section

https://github.com/GameSphere-MultiPlayer/GameSphere/assets/154777864/a88f676a-69c8-4cc9-b6e6-98e5fca1aa59

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Anjaliavv51 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by Anjaliavv51** [comment]
@kunjgit please review the Game!

**Comment by Anjaliavv51** [comment]
@kunjgit please review the Game!

**Comment by Anjaliavv51** [comment]
@kunjgit please review the game.

**Comment by kunjgit** [comment]
Hey @Anjaliavv51 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
