### ISSUE TITLE
[Bug]:  Not responsive for the range mentioned below

### ISSUE THREAD

**Issue by bhaskarkumar1** [kunjgit/GameZone#373]
### Give a brief about the bug ✍️

Description: 
your app is not responsive between 1039x563 to 1247x563 dimension of the screen.

Please assign me this task. So that I can fix this bug.

### What is the expected behavior? 🤔

Description;

It must have shown the normal behaviour, without scrolling through right to left wee have only a single screen that fits up to 2-3 games name

### Provide step by step information reproduce the bug 📄

Description

just check at the given dimension above you will find it

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @bhaskarkumar1 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by bhaskarkumar1** [comment]
Ok thank you @kunjgit.
I will work on this issue.

/assign

**Comment by bhaskarkumar1** [comment]
someone already fixed it before me 😢

**Comment by kunjgit** [comment]
Hello @bhaskarkumar1, Time's Uppp!⏰ 
 Sorry for closing your issue! 
 But it's more than a week since we haven't received anything from your side 😢 . 
 Come up with new ideas, create a new issue and make sure you finish it within a week! 🔥 
 All the best! 🚀 
 Happy Hacking! 💗

**Comment by kunjgit** [comment]
Hey @bhaskarkumar1 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
