### ISSUE TITLE
[Bug]: Dice images not shown

### ISSUE THREAD

**Issue by shaklan2001** [kunjgit/GameZone#3730]
### Give a brief about the bug ✍️

**Description:**
In the pig game the image of the dices not show when we role the dice ad also the thumbnail of the game is also not shown.

<img width="1112" alt="Screenshot 2024-05-25 at 5 29 02 PM" src="https://github.com/kunjgit/GameZone/assets/90901154/f0256279-96ce-4cd5-af53-b45dbfc52273">

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @shaklan2001 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @shaklan2001 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
