### ISSUE TITLE
[New game]: Hit or Miss Cricket  🏏

### ISSUE THREAD

**Issue by namandude** [kunjgit/GameZone#3732]
### 🎮 Game Request

"Hit or Miss Cricket 🏏" is an interactive web game where players test their luck by predicting the outcome of each cricket ball—Six, Four, Single, Double, or Triple. Points are awarded for correct guesses, and the game continues until an incorrect guess is made. It's a simple yet engaging way to enjoy cricket and see how lucky you are with your predictions.

### Point down the features

 > Five buttons representing possible outcomes (Six, Four, Single, Double, Triple).
 > Display area for showing the result of the guess.
 > Scoreboard to keep track of the player's points.
 > Restart button to reset the game and start over.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @namandude ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by namandude** [comment]
Hey Please check the pr

**Comment by kunjgit** [comment]
Hey @namandude ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
