### ISSUE TITLE
[New game]: HitCounterPro

### ISSUE THREAD

**Issue by anisharma07** [kunjgit/GameZone#3733]
### 🎮 Game Request

Game logic and basic description

The Game will count the total number of 
i) spacebar hits
ii} mouse clicks  
(two games in one) for a specific period of time decided by the user .....
I will build a clean UI for the game and javascript logic for the same.

![image](https://github.com/kunjgit/GameZone/assets/126901961/31129b0f-220d-4c01-866a-e93d8b0bb679)

### Point down the features

Game points

1. Choose time limit for the game.
2. Game starts as soon as someone starts hitting on the keyboard or mouse clicks.
3. Results popup for the hits per minute or clicks per minute

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @anisharma07 , You can't have another issue before completing the previous one 😀 
 you already have the following 1 open issues 👀 ! :

#3457

**Comment by kunjgit** [comment]
Hey @anisharma07 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by kunjgit** [comment]
Hey @anisharma07 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)
