### ISSUE TITLE
[New game]: HitCounterPro

### ISSUE THREAD

**Issue by anisharma07** [kunjgit/GameZone#3734]
### 🎮 Game Request

Game logic and basic description

The Game will count the total number of
i) spacebar hits
ii} mouse clicks
(two games in one) for a specific period of time decided by the user .....
I will build a clean UI for the game and javascript logic for the same.

![Screenshot 2024-05-25 181604](https://github.com/kunjgit/GameZone/assets/126901961/ee04b821-7464-42be-aa7b-0c6adcd11ed0)

### Point down the features

Game points

1. Timer choosen by user.
2. Game starts as soon as user hits the spacebar.
3. Game ends and result will appear after timer has stopped

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @anisharma07 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @anisharma07 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
