### ISSUE TITLE
[New game]: Memory Flip

### ISSUE THREAD

**Issue by Aditi22Bansal** [kunjgit/GameZone#3744]
### 🎮 Game Request

Game logic and basic description
In this game, players flip tiles to find matching pairs. The goal is to match all pairs within a limited number of moves.

### Point down the features

Game points
1. Shuffled Tile Values
The game generates and shuffles tile values so that each game session is unique. This is implemented in the generateTileValues() function, which creates pairs of values, shuffles them, and assigns them to the tiles.

2. Move Counter
The game tracks the number of moves the player has made. This is displayed on the screen and updated every time two tiles are flipped. The move count is implemented using the moves variable and updated within the flipTile() and checkMatch() functions.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Aditi22Bansal , You can't have another issue before completing the previous one 😀 
 you already have the following 1 open issues 👀 ! :

#3742

**Comment by kunjgit** [comment]
Hey @Aditi22Bansal ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by kunjgit** [comment]
Hey @Aditi22Bansal ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by Aditi22Bansal** [comment]
Why this issue is closed?
Please clarify
Thankyou
