### ISSUE TITLE
[New game]: Color Catcher

### ISSUE THREAD

**Issue by Aditi22Bansal** [kunjgit/GameZone#3745]
### 🎮 Game Request

Game logic and basic description
In this game, players control a character that changes color. The objective is to collect falling objects of the same color while avoiding those of different colors.

### Point down the features

Game points
The player controls a character that changes color over time.
Objects of various colors fall from the top of the screen.
When the character and object colors match, the player scores points and the object disappears.
If the character collides with an object of a different color, the game ends.
The game becomes progressively faster and more challenging over time.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Aditi22Bansal , You can't have another issue before completing the previous one 😀 
 you already have the following 1 open issues 👀 ! :

#3742

**Comment by kunjgit** [comment]
Hey @Aditi22Bansal ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by kunjgit** [comment]
Hey @Aditi22Bansal ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @Aditi22Bansal! 
We are already having a similar game request in #3597 👀 
Make sure you come up with a cool unique idea 😀 
 Waiting for your new game idea 💗.
