### ISSUE TITLE
[New game]: Time Blender

### ISSUE THREAD

**Issue by Aditi22Bansal** [kunjgit/GameZone#3746]
### 🎮 Game Request

Game logic and basic description
In this game, players manipulate time to solve puzzles and navigate through levels

### Point down the features

Game points
The player controls a character with the ability to manipulate time.
Each level presents obstacles and puzzles that require time manipulation to overcome.
Time can be rewound, slowed down, or sped up to affect the environment and solve challenges.
The player must strategize and use their time-bending abilities effectively to progress.
As the game advances, levels become more complex, requiring precise timing and clever solutions.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Aditi22Bansal , You can't have another issue before completing the previous one 😀 
 you already have the following 1 open issues 👀 ! :

#3742

**Comment by kunjgit** [comment]
Hey @Aditi22Bansal ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by kunjgit** [comment]
Hey @Aditi22Bansal ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)
