### ISSUE TITLE
[New game]: Periodic table game

### ISSUE THREAD

**Issue by Vipullakum007** [kunjgit/GameZone#3749]
### 🎮 Game Request

Game logic and basic description : there 2 page index => shows all elements  , game page = > user needs to find symbol of provided elements.

### Point down the features

Game points: if select correct element score increase . if wrong element selected then deducted.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Vipullakum007 , You can't have another issue before completing the previous one 😀 
 you already have the following 1 open issues 👀 ! :

#3582

**Comment by kunjgit** [comment]
Hey @Vipullakum007 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by kunjgit** [comment]
Hey @Vipullakum007 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @Vipullakum007! 
We are already having a similar game request in #3248 👀 
Make sure you come up with a cool unique idea 😀 
 Waiting for your new game idea 💗.
