### ISSUE TITLE
[New game]: NameFate

### ISSUE THREAD

**Issue by NAVJOT-786** [kunjgit/GameZone#3754]
### 🎮 Game Request

🎮 Game Request: NameFate Game
Describe the game logic and also give a brief about the features of the game
Game logic and basic description:

NameFate is a captivating game that delves into the mysterious connections between names and destinies. Players input two names, and the game algorithm calculates their fate based on various factors derived from the combination of characters in the names. The result provides insight into the potential relationship dynamics between the individuals.

Features:

Name Combination: The game combines the characters from two input names to explore the intertwined destiny.
Fate Calculation: Utilizes an algorithm to analyze the combined names and derive fate-related insights.
Interactive Interface: User-friendly interface with input fields and a button for initiating fate calculation.
Real-Time Feedback: Provides immediate feedback on the calculated fate, allowing players to discover the outcome instantly.
Dynamic Results: Presents a variety of fate outcomes, ranging from harmonious to tumultuous relationships.
Customization Options: Offers customization features such as theme selection and result sharing for a personalized experience.
Educational Value: Provides an entertaining way to learn about the potential significance of names in interpersonal relationships.

I am contributing upon Gssoc24 Please assign

### Point down the features

Detailed Game Logic:

Input Names: Players enter two names into the input fields.
Normalize Names: Converts both names to lowercase and removes any whitespace.
Combine Names: Merges the two normalized names into a single string.
Character Analysis: Analyzes the combined string to identify unique characters and their frequencies.
Fate Calculation: Applies a predetermined algorithm to calculate the fate based on the character analysis.
Result Display: Presents the calculated fate outcome to the players, offering insights into their potential relationship dynamics.
Example Calculation:

Names: Emma and Daniel
Combined: emmadaniel
Unique Characters: (e, m, a, d, n, i, l)
Fate Calculation: Utilizes the frequencies of unique characters to determine the fate outcome.
Result: The game reveals the fate outcome, such as "Harmonious Connection" or "Dynamic Relationship," based on the calculated analysis.
Point down the features
Intuitive Interface: User-friendly design with clear instructions and prompts.
Instant Feedback: Immediate display of fate outcome after inputting names.
Varied Results: Offers a range of fate outcomes to reflect diverse relationship possibilities.
Personalized Experience: Customization options for theme selection and result sharing.
Educational Insights: Provides insights into the potential significance of names in relationship dynamics.
Engaging Gameplay: Captivates players with the intrigue of exploring name-based destinies.

I am contributing upon Gssoc24 Please assign

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @NAVJOT-786 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by NAVJOT-786** [comment]
@kunjgit please add Gssoc label

**Comment by NAVJOT-786** [comment]
@kunjgit please add Gsooc label

**Comment by kunjgit** [comment]
Hey @NAVJOT-786 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
