### ISSUE TITLE
[Bug]: Thumbnail not visible for Game No.393 Pathfinder Puzzle

### ISSUE THREAD

**Issue by ansh-h-mehta** [kunjgit/GameZone#3758]
### Give a brief about the bug ✍️

THumbnail is not visible for this particular game
![image](https://github.com/kunjgit/GameZone/assets/99081110/252fc17f-c0bc-4eeb-8c6c-bb4befe6a22d)

### What is the expected behavior? 🤔

Thumbnail must be visible 

### Provide step by step information reproduce the bug 📄

Go to 'https://kunjgit.github.io/GameZone/'
Select Page No.20
Scroll down
Find game No.393 Pathfinder Puzzle
See the issue

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by ansh-h-mehta** [comment]
Kindly Assign this bug to me, I'd be happy to fix it

**Comment by kunjgit** [comment]
Hey @ansh-h-mehta ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hello @ansh-h-mehta, Time's up!⏰ 
 Sorry for closing your issue! 
 But it's more than a week since we haven't received anything from your side 😢 . 
 Come up with new ideas, create a new issue and make sure you finish it within a week! 🔥 
 All the best! 🚀 
 Happy Hacking! 💗

**Comment by kunjgit** [comment]
Hey @ansh-h-mehta ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
