### ISSUE TITLE
[Bug]: Tennis game is not working

### ISSUE THREAD

**Issue by vidhiisaxena** [kunjgit/GameZone#3765]
### Give a brief about the bug ✍️

Description
the tennis game is not working with no ball, paddles and score elements.
![image](https://github.com/kunjgit/GameZone/assets/144513634/61894afe-de09-4069-a836-960121f50a62)

### What is the expected behavior? 🤔

Description
The game cannot be played until the problem is resolved. It is just a blank screen which is not expected. 

### Provide step by step information reproduce the bug 📄

Description
Under the github repository, in the games folder when you locate the tennis game, you can see the errors and resolve them.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @vidhiisaxena ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @vidhiisaxena ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by kunjgit** [comment]
Hey @vidhiisaxena ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
