### ISSUE TITLE
[New game]: color matching application

### ISSUE THREAD

**Issue by TiwariRahul16** [kunjgit/GameZone#3767]
### 🎮 Game Request

In this game, you are provided one color and are asked to select it from the list of colors below.
You win if you select the correct color; if not, you lose.

![colorgame](https://github.com/kunjgit/GameZone/assets/168175850/9e5eb617-fcdf-46e9-9b3e-fc658b98adc2)

### Point down the features

In this game, you are provided one color and are asked to select it from the list of colors below.
You win if you select the correct color; if not, you lose.
This game's characteristic is that it displays several colors, some of which are only shades of one the color; you must select the correct color.
simple and better user interface

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @TiwariRahul16 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by Anmolgupta2004** [comment]
can you please assign to me that issue?

**Comment by kunjgit** [comment]
Hey @TiwariRahul16 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
