### ISSUE TITLE
[Enhancement]: Tic Tac Toe game Missing Error

### ISSUE THREAD

**Issue by sivaprasath2004** [kunjgit/GameZone#3771]
### Do you want to have the enhancement of existing game ? 😀 Describe yourself..

- In this game win the player `x` after that match is finish,but the game not finish continuous move is worked.
- This spolling the game rules.
- please assign me.. 
- i want to add proper game and UI

### Expected behaviour & UI
[Screencast from 2024-05-26 13-38-39.webm](https://github.com/kunjgit/GameZone/assets/121082414/91bb65da-ed4c-4914-95a5-9383a37f46fc)

### Actual behaviour & UI
[Screencast from 2024-05-26 13-32-46.webm](https://github.com/kunjgit/GameZone/assets/121082414/edc19793-261a-48cc-a1be-e4451da00e52)

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @sivaprasath2004 , You can't have another issue before completing the previous one 😀 
 you already have the following 1 open issues 👀 ! :

#3154

**Comment by kunjgit** [comment]
Hey @sivaprasath2004 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by kunjgit** [comment]
Hey @sivaprasath2004 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by sivaprasath2004** [comment]
@kunjgit why the issue can closed... Please explain

**Comment by sivaprasath2004** [comment]
I will work on the isuue

**Comment by sivaprasath2004** [comment]
@kunjgit i will close the previous issue #3154 
- please reopen the issue....
