### ISSUE TITLE
[New game]: Poker Game

### ISSUE THREAD

**Issue by Swarnav-Kumar** [kunjgit/GameZone#3773]
### 🎮 Game Request

Game logic and basic description:-A card game that combines strategy, skill, and luck.

### Point down the features

Game points:-
1.The structure includes sections for two players and the community cards with a deal button.
2. Basic styling to center elements and style the cards.
3.Creates and shuffles a deck of cards.
4.Deals two cards to each player and five community cards.
5.Renders the dealt cards to the screen.
6.Uses setTimeout to simulate the stages of dealing the community cards (flop, turn, river).

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Swarnav-Kumar ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by Swarnav-Kumar** [comment]
assign

**Comment by kunjgit** [comment]
Hello @Swarnav-Kumar, Time's up!⏰ 
 Sorry for closing your issue! 
 But it's more than a week since we haven't received anything from your side 😢 . 
 Come up with new ideas, create a new issue and make sure you finish it within a week! 🔥 
 All the best! 🚀 
 Happy Hacking! 💗

**Comment by kunjgit** [comment]
Hey @Swarnav-Kumar ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
