### ISSUE TITLE
[Enhancement]: UI of "Guess The Correct Logo Game". and adding new features.

### ISSUE THREAD

**Issue by Changingthegame** [kunjgit/GameZone#3776]
### Do you want to have the enhancement of existing game ? 😀 Describe yourself..

I played this game and found that it's a nice game for children and adults who keep good interest in popular brands as there is always a  discussion between friends what's this brand's logo etc. But when I clicked on the game the thing I do not liked was that there is no catchy and attractive background and also the instructions are given in very dull manner with no attractive colors and nice fonts as well as there should be a background color of the start button. Also during playing , I found that the background there is also black which should be changed to a attractive and fancy as well as brighter one. I am also thinking of adding more logos and pause, resume  buttons if possible , I will try this one also...                                                                                                                                                  

### Describe the solution you'd like

Firstly, I will improve the initial page UI then I will make the main page attractive and also change the fonts and background of the button ( start button ). 
Also , if possible I will try my best to add more logos and a pause, resume button.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Changingthegame , You can't have another issue before completing the previous one 😀 
 you already have the following 1 open issues 👀 ! :

#3369

**Comment by kunjgit** [comment]
Hey @Changingthegame ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by kunjgit** [comment]
Hey @Changingthegame ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by Changingthegame** [comment]
I have a query that this issue is closed at present , then what should I do?

**Comment by Changingthegame** [comment]
Can you please tell me that should I self assign me this issue instead of caring about the issue is closed or open , will it be counted as my contribution and also will I be able to make a pull request for this?
