### ISSUE TITLE
[Bug]:  Making the background more appealing and attractive for better increasing user stay on website

### ISSUE THREAD

**Issue by MUKUL-RAJPUT2004** [kunjgit/GameZone#3777]
### Give a brief about the bug ✍️

Description : I will change the background from solid black.

### What is the expected behavior? 🤔

Description: It should me attractive.

### Provide step by step information reproduce the bug 📄

Description: I will change to some appealing picture or video in background .
![Screenshot (41)](https://github.com/kunjgit/GameZone/assets/118878628/55e5238b-9417-4092-9444-2cfcea217f99)

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @MUKUL-RAJPUT2004 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by SanaAzeem512** [comment]
@kunjgit Hello
please assign this issue to me under GSSOC24

**Comment by kunjgit** [comment]
Hello @MUKUL-RAJPUT2004, Time's up!⏰ 
 Sorry for closing your issue! 
 But it's more than a week since we haven't received anything from your side 😢 . 
 Come up with new ideas, create a new issue and make sure you finish it within a week! 🔥 
 All the best! 🚀 
 Happy Hacking! 💗

**Comment by kunjgit** [comment]
Hey @MUKUL-RAJPUT2004 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
