### ISSUE TITLE
[Bug]:  Bullseye does not have thumbnail 

### ISSUE THREAD

**Issue by MUKUL-RAJPUT2004** [kunjgit/GameZone#3778]
### Give a brief about the bug ✍️

Description : Game Bullseye does not have thumbnail in its card. I can add that.
Please assign it to me in Gsoc 2024 I will solve fix it at my earliest .
Looking for a positive response from your side.
Thank you

### What is the expected behavior? 🤔

Description: It should have good appealing thumbnail.

### Provide step by step information reproduce the bug 📄

Description: I will add an appe
![Uploading photo_2024-05-26_15-40-18.jpg…]()
aling thumbnail to it.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @MUKUL-RAJPUT2004 , You can't have another issue before completing the previous one 😀 
 you already have the following 1 open issues 👀 ! :

#3777

**Comment by kunjgit** [comment]
Hey @MUKUL-RAJPUT2004 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by kunjgit** [comment]
Hey @MUKUL-RAJPUT2004 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)
