### ISSUE TITLE
[Enhancement]: Piano Keys Edit

### ISSUE THREAD

**Issue by bhumika-1127** [kunjgit/GameZone#3780]
### Do you want to have the enhancement of existing game ? 😀 Describe yourself..

Change the color of the keys to distinguish whether the key is pressed or not. @kunjgit I wanted to solve this issue under GSSOC'24.

### Describe the solution you'd like

![image](https://github.com/kunjgit/GameZone/assets/137604220/8c386762-b911-4b91-ba16-c92dd0ce0f16)

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @bhumika-1127 , You can't have another issue before completing the previous one 😀 
 you already have the following 1 open issues 👀 ! :

#3641

**Comment by kunjgit** [comment]
Hey @bhumika-1127 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by kunjgit** [comment]
Hey @bhumika-1127 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)
