### ISSUE TITLE
[Bug]: The ludo game is not supported for 4 players.

### ISSUE THREAD

**Issue by Bhagat-Nidhi** [kunjgit/GameZone#3785]
### Give a brief about the bug ✍️

I've tried playing the ludo game but instead of giving option for chooding no. of players and colours only two players are by default given insted of allowing the user to choose .
I would like to work on the issue.
![Screenshot 2024-05-26 173047](https://github.com/kunjgit/GameZone/assets/150457325/cd8d0684-3a77-4a50-aedc-e89cb8b7da62)

### What is the expected behavior? 🤔

The game should allow the user to choose the no of players and the colour by which he wants to play(red/blue/green/yellow)
![Screenshot 2024-05-26 173627](https://github.com/kunjgit/GameZone/assets/150457325/9086e945-9890-4b17-b72e-9ed9bc6e0b69)
![Screenshot 2024-05-26 173654](https://github.com/kunjgit/GameZone/assets/150457325/f84e60ce-72e6-494d-806b-55c1978406f6)

### Provide step by step information reproduce the bug 📄

Please assign the issue to me I would like to contribute in the betterment of this

### Select program in which you are contributing

GSSOC'24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Bhagat-Nidhi ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by Bhagat-Nidhi** [comment]
my previous game was unassigned can you either assign this rummy game to me or re assignthe ludo one?

**Comment by Bhagat-Nidhi** [comment]
I also forgot to add the GSSOC'24 label in the program section can you do put the label?

**Comment by kunjgit** [comment]
Hello @Bhagat-Nidhi, Time's up!⏰ 
 Sorry for closing your issue! 
 But it's more than a week since we haven't received anything from your side 😢 . 
 Come up with new ideas, create a new issue and make sure you finish it within a week! 🔥 
 All the best! 🚀 
 Happy Hacking! 💗

**Comment by kunjgit** [comment]
Hey @Bhagat-Nidhi ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
