### ISSUE TITLE
[New game]: Rummy

### ISSUE THREAD

**Issue by Bhagat-Nidhi** [kunjgit/GameZone#3786]
### 🎮 Game Request

Rummy is a popular card game known for its simple rules and strategic depth. The objective is to form sets and runs with your cards and be the first to get rid of all your cards or have the lowest unmatched cards' total

The main goal in rummy is to create sets and runs from the cards in your hand. A set is a group of three or four cards of the same rank but different suits (e.g., 8♦ 8♠ 8♣), and a run is a sequence of three or more consecutive cards of the same suit (e.g., 4♠ 5♠ 6♠).

I would like to contribute in the creation of this new game

### Point down the features

Cards 2 through 10 are worth their face value.
Face cards (Jack, Queen, King) are worth 10 points each.
Aces can be worth 1 or 11 points, depending on the variant.

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Bhagat-Nidhi , You can't have another issue before completing the previous one 😀 
 you already have the following 1 open issues 👀 ! :

#3785

**Comment by kunjgit** [comment]
Hey @Bhagat-Nidhi ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by kunjgit** [comment]
Hey @Bhagat-Nidhi ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)
