### ISSUE TITLE
[New game]:  Ping Pong Singleplayer

### ISSUE THREAD

**Issue by vidhiisaxena** [kunjgit/GameZone#3789]
### 🎮 Game Request

Game logic and basic description:
The pinball game involves moving a ball within a confined area, changing direction upon collision with the paddle, aiming to keep the ball in play as long as possible. The paddle will move with the help of up and down arrows.

### Point down the features

Game points:

- It is a single player game where a single person will play with another moving paddle.
- The player will gain points if the second paddle is unable to touch the ball in time.
- The player will lose points if his paddle misses to hit the ball. 

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @vidhiisaxena , You can't have another issue before completing the previous one 😀 
 you already have the following 1 open issues 👀 ! :

#3765

**Comment by kunjgit** [comment]
Hey @vidhiisaxena ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by kunjgit** [comment]
Hey @vidhiisaxena ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)
