### ISSUE TITLE
[Bug]: Horizontal Scroll in Light Mode

### ISSUE THREAD

**Issue by rahul-p19** [kunjgit/GameZone#3790]
### Give a brief about the bug ✍️

On changing to light mode, we get a horizontal scroll, although there is not extra content to view by scrolling.

### What is the expected behavior? 🤔

No horizontal scroll is expected.

### Provide step by step information reproduce the bug 📄

The bug can be fixed by adding removing overflow in x direction. I would also like to change the light mode background to a softer color which is better to look at.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @rahul-p19 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @rahul-p19 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
