### ISSUE TITLE
[Enhancement]: 

### ISSUE THREAD

**Issue by divyanshiet** [kunjgit/GameZone#38]
### Is your enhancement request related to a problem? Please describe.➕

Game enhancement

I would like to enhance the current view of your site By contributing in the CSS file.

### Describe the solution you'd like

Solution steps
1) The current website has the footer section at a sticky position which should need to be change.
2) also the games which were live on the website currently was need to be repositioned such that it would look prettier
3) above two issues were resolved by using CSS properties such as flexbox, grid, and position,etc.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @divyanshiet  ! Thank you for raising an issue 💗 You have been assigned this issue you can start working on the issue 🎮
Make sure you also show us what changes you want to make in design ❤️

**Comment by kunjgit** [comment]
Hello @divyanshiet, Time's Uppp!⏰ 
 Sorry for closing your issue! 
 But it's more than a week since we haven't received anything from your side 😢 . 
 Come up with new ideas, create a new issue and make sure you finish it within a week! 🔥 
 All the best! 🚀 
 Happy Hacking! 💗

**Comment by kunjgit** [comment]
Hey @divyanshiet ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
