### ISSUE TITLE
[New game]: Arkanoid Game

### ISSUE THREAD

**Issue by its-kritika** [kunjgit/GameZone#3800]
### 🎮 Game Request

Arkanoid is a modern take on the classic Breakout game, featuring enhanced gameplay, diverse brick types, and engaging challenges. In this game, players control a paddle to bounce a ball and break various bricks arranged on the screen. The objective is to clear all the bricks while preventing the ball from falling off the bottom edge of the screen.

### Point down the features

**Paddle Control:** Players use the left and right arrow keys to move the paddle horizontally along the bottom of the screen.
**Ball Physics:** The ball bounces off the paddle, walls, and bricks, changing direction with each collision.
**Brick Types:** The game includes three types of bricks, each with different hit points and corresponding score values:
- Normal Bricks: These blue bricks break with a single hit, awarding 10 points each.
- Silver Bricks: These silver bricks require two hits to break, awarding 20 points each upon destruction.
- Gold Bricks: These gold bricks are the toughest, requiring three hits to break, and awarding 30 points each upon destruction.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @its-kritika ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @its-kritika ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
