### ISSUE TITLE
[Enhancement]: Add Contribute Section to Homepage

### ISSUE THREAD

**Issue by JasmanD18** [kunjgit/GameZone#3802]
### Do you want to have the enhancement of existing game ? 😀 Describe yourself..

I am a contributor looking to enhance the usability and engagement of the GameZone website by adding a dedicated "Contribute" section to the homepage. This section will encourage visitors to contribute to the project and provide them with clear guidelines on how to get started.

### Describe the solution you'd like

Fork the GameZone repository and clone it locally.
Create a new branch for the enhancement.
Add the "Contribute" section to the index.html file.
Commit the changes with a meaningful commit message.
Push the changes to the forked repository.
Create a pull request with a detailed description of the enhancement.

### Select program in which you are contributing

Other

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @JasmanD18 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hello @JasmanD18, Time's up!⏰ 
 Sorry for closing your issue! 
 But it's more than a week since we haven't received anything from your side 😢 . 
 Come up with new ideas, create a new issue and make sure you finish it within a week! 🔥 
 All the best! 🚀 
 Happy Hacking! 💗

**Comment by kunjgit** [comment]
Hey @JasmanD18 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
