### ISSUE TITLE
[Enhancement]: "Adding Game Over feature and Alerts for Missed Balls with Home Page Option in Catch the Ball Game"

### ISSUE THREAD

**Issue by ShristiiSharma** [kunjgit/GameZone#3807]
### Do you want to have the enhancement of existing game ? 😀 Describe yourself..

Game enhancement
1. Improved User Experience: Providing alerts for missed balls and a game over notification enhances the user experience by giving clear feedback on game progress.
2. Enhanced Engagement: Alerts and navigation options increase player engagement by keeping them informed and providing a means to navigate between game states.
3. Reduced Frustration: Alerts help players stay informed about their progress, reducing frustration by providing timely feedback on missed balls and the game's end.
4. User-Friendly Navigation: Adding a home page navigation option offers convenience, allowing players to easily return to the main menu without hassle.

### Describe the solution you'd like

Solution steps
1. Game Over Alert: An alert will be displayed when the player misses 5 balls, indicating that the game is over.
2. Missed Ball Alert: An alert will be shown after each missed ball to notify the player.
3. Home Page Navigation: An option will be added to allow the player to navigate back to the home page.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @ShristiiSharma ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
