### ISSUE TITLE
[New game]: Color Shifting

### ISSUE THREAD

**Issue by MrVisc** [kunjgit/GameZone#381]
### 🎮 Game Request

The game tests the users reaction speeds.
1.Developing a game where a user is actively required to change color of object to traverse through the course and survive.
2.The obstacles come in different colors where the player needs to change color of ball to the obstacles color to pass through it.

Tech Stack Used: HTML, CSS, JS.

### Point down the features

1.Obstacle generation where obstacles of various shapes and sizes will be spawned.
2.Color switching where the user needs to change colors of ball depending on the obstacles.
3.Scoring and progression, keeping track of the score of the player and improving difficulty of the game progressing by speeding up the games pace.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @MrVisc ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @MrVisc ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
