### ISSUE TITLE
[New game]: NewsJunction

### ISSUE THREAD

**Issue by zalabhavy** [kunjgit/GameZone#3813]
### 🎮 Game Request

The "NewsJunction" allows users to enter topics of interest and fetches news articles related to those topics. It offers personalized news feeds, real-time updates, and customization options.

### Point down the features

Key Features:-

Topic-Based Feeds: Customized news based on user-selected topics.
Search Functionality: Find specific articles or topics on demand.
Real-Time Updates: Stay current with the latest news.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @zalabhavy ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @zalabhavy ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
