### ISSUE TITLE
[New game]: Simon Memory Game

### ISSUE THREAD

**Issue by aysal04** [kunjgit/GameZone#382]
### 🎮 Game Request

Game logic and basic description:

Its a game in which there are cards of dinstinct colors and using basic js we display a random color and user should click on the same. for the next turn computer displays one more color but this time user should click a pattern of previous card and the present card. Believe me it would be fun playing it to test our memory. I would like to add this game to the website.

### Point down the features

Game points:

This game helps us to test memory. Based on the highest level received users can compete with others individually.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @aysal04 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @aysal04! 
We are already having a similar game request in #365 👀 
Make sure you come up with a cool unique idea 😀 
 Waiting for your new game idea 💗.

**Comment by kunjgit** [comment]
Hey @aysal04 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
