### ISSUE TITLE
[New game]: Catch stars

### ISSUE THREAD

**Issue by manishh12** [kunjgit/GameZone#3824]
### 🎮 Game Request

Catch the  Stars is a fun and engaging game where players must catch stars appearing from the sky. The goal is to click on the stars as they fall, earning points for each star caught. The game lasts for 30 seconds, and the player's score is displayed at the end. This game tests your reflexes and provides a quick, entertaining challenge.

### Point down the features

Random Appearance: Stars appear at random positions and intervals on the screen.
Timed Gameplay: The game lasts for 30 seconds, providing a quick and engaging challenge.
Score Display: The player's score is updated in real-time and displayed at the end of the game.
Interactive Elements: Stars have animations and visual effects when caught.
Responsive Design: The game adjusts to different screen sizes and devices for optimal playability.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @manishh12 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @manishh12 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
