### ISSUE TITLE
[Enhancement]: Display number of ties along with wins and loses in rock paper scissors game.

### ISSUE THREAD

**Issue by meetarora10** [kunjgit/GameZone#3826]
### Do you want to have the enhancement of existing game ? 😀 Describe yourself..

The game currently displays the number of wins and loses . The number of ties can also be displayed on the screen.

### Describe the solution you'd like

I can display the number of ties along with the number of wins and loses.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @meetarora10 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
