### ISSUE TITLE
[New game]: Aim training game

### ISSUE THREAD

**Issue by DP-NOTHING** [kunjgit/GameZone#383]
### 🎮 Game Request

Game logic and basic description

- The bubble popping game is a simple and addictive game where the player's objective is to pop as many bubbles as possible within a limited time. Colorful bubbles randomly appear on the screen, and the player must quickly click on them to pop them. Each popped bubble earns the player a point, and the score is displayed in real-time. The game lasts for 30 seconds.

- The player starts the game by clicking the "Start" button.
- Bubbles start appearing on the screen at regular intervals.
- The player's goal is to click on the bubbles to pop them.

- Overall, the game aims to test the player's agility, reflexes, and hand-eye coordination. 

### Point down the features

Game points

- Colorful bubbles appear randomly on the screen at regular intervals.
- The player can click on the bubbles to pop them and earn points.
- The player's score is displayed in real-time, showing the number of bubbles popped.
- The highest score achieved is tracked and displayed as the high score.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @DP-NOTHING ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @DP-NOTHING ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
