### ISSUE TITLE
[New game]: Flappy bird

### ISSUE THREAD

**Issue by aysal04** [kunjgit/GameZone#384]
### 🎮 Game Request

Game logic and basic description:

This is an interesting never ending game. There is a bird in it which moves only in forward directions. We can make it fly up and down using arrow keys. There are pipes acting as obstacles in between. If the bird hits the pipe game will be over.

### Point down the features

Game points:

This would be a funny and intersting game as well. Based on the score individuals can compete among themselves

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @aysal04 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by aysal04** [comment]
I am willing to work on it.

**Comment by Lavesh12** [comment]
Hello,
I hope you're doing well. I am interested in contributing to this project as part of GSSoC. I have gone through the project's repository and identified that I would like to tackle. It aligns with my skills and interests, and I believe I can make a meaningful contribution to the project. I am eager to get started and contribute to the project. Could you please assign this task to me? 
Looking forward to hearing from you.
Thank you,
Lavesh Vishwakarma

**Comment by kunjgit** [comment]
Hey @aysal04 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
