### ISSUE TITLE
[New game]: Shape pattern Game

### ISSUE THREAD

**Issue by manishh12** [kunjgit/GameZone#3841]
### 🎮 Game Request

User have to remember the shape and based on that he have to find its pair.

### Point down the features

shape generation
Flipping the hidden states
Score Points

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @manishh12! 
We are already having a similar game request in #3454 👀 
Make sure you come up with a cool unique idea 😀 
 Waiting for your new game idea 💗.
