### ISSUE TITLE
[Enhancement]: AI_CHESS

### ISSUE THREAD

**Issue by VijaySamant4368** [kunjgit/GameZone#3844]
### Do you want to have the enhancement of existing game ? 😀 Describe yourself..

When we checkmate the AI, it alerts the following message:
![image](https://github.com/kunjgit/GameZone/assets/145102345/48224b0b-5b0b-4b3e-92e0-860a733836c9)
even before we actually make the move.

### Describe the solution you'd like

I will make it such that we take the move first and then it displays checkmate alert

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @VijaySamant4368 , You can't have another issue before completing the previous one 😀 
 you already have the following 1 open issues 👀 ! :

#3691

**Comment by kunjgit** [comment]
Hey @VijaySamant4368 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by kunjgit** [comment]
Hey @VijaySamant4368 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)
