### ISSUE TITLE
[New game]: Hover Board game

### ISSUE THREAD

**Issue by Yashgabani845** [kunjgit/GameZone#3848]
### 🎮 Game Request

Game logic and basic description
Hover Board is real life based  game 
 it is gamind experience where random colour will be genrated on hovering board

### Point down the features

Game points
hover the board
colour will be chnaged
get points and have fubn

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Yashgabani845 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
