### ISSUE TITLE
[New game]: Musical Memory Game

### ISSUE THREAD

**Issue by Harshitmishra001** [kunjgit/GameZone#3849]
### 🎮 Game Request

This game challenges players to test their musical memory by matching pairs of identical sounds.

### Point down the features

Sound-Based Matching: Players listen to and remember a series of musical snippets, then match them by clicking on corresponding tiles.
Difficulty Levels: Adjust the difficulty by changing the number of sound pairs, the length of the snippets, or the complexity of the music.
Progress Tracking: Monitor the player's performance with a score system, showcasing their accuracy and speed.
Visual Feedback: Provide visual cues to indicate successful matches and highlight incorrect choices.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Harshitmishra001 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @Harshitmishra001 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
