### ISSUE TITLE
[Enhancement]: Catch_Stars

### ISSUE THREAD

**Issue by NAVJOT-786** [kunjgit/GameZone#3858]
### Do you want to have the enhancement of existing game ? 😀 Describe yourself..

Title: Add Reset Button to Catch The Star Game

Description: Enhance the existing "Catch The Star" game by adding a reset button that allows players to restart the game. The reset button is positioned at the bottom center of the game screen for easy access.

Enter a brief description about the enhancement you need:
This enhancement adds a reset button to the game interface. The reset button, placed at the bottom center of the screen, allows players to restart the game at any point, resetting the time, score, and stars. This feature improves user experience by providing an easy way to replay the game without refreshing the browser.

Thank you for considering this enhancement!

### Describe the solution you'd like

Describe the solution you'd like:
I would like to enhance the "Catch The Star" game by adding a reset button that allows players to restart the game at any point. This reset button will be placed at the bottom center of the game screen for easy accessibility. When clicked, it will reset the time, score, and remove all current stars from the screen, effectively restarting the game without requiring a page refresh.

Steps to solve it:

**Update HTML:**

Add a reset button to the HTML file within the game container.
html

`<button class="btn" id="reset-btn">Reset Game</button>`

**Update CSS:**

Style the reset button to be positioned at the bottom center of the screen.

```
#reset-btn {
  position: absolute;
  bottom: 20px;
  left: 50%;
  transform: translateX(-50%);
}
```

**Update JavaScript:**

Add an event listener for the reset button.
Define a function to handle the reset logic: clear the interval, reset the time and score, hide the message, and remove all existing stars from the game container.

**javascript**

```
const reset_btn = document.getElementById('reset-btn');

reset_btn.addEventListener('click', resetGame);

function resetGame() {
    clearInterval(interval);
    seconds = 0;
    score = 0;
    timeEl.innerHTML = 'Time: 00:00';
    scoreEl.innerHTML = 'Score: 0';
    message.classList.remove('visible');
    screens[0].classList.remove('up');
    const stars = document.querySelectorAll('.star');
    stars.forEach(star => star.remove());
}
```
By following these steps, the reset button will be added to the game, providing players with the ability to restart the game easily, enhancing the overall user experience.

I am contributing from open source GSSoc24

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @NAVJOT-786 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
