### ISSUE TITLE
[Enhancement]: catch stars

### ISSUE THREAD

**Issue by NAVJOT-786** [kunjgit/GameZone#3859]
### Do you want to have the enhancement of existing game ? 😀 Describe yourself..

This enhancement adds a reset button to the game interface. The reset button, placed at the bottom center of the screen, allows players to restart the game at any point, resetting the time, score, and stars. This feature improves user experience by providing an easy way to replay the game without refreshing the browser.

### Describe the solution you'd like

I would like to enhance the "Catch The Star" game by adding a reset button that allows players to restart the game at any point. This reset button will be placed at the bottom center of the game screen for easy accessibility. When clicked, it will reset the time, score, and remove all current stars from the screen, effectively restarting the game without requiring a page refresh.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @NAVJOT-786 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by NAVJOT-786** [comment]
@kunjgit please add gssoc label

**Comment by kunjgit** [comment]
Hey @NAVJOT-786 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
