### ISSUE TITLE
[Documentation Bug]: Fix grammatical errors and typos in README.md

### ISSUE THREAD

**Issue by pineapplepeachypie** [kunjgit/GameZone#3862]
### Describe the bug ✍️

Describe your bug here:
I would like to provide edits to the README.md file to fix some grammatical errors and some typos. 
For example: 

- "together with a construvtive and a positive" -> there is a typo here, "construvtive" should be spelled as "constructive".
- "Raise and issue to add new game or to enhancement for a game (Have a look at few things you have to take care during raising issue )" -> Raise _an_ issue to add _a_ new game or to _enhance an existing_ game. (Have a look at _a_ few things you have to take care _of_ _when raising an_ issue. 

Those two are a couple of the grammatical errors that I would like to fix. The motivation to fix these grammatical errors and typos is to help polish GameZone's documentation. I think this is a great open source project and I would like to make a contribution regardless of how little it may be. 

### Provide step by step information reproduce the bug 📄

Description:
Click the README.md file to read through the documentation. 

### Select program in which you are contributing

Other

### Code of Conduct

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @pineapplepeachypie ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hello @pineapplepeachypie, Time's up!⏰ 
 Sorry for closing your issue! 
 But it's more than a week since we haven't received anything from your side 😢 . 
 Come up with new ideas, create a new issue and make sure you finish it within a week! 🔥 
 All the best! 🚀 
 Happy Hacking! 💗

**Comment by kunjgit** [comment]
Hey @pineapplepeachypie ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
