### ISSUE TITLE
[New game]:  Letter Labyrinth

### ISSUE THREAD

**Issue by Aditi22Bansal** [kunjgit/GameZone#3869]
### 🎮 Game Request

Game logic and basic description
 In this game, players navigate a maze filled with letters and form words by connecting adjacent letters.

### Point down the features

Game points
Navigate through the labyrinth of letters and form as many words as possible within the time limit.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Aditi22Bansal , You can't have another issue before completing the previous one 😀 
 you already have the following 1 open issues 👀 ! :

#3742

**Comment by kunjgit** [comment]
Hey @Aditi22Bansal ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by kunjgit** [comment]
Hey @Aditi22Bansal ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)
