### ISSUE TITLE
[Question]: We Can add Typewriter theme in footer and give margin to icons from top and bottom.

### ISSUE THREAD

**Issue by zalabhavy** [kunjgit/GameZone#3872]
### Describe your question or ask for support.❓

I want to add Typewriter theme in **by kunj** so it will looks good also give margin to icons from top and bottom.
![image](https://github.com/kunjgit/GameZone/assets/126322584/c8bbf278-9d0e-46e1-934d-c08081e8c62f)

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @zalabhavy , You can't have another issue before completing the previous one 😀 
 you already have the following 1 open issues 👀 ! :

#3813

**Comment by kunjgit** [comment]
Hey @zalabhavy ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by kunjgit** [comment]
Hey @zalabhavy ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)
