### ISSUE TITLE
[New game]: Tic-Tac-Toe

### ISSUE THREAD

**Issue by jency1** [kunjgit/GameZone#3873]
### 🎮 Game Request

1) Game Interface:

1. Design a 3x3 grid for the game board.
2. Provide clear visual indicators for player turns (e.g., 'X' and 'O').
3. Include a reset button to start a new game.

2) Game Mechanics:

1. Implement logic for two players to take turns.
2. Detect and handle invalid moves (e.g., selecting an already occupied cell).
3. Determine the game's outcome (win, lose) and display appropriate messages.

3) Player Interaction:

1. Enable players to click on the cells to make their moves.
2. Ensure the game updates in real-time with each move.

4) Code Quality:

1. Write clean, readable, and maintainable code.
2. Include comments and documentation where necessary.

### Point down the features

1. Design a 3x3 grid for the game board.
2. Provide clear visual indicators for player turns (e.g., 'X' and 'O').
3. Include a reset button to start a new game.
4. Detect and handle invalid moves (e.g., selecting an already occupied cell).
5. Determine the game's outcome (win, lose) and display appropriate messages.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @jency1 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @jency1 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
