### ISSUE TITLE
[Documentation Bug]: Spelling mistake in SPIDER MAN GO

### ISSUE THREAD

**Issue by shruti110503** [kunjgit/GameZone#3874]
### Describe the bug ✍️

There is Spelling mistake in Spider Man Go game's readme file and its alignment needs to be corrected.
![Screenshot 2024-05-29 204928](https://github.com/kunjgit/GameZone/assets/118251562/0682e7ff-f547-489f-8449-e26beef38845)

### Provide step by step information reproduce the bug 📄

I will correct the spelling and make the alignment right.

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @shruti110503 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @shruti110503 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
