### ISSUE TITLE
[New game]: NumPuz

### ISSUE THREAD

**Issue by Yashgabani845** [kunjgit/GameZone#3878]
### 🎮 Game Request

Game logic and basic description
n this puzzle game, you have a grid with numbered tiles and one empty space. The objective is to slide the tiles around the grid to arrange them in a specific order, usually from lowest to highest number, with the empty space in a designated position (often at the bottom-right corner).

- 8-Puzzle: A 3x3 grid with 8 numbered tiles (1-8) and one empty space.
- 16-Puzzle: A 4x4 grid with 15 numbered tiles (1-15) and one empty space.

### Point down the features

Game points

1. Starting Points: 1000
2. Moves: 45 (45 points deducted)
3. Time: 7 minutes (35 points deducted)
4. Bonus: Solved under 50 moves (awarded 50 points)

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Yashgabani845 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @Yashgabani845 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
