### ISSUE TITLE
[Enhancement]: Improving the UI and adding Home icon in "Brain Burst Game"

### ISSUE THREAD

**Issue by ShristiiSharma** [kunjgit/GameZone#3880]
### Do you want to have the enhancement of existing game ? 😀 Describe yourself..

Game enhancement

1. I will enhance the UI of the game as enhancing the game's visual appeal is essential for creating a compelling, enjoyable, and professional experience that attracts and retains players.
3. I will add a Home Icon, adding it will improve the game's usability, making it more user-friendly and accessible, which can lead to higher user satisfaction and retention.

### Describe the solution you'd like

Solution steps

1. Visual Appeal: Adding gradients, shadows, and rounded corners to create a modern look.
2. Interactivity: Implementing hover effects and transitions for a more engaging user experience.
3. Readability and Usability: Improving text visibility and providing clear visual feedback.
4. Home Icon: Adding Home Icon at the top of the game, it will help players to navigate to the Home Page easily.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @ShristiiSharma , You can't have another issue before completing the previous one 😀 
 you already have the following 1 open issues 👀 ! :

#3807

**Comment by kunjgit** [comment]
Hey @ShristiiSharma ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by kunjgit** [comment]
Hey @ShristiiSharma ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)
