### ISSUE TITLE
[New game]: Color The Page 

### ISSUE THREAD

**Issue by codewithganeshhh** [kunjgit/GameZone#3884]
### 🎮 Game Request

Game logic and basic description:
This a simple project where user can generate a random color for background, random gradient background and random button background .The heading also changes contrast on the basis of basis of background color. Background color also changes in case button background is button color is light.

### Point down the features

Game points:
User can have RGB value random color and can see how a color would look on background of the page and button. User can also have random gradient background color.

![Screenshot 2024-05-30 124457](https://github.com/kunjgit/GameZone/assets/139307139/c599077c-179a-41ea-ad04-cee68be1fe89)

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @codewithganeshhh ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @codewithganeshhh ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
