### ISSUE TITLE
[New game]: 2D Bouncing Ball Game

### ISSUE THREAD

**Issue by nandita27iitp** [kunjgit/GameZone#3885]
### 🎮 Game Request

Game logic and basic description

The 2D Bouncing Ball Game is a simple yet engaging web-based game developed using HTML, CSS, and JavaScript. It involves a ball that continuously bounces around within the boundaries of the game area, changing direction upon collision with the edges. This game provides a great example of basic game physics and interactive animation on the web.

### Point down the features

- Responsive Design: The game is designed to be responsive, ensuring it works seamlessly across various devices, from desktops to mobile phones.
- Smooth Animation: Utilizing CSS for styling and JavaScript for logic, the game features smooth and fluid ball movements.
- Interactive UI: Simple and intuitive user interface allows players to start, pause, and reset the game effortlessly.

## Technical Details
- HTML: The structure of the game is built using HTML, providing the canvas element where the game animations occur.
- CSS: Styling is applied through CSS to ensure the game has a clean and visually appealing look. CSS is also used for animations that enhance the game's interactivity.
- JavaScript: Core game logic is implemented in JavaScript, which includes ball movement, collision detection, speed adjustments, and game state management.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @nandita27iitp ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hello @nandita27iitp, Time's up!⏰ 
 Sorry for closing your issue! 
 But it's more than a week since we haven't received anything from your side 😢 . 
 Come up with new ideas, create a new issue and make sure you finish it within a week! 🔥 
 All the best! 🚀 
 Happy Hacking! 💗

**Comment by kunjgit** [comment]
Hey @nandita27iitp ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
