### ISSUE TITLE
[Bug]: Increase Heading size from Top in Responsive Mode

### ISSUE THREAD

**Issue by TARUN2K3** [kunjgit/GameZone#3887]
### Give a brief about the bug ✍️

In responsive mode, the heading size from the top is currently too small, which affects the overall readability and visual appeal of the page. I propose increasing the margin to enhance the user experience on smaller screens.

![image](https://github.com/kunjgit/GameZone/assets/127468524/70f13641-14dc-431a-8450-4945941643e8)

### What is the expected behavior? 🤔

The heading should have a larger margin from the top to improve readability and visual structure.

### Provide step by step information reproduce the bug 📄

- Open the application in a web browser.
- Resize the browser window to a smaller width (e.g., less than 768px) to trigger the responsive mode.
- Observe the size on the top of the page and the heading.

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @TARUN2K3 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by TARUN2K3** [comment]
Assign!!

**Comment by kunjgit** [comment]
Hello @TARUN2K3, Time's up!⏰ 
 Sorry for closing your issue! 
 But it's more than a week since we haven't received anything from your side 😢 . 
 Come up with new ideas, create a new issue and make sure you finish it within a week! 🔥 
 All the best! 🚀 
 Happy Hacking! 💗

**Comment by kunjgit** [comment]
Hey @TARUN2K3 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
