### ISSUE TITLE
[Bug]: The font used below "GAMEZONE"

### ISSUE THREAD

**Issue by payalgupta25** [kunjgit/GameZone#3888]
### Give a brief about the bug ✍️

<h2> 
The font below "GAMEZONE" seems so normal for a gaming website 
</h2>

### What is the expected behavior? 🤔

The font should be cool looking not just simple  like this 
![image](https://github.com/kunjgit/GameZone/assets/139633883/98121733-80a0-401e-96ed-aac97e8b3fbb)

### Provide step by step information reproduce the bug 📄

<h3>I would like to change all the font of website giving them a funky readable cool look

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by 143divya** [comment]
Can you please assign this issue to me

**Comment by Aashka19** [comment]
please assign it to me

**Comment by payalgupta25** [comment]
Assign @payalgupta25

**Comment by 143divya** [comment]
Can you please this issue to me under GssoC24?

**Comment by kunjgit** [comment]
Hello @payalgupta25, Time's up!⏰ 
 Sorry for closing your issue! 
 But it's more than a week since we haven't received anything from your side 😢 . 
 Come up with new ideas, create a new issue and make sure you finish it within a week! 🔥 
 All the best! 🚀 
 Happy Hacking! 💗

**Comment by kunjgit** [comment]
Hey @payalgupta25 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
