### ISSUE TITLE
[Enhancement]: Navbar addition

### ISSUE THREAD

**Issue by aggrhythm** [kunjgit/GameZone#3892]
### Do you want to have the enhancement of existing game ? 😀 Describe yourself..

We can add a navbar to the top to make it look more visually appealing.

### Describe the solution you'd like

I would likes to add a navbar with Home, contact us and other buttons.
Therefor i request the project admin @kunjgit  to assign me this issue and label under gssoc

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @aggrhythm ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @aggrhythm ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
