### ISSUE TITLE
[Documentation Bug]: ludo game readme file missing text

### ISSUE THREAD

**Issue by shruti110503** [kunjgit/GameZone#3894]
### Describe the bug ✍️

There's a missing line in functionalaties of LUDO game.
![Screenshot 2024-05-30 134816](https://github.com/kunjgit/GameZone/assets/118251562/c09db66b-4133-425b-8c45-193fa7b7d6ff)

### Provide step by step information reproduce the bug 📄

I will fix it

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @shruti110503 , You can't have another issue before completing the previous one 😀 
 you already have the following 1 open issues 👀 ! :

#3893

**Comment by kunjgit** [comment]
Hey @shruti110503 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by kunjgit** [comment]
Hey @shruti110503 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)
