### ISSUE TITLE
[New game]:  Guess the Song game

### ISSUE THREAD

**Issue by Damini2004** [kunjgit/GameZone#3896]
### 🎮 Game Request

Game logic and basic description
The game randomly selects a song and presents a snippet of its lyrics or a short audio clip. Players guess the song title and artist, earning points for accuracy. Hints are available at a cost to the score. The game includes multiple difficulty levels and timed challenges. In multiplayer mode, players compete in real-time or take turns. A leaderboard tracks scores and achievements.

### Point down the features

Game points
The game features an extensive song database, various categories, and playlists. Players can choose between audio and lyrics modes, use hints, and enjoy multiplayer and social features. Achievements and rewards encourage progress, while user-created content and customizable profiles enhance personalization. The game is available on multiple platforms for broad accessibility.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Damini2004 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
