### ISSUE TITLE
[Bug]: Uncaught SyntaxError

### ISSUE THREAD

**Issue by patelkiran185** [kunjgit/GameZone#3899]
### Give a brief about the bug ✍️

Description
While inspecting i found this error,
It indicates that the code is trying to access an element with the id "progress" but that element doesn't exist in the DOM (Document Object Model) at the time the script tries to access it

### What is the expected behavior? 🤔

Description
No error

### Provide step by step information reproduce the bug 📄

Description
Ensure the element exists or move the code to check for existence

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

Please assign me this

**Comment by kunjgit** [comment]
Hey @patelkiran185 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @patelkiran185 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
