### ISSUE TITLE
[New game]: 2048 game

### ISSUE THREAD

**Issue by AbhishekPSingh07** [kunjgit/GameZone#39]
### 🎮 Game Request

2048 is a popular puzzle game played on a 4x4 grid. The objective of the game is to slide numbered tiles on the grid and combine them to reach the tile with the number 2048.

At the beginning of the game, there are two randomly placed tiles, either with the number 2 or 4. You can use the arrow keys (up, down, left, and right) to move all the tiles on the grid in that direction. When you make a move, all the tiles slide as far as possible in the chosen direction, either merging with another tile of the same number or stopping at the edge of the grid.

Whenever two tiles with the same number collide during a move, they merge into one tile with the sum of their values. For example, if you slide two tiles with the number 2 together, they combine to form a single tile with the number 4. The merged tiles also free up a space on the grid for new tiles to appear.

### Point down the features

The game continues until you either reach the tile with the number 2048 or are unable to make any more moves. Your score is based on the value of the tiles you combine during the game. The higher the value of the merged tiles, the higher your score will be.

2048 is known for its simple rules but challenging gameplay, requiring strategic thinking and planning to reach the elusive 2048 tile. It has gained immense popularity on various platforms and has inspired numerous versions and adaptations across different devices and operating systems.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey  @AbhishekPSingh07  ! Thank you for raising an issue 💗 You have been assigned this issue you can start working on the issue 🎮

**Comment by kunjgit** [comment]
Hey @AbhishekPSingh07 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
