### ISSUE TITLE
[New game]: Crossy Road 

### ISSUE THREAD

**Issue by Damini2004** [kunjgit/GameZone#3902]
### 🎮 Game Request

Game logic and basic description
Objective: The primary goal in Crossy Road is to navigate a character across a series of roads, rivers, train tracks, and other obstacles without getting hit or falling into the water.
Controls: Players control their character by tapping to move forward and swiping to move sideways, backward, or jump.
Endless Runner: The game is endless, meaning the player continues as long as they avoid obstacles and stay alive. The challenge increases as the game progresses.
Scoring: Players earn points for each step forward. Additional points can be collected by picking up coins scattered across the playing field.
Obstacles: The game features various dynamic obstacles such as moving cars, trucks, trains, and logs. Timing and precision are crucial to avoid these hazards.
Character Mechanics: If the character is idle for too long, an eagle swoops down to take them away, adding an element of urgency.

### Point down the features

Game points
Diverse Characters: A wide range of characters can be unlocked, each with unique appearances and sometimes special abilities. Characters can be unlocked using in-game currency or by completing specific challenges.
Varied Environments: Different environments and themes change the look and feel of the game. For example, changing from urban roads to rivers or snowy landscapes.
Multiplayer Mode: Allows players to compete with friends or other players in real-time.
Daily Rewards: Players can collect daily rewards and bonuses, encouraging regular gameplay.
Achievements and Leaderboards: In-game achievements provide goals and rewards, while leaderboards foster competition among players globally.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Damini2004 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)
