### ISSUE TITLE
adding bubble bash game

### ISSUE THREAD

**Issue by ChaitanyaLonarkar** [kunjgit/GameZone#3904]
### 🎮 Game Request

It a simple bubble blast game made by using HTML CSS and Js

I want to add this is your website

assign this issue to me under gssoc24.

![image](https://github.com/kunjgit/GameZone/assets/110454138/2505631a-5e9b-4d43-b027-c18b6a0a50cd)

### Point down the features

Game points
It is simple to play and understand.
Anyone can play this.
Easy UI

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @ChaitanyaLonarkar ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @ChaitanyaLonarkar ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by ChaitanyaLonarkar** [comment]
Why this is closed??
