### ISSUE TITLE
[New game]: Stone paper Scissor Game 

### ISSUE THREAD

**Issue by Vaishnavi1047** [kunjgit/GameZone#3905]
### 🎮 Game Request

Game logic and basic description
simple js,html,css web app for stone paper scissor game based on simple logics.

### Point down the features

Game points
![Screenshot 2024-01-04 173544](https://github.com/kunjgit/GameZone/assets/149894552/73a64868-3da5-46b6-ae48-915779dad30c)

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by Vaishnavi1047** [comment]
assign

**Comment by Vaishnavi1047** [comment]
please apply the gssoc tag along with that

**Comment by Vaishnavi1047** [comment]
@kunjgit please apply the gssoc tag along with that

**Comment by Akash-nema** [comment]
@kunjgit  please assign me I add some attractive color combinations.

**Comment by Vaishnavi1047** [comment]
Could u pls add the gssoc label as i forgot to mention my contributing
under gssoc one . The issue is #3905

**Comment by Vaishnavi1047** [comment]
@kunjgit assign me this issue

**Comment by Vaishnavi1047** [comment]
and pls add gssoc label too

**Comment by kunjgit** [comment]
Hey @Vaishnavi1047 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
