### ISSUE TITLE
[New game]: Tree Planting 

### ISSUE THREAD

**Issue by Ashok-Kumar-dharanikota** [kunjgit/GameZone#391]
### 🎮 Game Request

**Game logic and basic description:**

I would like to create a game that not only for fun but also talks about the importance of trees. The concept of game is, a seed will be sow into land. By providing regularly water and sun light at some particular intervals of time. The plant start growing as big tree. But if we didn't provide this to plant. It will show how plant will die and how it effect the nature and human life by adding background animations and effects.

### Point down the features

**Game points**

- helps to learn virtually How to sow plants.
- Fun and learning concept for Little children.
- helps to teach children importance of trees.
- etc 

It would be good if multiple people work on this concept. 

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Ashok-Kumar-dharanikota ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hello @Ashok-Kumar-dharanikota, Time's Uppp!⏰ 
 Sorry for closing your issue! 
 But it's more than a week since we haven't received anything from your side 😢 . 
 Come up with new ideas, create a new issue and make sure you finish it within a week! 🔥 
 All the best! 🚀 
 Happy Hacking! 💗

**Comment by kunjgit** [comment]
Hey @Ashok-Kumar-dharanikota ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by Ashok-Kumar-dharanikota** [comment]
No problem, @kunjgit . I am upskillimg my css skill to Match the desired output. Next time i will try to finish it within the time period. 

Thank you for your support and encouragement. ☺️🤝
