### ISSUE TITLE
[Bug]: The link to Love Calculator is broken, or it doesn't exist

### ISSUE THREAD

**Issue by sandy-queen** [kunjgit/GameZone#3910]
### Give a brief about the bug ✍️

The "Love Calculator" game is not working when you click on it. 

### What is the expected behavior? 🤔

This is what happens when you click on the game: 

![bugingamezone](https://github.com/kunjgit/GameZone/assets/147652780/af0292ab-5e99-4a3f-bd69-02f211a75621)

### Provide step by step information reproduce the bug 📄

I will fix this issue by either removing the game from the list of available list of games, or by fixing the link by linking it to the correct resource. 

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @sandy-queen ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by sandy-queen** [comment]
@kunjgit please also add the relevant tags.

**Comment by kunjgit** [comment]
Hello @sandy-queen, Time's up!⏰ 
 Sorry for closing your issue! 
 But it's more than a week since we haven't received anything from your side 😢 . 
 Come up with new ideas, create a new issue and make sure you finish it within a week! 🔥 
 All the best! 🚀 
 Happy Hacking! 💗

**Comment by kunjgit** [comment]
Hey @sandy-queen ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
