### ISSUE TITLE
[New game]: " ShroomKnight " game will be added

### ISSUE THREAD

**Issue by shuvadeepmondal** [kunjgit/GameZone#3913]
### 🎮 Game Request

"ShroomKnight" is an engaging web game where players control a fairy hero tasked with defending against invading spiders. The fairy combats the spiders by spawning mushrooms, which serve as automated defense units. These mushrooms shoot bullets at regular intervals, aiming to eliminate the approaching spiders before they reach the bottom of the screen.

- **Move the Fairy**: Use the arrow keys (Left, Right, Up, Down) to navigate the fairy across the canvas. Position the fairy strategically to avoid spiders and place mushrooms effectively.
- **Spawn Mushrooms**: Press the spacebar to spawn mushrooms at the fairy's current location. Each mushroom will automatically fire bullets upwards to destroy any spiders in their path.
- **Avoid Spider**s: The goal is to prevent spiders from reaching the bottom of the screen. If a spider gets past the defenses, it continues, but players should aim to stop as many as possible.

### Point down the features

1. Arrow Keys & ' W, A, S, D ' : Move the fairy in the respective direction.
2. Spacebar: Spawn a mushroom at the fairy's current position. The mushroom will fight against the spider by using their ability

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @shuvadeepmondal ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by shuvadeepmondal** [comment]
@kunjgit Sir Can i make another PR?

**Comment by kunjgit** [comment]
Hey @shuvadeepmondal ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
