### ISSUE TITLE
[New game]: Find_the_ball

### ISSUE THREAD

**Issue by manishh12** [kunjgit/GameZone#3914]
### 🎮 Game Request

The Find the Ball Game is an entertaining web-based game where players must guess which bowl is hiding the ball. The game challenges and improves memory and guessing skills while offering an enjoyable user experience with a visually appealing interface.

### Point down the features

Game points- Displays a row of bowls, one of which hides a ball.
- Reveals the ball when a bowl is clicked.
- Allows players to guess which bowl hides the ball.
- Tracks and displays the player's score.
- Provides a reset button to restart the game.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @manishh12 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @manishh12 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
