### ISSUE TITLE
[New game]: Letter Labyrinth Game

### ISSUE THREAD

**Issue by Aditi22Bansal** [kunjgit/GameZone#3918]
### 🎮 Game Request

Game logic and basic description
The Letter Labyrinth game is a fun and engaging word puzzle that challenges players to navigate through a maze of letters to find hidden words. 

### Point down the features

Game points
Count Board
Multidirectional

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Aditi22Bansal ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @Aditi22Bansal! 
We are already having a similar game request in #3383 👀 
Make sure you come up with a cool unique idea 😀 
 Waiting for your new game idea 💗.
