### ISSUE TITLE
[New game]: Simon game

### ISSUE THREAD

**Issue by Aditi22Bansal** [kunjgit/GameZone#3919]
### 🎮 Game Request

Game logic and basic description
A memory game where players must repeat a sequence of lights and sounds. Each round, the sequence gets longer.

### Point down the features

Game points
Colored buttons that light up in a sequence.
JavaScript to handle the sequence logic and user input.
Feedback for correct/incorrect sequences.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Aditi22Bansal ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by Yashgabani845** [comment]
i have implemented this code futher i want to add this code to gamezon 
you please work with other one 
/assign
