### ISSUE TITLE
[Enhancement]: Pagination for Contributor section

### ISSUE THREAD

**Issue by ShreeluSantosh** [kunjgit/GameZone#3920]
### Do you want to have the enhancement of existing game ? 😀 Describe yourself..

The contributors section is too long and can be overwhelming.

### Describe the solution you'd like

- Add pagination at the bottom of the contributor section
- Use 20-30 contributors per page
- Add 'Total contributors so far! : (number)' subheading to indicate contributor count, below 'Our Valuable Contributors' heading

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @ShreeluSantosh ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by ShreeluSantosh** [comment]
Pull request: #3964

**Comment by kunjgit** [comment]
Hey @ShreeluSantosh ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
