### ISSUE TITLE
[Enhancement]:  Add  color  combinations

### ISSUE THREAD

**Issue by Akash-nema** [kunjgit/GameZone#3922]
### Do you want to have the enhancement of existing game ? 😀 Describe yourself..

Game enhancement (add some attractive colors in different -  different games)

### Describe the solution you'd like

Solution steps   
![Screenshot 2024-05-30 212504](https://github.com/kunjgit/GameZone/assets/143901772/5477fe54-d580-4cae-814b-73994f176aee)
add colors on hands like( Red , Blue, Green)
add a green color to the play button

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Akash-nema ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by Akash-nema** [comment]
Thank you, sir (Can you guide me in the GSSOC'24 journey.)

**Comment by Akash-nema** [comment]
Could u pls add the gssoc label as i forgot to mention my contributing
under gssoc one . The issue is [#3922](https://github.com/kunjgit/GameZone/issues/3922)

**Comment by kunjgit** [comment]
Hello @Akash-nema, Time's up!⏰ 
 Sorry for closing your issue! 
 But it's more than a week since we haven't received anything from your side 😢 . 
 Come up with new ideas, create a new issue and make sure you finish it within a week! 🔥 
 All the best! 🚀 
 Happy Hacking! 💗

**Comment by kunjgit** [comment]
Hey @Akash-nema ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
