### ISSUE TITLE
[New game]: Egg Catcher

### ISSUE THREAD

**Issue by AtharvaShinde253** [kunjgit/GameZone#3928]
### 🎮 Game Request

Game logic and basic description- The Egg Catcher game is a simple, interactive browser-based game where players control a basket to catch falling eggs. The basket is controlled using the mouse, and the goal is to catch as many eggs as possible without missing them. The game ends when a certain number of eggs are missed. This project is implemented using HTML for the structure, CSS for styling, and JavaScript for interactivity and game logic.

### Point down the features

Game points
1.You have to catch as many eggs as possible.
2.Use your mouse movement to control the basket.
3.You have 5 lives at the start.
4.You get 1 point per correct catch.
5.You can restart the game if you lose and try again

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @AtharvaShinde253 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hello @AtharvaShinde253, Time's up!⏰ 
 Sorry for closing your issue! 
 But it's more than a week since we haven't received anything from your side 😢 . 
 Come up with new ideas, create a new issue and make sure you finish it within a week! 🔥 
 All the best! 🚀 
 Happy Hacking! 💗

**Comment by kunjgit** [comment]
Hey @AtharvaShinde253 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
