### ISSUE TITLE
[New game]: Tic Tac Toe Game

### ISSUE THREAD

**Issue by Vaishnavi1047** [kunjgit/GameZone#3930]
### 🎮 Game Request

Game logic and basic description
simple tic tac toe game build by using html,css,javascript 

### Point down the features

Sample display
![Screenshot 2024-01-04 173646](https://github.com/kunjgit/GameZone/assets/149894552/b5ef3fe7-b4e7-4c4a-9618-561516cebe2b)

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Vaishnavi1047 , You can't have another issue before completing the previous one 😀 
 you already have the following 1 open issues 👀 ! :

#3905

**Comment by kunjgit** [comment]
Hey @Vaishnavi1047 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by kunjgit** [comment]
Hey @Vaishnavi1047 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)
