### ISSUE TITLE
[New game]: Guess the Friend's Name

### ISSUE THREAD

**Issue by TiwariRahul16** [kunjgit/GameZone#3931]
### 🎮 Game Request

Gameplay Overview: In “Guess the Friend's Name” players embark on a journey of memory and luck. player enters the names of four close friends into the game. The game then generates a random name from the list, and the player must use their intuition and knowledge about their friends to guess which name has been chosen.

![guess the friend name](https://github.com/kunjgit/GameZone/assets/168175850/05e65b13-52e8-4381-aa6b-d73ff5cf474a)

### Point down the features

How to Play:

Enter Names: Start by typing in the names of four friends you know well.

Make Your Guess:  Your task is to select the name you believe the game randomly chose.

Reveal & Score: After making your selection, 
. If your guess was right, you score points; if not, better luck next time!

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @TiwariRahul16 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @TiwariRahul16 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
