### ISSUE TITLE
[New game]: Treasure Hunt

### ISSUE THREAD

**Issue by Antiquely3059** [kunjgit/GameZone#3934]
## Game logic and basic description
Treasure Hunt is an exciting game where players navigate through a map to find hidden treasures. Using clues provided within the game, players must overcome obstacles and challenges across multiple levels. The objective is to find the treasures.

## Game points
Single Player: The game is designed for a single player who navigates through the map.
Collect Treasures: The player gains points by collecting hidden treasures.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Antiquely3059 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @Antiquely3059 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
