### ISSUE TITLE
[New game]: ClickTheButton

### ISSUE THREAD

**Issue by shruti110503** [kunjgit/GameZone#3941]
### 🎮 Game Request

Game logic and basic description - ClickTheButton is a simple yet addictive game where the player simply has to click on a button using the mouse pointer in a certain time limit. At the end it will display the final score ie the number of times you have managed to click.
The game is build using HTML, CSS for styling and JavaScript for logic.
![Screenshot 2024-05-31 003646](https://github.com/kunjgit/GameZone/assets/118251562/d5345283-fa3f-45ef-92a3-909a8c606fbc)

### Point down the features

Game points-
-Click the button as many time you can using mouse
-Time limit based

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @shruti110503 , You can't have another issue before completing the previous one 😀 
 you already have the following 1 open issues 👀 ! :

#3893

**Comment by kunjgit** [comment]
Hey @shruti110503 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by kunjgit** [comment]
Hey @shruti110503 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by shruti110503** [comment]
i have already submitted a pull req for  #3893

**Comment by shruti110503** [comment]
@kunjgit can I add the game or not?
