### ISSUE TITLE
[New game]: guess the movie name 

### ISSUE THREAD

**Issue by Zedoman** [kunjgit/GameZone#3942]
### 🎮 Game Request

Game logic and basic description

#### Game Logic

1. **Setup**:
   - **Movie Database**: Create a database of movies, including titles, release years, genres, and clues (e.g., famous quotes, plot descriptions, character names, etc.).
   - **User Interface**: Design a user-friendly interface with input fields, buttons, and display areas for clues and guesses.

2. **Game Start**:
   - **Random Selection**: Randomly select a movie from the database to be the target movie for the current game round.
   - **Clue Presentation**: Display an initial clue to the player. This could be a famous quote, a brief plot description, or a character name from the movie.

3. **Gameplay**:
   - **Player Input**: Allow the player to enter their guess for the movie title.
   - **Hint System**: If the player struggles, provide additional hints at intervals. Hints could be progressively easier to help the player narrow down their guesses (e.g., additional quotes, genre, release year).
   - **Guess Validation**: Compare the player's guess to the correct movie title. Ensure to handle common variations and misspellings.

4. **Scoring and Feedback**:
   - **Correct Guess**: If the player guesses the movie correctly, display a congratulatory message and award points based on the number of hints used and the time taken to guess.
   - **Incorrect Guess**: If the guess is incorrect, provide feedback and allow the player to try again. Optionally, offer another hint after a certain number of incorrect guesses.

5. **Game Over**:
   - **End Round**: After a correct guess or a set number of failed attempts, reveal the movie title and provide a brief description or trivia about the movie.
   - **Restart Option**: Offer the player the option to start a new round with a different movie.

6. **Leaderboard and Achievements**:
   - **Track Scores**: Maintain a leaderboard to display the top scores and encourage competition.
   - **Achievements**: Implement achievements for milestones such as guessing multiple movies correctly, guessing with minimal hints, or achieving a high score.

#### Basic Description

**"Guess the Movie Name"** is an engaging and interactive game where players test their movie knowledge by guessing the titles of films based on provided clues. Each round, players receive a hint related to a randomly selected movie, such as a famous quote, a character name, or a plot description. Players enter their guesses and receive immediate feedback. If a guess is incorrect, additional hints can be requested to aid in identifying the movie. Points are awarded based on the accuracy and speed of the guess, with fewer hints resulting in higher scores. The game tracks high scores on a leaderboard and offers achievements for various milestones, creating a fun and competitive environment for movie enthusiasts.

### Point down the features

Game points

Extensive Movie Database:

A comprehensive database of movies including titles, release years, genres, and various clues.
Random Movie Selection:

Randomly selects a movie from the database for each game round to ensure variety and replayability.
Clue Presentation:

Initial clue provided at the start of each round (e.g., famous quote, brief plot description, character name).
Additional hints available on request, becoming progressively easier.
User-Friendly Interface:

Intuitive design with clear input fields for guesses, buttons for requesting hints, and display areas for clues and feedback.
Guess Validation:

Real-time validation of player guesses against the correct movie title.
Handles common variations and misspellings to enhance user experience.
Scoring System:

Points awarded based on the number of hints used and the time taken to guess correctly.
Bonuses for guessing with fewer hints and within shorter time frames.
Feedback Mechanism:

Instant feedback on guesses, indicating whether they are correct or incorrect.
Additional clues provided after a set number of incorrect guesses.
Game Over Screen:

Reveals the correct movie title if the player fails to guess correctly after a set number of attempts.
Provides a brief description or trivia about the movie to enhance learning and enjoyment.
Restart Option:

Option to start a new game round with a different movie immediately after completing the current round.
Leaderboard:

Tracks and displays top scores to foster a competitive environment.
Allows players to see how they rank against others

### Select program in which you are contributing

GSSoC'24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Zedoman ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @Zedoman ! , This issue is already assigned to @dnyandeepchute. 💗 
 You can work on other issues 🚀 
 If there is anything wrong you can contact us on [Discord🕹️](https://discord.gg/fgwk4XZfxG)👀

**Comment by Zedoman** [comment]
but i have raised this issue sir

**Comment by Zedoman** [comment]
You can check up

**Comment by kunjgit** [comment]
Hello @Zedoman, Time's up!⏰ 
 Sorry for closing your issue! 
 But it's more than a week since we haven't received anything from your side 😢 . 
 Come up with new ideas, create a new issue and make sure you finish it within a week! 🔥 
 All the best! 🚀 
 Happy Hacking! 💗
