### ISSUE TITLE
[New game]: Word Scramble 

### ISSUE THREAD

**Issue by Bhumika1312** [kunjgit/GameZone#3949]
### 🎮 Game Request

Game logic and basic description
In this game, letters are shuffled randomly, and you have to find the correct word using those letters within 30 seconds. For easier gameplay, hints are also provided.

### Point down the features

Game points
Single-player: The game is designed for a single-player
Refresh Word: This game provides a chance to refresh the word if not able to guess the correct word

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Bhumika1312 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @Bhumika1312 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
