### ISSUE TITLE
[New game]: Screen Pet Game

### ISSUE THREAD

**Issue by nisargaa20** [kunjgit/GameZone#3953]
### 🎮 Game Request

Game logic and basic description

Screen Pet game is an event-based program, which means the functions it performs and the order in which it performs all functions is dependent on user input. In such programs, user input can take any form, such as keypresses and mouse clicks.

### Point down the features

Game points

Happy Face: When you will click on it with the mouse the screen pet will blush and it will look happy.

Cheeky Face: If you double-click it, then it will show its tongue to you.

Sad Face: If you ignore it then it will become sad and the point where you click then it will become happy again.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @nisargaa20 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by nisargaa20** [comment]
@kunjgit I have raised an PR kindly check it out

**Comment by kunjgit** [comment]
Hey @nisargaa20 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
