### ISSUE TITLE
[New game]:Memory Gane

### ISSUE THREAD

**Issue by aursh24** [kunjgit/GameZone#3960]
### 🎮 Game Request

Game logic and basic description
A Basic 4x2 Memory Game. Which depicts your score of your memory retention and concentration power. 
The goal is to find all matching pairs of cards by flipping them over two at a time. 

### Point down the features

Game points:
I have kept the game as simple and light as possible, so that anyone can get it easily.
It contains a Score Board which counts +1 if you picked up the write combinations. And counts -1 for every wrong combinations picked.
It shows a result at the end of the game for the intended pun.
You also get a reset button. Don't worry my game wont give you a similar card at the same place <3 

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @aursh24 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hello @aursh24, Time's up!⏰ 
 Sorry for closing your issue! 
 But it's more than a week since we haven't received anything from your side 😢 . 
 Come up with new ideas, create a new issue and make sure you finish it within a week! 🔥 
 All the best! 🚀 
 Happy Hacking! 💗

**Comment by kunjgit** [comment]
Hey @aursh24 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
