### ISSUE TITLE
[New game]: Rapid Click Frenzy

### ISSUE THREAD

**Issue by NAVJOT-786** [kunjgit/GameZone#3962]
### 🎮 Game Request

**Game Title: Rapid Click Frenzy**
Game Logic
In Rapid Click Frenzy, the player’s objective is to click a button as many times as possible within a given time limit. The game starts when the player clicks the "Start Game" button, which initializes the score to zero and sets the timer to the predefined duration (e.g., 10 seconds). As the game begins, the player clicks the "Click Me!" button repeatedly to increase their score. A timer counts down from the starting time, and once it reaches zero, the game ends. The player’s final score is then displayed, showing how many times they managed to click the button within the time limit.

### Point down the features

Features
Simple and Intuitive Gameplay

Easy-to-understand mechanics: click the button as fast as you can within the time limit.
Time-Limited Challenge

Players have a fixed amount of time (e.g., 10 seconds) to achieve the highest score possible by rapidly clicking a button.
Score Tracking

Real-time score display updates with each button click, showing the player’s current score.
Timer Display

A countdown timer visible on the screen, keeping the player aware of the remaining time.
Start and Restart Game

"Start Game" button to begin the game and reset all parameters (score and timer) for a fresh start.
Ability to restart the game after it ends by clicking the "Start Game" button again.
Game Over Screen

Upon the timer reaching zero, the game ends and a "Game Over" screen appears, displaying the player’s final score.
Responsive Design

The game adapts to different screen sizes and devices, ensuring a consistent experience on both desktop and mobile devices.

I am contributing Upne Gssoc24

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @NAVJOT-786 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by NAVJOT-786** [comment]
@kunjgit please add gssoc label

**Comment by kunjgit** [comment]
Hey @NAVJOT-786 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
