### ISSUE TITLE
[New game]: Forest Guardian 

### ISSUE THREAD

**Issue by Aditi22Bansal** [kunjgit/GameZone#3977]
### 🎮 Game Request

Game logic and basic description
 In this game, the player controls a guardian spirit that protects a magical forest. The player needs to navigate through the forest, collecting magical orbs and avoiding harmful creatures. The game will have multiple levels with increasing difficulty.

### Point down the features

Game points
Guardian Movement: Players control a guardian spirit using the left and right arrow keys to navigate through the forest.
Orb Collection: Players must collect magical orbs that appear at random positions to score points.
Avoiding Creatures: Harmful creatures appear and move through the forest, which the player must avoid to stay alive.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Aditi22Bansal ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @Aditi22Bansal ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
