### ISSUE TITLE
[New game]: Bubble Bash

### ISSUE THREAD

**Issue by ChaitanyaLonarkar** [kunjgit/GameZone#3979]
### 🎮 Game Request

Game logic and basic description
Enter the thrilling world of Bubble Bash, a captivating bubble-hit game powered by JavaScript. Test your skills as you aim to pop the exact number of bubbles within 60 seconds to boost your score. Immerse yourself in the excitement as you strive for the highest score in this addictive browser-based game.

### Point down the features

Game points
Objective: Pop as many bubbles as you can within 60 seconds to achieve the highest score possible.
Scoring: Each bubble popped earns +10 points, with bonus points for quick succession combos.
Responsive Controls: Easy-to-use mouse or touchpad controls make the game accessible for all ages.

![Screenshot 2024-05-30 184821](https://github.com/kunjgit/GameZone/assets/110454138/c5f0b3f0-0ffe-4085-9348-e2f1a05f977b)

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @ChaitanyaLonarkar ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hello @ChaitanyaLonarkar, Time's up!⏰ 
 Sorry for closing your issue! 
 But it's more than a week since we haven't received anything from your side 😢 . 
 Come up with new ideas, create a new issue and make sure you finish it within a week! 🔥 
 All the best! 🚀 
 Happy Hacking! 💗

**Comment by kunjgit** [comment]
Hey @ChaitanyaLonarkar ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
