### ISSUE TITLE
[New game]: Black_jackk

### ISSUE THREAD

**Issue by codewithishu** [kunjgit/GameZone#3980]
### 🎮 Game Request

Game logic and basic description

Blackjack is a popular casino card game with simple rules and strategic depth. Here’s an overview of the game logic and how it’s typically played:

Objective
The goal of blackjack is to beat the dealer by having a hand value closest to 21 without exceeding it.

Card Values
Number cards (2-10): Face value.
Face cards (J, Q, K): 10 points each.
Aces: Can be either 1 point or 11 points, depending on which value is more favorable for the hand.

Game Setup

Deck: Blackjack is usually played with one to eight decks of 52 cards.

Players: One or more players compete against the dealer.

Initial Deal: Each player and the dealer are dealt two cards. Players' cards are typically dealt face up, while the dealer has one card 
face up (the "upcard") and one card face down (the "hole card").

### Point down the features

Game points

Card Values

Number Cards (2-10): These cards are worth their face value.

Example: A 5 is worth 5 points.

Face Cards (J, Q, K): These cards are each worth 10 points.

Example: A Queen is worth 10 points.

Aces (A): Aces can be worth either 1 point or 11 points, depending on which value benefits the hand most without causing the hand to bust (exceed 21 points).

Example: An Ace can be worth 11 points if it doesn’t cause the hand to exceed 21; otherwise, it’s worth 1 point.

Example Hands and Their Point Values

Hand: 5♣, 7♦

Total Points: 5 + 7 = 12

Hand: K♠, 9♥

Total Points: 10 (for the King) + 9 = 19

Hand: A♠, 8♦

Total Points: 11 (for the Ace) + 8 = 19

Hand: A♣, 7♠, 3♦

Total Points: Ace can be 11 or 1. If 11, total is 21 (11 + 7 + 3). If 1, total is 11 (1 + 7 + 3), but 21 is the preferred value in this case.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @codewithishu , You can't have another issue before completing the previous one 😀 
 you already have the following 1 open issues 👀 ! :

#3447

**Comment by kunjgit** [comment]
Hey @codewithishu ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by kunjgit** [comment]
Hey @codewithishu ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)
