### ISSUE TITLE
[New game]: Toast Notification

### ISSUE THREAD

**Issue by Vipullakum007** [kunjgit/GameZone#3983]
### 🎮 Game Request

Game logic and basic description : The toast notification game is a simple web-based game where clicking a button generates toast notifications with random messages and types. These notifications appear on the screen and disappear after a short duration.

### Point down the features

Game points : 
1. **Randomized Content**: Generates notifications with random messages and types (info, success, error) for variety.
2. **Auto-Removal**: Notifications disappear after 3 seconds, ensuring a clean UI.
3. **Dynamic Creation**: Clicking the button creates a new notification, enhancing interactivity.
4. **Reusable Functions**: Separate functions handle random message/type generation, making the code modular and easy to extend.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Vipullakum007 , You can't have another issue before completing the previous one 😀 
 you already have the following 1 open issues 👀 ! :

#3582

**Comment by kunjgit** [comment]
Hey @Vipullakum007 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by kunjgit** [comment]
Hey @Vipullakum007 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)
