### ISSUE TITLE
[Enhancement]: Add Typewriter theme in footer and add margin top , bottom in social icons

### ISSUE THREAD

**Issue by zalabhavy** [kunjgit/GameZone#3988]
### Do you want to have the enhancement of existing game ? 😀 Describe yourself..

I want to add Typewriter theme in "by Kunj" that looks good and give margin top and margin bottom to social icons for better view.
![image](https://github.com/kunjgit/GameZone/assets/126322584/ca151c36-3f7a-459f-919b-dcc19a7f6b2d)

### Describe the solution you'd like

I will use javascript for typewriter theme and for margin i will use css to fix.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @zalabhavy , You can't have another issue before completing the previous one 😀 
 you already have the following 1 open issues 👀 ! :

#3877

**Comment by kunjgit** [comment]
Hey @zalabhavy ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by kunjgit** [comment]
Hey @zalabhavy ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)
