### ISSUE TITLE
[New game]: Flip Coin

### ISSUE THREAD

**Issue by CodeXsubham** [kunjgit/GameZone#3991]
### 🎮 Game Request

**Game logic and basic description**
The Flip Coin Game is a simple web-based game where the user can "flip" a virtual coin by clicking a button. The game randomly determines the result of the coin flip, displaying either "Heads" or "Tails".
- The game interface consists of a button labeled "Flip Coin"
- When the user clicks the button, a JavaScript function is triggered.
- The result ("Heads" or "Tails") is displayed on the screen.

### Point down the features

- Interactive Interface
- Random Result Generation
- Immediate Feedback
- Simple and Clean Design

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @CodeXsubham ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @CodeXsubham ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by CodeXsubham** [comment]
@kunjgit I need help regarding pushing the code , when i type git push origin <branch name> an error shows up (img below) , login to github message shows up , even after connecting github , this error still continues and again after pushing the same command same error and login page shows after 
![Screenshot 2024-06-01 121754](https://github.com/kunjgit/GameZone/assets/119094596/f81a42c7-d8c4-47bd-96c7-38f70f65c300)
