### ISSUE TITLE
[New game]:  Rubix cube

### ISSUE THREAD

**Issue by Aditi16-ctrl** [kunjgit/GameZone#3997]
### 🎮 Game Request

Game logic and basic description: Rubix 3x3 cube puzzle solve

### Point down the features

Game points: No. of solves and time requires to solve

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Aditi16-ctrl ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by Aditi16-ctrl** [comment]
Assign me the issue

**Comment by Aditi16-ctrl** [comment]
assign

**Comment by why-Radhika** [comment]
Hey @kunjgit , I would like to work on this issue. I noticed it was assigned for over a month but no PR is merged yet. So if it matches the guidelines please assign the issue to me. I would like to work on it.

**Comment by kunjgit** [comment]
Hello @Aditi16-ctrl, Time's up!⏰ 
 Sorry for closing your issue! 
 But it's more than a week since we haven't received anything from your side 😢 . 
 Come up with new ideas, create a new issue and make sure you finish it within a week! 🔥 
 All the best! 🚀 
 Happy Hacking! 💗
