### ISSUE TITLE
[New game]: 

### ISSUE THREAD

**Issue by abhishekdumaniya** [kunjgit/GameZone#3998]
### 🎮 Game Request

Elemental Match is a puzzle game where players match elements (Fire, Water, Earth, Air) on a grid. The objective is to clear as many elements as possible within a time limit by matching three or more of the same type in a row or column.

### Point down the features

Elemental Match features an 8x8 grid-based gameplay where players match elemental icons (Fire, Water, Earth, Air) to clear them and score points. The game includes dynamic element drops, score tracking, and a restart option. Players can earn additional combo points for consecutive matches. The interactive UI, simple click controls, and responsive design ensure a smooth user experience. Future enhancements could introduce power-ups, special elements with unique effects, multiplayer modes, and an achievement system to further engage players.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by abhishekdumaniya** [comment]
@kunjgit please assign me this issue

**Comment by kunjgit** [comment]
Hey @abhishekdumaniya ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by kunjgit** [comment]
Hey @abhishekdumaniya ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)
