### ISSUE TITLE
[Bug]: Icons were missing and media queries were missing

### ISSUE THREAD

**Issue by iriteshmishra** [kunjgit/GameZone#4]
### Give a brief about the bug ✍️

Icons were missing and media queries between 480px to 563px of simon game were not present in the GameZone.

### What is the expected behavior? 🤔

Icons were missing and media queries between 480px to 563px of simon game were not present. The icons should have be present at the tab and media queries were not proper between  480px to 563px 

### Provide step by step information reproduce the bug 📄

I have added icons which were missing in the GameZone and also added media query between 480px to 563px in simon game.

![Screenshot 2023-05-19 223351](https://github.com/kunjgit/GameZone/assets/96378085/ef201577-97f2-44f2-bcae-75c8fe7f16ce)
![Screenshot 2023-05-19 223639](https://github.com/kunjgit/GameZone/assets/96378085/8ba2d6a4-b74b-43d0-ad80-5aabe6c43231)

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by iriteshmishra** [comment]
I hope you will assign me this issue @kunjgit

**Comment by kunjgit** [comment]
Hey @iriteshmishra  ! Thank you for raising an issue 💗 You have been assigned this issue you can start working on the issue 🎮
