### ISSUE TITLE
Ludo Game [New game]: 

### ISSUE THREAD

**Issue by Gurnav224** [kunjgit/GameZone#40]
### 🎮 Game Request

Ludo is a board game where players aim to move their tokens from the starting point to the center of the board. Rolling a dice determines the number of spaces a token can move. Capturing opponents' tokens and reaching the home area leads to victory. It's a mix of luck and strategy.

### Point down the features

Game points
Multiplayer board game.
Simple rules.
Colorful and visually appealing board design.
Distinct tokens for each player.
Dice rolling for movement.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey  @Gurnav224 ! Thank you for raising an issue 💗 You have been assigned this issue you can start working on the issue 🎮

**Comment by kunjgit** [comment]
Hello @Gurnav224, Time's Uppp!⏰ 
 Sorry for closing your issue! 
 But it's more than a week since we haven't received anything from your side 😢 . 
 Come up with new ideas, create a new issue and make sure you finish it within a week! 🔥 
 All the best! 🚀 
 Happy Hacking! 💗

**Comment by kunjgit** [comment]
Hey @Gurnav224 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
