### ISSUE TITLE
[New game]: Jumble Words Game

### ISSUE THREAD

**Issue by manishh12** [kunjgit/GameZone#4005]
### 🎮 Game Request

This game will generate a random word and scramble it. The player will see the scrambled word and will need to input the correct unscrambled word. If the player guesses correctly, a congratulatory message will be shown; if not, an error message will appear.

### Point down the features

startGame: Selects a random word, scrambles it, and displays it. Enables the input field and submit button.
scrambleWord: Scrambles the letters of the word ensuring the scrambled word is different from the original.
checkWord: Compares the user's input with the original word and displays a message indicating whether the guess was correct or not.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @manishh12 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @manishh12! 
We are already having a similar game request in #3949 👀 
Make sure you come up with a cool unique idea 😀 
 Waiting for your new game idea 💗.

**Comment by kunjgit** [comment]
Hey @manishh12 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
