### ISSUE TITLE
[New game]: Wordmix

### ISSUE THREAD

**Issue by manishh12** [kunjgit/GameZone#4007]
### 🎮 Game Request

WordMix: Merge & Win is a captivating web-based game where players merge two given words to form a single word by alternating letters. This game not only challenges players' vocabulary skills but also tests their creativity in word manipulation, offering an immersive and enjoyable gaming experience.

### Point down the features

Presents players with a pair of words to merge.
Allows players to input their merged word.
Provides instant feedback on the correctness of the merged word.
Generates a new word pair for each game session.
Features a sleek and intuitive user interface for seamless gaming.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @manishh12 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @manishh12 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
