### ISSUE TITLE
[Enhancement]: Adding Home Icon in Connect 4 game

### ISSUE THREAD

**Issue by ShristiiSharma** [kunjgit/GameZone#4014]
### Do you want to have the enhancement of existing game ? 😀 Describe yourself..

Game enhancement

I will add a Home Icon, adding it will improve the game's usability, making it more user friendly and accessible, which can lead to higher user satisfaction and retention.

### Describe the solution you'd like

Solution steps

Adding Home Icon at the top of the game, it will help players to navigate to the Home Page easily, increasing their convenience.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @ShristiiSharma ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @ShristiiSharma ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
