### ISSUE TITLE
[New game]: man,elephant,ant

### ISSUE THREAD

**Issue by tanishkaa08** [kunjgit/GameZone#4015]
### 🎮 Game Request

Game logic and basic description: another version of rock paper scissors but with a cuter look. It is inspired by the good old bedtime story of a elephant and an ant where the ant teaches the elephant a lesson.

### Point down the features

Game points: play with the computer , the computer randomly chooses one of the 3 options when the user does. The won who wins will receive a point. It is a never ending game and can be played with however times one wants. in the game:
the man kills the ant while the ant bites the elephant furthermore the man is crushed by the elephant.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @tanishkaa08 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @tanishkaa08 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
