### ISSUE TITLE
[New game]: Simon Game

### ISSUE THREAD

**Issue by MitulSonagara** [kunjgit/GameZone#4018]
### 🎮 Game Request

In this different color palate's are there and they blink in some specific order and after that we have to click all the palates in that order. If we successfully click on that order then level goes up.

### Point down the features

Points are based on at most which level can you reach.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @MitulSonagara , You can't have another issue before completing the previous one 😀 
 you already have the following 1 open issues 👀 ! :

#3242

**Comment by kunjgit** [comment]
Hey @MitulSonagara ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by MitulSonagara** [comment]
> Hey @MitulSonagara , You can't have another issue before completing the previous one 😀 you already have the following 1 open issues 👀 ! :
> 
> #3242

I have already opened the pull request for that please check that.

**Comment by MitulSonagara** [comment]
@kunjgit can you open this issue this issue is closed
