### ISSUE TITLE
[New game]: "Eco Quest: The Recycling Challenge

### ISSUE THREAD

**Issue by dvnshi** [kunjgit/GameZone#4021]
### 🎮 Game Request

Game logic and basic description
Primary Description:
Players are presented with different types of waste items, and they need to drag and drop each item into the correct bin (e.g., paper, plastic, glass, metal, organic, and general waste). The game features multiple levels of increasing difficulty, with more types of waste and more bins as the levels progress. Players are rewarded with points and can unlock badges or achievements for reaching certain milestones.

Game Logic
1. Game Setup:

HTML Structure:
Containers for waste items and recycling bins.
Score display.
Level indicator.
Start button.
2. Game Start:

Display the initial set of waste items and bins.
Initialize score and level.
3. Drag and Drop Mechanics:

Implement drag and drop functionality using JavaScript.
Allow waste items to be draggable.
Designate bins as drop targets.
4. Sorting Logic:

Check if the dragged item is dropped into the correct bin.
If correct, increase the score and display a success message.
If incorrect, display an error message and potentially decrease the score.
5. Levels and Difficulty:

As the player progresses through levels, increase the number of waste items and bins.
Introduce new types of waste items at higher levels.
Make the game progressively more challenging.
6. Scoring System:

Award points for each correctly sorted item.
Deduct points for incorrect sorting (optional).
Track and display the player’s total score.
7. Game Over and Restart:

Define the conditions for the game to end (e.g., timer runs out, all items are sorted).
Provide an option to restart the game from the beginning or the last completed level.

### Point down the features

Game points 
Eco Quest: The Recycling Challenge" is an interactive web-based game designed to educate players on proper recycling practices. The game involves sorting various types of waste into the correct recycling bins under time pressure. It aims to raise awareness about environmental sustainability while providing a fun and engaging experience.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by dvnshi** [comment]
please assign this issue to me under GSSOC'24 with levels

**Comment by kunjgit** [comment]
Hey @dvnshi ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by dvnshi** [comment]
pls add the level gssoc

**Comment by kunjgit** [comment]
Hello @dvnshi, Time's up!⏰ 
 Sorry for closing your issue! 
 But it's more than a week since we haven't received anything from your side 😢 . 
 Come up with new ideas, create a new issue and make sure you finish it within a week! 🔥 
 All the best! 🚀 
 Happy Hacking! 💗
