### ISSUE TITLE
[New game]: Monopoly Game

### ISSUE THREAD

**Issue by Damini2004** [kunjgit/GameZone#4025]
### 🎮 Game Request

Game logic and basic description

Monopoly is a classic board game where players compete to acquire wealth through buying, renting, and trading properties. The objective is to drive opponents into bankruptcy, thus becoming the richest player by the end of the game.

Game Setup:
Players: 2 to 8 players.
Board: The board consists of 40 spaces, including 28 properties, 3 Chance spaces, 3 Community Chest spaces, 4 railroads, 2 utilities, a "Go" space, a "Jail" space, a "Free Parking" space, and a "Go to Jail" space.
Tokens: Each player selects a token to move around the board.
Money: Players start with a set amount of money.

### Point down the features

Game points
Game Play:
Turns: Players take turns rolling two six-sided dice.
Movement: Players move their tokens the number of spaces indicated by the dice roll.
Property Transactions:
Buying: If a player lands on an unowned property, they can buy it.
Rent: If the property is owned, the player must pay rent to the owner.
Chance and Community Chest: Players draw cards that can result in various outcomes, such as paying fines, earning money, or moving to different board spaces.
Special Spaces:
Go: Players collect $200 each time they pass "Go".
Jail: Players can be sent to jail and must either roll doubles, use a "Get Out of Jail Free" card, or pay a fee to get out.
Free Parking: A neutral space where nothing happens.
Go to Jail: Sends the player directly to jail.
Development: Players can build houses and hotels on their properties to increase the rent they can charge.
Trading: Players can trade properties, money, and cards.
Bankruptcy: When a player cannot pay what they owe, they go bankrupt and are out of the game. Their assets are distributed to their creditors or returned to the bank.
Winning: The game ends when all but one player is bankrupt, or a set time limit is reached, and the wealthiest player wins.

![image](https://github.com/kunjgit/GameZone/assets/119414762/88ebf72b-d4e0-4070-80d0-57b3fbdf158e)

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Damini2004 , You can't have another issue before completing the previous one 😀 
 you already have the following 1 open issues 👀 ! :

#3896

**Comment by kunjgit** [comment]
Hey @Damini2004 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by kunjgit** [comment]
Hey @Damini2004 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by Damini2004** [comment]
@kunjgit I have created Pull Request For it kindly go through the pull request.
