### ISSUE TITLE
[New game]: Dice game

### ISSUE THREAD

**Issue by Hemav009** [kunjgit/GameZone#4027]
### 🎮 Game Request

Engaging two-player dice game where the objective is to be the first to reach a total score of 100 points. Players take turns rolling a die and accumulate points during their turn. The twist is that if a player rolls a 1, their current turn's score is reset to 0, and their turn ends. Players must strategize when to roll and when to hold to avoid losing points and give themselves the best chance to win.

Game Rules

### Point down the features

- Two Players: The game is played with two players.

- Turn-Based Play: Players alternate turns rolling a single die.

- Scoring: On their turn, a player can roll the die as many times as they wish. Each roll adds the die's value to the player's temporary score for that turn.

- Rolling a 1: If a player rolls a 1, their temporary score for that turn is reset to 0, and their turn ends immediately.

- Holding: A player can choose to hold at any time during their turn, adding their temporary score to their total score and ending their turn.

- Winning the Game: The first player to reach a total score of 100 points wins the game.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Hemav009 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @Hemav009 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
