### ISSUE TITLE
[Enhancement]:  Snake water Gun game main page is to change and add water pic to the water button 

### ISSUE THREAD

**Issue by jayanththalla** [kunjgit/GameZone#4030]
### Do you want to have the enhancement of existing game ? 😀 Describe yourself..

Game enhancement
My idea is add the water pic in the water button and remove replit

### Describe the solution you'd like

Solution steps
<img width="290" alt="image" src="https://github.com/kunjgit/GameZone/assets/121346142/9da752f6-ff47-4165-bcee-cdc45c15a9c3">
water button showing white 
<img width="116" alt="image" src="https://github.com/kunjgit/GameZone/assets/121346142/c69c7f67-4726-46cf-b504-7fed91ae0e40">
remove replit 
please assign me @pa

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @jayanththalla , You can't have another issue before completing the previous one 😀 
 you already have the following 1 open issues 👀 ! :

#3428

**Comment by kunjgit** [comment]
Hey @jayanththalla ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by kunjgit** [comment]
Hey @jayanththalla ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by jayanththalla** [comment]
please assign me #3428 was assigned to others 
please assign me this issue @kunjgit
