### ISSUE TITLE
[New game]: Tic Tac Toe

### ISSUE THREAD

**Issue by dipansrimany2006** [kunjgit/GameZone#4032]
### 🎮 Game Request

Game logic and basic description: The Tic Tac Toe Game is a fundamental game. The existing Tic Tac Toe has many issues, so I want to add a new game.

Issues of the Existing Tic Tac Toe Game:
1. After the game is complete, one can edit the game-winner. 
2. The theme is not so good.
3. So many sounds are used, which makes the User Experience down.
4. There is no round counter in the game and the game does not count the winning time of X and O players.
5. The home button in the game redirects the GameZone to a new page. 

### Point down the features

Game points

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @dipansrimany2006 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @dipansrimany2006 ! , This issue is already assigned to @Saipradyumnagoud. 💗 
 You can work on other issues 🚀 
 If there is anything wrong you can contact us on [Discord🕹️](https://discord.gg/fgwk4XZfxG)👀

**Comment by kunjgit** [comment]
Hey @dipansrimany2006 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
