### ISSUE TITLE
[New game]:  DodgeIT

### ISSUE THREAD

**Issue by harshmishra19** [kunjgit/GameZone#4034]
### 🎮 Game Request

Game logic and basic description
Welcome to Dodgeit, a fast-paced dodging game where you must avoid obstacles to score points!

### Point down the features

Game points
Use the left and right arrow keys to move your vehicle.
Dodge obstacles to earn points and survive as long as possible.
Press the "Play" button on the main menu to start the game.
Left Arrow Key: Move the vehicle to the left.
Right Arrow Key: Move the vehicle to the right.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @harshmishra19 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by harshmishra19** [comment]
@kunjgit You were suppose to assign me

**Comment by kunjgit** [comment]
Hello @harshmishra19, Time's up!⏰ 
 Sorry for closing your issue! 
 But it's more than a week since we haven't received anything from your side 😢 . 
 Come up with new ideas, create a new issue and make sure you finish it within a week! 🔥 
 All the best! 🚀 
 Happy Hacking! 💗
