### ISSUE TITLE
[New game]: AquaSort: A Water Sorting Puzzle

### ISSUE THREAD

**Issue by thevijayshankersharma** [kunjgit/GameZone#4036]
### 🎮 Game Request

Game Request:
Dive into the refreshing world of AquaSort, a water sorting puzzle adventure that challenges your strategic thinking and problem-solving skills. Inspired by the popular water sort puzzle game, AquaSort takes the concept to the next level with immersive gameplay and captivating challenges.

### Point down the features

Game Logic:
In AquaSort, players are presented with a series of test tubes filled with colorful water. The objective is to sort the water in each tube so that each tube contains only one color of water. To achieve this, players can transfer water between tubes, but there are rules to follow:

Players can only transfer water from one tube to another if the receiving tube is either empty or has the same color of water on top.
The last layer of water in a tube must match the color of the water being transferred.
As players progress through levels, they will encounter increasingly complex arrangements of test tubes and water colors, requiring careful planning and strategic thinking to solve.

![image](https://github.com/kunjgit/GameZone/assets/109781385/ac728ae4-bc30-42dd-bc6d-f43ce9946f3a)

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @thevijayshankersharma ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @thevijayshankersharma ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by thevijayshankersharma** [comment]
@kunjgit do you have any discord server to communicate??
