### ISSUE TITLE
[New game]: Arrow Strike

### ISSUE THREAD

**Issue by Nikuunj** [kunjgit/GameZone#4052]
## Game logic and basic description

Arcane Archer is a captivating journey where players master the art of archery amidst mystical landscapes. With intuitive controls and magical abilities, players embark on quests, face mythical creatures, and compete in thrilling tournaments. Become a legend of the bow in Arcane Archer.

## Game points
- Target Accuracy: Hit closer to the center for more points.
- Combo Multipliers: Keep hitting targets without missing for extra points.
- Special Shots: Use special abilities for additional points.
- Quest Completion: Complete objectives for point rewards.

### Select program in which you are contributing  
GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Nikuunj ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by Nikuunj** [comment]
@kunjgit plz review my pr

**Comment by why-Radhika** [comment]
Hey @kunjgit, I would like to work on this issue. I noticed it was assigned for over a month but no PR is merged yet. So if it matches the guidelines please assign the issue to me. I would like to work on it.

**Comment by kunjgit** [comment]
Hello @Nikuunj, Time's up!⏰ 
 Sorry for closing your issue! 
 But it's more than a week since we haven't received anything from your side 😢 . 
 Come up with new ideas, create a new issue and make sure you finish it within a week! 🔥 
 All the best! 🚀 
 Happy Hacking! 💗
