### ISSUE TITLE
Memory Maze

### ISSUE THREAD

**Issue by abhishekdumaniya** [kunjgit/GameZone#4053]
### 🎮 Game Request

Help children enhance their memory, problem-solving, and spatial reasoning skills by navigating through a series of mazes where they need to remember patterns and sequences to progress.

### Point down the features

Memory Challenges: Puzzles that focus on improving short-term and long-term memory.
Pattern Recognition: Activities that teach children to identify and replicate patterns.
Problem-Solving: Games that encourage logical thinking and strategy.
Mini-Games:

Sequence Recall: Players observe a sequence of lights or sounds and must replicate it accurately.
Match the Pairs: A classic memory game where players find matching pairs of cards within a limited time.
Shape and Color Puzzles: Activities where players must match shapes or colors based on given patterns.

Progress Badges: Players earn badges for successfully completing educational activities, encouraging continued participation.
Unlockable Content: Special areas, characters, or abilities become available upon completing a certain number of learning stations.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @abhishekdumaniya ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @abhishekdumaniya! 🙂 
 It seems like you are not following proper guidelines !! 👀 
 Read documentation properly !!🙏 
 If you have any queries reach out to us on [Discord🕹️](https://discord.gg/fgwk4XZfxG) .

**Comment by kunjgit** [comment]
Hey @abhishekdumaniya ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
