### ISSUE TITLE
[New game]: Building Block Game 

### ISSUE THREAD

**Issue by aasthakourav20** [kunjgit/GameZone#4056]
### 🎮 Game Request

Game logic and basic description : JavaScript concepts such as manipulating the DOM, handling event listeners, and creating user-friendly designs are used.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @aasthakourav20 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by aasthakourav20** [comment]
Hey @kunjgit , Kindly assign this issue to me under GSSoC'24 so that I can start working on it .

**Comment by kunjgit** [comment]
Hey @aasthakourav20 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
