### ISSUE TITLE
[New game]: Cartoon Character Guessing Game

### ISSUE THREAD

**Issue by DharshiBalasubramaniyam** [kunjgit/GameZone#4058]
### 🎮 Game Request

Game logic and basic description:
Objective: The player guesses the cartoon character based on an image.

Display an image of a cartoon character.
Provide multiple-choice options for the character's name.
Give feedback on correct or incorrect guesses.

### Point down the features

Game points:
for each correct answer player will gain 1 point.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @DharshiBalasubramaniyam ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @DharshiBalasubramaniyam ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
