### ISSUE TITLE
[New game]:  Adding "Turn on the Light" Game

### ISSUE THREAD

**Issue by thevijayshankersharma** [kunjgit/GameZone#4059]
### 🎮 Game Request

"Turn on the Light" is a puzzle game where players are presented with a grid of lights, some of which are on and others off. The goal is to turn on all the lights by toggling them on or off. However, toggling one light affects the adjacent lights, either turning them on if they were off or turning them off if they were on. The challenge lies in figuring out the correct sequence of moves to achieve the goal.

### Point down the features

Grid Layout: The game will feature a grid layout, typically ranging from 4x4 to 8x8, with lights arranged in a pattern.
Toggle Mechanics: Players can interact with the lights by tapping or clicking on them to toggle their state.
Adjacent Interaction: Toggling a light affects the state of adjacent lights, creating a chain reaction that players must strategize around.
Multiple Levels: The game will offer multiple levels of increasing difficulty, with different grid sizes and configurations to challenge players.
Hints System: For players who get stuck, a hint system can provide clues or guidance on the next move without giving away the solution entirely.
Undo Functionality: Players can undo their moves to backtrack and try different strategies if they make a mistake.
Saves Progress: The game automatically saves the player's progress, allowing them to continue from where they left off.
Score and Achievement Tracking: Players can earn achievements based on their performance, such as completing levels within a certain number of moves or time limits.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @thevijayshankersharma , You can't have another issue before completing the previous one 😀 
 you already have the following 1 open issues 👀 ! :

#4036

**Comment by kunjgit** [comment]
Hey @thevijayshankersharma ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by kunjgit** [comment]
Hey @thevijayshankersharma ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)
