### ISSUE TITLE
[New game]: Life’s Mosaic

### ISSUE THREAD

**Issue by PallaviGudupallavi** [kunjgit/GameZone#4060]
### 🎮 Game Request

Game logic and basic description:
This basic logic forms the foundation of Life's Mosaic, allowing for the exploration of complex patterns and behaviors emerging from simple rules.The universe is an infinite, two-dimensional orthogonal grid of square cells.
Each cell can be in one of two states: ALIVE or DEAD.
Each cell interacts with its eight neighbors (horizontally, vertically, and diagonally adjacent cells).

Rules:
Underpopulation: Any live cell with fewer than two live neighbors dies.
Survival: Any live cell with two or three live neighbors lives on to the next generation.
Overpopulation: Any live cell with more than three live neighbors dies.
Reproduction: Any dead cell with exactly three live neighbors becomes a live cell.

### Point down the features

Controls: Play, Pause, Fast Forward, Slow Down, Clear, Random
Preset patterns (e.g., Glider, Gosper Glider Gun)

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @PallaviGudupallavi ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hello @PallaviGudupallavi, Time's up!⏰ 
 Sorry for closing your issue! 
 But it's more than a week since we haven't received anything from your side 😢 . 
 Come up with new ideas, create a new issue and make sure you finish it within a week! 🔥 
 All the best! 🚀 
 Happy Hacking! 💗
