### ISSUE TITLE
[New game]: Adding 2048 Game

### ISSUE THREAD

**Issue by harshmishra19** [kunjgit/GameZone#4071]
### 🎮 Game Request

Game logic and basic description
The 2048 game is an addictive puzzle game that has gained immense popularity among puzzle enthusiasts and casual gamers. The objective of the game is to combine numbered tiles on a grid to create a tile with a value of 2048. The game is played on a 4x4 grid, but variations with different grid sizes also exist.

### Point down the features

Game points

The game starts with two tiles, each with a value of either 2 or 4, randomly placed on the grid. The player can move the tiles in four directions: up, down, left, and right. When the player moves the tiles, all the tiles on the grid slide in that direction, with empty spaces being filled by new tiles appearing with a value of 2 or 4.

When two tiles with the same value collide while moving, they merge into a single tile with their values added together. For example, if two tiles with a value of 2 collide, they merge into a single tile with a value of 4. The player's goal is to strategically move the tiles to combine them and create higher-value tiles. The game is won when a tile with a value of 2048 is created, although it is possible to continue playing and achieve higher scores.

However, the game becomes more challenging as the grid fills up with tiles and there are fewer empty spaces to maneuver. The player needs to plan their moves carefully to avoid filling up the grid completely and not being able to make any valid moves. The game ends when there are no more possible moves available, and the player's final score is determined by the total value of the merged tiles on the grid.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @harshmishra19 , You can't have another issue before completing the previous one 😀 
 you already have the following 1 open issues 👀 ! :

#4034

**Comment by kunjgit** [comment]
Hey @harshmishra19 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by kunjgit** [comment]
Hey @harshmishra19 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @harshmishra19! 
We are already having a similar game request in #3856 👀 
Make sure you come up with a cool unique idea 😀 
 Waiting for your new game idea 💗.
