### ISSUE TITLE
[New game]: Disney Trivia

### ISSUE THREAD

**Issue by manmita** [kunjgit/GameZone#4073]
### 🎮 Game Request

A fun and engaging trivia game about Disney movies, characters, and history.

### Point down the features

Features of this game will be as follows:

- Question Display: Shows a trivia question and multiple-choice answers.
- Next Button: Moves to the next question when clicked.
- Timer: Automatically moves to the next question when time runs out.
- Scoreboard: Tracks and displays the player's score at the end of the game or upon restarting.
- Restart Functionality: Allows players to restart the game from the beginning with a reset score.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @manmita ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @manmita ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
