### ISSUE TITLE
[New game]: Doraemon Slide Puzzle

### ISSUE THREAD

**Issue by akshbansal61203** [kunjgit/GameZone#4074]
### 🎮 Game Request

Game logic and basic description: It is a 5X5 slide puzzle game having a Doraemon image.
user has to arrange the pieces of slide puzzle in order to make the image of Doraemon correct. It's a fun game to challenge your brain

### Point down the features

Game points:
I t will count the number of turns user took to solve the puzzle and if the number of turns are minimum the user will be declared as winner

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @akshbansal61203 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by akshbansal61203** [comment]
thank you

**Comment by kunjgit** [comment]
Hello @akshbansal61203, Time's up!⏰ 
 Sorry for closing your issue! 
 But it's more than a week since we haven't received anything from your side 😢 . 
 Come up with new ideas, create a new issue and make sure you finish it within a week! 🔥 
 All the best! 🚀 
 Happy Hacking! 💗
