### ISSUE TITLE
New Game Added : Tic Tac Toe

### ISSUE THREAD

**Issue by jency1** [kunjgit/GameZone#4077]
@kunjgit Please review and merge this PR.

I have resolved the merge conflict issues.

_Originally posted by @jency1 in https://github.com/kunjgit/GameZone/issues/3881#issuecomment-2143692109_

**Comment by kunjgit** [comment]
Hey @jency1 , You can't have another issue before completing the previous one 😀 
 you already have the following 1 open issues 👀 ! :

#3873

**Comment by kunjgit** [comment]
Hey @jency1 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by kunjgit** [comment]
Hey @jency1 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)
