### ISSUE TITLE
[Bug]: Signup/login

### ISSUE THREAD

**Issue by Rupalpy** [kunjgit/GameZone#4078]
### Give a brief about the bug ✍️

 Signup/Login missing

### What is the expected behavior? 🤔

Signup/login must be made essential before playing any game on the page.

### Provide step by step information reproduce the bug 📄

First the user must sign up then be able to play any of the game listed on the website.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Rupalpy ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @DhruvJohri ! , This issue is already assigned to @Rupalpy. 💗 
 You can work on other issues 🚀 
 If there is anything wrong you can contact us on [Discord🕹️](https://discord.gg/fgwk4XZfxG)👀

**Comment by Rupalpy** [comment]
@kunjgit i have worked on it and created the signup/login pages , kindly check pr #4255

**Comment by kunjgit** [comment]
Hello @Rupalpy, Time's up!⏰ 
 Sorry for closing your issue! 
 But it's more than a week since we haven't received anything from your side 😢 . 
 Come up with new ideas, create a new issue and make sure you finish it within a week! 🔥 
 All the best! 🚀 
 Happy Hacking! 💗
