### ISSUE TITLE
[Enhancement]: Making Beyblade Game interactive

### ISSUE THREAD

**Issue by KomalMaurya** [kunjgit/GameZone#4080]
### Do you want to have the enhancement of existing game ? 😀 Describe yourself..

Game enhancement : In the existing "Beyblade" game, it doesn't declare any winner and it seems non- interactive too as only beys are spinning on their position and nothing else.

https://github.com/kunjgit/GameZone/assets/145214525/bd7c0815-f25f-4b83-a892-aa4c1d3738ee
Name : Komal Maurya 
GitHub profile link : https://github.com/KomalMaurya
Role in GSSOC'24 : Contributor

### Describe the solution you'd like

Solution steps : 
I would like to make it interactive by starting every match with countdown to 3 and will spin and revolute bey around in bey stadium which will conclude to a winner.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @KomalMaurya ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by KomalMaurya** [comment]
Assign

**Comment by KomalMaurya** [comment]
@kunjgit I have added a pull request.
Happy to work for your project!
Thank you for providing this issue

**Comment by KomalMaurya** [comment]
@kunjgit I already added pulled request and fixed the issue.

**Comment by dnyandeepchute** [comment]
sorry @KomalMaurya, i didn't saw that.

**Comment by dnyandeepchute** [comment]
i will unassign myself.

**Comment by KomalMaurya** [comment]
@dnyandeepchute It's alright now. Thanks for understanding...

**Comment by kunjgit** [comment]
Hey @KomalMaurya ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
