### ISSUE TITLE
[New game]:  Tetris

### ISSUE THREAD

**Issue by CodeXsubham** [kunjgit/GameZone#4091]
### 🎮 Game Request

Game logic and basic description
In Tetris, players complete lines by moving differently shaped pieces , which descend onto the playing field.
The Tetris game requires players to strategically rotate, move, and drop a procession of Tetriminos that fall into the rectangular Matrix at increasing speeds. Players attempt to clear as many lines as possible by completing horizontal rows of blocks without empty space

### Point down the features

Game points
- Core Gameplay mechanics
- Controls
- Scoring system

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @CodeXsubham , You can't have another issue before completing the previous one 😀 
 you already have the following 1 open issues 👀 ! :

#4023

**Comment by kunjgit** [comment]
Hey @CodeXsubham ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by kunjgit** [comment]
Hey @CodeXsubham ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)
