### ISSUE TITLE
[Enhancement]: Tic Tac Toe Game 

### ISSUE THREAD

**Issue by Apurv7777** [kunjgit/GameZone#4095]
### Do you want to have the enhancement of existing game ? 😀 Describe yourself..

Game enhancement :
- A better version of exisiting Tic Tac Toe Game

### Describe the solution you'd like

Solution steps :
- You can preview it here : [Tic Tac Toe](https://oxoxgame.netlify.app/)

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Apurv7777 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
