### ISSUE TITLE
[Question]: Too many games

### ISSUE THREAD

**Issue by VijaySamant4368** [kunjgit/GameZone#4098]
### Describe your question or ask for support.❓

I think there are already too many games in the repo, and almost al the new one's quality is very very low.
In my opinion we should opt for quality over quantity, therefore it would be better to stop assigning new games to people, instead we should work on improving the existing ones.

### Select program in which you are contributing

GSSoC24, IWOC2024

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @VijaySamant4368 , You can't have another issue before completing the previous one 😀 
 you already have the following 1 open issues 👀 ! :

#4008

**Comment by kunjgit** [comment]
Hey @VijaySamant4368 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by kunjgit** [comment]
Hey @VijaySamant4368 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)
