### ISSUE TITLE
[Documentation Bug]: Issue with the README.md file

### ISSUE THREAD

**Issue by Akshit-Soni** [kunjgit/GameZone#4099]
### Describe the bug ✍️

The README.md file contains a list of all the games mentioned in a tabular format. I have noticed the table to be missing after a few games. Also, there are multiple duplicate entries for many games.

### Provide step by step information reproduce the bug 📄

I will rewrite the file to ensure the table is complete and clear.  I will also make sure there are no duplicate entries in the table.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Akshit-Soni ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by AkashKeote** [comment]
cant able to do my work sorry it is big data

**Comment by Akshit-Soni** [comment]
The issue has still not been resolved.

**Comment by AkashKeote** [comment]
what happen help me to find out

**Comment by Akshit-Soni** [comment]
> what happen help me to find out

Hi, I cannot see whether the README.md file was updated. I am fairly new to open-source contribution so sorry if I am mistaken.

**Comment by AkashKeote** [comment]
its take time to get update the the review it first

**Comment by AkashKeote** [comment]
![image](https://github.com/kunjgit/GameZone/assets/170916476/be77c6b3-979a-46db-9832-d4f368872202)
here this is my repository after change you see that the duplicates games remove and i add unique games in table

**Comment by AkashKeote** [comment]
https://github.com/AkashKeote/GameZone/blob/main/README.md

**Comment by AkashKeote** [comment]
if any duplicates may be left beacause data is so big and its take time for me to search so now my work is done you can assign yourself now

**Comment by Akshit-Soni** [comment]
okay sure. thanks.

**Comment by AkashKeote** [comment]
@Akshit-Soni did you see any changes in original i get merged message but cant see my changes in the original one .I am too excited beacuse i invest my 6hr to change the fixes today on my 1st contribution

**Comment by kunjgit** [comment]
Hello @Akshit-Soni, Time's up!⏰ 
 Sorry for closing your issue! 
 But it's more than a week since we haven't received anything from your side 😢 . 
 Come up with new ideas, create a new issue and make sure you finish it within a week! 🔥 
 All the best! 🚀 
 Happy Hacking! 💗
