### ISSUE TITLE
[New game]: Duck hunting game

### ISSUE THREAD

**Issue by ePSA-eJya** [kunjgit/GameZone#410]
### 🎮 Game Request

Game logic and basic description

### Point down the features

Game points

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @ePSA-eJya! 
We are already having a similar game request in #283 👀 
Make sure you come up with a cool unique idea 😀 
 Waiting for your new game idea 💗.
