### ISSUE TITLE
[New game]:  Pop the Bubbles

### ISSUE THREAD

**Issue by samarsajad** [kunjgit/GameZone#4100]
### 🎮 Game Request

Pop The Bubbles!" is a fast-paced, retro-style game where your reflexes and number recognition skills are put to the test. You have 60 seconds to pop as many bubbles as possible, focusing on bubbles with the current target number for bonus points. Perfect for players of all ages, it's easy to learn and endlessly fun!
![image](https://github.com/swapnilsparsh/30DaysOfJavaScript/assets/142666229/32720484-0385-4e3e-bb86-5ca93a6b4933)

### Point down the features

Your reflexes and number recognition skills are put to the test.
You have 60 seconds to pop as many bubbles as possible.
Each time you pop a bubble, a new target number appears. Focus on popping bubbles with the current target number for bonus points!
Easy to learn and perfect for players of all ages

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by samarsajad** [comment]
Please assign this to me

**Comment by kunjgit** [comment]
Hey @samarsajad ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by samarsajad** [comment]
Please assign thus to me @kunjgit

**Comment by kunjgit** [comment]
Hey @samarsajad ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
