### ISSUE TITLE
[Bug]: Three bugs in Guess The Number Game

### ISSUE THREAD

**Issue by mohitgedar** [kunjgit/GameZone#4101]
### Description: There are three bugs in the game 
- Once you have completed the game and won, now if you keep pressing the guess button the no. of tries you used keeps increasing
- But if you lost the game and lost all lives, now if you keep pressing the guess game , the  ***Guessed numbers are:***  , keep adding more numbers
- third if you reset the game , the no of lives already used do not get updated for new game instead its the same of previous game , once you start , then it get updated

### Description : Expected Behavior
- once you complete the game the guess button , should not do anything 
- reset button should reset the game totally, not only internally but also on the display

### I have already fixed these bugs in my local repo and also well commented them :

- Manupulating Dom to update screen in reset  button so that the lives are reset properly
- Added two if's to the Play function to check if user has won or lost , so that pressing the Guess button don't run the game function

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @mohitgedar ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by AkashKeote** [comment]
want to work this project /assign me please

**Comment by kunjgit** [comment]
Hey @AkashKeote ! , This issue is already assigned to @mohitgedar. 💗 
 You can work on other issues 🚀 
 If there is anything wrong you can contact us on [Discord🕹️](https://discord.gg/fgwk4XZfxG)👀

**Comment by kunjgit** [comment]
Hey @mohitgedar ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
