### ISSUE TITLE
[New game]: Reflex Test Game

### ISSUE THREAD

**Issue by Harshitmishra001** [kunjgit/GameZone#4103]
### Game logic and basic description
Create a Reflex Test game using HTML, CSS, and JavaScript. The game features a 3x3 grid of circles, with a circle image turning "Yellow" every second. The player clicks the active circle to score points. The game ends if the player clicks a wrong circle ("You Lose!") or when the 60-second timer reaches zero ("Time's Up! Game Over!"). The game initializes with a score of 0 and a countdown timer. The coloured circle disappears and reappears in another random circle upon a successful click.

### Point down the features

Game points
-3x3 grid with circles
-Start button
-60-second timer
-Scoreboard
-End game conditions (wrong click or timer ends)

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Harshitmishra001 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @Harshitmishra001! 
We are already having a similar game request in #3917 👀 
Make sure you come up with a cool unique idea 😀 
 Waiting for your new game idea 💗.

**Comment by kunjgit** [comment]
Hey @Harshitmishra001 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
