### ISSUE TITLE
[Enhancement]: UI of Brick Breaker Game

### ISSUE THREAD

**Issue by sau-mili** [kunjgit/GameZone#4110]
### Do you want to have the enhancement of existing game ? 😀 Describe yourself..

Game enhancement: I would like to enhance the whole UI of brick breaker game

### Describe the solution you'd like

Solution steps
I would like to improve both the CSS as well as game window UI for this

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @sau-mili , You can't have another issue before completing the previous one 😀 
 you already have the following 1 open issues 👀 ! :

#4108

**Comment by kunjgit** [comment]
Hey @sau-mili ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by kunjgit** [comment]
Hey @sau-mili ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by sau-mili** [comment]
I have completed and done PR for previous issue, can you please open this again?
