### ISSUE TITLE
[New game]: Jumbled Word Game

### ISSUE THREAD

**Issue by Jagpreet153** [kunjgit/GameZone#4116]
### 🎮 Game Request

Game logic and basic description
There would be some jumbled word the correct word need to be guessed by the user . The user need to guess the word within time limit

### Point down the features

Game points
If the guess is correct the user gain points 

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Jagpreet153 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @Jagpreet153! 
We are already having a similar game request in #3949 👀 
Make sure you come up with a cool unique idea 😀 
 Waiting for your new game idea 💗.
