### ISSUE TITLE
[New game]: Seahorse Rash

### ISSUE THREAD

**Issue by udbhav26** [kunjgit/GameZone#4117]
### 🎮 Game Request

Game logic and basic description
   It's a shooting game where a mechanical seahorse throws bullets towards the incoming enemy fishes which are of different sizes and health points. Eliminating each fish will reward some points. The end goal of the game is to collect let's say 50 points (can be changed) in less than 30 seconds.

### Point down the features

Game points
  - There will be a seahorse which shoots bullets. 
  - It will gain a power up for some time if hit by any fish. 
  - When fishes are hit their parts will bounce and drop on the floor.
  - Elimination of certain fish rewards with some points.
  - The seahorse will have certain number of bullets which keeps filling with time if out of bullets then the horse will not be able to 
    shoot.
  - There will be a fixed timer which can be set by us developers.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @udbhav26 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by udbhav26** [comment]
can you please assign this to me

**Comment by udbhav26** [comment]
assign

**Comment by AkashKeote** [comment]
**@udbhav26  what is problem in this game i will solve**

**Comment by udbhav26** [comment]
@AkashKeote there  is no issue. I have raised this to add a new game which i have made.

**Comment by AkashKeote** [comment]
@udbhav26 sorry i am new so dont know much

**Comment by kunjgit** [comment]
Hello @udbhav26, Time's up!⏰ 
 Sorry for closing your issue! 
 But it's more than a week since we haven't received anything from your side 😢 . 
 Come up with new ideas, create a new issue and make sure you finish it within a week! 🔥 
 All the best! 🚀 
 Happy Hacking! 💗
