### ISSUE TITLE
Adding a "Help Us Improve!"

### ISSUE THREAD

**Issue by AkshitGarg24** [kunjgit/GameZone#4118]
### Give a brief about the bug ✍️

The "Help Us Improve!" button is not currently visible or functional on the website.

### What is the expected behavior? 🤔

A "Help Us Improve!" button should be included on the website, and users should be able to use it when they face any technical glitches or when they want to provide additional suggestions or features.

### Provide step by step information reproduce the bug 📄

- Navigate to the website homepage.

- Look for the "Help Us Improve!" button in the header or footer section of the page.

- Observe that the button is either not present or non-functional.

- Attempt to provide feedback through any other available options to verify the absence of the dedicated feedback button.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @AkshitGarg24 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @AkshitGarg24! 🙂 
 It seems like you are not following proper guidelines !! 👀 
 Read documentation properly !!🙏 
 If you have any queries reach out to us on [Discord🕹️](https://discord.gg/fgwk4XZfxG) .

**Comment by kunjgit** [comment]
Hey @AkshitGarg24 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
