### ISSUE TITLE
[Enhancement]: Whack a Mole : Game's start button's style should be modified and there should be a  message after starting the game

### ISSUE THREAD

**Issue by Tasnuva12** [kunjgit/GameZone#4120]
### Do you want to have the enhancement of existing game ? 😀 Describe yourself..

-I want to modify the button's style
-I want to add some messages so that user can understand when the game has been started and when it's over

### Describe the solution you'd like

- Go to the css file and change the button's style
- -Go to the js file and change the functionality of the page 

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Tasnuva12 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @Tasnuva12 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
