### ISSUE TITLE
[New game]: Reverse Memory Challenge

### ISSUE THREAD

**Issue by MuraliDharan7** [kunjgit/GameZone#4122]
### 🎮 Game Request

Game logic and basic description

The game presents a grid of colored squares.
Clicking a square reveals a random color for a brief moment, then hides it again.
The twist is memorizing the sequence of colors in reverse order. With each successful recall, the sequence length increases, making it progressively harder.
Players lose if they enter the sequence incorrectly.

### Point down the features

Game points

Reverse Memory: Recall colors in reverse order, adding a unique challenge.
Level Up System: Sequence length increases for a growing challenge.
Simple Interface: Easy to learn with familiar grid and colors.
Customizable Difficulty (Optional): Adjust grid size or difficulty levels for personalization.
Feedback (Optional): Visual/audio cues for right/wrong answers for better engagement.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @MuraliDharan7 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @MuraliDharan7 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
