### ISSUE TITLE
[Bug]: Add Navbar to website

### ISSUE THREAD

**Issue by udbhav26** [kunjgit/GameZone#4127]
### Give a brief about the bug ✍️

Description
This website should contain a navbar using which we can navigate to different pages like home, games, signup,login.
Also we can keep the toggle button of light/dark mode and search bar there for ease of access.

### What is the expected behavior? 🤔

Description
Expected behavior of the navbar is to give us ability to naviagte and use features mentioned above with ease.

### Provide step by step information reproduce the bug 📄

Description
- Add all the necessary code of html and css required for the navbar and its features.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @udbhav26 , You can't have another issue before completing the previous one 😀 
 you already have the following 1 open issues 👀 ! :

#4117

**Comment by kunjgit** [comment]
Hey @udbhav26 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by kunjgit** [comment]
Hey @udbhav26 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)
