### ISSUE TITLE
[New game]: I want to  add Quiz game 

### ISSUE THREAD

**Issue by anishaxtha** [kunjgit/GameZone#413]
### 🎮 Game Request

Game logic and basic description
Here in this game::
The user is asked if they want to play the quiz game. If they don't respond with "yes," the game ends.
If the user chooses to play, the game begins with an initial score of 0.
The user is asked a series of questions, and their answers are compared to the correct answers.
For each correct answer, the score is incremented by 1.
After all the questions are answered, the final score is displayed along with a corresponding message.
If the score is 5 or higher, a congratulations message is printed along with the percentage of correct answers.
If the score is between 3 and 4, a message is printed indicating the number of correct answers.
If the score is below 3, an "Oops! Try again" message is displayed.
The code follows a linear flow where each question is asked and evaluated individually. In the end, the score is checked to determine the appropriate message to display.

### Point down the features

Game points

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @anishaxtha ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @anishaxtha! 
We are already having a similar game request in #401 👀 
Make sure you come up with a cool unique idea 😀 
 Waiting for your new game idea 💗.

**Comment by kunjgit** [comment]
Hey @anishaxtha ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
