### ISSUE TITLE
[Enhancement]: adding more puzzle question to escaperoom game

### ISSUE THREAD

**Issue by NAVJOT-786** [kunjgit/GameZone#4135]
### Title:
Enhancement of Escape Room Game

### Description:
I want to add a new feature to the existing Escape Room Game. Currently, the game involves solving a series of puzzles to find a key and unlock the door. I would like to introduce a time limit for completing the game. Players will have a certain amount of time to solve all the puzzles and escape the room. If they fail to escape within the time limit, they lose the game.

### Proposed Changes:
1. Introduce a countdown timer at the beginning of the game.
2. Display the remaining time to the player throughout the game.
3. If the time runs out before all puzzles are solved, display a message indicating that the player has failed to escape.
4. Allow players to retry the game if they fail to escape within the time limit.

### Benefits:
1. Adds a sense of urgency and challenge to the game.
2. Increases replay value as players can try to beat their previous time.
3. Provides a clear win condition for the game.

### Additional Notes:
Players should have enough time to reasonably solve all the puzzles, so the time limit should be set accordingly.

### Describe the solution you'd like

**Design the User Interface:**

Determine where to display the countdown timer on the game screen.
Decide on the format for displaying the time remaining (e.g., minutes and seconds).
Implement the Countdown Timer:

**Add JavaScript code to initialize a countdown timer when the game starts.**
Update the timer display every second to show the remaining time.
Handle the case when the time runs out, triggering a game over scenario.
**Update the Game Logic:**

Integrate the countdown timer into the game logic to enforce the time limit.
Modify the win condition to include completing the game within the time limit.
Adjust the game over condition to include running out of time.

I am contrubuting upon gssoc24.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @NAVJOT-786 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by sahithivemishetty** [comment]
I would like to work on the issue please assign me

**Comment by kunjgit** [comment]
Hey @NAVJOT-786 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
