### ISSUE TITLE
[New game]: Quantum Maze

### ISSUE THREAD

**Issue by Aditi22Bansal** [kunjgit/GameZone#4137]
### 🎮 Game Request

Game logic and basic description
"Quantum Maze" that involves navigating through a maze with quantum mechanics principles, including superposition and entanglement.

### Point down the features

Game points
Gameplay Features:

Quantum Walls: Walls that can exist in multiple states simultaneously. Players must collapse these walls by observing them to determine if they are passable.
Entangled Paths: Certain paths are entangled, meaning if you choose one path, the corresponding entangled path changes as well.
Superposition Gates: Gates that require the player to be in two places at once, achieved by splitting the player's state.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by Aditi22Bansal** [comment]
@kunjgit 
Kindly assign this issue to me

**Comment by kunjgit** [comment]
Hey @Aditi22Bansal ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @Aditi22Bansal ! , This issue is already assigned to @DhruvJohri. 💗 
 You can work on other issues 🚀 
 If there is anything wrong you can contact us on [Discord🕹️](https://discord.gg/fgwk4XZfxG)👀

**Comment by Aditi22Bansal** [comment]
@kunjgit 
I have already created the PR
Check

**Comment by kunjgit** [comment]
Hey @Aditi22Bansal ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by kunjgit** [comment]
Hey @Aditi22Bansal ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by ishita-43** [comment]
The assignment is First Come First Serve Basis please keep that in mind. 
If only assigner not able to complete task on time the other will get the assignment. 
Thank you

**Comment by kunjgit** [comment]
Hello @Aditi22Bansal, Time's up!⏰ 
 Sorry for closing your issue! 
 But it's more than a week since we haven't received anything from your side 😢 . 
 Come up with new ideas, create a new issue and make sure you finish it within a week! 🔥 
 All the best! 🚀 
 Happy Hacking! 💗
