### ISSUE TITLE
Alignment of going Up Arrow in the center 

### ISSUE THREAD

**Issue by 1754riya** [kunjgit/GameZone#4138]
### Is there an existing issue for this?
I have searched the existing issues

### What happened?
Alignment of the Arrow in the center of the circle for going up arrow.
![Screenshot (77)](https://github.com/kunjgit/GameZone/assets/167575288/0e98af9e-27fb-4b55-87d3-a82a0f9e8883)

### Record:
1. I agree to follow this project's Code of Conduct
2. I'm a GSSOC'24 contributor
3. I want to work on this issue.

@kunjgit, Please assign me this task.

**Comment by kunjgit** [comment]
Hey @1754riya! 🙂 
 It seems like you are not following proper guidelines !! 👀 
 Read documentation properly !!🙏 
 If you have any queries reach out to us on [Discord🕹️](https://discord.gg/fgwk4XZfxG) .

**Comment by kunjgit** [comment]
Hey @1754riya ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @1754riya ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
