### ISSUE TITLE
[New game]: I want to add Dice roller game 

### ISSUE THREAD

**Issue by anishaxtha** [kunjgit/GameZone#414]
### 🎮 Game Request

Game logic and basic description

The program starts by defining a dictionary called dice_art, which contains ASCII art representations of dice faces from 1 to 6.

The user is prompted to enter the number of dice they want to roll.

A list called dice is created to store the values of the rolled dice.

The program generates a random number between 1 and 6 for each die and appends it to the dice list.

The program then prints the ASCII art representation of each die vertically, line by line.

After printing vertically, the program prints the ASCII art representation of each die horizontally, line by line.

The program calculates the sum of the values of all the dice rolled and stores it in the total variable.

Finally, the program displays the total sum of the dice rolled.

### Point down the features

Game points

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @anishaxtha ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @anishaxtha! 
We are already having a similar game request in #401 👀 
Make sure you come up with a cool unique idea 😀 
 Waiting for your new game idea 💗.

**Comment by anishaxtha** [comment]
can you assign me
