### ISSUE TITLE
[New game]: Fighting Game

### ISSUE THREAD

**Issue by zanzo2003** [kunjgit/GameZone#4144]
### 🎮 Game Request

Game logic and basic description
"Fighting Game" is a samurai-themed **multiplayer** game created using HTML, CSS, and JS. In this game, there are 2 player who fight for the victory. 

### Point down the features

Game points
**Movement** - Both player are able to move forward and backward and have unlimited no of jumps.
**Attack** - Both players are masters of sword fighting and can attack each other with their slashes.
**Winner** - The one who survives will win the game.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @zanzo2003 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @zanzo2003! 
We are already having a similar game request in #4062 👀 
Make sure you come up with a cool unique idea 😀 
 Waiting for your new game idea 💗.

**Comment by kunjgit** [comment]
Hey @zanzo2003 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by zanzo2003** [comment]
@kunjgit Hi, thanks for the quick response, will come up with something new.
