### ISSUE TITLE
[New game]: Space Invaders

### ISSUE THREAD

**Issue by zanzo2003** [kunjgit/GameZone#4145]
### 🎮 Game Request

Game logic and basic description
Space Invaders is a classic game in which we have to shoot down all the alien space shuttles preventing them from reaching our base.

### Point down the features

Game points
**Space Shuttle** - Our space shuttle have a gun using which we will shoot down enemies.
**Movement** - We can move left and right and aim at the aliens.
**Aliens** - Auto generated aliens move closer to the base, and our task is to prevent them from reaching our base.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by zanzo2003** [comment]
Please assign this to me

**Comment by kunjgit** [comment]
Hey @zanzo2003 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hello @zanzo2003, Time's up!⏰ 
 Sorry for closing your issue! 
 But it's more than a week since we haven't received anything from your side 😢 . 
 Come up with new ideas, create a new issue and make sure you finish it within a week! 🔥 
 All the best! 🚀 
 Happy Hacking! 💗
