### ISSUE TITLE
[Bug]: Fixing the light mode toggle

### ISSUE THREAD

**Issue by Jasleen1210** [kunjgit/GameZone#4148]
### Give a brief about the bug ✍️

When the light mode toggle is clicked, the colours of the game images are inverted as well, this causes some game previews to be non satisfactory:
![Screenshot 2024-06-02 193302](https://github.com/kunjgit/GameZone/assets/144164397/168710bb-6fe7-4891-b5a4-f6d7afc9b8d2)

### What is the expected behavior? 🤔

The light mode should not consist of the game previews changing, only the background and the accent (header footer search etc) should be affected by the toggle. 

### Provide step by step information reproduce the bug 📄

I have already fixed these bugs in my local repo and also well commented them:
The bug can be fixed by conditioning the toggle to not affect the game images. 

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Jasleen1210 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @Jasleen1210 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
