### ISSUE TITLE
[New game]: Gravity Simulation Game

### ISSUE THREAD

**Issue by Sara1428** [kunjgit/GameZone#4149]
### Game logic and basic description
Objects of type Ball are created in JS, their colors and sizes are assigned randomly via Math.random().
Then, as per the type of celestial body selected by user, the value of gravity is adjusted, and then their motion is simulated by the adjusting the x and y attributes of the object according to the laws of motion.
**The collisions are assumed to be perfectly elastic**

### Game points
First the user needs to select a celestial body of our solar system among the given options. Then a simulation of various balls of various shapes and colors colliding with each other and jumping under the influence of gravity is shown, until all the balls come at rest at the floor.
This way user can feel and enjoy the diverse gravitation of the planetary bodies our solar system.  

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Sara1428 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @Sara1428 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
