### ISSUE TITLE
[New game]: I want to add snake, water and gun game 

### ISSUE THREAD

**Issue by anishaxtha** [kunjgit/GameZone#416]
### 🎮 Game Request

Game logic and basic description
The program starts by importing the random module and printing the game's title.

The user is prompted to enter the number of rounds they want to play.

The program defines a list called options containing the possible choices for the game: Snake, Water, and Gun.

The program initializes counters for the computer's and player's wins.

The game consists of a loop that runs for the specified number of rounds.

In each round, the program displays the available options (Snake, Water, Gun) to the player.

The player enters their choice, and the program uses random.choice() to randomly select the computer's choice.

The program evaluates the choices based on the game rules: Snake beats Water, Water beats Gun, and Gun beats Snake.

The program increments the appropriate win counter based on the outcome of the round.

After each round, the program announces the winner of that round or declares a draw.

Once all rounds are completed, the program determines the final winner based on the number of wins.

The program displays the final result, indicating whether the player won, lost, or if the game ended in a draw.

### Point down the features

Game points

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @anishaxtha ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by anishaxtha** [comment]
can you please assign me

**Comment by anishaxtha** [comment]
can i add this game in python programming

**Comment by kunjgit** [comment]
Hello @anishaxtha, Time's Uppp!⏰ 
 Sorry for closing your issue! 
 But it's more than a week since we haven't received anything from your side 😢 . 
 Come up with new ideas, create a new issue and make sure you finish it within a week! 🔥 
 All the best! 🚀 
 Happy Hacking! 💗

**Comment by kunjgit** [comment]
Hey @anishaxtha ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
