### ISSUE TITLE
[New game]: Tower Defence

### ISSUE THREAD

**Issue by Aditi22Bansal** [kunjgit/GameZone#4161]
### 🎮 Game Request

Game logic and basic description
 In this game, players place defensive towers along a path to stop waves of enemies from reaching the end. Each tower has different abilities and ranges, and players can upgrade towers to improve their effectiveness.

### Point down the features

Game points
Multiple Tower Types:

Basic Tower: Standard tower with medium range and attack speed.
Sniper Tower: Long-range tower with high damage but slow attack speed.
Rapid Fire Tower: Short-range tower with low damage but very fast attack speed.
Splash Damage Tower: Deals area-of-effect damage to multiple enemies at once.
Enemy Variety:

Basic Enemy: Standard enemy with average speed and health.
Fast Enemy: High-speed enemy with lower health.
Tank Enemy: Slow-moving enemy with high health.
Flying Enemy: Can only be attacked by certain towers.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Aditi22Bansal , You can't have another issue before completing the previous one 😀 
 you already have the following 1 open issues 👀 ! :

#4137

**Comment by kunjgit** [comment]
Hey @Aditi22Bansal ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by kunjgit** [comment]
Hey @Aditi22Bansal ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)
