### ISSUE TITLE
[New game]:  Pathways - The maze game

### ISSUE THREAD

**Issue by Pujan-sarkar** [kunjgit/GameZone#4162]
## Game logic and basic description

This is simply a Maze game where you have to start from one point and go to the finish point as fast as you can!

## Game points

1. There are 5 levels in total & each new level increases the difficulty!
2.  You have to use your **W,S,A,D** keys (_W - UP_, _S - DOWN_, _A - LEFT_, _D - RIGHT_) to navigate throught the maze!

## Game interface
![Screenshot 2024-06-03 192837](https://github.com/kunjgit/GameZone/assets/144250917/0de32e4e-787d-4b30-aaea-51be83db41b5)

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hello @Pujan-sarkar, Time's up!⏰ 
 Sorry for closing your issue! 
 But it's more than a week since we haven't received anything from your side 😢 . 
 Come up with new ideas, create a new issue and make sure you finish it within a week! 🔥 
 All the best! 🚀 
 Happy Hacking! 💗
