### ISSUE TITLE
[New game]: Taash Game

### ISSUE THREAD

**Issue by codewithganeshhh** [kunjgit/GameZone#4165]
### 🎮 Game Request

Game logic and basic description:
In Taash Game, the suits have no meaning. 
1. Number cards have a value equal to their number.
2. All the picture cards (Jacks, Queens, and Kings) are worth 10. 
3. Aces are worth 1.
4. The table keeps a record of total wins,loses and draws
5. Click on "Restart" Button to start a new game
6. Click on "Deal" Button to clear the field

### Point down the features

![Patti Game](https://github.com/kunjgit/GameZone/assets/139307139/0457cc7d-5650-4655-babf-f3a737293df9)

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @codewithganeshhh ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @codewithganeshhh ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
