### ISSUE TITLE
[Bug]:  Text remains white when we switch to light mode

### ISSUE THREAD

**Issue by anuragnegi000** [kunjgit/GameZone#4168]
### Give a brief about the bug ✍️

When we switch from dark mode to light mode, the text should also switch to the black color
![blackText](https://github.com/kunjgit/GameZone/assets/115611556/ed693b16-52f8-47de-85c7-9e0576eb5043)

### What is the expected behavior? 🤔

The text should be black when we switch to light mode

### Provide step by step information reproduce the bug 📄

1.Click on the hosted URL
2.Check in navbar switch to light mode

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @anuragnegi000 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by riya-rjha** [comment]
Has this issue been solved? If not then I'm willing to work on this please.

**Comment by kunjgit** [comment]
Hello @anuragnegi000, Time's up!⏰ 
 Sorry for closing your issue! 
 But it's more than a week since we haven't received anything from your side 😢 . 
 Come up with new ideas, create a new issue and make sure you finish it within a week! 🔥 
 All the best! 🚀 
 Happy Hacking! 💗
