### ISSUE TITLE
[New game]: Rock paper Scissors 

### ISSUE THREAD

**Issue by Prajwal0225** [kunjgit/GameZone#417]
### 🎮 Game Request

Game logic and basic description
Rock-Paper-Scissors is a classic hand game played between two players. The game involves choosing one of three possible options: rock, paper, or scissors. Each option has a specific hierarchy, where rock beats scissors, scissors beats paper, and paper beats rock. 

### Point down the features

Game points
The score keeps increasing by 1 as the player won. Decrement by 1 when a player loses to a computer
![rock paper seasor](https://github.com/kunjgit/GameZone/assets/103810119/7ccf0e31-3e57-47cc-84b3-7fa9702fe261)
.

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Prajwal0225 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @Prajwal0225! 
We are already having a similar game request in #340 👀 
Make sure you come up with a cool unique idea 😀 
 Waiting for your new game idea 💗.

**Comment by kunjgit** [comment]
Hey @Prajwal0225 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
