### ISSUE TITLE
[Enhancement]: Text is not visible on silver background

### ISSUE THREAD

**Issue by Garima-149** [kunjgit/GameZone#4171]
### Do you want to have the enhancement of existing game ? 😀 Describe yourself..

Game enhancement
![Screenshot (46)](https://github.com/kunjgit/GameZone/assets/143211271/1bc4562a-0952-40d1-a183-3f4410dac4d3)
Text color do not seem to be suitable for this silver background.

### Describe the solution you'd like

I would like to have some dark text color so,that it becomes visible  to users and will help in increasing user experience.Excited   
 to contribute in project.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Garima-149 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by Garima-149** [comment]
Could you please elaborate on self -assign issue @kunjgit

**Comment by Garima-149** [comment]
@kunjgit There is some first come first serve basis on assigning issue to anybody according guidelines of GSSoc'24. I have made the issue and without any reply, how could you assign that issue to somebody else. This is just unfair. I was asking for some clarification before somebody else commented upon.

**Comment by anuragnegi000** [comment]
@Garima-149 check #4168 i have created issue before you

**Comment by anuragnegi000** [comment]
Sorry for that I haven’t saw duplicate label on this repo

**Comment by kunjgit** [comment]
Hey @143divya ! , This issue is already assigned to @anuragnegi000. 💗 
 You can work on other issues 🚀 
 If there is anything wrong you can contact us on [Discord🕹️](https://discord.gg/fgwk4XZfxG)👀

**Comment by ishita-43** [comment]
Hey @anuragnegi000 you don't need to get same issue assigned to yourself you can continue on other one we are closing this issue.

**Comment by ishita-43** [comment]
Now I am closing this one as a duplicate

**Comment by kunjgit** [comment]
Hey @Garima-149 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
