### ISSUE TITLE
[New game]: Snake

### ISSUE THREAD

**Issue by 1911aditi** [kunjgit/GameZone#4174]
### 🎮 Game Request

Game logic and basic description:-This game will create a canvas where players control a snake using arrow keys. The snake grows longer as it eats food, and the game ends if the snake collides with itself or the canvas boundaries.

### Point down the features

Game points.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @1911aditi ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
