### ISSUE TITLE
[New game]: Quiz game

### ISSUE THREAD

**Issue by chaanakyaaM** [kunjgit/GameZone#4175]
### 🎮 Game Request

Game logic and basic description

Game Logic:
Quiz Data Setup: The quiz questions, options, and correct answers are stored in an array of objects named quizData.
Display Question: The displayQuestion() function dynamically generates HTML elements to display the current question and its options on the webpage. It also shuffles the order of the options each time a question is displayed.
Check Answer: The checkAnswer() function verifies if the user has selected an option and checks whether it matches the correct answer. It updates the score accordingly and moves to the next question.
Display Result: When all questions are answered, the displayResult() function hides the quiz area and displays the user's score along with an option to retry or show correct answers.
Retry Quiz: The retryQuiz() function resets the quiz by setting the current question back to the first question, resetting the score, and clearing any incorrect answers recorded.
Show Answer: The showAnswer() function hides the quiz area, displays the user's score, and reveals the correct answers to the questions that were answered incorrectly.

### Point down the features

Game points

Interactive User Interface: The game provides a visually appealing and interactive user interface where users can easily navigate through the quiz questions and select their answers.

Randomized Options: To enhance replayability and challenge, the order of options for each question is randomized every time the question is displayed, ensuring that users can't rely on memorizing the position of the correct answer.

Score Tracking: The game keeps track of the user's score as they progress through the quiz, providing immediate feedback on their performance.

Feedback on Incorrect Answers: If a user selects an incorrect answer, the game records it and provides feedback at the end of the quiz, showing the correct answer along with the user's choice.

Retry Option: Users have the option to retry the quiz after completing it, allowing them to attempt it again and improve their score.

Show Answers: Additionally, users can choose to view the correct answers for the questions they answered incorrectly, helping them learn from their mistakes and improve their knowledge.

Educational Value: The game serves as an educational tool, testing users' knowledge on various topics while providing an engaging and entertaining experience.

![Screenshot (80)](https://github.com/kunjgit/GameZone/assets/131477601/57820e9b-d515-4235-8603-3bce856c4311)

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @chaanakyaaM ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @chaanakyaaM! 
We are already having a similar game request in #4092 👀 
Make sure you come up with a cool unique idea 😀 
 Waiting for your new game idea 💗.

**Comment by kunjgit** [comment]
Hey @chaanakyaaM ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
