### ISSUE TITLE
[New game]: Word scribble game

### ISSUE THREAD

**Issue by codewithishu** [kunjgit/GameZone#4179]
### 🎮 Game Request

Game logic and basic description

Word Scribble is a word puzzle game where players rearrange a set of scrambled letters to form meaningful words. The game logic involves several key components to ensure an engaging and challenging experience for the player. Here's a detailed breakdown of the game logic for Word Scribble:

1. Game Initialization

Word List Selection: Choose a list of words appropriate for the game's difficulty level.
Random Word Selection: Randomly select a word from the list.
Scramble Letters: Shuffle the letters of the selected word to create the scrambled word presented to the player.

2. User Interface (UI)
Display Scrambled Word: Show the scrambled letters to the player.
Input Mechanism: Provide a way for the player to input their guesses (e.g., text input box, draggable letters).
Feedback System: Display feedback for correct or incorrect guesses.

3. Gameplay Loop
Start Game: Display the first scrambled word to the player.
Player Input: Allow the player to rearrange the letters or type their guess.

Check Guess:
Compare the player's guess to the original word.
If the guess is correct, move to the next word or end the game if it was the last word.
If the guess is incorrect, provide feedback and allow the player to try again.

### Point down the features

Game points

Scoring System
Score Calculation: Assign points based on the accuracy and speed of the player's guesses.
Correct guess on the first try: Maximum points.
Correct guess after multiple attempts: Fewer points.
Bonus points for completing the game quickly.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @codewithishu ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @codewithishu! 
We are already having a similar game request in #3949 👀 
Make sure you come up with a cool unique idea 😀 
 Waiting for your new game idea 💗.

**Comment by kunjgit** [comment]
Hey @codewithishu ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
