### ISSUE TITLE
[Enhancement]: City_Builder_Game complete renewal 

### ISSUE THREAD

**Issue by mohitgedar** [kunjgit/GameZone#4183]
## Game enhancement: City_Builder_Game
- Currently the game do nothing , you have fixed amount of credit  with which you just add some building , there is no start or end of the game , there is no win or lose

## Solution steps:
- I would like to enhance the game completely , building  should cost to create , and maintain , factories should produce money , 
- Add a pollution feature , where houses and factories create pollution and parks reduce the pollution
- Add a restart button to restart anytime you want 
- Final detailed result should be shown in the end which should also include the restart button
- CSS needs to be improved to make the game look better 
- Instructions should be added , how to play , what the game does  , what is its motive 
- Much more features can be added , as one starts working on it 

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @mohitgedar , You can't have another issue before completing the previous one 😀 
 you already have the following 1 open issues 👀 ! :

#4101

**Comment by kunjgit** [comment]
Hey @mohitgedar ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)
