### ISSUE TITLE
[New game]: Anagram Word Game

### ISSUE THREAD

**Issue by manishh12** [kunjgit/GameZone#4184]
### 🎮 Game Request

Setup
    - Select a list of words (word bank).
    - Randomly pick a word from the word bank.
    - Scramble the letters of the chosen word to create a puzzle.

End Game
    - Once the player guesses the word correctly or chooses to give up, reveal the correct word.
    - Optionally, move to the next word or end the game.

### Point down the features

1. **Gameplay**:
    - Display the scrambled word to the player.
    - Allow the player to guess the original word.
    - Provide an input method for the player to submit their guess.
    - Check if the guess is correct:
        - If correct, notify the player of their success.
        - If incorrect, allow the player to guess again or provide a hint option.
        
2. **Scoring (Optional)**:
    - Track the number of attempts taken to guess the word.
    - Award points based on the number of attempts (fewer attempts yield more points).

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @manishh12 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @manishh12 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
