### ISSUE TITLE
[New game]: SIMON GAME

### ISSUE THREAD

**Issue by Nih1tGupta** [kunjgit/GameZone#4189]
### 🎮 Game Request

Game logic and basic description
SIMPLE GAME MADE USING HTML,CSS AND JS

### Point down the features

Game points
![SG](https://github.com/kunjgit/GameZone/assets/119615342/14f49582-78fc-4481-b0ef-e56035a73c2b)

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Nih1tGupta ! , This issue is already assigned to @aamira0. 💗 
 You can work on other issues 🚀 
 If there is anything wrong you can contact us on [Discord🕹️](https://discord.gg/fgwk4XZfxG)👀

**Comment by kunjgit** [comment]
Hey @Nih1tGupta ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
