### ISSUE TITLE
[Bug]: 3D box game not available

### ISSUE THREAD

**Issue by anisharma07** [kunjgit/GameZone#4190]
### Give a brief about the bug ✍️

https://github.com/kunjgit/GameZone/assets/126901961/35f9f48b-64dd-48a3-816f-9f1f9d57f6a3

### What is the expected behavior? 🤔

The 3D box game should not appear at the dashboard, if it is not available

### Provide step by step information reproduce the bug 📄

1. finding out the game, check if available..
2. If not available, comment out the part making 3d box appear to dashboard

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @anisharma07 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @anisharma07 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
