### ISSUE TITLE
[New game]: DSA Quiz Game.

### ISSUE THREAD

**Issue by zalabhavy** [kunjgit/GameZone#4192]
### 🎮 Game Request

There are some problems related to DSA, and any one of the 10 will be randomly asked to the user. The user needs to answer.
I will use html ,css , js , json file.

### Point down the features

-A random selection of questions from a pool of 10. 
-Wrong/Right answer indicator. 
-Total score calculation. 
-A mix of DSA concepts, logical problems, and mathematical problems.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @zalabhavy ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @zalabhavy ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
