### ISSUE TITLE
[New game]: Wordling

### ISSUE THREAD

**Issue by codewithishu** [kunjgit/GameZone#4194]
### 🎮 Game Request

Game logic and basic description

Components of the Game

Word List: A predefined list of acceptable words that can be used as the secret word and guessed words.

Secret Word: A randomly selected word from the word list that players need to guess.

Guess Input: Players input their guesses, which must be checked against the word list to ensure they are valid words.

Feedback Mechanism: After each guess, provide feedback to indicate which letters are correct and in the correct position, which are correct but in the wrong position, and which are incorrect.

Win/Lose Conditions: Determine when the player has won or lost the game based on the number of guesses.

### Point down the features

Game points

Scoring System

Base Points: Each guess earns a base number of points. For example, each guess could start with a base value of 10 points.

Bonus Points: Additional points are awarded for correct letters and correct positions.

Correct letter in the correct position (Green): +5 points.

Correct letter in the wrong position (Yellow): +2 points.

Penalty Points: Deductions can be applied for incorrect guesses or using too many attempts.

Incorrect letter: -1 point.

Exceeding a certain number of attempts could result in a penalty (optional).

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @codewithishu ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @codewithishu ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
