### ISSUE TITLE
[New game]: Add Candy Crush Game

### ISSUE THREAD

**Issue by AsmitaMishra24** [kunjgit/GameZone#4199]
### 🎮 Game Request

Description:
I would suggest adding a Candy Crush-style game to our project. This game will involve matching three or more identical candies to clear them from the board, and score points.

Game Logic:
1. Board Setup:
- The game board will consist of a grid (e.g., 8x8) populated with various types of candies.
- Initial candy placement will be randomized, ensuring no starting matches are present.

2.Matching Mechanism:
- Players will be able to swap adjacent candies to form horizontal or vertical lines of three or more identical candies.
- Upon matching, the candies will be cleared from the board, and new candies will cascade from the top to fill the empty spaces.

3.Scoring:
- Points will be awarded for each match. Larger matches (e.g., four or five candies) will yield higher scores and special candies.
- Special candies will possess unique effects, such as clearing entire rows or columns.

4.Game Over Conditions:
- The game will end when the player exhausts all moves or fails to meet the level objectives.

### Point down the features

1.Matching and Clearing:
- Swap adjacent candies to form matches of three or more.
- Clear matched candies and cascade new candies from the top.

2.Special Candies and Combos:
- Create special candies (striped, wrapped, color bombs) with unique clearing effects.
- Combine special candies for enhanced effects.

3.Power-ups and Boosters:
- In-game power-ups (e.g., extra moves, shuffle board).
- Pre-level boosters for strategic advantages.

Screenshot: 
![sddefault](https://github.com/kunjgit/GameZone/assets/146121869/653faf3d-c336-4b44-b842-0607cd153252)

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @AsmitaMishra24 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @AsmitaMishra24 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
