### ISSUE TITLE
[New game]: Grab the carrot 

### ISSUE THREAD

**Issue by Aksshay88** [kunjgit/GameZone#4201]
### 🎮 Game Request

Game logic and basic description

it is basically a game like temple run where the character will be running and behind us there will be a monster chasing and we need jump the obstacle and other stuffs .

![image](https://github.com/kunjgit/GameZone/assets/119944779/55bef8c6-6d3e-4732-b48b-dfa4acc386cc)

### Point down the features

Game points

This will be warded to the user according to the user highscore 

pls do assign the GSSOC Label 

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Aksshay88 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @Aksshay88 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
