### ISSUE TITLE
[New game]: Kill the Bird 

### ISSUE THREAD

**Issue by Aksshay88** [kunjgit/GameZone#4203]
### 🎮 Game Request

Game logic and basic description
This game basically shoots the bird by and this gives the score and if the user shoots the bird that displays that I am dead 

### Point down the features

Game points

This basically generated points based on the user reflex 

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Aksshay88 , You can't have another issue before completing the previous one 😀 
 you already have the following 1 open issues 👀 ! :

#4201

**Comment by kunjgit** [comment]
Hey @Aksshay88 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by kunjgit** [comment]
Hey @Aksshay88 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by Aksshay88** [comment]
![image](https://github.com/kunjgit/GameZone/assets/119944779/a8926226-66e0-4d31-9555-17f4295de668)


this is the SS
