### ISSUE TITLE
Hidden Object Game

### ISSUE THREAD

**Issue by mahek0620** [kunjgit/GameZone#4206]
### 🎮 Game Request

Hidden Object Game: A game where players find hidden objects in a picture or scene.

### Point down the features

Hidden Object Games feature visually detailed scenes where players find specific objects within, often with levels, hints, time limits, scoring, themed storylines, and interactive elements.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @mahek0620! 🙂 
 It seems like you are not following proper guidelines !! 👀 
 Read documentation properly !!🙏 
 If you have any queries reach out to us on [Discord🕹️](https://discord.gg/fgwk4XZfxG) .

**Comment by kunjgit** [comment]
Hey @mahek0620 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
