### ISSUE TITLE
[New game]: Russian Roulette

### ISSUE THREAD

**Issue by Harshitmishra001** [kunjgit/GameZone#4208]
### Game logic and basic description

- A simple Russian Roulette Game Where you test your luck by shooting bullets by Clicking a Button.
- The Gun has a 33% chance of shooting and if shot a shooting sound plays and you die and the death counter increases.

### Game points

- A gun
- A button that when clicked shoots gun
- 33% chance of gun shooting
- when shot you die and death counter increases

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Harshitmishra001 , You can't have another issue before completing the previous one 😀 
 you already have the following 1 open issues 👀 ! :

#4109

**Comment by kunjgit** [comment]
Hey @Harshitmishra001 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by kunjgit** [comment]
Hey @Harshitmishra001 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)
