### ISSUE TITLE
[New game]: Full chess game with multiplayer and AI support.

### ISSUE THREAD

**Issue by sagnik3788** [kunjgit/GameZone#421]
### 🎮 Game Request

Game logic and basic description:-

Backend

The backend of the chess game is responsible for the game logic. This includes things like:

Validating moves
Checking for checkmate
Storing the game state
Communicating with the frontend
The backend can be implemented in Node js and  mongo db .

Frontend

The frontend of the chess game is responsible for the user interface. This includes things like:

Displaying the game board
Handling user input
Communicating with the backend
The frontend can be implemented in HTML, CSS, and JavaScript.

Communication between backend and frontend

The backend and frontend communicate with each other using a REST API. This allows the frontend to send requests to the backend, and the backend to send responses to the frontend.

The REST API can be implemented in  javascript.

### Point down the features

Game points:-
Game points are calculated by adding up the value of all the pieces that a player has captured. The value of each piece is as follows:

King: 1000 points
Queen: 900 points
Rook: 500 points
Knight: 300 points
Bishop: 300 points
Pawn: 100 points
For example, if a player has captured a queen and a rook, they would have 1400 game points.

Game points can be a helpful way to assess the progress of a chess game. If one player has significantly more game points than the other, it is likely that they will win the game. However, it is important to remember that game points are not the only factor that determines the outcome of a chess game. Skill, strategy, and luck all play a role as well.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @sagnik3788 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hello @sagnik3788, Time's Uppp!⏰ 
 Sorry for closing your issue! 
 But it's more than a week since we haven't received anything from your side 😢 . 
 Come up with new ideas, create a new issue and make sure you finish it within a week! 🔥 
 All the best! 🚀 
 Happy Hacking! 💗

**Comment by kunjgit** [comment]
Hey @sagnik3788 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
