### ISSUE TITLE
[New game]: Snake-with-GPT4 

### ISSUE THREAD

**Issue by Maheshwari-Love** [kunjgit/GameZone#4210]
### 🎮 Game Request

I want to add New game in this project...

### Point down the features

1.Click any key to get past the title screen.
2.Select a theme.
3.Select a difficulty.
4.Play.
5.Press Esc at anytime to quit.
6.Game Over.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Maheshwari-Love ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by Maheshwari-Love** [comment]
@kunjgit Please assign this to me to introduce new game in this project...

**Comment by kunjgit** [comment]
Hey @Maheshwari-Love ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
