### ISSUE TITLE
[New game]: Bubble'z Popper

### ISSUE THREAD

**Issue by Chandu6702** [kunjgit/GameZone#4212]
### 🎮 Game Request

Pop the Bubbles

A simple bubble-popping game made using HTML, CSS, and Javascript.
By moving the cursor onto the bubbles they blast.If you miss the 10 chances the game will end.

https://github.com/kunjgit/GameZone/assets/125206920/af0a669d-1e5e-40b5-bdd4-e32745c0a399

 

### Point down the features

-Points increase based on number of bubbles blasted.
-Sounds are added for good user experiences.
-Works on mobile too.the 

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Chandu6702 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @Chandu6702 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
