### ISSUE TITLE
[New game]: Playing With Probability

### ISSUE THREAD

**Issue by Sara1428** [kunjgit/GameZone#4216]
### 🎮 Game Request

Game logic and basic description :-
Given two dice, the user can enter any sum and calculate the probability of getting that as the sum of the numbers appearing on the top of the two dice. Interestingly user can also select the number of trials to very large and very less number of trials and extract  intuition from it.

### Point down the features

Probability Calculation in a gamefic manner

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Sara1428 , You can't have another issue before completing the previous one 😀 
 you already have the following 1 open issues 👀 ! :

#4149

**Comment by kunjgit** [comment]
Hey @Sara1428 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by kunjgit** [comment]
Hey @Sara1428 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by Sara1428** [comment]
> Hey @Sara1428 , You can't have another issue before completing the previous one 😀 you already have the following 1 open issues 👀 ! :
> 
> #4149

I already made the pull request for this issue
