### ISSUE TITLE
[New game]: Mechanica

### ISSUE THREAD

**Issue by Winter262005** [kunjgit/GameZone#4217]
### 🎮 Game Request

Game logic and basic description

Mechanica is a 2D Shooter game which runs on JavaScript.

### Point down the features

Game points

Shoot down the enemies to get the highest score and survive the assault.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Winter262005 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
