### ISSUE TITLE
[New game]: Adding a bouncing ball game

### ISSUE THREAD

**Issue by YadlaMani** [kunjgit/GameZone#4218]
### 🎮 Game Request

Game logic and basic description
This HTML code represents a Bouncing Ball Game that you can play using the left, right, and up arrow keys. The game canvas displays a map created with customizable and scriptable tiles, each having various properties like color, solidity, bounce, friction, gravity, and more.

### Point down the features

Game points
Players can control a ball character on the map using the left, right, and up arrow keys to move and interact with the different tiles. For example, some tiles are solid, and the ball can bounce off them, while others trigger scripts when touched.

Uploading Recording 2024-06-04 214855.mp4…

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by YadlaMani** [comment]
/ assign

**Comment by YadlaMani** [comment]
/ assign

**Comment by kunjgit** [comment]
Hey @YadlaMani ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
