### ISSUE TITLE
[New game]: Emoji Enigma

### ISSUE THREAD

**Issue by Roshr2211** [kunjgit/GameZone#4222]
### 🎮 Game Request

# Game logic and basic description
Emoji Enigma is an engaging memory card game that challenges players to match pairs of emojis hidden behind cards. The game board consists of a grid of cards, each containing a unique emoji. Players must remember the location of the emojis as they flip cards to uncover matches. The objective is to clear the board by matching all pairs within the shortest time possible.

# How to Play:

Click on any facedown card to reveal the emoji underneath.
Click on a second card to see if it matches the first.
Match all pairs of emojis to complete the game.
Enter your username to record your score on the leaderboard

### Point down the features

# Game points
- Memory Challenge: Test your memory skills by remembering the positions of emojis as you flip cards.
- Timer: Track your progress and challenge yourself to beat your best time.
- Leaderboard: Compete with friends and other players by achieving top scores on the leaderboard.
- Dynamic Gameplay: Each playthrough shuffles the emojis, providing a fresh challenge every time.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Roshr2211 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @Roshr2211 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
