### ISSUE TITLE
[New game]: 8 PUZZLE

### ISSUE THREAD

**Issue by manikumarreddyu** [kunjgit/GameZone#4223]
### 🎮 Game Request

Game logic and basic description
Game Request:
 8 Puzzle Game
 
Description

The 8 Puzzle Game is a classic sliding puzzle game developed in JavaScript. The game consists of a 3x3 grid with eight numbered tiles and one empty space. The objective is to arrange the tiles in numerical order by sliding them into the empty space.

Features:

2D Graphics: Simple and clean 2D interface.
Player Controls: Click or tap to move tiles into the empty space.
Randomized Start: Tiles start in a random order to ensure each game is unique.
Tile Sliding: Smooth sliding animations for tiles.
Move Counter: Tracks the number of moves made by the player.
Timer: Optional timer to track how long it takes to solve the puzzle.
Hint System: Provides hints or solutions if the player gets stuck.
Reset and Shuffle: Options to reset the puzzle or shuffle for a new challenge.
Sound Effects: Simple sound effects for tile movements.
Victory Screen: Celebratory message or animation upon solving the puzzle.

### Point down the features

Game points

Objective: Arrange the tiles in numerical order (1-8) with the empty space in the bottom-right corner.
Moves: Use the minimum number of moves to solve the puzzle.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @manikumarreddyu ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @manikumarreddyu ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
