### ISSUE TITLE
[New game]: Blackjack

### ISSUE THREAD

**Issue by manikumarreddyu** [kunjgit/GameZone#4224]
### 🎮 Game Request

Game logic and basic description

Description
Blackjack is a classic card game developed in JavaScript. The objective is to have a hand value as close to 21 as possible without exceeding it. Players compete against the dealer, aiming to have a higher hand value than the dealer without busting. The game includes options for hitting, standing, splitting, and doubling down. The dealer follows a set of predefined rules for drawing cards.

### Point down the features

Game points
Objective: Achieve a hand value closer to 21 than the dealer without exceeding 21.
Strategies: Utilize strategic decisions like hitting, standing, splitting, and doubling down to maximize chances of winning.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @manikumarreddyu , You can't have another issue before completing the previous one 😀 
 you already have the following 1 open issues 👀 ! :

#4223

**Comment by kunjgit** [comment]
Hey @manikumarreddyu ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by kunjgit** [comment]
Hey @manikumarreddyu ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)
