### ISSUE TITLE
[New game]: Quantum Maze Game

### ISSUE THREAD

**Issue by Maheshwari-Love** [kunjgit/GameZone#4227]
### 🎮 Game Request

"Quantum Maze" that involves navigating through a maze with quantum mechanics principles, including superposition and entanglement.

### Point down the features

Game points
Gameplay Features:

Quantum Walls: Walls that can exist in multiple states simultaneously. Players must collapse these walls by observing them to determine if they are passable.
Entangled Paths: Certain paths are entangled, meaning if you choose one path, the corresponding entangled path changes as well.
Superposition Gates: Gates that require the player to be in two places at once, achieved by splitting the player's state.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Maheshwari-Love , You can't have another issue before completing the previous one 😀 
 you already have the following 1 open issues 👀 ! :

#4210

**Comment by kunjgit** [comment]
Hey @Maheshwari-Love ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by kunjgit** [comment]
Hey @Maheshwari-Love ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @Maheshwari-Love! 
We are already having a similar game request in #4162 👀 
Make sure you come up with a cool unique idea 😀 
 Waiting for your new game idea 💗.
