### ISSUE TITLE
[New game]: 3D-Box

### ISSUE THREAD

**Issue by AnmolChauhan123** [kunjgit/GameZone#423]
### 🎮 Game Request

There will be 2 types of 3d boxes of color red and green. Red is for danger and green will be our moving block. So we have to avoid all the red boxes and keep the green box on the platform and go as far as we can... It's an amazing game and will really be fun to make. It's gonna use HTML, CSS, JavaScript and Three.js Library.

Please assign this issue to me under the tag GSSoC'23 and I will try my best to close this issue and create a PR...

### Point down the features

The player can save his box by clicking left, right and can also use up and down arrow to move our box forward and backward respectively. The user can also use mouse to see the platform from the different angles so that he can get a 3D experience.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @AnmolChauhan123 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hello @AnmolChauhan123, Time's Uppp!⏰ 
 Sorry for closing your issue! 
 But it's more than a week since we haven't received anything from your side 😢 . 
 Come up with new ideas, create a new issue and make sure you finish it within a week! 🔥 
 All the best! 🚀 
 Happy Hacking! 💗

**Comment by kunjgit** [comment]
Hey @AnmolChauhan123 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
