### ISSUE TITLE
[New game]: Circuit Scape

### ISSUE THREAD

**Issue by patelkiran185** [kunjgit/GameZone#4231]
### 🎮 Game Request

Game logic and basic description
It is a fun and relaxing game.Twist and turn lines to connect into loops,
 each lighting up a lamp.Light up all the lines to complete the level. 
 Similar to this ....
![256x256bb](https://github.com/kunjgit/GameZone/assets/138752385/58bdd3f3-b6c6-47ec-8f39-5a1f01d6488e)

### Point down the features

Game points
Calm and minimalist Design
Relaxing Soundtracks
Visual rewards and hint system

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @patelkiran185 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @patelkiran185 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
