### ISSUE TITLE
[New game]:  🎮 Chess Game with compute Request

### ISSUE THREAD

**Issue by thevijayshankersharma** [kunjgit/GameZone#4233]
### 🎮 Game Request

Description:
We propose the development of an AI-powered chess game that offers an engaging and challenging experience to players of all levels. The game will leverage advanced algorithms to provide intelligent gameplay while also offering a user-friendly interface for an immersive gaming experience.

Game Logic:
The AI chess game will follow standard chess rules, allowing players to enjoy the classic game in a digital format. The game will include features such as move validation, checkmate detection, and various difficulty levels to accommodate players from beginners to advanced.

### Point down the features

Intelligent AI Opponent: The game will feature an AI opponent with varying levels of difficulty, from beginner to grandmaster, to provide a challenging experience for players of all skill levels.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @thevijayshankersharma ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by thevijayshankersharma** [comment]
> /assign

I have already raised an PR

**Comment by kunjgit** [comment]
Hey @thevijayshankersharma ! , This issue is already assigned to @dnyandeepchute. 💗 
 You can work on other issues 🚀 
 If there is anything wrong you can contact us on [Discord🕹️](https://discord.gg/fgwk4XZfxG)👀

**Comment by thevijayshankersharma** [comment]
@ishita-43 someone else got assigned.

**Comment by ishita-43** [comment]
The issues are assigned on first come first serve basis. if the first person will not be able to complete pr another will get the issue. And also always make sure if you are intended to work on created issue then assign it for yourself before other try to do that!!

**Comment by thevijayshankersharma** [comment]
> The issues are assigned on first come first serve basis. if the first person will not be able to complete pr another will get the issue. And also always make sure if you are intended to work on created issue then assign it for yourself before other try to do that!!

Thank you. Could you check my PR related to this.

**Comment by kunjgit** [comment]
Hey @thevijayshankersharma ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
