### ISSUE TITLE
[Bug]: text is not visible

### ISSUE THREAD

**Issue by dnyandeepchute** [kunjgit/GameZone#4236]
### Give a brief about the bug ✍️

text is not visible in light mode
![Screenshot 2024-06-05 142217](https://github.com/kunjgit/GameZone/assets/158272735/d55bf444-c6cf-45bb-a665-f638e51d71ba)
![Screenshot 2024-06-05 142238](https://github.com/kunjgit/GameZone/assets/158272735/7780207b-5c0e-40a6-a33e-c70c3a9bd0ed)

### What is the expected behavior? 🤔

text should be visible properly.

### Provide step by step information reproduce the bug 📄

by making the text color visible in both the mode

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @dnyandeepchute ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by dnyandeepchute** [comment]
hey @kunjgit , please assign this to me,  thank you.

**Comment by dnyandeepchute** [comment]
@kunjgit please add the level label

**Comment by dnyandeepchute** [comment]
@kunjgit please add the level label, i would like to work on this

**Comment by kunjgit** [comment]
Hey @dnyandeepchute ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
