### ISSUE TITLE
[Enhancement]: Rock Paper Scissors game

### ISSUE THREAD

**Issue by dnyandeepchute** [kunjgit/GameZone#4238]
### Do you want to have the enhancement of existing game ? 😀 Describe yourself..

UI can be better
problems in current game-
small logo for Rock Paper and Scissors
automatically selecting the choice
buttons are not proper due to color
bad front end

### Describe the solution you'd like

https://dnyandeepchute.github.io/rockPaperScissorsGame/

you can refer this

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @dnyandeepchute , You can't have another issue before completing the previous one 😀 
 you already have the following 1 open issues 👀 ! :

#4236

**Comment by kunjgit** [comment]
Hey @dnyandeepchute ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by kunjgit** [comment]
Hey @dnyandeepchute ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by dnyandeepchute** [comment]
hey @kunjgit , please assign this to me, thank you.
