### ISSUE TITLE
[New game]: Bingo Game

### ISSUE THREAD

**Issue by Avdhesh-Varshney** [kunjgit/GameZone#424]
### 🎮 Game Request

Game logic and basic description

1. This is game is go for any number for players.
2. There are 25 numbers will keep in the game.
3. In one move, one player tell which number will he/she want to cut, that number will also be cut down by each and every member of the game.

### Point down the features

Game points

0. In this game, Winner will decide when the winner one will cut the all the letters of the "BINGO".

1. Letter of the BINGO can be cut when a straight line passing through those 5 numbers which are cut marked by the members.
2. One cut mark number can also be part of the other straight line.
3. This game will give user a best experience.
4. Result will be declared and stored for each and every rounds till the user is playing the game on the website.

So, Please assign this game task to me, please !

### Select program in which you are contributing

GSSoC'23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Avdhesh-Varshney ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by Avdhesh-Varshney** [comment]
Please assign this task to me. Please !

**Comment by Gun2902** [comment]
can u assign me this isssue

**Comment by whiteknight16** [comment]
@Avdhesh-Varshney write / assign to  get assigned with issue don't place space between / and assign

**Comment by Avdhesh-Varshney** [comment]
@kunjgit please assign this task to me to contribute under GSSoC'23

**Comment by Avdhesh-Varshney** [comment]
@kunjgit /assign this task to me

**Comment by kunjgit** [comment]
Hey @Avdhesh-Varshney ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
