### ISSUE TITLE
[Enhancement]: In Tilting Maze adding a restart button and enhancing the text size and style

### ISSUE THREAD

**Issue by jaydeep099** [kunjgit/GameZone#4241]
### Do you want to have the enhancement of existing game ? 😀 Describe yourself..

Game enhancement
In Tilting maze , There is no restart button and text are small with no style.
![Screenshot 2024-06-05 155106](https://github.com/kunjgit/GameZone/assets/148114163/2a9c4dd5-0954-4ce4-b8ad-9465836d11d7)

### Describe the solution you'd like

Solution steps
I will add restart button and enchance the text size and style.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @jaydeep099 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @jaydeep099 ! , This issue is already assigned to @dnyandeepchute. 💗 
 You can work on other issues 🚀 
 If there is anything wrong you can contact us on [Discord🕹️](https://discord.gg/fgwk4XZfxG)👀

**Comment by jaydeep099** [comment]
@kunjgit i have created pull request i just forgot to write /assign

**Comment by kunjgit** [comment]
Hey @jaydeep099 ! , This issue is already assigned to @dnyandeepchute. 💗 
 You can work on other issues 🚀 
 If there is anything wrong you can contact us on [Discord🕹️](https://discord.gg/fgwk4XZfxG)👀

**Comment by kunjgit** [comment]
Hey @jaydeep099 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
