### ISSUE TITLE
[New game]: Word Builder Game

### ISSUE THREAD

**Issue by its-kritika** [kunjgit/GameZone#4244]
### 🎮 Game Request

It is a game where players enter words using letters displayed on the screen. The game has a timer set to 60 seconds. After the time runs out, the game ends, and the player's score (based on number of letters each words contains) is displayed.

### Point down the features

- **Letters :** The game will contain A-Z letters and players have to create new words to score points.
- **Score :** Score will be calculated based on length of words created.
- **Limited Time :** To make the game more challenging, it will have a time limit within which players must create as many words as possible.
- **Highest Score :** Users can keep track of their highest score.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @its-kritika ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @its-kritika! 
We are already having a similar game request in #4184 👀 
Make sure you come up with a cool unique idea 😀 
 Waiting for your new game idea 💗.

**Comment by kunjgit** [comment]
Hey @its-kritika ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
