### ISSUE TITLE
[New game]: Word Builder Game

### ISSUE THREAD

**Issue by its-kritika** [kunjgit/GameZone#4245]
### 🎮 Game Request
It is a game where players enter words using letters displayed on the screen. The game has a timer set to 60 seconds. After the time runs out, the game ends, and the player's score (based on number of letters each words contains) is displayed. It is different from anagram word game as everytime players will have same set of letters and will have to create new words of larger length to score more points. It is a time based game.

Similar to this SS
![Screenshot (416)](https://github.com/kunjgit/GameZone/assets/144522556/4edc5a34-c65b-4d6d-8dfd-d66e17458caf)

### Point down the features

- **Letters :** The game will contain A-Z letters and players have to create new words to score points.
- **Score :** Score will be calculated based on length of words created.
- **Limited Time :** To make the game more challenging, it will have a time limit within which players must create as many words as possible.
- **Word Validation:** The game verifies the validity of the words submitted by players against a dictionary or predefined word list. Invalid words are not counted towards the player's score.
- **Highest Score :** Users can keep track of their highest score.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @its-kritika! 
We are already having a similar game request in #4233 👀 
Make sure you come up with a cool unique idea 😀 
 Waiting for your new game idea 💗.

**Comment by kunjgit** [comment]
Hey @its-kritika ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
