### ISSUE TITLE
[Documentation Bug]: Broken Link in Documentation

### ISSUE THREAD

**Issue by GUNJESH843** [kunjgit/GameZone#4248]
### Describe the bug ✍️

To fix the broken link, I plan to update the URL to the correct one for the "Hit_the_hamster" game.
![Screenshot 2024-06-05 194441](https://github.com/kunjgit/GameZone/assets/109446288/f1447905-123c-4e69-a9fc-c547965525b5)

I am contributing to the GameZone program.

Code of Conduct: By submitting this issue, you agree to follow our CODE OF CONDUCT.

[✅] I follow the CONTRIBUTING GUIDELINE of this project.

### Provide step by step information reproduce the bug 📄

Step by step information to reproduce the bug:

Navigate to the documentation section of the GameZone repository.
Look for the link to the "Hit_the_hamster" game.
Click on the link and observe that it leads to a broken URL.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @GUNJESH843 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by GUNJESH843** [comment]
assign

**Comment by kunjgit** [comment]
Hey @143divya ! , This issue is already assigned to @GUNJESH843. 💗 
 You can work on other issues 🚀 
 If there is anything wrong you can contact us on [Discord🕹️](https://discord.gg/fgwk4XZfxG)👀

**Comment by GUNJESH843** [comment]
hey @kunjgit I have submitted a PR for the same please review it [here](https://github.com/kunjgit/GameZone/pull/4253)!

Thank you.

**Comment by kunjgit** [comment]
Hey @GUNJESH843 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
