### ISSUE TITLE
[New game]: Sorting Visualizer

### ISSUE THREAD

**Issue by AnmolChauhan123** [kunjgit/GameZone#425]
### 🎮 Game Request

Sorting Visualizer is a frontend project which includes HTML, CSS, JavaScript and contains many algorithmic ways via which user can show the sorting procedure.

### Point down the features

There is going to be a landing page that will take you to the main page where the sorting will take place. There is going to be bars which describe the range of elements on which we will apply the sorting on, there will be dropdown menus for both selecting the Algorithm for sorting and also the speed in which the user can define the speed of sorting. There is also going to be a page on which he/she can learn about the sorting techniques.

I expect that this project is really great and helps the user to not just cram the sorting algorithms but see them in action of what is going on actually and there is also a speed button by which user can just enjoy the sorting visualization on it's own pace.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @AnmolChauhan123 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hello @AnmolChauhan123, Time's Uppp!⏰ 
 Sorry for closing your issue! 
 But it's more than a week since we haven't received anything from your side 😢 . 
 Come up with new ideas, create a new issue and make sure you finish it within a week! 🔥 
 All the best! 🚀 
 Happy Hacking! 💗

**Comment by kunjgit** [comment]
Hey @AnmolChauhan123 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
