### ISSUE TITLE
[New game]: Tile Connect Game

### ISSUE THREAD

**Issue by Archiesachin** [kunjgit/GameZone#4250]
### 🎮 Game Request

Player against Computer Game. 
The user will select one tile then the computer. The player which has maximum tiles wins. 

### Point down the features

![Screenshot (1055)](https://github.com/kunjgit/GameZone/assets/103347688/48d44b89-ac1b-48b0-892b-d6a0ba06be12)

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Archiesachin , You can't have another issue before completing the previous one 😀 
 you already have the following 1 open issues 👀 ! :

#3994

**Comment by kunjgit** [comment]
Hey @Archiesachin ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by kunjgit** [comment]
Hey @Archiesachin ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)
