### ISSUE TITLE
Light Mode text color and effects

### ISSUE THREAD

**Issue by riya-rjha** [kunjgit/GameZone#4251]
### Give a brief about the bug ✍️

The text color is white in the white mode also which is not at all looking readable. Plus the effects can be changed on hover in light mode. 

### What is the expected behavior? 🤔

In light mode, the text must be in black color and the hover effects should be properly visible. Plus the headings are also in white color which is making the site very unreadable. 

### Provide step by step information reproduce the bug 📄

Here's the screenshot attached where I would like to work upon :

![Screenshot (64)](https://github.com/kunjgit/GameZone/assets/112813772/5bee0a24-7fe8-493e-bb2b-2840d62b1818)

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @riya-rjha ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @riya-rjha! 🙂 
 It seems like you are not following proper guidelines !! 👀 
 Read documentation properly !!🙏 
 If you have any queries reach out to us on [Discord🕹️](https://discord.gg/fgwk4XZfxG) .

**Comment by kunjgit** [comment]
Hey @riya-rjha ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
