### ISSUE TITLE
[Bug]: Image for tic tac toe game and others not visible

### ISSUE THREAD

**Issue by riya-rjha** [kunjgit/GameZone#4252]
### Give a brief about the bug ✍️

Description: 

On loading the website the images do not load for games, particularly the tic-tac-toe game & others beside.

### What is the expected behavior? 🤔

Description:

The images should be visible for every game.

### Provide step by step information reproduce the bug 📄

Description:

I would want to add images for every game. Plus if required, I would willingly add images for all the games which are not loading in the website.

Screenshot: 
![Screenshot (62)](https://github.com/kunjgit/GameZone/assets/112813772/032073f2-7aaf-4755-8a90-5966a6c3b97a)

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hello @riya-rjha, Time's up!⏰ 
 Sorry for closing your issue! 
 But it's more than a week since we haven't received anything from your side 😢 . 
 Come up with new ideas, create a new issue and make sure you finish it within a week! 🔥 
 All the best! 🚀 
 Happy Hacking! 💗
