### ISSUE TITLE
[New game]: text not visible

### ISSUE THREAD

**Issue by dnyandeepchute** [kunjgit/GameZone#4259]
### 🎮 Game Request

text is not visible in light mode

### Point down the features

![Screenshot 2024-06-05 230129](https://github.com/kunjgit/GameZone/assets/158272735/577d8b8b-3f8f-4f79-90cf-ac50dfc09bd9)
![Screenshot 2024-06-05 230223](https://github.com/kunjgit/GameZone/assets/158272735/34c070cd-ff6d-4dd2-b31c-23ea16ee67dd)

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @dnyandeepchute ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by Vijayaa21** [comment]
I want to Contribute to this issue. Pls assign me,

**Comment by kunjgit** [comment]
Hey @dnyandeepchute ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
