### ISSUE TITLE
[Bug]: Doraemon_Jump Game No need of Reset button

### ISSUE THREAD

**Issue by jaydeep099** [kunjgit/GameZone#4260]
### Give a brief about the bug ✍️

Description
In Doremon Jump There is reset button which is not needed as to play again and on pressing it , does not work also.
![Screenshot 2024-06-05 231318](https://github.com/kunjgit/GameZone/assets/148114163/ea531e22-377c-4d84-8a76-53bb5b33f72f)

### What is the expected behavior? 🤔

Description
There should be no reset button 

### Provide step by step information reproduce the bug 📄

Description
Remove the reset button

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @jaydeep099 , You can't have another issue before completing the previous one 😀 
 you already have the following 1 open issues 👀 ! :

#4241

**Comment by kunjgit** [comment]
Hey @jaydeep099 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by kunjgit** [comment]
Hey @jaydeep099 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by jaydeep099** [comment]
@kunjgit Please check the pull request
