### ISSUE TITLE
[Bug]: Link to GitHub & Favourite icon placement not responsive for every game

### ISSUE THREAD

**Issue by riya-rjha** [kunjgit/GameZone#4266]
### Give a brief about the bug ✍️

On the main page of the website, there are two links with their icons, one for the github repo of the game & the other one is to add to favourites. According to the text size or no of letters in the game, the icons get shifted in a way which is not at all responsive. 

### What is the expected behavior? 🤔

I would want to make the icons responsive enough so that whatever text & the amount of text is added, they get placed in a proper position.

### Provide step by step information reproduce the bug 📄

Here's the problem screenshot: 

![Screenshot (76)](https://github.com/kunjgit/GameZone/assets/112813772/67a87056-1192-4266-9f40-ecc83b6bd290)

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @riya-rjha , You can't have another issue before completing the previous one 😀 
 you already have the following 1 open issues 👀 ! :

#4252

**Comment by kunjgit** [comment]
Hey @riya-rjha ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by kunjgit** [comment]
Hey @riya-rjha ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by riya-rjha** [comment]
Now that this issue #4252 has been completed from my end and the PR has been submitted for review, can you reopen this issue so that I can work on it?
