### ISSUE TITLE
Morse code generator

### ISSUE THREAD

**Issue by Saipradyumnagoud** [kunjgit/GameZone#4268]
### 🎮 Game Request

**Game Logic:**

The Morse Code generator is a tool that translates regular text input into Morse Code, a method of encoding text characters using sequences of dots and dashes.

1. **Input Text:**
   - The user inputs text into a text field or textarea.

2. **Conversion:**
   - The generator converts each character of the input text into its corresponding Morse Code representation.
   - Morse Code representations are typically composed of dots (.) and dashes (-), where dots represent short signals and dashes represent long signals.

3. **Output Display:**
   - The generator displays the converted Morse Code either in a separate textarea or alongside the input text.

### Point down the features

**Features of the Generator:**

1. **Character Translation:**
   - The generator translates each character of the input text into its Morse Code equivalent.
   - It includes translations for letters (A-Z), numbers (0-9), and common punctuation marks.

2. **Whitespace Handling:**
   - The generator properly handles whitespace characters (spaces) between words in the input text.
   - It may use a specific Morse Code representation for spaces to maintain clarity between words.

3. **Case Insensitivity:**
   - The generator may be case insensitive, allowing both uppercase and lowercase characters in the input text.
   - It converts all characters to a consistent case before translating them into Morse Code.

4. **Interactive User Interface:**
   - The generator provides a user-friendly interface for inputting text and viewing the corresponding Morse Code output.
   - It may include features such as clear buttons to reset the input and output fields, as well as copy buttons to easily copy the Morse Code output.

5. **Real-Time Conversion:**
   - The generator may perform real-time conversion, updating the Morse Code output as the user types or modifies the input text.
   - This feature provides immediate feedback to the user and enhances the interactive experience.

6. **Error Handling:**
   - The generator handles errors gracefully, such as invalid characters in the input text that cannot be translated into Morse Code.
   - It may display error messages to alert the user and guide them in correcting the input.

7. **Customization Options:**
   - The generator may offer customization options for the Morse Code output, such as adjusting the speed of dots and dashes or choosing different visual representations for dots and dashes.

8. **Accessibility:**
   - The generator ensures accessibility for all users, including those with visual impairments, by providing alternative text descriptions or audio feedback for Morse Code output.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Saipradyumnagoud ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @Saipradyumnagoud! 🙂 
 It seems like you are not following proper guidelines !! 👀 
 Read documentation properly !!🙏 
 If you have any queries reach out to us on [Discord🕹️](https://discord.gg/fgwk4XZfxG) .

**Comment by kunjgit** [comment]
Hey @Saipradyumnagoud ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
