### ISSUE TITLE
[Bug]: Title and game fonts are not visible in light mode

### ISSUE THREAD

**Issue by ayush-848** [kunjgit/GameZone#4272]
### Give a brief about the bug ✍️

Description
In light mode the texts are not clearly visible

### What is the expected behavior? 🤔

Description
They must be readable

### Provide step by step information reproduce the bug 📄

![image](https://github.com/kunjgit/GameZone/assets/126975547/a436a20e-41eb-40f0-9d68-6174e4614422)

![image](https://github.com/kunjgit/GameZone/assets/126975547/58ae1f70-06e4-4213-b093-00b6b258e8d4)

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @ayush-848 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by ayush-848** [comment]
@kunjgit Light theme background changes are also required
I would like your suggestion
