### ISSUE TITLE
[Enhancement]: To design the footer properly

### ISSUE THREAD

**Issue by ayush-848** [kunjgit/GameZone#4273]
### Do you want to have the enhancement of existing game ? 😀 Describe yourself..

I will add "About", "Contribute here", "Contact", Subscribe to newsletter etc

### Describe the solution you'd like

![image](https://github.com/kunjgit/GameZone/assets/126975547/e449cc94-867d-4db2-8297-3d1b12e9214f)

I will design the footer and add required links

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @ayush-848 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by ShahHetviIT** [comment]
I'm excited about taking the lead on the GameZone project. With my proficiency in HTML, CSS, JavaScript, and ReactJS, I'm confident in my ability to drive significant progress on this initiative. Please assign me to this project via GSSOC.

**Comment by ayush-848** [comment]
@kunjgit I have requested a PR, please check

**Comment by kunjgit** [comment]
Hey @ayush-848 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
