### ISSUE TITLE
[New game]: Yahtzee

### ISSUE THREAD

**Issue by pankhuri92** [kunjgit/GameZone#4276]
### 🎮 Game Request
To add the game of Yahtzee. 
The game consists of thirteen rounds.
Each round begins with the rolling of five dice.
The player is allowed two more rolls within the round.   The player can choose certain dice to hold their values during a reroll.  

### Point down the features
Roll dice for scoring combinations, and get the highest total score.

![Yahtzee5](https://github.com/kunjgit/GameZone/assets/138357063/2f994c26-0a66-4ff5-8654-f4ca95ee65cc)

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @pankhuri92 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @pankhuri92 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
