### ISSUE TITLE
[Enhancement]: Changing the ui of "Memory Game"

### ISSUE THREAD

**Issue by divyalaldinani** [kunjgit/GameZone#4278]
### Do you want to have the enhancement of existing game ? 😀 Describe yourself..

Game enhancement
![image](https://github.com/kunjgit/GameZone/assets/82147067/03b3d754-fb8b-4fb5-9eb6-eb05c4d8e56d)
The UI of this page including adding a relevant background, colors, instructions box etc.

### Describe the solution you'd like

a new relevant bg should be added and color palette should be updated etc.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @divyalaldinani ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @divyalaldinani ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
