### ISSUE TITLE
[Enhancement]: 

### ISSUE THREAD

**Issue by Rhythm408** [kunjgit/GameZone#428]
### Is your enhancement request related to a problem? Please describe.➕

Game enhancement of Snake Game

### Describe the solution you'd like

Improve the UI of Snake Game.
Add a guidelines page for rules.
Add features like score and time.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hello @Rhythm408, Time's Uppp!⏰ 
 Sorry for closing your issue! 
 But it's more than a week since we haven't received anything from your side 😢 . 
 Come up with new ideas, create a new issue and make sure you finish it within a week! 🔥 
 All the best! 🚀 
 Happy Hacking! 💗

**Comment by kunjgit** [comment]
Hey @Rhythm408 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
