### ISSUE TITLE
[New game]: Go Fish

### ISSUE THREAD

**Issue by pani2004** [kunjgit/GameZone#4280]
### 🎮 Game Request

Go Fish is a classic card game , The objective of the game is to collect as many pairs of cards as possible. Players take turns asking each other for specific cards to match the ones they already have in their hand. If the opponent has the requested card, they must give it to the player. If not, the player "goes fish" and draws a card from the deck. The game continues until all pairs have been collected or the deck is empty. The player with the most pairs at the end wins!

### Point down the features

Game Logic:
Creation of a deck of cards (52 cards).
Shuffling of the deck before dealing cards.
Dealing 7 cards to each player at the beginning of the game.
Implementing the rules of the game (asking for cards, drawing from the deck, forming pairs).
Tracking pairs and updating the score.

Computer Player:

AI for the computer player to make decisions.
Strategy for the computer player's turn (e.g., choosing which cards to ask for).

End Game:

Detecting the end of the game (when all pairs are formed or the deck is empty.
Declaring the winner based on the number of pairs collected.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @pani2004 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by pani2004** [comment]
@kunjgit Pls add the gssoc label

**Comment by pani2004** [comment]
@ishita-43 Pls add the gssoc label

**Comment by kunjgit** [comment]
Hey @pani2004 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
