### ISSUE TITLE
[New game]: Planet colonizer 

### ISSUE THREAD

**Issue by Yashgabani845** [kunjgit/GameZone#4287]
### 🎮 Game Request

Game logic and basic description
is a simple and engaging web-based game where players are tasked with colonizing planets by clicking on them. The game is built using HTML, CSS, and JavaScript, providing an interactive experience right in the browser.

### Point down the features

# Game points
- Interactive Gameplay: Players can click on planets to colonize them.
- Visual Feedback: Colonized planets change color to indicate they have been successfully colonized.
- Score Tracking: A scoreboard keeps track of the number of planets colonized by the player.
 # How to Play:
- Open the Game: Launch the game by opening the index.html file in your web browser.
- Colonize Planets: Click on any of the planets displayed on the screen. Each click will change the planet's color, indicating that it has been colonized.
- Track Your Progress: The scoreboard at the bottom of the screen will update to show the number of planets you have colonized.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Yashgabani845 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @Yashgabani845 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
