### ISSUE TITLE
[New game]: DrumKit

### ISSUE THREAD

**Issue by Ayesha-Siddiqua88** [kunjgit/GameZone#4288]
### 🎮 Game Request

The Drum Kit game is an interactive music game where different instruments are displayed on the screen, each associated with a specific letter key. When the player presses the corresponding key on their keyboard, the respective instrument sound plays. This simple yet engaging gameplay allows players to create rhythms and music by pressing different keys.

### Point down the features

The Drum Kit game includes keyboard interaction, where each instrument is mapped to a specific letter key. When a key is pressed, the corresponding instrument sound plays, accompanied by visual feedback such as highlights or animations. The game features various percussion instruments like drums and cymbals and offers a responsive design that adapts to different screen sizes and devices for a seamless experience.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Ayesha-Siddiqua88 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hello @Ayesha-Siddiqua88, Time's up!⏰ 
 Sorry for closing your issue! 
 But it's more than a week since we haven't received anything from your side 😢 . 
 Come up with new ideas, create a new issue and make sure you finish it within a week! 🔥 
 All the best! 🚀 
 Happy Hacking! 💗
