### ISSUE TITLE
[New game]: Mamba_Mayhem

### ISSUE THREAD

**Issue by Lelin07** [kunjgit/GameZone#4291]
### 🎮 Game Request

# Game Request
I would like to make a fun and interesting retro-style Snake game with high score functionality.

### Point down the features

- Classic snake gameplay with retro graphics and sound effects
- Smooth and responsive controls
- Increasing difficulty as the snake grows longer
- Display of current score during the game
- High score tracking and display after each game
- Option to reset high scores

## Game points
- Points are earned by eating food items that appear on the screen
- Each food item increases the snake's length and adds to the player's score
- The game ends when the snake collides with itself or the walls

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Lelin07 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @Lelin07 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
