### ISSUE TITLE
[Bug]: The scroll down/up is not working in the contributors sections

### ISSUE THREAD

**Issue by Vijayaa21** [kunjgit/GameZone#4292]
### Give a brief about the bug ✍️

Description
Scrolling down to the contributions section, when I try to access below the previous and next buttons, and move the cursor down to them, scrolling up and down does not work.

### What is the expected behavior? 🤔

Description
The expected behavior in the contributor section is that the key must function for scrolling up and down.

### Provide step by step information reproduce the bug 📄

Description
Check the code and bootstrap to allow scrolling in that section by cancelling the stop-scroll function.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hello @Vijayaa21, Time's up!⏰ 
 Sorry for closing your issue! 
 But it's more than a week since we haven't received anything from your side 😢 . 
 Come up with new ideas, create a new issue and make sure you finish it within a week! 🔥 
 All the best! 🚀 
 Happy Hacking! 💗

**Comment by kunjgit** [comment]
Hey @Vijayaa21 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
