### ISSUE TITLE
[New game]: Stone-Paper-Scissor

### ISSUE THREAD

**Issue by Vaishnavi1047** [kunjgit/GameZone#4293]
### 🎮 Game Request

based on html,css and javascipt.

### Point down the features

Game points
![Screenshot 2024-01-04 173544](https://github.com/kunjgit/GameZone/assets/149894552/cb2f4179-b762-407a-96f6-b2e906b0f3fa)

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Vaishnavi1047 , You can't have another issue before completing the previous one 😀 
 you already have the following 1 open issues 👀 ! :

#3905

**Comment by kunjgit** [comment]
Hey @Vaishnavi1047 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by kunjgit** [comment]
Hey @Vaishnavi1047 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by Vaishnavi1047** [comment]
why it is closed?

**Comment by ishita-43** [comment]
PR is closed by bot , You need to make new pr again make sure to follow contribution guidelines
