### ISSUE TITLE
[New game]: Song Visualizer Game

### ISSUE THREAD

**Issue by sidharth2829** [kunjgit/GameZone#4295]
### 🎮 Game Request

This Game allows users to upload a song file, visualize its frequency data, and manipulate specific frequencies at various points. Users can see a graphical representation of the sound's frequencies and interact with them to change the audio output.

<img width="620" alt="Screenshot 2024-06-06 at 7 07 25 PM" src="https://github.com/kunjgit/GameZone/assets/111569459/4eefee59-29c9-4fe0-b30a-df569c2d1048">

### Point down the features

File Upload: Allow users to upload their song file.
Audio Context Setup: Create an audio context and set up the audio nodes for playback and manipulation.
Analyser Node: Use an AnalyserNode to visualize the audio frequencies.
Gain Nodes: Create multiple GainNode elements to control the gain (volume) at specific frequencies.
UI for Manipulation: Provide a user interface to manipulate the gain at various frequencies.
Update Audio: Apply the changes in real-time as users interact with the UI.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by sidharth2829** [comment]
Please assign me this issue under gssoc'24

**Comment by kunjgit** [comment]
Hey @sidharth2829 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @sidharth2829 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
