### ISSUE TITLE
[Enhancement]: Would like to add "Back To Main Menu" button 

### ISSUE THREAD

**Issue by ShrikanthDeva** [kunjgit/GameZone#43]
### Is your enhancement request related to a problem? Please describe.➕

Game enhancement: After entering  a game, There is no button to go back to the main menu to try playing other games.

### Describe the solution you'd like

Solution steps
So i would like to add the " < Go Back "  button for each game, as a part of GSSoC'23 contributor !

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
@ShrikanthDeva for that they can use the browser back button as well to make that possible we have to make that available to all the games present on GameZone which is quite impossible for now !! 
Thank you soo much for raising an issue on GameZone 🎮 💗
