### ISSUE TITLE
[Bug]: Correct light mode text colors and theme

### ISSUE THREAD

**Issue by saadakbar1** [kunjgit/GameZone#4300]
### Give a brief about the bug ✍️

I ll correct all background and text colors and theme for light mode
![dark](https://github.com/kunjgit/GameZone/assets/102979976/6b9e7eee-87fe-4169-b133-b85339dd797a)

### What is the expected behavior? 🤔

It will become more professional

### Provide step by step information reproduce the bug 📄

I ll edit light mode css file

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @saadakbar1 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by saadakbar1** [comment]
@kunjgit assign me issue and label gssoc

**Comment by Jetshree** [comment]
want to work on this project, please assign it to me @kunjgit

**Comment by kunjgit** [comment]
Hello @saadakbar1, Time's up!⏰ 
 Sorry for closing your issue! 
 But it's more than a week since we haven't received anything from your side 😢 . 
 Come up with new ideas, create a new issue and make sure you finish it within a week! 🔥 
 All the best! 🚀 
 Happy Hacking! 💗

**Comment by kunjgit** [comment]
Hey @saadakbar1 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
