### ISSUE TITLE
[New game]: 

### ISSUE THREAD

**Issue by Sambit-Mondal** [kunjgit/GameZone#4301]
### 🎮 Game Request

I want to develop a real-time multiplayer game where players control heroes with unique abilities and battle against each other in teams.

### Point down the features

The game would include features like:
- Real-time multiplayer with WebSockets.
- Character abilities and leveling system.
- Dynamic maps with various terrains.
- AI-controlled minions and bosses.
- In-game chat system.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Sambit-Mondal , You can't have another issue before completing the previous one 😀 
 you already have the following 1 open issues 👀 ! :

#4282

**Comment by kunjgit** [comment]
Hey @Sambit-Mondal ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by kunjgit** [comment]
Hey @Sambit-Mondal ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @Sambit-Mondal! 
We are already having a similar game request in #4287 👀 
Make sure you come up with a cool unique idea 😀 
 Waiting for your new game idea 💗.
