### ISSUE TITLE
[Enhancement]:  Tic Tac Toe game

### ISSUE THREAD

**Issue by sivaprasath2004** [kunjgit/GameZone#4308]
### Do you want to have the enhancement of existing game ? 😀 Describe yourself..

- In this game ui was poor Ui .
- Game logic mistake if the  game actual win announced but the user moved option, this is not proper logic of the game.
- please assign me ...

### Expected behaviour & UI
[Screencast from 2024-05-26 13-38-39.webm](https://github.com/kunjgit/GameZone/assets/121082414/91bb65da-ed4c-4914-95a5-9383a37f46fc)

### Actual behaviour & UI
[Screencast from 2024-05-26 13-32-46.webm](https://github.com/kunjgit/GameZone/assets/121082414/edc19793-261a-48cc-a1be-e4451da00e52)

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @sivaprasath2004 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by ShahHetviIT** [comment]
I'm excited about taking the lead on the GameZone project. With my proficiency in HTML, CSS, JavaScript, and ReactJS, I'm confident in my ability to drive significant progress on this initiative. Please assign me to this project via GSSOC.

**Comment by kunjgit** [comment]
Hey @sivaprasath2004 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
