### ISSUE TITLE
[New game]: 3 player tic-tac

### ISSUE THREAD

**Issue by trishanu-init** [kunjgit/GameZone#431]
### 🎮 Game Request

This game will allow three players to play tic-tac-toe simultaneously creating a game that is very different and unique from the traditional game of 2 player tic-tac-toe.

### Point down the features

- 3 Player gameplay
- Interactive UI
- Low system memory usage
- Available online as well as offline
- Easy and engaging

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @trishanu-init ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by Akanksha038** [comment]
Hello sir/Ma'am,
I want to add Snake and Ladder Game. I have made this game using HTML, CSS, and JavaScript. Can you Please assign this issue to me?

**Comment by Gun2902** [comment]
can u assign me this isssue

**Comment by kunjgit** [comment]
Hello @trishanu-init, Time's Uppp!⏰ 
 Sorry for closing your issue! 
 But it's more than a week since we haven't received anything from your side 😢 . 
 Come up with new ideas, create a new issue and make sure you finish it within a week! 🔥 
 All the best! 🚀 
 Happy Hacking! 💗

**Comment by kunjgit** [comment]
Hey @trishanu-init ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
