### ISSUE TITLE
[New game]: Catch the Falling Object

### ISSUE THREAD

**Issue by katarianikita2003** [kunjgit/GameZone#4311]
### 🎮 Game Request

Game logic and basic description : 
Objects will be falling from the top and we have to collect that at the bottom
![Screenshot 2024-06-07 122438](https://github.com/kunjgit/GameZone/assets/158465309/a4884e2f-ef43-4580-9cb4-b22f9993ceed)

### Point down the features

- Score will be displayed.
- 5 lives will be provided to the player.
- If player will not catch the objects, then player will loose 1 life 

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @katarianikita2003 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by katarianikita2003** [comment]
I want to work on this issue, @kunjgit can you please assign it to me

**Comment by katarianikita2003** [comment]
https://github.com/kunjgit/GameZone/assets/158465309/215df9cd-b8d9-40ee-8878-efc400471d14

![Screenshot 2024-06-07 133434](https://github.com/kunjgit/GameZone/assets/158465309/a0c366be-b620-4626-b3b1-308ba5ecb37d)
![Screenshot 2024-06-07 133459](https://github.com/kunjgit/GameZone/assets/158465309/91657a6e-ccb1-4668-aa97-90cd6bee2ab0)


@kunjgit , review it

**Comment by ShahHetviIT** [comment]
I'm excited about taking the lead on the eSmart project. With my proficiency in HTML, CSS, JavaScript, and ReactJS, I'm confident in my ability to drive significant progress on this initiative. Please assign me to this project via GSSOC.

**Comment by kunjgit** [comment]
Hey @katarianikita2003 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by kunjgit** [comment]
Hey @katarianikita2003 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
