### ISSUE TITLE
[New game]: Tetris

### ISSUE THREAD

**Issue by muskan42** [kunjgit/GameZone#4312]
### 🎮 Game Request

Game logic and basic description:

1. Continuously checking for player input (movement, rotation) and moving the active tetromino down the board at set intervals.
2. If the tetrimino hits the bottom, another block, or goes out of bounds, solidify it on the board.
3. Checking each row after a tetromino lands. If a row is full, remove all blocks in that row and update score.
4. Increasing the speed of falling tetrominoes as more lines are cleared. 

![image](https://github.com/kunjgit/GameZone/assets/141642724/37ef5a0b-cef7-4c4c-adb1-5ae8d5345b3e)

### Point down the features

Tetris features: 
  - Classic tetromino shapes (I, J, L, O, S, T, Z).
  - Players control and rotate these shapes.
  - Cleared line award points and increased difficulty.
  - The goal is to maximize points before the board fills up. 

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @muskan42 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by muskan42** [comment]
assign

**Comment by muskan42** [comment]
@kunjgit I request you to kindly address the PR so that I can work on further issues

**Comment by kunjgit** [comment]
Hey @muskan42 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
