### ISSUE TITLE
[New game]: Bingo

### ISSUE THREAD

**Issue by Sreema-sahu** [kunjgit/GameZone#4313]
### 🎮 Game Request

Game logic and basic description: Bingo is a social game where players are given cards with grids of numbers. The main goal is to mark off a specific pattern of numbers on the card, usually five in a row, column, or diagonal before your opponents do. The player who completes the pattern and shouts “Bingo!” is declared the winner.

### Point down the features

Game points: Grid Layout: 5x5 grid with B-I-N-G-O columns.
Number Ranges: B (1-15), I (16-30), N (31-45), G (46-60), O (61-75).
Number Drawing: Randomly selects and announces numbers/letters.
Verification: Checks winning cards.
Rewards: Non-monetary prizes for winners.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Sreema-sahu ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by Sreema-sahu** [comment]
assign

**Comment by Anjaliavv51** [comment]
@kunjgit please review the changes

**Comment by Anjaliavv51** [comment]
@ishita-43 @kunjgit please review the game

**Comment by Anjaliavv51** [comment]
@ishita-43 @kunjgit please review the game

**Comment by kunjgit** [comment]
Hey @Sreema-sahu ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
