### ISSUE TITLE
[New game]: Slot machine

### ISSUE THREAD

**Issue by ayush-848** [kunjgit/GameZone#4314]
## Game logic and basic description
The Slot Machine Game is a simple and engaging web-based game where players spin three reels containing various fruit symbols. The objective is to match all three symbols to win a prize. Each spin costs $10, and a successful match rewards the player with $50. Players start with a balance of $100, and the game provides buttons to spin, reset the game, and view the rules.

## Game points
Starting Balance: $100
Cost per Spin: $10
Win Reward: $50 for matching all three symbols
Loss Penalty: $10 for not matching symbols

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @ayush-848 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by kunjgit** [comment]
Hey @ayush-848 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)
