### ISSUE TITLE
[Enhancement]: Addition of Chatbot

### ISSUE THREAD

**Issue by Anjaliavv51** [kunjgit/GameZone#4317]
### Do you want to have the enhancement of existing game ? 😀 Describe yourself..

Addition of Chatbot

### Describe the solution you'd like

Addition of Chatbot , to assist the user's.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Anjaliavv51 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by ishita-43** [comment]
your pr is closed you need to open again and make new pr

**Comment by Anjaliavv51** [comment]
@ishita-43 can u reopen the PR?

**Comment by Anjaliavv51** [comment]
@ishita-43 i think u have that access right

**Comment by ishita-43** [comment]
i cant do this it is your department and admins department your pr will simply be opened if you will make new pr i guess

**Comment by Anjaliavv51** [comment]
@ishita-43 okay I createanother pr

**Comment by kunjgit** [comment]
Hey @Anjaliavv51 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
