### ISSUE TITLE
[New game]: Spirograph

### ISSUE THREAD

**Issue by muskan42** [kunjgit/GameZone#4321]
### 🎮 Game Request

A Spirograph is a geometric drawing tool that creates beautiful, spiraling curves.

Logic:
1. setting parameters like gear sizes and frequency values that define the shape of the structure.
2. calculating the X and Y coordinates involving trigonometric functions.
3. the t value is continuously incremented, causing the calculations to update the X and Y coordinates, resulting in an animation of the curve being drawn on the screen.

![Screenshot 2024-06-07 193135](https://github.com/kunjgit/GameZone/assets/141642724/6daf2307-1622-4484-82f8-4207dbb85802)

### Point down the features

1. Combine gears with various sizes to create unique designs.
2. Roll a smaller gear around a larger one, tracing stunning curves.
3. These patterns, called hypotrochoids/epitrochoids, hold mathematical beauty.
4. Explore endless patterns and designs. 

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @muskan42 , You can't have another issue before completing the previous one 😀 
 you already have the following 1 open issues 👀 ! :

#4312

**Comment by kunjgit** [comment]
Hey @muskan42 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by kunjgit** [comment]
Hey @muskan42 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)
