### ISSUE TITLE
[New game]: History Time Travel: Interactive History Lessons

### ISSUE THREAD

**Issue by Zedoman** [kunjgit/GameZone#4324]
### 🎮 Game Request

Game logic and basic description
History Time Travel is a dynamic web application designed to bring history to life through an immersive and interactive learning experience. The application allows users to "travel" to different historical eras, such as Ancient Egypt, Medieval Europe, and the Industrial Revolution. Within each era, users are presented with specific tasks that they must complete to progress.

Each task is associated with a short quiz designed to test the user's knowledge about the historical period. For example, a task in Ancient Egypt might be "Build a pyramid," which involves answering questions about pyramid construction and Egyptian pharaohs. The quiz format is multiple-choice, with questions presented in a visually appealing popup window. Users must select the correct answer from the given options to move on to the next question. If the user selects an incorrect answer, they are prompted to try again.

Upon successfully answering all questions in the quiz, the task is marked as completed. The "Complete Task" button changes to "Task Completed," indicating that the user has successfully finished the task. This task status update provides a sense of accomplishment and encourages users to explore and complete other tasks within the era or move on to different historical periods.

The frontend of the application is built with HTML, CSS, and JavaScript, ensuring a smooth and responsive user interface. The backend is powered by Flask, a lightweight Python web framework, which serves the static files and handles the task and quiz data.

Game Logic
Homepage:

The user is presented with buttons for each historical period.
Clicking on a period displays a list of tasks associated with that period.
Displaying Tasks:

Each task is displayed with a description and a "Complete Task" button.
When the user clicks on "Complete Task," a quiz popup appears.
Quiz Popup:

The quiz consists of multiple-choice questions related to the task.
Questions are displayed one at a time, and the user must select the correct answer to proceed.
If the user answers incorrectly, they are prompted to try again.
Completing the Task:

After correctly answering all questions, the task is marked as completed.
The "Complete Task" button updates to "Task Completed," and further interaction with the task is disabled.
Task and Quiz Management:

The task descriptions and quiz questions are predefined and stored in the Flask backend.
The backend serves this data to the frontend upon request.
By combining historical content with interactive elements, History Time Travel transforms the learning process into an engaging experience. Users not only gain knowledge about different historical periods but also develop a sense of accomplishment as they complete various tasks and quizzes. This approach aims to make history education more dynamic and enjoyable for users of all ages.

### Point down the features

Game points
Upon successfully answering all questions in the quiz, the task is marked as completed. The "Complete Task" button changes to "Task Completed," indicating that the user has successfully finished the task. This task status update provides a sense of accomplishment and encourages users to explore and complete other tasks within the era or move on to different historical periods.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Zedoman ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by kunjgit** [comment]
Hey @Zedoman ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @Zedoman ! , This issue is already assigned to @Zedoman. 💗 
 You can work on other issues 🚀 
 If there is anything wrong you can contact us on [Discord🕹️](https://discord.gg/fgwk4XZfxG)👀

**Comment by Zedoman** [comment]
please make it gssoc
