### ISSUE TITLE
[New game]: KeySymphony : A Playable Piano

### ISSUE THREAD

**Issue by AdityaP700** [kunjgit/GameZone#4328]
### 🎮 Game Request

Game logic and basic description :
The Playable Piano game is an interactive game depicting a real piano. Users can play musical notes by clicking on the piano keys or using their keyboard. This project provides a fun experience, allowing users to practice piano playing directly in their web browser.

### Point down the features

Game points

- Interactive Keyboard
- Visual Feedback
- Audio Playback
- Responsive Design
 

### Select program in which you are contributing

GSSoC24, Other

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @AdityaP700 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @AdityaP700 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
