### ISSUE TITLE
[New game]: Car Racing

### ISSUE THREAD

**Issue by shellyverma** [kunjgit/GameZone#4333]
### 🎮 Game Request

This game will involve players controlling a car as it races along a track, avoiding obstacles and competing to achieve the highest score.

### Point down the features

Smooth and responsive controls for the car (up, down, left, right).
A dynamically scrolling race track with varying difficulty and obstacles.
Various obstacles on the track that players must avoid.
Display of current score during the game.
High score tracking and display after each game.
The game ends if the car crashes into an obstacle or goes off the track.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @shellyverma ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @shellyverma ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
