### ISSUE TITLE
[New game]: Cake Builder

### ISSUE THREAD

**Issue by ayushicpp** [kunjgit/GameZone#4335]
### 🎮 Game Request

The main objective of the Cake Builder game is to create a visually appealing cake by stacking layers and adding decorations.

### Point down the features

Game points
Interactive Buttons:
Buttons allow the player to add different types of cake layers (chocolate, vanilla) and decorations (sprinkles, cherry).
Dynamic Cake Construction:
The cake is constructed in real-time as the user interacts with the buttons, providing immediate visual feedback.
Simple Graphics:
The game uses simple CSS for styling the layers and decorations, making it easy to expand with additional styles or images.
Visual Feedback:
Each layer and decoration is visually distinct, allowing the player to see the immediate result of their actions.
Extensible Design:
The game structure is designed to be easily extended with additional types of layers, decorations, and more advanced features.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @ayushicpp ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by ayushicpp** [comment]
I want to work in collab with @aadyagupta44

**Comment by aadyagupta44** [comment]
kindly assign to me as well , in order to work together with  @ayushicpp @kunjgit .
assigned

**Comment by aadyagupta44** [comment]
assigned

**Comment by kunjgit** [comment]
Hey @aadyagupta44 ! , This issue is already assigned to @ayushicpp. 💗 
 You can work on other issues 🚀 
 If there is anything wrong you can contact us on [Discord🕹️](https://discord.gg/fgwk4XZfxG)👀

**Comment by kunjgit** [comment]
Hello @ayushicpp, Time's up!⏰ 
 Sorry for closing your issue! 
 But it's more than a week since we haven't received anything from your side 😢 . 
 Come up with new ideas, create a new issue and make sure you finish it within a week! 🔥 
 All the best! 🚀 
 Happy Hacking! 💗

**Comment by kunjgit** [comment]
Hey @ayushicpp ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by Ayushigupta2005** [comment]
> Hey @ayushicpp ! Thank you so much for your raising the issue💗 It’s all yours, you can come anytime again and make some contributions! 🚀 Alone, we can do little, but together we can do so much! 😇

Hey @kunjgit my part has been ready from a long time but I'm facing problem as I'm unaware of how to upload the files even though I read it how to do but its something new to me so kindly guide me
