### ISSUE TITLE
[New game]: Whac a Mole

### ISSUE THREAD

**Issue by taneeshaa15** [kunjgit/GameZone#4339]
### 🎮 Game Request

User friendly and very enjoyable game

### Point down the features

1. Easy to play.
2. User friendly.
3. Age friendly.
4. Enjoyable.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @taneeshaa15 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by taneeshaa15** [comment]
@kunjgit Please assign this issue to me.

**Comment by taneeshaa15** [comment]
self

**Comment by TheNikhilRaj** [comment]
I would like to work on this issue, please assign this to me.
@kunjgit

**Comment by kunjgit** [comment]
Hey @taneeshaa15 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
