### ISSUE TITLE
UI enhancement 

### ISSUE THREAD

**Issue by Akshitha-reddy-13** [kunjgit/GameZone#4341]
Nothing is visible in day mode on the website. I would like to change it and make it more attractive as it seems so basic.
![image](https://github.com/kunjgit/GameZone/assets/122172211/bebf87f5-228c-4812-91c1-7017aaca2cdc)

Can you assign it to me? @kunjgit 
Full name: Akshitha Reddy
GitHub profile link: [Akshitha-reddy-13](https://github.com/Akshitha-reddy-13)
Email ID: akshithajagan13@gmail.com
What is your participant role?: GSSoC-2024 contributor

Can you add the label for GSSoC, please?
Thanks.

**Comment by kunjgit** [comment]
Hey @Akshitha-reddy-13 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by Akshitha-reddy-13** [comment]
Please add gssoc label

**Comment by techy4shri** [comment]
I think you can assign this issue yourself as the PA said.

**Comment by Akshitha-reddy-13** [comment]
There is no option for the assigning myself and also there is no gssoc label added by PA.  Hence, I am waiting for the response

**Comment by kunjgit** [comment]
Hey @Akshitha-reddy-13 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
