### ISSUE TITLE
BUG 🐞: Dark mode gets turned off on refreshing the page

### ISSUE THREAD

**Issue by aslams2020** [kunjgit/GameZone#4353]
### Give a brief about the bug ✍️

Hey @kunjgit,
Here is the issue -
The dark mode preference does not persist across page refreshes.
Each time the page is refreshed, the mode resets to the default instead of maintaining the user-selected mode (dark or light).
I think it is due to the theme state is not being persisted when the page is refreshed.

**Screenshots**
- Before refreshing the page looks like(currently in light mode) :

![image](https://github.com/kunjgit/GameZone/assets/131389695/2c5c16dd-c5a8-42dd-b319-c51e43f8d28d)

- After refreshing the page :

![image](https://github.com/kunjgit/GameZone/assets/131389695/4ea8f8ee-9cfa-4adf-9bb5-3570c1ac8167)

### What is the expected behavior? 🤔

The selected dark or light mode should persist across page refreshes.
If a user selects dark mode, the page should remain in dark mode even after refreshing.

I hope I was able to explain the issue.
If so, Could you please assign this issue to me under GSSoC 24?

### Provide step by step information reproduce the bug 📄

**To Reproduce**
- Go to the website.
- Toggle the dark mode switch to change the theme.
- Refresh the page.
- Observe that the theme reverts to the default mode instead of retaining the selected mode.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @aslams2020 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @aslams2020 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
