### ISSUE TITLE
[Bug]: Removing unwanted vertical scrolling from 2048 game

### ISSUE THREAD

**Issue by divyalaldinani** [kunjgit/GameZone#4356]
### Give a brief about the bug ✍️

![image](https://github.com/kunjgit/GameZone/assets/82147067/545f9e80-9cbb-4b75-ba0a-d864b01fd664)
In laptop, we use arrow keys to play this game, and due if we press up or down keys then the page starts moving up or down which is unneccsarry and not required, thus scrolling is a pain here.

### What is the expected behavior? 🤔

No scrolling required

### Provide step by step information reproduce the bug 📄

setting Overflow to be hidden

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @divyalaldinani , You can't have another issue before completing the previous one 😀 
 you already have the following 1 open issues 👀 ! :

#4278

**Comment by kunjgit** [comment]
Hey @divyalaldinani ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by kunjgit** [comment]
Hey @divyalaldinani ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)
