### ISSUE TITLE
[Bug]: Adding automatic copyright

### ISSUE THREAD

**Issue by dishathakurata** [kunjgit/GameZone#4363]
### Give a brief about the bug ✍️

The current code contains manual copyright year which needs to be changed every year manually.

### What is the expected behavior? 🤔

Adding automatic copyright year reduces manual effort by updating every year automatically, and this makes website look more professional.

### Provide step by step information reproduce the bug 📄

Adding a JavaScript currentYear code in the copyright section.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @dishathakurata , You can't have another issue before completing the previous one 😀 
 you already have the following 1 open issues 👀 ! :

#4362

**Comment by kunjgit** [comment]
Hey @dishathakurata ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by dishathakurata** [comment]
@kunjgit Can I work on this now as my previous issue is completed? Please open this issue and assign it to me under GSSoC.
