### ISSUE TITLE
[SEARCH INPUT TEXT]: THE TEXT REMAINS EVEN AFTER RERENDER

### ISSUE THREAD

**Issue by laxmanp090404** [kunjgit/GameZone#4365]
### Give a brief about the bug ✍️

The input text that is expected to be cleared or updated during a rerendering process remains visible and unchanged.This is not advisable as it would cause some disturbance in searching.

### What is the expected behavior? 🤔

The expected behaviour is after a rerender the text in the search input shoud reset to empty or its default placeholder.

### Provide step by step information reproduce the bug 📄

I plan on solving the issue by providing new logic for the text input change on rerender by either creating a function to change text.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @laxmanp090404 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @laxmanp090404! 🙂 
 It seems like you are not following proper guidelines !! 👀 
 Read documentation properly !!🙏 
 If you have any queries reach out to us on [Discord🕹️](https://discord.gg/fgwk4XZfxG) .

**Comment by kunjgit** [comment]
Hey @laxmanp090404 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
