### ISSUE TITLE
[New game]: QR CODE Generator

### ISSUE THREAD

**Issue by codewithganeshhh** [kunjgit/GameZone#4366]
### **Game logic and basic description:** 
A simple web application which will generate a QR Code.
You Can Create Your Name Number QR codes

### Game points :
A simple web application which will generate a QR Code.
You Can Create Your Name Number QR codes**

![QR CODE Generator](https://github.com/kunjgit/GameZone/assets/139307139/af895552-69c2-49c7-91c1-96c32a8d9e64)

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @codewithganeshhh ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @codewithganeshhh! 
We are already having a similar game request in #4269 👀 
Make sure you come up with a cool unique idea 😀 
 Waiting for your new game idea 💗.

**Comment by kunjgit** [comment]
Hey @codewithganeshhh ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
