### ISSUE TITLE
[Enhancement]: Adding the dynamic background.

### ISSUE THREAD

**Issue by happyrao78** [kunjgit/GameZone#4370]
### Do you want to have the enhancement of existing game ? 😀 Describe yourself..

Game enhancement: I want to add the auto color changing background to enhance user interaction.

### Describe the solution you'd like

Solution steps
I would use the  Math.random() method which will generate a random hex code value and pish into the dummy array.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @happyrao78 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by happyrao78** [comment]
@kunjgit Kindly merge this PR after reviewing.

**Comment by kunjgit** [comment]
Hey @happyrao78 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
