### ISSUE TITLE
[Bug]: Footer being sticky. 

### ISSUE THREAD

**Issue by shishiro26** [kunjgit/GameZone#438]
### Give a brief about the bug ✍️

Description FootBar is being sticky to the bottom because of that the games below cant be visible.
![image](https://github.com/kunjgit/GameZone/assets/113853868/06f6f813-2a99-4965-8564-cbbd5b5949a6)

### What is the expected behavior? 🤔

Description The FootBar need not be sticky and the scroller should be free to scroll to the bottom...and the games below the footer need ed to be visible.

### Provide step by step information reproduce the bug 📄

Description I willl try to remove the footer being sticky  and stick it to the bottom.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @shishiro26 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hello @shishiro26, Time's Uppp!⏰ 
 Sorry for closing your issue! 
 But it's more than a week since we haven't received anything from your side 😢 . 
 Come up with new ideas, create a new issue and make sure you finish it within a week! 🔥 
 All the best! 🚀 
 Happy Hacking! 💗

**Comment by kunjgit** [comment]
Hey @shishiro26 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
