### ISSUE TITLE
[New game]: Rabbit_Chase

### ISSUE THREAD

**Issue by manikumarreddyu** [kunjgit/GameZone#4381]
### 🎮 Game Request

Game logic and basic description

The game is simple..like tenple run
The rabbits runs along the way and a ghost chases it
the rabbit have to grab the carrots by jumping
and rabbit should avoid obsacles

### Point down the features

Game points

the points are given according to the number of carrots are eaten or grabbed by the rabbit 
and the number obstacles it avoided
how much time the game is played

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @manikumarreddyu ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @manikumarreddyu ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
