### ISSUE TITLE
[New game]: Lunar Lander

### ISSUE THREAD

**Issue by Maheshwari-Love** [kunjgit/GameZone#4389]
### 🎮 Game Request

The Lunar Lander game is a classic arcade-style game where the player controls a spacecraft that must safely land on the moon's surface. The game simulates the physics of space flight, requiring the player to carefully manage the spacecraft's fuel and thrust to achieve a soft landing.

### Point down the features

Game points
Controls
 Simulation
Player Input
Collision Detection

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by Maheshwari-Love** [comment]
\assign

**Comment by kunjgit** [comment]
Hey @Maheshwari-Love ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @Maheshwari-Love ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
