### ISSUE TITLE
[New game]: Alphabet

### ISSUE THREAD

**Issue by TusharMinche** [kunjgit/GameZone#439]
### 🎮 Game Request

Dear @kunjgit  ,
I hope this message finds you well. I would like to request the addition of my JavaScript project to your repository. The project is designed to help children learn the alphabet in an interactive and engaging way.

### Point down the features

The project features a user interface that displays all the alphabets from A to Z, accompanied by corresponding images. When a child clicks on a specific alphabet or types a single alphabet, a corresponding sound is played. For example, if the child clicks on the letter 'A', a sound saying "A for apple" will be played.

The purpose of this project is to provide a fun and educational tool for children to learn and familiarize themselves with the alphabet. By associating each letter with a visual representation and an auditory cue, it aims to enhance their understanding and retention of the alphabet.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @TusharMinche ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by TusharMinche** [comment]
Assign the issue to me.

**Comment by kunjgit** [comment]
Hey @TusharMinche ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
