### ISSUE TITLE
[New game]: Lava Run

### ISSUE THREAD

**Issue by Maheshwari-Love** [kunjgit/GameZone#4392]
### 🎮 Game Request

Lava Run is an exhilarating and fast-paced platformer game where players must navigate through a series of obstacles while escaping from a rising tide of molten lava. The game tests the player's reflexes, timing, and strategic thinking as they race against the clock to avoid being consumed by the advancing lava flow.

### Point down the features

Game points
Controls:
Movement: Use arrow keys or WASD to move left and right.
Jumping: Spacebar or up arrow key to jump.
Special Abilities: Specific keys or combinations to activate power-ups.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Maheshwari-Love , You can't have another issue before completing the previous one 😀 
 you already have the following 1 open issues 👀 ! :

#4389

**Comment by kunjgit** [comment]
Hey @Maheshwari-Love ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by kunjgit** [comment]
Hey @Maheshwari-Love ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)
