### ISSUE TITLE
[New game]: Jigsaw Game

### ISSUE THREAD

**Issue by Vipullakum007** [kunjgit/GameZone#4394]
### 🎮 Game Request

Game logic and basic description : 
### Jigsaw Puzzle Game Description
A Jigsaw Puzzle game where players drag and drop pieces to fit them together and complete a picture.

### Game Logic
1. **Shuffle Pieces:** Randomly place jigsaw pieces around the canvas.
2. **Drag and Drop:** Allow pieces to be draggable and snapped into place when close to their correct position.
3. **Completion Check:** Continuously check if all pieces are correctly placed to display a completion message.

### Jigsaw Puzzle Game Features

1. **Piece Shuffling:** Randomly distribute pieces on the canvas.
2. **Drag and Drop:** Enable dragging and snapping of pieces.
3. **Completion Check:** Detect when all pieces are correctly placed.
4. **Completion Message:** Display a message upon completing the puzzle.
5. **Image Selection:** Allow users to select different images for the puzzle.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Vipullakum007 , You can't have another issue before completing the previous one 😀 
 you already have the following 1 open issues 👀 ! :

#3582

**Comment by kunjgit** [comment]
Hey @Vipullakum007 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
