### ISSUE TITLE
[New game]: Jigsaw Game

### ISSUE THREAD

**Issue by Vipullakum007** [kunjgit/GameZone#4395]
### 🎮 Game Request

Game logic and basic description:
Jigsaw Puzzle Game Description
A Jigsaw Puzzle game where players drag and drop pieces to fit them together and complete a picture.

Game Logic
Shuffle Pieces: Randomly place jigsaw pieces around the canvas.
Drag and Drop: Allow pieces to be draggable and snapped into place when close to their correct position.
Completion Check: Continuously check if all pieces are correctly placed to display a completion message.

### Point down the features

Jigsaw Puzzle Game Features
Piece Shuffling: Randomly distribute pieces on the canvas.
Drag and Drop: Enable dragging and snapping of pieces.
Completion Check: Detect when all pieces are correctly placed.
Completion Message: Display a message upon completing the puzzle.
Image Selection: Allow users to select different images for the puzzle.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Vipullakum007 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hello @Vipullakum007, Time's up!⏰ 
 Sorry for closing your issue! 
 But it's more than a week since we haven't received anything from your side 😢 . 
 Come up with new ideas, create a new issue and make sure you finish it within a week! 🔥 
 All the best! 🚀 
 Happy Hacking! 💗

**Comment by kunjgit** [comment]
Hey @Vipullakum007 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
