### ISSUE TITLE
[New game]: Endless Runner

### ISSUE THREAD

**Issue by Vipullakum007** [kunjgit/GameZone#4398]
### 🎮 Game Request

Game logic and basic description : 
Endless Runner

Build an endless runner game where the player controls a character that runs infinitely, jumping over obstacles and collecting items.

## Features 🎮
- **Endless Running:**
  - The player character runs infinitely, and the game continues until the player hits an obstacle.
- **Obstacle Avoidance:**
  - Jump over obstacles to avoid collisions and keep running.
- **Responsive Controls:**
  - Use the spacebar to make the player character jump.
- **Simple and Intuitive Design:**
  - Clean and straightforward design for an enjoyable gaming experience.
- **Score Tracking:**
  - Keep track of your score based on the distance covered and items collected.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Vipullakum007 , You can't have another issue before completing the previous one 😀 
 you already have the following 1 open issues 👀 ! :

#4395

**Comment by kunjgit** [comment]
Hey @Vipullakum007 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by kunjgit** [comment]
Hey @Vipullakum007 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)
