### ISSUE TITLE
[New game]: Dice Game

### ISSUE THREAD

**Issue by snehalsenapati23** [kunjgit/GameZone#44]
## Game logic and basic description

It is a simple dice game in which the player have to guess the number from 1 to 6 . And a number will displayed on the dice if both the number is same then user will get +5 points and if it not the same number then user will gt -2 points. 

## Point down the features
1.Game points
2.Simple UI
3.Single User
4.Reset option
5.Animation
6.User-friendly

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @snehalsenapati23 !
Make sure you add some more features it is looking too simple for now !! ❤️

**Comment by SahilPrabhu** [comment]
hey can i be assigned this under GSSOC'23?

**Comment by kunjgit** [comment]
Hey @snehalsenapati23 !! we are already having a game with similar logic come up with some unique idea or you can do enhancement later on !!

**Comment by kunjgit** [comment]
Hey @snehalsenapati23 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
