### ISSUE TITLE
[New game]: Card Matching Game

### ISSUE THREAD

**Issue by DEVANSHUKEJRIWAL** [kunjgit/GameZone#440]
### 🎮 Game Request

Game logic and basic description
This is basically a card matching game in which one card matches with similiar kind of other card the card gets removed

### Point down the features

Game points

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @DEVANSHUKEJRIWAL! 
We are already having a similar game request in #365 👀 
Make sure you come up with a cool unique idea 😀 
 Waiting for your new game idea 💗.

**Comment by kunjgit** [comment]
Hey @DEVANSHUKEJRIWAL ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)
