### ISSUE TITLE
[Documentation Bug]: Documentation Need improvement and links of games are not well organized

### ISSUE THREAD

**Issue by VesperAkshay** [kunjgit/GameZone#4401]
## To improve the organization of the games list in the readme file, consider the following approach:

- Use Headers or Sections: Divide the games into categories or sections to make it easier for readers to navigate. For example, categorize the games by genre, release date, or platform.

- Alphabetical Order: Arrange the games in alphabetical order within each category. This will make it easier for readers to find specific games.

- Formatting: Use bullet points or numbering to clearly list each game. Consider using bold or italic formatting for game titles to make them stand out.

- Descriptions: Provide brief descriptions or key features for each game to give readers a better understanding of what to expect.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @VesperAkshay ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @VesperAkshay ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
