### ISSUE TITLE
[New game]:  Fruit Slicer 

### ISSUE THREAD

**Issue by narayani9120** [kunjgit/GameZone#4405]
### 🎮 Game Request

Fruit Slider is a fun and engaging puzzle game where players slide fruit pieces on a grid to align them in a specific order or pattern. The objective is to complete the puzzle in the fewest moves possible.

### Point down the features

- Players can slide fruit pieces horizontally or vertically into an adjacent empty slot.
-The goal is to rearrange the fruit pieces to match a given target pattern or order.
- Bonus points for completing levels quickly or with fewer moves.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by narayani9120** [comment]
assign

**Comment by kunjgit** [comment]
Hey @narayani9120 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
