### ISSUE TITLE
[New game]:  Word Shuffle Game Request

### ISSUE THREAD

**Issue by thevijayshankersharma** [kunjgit/GameZone#4406]
### 🎮 Game Request

The Word Shuffle game challenges players to unscramble a set of letters to form meaningful words within a given time frame. Players are presented with a grid of letters, and they must rearrange these letters to create valid words. The game provides hints and shuffle options to assist players in finding words. Each level becomes progressively more difficult, with longer words and shorter time limits.

### Point down the features

Features:

Word Unscrambling: Players unscramble letters to form valid words.
Time Limit: Each level has a time limit within which players must complete the word unscrambling task.
Hints: Players can use hints to reveal letters or words to aid them in solving the puzzle.
Shuffle Option: Players can shuffle the letters to get a different arrangement, potentially revealing new word combinations.
Progressive Difficulty: As players advance through levels, the complexity of the word puzzles increases.
Score Tracking: The game keeps track of players' scores based on the number of words solved and the time taken.
Level System: Players progress through different levels, each with its own unique set of word puzzles.
Responsive Design: The game is designed to be playable on various devices with different screen sizes.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @thevijayshankersharma ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @thevijayshankersharma ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
