### ISSUE TITLE
[New game]: Word Atlas

### ISSUE THREAD

**Issue by abckhush** [kunjgit/GameZone#4408]
### 🎮 Game Request

World Atlas is an engaging educational game in which the user has to input a place by the last letter of the last shown place in 30 secs and no repetition of the place is required.

### Point down the features

1. Starting place is shown on the screen.
2. User has to input a new game using the last letter in 30 secs.
3. Verification checks are performed for the user input to be a place.
4. The game continues till the user fails to input the place in time.
5. Scores are maintained.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @abckhush ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @abckhush ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
