### ISSUE TITLE
[New game]: Go Fish

### ISSUE THREAD

**Issue by tanyagupta01** [kunjgit/GameZone#4410]
### 🎮 Game Request

The goal of the game is to collect as many complete sets of four numerically matching cards (one from each suit) as you can. Players can collect the cards they need from other players, or by “fishing” from the cards in the center.

### Point down the features

This game can be played by 2 to 7 players.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @tanyagupta01 , You can't have another issue before completing the previous one 😀 
 you already have the following 1 open issues 👀 ! :

#3620

**Comment by kunjgit** [comment]
Hey @tanyagupta01 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by kunjgit** [comment]
Hey @tanyagupta01 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @tanyagupta01! 
We are already having a similar game request in #4280 👀 
Make sure you come up with a cool unique idea 😀 
 Waiting for your new game idea 💗.
