### ISSUE TITLE
[Bug]: Light mode

### ISSUE THREAD

**Issue by avireet** [kunjgit/GameZone#4413]
### Give a brief about the bug ✍️

In light mode, the website font is not visible and is not as beautiful as it is in dark mode

### What is the expected behavior? 🤔

Change the font color 

### Provide step by step information reproduce the bug 📄

we can change the font color of the website in light mode or maybe remove the light mode altogether as I don't really see the need of light mode.
The game looks pretty in dark mode and I think most users would also prefer to play in dark mode only.
Just a suggestion.

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @avireet ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @avireet ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
