### ISSUE TITLE
[New game]: Word Detective

### ISSUE THREAD

**Issue by MuraliDharan7** [kunjgit/GameZone#4416]
### 🎮 Game Request

"Word Detective" is an engaging and challenging word puzzle game. The objective is to guess the hidden word based on a given hint. Here's how the game works:

- **Letter Boxes:** You'll have a series of letter boxes where you can type your guesses for the hidden word.
- **Hint Provided:** A hint will be given to help you figure out the word. Use this clue wisely to make your guesses.
- **Incorrect Letters:** Each time you guess a letter incorrectly, it will be added to the 'Incorrect Letters' row, making it easier to see which letters you've already tried.

### Point down the features

Game points:
Letter Boxes: You'll have a series of letter boxes where you can type your guesses for the hidden word.
Hint Provided: A hint will be given to help you figure out the word. Use this clue wisely to make your guesses.
Incorrect Letters: Each time you guess a letter incorrectly, it will be added to the 'Incorrect Letters' row, making it easier to see which letters you've already tried.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @MuraliDharan7 , You can't have another issue before completing the previous one 😀 
 you already have the following 1 open issues 👀 ! :

#4352

**Comment by kunjgit** [comment]
Hey @MuraliDharan7 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)
