### ISSUE TITLE
[New game]: Math Race Game

### ISSUE THREAD

**Issue by DharshiBalasubramaniyam** [kunjgit/GameZone#4418]
### 🎮 Game Request

Game logic and basic description

Start the game by answering the first math problem.
Submit the answer to move your car forward if correct.
Computer moves automatically after each question.
Continue answering until all 10 questions are answered.
The game declares the winner based on the number of correct answers.
Use the replay button to start a new game.

### Point down the features

Game points

nteractive Gameplay:

Players solve addition problems to move their car forward.
Computer opponent provides a challenging competitive element.
Scoring:

Each correct answer moves the player's car forward by 10 pixels.
Scores are tracked for both the player and the computer.
End of Game:

After 10 questions, the game stops.
Displays the final result, indicating the winner (player, computer, or tie).
Replayability:

Includes a "Replay" button to reset the game and start a new round.
User Interface:

Simple and intuitive UI with a race track, cars for player and computer, and an input field for answers.
Displays current question, result of the last answer (correct/incorrect), and final game result.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @DharshiBalasubramaniyam ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @DharshiBalasubramaniyam ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by kunjgit** [comment]
Hey @DharshiBalasubramaniyam ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by kunjgit** [comment]
Hey @DharshiBalasubramaniyam ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
