### ISSUE TITLE
[Documentation Bug]: Broken Links in README.md

### ISSUE THREAD

**Issue by GUNJESH843** [kunjgit/GameZone#4421]
### Describe the bug ✍️

The README.md file of the GameZone repository contains broken links. Several game names are listed as links, but they are not properly formatted or may be pointing to non-existent files or directories.

The broken links need to be fixed to ensure the smooth navigation and functionality of the documentation.

Step-by-step information to reproduce the bug 📄

1. Navigate to the README.md file of the GameZone repository.
2. Look for the list of games under the "Games" section.
3. Check each game name listed as a link.
4. Observe that several links are broken or improperly formatted.
![Screenshot 2024-06-10 214320](https://github.com/kunjgit/GameZone/assets/109446288/2a421879-a7be-4c16-9a39-f3464d53072f)

### Provide step by step information reproduce the bug 📄

I plan to address this issue by:

Reviewing the README.md file to identify all broken links.
Correcting the formatting of broken links or removing them if necessary.
Ensuring that all game names listed as links are functional and properly formatted.
Testing the updated README.md file to ensure all links are working as expected.

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @GUNJESH843 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by GUNJESH843** [comment]
@ishita-43, this issue is a follow-up to your comment(https://github.com/kunjgit/GameZone/pull/4253#issuecomment-2156542043) on my previous PR,

Just had a small request, if you could label my PR as level2.

Thankyou

**Comment by SohaFarhana** [comment]
Hello
I would like to work on this issue

**Comment by HareRamDwivedi** [comment]
Hello , assign me this issue under GSSOC24

**Comment by ishita-43** [comment]
The issues are assigned on basis of first come first serve however you can create issues related to topic which are not still addressed

**Comment by kunjgit** [comment]
Hey @GUNJESH843 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
