### ISSUE TITLE
[New game]:  Cricket  game

### ISSUE THREAD

**Issue by Gamerking177** [kunjgit/GameZone#4423]
### 🎮 Game Request

Game logic and basic description

it takes user input while clicking the button and the computer responds on the three options 

### Point down the features

Game points

if it draws no onne can get point if user wins user got the points and the user lost the game computer got the point and the score will store on the local storage

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by TheNikhilRaj** [comment]
I would like to work on this issue, please assign this to me.
@kunjgit

**Comment by kunjgit** [comment]
Hello @Gamerking177, Time's up!⏰ 
 Sorry for closing your issue! 
 But it's more than a week since we haven't received anything from your side 😢 . 
 Come up with new ideas, create a new issue and make sure you finish it within a week! 🔥 
 All the best! 🚀 
 Happy Hacking! 💗

**Comment by kunjgit** [comment]
Hey @Gamerking177 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
