### ISSUE TITLE
[New game]: Bullseye Game

### ISSUE THREAD

**Issue by narayani9120** [kunjgit/GameZone#4426]
### 🎮 Game Request

Experience the thrill of archery in this simple yet engaging game. Your objective is to hit the targets with precision by drawing, aiming, and releasing your arrows. Perfect for players of all ages, this game combines easy-to-learn mechanics with the challenge of mastering your aim.

### Point down the features

Game points
- Draw: Click and hold to draw the bowstring.
- Aim: Move the cursor to aim at the target.
- Release: Let go to release the arrow and watch it fly towards the target.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @narayani9120 , You can't have another issue before completing the previous one 😀 
 you already have the following 1 open issues 👀 ! :

#4405

**Comment by kunjgit** [comment]
Hey @narayani9120 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by kunjgit** [comment]
Hey @narayani9120 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)
