### ISSUE TITLE
[New game]: Tic Tac Toe 

### ISSUE THREAD

**Issue by ThisIsSahaj** [kunjgit/GameZone#4427]
### 🎮 Game Request

Tic Tac Toe is a traditional 2 player game. Where players take turn one by one to mark a cell out of 9

### Point down the features

If a player is able to mark 3 consecutive cells (horizontally/vertically/diagonally) then that player wins the game.
If no player is able to mark 3 consecutive cells, then the game is a draw

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @ThisIsSahaj , You can't have another issue before completing the previous one 😀 
 you already have the following 1 open issues 👀 ! :

#4393

**Comment by kunjgit** [comment]
Hey @ThisIsSahaj ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by kunjgit** [comment]
Hey @ThisIsSahaj ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)
