### ISSUE TITLE
[New game]: Add Mario Game

### ISSUE THREAD

**Issue by ananyag309** [kunjgit/GameZone#4430]
### 🎮 Game Request

Game logic and basic description - The Mario game series, created by Nintendo, centers around the adventures of Mario, an Italian plumber who embarks on various quests to rescue Princess Peach from the villainous Bowser. The series is known for its colorful graphics, engaging gameplay, and memorable characters.

In the classic platformers, players navigate Mario through levels filled with obstacles, enemies, and puzzles, collecting coins and power-ups along the way. Mario can gain abilities like throwing fireballs or becoming invincible with specific power-ups. The gameplay often involves jumping on platforms, avoiding hazards, and defeating enemies by stomping on them or using power-ups.

### Point down the features

Game points - 
I will add the best graphics, visuals 

@ku  please assign me this issue under gssoc

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @ananyag309 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @ananyag309 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
