### ISSUE TITLE
[Bug]: Texts not so visible in light mode.

### ISSUE THREAD

**Issue by sristy17** [kunjgit/GameZone#4438]
### Give a brief about the bug ✍️

Description
![Screenshot from 2024-06-11 18-53-24](https://github.com/kunjgit/GameZone/assets/136837204/14001966-453f-4577-a2ab-61c7be142211)

### What is the expected behavior? 🤔

Description

The text must be of different colours in light mode.

### Provide step by step information reproduce the bug 📄

Description

The text can be of different colour in light mode.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @sristy17 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @sristy17 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
