### ISSUE TITLE
[Enhancement]: Adding Scroll to the top

### ISSUE THREAD

**Issue by shishiro26** [kunjgit/GameZone#444]
### Is your enhancement request related to a problem? Please describe.➕

Game enhancement: Adding a "Scroll to Top" functionality to the hero page can greatly enhance the user experience, particularly when dealing with a large number of games. By implementing this feature, users will be able to quickly navigate back to the top of the page without the need for manual scrolling. This not only improves convenience but also boosts overall efficiency

### Describe the solution you'd like

Solution steps: Adding a scroll to the top in the heroPage 

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @shishiro26 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @shishiro26 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
