### ISSUE TITLE
[Bug]: Favorite Games button on home page is clearly visible

### ISSUE THREAD

**Issue by divyansh-2005** [kunjgit/GameZone#4442]
### Give a brief about the bug ✍️

![image](https://github.com/kunjgit/GameZone/assets/118552563/4f7c4f8a-3ac6-461f-b664-3551cb9af214)
the button is not Cleary visible.

### What is the expected behavior? 🤔

The icon or button can be changed and an hover animation to improve visibility. 

### Provide step by step information reproduce the bug 📄

Description

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @divyansh-2005 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by divyansh-2005** [comment]
assign

**Comment by HareRamDwivedi** [comment]
Please assign me this issue under GSSOC24

**Comment by kunjgit** [comment]
Hey @divyansh-2005 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
