### ISSUE TITLE
[Bug]: Game Cards are not shown 

### ISSUE THREAD

**Issue by divyansh-2005** [kunjgit/GameZone#4443]
### Give a brief about the bug ✍️

No Game card is visible on home page
![image](https://github.com/kunjgit/GameZone/assets/118552563/27d15f89-9aac-4da8-9e17-47ee7ad9151c)

### What is the expected behavior? 🤔

A List  of games mut be displayed. 

### Provide step by step information reproduce the bug 📄

Description

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @divyansh-2005 , You can't have another issue before completing the previous one 😀 
 you already have the following 1 open issues 👀 ! :

#4442

**Comment by kunjgit** [comment]
Hey @divyansh-2005 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)
