### ISSUE TITLE
[Bug]: No  game is showing

### ISSUE THREAD

**Issue by pandeyji711** [kunjgit/GameZone#4444]
### Give a brief about the bug ✍️

Description whille  visiting website no game is showing on page

please assign this task to me under Gssoc24 

### take a look 
![Screenshot 2024-06-12 020422](https://github.com/kunjgit/GameZone/assets/154527778/149142f7-125b-4d27-bb53-f60121eb2d08)

_No response_

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by pandeyji711** [comment]
@kunjgit can you please assign to me!!

**Comment by kunjgit** [comment]
Hello @pandeyji711, Time's up!⏰ 
 Sorry for closing your issue! 
 But it's more than a week since we haven't received anything from your side 😢 . 
 Come up with new ideas, create a new issue and make sure you finish it within a week! 🔥 
 All the best! 🚀 
 Happy Hacking! 💗

**Comment by kunjgit** [comment]
Hey @pandeyji711 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
