### ISSUE TITLE
[New game]: Round the Coils Correctly

### ISSUE THREAD

**Issue by Anjaliavv51** [kunjgit/GameZone#4447]
### 🎮 Game Request

Game logic and basic description

Coil is an addictive HTML5 game where you have to defeat your enemies by enclosing them in your trail. Most of the game is drawn on 2d canvas but if WebGL support is detected additional effects are added.

### Point down the features

Game points

coil the blue to get points except Red and Yellow.

https://github.com/ChromeGaming/GameSphere/assets/154777864/5f318234-9799-47b7-8655-117c71feda8b

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Anjaliavv51 , You can't have another issue before completing the previous one 😀 
 you already have the following 1 open issues 👀 ! :

#4317

**Comment by kunjgit** [comment]
Hey @Anjaliavv51 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by kunjgit** [comment]
Hey @Anjaliavv51 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)
