### ISSUE TITLE
[Bug]: Add Social media  Instagram

### ISSUE THREAD

**Issue by Gokilp** [kunjgit/GameZone#4458]
### Give a brief about the bug ✍️

Description

Footer Section was impressive and 

Add Social media  Instagram, Hash node

![image](https://github.com/kunjgit/GameZone/assets/76507378/1dd22594-f1bb-42c6-86fc-6a39f1ca3b22)

### What is the expected behavior? 🤔

Description

Footer Section was impressive and  Add Social media  Instagram, Hash node

### Provide step by step information reproduce the bug 📄

Description

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Gokilp ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by Gokilp** [comment]
please assign to me  Under Gssoc24

**Comment by Gokilp** [comment]
can please instagram and hash node profile link

**Comment by ishita-43** [comment]
You can self assign the task using assign

**Comment by Gokilp** [comment]
Thank you @ishita-43

**Comment by Gokilp** [comment]
please review my pr @ishita-43

**Comment by kunjgit** [comment]
Hey @Gokilp ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
