### ISSUE TITLE
Bug🪲 : Light mode gets turned off on refreshing a page 

### ISSUE THREAD

**Issue by Tejashri-Taral** [kunjgit/GameZone#4462]
### Give a brief about the bug ✍️

Description:
Here is the issue I encountered -
The light mode preference does not persist across page refreshes. Each time the page is refreshed, the mode resets to the default instead of maintaining the user-selected mode (dark or light).
I think it is due to the theme state is not being persisted when the page is refreshed.

### What is the expected behavior? 🤔

Description:
The selected dark or light mode should persist across page refreshes.
If a user selects light mode, the page should remain in dark mode even after refreshing.

### Provide step by step information reproduce the bug 📄

Description:
**Steps to reproduce the behavior:**

Go to the website.
Toggle the light mode switch to change the theme.
Refresh the page.
Observe that the theme reverts to the default mode instead of retaining the selected mode.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Tejashri-Taral ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by DakshantJain** [comment]
Hello @kunjgit,

I loved your beautifully designed website! I noticed a few areas where improvements could make it even more amazing. I'd be thrilled to help enhance its look and functionality for the best results.

Please consider assigning this task to me—I guarantee you'll be pleased with the outcome.

Thank you!

Best,
Dakshant Jain

**Comment by kunjgit** [comment]
Hey @Tejashri-Taral ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
