### ISSUE TITLE
[Bug]: Light mode

### ISSUE THREAD

**Issue by Bhumika1312** [kunjgit/GameZone#4464]
### Give a brief about the bug ✍️

Description
Upon clicking the toggle button, it switches to light mode. However, the text becomes invisible and difficult to comprehend.

![image](https://github.com/kunjgit/GameZone/assets/115869626/f3ad0056-9f67-473b-b3fd-10b36d95ebcd)

### What is the expected behavior? 🤔

Description
When the mode is switched to light or dark, the text colour should adjust accordingly to ensure easy readability.

### Provide step by step information reproduce the bug 📄

Description
I will change the colour of the text to make it readable when the modes are changed.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Bhumika1312 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by Bhumika1312** [comment]
sir this part is already completed by someone but it's not merged yet so I am closing this issue

**Comment by kunjgit** [comment]
Hey @Bhumika1312 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
