### ISSUE TITLE
[New game]: Kill the bird game

### ISSUE THREAD

**Issue by DiwareNamrata23** [kunjgit/GameZone#4465]
### 🎮 Game Request

Game logic and basic description. 
Steps to create this game:
In this game the birds will come randomly on the screen and for killing the bird we have to double click that bird so the maximum no of birds you kill the maximum points will get achieved.

### Point down the features

Game points
To implement this game . Below given some functionalities of this game:

the birds will come randomly to the screen it is your task that how much no of birds you can kill in the given time the score will be depend on the no of birds you killed.
Whenever the time gets  up the game is over.

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @DiwareNamrata23 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @DiwareNamrata23! 
We are already having a similar game request in #4414 👀 
Make sure you come up with a cool unique idea 😀 
 Waiting for your new game idea 💗.

**Comment by kunjgit** [comment]
Hey @DiwareNamrata23 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
