### ISSUE TITLE
[New game]: CopyCat

### ISSUE THREAD

**Issue by DiwareNamrata23** [kunjgit/GameZone#4466]
### 🎮 Game Request

Game logic and basic description
the game copy cat can be build using html css and js . the game consist of 2 cats and two homes separated by one division make you have to make use of arrows such that they reach their homes
<img width="584" alt="Screenshot 2024-06-12 at 5 00 19 PM" src="https://github.com/kunjgit/GameZone/assets/142529986/f38a44c8-a506-4f6d-9309-bc2a6a645aad">

### Point down the features

Game points
after winning each round the next level comes.

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @DiwareNamrata23 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @DiwareNamrata23 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
