### ISSUE TITLE
[New game]: Card Racing Game

### ISSUE THREAD

**Issue by Ayushmaanagarwal1211** [kunjgit/GameZone#4469]
### 🎮 Game Request

Game logic and basic description
Its a simple car racing racing where car is moving and our task is to defend it from other moving cars 

### Point down the features

Game points
1. A car is moving on the road
2. Their are many more vehicles on the road
3. we have to defend it from the other cars

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Ayushmaanagarwal1211 , You can't have another issue before completing the previous one 😀 
 you already have the following 1 open issues 👀 ! :

#4332

**Comment by kunjgit** [comment]
Hey @Ayushmaanagarwal1211 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by kunjgit** [comment]
Hey @Ayushmaanagarwal1211 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by Ayushmaanagarwal1211** [comment]
@kunjgit  Hii actually you didn't assigned that issue

**Comment by kunjgit** [comment]
Hey @Ayushmaanagarwal1211! 
We are already having a similar game request in #4333 👀 
Make sure you come up with a cool unique idea 😀 
 Waiting for your new game idea 💗.
