### ISSUE TITLE
Mine Sweaper

### ISSUE THREAD

**Issue by HareRamDwivedi** [kunjgit/GameZone#4470]
### 🎮 Game Request

# Objective:
The primary objective of Minesweeper is to clear a rectangular board containing hidden "mines" or bombs without detonating any of them. The player achieves this by uncovering all the non-mined squares.
# Gameplay Loop:
Starting the Game: The player selects a cell to reveal. If the cell contains a mine, the game ends. If it doesn't, it reveals either a number (indicating the number of adjacent mines) or an empty space.
Revealing Cells: Based on the revealed numbers, the player uses logic to deduce the locations of mines. The player continues to uncover cells or mark cells suspected of containing mines.
Marking Mines: The player can right-click (or use a similar input) to flag cells they believe contain mines, preventing accidental clicks on those cells.
Winning the Game: The game is won when all non-mined cells are uncovered, and all mines are either correctly flagged or identified.
Losing the Game: The game is lost if the player uncovers a cell containing a mine.
# Mechanics:
Revealing a Cell: Clicking on a cell reveals its content. If it’s a mine, the game ends. If it’s a number, it shows the count of adjacent mines. If it’s a blank (0 adjacent mines), all adjacent cells are automatically revealed.
Flagging a Cell: Right-clicking (or a similar action) on a cell flags it as a suspected mine. This helps in keeping track of potential mine locations.
Chaining Reveals: Revealing a cell with 0 adjacent mines causes a chain reaction, revealing all adjacent non-mine cells until cells with numbers are reached.
# Events and Triggers:
Initial Click: The first click is always safe and will not hit a mine. This ensures the game starts with a playable board.
Chain Reaction: Revealing a cell with no adjacent mines triggers the automatic reveal of connected non-mined cells.
Game Over: Hitting a mine ends the game, often revealing the entire board to show where all the mines were placed.
Victory: Uncovering all non-mined cells and/or correctly flagging all mines results in a victory notification.

### Point down the features

The primary objective of Minesweeper is to clear a rectangular board containing hidden "mines" or bombs without detonating any of them. The player achieves this by uncovering all the non-mined squares.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @HareRamDwivedi ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @HareRamDwivedi! 🙂 
 It seems like you are not following proper guidelines !! 👀 
 Read documentation properly !!🙏 
 If you have any queries reach out to us on [Discord🕹️](https://discord.gg/fgwk4XZfxG) .

**Comment by kunjgit** [comment]
Hey @HareRamDwivedi ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
