### ISSUE TITLE
[New game]: Bunny

### ISSUE THREAD

**Issue by divyansh-2005** [kunjgit/GameZone#4478]
### 🎮 Game Request

**Game Logic:**  
In "Bunny is Lost!", players control a bunny escaping a forest fire by jumping over obstacles and collecting carrots to maintain health. The game starts with a "Run!" button and features a main loop updating the bunny's movement, health, and collision with enemies like birds. The game ends if the bunny's health drops to zero or it gets caught by a bird.

![image](https://github.com/kunjgit/GameZone/assets/118552563/ed387f7c-3a74-41d0-a8b3-b1cbe557a916)

### Point down the features

Game points **Features:**  
- Dynamic scaling for different devices
- Procedurally generated background music
- Interactive controls via keyboard or touch
- Collectible carrots for health
- Challenging obstacles and enemies
- Visual health and jump indicators
- Endgame feedback on bunny’s fate

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @divyansh-2005 , You can't have another issue before completing the previous one 😀 
 you already have the following 1 open issues 👀 ! :

#4442

**Comment by kunjgit** [comment]
Hey @divyansh-2005 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)
