### ISSUE TITLE
[New game]: Bunny is Lost!

### ISSUE THREAD

**Issue by divyansh-2005** [kunjgit/GameZone#4479]
### 🎮 Game Request

**Game Logic:**  
In "Bunny is Lost!", players control a bunny escaping a forest fire by jumping over obstacles and collecting carrots to maintain health. The game starts with a "Run!" button and features a main loop updating the bunny's movement, health, and collision with enemies like birds. The game ends if the bunny's health drops to zero or it gets caught by a bird.

![image](https://github.com/kunjgit/GameZone/assets/118552563/ed387f7c-3a74-41d0-a8b3-b1cbe557a916)

### Point down the features

Game points **Features:**  
- Dynamic scaling for different devices
- Procedurally generated background music
- Interactive controls via keyboard or touch
- Collectible carrots for health
- Challenging obstacles and enemies
- Visual health and jump indicators
- Endgame feedback on bunny’s fate

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @divyansh-2005 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by divyansh-2005** [comment]
Please assign me this task so that I can work on it as soon as possible under GSSOC'24.

**Comment by kunjgit** [comment]
Hey @divyansh-2005 ! , This issue is already assigned to @shivan2004. 💗 
 You can work on other issues 🚀 
 If there is anything wrong you can contact us on [Discord🕹️](https://discord.gg/fgwk4XZfxG)👀

**Comment by divyansh-2005** [comment]
Issue was created my me. Kindly assign me, I have the code ready for the game.

**Comment by kunjgit** [comment]
Hey @divyansh-2005 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
