### ISSUE TITLE
[New game]: Etch a Sketch 2

### ISSUE THREAD

**Issue by TexZ-GenZ** [kunjgit/GameZone#4484]
### 🎮 Game Request

Game logic and basic description:
Etch-a-Sketch is a delightful web-based drawing game that combines simplicity and creativity, inspired by the classic Etch-a-Sketch toy. This interactive game allows users to create vibrant patterns and drawings on a grid, offering various modes for different artistic expressions. The game's intuitive interface and dynamic functionality make it an engaging tool for users of all ages.

Game Logic:
The core of Etch-a-Sketch lies in its grid-based canvas. Users can dynamically adjust the grid size, with each cell of the grid serving as a pixel for drawing. The game features three main drawing modes: Monochromatic, Random Colors, and Darken. Each mode offers a unique way to interact with the grid and create distinct visual effects.

### Point down the features

Grid Creation:

Grid Size: Users can set the grid size by clicking the "Set Grid Size" button. The grid can be adjusted up to a maximum of 100x100 cells.
Cell Dimensions: The dimensions of each cell are dynamically calculated based on the grid size, ensuring the entire grid fits within a 600x600 pixel container.

Drawing Modes:

1: Monochromatic Mode: In this mode, hovering over grid cells colors them red. It is the simplest mode, ideal for straightforward and bold designs.
2: Random Colors Mode: This mode adds an element of surprise and vibrancy. Each cell changes to a randomly generated RGB color when hovered over, creating a colorful and dynamic drawing experience.
3: Darken Mode: This mode introduces a shading effect. Initially, all cells are black with 0% opacity. Hovering over a cell increases its opacity incrementally by 10%, gradually darkening the cell until it reaches full opacity.

Features:

1->Dynamic Grid Adjustment: Users can easily change the grid size to accommodate detailed or broad designs.
2->Multiple Drawing Modes: Three distinct modes provide versatility in drawing styles and effects.
3->Interactive Hover Effects: Real-time color changes and shading effects create an engaging and responsive drawing experience.
4->User-Friendly Interface: The game features a simple and intuitive interface with clearly labeled buttons and a clean design, making it accessible to all users.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @TexZ-GenZ ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @TexZ-GenZ ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
