### ISSUE TITLE
[New game]: Minesweeper Easy

### ISSUE THREAD

**Issue by ThisIsSahaj** [kunjgit/GameZone#4488]
### 🎮 Game Request

Game logic and basic description
Minesweeper is a classic puzzle game that involves a grid of squares. Some squares contain mines, while others do not. 
The objective of the game is to reveal all the squares that do not contain mines without triggering any mines.

### Point down the features

Game points
Players can flag squares they suspect to contain mines to avoid triggering them accidentally.
If the player reveals a cell containing a mine, the game is over

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @ThisIsSahaj ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @ThisIsSahaj ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
