### ISSUE TITLE
[New game]:  project addition by MonoPoly Game addition

### ISSUE THREAD

**Issue by Damini2004** [kunjgit/GameZone#4490]
### 🎮 Game Request

Game logic and basic description
Monopoly is a classic board game where players compete to acquire wealth through buying, renting, and trading properties. The objective is to drive opponents into bankruptcy, thus becoming the richest player by the end of the game.

### Point down the features

Game points
Players: 2 to 8 players.
Board: The board consists of 40 spaces, including 28 properties, 3 Chance spaces, 3 Community Chest spaces, 4 railroads, 2 utilities, a "Go" space, a "Jail" space, a "Free Parking" space, and a "Go to Jail" space.
Tokens: Each player selects a token to move around the board.
Money: Players start with a set amount of money.

![image](https://github.com/kunjgit/GameZone/assets/119414762/cd77356c-06cb-46cf-bcc7-c035cf7180f1)

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Damini2004 , You can't have another issue before completing the previous one 😀 
 you already have the following 2 open issues 👀 ! :

#4483
#3896

**Comment by kunjgit** [comment]
Hey @Damini2004 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by kunjgit** [comment]
Hey @Damini2004 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)
