### ISSUE TITLE
[New game]: Pac-Man Game

### ISSUE THREAD

**Issue by Parul1606** [kunjgit/GameZone#45]
### 🎮 Game Request

Pac-Man is a classic arcade game where the player controls a character named Pac-Man, who navigates a maze filled with pellets and ghosts. The objective is to eat all the pellets while avoiding the ghosts. 
Basic logic behind this games will be: 
1. Display a maze consisting of walls, pellets, power pellets and ghosts.
2. Allow the player to control Pac-Man using arrow keys to navigate the maze.
3. Generate ghosts that move through the maze and chase Pac-Man.
4. Implement collision detection to check if Pac-Man collides with a ghost or vice versa.
5. When Pac-Man eats a power pellet, the ghosts turn blue and become edible for a limited time.
6. Keep track of the player's score based on the number of pellets.
7. End the game if any of the following conditions are met:
   Pac-Man loses live by colliding with a ghost.
   Pac-Man eats all the pellets in the maze.

### Point down the features

Features I'm going to add in this game are:
1. Pac-Man control -  Allow the player to control Pac-Man's movement using arrow keys or WASD keys to navigate the maze.
2. Maze-Design: Create a maze with walls and corridors where Pac-Man and the ghosts can move. 
3. Pellets and Power Pellets: Scatter small pellets throughout the maze for Pac-Man to eat. 
4. Collision Detection: Detect collisions between Pac-Man and the ghosts, as well as between Pac-Man and the walls of the maze.
5. Score Tracking: Keep track of the player's score based on the number of pellets and ghosts eaten. Display the current score on the game screen.
6. Lives and Game Over: Give Pac-Man a live at the start of the game. When Pac-Man collides with a ghost, game stops there.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey  @Parul1606 ! Thank you for raising an issue 💗 You have been assigned this issue you can start working on the issue 🎮

**Comment by Parul1606** [comment]
Thank you @kunjgit ! I will try my best to give to this project.

**Comment by kunjgit** [comment]
Hey @Parul1606 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
