### ISSUE TITLE
[New game]: Catch the fruit

### ISSUE THREAD

**Issue by sudarshan-hub** [kunjgit/GameZone#450]
### 🎮 Game Request

**Game Logic:**

1. The game is a simple catch-the-falling-fruit game where the player controls a character to catch falling fruits.
2. The player can move horizontally within the game container using the mouse.
3. Fruits fall from the top of the game container and the player needs to position themselves to catch the falling fruits.
4. When a fruit is caught, the player's score increases.
5. If a fruit reaches the bottom without being caught, it resets to the top, and the game continues.
6. The game continues indefinitely, allowing the player to try to achieve the highest score possible.

### Point down the features

 **Features of the Game:**

1. **Player Control:** The player can move horizontally within the game container by moving the mouse.
2. **Falling Fruits:** Fruits fall from the top of the game container and the player needs to catch them.
3. **Score Tracking:** The player's score is displayed at the top of the game container and increases each time a fruit is caught.
4. **Continuous Gameplay:** The game continues indefinitely, allowing the player to catch as many fruits as possible and try to achieve a high score.
5. **Dynamic Difficulty:** The speed at which the fruits fall can be adjusted to increase the difficulty as the game progresses.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @sudarshan-hub ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hello @sudarshan-hub, Time's Uppp!⏰ 
 Sorry for closing your issue! 
 But it's more than a week since we haven't received anything from your side 😢 . 
 Come up with new ideas, create a new issue and make sure you finish it within a week! 🔥 
 All the best! 🚀 
 Happy Hacking! 💗

**Comment by kunjgit** [comment]
Hey @sudarshan-hub ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
