### ISSUE TITLE
Update CONTRIBUTION.md 

### ISSUE THREAD

**Issue by 1754riya** [kunjgit/GameZone#4500]
### Is there an existing issue for this?
I have searched the existing issues

### Feature Description
I would like to learn more about the contributing guidelines such as:

1. Code Style
2. Testing
3. Spread the Word
4. Community Guidelines
5. Resources for Guidance
6. Code Review
7. Feature Requests
8. Contributing Guidelines
9. Code of Conduct

### Priority
High

### Record
I have read the Contributing Guidelines
I'm a GSSOC'24 contributor
I have starred the repository

@kunjgit , Please assign me this issue.

**Comment by kunjgit** [comment]
Hey @1754riya ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @1754riya! 🙂 
 It seems like you are not following proper guidelines !! 👀 
 Read documentation properly !!🙏 
 If you have any queries reach out to us on [Discord🕹️](https://discord.gg/fgwk4XZfxG) .

**Comment by kunjgit** [comment]
Hey @1754riya ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
