### ISSUE TITLE
[New game]: Quest For Riches

### ISSUE THREAD

**Issue by peculiap1** [kunjgit/GameZone#4505]
### 🎮 Game Request

Quest for Riches is a side-scrolling action-adventure game where players navigate through a fantasy world, battling enemies and solving puzzles to find a hidden treasure. The game includes a health system, enemy AI, player combat mechanics, and level progression.

### Point down the features

- Movement (run, jump, attack
- Health system with health bar
- Animations for idle, running, jumping, attacking, hurt, and dying.
- NPC's 
- Enemy detects and chases player
- Enemy Attack mechanics
- Two levels
- Unlockable treasure chest after defeating enemies and solving a puzzle.

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @peculiap1 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @peculiap1 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
