### ISSUE TITLE
[New game]: PIXEL PAINTER

### ISSUE THREAD

**Issue by aadyagupta44** [kunjgit/GameZone#4508]
### 🎮 Game Request

Pixel Painter is a drawing game where players can create pixel art. The game features a grid canvas where each cell represents a pixel. Players can select colors from a palette and fill in the pixels to create their artwork. 

### Point down the features

Pixel Painter Game Features
1. Interactive Grid Canvas-
Pixel Grid: The game features a dynamic grid where each cell represents a pixel. Users can draw by clicking on the cells.
Customizable Size: The canvas size can be adjusted, allowing users to choose the number of pixels horizontally and vertically.

2. Extensive Color Palette-
Color Selection: A wide range of colors is available for users to select from and apply to their pixel art.
Color Preview: The selected color is displayed prominently to provide visual feedback.

3. Versatile Drawing Tools-
Pencil Tool: Users can click on individual pixels to color them with the selected color.
Eraser Tool: Users can click on pixels to revert them to the default background color (white).
Fill Tool: Users can click on a pixel to fill an area with the selected color, similar to a paint bucket tool in traditional drawing applications.
Clear Canvas: A button to reset the entire canvas, clearing all drawings.

4. Save & Share Functionality-
Save Artwork: Users can save their artwork locally as an image file.
Shareable Links: Users can generate a shareable link that encodes their artwork, allowing others to view it by opening the link.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @aadyagupta44 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hello @aadyagupta44, Time's up!⏰ 
 Sorry for closing your issue! 
 But it's more than a week since we haven't received anything from your side 😢 . 
 Come up with new ideas, create a new issue and make sure you finish it within a week! 🔥 
 All the best! 🚀 
 Happy Hacking! 💗

**Comment by kunjgit** [comment]
Hey @aadyagupta44 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
