### ISSUE TITLE
[New game]: A simple pottery Game

### ISSUE THREAD

**Issue by VesperAkshay** [kunjgit/GameZone#4509]
### 🎮 Game Request

# Issue Description

### Description:
The application should include a simple game focused on pottery making. The game should allow users to engage in the process of creating pottery, including steps such as:

1. Shaping the clay - Users should be able to mold and shape a piece of clay into the desired form for a pottery item.

2. Decorating the pottery - Users should have the ability to add decorative elements, patterns, or glazes to the shaped pottery.

3. Firing the pottery - The game should simulate the firing process in a kiln to harden and finalize the pottery piece.

4. Displaying the final product - Once complete, the finished pottery item should be showcased to the user, allowing them to admire their handiwork.

The game should have an intuitive and user-friendly interface, guiding players through the pottery making steps in a smooth and engaging manner. Appropriate sound effects, animations, and visual feedback should be incorporated to enhance the pottery game experience.

### Features:
- **Clay Shaping**: Users should be able to manipulate and shape a piece of clay using various tools and techniques, such as pinching, coiling, and throwing.
- **Firing Process**: The game should simulate the firing process in a kiln, where the pottery is heated to high temperatures to harden and set the final form.
- **Final Product Display**: Upon completing the pottery-making process, the finished piece should be showcased to the user, with the ability to rotate and zoom in on the creation.
- **User Progress Tracking**: The game should keep track of the user's progress, allowing them to view their previous pottery creations and achievements.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @VesperAkshay , You can't have another issue before completing the previous one 😀 
 you already have the following 1 open issues 👀 ! :

#4401

**Comment by kunjgit** [comment]
Hey @VesperAkshay ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by kunjgit** [comment]
Hey @VesperAkshay ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)
