### ISSUE TITLE
[Documentation Bug]: Fix Text in README

### ISSUE THREAD

**Issue by Sriparno08** [kunjgit/GameZone#451]
### Describe the bug ✍️

I have notcied some typos in README.

![Screenshot 2023-05-26 213057](https://github.com/kunjgit/GameZone/assets/89148144/2f9529eb-f824-4d26-bec9-620bf9fe3a91)

This sentence:

> Make sure select the program in which you are participating to

needs to be changed to:

> Make sure you select the program in which you are participating

I would like to contribute it as part of GSSoC'23.

### Provide step by step information reproduce the bug 📄

Description

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Sriparno08 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @Sriparno08 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
