### ISSUE TITLE
[New game]: Pokemon Style game

### ISSUE THREAD

**Issue by VesperAkshay** [kunjgit/GameZone#4512]
#### Description
The team has identified the need to create a game with a "Pokemon-style" gameplay, where users can catch, train, and battle with various creatures or characters.

### Point down the features

 **Combat and Battles**:
  - The game should have a turn-based or real-time combat system where players pit their creatures/characters against others
  - Battles should have strategic depth, with different move types, elemental advantages, and team compositions
  - Players should be able to participate in both single-player and multiplayer battles

- **Progression and Advancement**:
  - The game should have a structured progression system, with various challenges, quests, or storylines for the player to complete
  - Completing these challenges should reward the player with new creatures/characters, items, or access to new areas
  - The progression system should provide a sense of accomplishment and encourage players to continue their journey

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @VesperAkshay , You can't have another issue before completing the previous one 😀 
 you already have the following 1 open issues 👀 ! :

#4510

**Comment by kunjgit** [comment]
Hey @VesperAkshay ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by kunjgit** [comment]
Hey @VesperAkshay ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)
