### ISSUE TITLE
[New game]: Sliding puzzle Game

### ISSUE THREAD

**Issue by Anshika-17** [kunjgit/GameZone#4513]
### 🎮 Game Request

# Sliding Puzzle Game

## Overview
Sliding Puzzle Game is a classic brain-teasing puzzle game where players need to rearrange a set of numbered tiles to match a target pattern. The tiles are initially scrambled and the objective is to slide the tiles horizontally or vertically to restore the correct numerical order.

## Gameplay
The game board consists of a grid of tiles, with one tile missing to allow the other tiles to slide. Players can move the tiles by clicking on the empty space and dragging the adjacent tile into it. The goal is to arrange the tiles in the correct numerical order, from 1 to the total number of tiles on the board.

## Features
- Adjustable grid size: The game offers different difficulty levels by allowing players to choose the size of the grid, ranging from 3x3 to 6x6.
- Timer and move counter: The game tracks the time taken to solve the puzzle and the number of moves made, providing a challenge for players to improve their efficiency.
- Randomized initial configuration: Each new game presents a unique scrambled arrangement of the tiles, ensuring a fresh challenge every time.
- Hint and reset options: The game provides a hint feature to assist players, as well as a reset option to start a new game from the beginning.
- Leaderboard and achievements: Players can compete against each other by sharing their high scores and fastest times, unlocking various achievements for their accomplishments.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Anshika-17 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @Anshika-17 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
