### ISSUE TITLE
[Bug]:  In light mode, the text color should be changed

### ISSUE THREAD

**Issue by bheemajayashreee** [kunjgit/GameZone#4515]
### Give a brief about the bug ✍️

The text color should be changed in light-mode as it is visually not appealing.
![image](https://github.com/kunjgit/GameZone/assets/112753765/1bacf0e1-be0e-4705-8303-92eb9ffa63a8)

### What is the expected behavior? 🤔

The text-color should be dark.

### Provide step by step information reproduce the bug 📄

1. Go to light mode.
2. See the error

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @bheemajayashreee ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by bheemajayashreee** [comment]
/assign 
this to me with respective label

**Comment by kunjgit** [comment]
Hey @Sristy-72 ! , This issue is already assigned to @bheemajayashreee. 💗 
 You can work on other issues 🚀 
 If there is anything wrong you can contact us on [Discord🕹️](https://discord.gg/fgwk4XZfxG)👀

**Comment by bheemajayashreee** [comment]
can u please provide a respective label for this

**Comment by kunjgit** [comment]
Hello @bheemajayashreee, Time's up!⏰ 
 Sorry for closing your issue! 
 But it's more than a week since we haven't received anything from your side 😢 . 
 Come up with new ideas, create a new issue and make sure you finish it within a week! 🔥 
 All the best! 🚀 
 Happy Hacking! 💗

**Comment by kunjgit** [comment]
Hey @bheemajayashreee ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
