### ISSUE TITLE
Can add a go to top button 

### ISSUE THREAD

**Issue by bheemajayashreee** [kunjgit/GameZone#4516]
### Give a brief about the bug ✍️

There can be go to top button added for easy navigation in the page.

![image](https://github.com/kunjgit/GameZone/assets/112753765/3f9ad1e5-fd6d-4910-94a3-c1e4461ded62)

### What is the expected behavior? 🤔

The go to top button will get you to the top of the page

### Provide step by step information reproduce the bug 📄

1. Go to bottom of the page.
2. Try to go up.
3. See the error.

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @bheemajayashreee , You can't have another issue before completing the previous one 😀 
 you already have the following 1 open issues 👀 ! :

#4515

**Comment by kunjgit** [comment]
Hey @bheemajayashreee ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by kunjgit** [comment]
Hey @bheemajayashreee ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @bheemajayashreee! 🙂 
 It seems like you are not following proper guidelines !! 👀 
 Read documentation properly !!🙏 
 If you have any queries reach out to us on [Discord🕹️](https://discord.gg/fgwk4XZfxG) .

**Comment by bheemajayashreee** [comment]
Please assign this to me
