### ISSUE TITLE
[Bug]: Cursor Problem

### ISSUE THREAD

**Issue by CoderGirl2844** [kunjgit/GameZone#4517]
### Give a brief about the bug ✍️

We can see a double cursor and in light mode the cursor vanishes

https://github.com/kunjgit/GameZone/assets/155231566/51bb1f2f-87c2-43a4-bd2b-fdc1cecf0c74

### What is the expected behavior? 🤔

only one cursor should be shown, and it should not vanish

### Provide step by step information reproduce the bug 📄

Fix this issue by changing the styling of cursor

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @CoderGirl2844 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by CoderGirl2844** [comment]
assign this issue to me and please add the level label

**Comment by kunjgit** [comment]
Hello @CoderGirl2844, Time's up!⏰ 
 Sorry for closing your issue! 
 But it's more than a week since we haven't received anything from your side 😢 . 
 Come up with new ideas, create a new issue and make sure you finish it within a week! 🔥 
 All the best! 🚀 
 Happy Hacking! 💗

**Comment by kunjgit** [comment]
Hey @CoderGirl2844 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
