### ISSUE TITLE
[Enhancement]:  Adding a About us page for modulo game 

### ISSUE THREAD

**Issue by Ayushmaanagarwal1211** [kunjgit/GameZone#4518]
### Do you want to have the enhancement of existing game ? 😀 Describe yourself..

Game enhancement
I will add a about us page for modulo game describing how to play the game because this may be tough for some peoples to understand this game 

### Describe the solution you'd like

Solution steps
Changes in some html file and creating a new file for about us page 

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Ayushmaanagarwal1211 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by Ayushmaanagarwal1211** [comment]
Ok i am starting working on it please assign it

**Comment by ishita-43** [comment]
YOU CAN always self assign the issues in this repository

**Comment by Ayushmaanagarwal1211** [comment]
Ok sure

**Comment by kunjgit** [comment]
Hey @Ayushmaanagarwal1211 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
