### ISSUE TITLE
[New game]:  Add Alien Invaders Game 

### ISSUE THREAD

**Issue by Ayushmaanagarwal1211** [kunjgit/GameZone#4519]
### 🎮 Game Request

Game logic and basic description
The primary goal of the game is to shoot down all the aliens before they reach the bottom of the screen. The player must move the spaceship left and right to avoid the aliens and strategically position themselves to shoot the aliens.

### Point down the features

Game points
Collision Detection: The game detects collisions between the bullets and aliens. When a collision is detected, the alien is destroyed, and the bullet is removed from the screen.
Alien Movement: The aliens move in a group, bouncing off the edges of the screen and moving downward with each bounce, creating a progressively challenging game environment.
Animation Loop: The game uses an animation loop to continually redraw the canvas, update the positions of the spaceship, bullets, and aliens, and check for collisions, making the game interactive and dynamic.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Ayushmaanagarwal1211 , You can't have another issue before completing the previous one 😀 
 you already have the following 1 open issues 👀 ! :

#4518

**Comment by kunjgit** [comment]
Hey @Ayushmaanagarwal1211 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by kunjgit** [comment]
Hey @Ayushmaanagarwal1211 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)
