### ISSUE TITLE
[New game]:  Sound Wordle Game

### ISSUE THREAD

**Issue by abckhush** [kunjgit/GameZone#4520]
### 🎮 Game Request

In this game, a tune will be played, and the user has to guess the name of the song in 5 guesses.

### Point down the features

1. The user will be given 5 chances.
2. The tune can be played as many times as the user wants.
3. If the letter is used in the word, it will become yellow.
4. If the letter is in the right place in the word, it will become green.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @abckhush , You can't have another issue before completing the previous one 😀 
 you already have the following 1 open issues 👀 ! :

#4408

**Comment by kunjgit** [comment]
Hey @abckhush ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by kunjgit** [comment]
Hey @abckhush ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @abckhush! 
We are already having a similar game request in #4406 👀 
Make sure you come up with a cool unique idea 😀 
 Waiting for your new game idea 💗.

**Comment by abckhush** [comment]
Hi @kunjgit. For issue #4408 I have opened the PR and it has the label of "ready to merge". If you could merge it, I will be able to work on this new issue.

The issue #4406 is the Word Shuffle Game. My game is different. It uses audio and is not unscrambling of words, it is more of a guessing game. Like a wordle but using audio.
