### ISSUE TITLE
[Enhancement]: Taash game

### ISSUE THREAD

**Issue by sivaprasath2004** [kunjgit/GameZone#4521]
### Do you want to have the enhancement of existing game ? 😀 Describe yourself..

- In this game cannot upproach proper UI.
- I will make Redesign it.
- please assign me..

### Describe the solution you'd like

![Screenshot from 2024-06-14 16-23-24](https://github.com/kunjgit/GameZone/assets/121082414/cc119f95-294b-4739-ba20-ab65ef2923c4)

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @sivaprasath2004 , You can't have another issue before completing the previous one 😀 
 you already have the following 1 open issues 👀 ! :

#4308

**Comment by kunjgit** [comment]
Hey @sivaprasath2004 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by kunjgit** [comment]
Hey @sivaprasath2004 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)
