### ISSUE TITLE
 Catch Egg Game

### ISSUE THREAD

**Issue by narayani9120** [kunjgit/GameZone#4526]
### 🎮 Game Request

To showcase your skills, collect the falling eggs from the chicken. Be quick and catch the eggs that are dropped by the chicken.

### Point down the features

**Scoring:** Earn points for each egg caught.
**Lives:** Start with 5 lives. Lose a life for each egg missed. Game over when lives reach 0.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @narayani9120 , You can't have another issue before completing the previous one 😀 
 you already have the following 1 open issues 👀 ! :

#4405

**Comment by kunjgit** [comment]
Hey @narayani9120 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by kunjgit** [comment]
Hey @narayani9120 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @narayani9120! 🙂 
 It seems like you are not following proper guidelines !! 👀 
 Read documentation properly !!🙏 
 If you have any queries reach out to us on [Discord🕹️](https://discord.gg/fgwk4XZfxG) .
