### ISSUE TITLE
[New game]: Drawing App Game

### ISSUE THREAD

**Issue by revanth1718** [kunjgit/GameZone#4528]
### 🎮 Game Request

Drawing App created with HTML, CSS, and JavaScript. This application will allow users to create drawings using various shapes and colors, offering a simple yet engaging drawing experience directly in the browser.
- Users select a tool and color, then interact with the canvas by clicking and dragging the mouse to draw.
- When a shape is selected, users click to define the shape's position and dimensions.
- The fill color option will fill shapes with the selected color, while the brush will allow for continuous freehand drawing.

### Point down the features

![drawing app](https://github.com/kunjgit/GameZone/assets/109272714/6554beb3-1958-49a7-a263-90ad2372e093)

This Drawing App will be a fun and creative addition to our collection of web-based games, offering users a simple yet powerful tool to create and share their artwork. 

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @revanth1718 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)
