### ISSUE TITLE
[New game]: Color Match Game

### ISSUE THREAD

**Issue by sanayamahajan-23** [kunjgit/GameZone#4529]
### 🎮 Game Request

"Color Match Challenge" is a fast-paced game where players must quickly identify and select the correct color based on a given prompt. Each prompt specifies a color either by name (e.g., "Select the color that matches 'Blue'") or visually (e.g., "Select the color that matches this color swatch"). Players then choose the corresponding color from a set of options.

### Point down the features

Color Prompt Generation: The game generates color-related prompts randomly, challenging players with color names or visual representations.

Color Options: Players are presented with clickable buttons, each representing a different color. One button corresponds correctly with the prompt, while the others are incorrect.

Timing and Speed: The game may incorporate a timer to add urgency, rewarding players based on how quickly they select the correct color.

Scoring System: Points are awarded for each correct selection. Players aim to achieve high scores by making accurate and swift choices.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @sanayamahajan-23 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @sanayamahajan-23! 
We are already having a similar game request in #4311 👀 
Make sure you come up with a cool unique idea 😀 
 Waiting for your new game idea 💗.

**Comment by kunjgit** [comment]
Hey @sanayamahajan-23 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
