### ISSUE TITLE
[New game]: Maze Runner

### ISSUE THREAD

**Issue by sanayamahajan-23** [kunjgit/GameZone#4530]
### 🎮 Game Request

"Maze Runner" is a dynamic and challenging game where players navigate through a series of increasingly complex mazes. The goal is to reach the exit of each maze as quickly as possible while avoiding obstacles and collecting bonuses along the way.

### Point down the features

Randomly Generated Mazes:

The game generates new mazes dynamically for each level, ensuring endless gameplay variety.
Interactive Gameplay:

Players control a character (e.g., a sprite or icon) using arrow keys or touchscreen controls to navigate through the maze.
Obstacles and Challenges:

Mazes include walls and other obstacles that players must navigate around to reach the exit.
Bonuses and Power-Ups:

Collectible items within the maze provide bonuses such as speed boosts, temporary invincibility, or shortcuts.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @sanayamahajan-23 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @sanayamahajan-23 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
