### ISSUE TITLE
Add Light mode 

### ISSUE THREAD

**Issue by coder-chahal** [kunjgit/GameZone#454]
heyy @kunjgit i want to work on this issue. Please assign this to me under GSSoC'23.

**Comment by kunjgit** [comment]
Hey @coder-chahal! 🙂 
 It seems like you are not following proper guidelines !! 👀 
 Read documentation properly !!🙏 
 If you have any queries reach out to us on [Discord🕹️](https://discord.gg/fgwk4XZfxG) .

**Comment by kunjgit** [comment]
Hey @coder-chahal ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
