### ISSUE TITLE
[New game]: Mathematics Escape Room

### ISSUE THREAD

**Issue by tanishaprasad** [kunjgit/GameZone#4542]
### 🎮 Game Request

Mathematics Escape Room is a game where the player solves math puzzles to progress through different rooms of an imaginary escape room.
Players navigate through different rooms by solving mathematical puzzles.
Each room presents a new challenge or puzzle related to a specific mathematical concept.

### Point down the features

Room Navigation:

Players navigate through different rooms by solving mathematical puzzles.
Each room presents a new challenge or puzzle related to a specific mathematical concept.

Progression System:

Players advance from one room to the next upon solving the puzzle correctly.
Each room's puzzle difficulty can increase progressively.

Feedback :

Immediate feedback on each puzzle attempt (correct or incorrect).

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @tanishaprasad ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @tanishaprasad ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
