### ISSUE TITLE
[New game]: Guess my number game

### ISSUE THREAD

**Issue by khushbumaheshwarii** [kunjgit/GameZone#455]
### 🎮 Game Request

Game logic and basic description 

It's a game where you have to guess the number between 1-20 .
if you guess it right you will win the game 

### Point down the features

Game points

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @khushbumaheshwarii ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by khushbumaheshwarii** [comment]
assing my self and make a PR plz review it.

**Comment by Harshvardhan-Dubey-Github** [comment]
please assign me this issue

**Comment by kunjgit** [comment]
Hey @khushbumaheshwarii ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
