### ISSUE TITLE
font color not change when theme is light, it is difficult to read

### ISSUE THREAD

**Issue by AnkitMourya12** [kunjgit/GameZone#4552]
### Give a brief about the bug ✍️

The Fix: where the font color isn't changing when you switch to the light theme. It's a bug or oversight in the code that controls the theme styles.
<img width="1034" alt="game1" src="https://github.com/kunjgit/GameZone/assets/121748364/15eecd75-090b-42b9-a721-b409c4617756">

### What is the expected behavior? 🤔

DescriptionThe primary goal is to maintain good contrast between text and background for optimal readability.
The color change should be automatic and occur seamlessly upon switching themes.

### Provide step by step information reproduce the bug 📄

1. Environment Setup:

Open your web application or website.
Ensure you have the ability to switch between light and dark themes (if applicable).
2. Reproduce the Bug:

Start with the dark theme applied. Verify that the font color is appropriate for a dark theme (e.g., white or light gray).
Switch to the light theme using the designated theme control (button, menu option, etc.).
3. Observe the Issue:

Inspect the font color of text elements throughout the application/website.
Focus on areas where text is expected to be clearly visible, such as navigation menus, body text, labels, and buttons.
4. Expected Behavior:

Upon switching to the light theme, the font color should change to a color suitable for a light background (e.g., black or dark gray).
5. Actual Behavior:

If the font color remains unchanged or is difficult to read against the light background, then the bug is confirmed.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @AnkitMourya12 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @AnkitMourya12! 🙂 
 It seems like you are not following proper guidelines !! 👀 
 Read documentation properly !!🙏 
 If you have any queries reach out to us on [Discord🕹️](https://discord.gg/fgwk4XZfxG) .

**Comment by kunjgit** [comment]
Hey @AnkitMourya12 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by AnkitMourya12** [comment]
please assign this issue to me @kunjgit  under required  gssoc'24 lables
