### ISSUE TITLE
[New game]: Cross the river game

### ISSUE THREAD

**Issue by DiwareNamrata23** [kunjgit/GameZone#4556]
### 🎮 Game Request

Game logic and basic description
A farmer needs to cross a river with a wolf, a goat, and a cabbage. The boat can only carry the farmer and one of the other three items at a time. The challenge is to get all three items across the river without leaving the wolf alone with the goat (the wolf would eat the goat) or the goat alone with the cabbage (the goat would eat the cabbage).

### Point down the features

Game points
1. The boat can only carry the farmer and one other item at a time.
2. The farmer cannot leave the wolf alone with the goat.
3. The farmer cannot leave the goat alone with the cabbage.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by DiwareNamrata23** [comment]
/ assign

**Comment by kunjgit** [comment]
Hey @DiwareNamrata23 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @DiwareNamrata23 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
