### ISSUE TITLE
[New game]:  Add Mario Matching Game

### ISSUE THREAD

**Issue by ananyag309** [kunjgit/GameZone#4557]
### 🎮 Game Request

Game logic and basic description:
Complete all pairs of Mario-themed pictures by stopping the moving lines at the right moment.

### Point down the features

Game points
The game board displays three lines of pictures moving horizontally.
Each line contains different parts of a complete picture.
Players must press a button to stop each line, trying to align the parts correctly to form a complete picture.
If the picture is correctly completed, the player earns points.
If the picture is not completed correctly, the lines start moving again.
The game continues until all pictures are correctly matched and completed.
The player with the most completed pictures at the end wins.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @ananyag309 , You can't have another issue before completing the previous one 😀 
 you already have the following 1 open issues 👀 ! :

#4430

**Comment by kunjgit** [comment]
Hey @ananyag309 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by kunjgit** [comment]
Hey @ananyag309 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)
