### ISSUE TITLE
[New game]: 3d Red Light Green Light 

### ISSUE THREAD

**Issue by uzmaansari23** [kunjgit/GameZone#456]
### 🎮 Game Request

This a very fun and amazing game and is totally based on HTML, CSS, JavaScript and Three.js Library. In this game there will be a doll which will try to catch our activity whenever we move. The catching action of the doll is totally random and we have to avoid the glare of the doll to win the game. It's based on the popular series Squid Game. I will really have so much fun making this game and will try to add my own design elements into the game.

### Point down the features

This game will contain a 3d Doll which is designed to catch the user moving. A background will be set and our object will try to cross a certain distance without the doll noticing anything. If the doll notices anything then the game will be over and if she doesn't then we will win this game.
I am really excited to build this game and I request you to assign this issue to me under the tag of GSSoC'23. 

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @uzmaansari23 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by Harshvardhan-Dubey-Github** [comment]
please assign me this issue

**Comment by kunjgit** [comment]
Hey @uzmaansari23 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
