### ISSUE TITLE
[New game]:  Solitaire

### ISSUE THREAD

**Issue by nikki-05** [kunjgit/GameZone#4564]
### 🎮 Game Request

Game logic and basic description:
Solitaire is a classic single-player card game where the objective is to move all cards to four foundations in ascending order (Ace to King) (52 cards) and separated by suit. The aim is to arrange the cards in some systematic order or, in a few cases, to pair them off to discard them.

### Point down the features

Game points:
The game is won when all cards have been moved to the four foundation piles, with only a single suit in each pile, and all cards being played in ascending sequence. The game is over if there are no more moves that can be made.

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @nikki-05 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @nikki-05 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
