### ISSUE TITLE
[New game]:  Cannibal and Missionaries

### ISSUE THREAD

**Issue by Rishi-Singhal21** [kunjgit/GameZone#4566]
### 🎮 Game Request

Game logic and basic description: 
Cannibal and Missionaries is an AI based problem and this game is based on that Ai problem. In the missionaries and cannibals game three missionaries and three cannibals must cross a river using a boat which can carry at most two people, under the constraint that, for both banks, if there are missionaries present on the bank, they cannot be outnumbered by cannibals (if they were, the cannibals would eat the missionaries). The boat cannot cross the river by itself with no people on board.

### Point down the features

Game points:
1. The game starts with all missionaries and cannibals on the right side.
2. Players move missionaries and cannibals to the boat by clicking on them, and then move the boat by clicking on it.
3. The game checks for invalid states (more cannibals than missionaries on either side) and winning states (all on the left side).

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Rishi-Singhal21 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @Rishi-Singhal21 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
