### ISSUE TITLE
[New game]: Aqua Sort Game

### ISSUE THREAD

**Issue by Nikhil11200** [kunjgit/GameZone#4574]
### 🎮 Game Request

Game logic and basic description :
Aqua Sort is a captivating and challenging puzzle game where the objective is to sort colored water in tubes until each tube contains only one color. Players must strategically pour water from one tube to another, adhering to simple rules, to achieve the goal with the fewest possible moves. The game provides a relaxing yet stimulating experience, perfect for sharpening logical thinking and problem-solving skills.

### Point down the features

The game consists of multiple tubes filled with colored water.
Each tube can hold a fixed number of water units (e.g., 4 units per tube).
The initial configuration is a randomized mix of different colored water in the tubes.
The goal is to sort the water so that each tube contains only one color.

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Nikhil11200 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hello @Nikhil11200, Time's up!⏰ 
 Sorry for closing your issue! 
 But it's more than a week since we haven't received anything from your side 😢 . 
 Come up with new ideas, create a new issue and make sure you finish it within a week! 🔥 
 All the best! 🚀 
 Happy Hacking! 💗

**Comment by kunjgit** [comment]
Hey @Nikhil11200 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
