### ISSUE TITLE
[Enhancement]: Master Typing UI changes

### ISSUE THREAD

**Issue by anisharma07** [kunjgit/GameZone#4577]
### Do you want to have the enhancement of existing game ? 😀 Describe yourself..

Game enhancement: 
Click for Instructions button is not properly working...
the Ui is also not properly visible on the window... and instruction page UI changes needed

https://github.com/kunjgit/GameZone/assets/126901961/630b93b6-f981-4e43-88c7-fd6f2952c7ec

### Describe the solution you'd like

changes in UI

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @anisharma07 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @anisharma07 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
