### ISSUE TITLE
[Documentation Bug]: Fixing Readme.md table with game links

### ISSUE THREAD

**Issue by vansh-codes** [kunjgit/GameZone#4582]
### Describe the bug ✍️

Describe your bug here
### Tables with folder link to games is messed up by everyone. Check the screenshots attached.
<br><br>
## Screenshot1:
![image](https://github.com/kunjgit/GameZone/assets/114163734/227cd483-069a-4650-931b-42e2142c9e18)
<br>
<br>
## Screenshot2:
![image](https://github.com/kunjgit/GameZone/assets/114163734/f89de88e-f28c-4c1a-b900-0e0e10094c01)

### Provide step by step information reproduce the bug 📄

I want to organize the readme's table which contains folder link to the games.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @vansh-codes , You can't have another issue before completing the previous one 😀 
 you already have the following 1 open issues 👀 ! :

#4576

**Comment by kunjgit** [comment]
Hey @vansh-codes ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by kunjgit** [comment]
Hey @vansh-codes ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)
