### ISSUE TITLE
[New game]: Add Go Game

### ISSUE THREAD

**Issue by AsmitaMishra24** [kunjgit/GameZone#4583]
### 🎮 Game Request

I kindly request the addition of a Go game. Go is a classic Chinese board game renowned for its deep strategic gameplay and cultural significance. By introducing a Go game, users would have the opportunity to engage in this ancient game of strategy directly on the platform.

### Point down the features

1. Traditional Rules: Implement complete Go rules, including stone capturing and territory scoring.
2. User Interface: Intuitive board display with clear grid markings and stone placement.
3. Accessibility: Cross-device compatibility and comprehensive documentation.
4. Game Modes: Single-player against AI with adjustable difficulty, and two-player (local or online).

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @AsmitaMishra24 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @AsmitaMishra24! 
We are already having a similar game request in #4559 👀 
Make sure you come up with a cool unique idea 😀 
 Waiting for your new game idea 💗.

**Comment by kunjgit** [comment]
Hey @AsmitaMishra24 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
