### ISSUE TITLE
[New game]: TownRise

### ISSUE THREAD

**Issue by Maheshwari-Love** [kunjgit/GameZone#4584]
### 🎮 Game Request

TownRise is an immersive city-building and resource management game where players take on the role of a city planner tasked with developing a small town into a thriving metropolis. The game combines strategic planning, resource management, and creative design to create a rich and engaging gameplay experience.

### Point down the features

Game points:
City Building
Resource Management
Dynamic Challenges

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by Maheshwari-Love** [comment]
assign\

**Comment by kunjgit** [comment]
Hey @Maheshwari-Love ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)
