### ISSUE TITLE
[New game]: Add Go Game

### ISSUE THREAD

**Issue by AsmitaMishra24** [kunjgit/GameZone#4585]
### 🎮 Game Request

**Objective:** 
The primary goal in Go is to control more territory on the board than your opponent by surrounding empty points and capturing their stones.

**How to Achieve It:**
1. Territory: Players aim to surround and secure as much empty space (territory) on the board as possible using their stones.
2. Capturing: Stones can be captured by completely surrounding them with your own stones, thereby removing them from the board and gaining points.
3. Winning Condition: At the end of the game, players count the points based on the territory they control and the stones they have captured. The player with more points wins.

### Point down the features

**Territory Points:**
1. Territory points are the primary way to score in Go. They represent the empty intersections (points) of the board that are completely surrounded by one player's stones.
2. Each empty point enclosed by a player's stones counts as one point towards their territory at the end of the game.

**Captured Stones:**
1. Captured stones are the stones of the opponent that a player successfully surrounds and removes from the board.
2. Each captured stone counts as one point towards the player's score at the end of the game.

**Komi:**
1. Komi is a predetermined number of points added to the score of the player who plays second (typically White) to compensate for the advantage of playing first (Black).
2. Komi is usually around 6.5 to 7.5 points in professional games and helps to balance the game.

**Dead Stones:**
1. Dead stones are stones that are considered captured or surrounded and are no longer in play.
2. Dead stones do not count towards the owner's territory or score.

**Endgame and Counting:**
1. The game ends when both players pass consecutively, signaling that no more moves are beneficial.
2. After the game ends, players together determine which stones are dead (captured) and remove them from the board.
3. Players then count the number of empty points they have surrounded (territory points), add the number of stones they have captured, and subtract the number of their own stones that have been captured by the opponent.
4. The player with the higher total of territory points, captured stones, and komi wins the game.

Screenshot:-
![images (2)](https://github.com/kunjgit/GameZone/assets/146121869/181cb0e2-e9e9-40be-b882-e3c7a5023cd7)

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @AsmitaMishra24 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @AsmitaMishra24! 
We are already having a similar game request in #4559 👀 
Make sure you come up with a cool unique idea 😀 
 Waiting for your new game idea 💗.

**Comment by kunjgit** [comment]
Hey @AsmitaMishra24 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
