### ISSUE TITLE
[New game]: Connect_4

### ISSUE THREAD

**Issue by ThisIsSahaj** [kunjgit/GameZone#4592]
### 🎮 Game Request

A strategy board game played by two players who take turns dropping colored discs from the top into a vertically suspended grid.
 

### Point down the features

The game ends as soon as a player successfully connects four of their discs in a row. The connection can be vertical, horizontal, or diagonal.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @ThisIsSahaj ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)
