### ISSUE TITLE
[New game]: Maze Game

### ISSUE THREAD

**Issue by rt-001** [kunjgit/GameZone#46]
### 🎮 Game Request

Game logic and basic description
The game logic revolves around a simple maze game where the player needs to navigate through a maze from a starting point to reach the end point.
1) Maze Generation:
- A maze is randomly generated using a grid-based system.
- The maze consists of walls and open paths that form a network of interconnected cells.
- The starting point is marked at a specific cell, and the end point is placed in another cell.
2) Player Movement:
- The player is represented as a character or object within the maze.
- The player can move in four directions: up, down, left, and right.
- The player uses input controls, such as arrow keys to navigate through the maze.
- The movement is constrained by the maze's walls, meaning the player cannot move through walls but can traverse through open paths.

### Point down the features

Game points

1. Difficulty levels can be implemented, altering the complexity of the maze generation.
2. Timer functionality can be included to track the time taken to complete the maze.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey  @rt-001 ! Thank you for raising an issue 💗 You have been assigned this issue you can start working on the issue 🎮

**Comment by kunjgit** [comment]
Hey @rt-001 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
