### ISSUE TITLE
[New game]: Magic 8 Ball Game

### ISSUE THREAD

**Issue by Monika5S** [kunjgit/GameZone#4606]
### 🎮 Game Request

It is a fun game where users ask the Magical Eight Ball fortune teller yes or no questions and get predictions about their future.

### Point down the features

- Person will give us a question as input to predict fortune on.
- The Magic Eight ball generates a random answer based on user luck to the question. 
- In case of no input the ball says, “Sorry but I can't work with that”.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Monika5S ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @Monika5S ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
