### ISSUE TITLE
[New game]: Hide and Seek

### ISSUE THREAD

**Issue by PilotAxis** [kunjgit/GameZone#4609]
### 🎮 Game Request

Hide and Seek will be a fun and interesting game. The game will feature a intuitive 4x4 (rows and columns) square tiles. In the square tiles there are certain set of emojis present on it (having multiple two two pairs of them will be present). The square tiles will be hidden by default and it will show it's content for 4 seconds when the user clicks the tile to find a pair of same emoji. If the user finds all the pairs of same emojis, he/she will win the game otherwise he/she lose the match.

### Point down the features

- Will help the user in memorising the things.
- Boosts user logical analysis and interpretation.
- Enhance the readability.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @PilotAxis ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @PilotAxis ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
