### ISSUE TITLE
Ultimate Football Manager

### ISSUE THREAD

**Issue by atul2727** [kunjgit/GameZone#4611]
### 🎮 Game Request

Ultimate Football Manager is a text-based football manager simulation game where players take on the role of a football team manager. The game allows players to build and manage their own football team, compete in various leagues, make strategic decisions, and lead their team to victory.

Game Logic:

Player Management:
->Players are loaded from a JSON file containing player data.
->Players have attributes such as name, age, rating, club, value, wage, position, etc.

Team Management:
->Teams are loaded from a JSON file containing team data.
->Players can be assigned to different positions and formations.
->Formations affect the team's strategy and gameplay.

Match Simulation:
->Matches are simulated based on the team's strength, player ratings, and tactics.
->Random events such as goals, injuries, and substitutions occur during the match.
->Match outcomes are determined by factors like team strength, player performance, and tactics.

League Standings:
->League standings are updated based on match results.
->Points are awarded for wins, draws, and losses.
->Teams are ranked in the league table based on points, goal difference, and other criteria.

### Point down the features

Core Features:

Team Selection:
->Choose a team from available leagues and teams.
->Start with a team and lead it to victory.

Team Management:
->View and manage player roster.
->Set team formations and tactics.
->Make strategic decisions for match preparation.

League Table:
->View the current standings of the league.
->Track the progress of your team and others in the league.

Match Simulation:
->Play or simulate matches against other teams.
->Experience realistic match outcomes based on player performance and tactics.

Schedule:
->View the upcoming fixtures and match schedules.
->Plan strategies for upcoming matches.

Results Screen:
->View the results of played matches.
->Analyze match statistics and outcomes.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @atul2727 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @atul2727 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
