### ISSUE TITLE
[New game]: Ultimate Football Manager

### ISSUE THREAD

**Issue by atul2727** [kunjgit/GameZone#4612]
### 🎮 Game Request

Game logic and basic description
Ultimate Football Manager is a text-based football manager simulation game where players take on the role of a football team manager. The game allows players to build and manage their own football team, compete in various leagues, make strategic decisions, and lead their team to victory.

Game Flow:

->Start New Game: Players start by selecting "Start New Game" from the landing page.
->Team Selection: In this phase, players select a team from available leagues and teams. Once a team is selected, the main menu appears.
->Main Menu: This is the hub where players can access various features of the game.
->Team: View and manage the selected team, including player management and formation.
->League Table: View the current standings of the league.
->Schedule: View upcoming fixtures and match schedules.
->Next Game: Proceed to the next scheduled game.
->League Table: View the current standings of the league.
->Schedule: View the upcoming fixtures and match schedules.
->Next Game:
Play the scheduled game.
Simulate match outcomes based on team strength, tactics, and player performance.
Display match results and update league standings.
Proceed to the next scheduled game.
->Results Screen:
View the results of the played matches.
Return to the main menu.

### Point down the features

Game points

Core Features:

Team Selection:
->Choose a team from available leagues and teams.
->Start with a team and lead it to victory.

Team Management:
->View and manage player roster.
->Set team formations and tactics.
->Make strategic decisions for match preparation.

League Table:
->View the current standings of the league.
->Track the progress of your team and others in the league.

Match Simulation:
->Play or simulate matches against other teams.
->Experience realistic match outcomes based on player performance and tactics.

Schedule:
->View the upcoming fixtures and match schedules.
->Plan strategies for upcoming matches.

Results Screen:
->View the results of played matches.
->Analyze match statistics and outcomes.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @atul2727 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by atul2727** [comment]
/assign
please add GSSoC label as well

**Comment by kunjgit** [comment]
Hey @manikumarreddyu ! , This issue is already assigned to @atul2727. 💗 
 You can work on other issues 🚀 
 If there is anything wrong you can contact us on [Discord🕹️](https://discord.gg/fgwk4XZfxG)👀

**Comment by kunjgit** [comment]
Hey @codewithganeshhh ! , This issue is already assigned to @atul2727. 💗 
 You can work on other issues 🚀 
 If there is anything wrong you can contact us on [Discord🕹️](https://discord.gg/fgwk4XZfxG)👀

**Comment by kunjgit** [comment]
Hey @atul2727 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
