### ISSUE TITLE
 Treasure Hunt Adventure🌲

### ISSUE THREAD

**Issue by animex007** [kunjgit/GameZone#4617]
### 🎮 Game Request

**Description**:
A beginner-friendly multiplayer game where players embark on a treasure hunt adventure. Players solve puzzles and complete challenges to find hidden treasures in a virtual world. The game features different levels of difficulty, cooperative gameplay elements, and a leaderboard to track progress.

*Objectives:*

- Create a virtual map with hidden treasures.
- Develop simple puzzles and challenges for players.
- Implement a multiplayer mode for cooperative gameplay.
- Add a leaderboard to track progress and achievements.

### Point down the features

*Features:*
-  **Multiplayer Mode**: Play with friends in a cooperative setting.
-  **Puzzle Solving**: Engage in simple puzzles to advance in the game.
-  **Challenges**: Complete basic challenges to unlock clues.
-  **Leaderboard**: Track players' progress and achievements.
-  **Beginner Friendly**: Designed for beginners with easy-to-understand mechanics.

**Technologies:**
*Unity and JavaScript.*

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @animex007 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @animex007! 🙂 
 It seems like you are not following proper guidelines !! 👀 
 Read documentation properly !!🙏 
 If you have any queries reach out to us on [Discord🕹️](https://discord.gg/fgwk4XZfxG) .

**Comment by kunjgit** [comment]
Hey @animex007 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
