### ISSUE TITLE
[New game]: Catch the Ball Game

### ISSUE THREAD

**Issue by Swapnilden** [kunjgit/GameZone#4620]
### 🎮 Game Request

The Catch the Ball game is a simple yet entertaining web-based game where the player controls a basket using the left and right arrow keys to catch falling balls. The balls drop from random positions at the top of the screen, and the player's goal is to catch as many balls as possible. Each successful catch increases the player's score by one point. The game continues indefinitely, allowing players to compete for the highest score.

1. Player Control: The player moves the basket left and right using the arrow keys.
2. Random Ball Drop: Balls fall from random horizontal positions at the top of the screen.
3. Score System: Each ball caught by the basket increases the player's score by one point.
4. Collision Detection: The game checks if the ball lands inside the basket.
5. Game Continuity: The game continues indefinitely, with balls continuously falling from the top.

### Point down the features

1. Responsive Design: The game adjusts to different screen sizes for an optimal playing experience on various devices.
2. Simple Controls: Easy-to-use arrow keys for intuitive gameplay.
3. Real-Time Scoring: The score is updated in real-time as the player catches the balls.
4. Reset Function: The ball resets to the top of the screen after being caught or missing the basket.
5. Visual Feedback: Changes in the ball and basket position are smoothly animated..

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Swapnilden ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @Swapnilden! 
We are already having a similar game request in #4311 👀 
Make sure you come up with a cool unique idea 😀 
 Waiting for your new game idea 💗.

**Comment by kunjgit** [comment]
Hey @Swapnilden ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
