### ISSUE TITLE
[New game]: Speed_Typing

### ISSUE THREAD

**Issue by SiriAmarlapudi** [kunjgit/GameZone#4623]
### 🎮 Game Request

Speed Typing is for users to type given words or sentences as quickly and accurately as possible. The game challenges players to improve their typing speed and accuracy over time.
A word or sentence is displayed at the top of the screen for the player to type.
 Immediate visual feedback on typing accuracy (e.g., highlighting errors in red).

### Point down the features

Real-Time Feedback: Immediate visual feedback on typing accuracy (e.g., highlighting errors in red).
Word/Sentence Display: A word or sentence is displayed at the top of the screen for the player to type.
Speed Score: Points awarded based on typing speed (words per minute - WPM).
Clean Layout: Simple and intuitive interface with clear text and input areas.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @SiriAmarlapudi , You can't have another issue before completing the previous one 😀 
 you already have the following 1 open issues 👀 ! :

#4622

**Comment by kunjgit** [comment]
Hey @SiriAmarlapudi ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by kunjgit** [comment]
Hey @SiriAmarlapudi ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)
