### ISSUE TITLE
Adding back to Top scrollbar option 

### ISSUE THREAD

**Issue by Garima-149** [kunjgit/GameZone#4627]
### Do you want to have the enhancement of existing game ? 😀 Describe yourself..

@kunjgit currently,There is no scrolltoTop option .I want to add this feature in the app to make it easily scrollable by everyone.It will also enhance its UI.

### Describe the solution you'd like

Solution steps
![Screenshot (74)](https://github.com/kunjgit/GameZone/assets/143211271/d2612f0a-25bb-4042-8908-4128b5056fce)

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Garima-149 , You can't have another issue before completing the previous one 😀 
 you already have the following 1 open issues 👀 ! :

#4171

**Comment by kunjgit** [comment]
Hey @Garima-149 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by kunjgit** [comment]
Hey @Garima-149 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @Garima-149! 🙂 
 It seems like you are not following proper guidelines !! 👀 
 Read documentation properly !!🙏 
 If you have any queries reach out to us on [Discord🕹️](https://discord.gg/fgwk4XZfxG) .

**Comment by Garima-149** [comment]
@kunjgit But the issue you are talking about is assigned to somebody else. How could I complete this.
