### ISSUE TITLE
[New game]:  Coin Game

### ISSUE THREAD

**Issue by tanyagupta01** [kunjgit/GameZone#4628]
### 🎮 Game Request

Game logic and basic description
<img width="926" alt="Screenshot 2024-06-19 at 10 14 41 PM" src="https://github.com/kunjgit/GameZone/assets/156044894/6a01d526-7a5e-4d25-b4a2-e3a2ae3d2aa4">

### Point down the features

Game points
Do not touch the walls or you lose.
Collect all the coins in as minimum time as possible.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @tanyagupta01 , You can't have another issue before completing the previous one 😀 
 you already have the following 1 open issues 👀 ! :

#4411

**Comment by kunjgit** [comment]
Hey @tanyagupta01 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by kunjgit** [comment]
Hey @tanyagupta01 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @tanyagupta01! 
We are already having a similar game request in #4603 👀 
Make sure you come up with a cool unique idea 😀 
 Waiting for your new game idea 💗.
