### ISSUE TITLE
[New game]:  Adding Love Calculator Game

### ISSUE THREAD

**Issue by codewithganeshhh** [kunjgit/GameZone#4632]
### 🎮 Game Request

Game logic and basic description :
Simple Calculation of love percentage with the use of name 
> Technologies used: 
- HTML
- CSS
- JAVASCRIPT

### Point down the features

![Screenshot 2024-06-20 211644](https://github.com/kunjgit/GameZone/assets/139307139/9a647da2-e7dc-4b20-9f78-a8da13052bdf)

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @codewithganeshhh ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @codewithganeshhh ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
