### ISSUE TITLE
[New game]: Build A Lighthouse

### ISSUE THREAD

**Issue by gp0814** [kunjgit/GameZone#464]
### 🎮 Game Request

In this game, the player has to build a lighthouse before becoming night. Which guides the ship to track its path otherwise the ship will crash and the play will lose the game.

### Point down the features

1. Easy to use
2. Interesting
3. Attractive
4. Two Graphic Quality ( Quite pretty / very pretty )
5. Moderate to play 
6. Fun to Lighthouse
7. Addective

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @gp0814 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by Harshvardhan-Dubey-Github** [comment]
please assign me this issue

**Comment by kunjgit** [comment]
Hey @gp0814 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
