### ISSUE TITLE
[New game]: 2048 game 

### ISSUE THREAD

**Issue by nikki-05** [kunjgit/GameZone#4641]
### 🎮 Game Request

Game logic and basic description
2048 is a popular single-player sliding tile puzzle game where the objective is to combine numbered tiles on a grid to create a tile with the number 2048.
 The goal is to create a tile with the number 2048. However,  the players can continue to play to achieve higher scores by creating larger tiles.

### Point down the features

Game points
How to Play??
->The game is played on a 4x4 grid.
->Tiles: The grid starts with two tiles, each displaying either a "2" or a "4". New tiles appear with each move, either "2" or "4".
->Moves: Players can slide tiles left, right, up, or down using the arrow keys.
->Combining Tiles: When two tiles with the same number collide while moving, they merge into a single tile with a value equal to the sum of the two original tiles (e.g., two "2" tiles merge to form a "4" tile).
->Game Over The game ends when there are no empty spaces on the grid and no possible moves left to combine tiles
->The game ends when the grid is full and no valid moves are left (i.e., no adjacent tiles can be merged, and no empty spots are available).

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @nikki-05 , You can't have another issue before completing the previous one 😀 
 you already have the following 1 open issues 👀 ! :

#4564

**Comment by kunjgit** [comment]
Hey @nikki-05 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by kunjgit** [comment]
Hey @nikki-05 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @nikki-05! 
We are already having a similar game request in #4603 👀 
Make sure you come up with a cool unique idea 😀 
 Waiting for your new game idea 💗.
