### ISSUE TITLE
[New game]: Adding OutRun offline game 

### ISSUE THREAD

**Issue by Maheshwari-Love** [kunjgit/GameZone#4642]
### 🎮 Game Request

I'm always frustrated when the default Chrome offline game (Dino game) becomes repetitive and loses its novelty quickly. It would be more engaging to have a variety of games to play when there's no internet connection.
I want to have an "Outrun" themed game available as an offline game in Chrome. This game would provide a retro racing experience with 80s-inspired graphics and music, offering a more diverse and enjoyable experience when offline.

### Point down the features

Game points
OutRun Offline Game
Graphics
Music

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Maheshwari-Love ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @Maheshwari-Love ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
