### ISSUE TITLE
[New game]: Sliding Game

### ISSUE THREAD

**Issue by muskan42** [kunjgit/GameZone#4644]
### 🎮 Game Request

* It's a 4x4 grid with 15 numbered tiles and one empty space.
* Players slide tiles into the empty space to reorder them numerically, ending with 1 in the top left and progressing to 15 in the bottom right.
* Swiping a tile checks if the empty space is adjacent. If so, the tiles swap positions.

### Point down the features

* Single-player tile puzzle game.
* Slide numbered tiles (1-15) to reorder them in sequence. 
* Empty space allows tile movement. 
* Goal: Reach order from 1 (top-left) to 15 (bottom-right). 

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

![Sliding_Game](https://github.com/kunjgit/GameZone/assets/141642724/e1494d65-db14-4201-a62d-99a72da342e3)

**Comment by muskan42** [comment]
\assign

**Comment by kunjgit** [comment]
Hey @muskan42 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by Karthikkariappa08** [comment]
plz assign this task to me

**Comment by kunjgit** [comment]
Hey @muskan42 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
