### ISSUE TITLE
[New game]: Wall Breaker Game

### ISSUE THREAD

**Issue by Nikhil11200** [kunjgit/GameZone#4647]
### 🎮 Game Request

In this game we are given certain no of lives and a ball with the help of which u need to break the different bricks.

### Point down the features

Game will be interactive for the users , also it will be very easy for the users to play it and they will definitely enjoy playing this.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Nikhil11200 , You can't have another issue before completing the previous one 😀 
 you already have the following 1 open issues 👀 ! :

#4574

**Comment by kunjgit** [comment]
Hey @Nikhil11200 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by kunjgit** [comment]
Hey @Nikhil11200 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @Nikhil11200! 
We are already having a similar game request in #4635 👀 
Make sure you come up with a cool unique idea 😀 
 Waiting for your new game idea 💗.
