### ISSUE TITLE
 Adding backTo top scroll button

### ISSUE THREAD

**Issue by Garima-149** [kunjgit/GameZone#4649]
### Do you want to have the enhancement of existing game ? 😀 Describe yourself..

Game enhancement
![Screenshot (74)](https://github.com/kunjgit/GameZone/assets/143211271/ececfea1-5a5d-4038-a21b-cafa412c940c)
@kunjgit I have opened this issue before too but you said that my previous issue is not completed so,I cannot make new one.But I want to remind you that the issue you were talking about was assigned to somebody else.So,How could I complete it.
I have not any issue uncompleted.
The idea is to make a scrollTOtop button at botttom of landing page

### Describe the solution you'd like

Solution steps

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Garima-149 , You can't have another issue before completing the previous one 😀 
 you already have the following 1 open issues 👀 ! :

#4171

**Comment by kunjgit** [comment]
Hey @Garima-149 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by kunjgit** [comment]
Hey @Garima-149 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @Garima-149! 🙂 
 It seems like you are not following proper guidelines !! 👀 
 Read documentation properly !!🙏 
 If you have any queries reach out to us on [Discord🕹️](https://discord.gg/fgwk4XZfxG) .

**Comment by Garima-149** [comment]
@kunjgit  please dont close it without looking
