### ISSUE TITLE
Jeopardy

### ISSUE THREAD

**Issue by shreyaslax** [kunjgit/GameZone#465]
### 🎮 Game Request

It contains a grid of cards. When you click on the card, you get a question with 2 options. You can't click another card until you answer the question. If you click the correct option, you get points and the background-color of the card changes to yellow, else if it is wrong it changes to green and you don't get any points.

This is a fun game built using HTML, CSS and JavaScript.

Please assign me this issue.

Thank you

### Point down the features

Game points
Questions with 2 options
Correct answer changes card color from Blue to Yellow and adds points to the final score
Wrong answer changes card color from Blue to Red and no points are added to the final score.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @shreyaslax ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @shreyaslax! 🙂 
 It seems like you are not following proper guidelines !! 👀 
 Read documentation properly !!🙏 
 If you have any queries reach out to us on [Discord🕹️](https://discord.gg/fgwk4XZfxG) .

**Comment by kunjgit** [comment]
Hey @shreyaslax ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by shreyaslax** [comment]
Thanks so much for this opportunity @kunjgit. I still didn't understand which Guideline I didn't follow, could you please specify.
