### ISSUE TITLE
[New game]: Color swap

### ISSUE THREAD

**Issue by aditya-bhaumik** [kunjgit/GameZone#4656]
### 🎮 Game Request

"Color Swap" is a simple yet addictive browser-based game developed using HTML, CSS, and JavaScript. The game revolves around the player controlling a character or object that must pass through obstacles matching its color. The color of the character changes randomly, requiring quick reflexes and strategic thinking.

### Point down the features

Simple Controls:

The player controls the character using the arrow keys or touch gestures on mobile devices.
The character moves left, right, up, or down to navigate through a series of color-coded obstacles.

Color Matching:

The character changes color periodically or when passing through special zones.
Players must guide the character through obstacles that match its current color to score points.

Increasing Difficulty:

As the game progresses, the speed and frequency of color changes increase.
More complex patterns and additional obstacles are introduced to challenge the player.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @aditya-bhaumik ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @aditya-bhaumik ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
