### ISSUE TITLE
[New game]: Add a ball and Paddle game

### ISSUE THREAD

**Issue by debangi29** [kunjgit/GameZone#4659]
### 🎮 Game Request

Game logic and basic description
Add a ball and paddle game
Control a paddle to keep a ball in play and break bricks.

### Point down the features

Game points
1. Control the paddle to get score using arrow keys
2. Once you lose the score resets

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @debangi29 , You can't have another issue before completing the previous one 😀 
 you already have the following 1 open issues 👀 ! :

#4657

**Comment by kunjgit** [comment]
Hey @debangi29 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by kunjgit** [comment]
Hey @debangi29 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by debangi29** [comment]
Hello @kunjgit 
I have completed the previous issue;
Can I now start working on it?
