### ISSUE TITLE
[Documentation Bug]: Fix README table with game folder links

### ISSUE THREAD

**Issue by vansh-codes** [kunjgit/GameZone#4664]
### Describe the bug ✍️

Describe your bug here
### Tables with folder link to games is messed up by everyone. Check the screenshots attached.
<br><br>
## Screenshot1:
![image](https://github.com/kunjgit/GameZone/assets/114163734/227cd483-069a-4650-931b-42e2142c9e18)
<br>
<br>
## Screenshot2:
![image](https://github.com/kunjgit/GameZone/assets/114163734/f89de88e-f28c-4c1a-b900-0e0e10094c01)

### Provide step by step information reproduce the bug 📄

I want to organize the readme's table which contains folder link to the games.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### Provide step by step information reproduce the bug 📄

Description

Organizing readme's table with game folder links

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @vansh-codes ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @vansh-codes ! , This issue is already assigned to @ankana2113. 💗 
 You can work on other issues 🚀 
 If there is anything wrong you can contact us on [Discord🕹️](https://discord.gg/fgwk4XZfxG)👀

**Comment by vansh-codes** [comment]
> /assign

Hey @ankana2113 It was my issue and i have already completed working on it. Please let me have this issue so that I can make a pull request. Please understand I have made the changes in the readme already.
@kunjgit Please assign it back to me as I have already started working upon it.

**Comment by kunjgit** [comment]
Hey @vansh-codes ! , This issue is already assigned to @ankana2113. 💗 
 You can work on other issues 🚀 
 If there is anything wrong you can contact us on [Discord🕹️](https://discord.gg/fgwk4XZfxG)👀

**Comment by vansh-codes** [comment]
@ankana2113 Fixing the table in readme is a time taking task, I have already done it, why do you want to waste your time doing it and mine too because I have already fixed it. Please reply so that it can be transfered to me by Kunjit. 
Dont do this please understand @ankana2113 please

**Comment by ankana2113** [comment]
Okay of course no Problem!

**Comment by vansh-codes** [comment]
> Okay of course no Problem!

mention @kunjgit and tell him to unassign you

**Comment by vansh-codes** [comment]
Thank You @ankana2113 for understanding!

**Comment by kunjgit** [comment]
Hey @vansh-codes ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
