### ISSUE TITLE
[Enhancement]: UI of  Click the Circle game and  adding some new features such as increasing time, button position etc.

### ISSUE THREAD

**Issue by Changingthegame** [kunjgit/GameZone#4668]
### Do you want to have the enhancement of existing game ? 😀 Describe yourself..

I  was finding a game for improvement and I saw that in "Click the circle game" the UI is so boring that it makes the user feel not to play it as it has only white background and black letters . Also there is only time limit of 15 seconds which is very less and the start button and letters are overlapping.

### Describe the solution you'd like

Firstly, I would like to change its UI so as it becomes dashing , I will use a nice background, change the fonts and colors as well as the position of text and buttons . Then I will increase the time limit to 30 seconds . I will try to add some more features and make necessary changes in it.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Changingthegame ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @Changingthegame ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
