### ISSUE TITLE
[New game]: Adding the Jigsaw Puzzle Game

### ISSUE THREAD

**Issue by shreyash3087** [kunjgit/GameZone#4676]
### 🎮 Game Request

**Game logic and basic description:**

I would like to request the addition of a classic jigsaw puzzle game to the site. This game will allow users to upload any image and transform it into a jigsaw puzzle with varying difficulty levels. Users can select from 12, 25, 50, 100, or 200 pieces to create a customized and engaging puzzle-solving experience.

### Point down the features

**Game points:**

- Image Upload: Users can upload their own images to create unique puzzles.
- Piece Selection: Choose from different puzzle sizes (12, 25, 50, 100, 200 pieces) for varying difficulty.
- Interactive Gameplay: Drag and drop pieces to solve the puzzle.
- User-Friendly Interface: Easy-to-use interface for a smooth and enjoyable user experience.
- Responsive Design: Fully responsive design to ensure compatibility across different devices.

This game will add a fun and interactive element to the site, appealing to users of all ages. It promotes problem-solving skills and provides a relaxing activity for users to enjoy.

**Screenshots:**

![Screenshot (61)](https://github.com/kunjgit/GameZone/assets/72603662/910c9b64-70d4-4a3e-994d-864bd30bb906)

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @shreyash3087 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @shreyash3087 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
