### ISSUE TITLE
[New game]: Catch master 

### ISSUE THREAD

**Issue by aditya-bhaumik** [kunjgit/GameZone#4685]
### Game Description:
In Catch Craze, you control a basket at the bottom of the screen, aiming to catch falling objects. The game gets progressively harder as you score more points, with objects falling faster and spawning more frequently. The goal is to score as many points as possible before the time runs out.

### How to Start:
Click the "Start Game" button to begin.
Move the basket to catch the falling objects.
Monitor the score and timer.
When the timer reaches zero, the game ends, showing your final score and a button to restart the game.

### Point down the features

Controls: Use the left and right arrow keys to move the basket.
Scoring: Each object caught increases your score by 1.
Difficulty: Object speed and spawn rate increase every 5 points.
Timer: The game lasts for 60 seconds.
Game Over: When time runs out, the final score is displayed with an option to play again.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @aditya-bhaumik , You can't have another issue before completing the previous one 😀 
 you already have the following 1 open issues 👀 ! :

#4656

**Comment by kunjgit** [comment]
Hey @aditya-bhaumik ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by kunjgit** [comment]
Hey @aditya-bhaumik ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)
