### ISSUE TITLE
[New game]: Want to Add Space Dominator Game

### ISSUE THREAD

**Issue by nishant0708** [kunjgit/GameZone#4686]
### 🎮 Game Request

Game logic and basic description

in this user have some lives and have to kill all the enemies .

### Point down the features

Game points
the main character can shoot
throw bombs 

https://github.com/kunjgit/GameZone/assets/101548649/2c519b03-e2f8-4d32-9ec7-c7bd2d2ac11d

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @nishant0708 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by nishant0708** [comment]
hey @kunjgit 
i am getting this error while cloning repo what should i do?
![image](https://github.com/kunjgit/GameZone/assets/101548649/de1bb435-fc97-4f96-adfb-3e540060cf50)

**Comment by nishant0708** [comment]
Hey @ishita-43 there is issue while forking repo can you fix that please

**Comment by ishita-43** [comment]
The error causing file was successfully renamed you can now try again to clone and tell me if other problem arises again!!

**Comment by nishant0708** [comment]
Hey @ishita-43  i will check and let you know thanks for responding
