### ISSUE TITLE
[New game]: Want to Add Dog Game

### ISSUE THREAD

**Issue by nishant0708** [kunjgit/GameZone#4687]
### 🎮 Game Request

Game logic and basic description
in this the main character is a dog whoose main aim is to score 50 points in 30 seconds and he can kill enemies when he is in combat mode

### Point down the features

Game points
![Screenshot 2024-06-23 214618](https://github.com/kunjgit/GameZone/assets/101548649/cd444a6b-e8a7-4e2f-a894-09ac98ab3807)
![Screenshot 2024-06-23 214639](https://github.com/kunjgit/GameZone/assets/101548649/3b492b72-dd3e-4bce-b464-e26cc5c0c660)

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @nishant0708 , You can't have another issue before completing the previous one 😀 
 you already have the following 1 open issues 👀 ! :

#4686

**Comment by kunjgit** [comment]
Hey @nishant0708 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by kunjgit** [comment]
Hey @nishant0708 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @nishant0708! 
We are already having a similar game request in #4686 👀 
Make sure you come up with a cool unique idea 😀 
 Waiting for your new game idea 💗.
