### ISSUE TITLE
[Enhancement]: Free Bird Game's UI and adding some new feature.

### ISSUE THREAD

**Issue by Changingthegame** [kunjgit/GameZone#4690]
### Do you want to have the enhancement of existing game ? 😀 Describe yourself..

The Free Bird Game is very exciting game and there is a craze between children as well as youngsters to play these games but in this game the UI is not that much good. Firstly, the game screen is very small which should be bigger then the color combinations as well as the text and fonts are also not that much dashing. When the game over the screen that appear is also not that much better.

### Describe the solution you'd like

Firstly , I will improve the game over screen, then will increase the screen size and improve the color combinations, fonts and text so that the overall UI looks dashing and attractive.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Changingthegame , You can't have another issue before completing the previous one 😀 
 you already have the following 1 open issues 👀 ! :

#4668

**Comment by kunjgit** [comment]
Hey @Changingthegame ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by kunjgit** [comment]
Hey @Changingthegame ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by Changingthegame** [comment]
I have already make a PR for the issue #4668 .
