### ISSUE TITLE
[New game]: Sand Tetris

### ISSUE THREAD

**Issue by Markcosay** [kunjgit/GameZone#4692]
### 🎮 Game Request

Game logic and basic description
A block of sand comes down which can be controlled by arrow keys, upon contacting ground the block breaks and behaves like sand.
The player tries to match the sand colors and connect both the side walls and if done, he scores points.
If sand reaches top position, Game Over

### Point down the features

Game points
Connect both sidewalls using same color of sand to score point

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Markcosay ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @Markcosay ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
