### ISSUE TITLE
Add Maze Generation Game

### ISSUE THREAD

**Issue by ananyag309** [kunjgit/GameZone#4693]
### 🎮 Game Request

Game logic and basic description - 
Navigate through procedurally generated mazes in this thrilling puzzle game, where each level presents a unique challenge of twists and turns. Use strategy and skill to find the exit while avoiding traps and solving puzzles along the way.

### Point down the features

Game points
Procedurally Generated Mazes: Each playthrough offers a unique maze, ensuring endless variety and replayability.
Increasing Difficulty Levels: Progressive challenge with mazes becoming more complex as you advance.
Traps and Obstacles: Navigate carefully to avoid traps that add an extra layer of difficulty.
Puzzle Elements: Solve puzzles within the maze to unlock new paths and the final exit.
Intuitive Controls: Easy-to-learn controls that make navigating the mazes smooth and enjoyable.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @ananyag309 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
