### ISSUE TITLE
[New game]: Flappy Bird

### ISSUE THREAD

**Issue by singh-anushka** [kunjgit/GameZone#47]
### 🎮 Game Request

Game logic and basic description
Basic Flappy Bird Game using HTML, CSS and JavaScript.

### Point down the features

Game points
Dodge the pipes and the score increases by 1 every time this happens.
The game ends as the pipe the bird crashes into a pipe.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @singh-anushka !! we are already having this game request in #22 
make sure you come up with unique game !! 💗
