### ISSUE TITLE
[New game]: space invader

### ISSUE THREAD

**Issue by bcritgithub** [kunjgit/GameZone#470]
### 🎮 Game Request

Game logic and basic description
 Space Invaders is a classic arcade game where the player controls a spaceship and must shoot down waves of invading alien ships. 

### Point down the features

Game points 
When the player shoots down an alien, you can award them a certain number of points. The points earned per alien may increase as the game progresses to add more challenge and reward for higher levels.
Completing a level can reward the player with a bonus score.
can give the player a bonus score based on their shooting accuracy.

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @bcritgithub ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @bcritgithub! 
We are already having a similar game request in #336 👀 
Make sure you come up with a cool unique idea 😀 
 Waiting for your new game idea 💗.

**Comment by kunjgit** [comment]
Hey @bcritgithub ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
