### ISSUE TITLE
[New game]: Bird Game

### ISSUE THREAD

**Issue by muskan42** [kunjgit/GameZone#4706]
### 🎮 Game Request

It is a notoriously difficult game that requires precise timing and reflexes.

Track bird, pipes, score, and game state.
Update bird based on gravity and user input.
Check collisions and update game state/score.

### Point down the features

The player controls a bird, attempting to fly through a series of gaps between pipes without hitting them.
Tapping the screen makes the bird flap its wings and ascend slightly.
The bird constantly descends due to gravity.
If the bird hits a pipe or goes off the screen, the game ends.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by muskan42** [comment]
\assign

**Comment by kunjgit** [comment]
Hey @muskan42 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @muskan42! 
We are already having a similar game request in #4607 👀 
Make sure you come up with a cool unique idea 😀 
 Waiting for your new game idea 💗.

**Comment by muskan42** [comment]
\assign

**Comment by kunjgit** [comment]
Hey @muskan42 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
