### ISSUE TITLE
[New game]: Paint

### ISSUE THREAD

**Issue by muskan42** [kunjgit/GameZone#4707]
### 🎮 Game Request

* Grid challenge with squares, not reflexes.
 * A color picker that picks from anywhere throughout the whole window.
 * Logic unlocks which squares to fill and leave empty.
 * Uncover an image through filling and marking.

### Point down the features

* Paint shapes with virtual tools. 
 * Choose colors and strategize brush sizes to fill them all.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by muskan42** [comment]
\assign

**Comment by kunjgit** [comment]
Hey @muskan42! 
We are already having a similar game request in #4508 👀 
Make sure you come up with a cool unique idea 😀 
 Waiting for your new game idea 💗.

**Comment by kunjgit** [comment]
Hey @muskan42 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by kunjgit** [comment]
Hey @muskan42 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)
