### ISSUE TITLE
[New game]: Flappy Bird Game

### ISSUE THREAD

**Issue by dhairyagothi** [kunjgit/GameZone#4712]
### 🎮 Game Request

Game logic and basic description
adding flappy bird game 
![image](https://github.com/kunjgit/GameZone/assets/142989448/768f84c3-d630-4075-961e-8b93077be5c8)

### Point down the features

Game points

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @dhairyagothi ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @dhairyagothi! 
We are already having a similar game request in #4607 👀 
Make sure you come up with a cool unique idea 😀 
 Waiting for your new game idea 💗.
