### ISSUE TITLE
2D Breakout 

### ISSUE THREAD

**Issue by shellyverma** [kunjgit/GameZone#4717]
### 🎮 Game Request

The game is a simple 2D Breakout. The player controls a paddle at the bottom of the screen to bounce a ball and break all the blocks at the top. The ball bounces off the paddle, walls, and blocks. The player scores points for each block broken. The game ends when the ball touches the bottom of the screen, and the player wins if all blocks are broken.

### Point down the features

Paddle Control: Move the paddle left or right using arrow keys.
Ball Mechanics: Ball bounces off walls, paddle, and blocks.
Block Grid: A grid of blocks to break with the ball.
Score Display: Current score displayed on the screen.
Winning Condition: Game displays a winning message when all blocks are broken.
Reset Mechanism: Countdown timer and reset of ball and paddle position after losing a life.
Collision Detection: Ball collision with blocks, walls, and paddle.
Responsive Gameplay: Smooth and responsive controls for an engaging experience.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @shellyverma! 🙂 
 It seems like you are not following proper guidelines !! 👀 
 Read documentation properly !!🙏 
 If you have any queries reach out to us on [Discord🕹️](https://discord.gg/fgwk4XZfxG) .

**Comment by kunjgit** [comment]
Hey @shellyverma ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
