### ISSUE TITLE
[Bug]:  Scrollbar cannot be dragged when website is in dark mode

### ISSUE THREAD

**Issue by techy4shri** [kunjgit/GameZone#4719]
### Give a brief about the bug ✍️

The scrollbar doesn't work properly, as in you cannot drag it up or down, when dark mode is in use. The dragging only works when the light mode is on.

https://github.com/kunjgit/GameZone/assets/141991095/899a603f-fe29-414f-b80c-090bf08d188c

### What is the expected behavior? 🤔

The scrollbar should function irrespective of the display settings and user should be able to drag it up or down no matter what light settings are set.

### Provide step by step information reproduce the bug 📄

1. Go to the website.
2. If dark mode is one, try to drag the scrollbar.
3. Now switch to light mode and try dragging the scrollbar again.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @techy4shri ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by techy4shri** [comment]
@kunjgit hey there! I just checked and the issue seems to be no longer present on the website. How come this happened? Please look into this. How can someone else work on ana issue I raised?

**Comment by kunjgit** [comment]
Hey @techy4shri ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
