### ISSUE TITLE
[Bug]: Search function of the website doesn't work.

### ISSUE THREAD

**Issue by techy4shri** [kunjgit/GameZone#4720]
### Give a brief about the bug ✍️

When you enter anything in the search box to search and click on the search icon, it doesn't search anything. Even pressing enter key doesn't work. 

https://github.com/kunjgit/GameZone/assets/141991095/bbae6db1-db1b-4b92-8476-44d0c489ed32

### What is the expected behavior? 🤔

The searchbox should function properly such that it brings back results related to the searched word. Upon pressing enter key or clickin on the search icon, two scenarios can happen:
1. The games related to the sarched words are shown if they are on the website.
2. If no such game exist, then either display an error message belwo the search box or show nothing.

### Provide step by step information reproduce the bug 📄

1. Go to the website and type anything in the search box.
2. Click on the magnifying glass icon or press enter.
3. See the error.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @techy4shri , You can't have another issue before completing the previous one 😀 
 you already have the following 1 open issues 👀 ! :

#4719

**Comment by kunjgit** [comment]
Hey @techy4shri ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by kunjgit** [comment]
Hey @techy4shri ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by techy4shri** [comment]
Understood!

**Comment by techy4shri** [comment]
@kunjgit hey there, I just checked that the issue was solved on the website but one one has been assigned to the issue. Please check. How can someone else work on this when I raised the issue?
