### ISSUE TITLE
[New game]: Guess the Murderer

### ISSUE THREAD

**Issue by abckhush** [kunjgit/GameZone#4722]
### 🎮 Game Request

It is an engaging and interactive detective-themed game that challenges players to identify the culprit by analyzing clue cards and eliminating suspects.

### Point down the features

1. Clue Analysis: Players read through a series of clue cards to gather information about the case.
2. Suspect Elimination: Players can click on suspect images to eliminate them based on the clues.
3. Interactive Prompts: The game provides prompts and feedback to guide players through the investigation process.
4. Final Decision: Players can confirm their final suspect and receive feedback on their choice.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @abckhush , You can't have another issue before completing the previous one 😀 
 you already have the following 1 open issues 👀 ! :

#4603

**Comment by kunjgit** [comment]
Hey @abckhush ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by kunjgit** [comment]
Hey @abckhush ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by abckhush** [comment]
Hi @kunjgit. It's been weeks since my last PR has been accepted. Kindly accept that so I can contribute more.
