### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by techy4shri** [kunjgit/GameZone#4726]
### Give a brief about the bug ✍️

There's an aux.js file in the repository which causes issues while cloning the repository on windows. This happens because aux is a reserved keyword and Windows has a file named aux. Please check.
![Screenshot 2024-07-02 001512](https://github.com/kunjgit/GameZone/assets/141991095/73367db4-c206-4b8c-a457-d6ed7e089189)
![Screenshot 2024-07-02 001205](https://github.com/kunjgit/GameZone/assets/141991095/15d60d56-8c2c-4ead-bab2-91a56dfdb557)
![Screenshot 2024-07-01 235614](https://github.com/kunjgit/GameZone/assets/141991095/1a25f6e5-bbca-43ea-874b-68324ba7d949)

### What is the expected behavior? 🤔

the file should be named anything but aux.js as this creates issues for any collaborator working on Windows.

### Provide step by step information reproduce the bug 📄

Using Windows OS, clone the repo.\
The issue shows up.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @techy4shri , You can't have another issue before completing the previous one 😀 
 you already have the following 1 open issues 👀 ! :

#4719

**Comment by kunjgit** [comment]
Hey @techy4shri ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by kunjgit** [comment]
Hey @techy4shri ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by Wahid7852** [comment]
> Hey @techy4shri , You can't have another issue before completing the previous one 😀 you already have the following 1 open issues 👀 ! :
> 
> #4719

asking @kunjgit to check it out since its an important issue

**Comment by kunjgit** [comment]
@techy4shri I have renamed the file !

**Comment by Wahid7852** [comment]
thanks man

**Comment by techy4shri** [comment]
> @techy4shri I have renamed the file !

Thanks a lot!
