### ISSUE TITLE
[New game]: Bubble Game

### ISSUE THREAD

**Issue by katarianikita2003** [kunjgit/GameZone#4733]
### 🎮 Game Request

Game logic and basic description

Click on The Given number 

https://github.com/kunjgit/GameZone/assets/158465309/38d2ec6c-dd83-417c-998e-6e04c80ea0e3

### Point down the features

Game points
- Hits will be shown and user will have to click on that number
- Every Hit will score 10 marks
- 30 sec timer will be given every time

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @katarianikita2003 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @katarianikita2003! 
We are already having a similar game request in #4598 👀 
Make sure you come up with a cool unique idea 😀 
 Waiting for your new game idea 💗.

**Comment by kunjgit** [comment]
Hey @katarianikita2003 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
