### ISSUE TITLE
[New game]: Tech Memory Block

### ISSUE THREAD

**Issue by somilyadav7** [kunjgit/GameZone#4736]
### 🎮 Game Request

Game logic and basic description
Match pairs of tech icons from various technologies and devices by flipping blocks and remembering their positions to test and improve your memory skills.

### Point down the features

Game points
Intro Screen: Introduction of the game
Difficulty mode selection: Selection for a difficulty level for the game. The difference between each level will be explained in a later section.
Gameplay area: This is where the user plays the actual game.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @somilyadav7 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
