### ISSUE TITLE
[New game]: Angry Bird

### ISSUE THREAD

**Issue by arunimaChintu** [kunjgit/GameZone#4744]
### 🎮 Game Request

Modify Coins:

Allows users to change their current coin count to a specified amount.
Input the current number of coins, and the script sets the coin count to a high value (e.g., 999,999).
Unlock All Levels:

Unlocks all levels in the game, allowing access to play any level without needing to progress sequentially.
Ensures that all stages are available for immediate play.
Unlock All Birds:

Unlocks all bird characters, providing access to every bird in the game.
This feature lets users utilize any bird with unique abilities from the start.
User-Friendly Interface:

Simple HTML interface with buttons for each action.
Easy to use with prompts and alerts guiding the user through each modification process.

### Point down the features

Game points- Level 3

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @arunimaChintu ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by arunimaChintu** [comment]
@kunjgit Please assign me this issue

**Comment by arunimaChintu** [comment]
@kunjgit How to self assign I didnt understood

**Comment by arunimaChintu** [comment]
@kunjgit ...

**Comment by kunjgit** [comment]
Hey @arunimaChintu ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
