### ISSUE TITLE
[Bug]: Main website is not working properly

### ISSUE THREAD

**Issue by mohitgedar** [kunjgit/GameZone#4756]
### Give a brief about the bug ✍️

Description : These bugs/enhancements are based on latest clone of the main project as well as published website.

- Games don't load as they used to, both in latest clone and main website.
- The scroller is not working properly , it hangs anytime anywhere, both in clone and website
- There is not much difference between Dark mode and Light mode in clone as website color keeps changing every few seconds.
- In footer section of latest clone there is a duplication of Socials
- In the footer of website, Instagram link is not provided, but is provided in clone.
- Pagination of contributors is not working , the buttons don't work 
- Html file contains inline style ,we need to move them to style.css for better maintainability of Html code
- Some CSS files are getting very large , they should be separated into multiple files and there are CSS properties that are not used anywhere.
- Previous and next button needs rearrangement as they look very odd with page number buttons and both are not of same size.
- website also needs to be enhanced in terms of responsive design. for small screens the website don't adapt very well.

There may be some other functionality and bugs that may need to be addressed as we resolve these.

### What is the expected behavior? 🤔

Description : 
- Games should load and play when clicked
- scroller should work smoothly and without getting stuck anywhere
- There should not be duplication of socials
- when a page number is clicked , contributors of that page should show
- Html and CSS should be in separate files for better maintainability
- previous and next buttons should be of same size and adjacent to other page buttons , like in most websites we encounter  each day
- website should adjust to different screen sizes properly

### Provide step by step information reproduce the bug 📄

Description : The steps to solve these issues can not  be explained before hand , They need to be addressed on the go as we go through codebase.
Although some of them can be explained

- I would also like to remove the toggle between dark and light theme , making it permanently dark themed **if you agree.**
- Remove the duplicated socials .
- Move all style from Html to separate CSS file.
- Adjust CSS of previous and next buttons to make them better inclined with the page.
- Add CSS so that the website respond well to small screens

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @mohitgedar ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by mohitgedar** [comment]
I am closing this issue because it is pointed out to me that I should create separate PR for each issue ,so that the overall changes are easy to review and merge ,if i solve too many things in one PR it may get difficult to clear conflicts merge it .

**Comment by kunjgit** [comment]
Hey @mohitgedar ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
