### ISSUE TITLE
[New game]: Maze explorer game 

### ISSUE THREAD

**Issue by aditya-bhaumik** [kunjgit/GameZone#4758]
### 🎮 Game Request

"Maze Explorer" is a thrilling adventure game where players navigate through intricate mazes, collecting treasures while avoiding obstacles. The goal is to reach the exit before time runs out, exploring multiple levels of challenging puzzles and surprises along the way

### Point down the features

Dynamic Maze Generation: Each playthrough features randomly generated mazes, ensuring a fresh challenge every time.

Treasure Collection: Players must collect treasures scattered throughout the maze to earn points and bonuses.

Time Management: Navigate efficiently to reach the exit before the timer runs out, while avoiding traps and strategically using power-ups for extended gameplay.Game points

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @aditya-bhaumik ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @aditya-bhaumik ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
