### ISSUE TITLE
[Bug]: Main website not working properly

### ISSUE THREAD

**Issue by mohitgedar** [kunjgit/GameZone#4760]
### Give a brief about the bug ✍️

Description: these bugs are based on latest clone of the project
- The scroller of the website don't work , it hangs anywhere , anytime .
- The Socials have duplicate entry.
- The page buttons of the contributors sections are not working properly.
- Images are placed at wrong places
- Main page is horizontally aligned , it should be vertically aligned
- Games don't load on the main website

### What is the expected behavior? 🤔

Description:
- The scroller should work smoothly. 
- Duplicate socials should be removed
- page buttons of the contributors section should work , so that one can see all contributors
- Images should be moved to right folder
- Main page should be vertically aligned

### Provide step by step information reproduce the bug 📄

Description:
You can see all these bugs by opening index.html in your browser from the latest clone of the repo .
 
- the bug for scroller needs to be addressed by analyzing the codebase
- duplicate socials can be removed from main html file directly
- bug regarding page button not working also needs to be searched for.
- Images that are placed in wrong folders can be moved to the right destination
- HTML structure and CSS need to be checked to make to page vertical
- games not loading , for this we need to check JS files .

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @mohitgedar ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @mohitgedar ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
