### ISSUE TITLE
[New game]: Hexsweep Game

### ISSUE THREAD

**Issue by ananyag309** [kunjgit/GameZone#4768]
### 🎮 Game Request

Game logic and basic description - Hex Sweep is a strategic puzzle game where players clear a hexagonal grid by identifying and marking mines based on numerical clues. It combines elements of logic and deduction, challenging players to carefully analyze the board and make precise moves to avoid triggering hidden mines.

### Point down the features

Game points - In Hex Sweep, players earn points by correctly identifying and marking all the mines on the grid without triggering any. Points are awarded based on the speed and accuracy of their moves, with bonus points for completing more challenging levels.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @ananyag309 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)
