### ISSUE TITLE
[New game]: BOOM BLAST

### ISSUE THREAD

**Issue by Shantnu-singh** [kunjgit/GameZone#4776]
### 🎮 Game Request

  - When the player clicks the "Start Game" button, the game begins. 
   - The timer is set to 30 seconds, and the score is reset to 0.
   - Every second, a new colored balloon appears randomly within the game area.
   - Each balloon has a random size and a bright color.
   -  A "Game Over" message is displayed, showing the player's final score.
   - The "Start Game" button is re-enabled so the player can start a new game.

### Point down the features

#features 
- interactive 
- colourful design
- simple controls
- limited time challenges
- 

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Shantnu-singh , You can't have another issue before completing the previous one 😀 
 you already have the following 1 open issues 👀 ! :

#4770

**Comment by kunjgit** [comment]
Hey @Shantnu-singh ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by kunjgit** [comment]
Hey @Shantnu-singh ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)
