### ISSUE TITLE
[Bug]: Multiple Issues on Website ,these bugs are based on latest clone of the project

### ISSUE THREAD

**Issue by priyashuu** [kunjgit/GameZone#4779]
### Give a brief about the bug ✍️

**Description:** 
Game Search Issue: We are unable to find any games when using the search functionality.
Text Alignment Issues: The text on the website  is not vertically aligned correctly
Heading Cutout Issues:  The headings on the website are cut off and not fully visible.
Navigation Issue: We are unable to navigate to the previous page.
Dark Theme Navbar Visibility: The navbar is not  fully visible in dark theme because of the text color , which negatively impacts user experience.
Contribution Page Access (Light Theme): The contribution page is accessible only in light theme. In dark theme, it does not work.
Footer section has been cutout 
Here is the video sample:

https://github.com/kunjgit/GameZone/assets/150767072/9881550e-9948-4c05-9b28-2d714f8daf7b

### What is the expected behavior? 🤔

Description
 The search results should display relevant games based on the search query.

 The text should be properly aligned vertically within its container.

 The headings should be fully visible and not cut off.

 Clicking the previous page button should navigate to the previous page of content.

The contribution page should be accessible and function correctly in both light and dark themes.

The navbar should be clearly visible and functional in both light and dark themes.

 The footer section should be fully visible and contain all intended content. The navbar should be clearly visible and functional in both light and dark themes.

The footer section should be fully visible and contain all intended content.

### Provide step by step information reproduce the bug 📄

Description

For Game Search Issues: Using js properties and methods to resolve this issues
For Text Alignment Issues: Adding Some padding to the text , adding some more properties of css to control the overflow text.
For Heading cutout Issues :using css properties  to centre the head elements
for Navigation Issue: using Js properties to place the correct url.
for Contribution Page Access: using js properties to place correct url in the dark them also.
Navbar Visibility :using the colorhunt website to choose correct color  for the navbar .
Scrollbar is not working sometimes.
Footer Section Cutout: Everything in the footer section has been cut off and is not visible.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @priyashuu , You can't have another issue before completing the previous one 😀 
 you already have the following 1 open issues 👀 ! :

#4754

**Comment by kunjgit** [comment]
Hey @priyashuu ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by kunjgit** [comment]
Hey @priyashuu ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)
