### ISSUE TITLE
[New game]: Falling Blocks

### ISSUE THREAD

**Issue by thakurdiwakar** [kunjgit/GameZone#478]
### 🎮 Game Request

Falling Blocks is a simple yet addictive game in which players use a platform at the bottom of the screen to catch falling blocks. The goal is to catch as many blocks as possible in order to score as many points as possible.

The game starts with a player-controlled platform in the bottom-center of the screen. Blocks of various shapes and colours begin to fall from the top of the screen at a consistent rate. To collect the falling pieces, the player must move the platform horizontally using the left and right arrow keys (or any other predefined controls).

### Point down the features

1.Easy to play
2.Addective
3.Responsive

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @thakurdiwakar ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by thakurdiwakar** [comment]
Hey is there any due date for completing the task,i have successfully created the game,and working on  some more features.

**Comment by kunjgit** [comment]
Hey @thakurdiwakar ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
