### ISSUE TITLE
[New game]: Want to Add New Game Five Nights At Freddy 

### ISSUE THREAD

**Issue by nishant0708** [kunjgit/GameZone#4784]
### 🎮 Game Request

Game logic and basic description
In this Game We are Locked in One room and There are 5 Killers which can move freely around house and are looking for us we spy on them using cameras and when we look any killer by camera he cant move . Our Aim is to Survive

### Point down the features

Game points
To Survive 

![image](https://github.com/kunjgit/GameZone/assets/101548649/94af79b7-140c-4511-add7-09cc5e15c3c2)

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @nishant0708 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @nishant0708 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
