### ISSUE TITLE
[New game]: A Dragon Game

### ISSUE THREAD

**Issue by Ishitamukherjee2004** [kunjgit/GameZone#4787]
### 🎮 Game Request

Game logic and basic description
A obstacle or a bad dragon will come towards the good dragon and good dragon have to jump to avoid the obstacle.

https://github.com/kunjgit/GameZone/assets/138589633/411de82d-9e2c-43a7-86bf-4835ed38bcbf

### Point down the features

Game points
The game will have the feature of update the score.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Ishitamukherjee2004 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @Ishitamukherjee2004 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
