### ISSUE TITLE
[Bug]: Instagram hover color not matching with original icon color in footer

### ISSUE THREAD

**Issue by Maana-Ajmera** [kunjgit/GameZone#4794]
### Give a brief about the bug ✍️

Description
Instagram hover color not matching with original icon color in footer

https://github.com/kunjgit/GameZone/assets/162733812/d8ca0498-0d78-4b0f-b414-5f9900acc288

### What is the expected behavior? 🤔

Description

https://github.com/kunjgit/GameZone/assets/162733812/255b6b32-8ca1-405c-96a6-3a234b3ea1f8

### Provide step by step information reproduce the bug 📄

Description

Change the hover color of instagram icon

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by Maana-Ajmera** [comment]
@kunjgit Please assign it to me under gssoc

**Comment by kunjgit** [comment]
Hey @Maana-Ajmera ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @Maana-Ajmera ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
