### ISSUE TITLE
[New game]: Maze Game 

### ISSUE THREAD

**Issue by Pragati-3003** [kunjgit/GameZone#480]
### 🎮 Game Request

I am writing to request the addition of my Maze Game project. 
![maze_game](https://github.com/kunjgit/GameZone/assets/132778037/7b23f907-3ab1-4677-95a7-b406e3c9ae7c)

### Point down the features

The Maze Game is a fully functional interactive game that challenges players to navigate through a series of mazes. 
The game features various levels of difficulty, visually appealing graphics, and an intuitive user interface.
So, please assign this to me. 

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Pragati-3003 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @Pragati-3003! 
We are already having a similar game request in #456 👀 
Make sure you come up with a cool unique idea 😀 
 Waiting for your new game idea 💗.

**Comment by kunjgit** [comment]
Hey @Pragati-3003 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
