### ISSUE TITLE
[Enhancement]: Enhanced the navbar of the main website

### ISSUE THREAD

**Issue by mohitgedar** [kunjgit/GameZone#4801]
### Do you want to have the enhancement of existing game ? 😀 Describe yourself..

- The navbar of the main website don't respond well to different screen sizes .

- The links in the navbar don't work .

- The theme-toggle button is placed incorrectly .

- Navbar hides when we scroll down the page.

### Describe the solution you'd like

- I would like the navbar to be responsive to different screen sizes and with smooth transitions .

- The links of the navbar should work 

- **#A new link *contact* should be added**

- The Theme-toggle button should be a part of navbar

- Navbar should be fixed at the top as that the links of the navbar can be used to move through the website.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @mohitgedar ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @mohitgedar ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
