### ISSUE TITLE
Dance Dance Revolution Clone

### ISSUE THREAD

**Issue by mahek0620** [kunjgit/GameZone#4805]
### 🎮 Game Request

Dance Dance Revolution (DDR) Clone is a rhythm-based game where players press specific keys in sync with musical beats. The game displays directional arrows (up, down, left, right) that move from the bottom of the screen to a target area at the top. Players must press the corresponding key when the arrow overlaps with the target area. Accurate timing awards points, and missed notes decrease the player's score.

### Point down the features

Arrow Generation: Arrows appear at the bottom of the screen and move upwards towards the target area.
Key Press Detection: The game detects when players press the correct keys (up, down, left, right) and matches it with the arrows reaching the target area.
Timing Accuracy: Points are awarded based on how accurately the player presses the key in sync with the arrow reaching the target area. Accuracy levels include Perfect, Great, Good, and Miss.
Score Tracking: The game tracks and displays the player's score in real-time.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @mahek0620 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @mahek0620! 🙂 
 It seems like you are not following proper guidelines !! 👀 
 Read documentation properly !!🙏 
 If you have any queries reach out to us on [Discord🕹️](https://discord.gg/fgwk4XZfxG) .

**Comment by kunjgit** [comment]
Hey @mahek0620 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
