### ISSUE TITLE
Parachute Game

### ISSUE THREAD

**Issue by mahek0620** [kunjgit/GameZone#4806]
### 🎮 Game Request

Control a parachutist to land safely on a target.

### Point down the features

Character Control:
Use arrow keys or touch controls to move the parachutist left or right.
Wind Simulation:
Random wind gusts that push the parachutist in different directions, adding a layer of challenge.
Obstacles:
Birds, balloons, and other objects that the parachutist must avoid while descending.
Landing Zone:
A target area that the parachutist must land on to score points. Different sections of the target can offer different point values.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @mahek0620 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @mahek0620! 🙂 
 It seems like you are not following proper guidelines !! 👀 
 Read documentation properly !!🙏 
 If you have any queries reach out to us on [Discord🕹️](https://discord.gg/fgwk4XZfxG) .

**Comment by kunjgit** [comment]
Hey @mahek0620 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by mahek0620** [comment]
@kunjgit This game is not present in the repo
