### ISSUE TITLE
[New game]: Add a Tower blocks game

### ISSUE THREAD

**Issue by Arnabhit** [kunjgit/GameZone#481]
### 🎮 Game Request

Game logic and basic description
It willl be a HTML,CSS AND JAVASCRIPT GAME based on the fact that we have to build a tower as long as we can. And in each step if our block does not fit the previous block the a part of the current block will be cut. In this way when no block will remain then our height of the tower will be calculated.

### Point down the features

Game points
Calculates tower height and creates a benchmark so that user can progress

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Arnabhit ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by Arnabhit** [comment]
hello @kunjgit I have seen that a Tower_blocks game is already pushed yesterday so i will like to add other games. Can you Please  close this issue.

**Comment by kunjgit** [comment]
Hello @Arnabhit, Time's Uppp!⏰ 
 Sorry for closing your issue! 
 But it's more than a week since we haven't received anything from your side 😢 . 
 Come up with new ideas, create a new issue and make sure you finish it within a week! 🔥 
 All the best! 🚀 
 Happy Hacking! 💗

**Comment by kunjgit** [comment]
Hey @Arnabhit ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
