### ISSUE TITLE
[New game]:  I want to add a Rocket Shooter game.

### ISSUE THREAD

**Issue by vishanurag** [kunjgit/GameZone#4812]
####  _Game logic and basic description_

- There will be some enemy rockets who will try to attack.
- Our mission will to shoot those enemy rockets to win the game. 

####  _Game points_

- Enemy rockets will try to attack on our rocket.
- Our mission is to shoot enemy rockets to win the game.
- I am a GSSOC'24 contributer.
- Please assign this issue to me under gssoc labels.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @vishanurag ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @vishanurag ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
