### ISSUE TITLE
[New game]: Guess the valorant agent 

### ISSUE THREAD

**Issue by manasdeshpande** [kunjgit/GameZone#4814]
### 🎮 Game Request

there would be a valorant agent on the left and 80 % of the image would be hidden we have to guess the agent

### Point down the features

Game points
1st guess:50 points 
2nd guess:30 points 
3rd guess:10 points 

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @manasdeshpande , You can't have another issue before completing the previous one 😀 
 you already have the following 1 open issues 👀 ! :

#4743

**Comment by kunjgit** [comment]
Hey @manasdeshpande ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by kunjgit** [comment]
Hey @manasdeshpande ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)
