### ISSUE TITLE
[Enhancement]:  Fix Contributors Link and Add Games Link in Navbar

### ISSUE THREAD

**Issue by shreyasmunge** [kunjgit/GameZone#4818]
### Do you want to have the enhancement of existing game ? 😀 Describe yourself..

The Contributors navigation link in the navbar is currently not working. Additionally, I would like to add a Games navigation link to the navbar, allowing users to jump directly to the games section. 

https://github.com/kunjgit/GameZone/assets/125213858/b944f1be-a143-4104-b6a2-f0a0b6415eca

@kunjgit Please assign me this task under GSSoC 2024. 
Thank you!

### Describe the solution you'd like

1. **Fix Contributors Link:** Check the href attribute of the Contributors link in the navbar and correct it to point to the appropriate section or page.
2. **Add Games Link:** Add a new navigation item in the navbar with the href attribute pointing to the Games section or page. Ensure it follows the same style and structure as the existing links.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @shreyasmunge ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @shreyasmunge ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
