### ISSUE TITLE
[New game]: Doraemon Run

### ISSUE THREAD

**Issue by Maana-Ajmera** [kunjgit/GameZone#4819]
### 🎮 Game Request

Game logic and basic description
Players have to jump on the dorayakis to get score
Touching the mouses will decrese the totatl score by 1
Start the game by clicking the start button and play again by pessein f5 key

### Point down the features

left,right,up key
fully responsive design

https://github.com/kunjgit/GameZone/assets/162733812/4b1894fc-8e74-4c88-a23f-c91fce4693d0

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Maana-Ajmera , You can't have another issue before completing the previous one 😀 
 you already have the following 1 open issues 👀 ! :

#4794

**Comment by kunjgit** [comment]
Hey @Maana-Ajmera ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)
