### ISSUE TITLE
[New game]: Add new game Snake Water gun 

### ISSUE THREAD

**Issue by ANKeshri** [kunjgit/GameZone#4820]
### 🎮 Game Request

In this game you have to choose between snake,water and gun. Snake kills the water, water kills the gun and gun kills the snake. 

**Additional**

I have seen that someone has added this game but it is not looking good and is very simple . I have linked the video of game . If you want I can add otherwise you can close this issue .

### Point down the features

In this game winner will get 1 point. if both choose the same then both will get 1 points. in total of 10 rounds who gets the highest points will be considered as winner.

https://github.com/user-attachments/assets/df8a7d48-8f3f-4dbe-b0fd-cf489c5e0ecf

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @ANKeshri ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @ANKeshri ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
