### ISSUE TITLE
[New game]: Catch the emoji game

### ISSUE THREAD

**Issue by Maana-Ajmera** [kunjgit/GameZone#4821]
### 🎮 Game Request

Game logic and basic description

- Click on the randomly appearing emojis at the right time to score
- Score will be calculated based on the number of emojis caught within the given time

### Point down the features

Game points

More you catch the emoji , more will be the points 
Catch maximum emojis in given time

https://github.com/kunjgit/GameZone/assets/162733812/896436b2-9022-4a9f-9792-9502bc849420

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Maana-Ajmera , You can't have another issue before completing the previous one 😀 
 you already have the following 1 open issues 👀 ! :

#4794

**Comment by kunjgit** [comment]
Hey @Maana-Ajmera ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by kunjgit** [comment]
Hey @Maana-Ajmera ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)
