### ISSUE TITLE
[Bug]: When press home in master typing website is not working

### ISSUE THREAD

**Issue by jayanththalla** [kunjgit/GameZone#4824]
### Give a brief about the bug ✍️

Description
If i press the home button in the master typing is not working 
![image](https://github.com/user-attachments/assets/d4da3cdc-77a6-4b3f-890f-21e2e47aae42)

### What is the expected behavior? 🤔

Description

### Provide step by step information reproduce the bug 📄

Description

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @jayanththalla ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @jayanththalla ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
