### ISSUE TITLE
[New game]: Hedgehog Havoc

### ISSUE THREAD

**Issue by shellygarg10** [kunjgit/GameZone#4827]
### 🎮 Game Request

Game logic and basic description : The player takes control of a fearless bunny on a mission to gather as many delicious carrots as possible. But beware! The field is crawling with prickly hedgehogs, determined to stop your veggie quest.

### Point down the features

Game points : The longer the player avoids those hedgehogs, the FASTER their score grows! Every safe second earns a bigger score boost! 

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @shellygarg10 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
