### ISSUE TITLE
[New game]: infinite Cars

### ISSUE THREAD

**Issue by divyansh-2005** [kunjgit/GameZone#4828]
### 🎮 Game Request

Game logic and basic description

https://github.com/user-attachments/assets/42512b06-dd71-45a8-b164-45aad863f5be

### Point down the features

Game points
refer the video

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @divyansh-2005 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by ishita-43** [comment]
You can always selff assign  the issue here, now it is assigned you can start working on it

**Comment by kunjgit** [comment]
Hey @divyansh-2005 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
