### ISSUE TITLE
[New game]: Four in row

### ISSUE THREAD

**Issue by heli0707** [kunjgit/GameZone#4830]
### 🎮 Game Request

**Four in a Row** is a two-player strategy game where players take turns dropping colored discs into a vertical grid. The objective is to connect four of their own discs in a row—either horizontally, vertically, or diagonally—before the opponent does.

### Point down the features

- **Two-Player Mode:** Designed for two players, either competitively or cooperatively.
- **Vertical Grid:** Features a vertical grid with slots where discs are dropped.
- **Disc Colors:** Players use different colored discs to differentiate between their moves.
- **Winning Condition:** The goal is to connect four discs in a row, either horizontally, vertically, or diagonally.
- **Turn-Based Play:** Players take turns dropping discs into the grid.
- **Game Over Detection:** The game ends when a player achieves four in a row or when the grid is full.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @heli0707 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by heli0707** [comment]
@kunjgit assign

**Comment by abhisek2004** [comment]
i want to contribute add me i will give or add new game to it

**Comment by kunjgit** [comment]
Hey @heli0707 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
