### ISSUE TITLE
[New game]: Ninja Hattori 

### ISSUE THREAD

**Issue by Maana-Ajmera** [kunjgit/GameZone#4833]
### 🎮 Game Request

Game logic and basic description

A very popular cartoon ninja hattori is all here !
Dont let "kiyo" hurt ninja hattori

### Point down the features

Game points

- Save ninja hattori from kiyo till the destination to win
- Jump when kiyo comes your way and move ahead , 
- More the number of kiyo you defeat , more will be the points
- As soon as you come in contact with kiyo , game is over 

https://github.com/user-attachments/assets/352c2b6f-9bc9-42a3-8d1a-cbb56ba1ecb3

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Maana-Ajmera ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @Maana-Ajmera ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
