### ISSUE TITLE
[New game]: Brick Blaster

### ISSUE THREAD

**Issue by ananyag309** [kunjgit/GameZone#4835]
### 🎮 Game Request

Game logic and basic description

The player controls a paddle to bounce a ball and destroy bricks in order to clear each level. Power-ups and different types of bricks add variety and challenge to the gameplay.

### Point down the features

Game points
Brick Blaster is an engaging arcade game where players control a paddle to keep a ball in play, aiming to break all the bricks arranged in rows and columns at the top of the canvas. The game features smooth ball movement, responsive paddle controls using keyboard and mouse, and dynamic collision detection. With each successful brick hit, the score increases, and the game includes a popup message for "Game Over" and "Play Again" functionality. The visually appealing canvas background enhances the overall gaming experience.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @ananyag309 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @ananyag309 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
