### ISSUE TITLE
[New game]: Matching Pairs

### ISSUE THREAD

**Issue by priyashuu** [kunjgit/GameZone#4844]
### 🎮 Game Request

Game logic and basic description
1. Initialization
Card Generation: Duplicate a set of symbols to create pairs, then shuffle.
Grid Setup: Dynamically create card elements and append them to the game container.
2. Card Flipping
Event Listener: Each card has an event listener to trigger the flip.
Flipping Logic: On click, reveal the card symbol. Store the first card, then check for a match with the second card.
3. Matching Logic
Match Check: Compare the symbols of two flipped cards. If they match, keep them face-up; if not, flip them back down after a brief delay.

### Point down the features

Game points

**Timer and Scoring System**: Track your performance with a real-time timer and move counter, challenging yourself to complete the game in the shortest time with the fewest moves.
**Difficulty Levels:** Choose from different grid sizes and levels of difficulty, from a 4x4 grid for beginners to larger grids for a more challenging experience.
**Animations and Visual Feedback**: Enjoy smooth animations and visual effects, including a 3D card flip animation when cards are matched, providing satisfying feedback and enhancing gameplay immersion.
**Sound Effects**: Delight in subtle sound effects for card flips and matches, and an optional background music track to create a more engaging atmosphere.
**Game Over and Restart**: Upon completing the game, receive a congratulatory message with your final score and time. Easily restart the game or choose a different difficulty level to keep the fun going.

***Screenshot of the Game***
![matchin-pair-game](https://github.com/user-attachments/assets/fe419a8b-1219-4962-8360-80a708ea0080)

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @priyashuu , You can't have another issue before completing the previous one 😀 
 you already have the following 1 open issues 👀 ! :

#4754

**Comment by kunjgit** [comment]
Hey @priyashuu ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by kunjgit** [comment]
Hey @priyashuu ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)
