### ISSUE TITLE
[New game]: Mosquito Whack: The Ultimate Bug-Busting Challenge!

### ISSUE THREAD

**Issue by ankit071105** [kunjgit/GameZone#4846]
### 🎮 Game Request

# Basic Description:
"Mosquito Whack" is an engaging and fast-paced game designed to test your reflexes and precision. The objective of the game is to swat as many mosquitoes as possible within a 30-second timeframe. Each successful hit awards points, while missing three mosquitoes results in game over. The game is complemented by lively background music and satisfying sound effects upon each successful hit, enhancing the overall gaming experience.

# Game Logic:

1 Game Start:
The game begins with a start screen where the player can start the game.
Background music starts playing as soon as the game begins.

2 Gameplay:
A 30-second timer starts counting down once the game begins.
Mosquitoes appear randomly on the screen at varying intervals and locations.
The player must click or tap on the mosquitoes to "whack" them.

3Scoring:
Each successful mosquito hit scores points for the player.
A sound effect is played with each successful hit to provide feedback.

4 Miss Count:
The player has three chances to miss hitting a mosquito.
Each time the player misses a mosquito, a miss counter increases.
If the miss counter reaches three, the game is over.

5 Timer:
The game runs on a 30-second timer.
When the timer reaches zero, the current game session ends.
If the game ends due to time running out, it automatically restarts for another session.

6 Game Over Conditions:
The game ends if the player misses three mosquitoes.
A game over screen is displayed, showing the player's score and an option to play again.

7Game Restart:
If the 30-second timer expires, the game restarts automatically for another round of mosquito whacking.
The player can also manually restart the game from the game over screen.

# VIDEO

https://github.com/user-attachments/assets/86a08beb-7886-411f-bf52-8e684f5272ae

### Point down the features

Features:

⦿ Background Music: Keeps the player engaged with an energetic soundtrack.

⦿ Sound Effects: Provides auditory feedback for each successful hit, adding to the game's excitement.

⦿ Score Display: Shows the player's current score during gameplay.

⦿ Miss Counter: Displays the number of misses, giving the player a visual cue of their remaining chances.

⦿ Timer Display: Keeps the player informed about the remaining time in the game session.

### Select program in which you are contributing

IWOC2024, GSSoC24, hacktoberfest, Other

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @ankit071105 , You can't have another issue before completing the previous one 😀 
 you already have the following 1 open issues 👀 ! :

#4845

**Comment by kunjgit** [comment]
Hey @ankit071105 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by kunjgit** [comment]
Hey @ankit071105 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by ankit071105** [comment]
assigned
