### ISSUE TITLE
[New game]:  Gita Shloka Generator

### ISSUE THREAD

**Issue by nikki-05** [kunjgit/GameZone#4849]
### 🎮 Game Request

Game logic and basic descriptionThe Gita Shlok Generator is an engaging and educational web-based game designed to introduce players to the profound teachings of the Bhagavad Gita. By generating random shlokas (verses) from the Gita, the game provides players with a unique opportunity to explore and understand the timeless wisdom embedded in this ancient scripture. The game is perfect for kids and adults, offering a blend of spiritual learning and interactive fun.

### Point down the features

Each shlok comes with its Sanskrit text, transliteration, translation, and explanation to help players understand the meaning and context of the verse. Players can generate a new shlok by clicking the "Generate Random Shlok" button, which will randomly select a shlok from the list and display it on the screen. 
**Features**

-simple UI
-A beautiful background image of Lord Krishna sets a serene and spiritual ambience.
-Players can generate random shlokas with a single click.
-It helps players learn Sanskrit and understand the philosophical concepts of the Gita.
-Developers can add more shlokas, improve the UI/UX, and enhance features.
Sample of the game.
![Screenshot 2024-07-14 161922](https://github.com/user-attachments/assets/f5fcd7f4-59f9-4760-af8b-524d8753ae60)

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @nikki-05 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @nikki-05 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
