### ISSUE TITLE
[Bug]: Nav bar is not responsive

### ISSUE THREAD

**Issue by bhumii-ka** [kunjgit/GameZone#4850]
### Give a brief about the bug ✍️

The nav bar is not responsive for small screen sizes (mobile screens), It cuts of the options in the navbar that does not look good.

### What is the expected behavior? 🤔

This issue can be by turning the navbar to a side nav menu (hamburger menu)  when screen size is less than 530px. I can fix this issue please assign it to me under GSSoC'24

### Provide step by step information reproduce the bug 📄

![image](https://github.com/user-attachments/assets/1c97cc99-a892-4f29-b389-e04262278d8f)

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @bhumii-ka ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @bhumii-ka ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
