### ISSUE TITLE
Add Legal Information to Footer

### ISSUE THREAD

**Issue by lovelymahor** [kunjgit/GameZone#4855]
### Give a brief about the bug ✍️

The footer of our website currently lacks essential legal information. To ensure compliance and provide users with important details, we need to add links to our Privacy Policy and Terms of Service.

### What is the expected behavior? 🤔

The footer should include clearly labeled links to the Privacy Policy and Terms of Service. These links should be styled consistently with the rest of the footer and should open in a new tab when clicked.

### Provide step by step information reproduce the bug 📄

Step 1 Open the website and scroll down to the footer section.
Step 2 Look for links to Privacy Policy and Terms of Service.
Step 3 Observe that the links are missing from the footer.
Step 4 Implement the following changes to add the necessary links:
- Add an HTML section for legal information in the footer.
- Include links to the Privacy Policy and Terms of Service with appropriate href attributes.
- Ensure the links open in a new tab by setting target="_blank".

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by lovelymahor** [comment]
@kunjgit Please assign it to me I want to work on this issue. Also, please add the label GSSOC and the level that you find appropriate for this issue. thank you!

**Comment by kunjgit** [comment]
Hey @lovelymahor ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @lovelymahor! 🙂 
 It seems like you are not following proper guidelines !! 👀 
 Read documentation properly !!🙏 
 If you have any queries reach out to us on [Discord🕹️](https://discord.gg/fgwk4XZfxG) .

**Comment by kunjgit** [comment]
Hey @lovelymahor ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
