### ISSUE TITLE
Improve Font Color Contrast in Dark Mode Navbar

### ISSUE THREAD

**Issue by lovelymahor** [kunjgit/GameZone#4856]
### Give a brief about the bug ✍️

In dark mode, the navbar font color is not clearly visible. This issue affects readability and user experience, as the text blends into the background. The font color contrast needs to be improved for better visibility.

### What is the expected behavior? 🤔

The navbar font color in dark mode should have a higher contrast against the background. The text should be easily readable, ensuring that users can clearly see and interact with the navbar options.

### Provide step by step information reproduce the bug 📄

Step 1: Open the website and switch to dark mode.
Step 2: Observe the navbar font color and how it appears against the dark background.
Step 3: Note that the text is difficult to read due to low contrast.
Step 4: Implement the following changes to improve the color contrast:

- Identify the CSS class or ID used for the navbar text in dark mode.
- Adjust the font color to a lighter shade or a color that contrasts well with the dark background.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @lovelymahor ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @lovelymahor! 🙂 
 It seems like you are not following proper guidelines !! 👀 
 Read documentation properly !!🙏 
 If you have any queries reach out to us on [Discord🕹️](https://discord.gg/fgwk4XZfxG) .

**Comment by lovelymahor** [comment]
@kunjgit  Please assign it to me I want to work on this issue. Also, please add the label GSSOC and the level that you find appropriate for this issue. thank you!

**Comment by kunjgit** [comment]
Hey @lovelymahor ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
