### ISSUE TITLE
[New game]: 

### ISSUE THREAD

**Issue by anushka29github** [kunjgit/GameZone#4858]
### 🎮 Game Request

Implement a Hangman game where players guess letters to reveal a hidden word. Incorrect guesses will result in parts of a hangman being drawn. The game ends when the word is guessed or the hangman is fully drawn.

### Point down the features

Game points:

Display the hidden word with underscores representing unguessed letters.
Show the letters guessed by the player.
Provide an input method for the player to guess letters.
Display the hangman drawing that progresses with each incorrect guess.

Randomly select a word from a predefined list.
Check if the guessed letter is in the word and update the displayed word accordingly.
Track incorrect guesses and update the hangman drawing.
Determine win/loss conditions and display appropriate messages.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @anushka29github ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @anushka29github! 
We are already having a similar game request in #4849 👀 
Make sure you come up with a cool unique idea 😀 
 Waiting for your new game idea 💗.

**Comment by kunjgit** [comment]
Hey @anushka29github ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
