### ISSUE TITLE
[New game]: Number Guessing by speaking the Number 

### ISSUE THREAD

**Issue by ankit071105** [kunjgit/GameZone#4860]
### 🎮 Game Request

Objective:
The objective of the game is for the player to guess a randomly generated number within a specified range by speaking their guesses. The game provides feedback to help the player narrow down the correct number.

Game Flow:
1 Game Initialization :
The game generates a random number within a specified range (e.g., 1 to 100).
The player is prompted to start guessing the number by speaking their guesses.

2 Player Input:
The player speaks a number as their guess.
The game uses speech recognition to convert the spoken number into text.

3 Processing the Guess:
The game compares the player's guess to the randomly generated number.
Based on the comparison, the game provides feedback:
Correct Guess: If the player's guess matches the random number, the game congratulates the player and ends the current round.
Higher/Lower Feedback: If the guess is incorrect, the game informs the player whether the correct number is higher or lower than their guess.
The player continues to guess based on the feedback until they correctly guess the number.

4 Game End and Restart:
Once the player guesses the correct number, they are given the option to play again.
The game resets with a new randomly generated number for the next round.

 5 This game combines the fun of traditional number guessing games with modern speech recognition technology, providing an engaging and interactive experience for players.

# Screenshots :- 

![Screenshot 2024-07-15 at 8 23 02 PM](https://github.com/user-attachments/assets/556b5de5-d801-4b0f-885b-dbf48648ebb0)
![Screenshot 2024-07-15 at 8 22 53 PM](https://github.com/user-attachments/assets/c2832bfa-ae79-48b1-af07-a720c9d5d5a5)

### Point down the features

Features of the Game:

1 Speech Recognition:
The game utilizes speech recognition technology to convert spoken guesses into text.
Ensures that the game is accessible and engaging by allowing hands-free interaction.

2 Range Selection:
Players can choose different difficulty levels by selecting different number ranges (e.g., 1-50, 1-100, 1-200).

3 Feedback System:
Provides real-time feedback on whether the guess is correct, too high, or too low.
Helps players narrow down their guesses efficiently.

4 Score Tracking:
Keeps track of the number of guesses taken by the player to guess the correct number.
Displays the player's score at the end of each round.

5 Voice Feedback:
The game provides voice feedback for a more immersive experience.
Encourages players and guides them through the game with spoken instructions and responses.

6 Multilingual Support:
Supports multiple languages for both speech recognition and voice feedback.
Allows players from different linguistic backgrounds to enjoy the game.

7 User-Friendly Interface:
Simple and intuitive interface designed for easy navigation.
Clear instructions and visual cues to assist players.

8 Play Again Option:
After guessing the correct number, players can choose to play again with a new number.
Option to adjust the difficulty level for the next round.
 
Example Scenario: 

The game generates a random number between 1 and 100.
The player starts guessing by saying, "50."
The game responds with, "The number is higher."
The player then guesses, "75."
The game responds with, "The number is lower."
The player guesses, "63."
The game responds with, "Congratulations! You guessed the correct number."
The player is given the option to play again or choose a different difficulty level.

### Select program in which you are contributing

IWOC2024, GSSoC24, hacktoberfest, Other

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @ankit071105 , You can't have another issue before completing the previous one 😀 
 you already have the following 1 open issues 👀 ! :

#4845

**Comment by kunjgit** [comment]
Hey @ankit071105 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by kunjgit** [comment]
Hey @ankit071105 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by ankit071105** [comment]
#4860 Assigned
