### ISSUE TITLE
[Bug]:  The thumbnail for the Brick Buster game isn't rendering correctly.

### ISSUE THREAD

**Issue by sweta-singh28** [kunjgit/GameZone#4868]
### Give a brief about the bug ✍️

Description
The thumbnail for the Brick Buster game is not rendering correctly, which is causing issues with its visibility and appeal. This improper rendering affects the overall presentation of the game, potentially impacting user engagement and interest. It's important to address this issue promptly to ensure that the thumbnail displays properly and attracts players effectively.

### What is the expected behavior? 🤔

Description
The expected behavior for the thumbnail of the Brick Buster game is that it should render clearly and correctly, displaying the intended image without any distortion, pixelation, or loading issues. The thumbnail should be visually appealing, adhere to the specified dimensions, and be fully visible across different devices and platforms, effectively attracting user interest and engagement.

![Screenshot 2024-07-16 193337](https://github.com/user-attachments/assets/b30352fb-d7b8-41e4-91d0-e65527cf934e)

### Provide step by step information reproduce the bug 📄

Description
Steps to Reproduce the Bug
1. Open the Platform: Launch the platform where Brick Buster is listed.
2. Navigate to Game Listing: Go to the section displaying the game.
3. Observe Thumbnail: Check for rendering issues (e.g., distortion or blank spaces).
4. Test on Different Devices: View the thumbnail on various devices and browsers.
5. Inspect Element: Right-click on the thumbnail and select "Inspect" to check the HTML/CSS.
6. Clear Cache: Clear your browser cache and reload the page.
7. Re-upload Thumbnail: Try re-uploading the thumbnail image.

Plan to Find the Bug's Solution
1. Review Image Specifications: Confirm the image format, dimensions, and size.
2. Check Server Logs: Look for errors related to image loading.
3. Test Different Images: Upload an alternative thumbnail to see if the issue persists.
4. Consult Documentation: Review platform guidelines for thumbnail rendering.
5. Engage Community Support: Ask for forums or support for similar issues.
6. Update Software: Ensure all related software is up to date.
7. Document Findings: Record any discoveries to identify patterns

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @sweta-singh28 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by malvika-sinha** [comment]
I want to resolve the issue, Kindly assign me the task

**Comment by kunjgit** [comment]
Hey @sweta-singh28 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
