### ISSUE TITLE
[Bug]: The thumbnail for the Tiny fishing game and  Pig game isn't rendering correctly.

### ISSUE THREAD

**Issue by sweta-singh28** [kunjgit/GameZone#4869]
### Give a brief about the bug ✍️

Description
The thumbnail for the Tiny fishing game and pig game is not rendering correctly, which is causing issues with its visibility and appeal. This improper rendering affects the overall presentation of the game, potentially impacting user engagement and interest. It's important to address this issue promptly to ensure that the thumbnail displays properly and attracts players effectively.

### What is the expected behavior? 🤔

Description
The expected behavior for the thumbnail of the Tiny fishing game and pig game is that it should render clearly and correctly, displaying the intended image without any distortion, pixelation, or loading issues. The thumbnail should be visually appealing, adhere to the specified dimensions, and be fully visible across different devices and platforms, effectively attracting user interest and engagement.

![Screenshot 2024-07-16 194407](https://github.com/user-attachments/assets/a8959895-5d47-46ab-bc80-c727b38a2685)

![Screenshot 2024-07-16 194407](https://github.com/user-attachments/assets/7ce5a5f8-d4af-4516-8125-5d3460897cd1)

### Provide step by step information reproduce the bug 📄

Description
Steps to Reproduce the Bug
1. Open Browser: Launch any web browser.
2. Navigate to the Game Listing Page: Go to the URL where Tiny Fishing and Pig games are listed.
3. Inspect Elements: Right-click on the thumbnail area and select “Inspect.”
4. Check Image Tags: Verify the src attributes of the <img> tags for correct file paths.
5. Console Errors: Look for any image loading errors in the Console tab.
6. Verify Formats: Ensure thumbnails are in supported formats (PNG, JPEG).
7. Review CSS: Check for CSS styles that may hide or distort images.
8. Clear Cache: Clear the browser cache or test in incognito mode.
9. Test on Different Browsers: See if the issue occurs across various browsers or devices.
10. Document Findings: Record any errors or issues encountered for further analysis.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @sweta-singh28 , You can't have another issue before completing the previous one 😀 
 you already have the following 1 open issues 👀 ! :

#4868

**Comment by kunjgit** [comment]
Hey @sweta-singh28 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by kunjgit** [comment]
Hey @sweta-singh28 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)
