### ISSUE TITLE
[New game]: Bulls and Cows game

### ISSUE THREAD

**Issue by aRUsh-codes** [kunjgit/GameZone#4870]
## Game logic and basic description
I want to add the famous Bulls and Cows game made in js.
The computer will have a unique 4-digit number while the player tries to guess it.

The number to be guessed must be a 4 digit number, using only digits from 1 - 9, each digit atmost once. e.g. 1874 is valid, 0172 is not valid, 9877 is not valid, 9536 is valid.
For every guess that the player makes, he gets 2 values - the number of bulls and the number of cows.
1 bull means the guess contains and the target number have 1 digit in common, and in the correct position.
1 cow means the guess and the target have 1 digit in common, but not in correct position.
Eg. Let the target be 1234. Guessing 4321 will give 0 bulls and 4 cows. 3241 will give 1 bull and 3 cows. 4 bulls means you have won the game!

## Game points

The player gets total 7 chances to correctly guess the entire number and is awarded points in accordance to the number of guesses it took to win

- 1 guess - 70 points
- 2 guess - 60 points
- 3 guess - 50 points
- 4 guess - 40 points
- 5 guess - 30 points
- 6 guess - 20 points
- 7 guess - 10 points
- if the player cannot guess then 0 points

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @aRUsh-codes ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @aRUsh-codes ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
