### ISSUE TITLE
[Enhancement]: Piano Game Theme

### ISSUE THREAD

**Issue by anisharma07** [kunjgit/GameZone#4879]
### Do you want to have the enhancement of existing game ? 😀 Describe yourself..

I want to add Some themes to the piano game
![image](https://github.com/user-attachments/assets/509adb82-f9ae-4fee-a13c-690a9a37014b)

### Describe the solution you'd like

Solution steps:
Theres a change theme buttom in the game .... but it is of no use ..
I will add some background image and theme colors to the game

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @anisharma07 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
