### ISSUE TITLE
[Bug]: Add games Cosmic_Blast and IKnowYou to gamedata.json file

### ISSUE THREAD

**Issue by vansh-codes** [kunjgit/GameZone#4881]
### Give a brief about the bug ✍️

Earlier I have created two games named "Cosmic Blast" and "IknowYou - Min Reading Game"
You can refer to this PR: #4525 and #4581 

These games are not added in the gamesData.json file
I want to add this games to the gamesData.json file to make it available on the website.

Assign me under GSSoC'24.
Thank you!

### What is the expected behavior? 🤔

To get the games available on the website

### Provide step by step information reproduce the bug 📄

To get the games available on the website by adding their data in the gamesData.json file

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @vansh-codes , You can't have another issue before completing the previous one 😀 
 you already have the following 1 open issues 👀 ! :

#4664

**Comment by kunjgit** [comment]
Hey @vansh-codes ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
