### ISSUE TITLE
[New game]:  Hnagman Game

### ISSUE THREAD

**Issue by aRUsh-codes** [kunjgit/GameZone#4886]
## Game logic and basic description
A man is hanging from a noose and the player has to save him by guessing the word from the clue given. If the player is able to guess the word within a limit of 6 clues then the hangman is saved otherwise he is hanged and the player loses.

## Game points
- If the player is not able to guess the word within 6 tries he gets 0 points
- If the player guesses the word in anywhere between 1-3 tries he gets 100 points
- If the player guesses the word in anywhere between 3-6 tries he gets 50 points

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @aRUsh-codes ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @aRUsh-codes! 
We are already having a similar game request in #4877 👀 
Make sure you come up with a cool unique idea 😀 
 Waiting for your new game idea 💗.

**Comment by kunjgit** [comment]
Hey @aRUsh-codes ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
