### ISSUE TITLE
[New game]: Guess that Pokemon

### ISSUE THREAD

**Issue by aRUsh-codes** [kunjgit/GameZone#4888]
## Game logic and basic description
A black outline of the pokemon will be displayed on the screen and the player has to guess which pokemon it is.
There will be options for guess, quit and hint.

## Game points
- If the player guesses the pokemon without using a hint they are rewarded 100 points.
- If the player guesses the pokemon after taking a hint they are rewarded 50 points.
- If the player incorrectly guesses the pokemon they get 0 points.
- If the player quits they get 0 points.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @aRUsh-codes ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @aRUsh-codes ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
