### ISSUE TITLE
[New game]: DNA Sequencer

### ISSUE THREAD

**Issue by kosuri-indu** [kunjgit/GameZone#4891]
### 🎮 Game Request

The DNA Sequencer Game challenges players to correctly arrange a randomized DNA sequence. Players can shuffle the sequence and use drag-and-drop functionality to reorder DNA bases (A, T, C, G) until they match the target sequence. The game includes a timer to add an element of urgency, requiring players to complete the task within the allotted time

### Point down the features

Game points
Objective: Arrange the DNA sequence correctly within the time limit.
Shuffle: Randomize the sequence for added difficulty.
Drag-and-Drop: Intuitively rearrange DNA bases using drag operations.
Timer: Countdown from 120 seconds to complete the game.
Feedback: Immediate indication of sequence accuracy

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @kosuri-indu ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
