### ISSUE TITLE
[New game]:  Speaking the Number and Guessing 

### ISSUE THREAD

**Issue by ankit071105** [kunjgit/GameZone#4897]
### 🎮 Game Request

# Number Guessing by Speaking the Number
Number Guessing by Speaking the Number is an interactive game where players guess a randomly generated number within a specified range using voice commands. The game leverages speech recognition to convert spoken guesses into text, providing a hands-free and engaging experience. Upon starting, the game generates a random number and prompts the player to begin guessing by speaking their number.

# Screenshot
![Screenshot 2024-07-19 at 10 35 23 AM](https://github.com/user-attachments/assets/aad534e0-1aaa-4b52-a355-1fda7656638e)

![Screenshot 2024-07-19 at 10 35 05 AM](https://github.com/user-attachments/assets/693ddf57-6e75-41d8-b43e-5d3aa00d3482)

### Point down the features

# Features
Players receive real-time feedback, indicating whether their guess is too high, too low, or correct. This feedback helps them narrow down their guesses efficiently. The game also offers voice feedback to guide and encourage players throughout their guessing journey.

Upon correctly guessing the number, players can choose to play again or adjust the difficulty level for a new challenge. This game blends the simplicity of a classic guessing game with modern technology, providing a fun and immersive experience for users of all ages.
Key features include multiple difficulty levels with different number ranges, score tracking to display the number of guesses taken, and multilingual support for both speech recognition and voice feedback. The user-friendly interface ensures easy navigation, and the game is enhanced with background music and sound effects to make the experience more enjoyable.

### Select program in which you are contributing

IWOC2024, GSSoC24, hacktoberfest, Other

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @ankit071105 , You can't have another issue before completing the previous one 😀 
 you already have the following 1 open issues 👀 ! :

#4845

**Comment by kunjgit** [comment]
Hey @ankit071105 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by kunjgit** [comment]
Hey @ankit071105 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)
