### ISSUE TITLE
[New game]: Candy Crush

### ISSUE THREAD

**Issue by singh-anushka** [kunjgit/GameZone#49]
### 🎮 Game Request

Game logic and basic description
Basic Candy Crush Game using HTML, CSS and JavaScript.
The goal is to match at least three candies of the same colour and type in a row or column to clear them from the board. With each successful match, players earn points.

### Point down the features

Game points
Points are earned when at least 3 candies in same row or column are matched. The more candies you match in a single move, the higher the score.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @singh-anushka ! It is really interesting but we want to hear more…..
Can you elaborate the features 🤔!
We are looking forward have your valuable contribution in GameZone 🎮

**Comment by singh-anushka** [comment]
@kunjgit I updated the issue, now please add the GSSOC23 label. And can I start working on the same?
