### ISSUE TITLE
[New game]: Quiz game with timer

### ISSUE THREAD

**Issue by heli0707** [kunjgit/GameZone#4906]
### 🎮 Game Request

A quiz game with a timer challenges players to answer questions within a limited time frame, adding an element of urgency and excitement. Players must quickly recall and select the correct answers before the timer runs out.

### Point down the features

1. **Timed Questions**: Each question has a countdown timer, adding urgency.
2. **Score Tracking**: Keeps track of the player's score based on correct answers and time taken.
3. **Responsive Design**: Compatible with various devices, ensuring a smooth experience on both desktop and mobile.
4. **Review Answers**: Allows players to review their answers after completing the quiz.
5. **Customizable Timer**: Players can set the timer duration according to their preference.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @heli0707 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by kunjgit** [comment]
Hey @heli0707 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)
