### ISSUE TITLE
[New game]: Adding a new game Rocket_Ride

### ISSUE THREAD

**Issue by ayush-848** [kunjgit/GameZone#4908]
### 🎮 Game Request

This rocket game features a player-controlled spacecraft navigating through space, avoiding obstacles and collecting power-ups. The player uses arrow keys to move the rocket up and down, aiming to survive as long as possible while managing a fuel supply. The game increases in difficulty over time, with faster-moving obstacles and a gradually depleting fuel gauge, challenging players to achieve the highest score possible.

### Point down the features

1. Smooth, responsive rocket movement using arrow keys
2. Randomly generated obstacles with varying behaviors (static and moving)
3. Two types of power-ups: fuel replenishment and score boosts
4. Fuel management system that adds strategic depth
5. Progressive difficulty increase based on score
6. Parallax star background for a sense of motion
7. High score tracking using local storage
8. Start screen with instructions and game over screen with restart option
9. Frame-independent game logic for consistent gameplay across devices
10. Score and fuel display during gameplay

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @ayush-848 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @ayush-848 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
