### ISSUE TITLE
[Enhancement]: `World Chain Game` mismatch logic

### ISSUE THREAD

**Issue by sivaprasath2004** [kunjgit/GameZone#4917]
### Do you want to have the enhancement of existing game ? 😀 Describe yourself..

- In this `World chain Game` cannot proper work,because mismatch game Logic.
- `Score` cannot showing and `UI` also poor
- please assign me.

### Describe the solution you'd like

![Screenshot from 2024-07-21 16-46-32](https://github.com/user-attachments/assets/e36ba512-cf3c-4533-b4f6-18c7e85745a2)

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @sivaprasath2004 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @sivaprasath2004 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
