### ISSUE TITLE
[Bug]: Games are not being rendered

### ISSUE THREAD

**Issue by abhay-sen** [kunjgit/GameZone#4919]
### Give a brief about the bug ✍️

Due to some issue in the home page of the website games are not being rendered and i would like to find and fix that issue
![Screenshot 2024-07-21 214935](https://github.com/user-attachments/assets/5299ed21-7922-435c-9a3e-b47a47cd7887)

### What is the expected behavior? 🤔

there should have been a carousel of games

### Provide step by step information reproduce the bug 📄

open the main website link

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @abhay-sen ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by abhay-sen** [comment]
@kunjgit could you please assign the label for level so ican start working on it

**Comment by kunjgit** [comment]
Hey @abhay-sen ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
