### ISSUE TITLE
[Gssoc'23] Add a reserved copyright footer

### ISSUE THREAD

**Issue by kanishkasah20** [kunjgit/GameZone#492]
![WhatsApp Image 2023-05-27 at 18 55 46](https://github.com/kunjgit/GameZone/assets/114860158/8fa97c5a-cc1c-4ea0-9bb1-1379c29cd921)

please assign this issue to me , thank you for your Consideration!

**Comment by kunjgit** [comment]
Hey @kanishkasah20 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @kanishkasah20! 🙂 
 It seems like you are not following proper guidelines !! 👀 
 Read documentation properly !!🙏 
 If you have any queries reach out to us on [Discord🕹️](https://discord.gg/fgwk4XZfxG) .

**Comment by kunjgit** [comment]
Hey @kanishkasah20 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
