### ISSUE TITLE
Multiply Game

### ISSUE THREAD

**Issue by AshishPandey04** [kunjgit/GameZone#4921]
### 🎮 Game Request

Game logic and basic description

- HTML, CSS, and Javascript are used in the creation of this project.

- One player can play this by just looking at the multiplication question asked and clicking on the correct answer of it out of the options.

- The player's score will be kept track of until the player loses.

- If the player give wrong answer or 1 min of game time is over the game is over .

### Point down the features

Game points

- When a player loses a game, the score will be shown 👍

- The player's greatest score will be stated.
- Giving option to restart the game .
- - Putting graphic user interface (GUI) into practice to create a more interactive experience.
- Working on its Features will add more .
![Screenshot 2024-07-21 225436](https://github.com/user-attachments/assets/15b1d8b4-e867-4782-a78b-7ce52d9f8f43)

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @AshishPandey04 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @AshishPandey04! 🙂 
 It seems like you are not following proper guidelines !! 👀 
 Read documentation properly !!🙏 
 If you have any queries reach out to us on [Discord🕹️](https://discord.gg/fgwk4XZfxG) .

**Comment by kunjgit** [comment]
Hey @AshishPandey04 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
