### ISSUE TITLE
[Enhancement]: Contributors guideline needs some update 

### ISSUE THREAD

**Issue by mohitgedar** [kunjgit/GameZone#4925]
### Do you want to have the enhancement of existing game ? 😀 Describe yourself..

- At present new games gets added to the project but not to website .
- some contributors don't add things to dedicated folders , and many don't follow naming conventions 

### Describe the solution you'd like

- I would like to update contributors guideline so that new game contributors add their games to website and also add more precise details so that contributors add things properly and follow proper naming conventions

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @mohitgedar ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @mohitgedar ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
