### ISSUE TITLE
[New game]: Unword It ( reverse dumb-shard multiplayer game )

### ISSUE THREAD

**Issue by Shantnu-singh** [kunjgit/GameZone#4929]
### 🎮 Game Request

is a digital twist on the classic game of charades. Players describe words in reverse order, challenging the opposing team to guess the original word.

## Gameplay:

- Teams take turns describing and guessing words
- Describing team sees the word in reverse
- Guessing team attempts to identify the word
- Points awarded for correct guesses or when time runs out
- Game continues for a set number of rounds or until a target score is reached

### Point down the features

- Reversed word display
- 30-second timer per round
- Two-team scoring system
- Reveal Letter" option (costs 1 point)
- Guess input and submission
- Alternating turns between teams
- Random word selection from a predefined list
- Simple, colorful user interface

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Shantnu-singh , You can't have another issue before completing the previous one 😀 
 you already have the following 1 open issues 👀 ! :

#4770

**Comment by kunjgit** [comment]
Hey @Shantnu-singh ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by kunjgit** [comment]
Hey @Shantnu-singh ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)
