### ISSUE TITLE
[New game]: Subway Surfers

### ISSUE THREAD

**Issue by arunimaChintu** [kunjgit/GameZone#4936]
### 🎮 Game Request

Subway Surfers is an endless runner game where the player takes on the role of a graffiti artist who is caught in the act of tagging a metro railway site and must run down railroad tracks to escape the Inspector and his dog. As the player runs, they must dodge oncoming trains and obstacles by swiping left or right to change lanes, swiping up to jump, and swiping down to roll. The game increases in speed and difficulty as the player progresses, requiring quick reflexes and strategic decision-making to survive longer.

### Point down the features

Endless Running: The game features a continuous, never-ending chase where the player aims to achieve the highest possible score by running as far as they can without being caught.
Power-Ups and Boosters: Players can collect various power-ups like jetpacks, super sneakers, coin magnets, and score multipliers to aid their run and increase their score.
Daily Challenges and Missions: The game includes daily challenges and missions that offer additional rewards and objectives to keep the gameplay engaging.
Character and Board Upgrades: Players can unlock and upgrade different characters and hoverboards, each offering unique abilities and boosts.
Vibrant Graphics and Locations: The game features colorful and vibrant graphics, with regular updates introducing new locations and seasonal themes.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @arunimaChintu ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @arunimaChintu ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
