### ISSUE TITLE
[New game]:  Fighting game

### ISSUE THREAD

**Issue by anandpiyush1521** [kunjgit/GameZone#494]
### 🎮 Game Request

Game logic and basic description
The game is a single player game in which the player have to change the color of bars according to the color of ball above the bars.
The game is made by using HTML ,CSS , JAVASCRIPT.

### Point down the features

Game points

Single player game.
Improve reflexing power.
simple keyboard command 

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @anandpiyush1521 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @anandpiyush1521! 
We are already having a similar game request in #490 👀 
Make sure you come up with a cool unique idea 😀 
 Waiting for your new game idea 💗.

**Comment by kunjgit** [comment]
Hey @anandpiyush1521 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
