### ISSUE TITLE
[New game]: Endless Runner

### ISSUE THREAD

**Issue by priyashuu** [kunjgit/GameZone#4941]
### 🎮 Game Request

Game logic and basic description
An Endless Runner game where you control a character running through an ever-changing environment. The goal is to survive as long as possible by avoiding obstacles, collecting power-ups, and achieving high scores.

### Point down the features

Game points
## Dynamic Environment:

Unique, procedurally generated levels each run.
Multiple themes (e.g., jungle, city, space).
## Character Control:

Smooth controls for jumping, sliding, and dodging.
Unlockable characters with unique abilities.
## Obstacles and Challenges:

Varied obstacles like gaps, spikes, and moving barriers.
Increasing difficulty over time.
## Power-ups and Collectibles:

 Power-ups like speed boosts and invincibility.
Collectibles to unlock new characters and upgrades.
## Scoring and Achievements:

 Score based on distance and collectibles.
Leaderboards and achievements for added challenge.
## Visual and Audio Design:

High-quality graphics and animations.
Engaging sound effects and dynamic background music.
## User Interface:

Intuitive controls and HUD displaying score and distance.
Start, pause, and game over screens.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @priyashuu , You can't have another issue before completing the previous one 😀 
 you already have the following 1 open issues 👀 ! :

#4754

**Comment by kunjgit** [comment]
Hey @priyashuu ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by kunjgit** [comment]
Hey @priyashuu ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)
