### ISSUE TITLE
[New game]: HexaBattle

### ISSUE THREAD

**Issue by PallaviGudupallavi** [kunjgit/GameZone#4944]
### 🎮 Game Request

Game logic and basic description:

Hexa Battle is a strategic game where players assemble a party of heroes to delve into a dungeon. The goal is to progress as far as possible by defeating enemies on each level. Surviving units are carried to the next level, earning gold to recruit more units.

### Point down the features

1. **Hero Selection:** Players can choose and assemble a team of heroes to enter the dungeon.
2. **Level Carryover:** Surviving heroes move on to the next level after clearing one.
3. **Currency Earning:** Players earn money after each level to buy more heroes.
4. **Increasing Challenge:** The dungeon gets harder the deeper players go, requiring strategy.
5. **Easy Controls:** Keyboard shortcuts make selecting and controlling units simple.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @PallaviGudupallavi , You can't have another issue before completing the previous one 😀 
 you already have the following 1 open issues 👀 ! :

#4060

**Comment by kunjgit** [comment]
Hey @PallaviGudupallavi ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by kunjgit** [comment]
Hey @PallaviGudupallavi ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by PallaviGudupallavi** [comment]
> Hey @PallaviGudupallavi , You can't have another issue before completing the previous one 😀 you already have the following 1 open issues 👀 ! :
> 
> #4060

I have raised the PR for that issue.Hope you review it once!
Thank you!
