### ISSUE TITLE
[New game]:  Want to add the wordel game 

### ISSUE THREAD

**Issue by Ayushmaanagarwal1211** [kunjgit/GameZone#4954]
### 🎮 Game Request

Game logic and basic description
I want to add the wordel game 
This game is about every word has its meaning and whenever user enters a word that has meaning it will make it coloured 

https://github.com/user-attachments/assets/21242d5e-bd91-4e08-a1d3-ce4be6524cf6

### Point down the features

Game points
- Its a word game 
- User have to make words with 5 rows 

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Ayushmaanagarwal1211 , You can't have another issue before completing the previous one 😀 
 you already have the following 1 open issues 👀 ! :

#4796

**Comment by kunjgit** [comment]
Hey @Ayushmaanagarwal1211 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by kunjgit** [comment]
Hey @Ayushmaanagarwal1211 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)
