### ISSUE TITLE
[New game]: Guess the movie's name with emojis as hints

### ISSUE THREAD

**Issue by vishalkumarmahto** [kunjgit/GameZone#496]
### 🎮 Game Request

By taking hints from the emoji given, we have to tell the movie's name. The user will left with 5 attempts to guess the movie's name correctly.

### Point down the features

The user will have different letters by which he can guess the movie's name.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @vishalkumarmahto ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by vishalkumarmahto** [comment]
How can I add entries for my game in main README.md
