### ISSUE TITLE
[New game]: Add Memory Game 

### ISSUE THREAD

**Issue by jency1** [kunjgit/GameZone#4965]
### 🎮 Game Request

I would like to add a memory game to the website to engage users and provide an interactive element. 

This addition aims to attract and retain users by offering a fun, casual activity that complements our existing content. The memory game will involve a grid of cards that users can flip to reveal images, with the goal of matching all pairs of images within the grid.

The implementation should focus on providing a smooth user experience, maintaining consistent design aesthetics with our current website, and ensuring accessibility for all users. 

### Point down the features

Game points
1. Grid Layout
2. Timer
3. Restart Option
4. Winning Message
5. Styling
6. Accessibility

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @jency1! 
We are already having a similar game request in #4933 👀 
Make sure you come up with a cool unique idea 😀 
 Waiting for your new game idea 💗.

**Comment by kunjgit** [comment]
Hey @jency1 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
