### ISSUE TITLE
[New game]: Add new game - Guess the Word

### ISSUE THREAD

**Issue by jency1** [kunjgit/GameZone#4969]
### 🎮 Game Request

I would like to add a Guess the Word game to our website to engage users and provide an entertaining and educational experience. The Hangman game will allow users to guess a hidden word by suggesting letters, with incorrect guesses resulting in parts of a hangman figure being drawn.

### Point down the features

Game points
Word Bank
User Interface
Score Tracking
Restart Option
Accessibility
Styling

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @jency1 , You can't have another issue before completing the previous one 😀 
 you already have the following 1 open issues 👀 ! :

#4966

**Comment by kunjgit** [comment]
Hey @jency1 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by kunjgit** [comment]
Hey @jency1 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)
