### ISSUE TITLE
[New game]: Add Pokemon adventure game

### ISSUE THREAD

**Issue by Vaibhav-kesarwani** [kunjgit/GameZone#4972]
### 🎮 Game Request

Game logic and basic description
This will be a two-dimensional game with a moving player, a single Pokemon that can battle other Pokemon, and other characters that they can interact with.

### Point down the features

Game points
1. Player Movement
2. Pokemon System
3. Battle System
4. Character Interactions
5. Game World
6. Graphics and UI
7. Sound and Music

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Vaibhav-kesarwani ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by Vaibhav-kesarwani** [comment]
@ishita-43 Please review this PR

**Comment by ishita-43** [comment]
You need to resolve arising conflicts of gamesdata. Json file

**Comment by Vaibhav-kesarwani** [comment]
ok should i raise a new PR

**Comment by Vaibhav-kesarwani** [comment]
@ishita-43 Please review the PR

**Comment by Vaibhav-kesarwani** [comment]
@ishita-43 Please Review the PR

**Comment by ishita-43** [comment]
Done reviewing, it will soon be merged by the admin

**Comment by Vaibhav-kesarwani** [comment]
@ishita-43 how much time it take to merge the PR

**Comment by ishita-43** [comment]
> @ishita-43 how much time it take to merge the PR

Make sure merge conflicts are resolved after that it will get merged

**Comment by kunjgit** [comment]
Hey @Vaibhav-kesarwani ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
