### ISSUE TITLE
[Enhancement]: Comprehensive Website Enhancements: Fix Game Loading, Pagination, Layout Issues, JSON Errors, Cursor Size, and Remove Redundant File

### ISSUE THREAD

**Issue by mohitgedar** [kunjgit/GameZone#4974]
### Do you want to have the enhancement of existing game ? 😀 Describe yourself..

- Users are unable to load games, impacting their experience and engagement.
- The pagination feature is not functioning, which makes it difficult for users to navigate through multiple games.
- The like button is overlapping with the game titles, making it difficult to read and interact with the content.
- Contributors are improperly modifying the gamesData.json file, adding trailing commas and removing the last curly brace, leading to errors.
- The manual cursor is excessively large, covering content and making it difficult for users to view and interact with elements like the like button.
- An unused index_old.html file is increasing the website’s load time, affecting performance.

### Describe the solution you'd like

- Improve game loading functionality to ensure all games are accessible to users. This enhancement will increase user satisfaction by providing a seamless and reliable gaming experience.
- Make pagination system working again to facilitate smooth navigation between games. This will improve the user experience by making it easier to browse and discover content.
- Redesign the like button layout to prevent it from overlapping with the game titles. This will enhance the visual layout and ensure that all interactive elements are clearly accessible and aesthetically pleasing.
- Update the contributors' guidelines to include clear instructions on proper JSON formatting.
- Adjust the size of the manual cursor to improve visibility and usability. This adjustment will ensure that the cursor does not obstruct important content, enhancing the overall user experience.
- Remove the unused index_old.html file to reduce load times and improve website performance. This will optimize the website’s efficiency and enhance the user experience.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @mohitgedar ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @mohitgedar ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
