### ISSUE TITLE
[New game]: Dragon Ball Anime Quiz Game

### ISSUE THREAD

**Issue by samarsajad** [kunjgit/GameZone#4977]
### 🎮 Game Request

This game tests your knowledge of the iconic Dragon Ball series, from the classic adventures of Goku and his friends to the epic battles and memorable moments that have defined the franchise.

### Point down the features

The quiz includes multiple-choice questions ensuring a comprehensive test of your Dragon Ball knowledge. Questions range from easy to hard, catering to both casual fans and die-hard followers of the series

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by samarsajad** [comment]
Please assign this issue to me @kunjgit

**Comment by kunjgit** [comment]
Hey @samarsajad ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)
