### ISSUE TITLE
[Bug]: The switch button in the top-right header does not serve any purpose. The page automatically changes its color to various bright colors regardless of the switch's state. 

### ISSUE THREAD

**Issue by PRASANNA-THE-PRASANN1** [kunjgit/GameZone#4978]
### Give a brief about the bug ✍️

The page automatically changes its color to various bright colors regardless of the switch's state.  So,Removing the switch button from the header to avoid confusion and clean up the user interface would be better option.

### What is the expected behavior? 🤔

The switch button should either have a clear and functional purpose (e.g., toggling between light and dark modes) or be removed if it is not intended to serve any function.

### Provide step by step information reproduce the bug 📄

Steps to Reproduce:
1. Open any page in the GameZone project.
2. Observe the switch button in the top-right header.
3. Click the switch button – it does not affect the color-changing behavior of the page.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @PRASANNA-THE-PRASANN1 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @PRASANNA-THE-PRASANN1 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
