### ISSUE TITLE
[New game]:  Alien Language Translator

### ISSUE THREAD

**Issue by nikki-05** [kunjgit/GameZone#4980]
### 🎮 Game Request

Game logic and basic description
The Alien Language Translator game is an interactive game where players translate messages from an alien language into English and vice versa. The game introduces players to a set of alien symbols and their corresponding English letters or words. The game blends education 😁 and entertainment by challenging players with unique translation puzzles.

### Point down the features

-Translate from alien Language to English
-Translate from English to alien language 
-Customized alien language 

Here is a sample picture of the game
![Screenshot 2024-07-26 093341](https://github.com/user-attachments/assets/c0342be3-0054-4466-a675-c112f9b12485)

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @nikki-05 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @nikki-05 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
