### ISSUE TITLE
Memory Match: 

### ISSUE THREAD

**Issue by anglerfishlyy** [kunjgit/GameZone#4982]
### 🎮 Game Request

**Game Logic:**

**_Goal:_** Match all card pairs.
_Play:_ Flip two cards; matching pairs stay face-up, non-matches flip back.
_Win_: All pairs matched.

**Description:**
Add a "Memory Match" game with a card grid to find matching pairs.

### Point down the features

- Grid layout (e.g., 4x4 cards).
- Flip two cards to find matching pairs.
- Track and display number of moves.
- Show win message when all pairs are matched.
- "Restart" button to reset the game.
- Responsive design for desktop and mobile.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @anglerfishlyy ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @anglerfishlyy! 🙂 
 It seems like you are not following proper guidelines !! 👀 
 Read documentation properly !!🙏 
 If you have any queries reach out to us on [Discord🕹️](https://discord.gg/fgwk4XZfxG) .

**Comment by kunjgit** [comment]
Hey @anglerfishlyy ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by anglerfishlyy** [comment]
Could you assign me this?

**Comment by anglerfishlyy** [comment]
What's not right in it?
