### ISSUE TITLE
[New game]: Wordle Game

### ISSUE THREAD

**Issue by ishita80** [kunjgit/GameZone#499]
### 🎮 Game Request

Game logic and basic description
Wordle is a game in which the user has to guess a word (of 5 letters) in 5 chances. 

Looks kind of like this.
<img width="239" alt="wordle" src="https://github.com/kunjgit/GameZone/assets/121221158/c70ffb9a-0c5d-42ca-8d35-92273fb06edd">

### Point down the features

Game points
->5 letter word.
->6 chances for the player.
->Color coding for right and wrong letters.
->Appealing UI.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @ishita80 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @ishita80! 
We are already having a similar game request in #343 👀 
Make sure you come up with a cool unique idea 😀 
 Waiting for your new game idea 💗.

**Comment by kunjgit** [comment]
Hey @ishita80 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
