### ISSUE TITLE
[New game]: Add Two Player Fighting Game

### ISSUE THREAD

**Issue by Vaibhav-kesarwani** [kunjgit/GameZone#4991]
### 🎮 Game Request

Game logic and basic description
This 2D game will replicate the real-world fighting experience of a samurai.

### Point down the features

Game points
This game have the features are:
1. Health
2. Katana Figurthing
3. A Moment of Triumph
4. The Best User Experience

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Vaibhav-kesarwani , You can't have another issue before completing the previous one 😀 
 you already have the following 1 open issues 👀 ! :

#4972

**Comment by kunjgit** [comment]
Hey @Vaibhav-kesarwani ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by kunjgit** [comment]
Hey @Vaibhav-kesarwani ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)
