### ISSUE TITLE
[New game]: color catcher

### ISSUE THREAD

**Issue by aadyagupta44** [kunjgit/GameZone#4994]
### 🎮 Game Request

The player controls a basket that can move left and right at the bottom of the screen.
Colored balls fall from the top of the screen at random positions and speeds.
The player must catch balls of a specific color while avoiding balls of other colors.
The game increases in difficulty as the player progresses, with more balls falling faster.

### Point down the features

Different colored balls with varying fall speeds.
Score tracking based on the number of correct color balls caught.
Lives system: the player loses a life for catching the wrong color.
Increasing difficulty as the game progresses.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @aadyagupta44 , You can't have another issue before completing the previous one 😀 
 you already have the following 1 open issues 👀 ! :

#4508

**Comment by kunjgit** [comment]
Hey @aadyagupta44 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by kunjgit** [comment]
Hey @aadyagupta44 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)
