### ISSUE TITLE
[New game]: Call Of Duty

### ISSUE THREAD

**Issue by arunimaChintu** [kunjgit/GameZone#4996]
### 🎮 Game Request

Call of Duty is a first-person shooter (FPS) game series where players experience various military scenarios, either through single-player campaigns or multiplayer modes. The game's logic involves players navigating through maps, completing objectives, and engaging in combat with enemies using a variety of weapons and tactics. The gameplay often includes a mix of shooting, stealth, and strategic elements, requiring players to make quick decisions and use their environment to their advantage.

### Point down the features

 players compete in teams or solo across different game types such as Team Deathmatch, Capture the Flag, and Battle Royale. Players can customize their loadouts with different weapons, attachments, and perks to suit their playstyle.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @arunimaChintu ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @arunimaChintu ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
