### ISSUE TITLE
[New game]: Snake Game

### ISSUE THREAD

**Issue by lmalkam** [kunjgit/GameZone#5]
### 🎮 Game Request

It will be a simple game where the snake can move around in any direction in the square and eat the fruit and it will become longer and longer.
This game will use the tech stack HTML, CSS and JavaScript.

### Point down the features

Snake will be of variable length
Fruit will appear randomly one after another
Easy UI to play

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by Chirag-04** [comment]
@lmalkam Hope you're doing well! I'm eager to work on this task and would greatly appreciate it if you could assign it to me.

**Comment by kunjgit** [comment]
Hey @lmalkam  ! Thank you for raising an issue 💗 You have been assigned this issue you can start working on the issue 🎮

**Comment by kunjgit** [comment]
Hey @lmalkam ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
