### ISSUE TITLE
[New game]: Dice game

### ISSUE THREAD

**Issue by sumitkr2000** [kunjgit/GameZone#50]
### 🎮 Game Request

This is a game where tow parties can resolve their arguments using rolling dices and whoever has large number win the game.

### Point down the features

Two dice for two players.
Roll dice individually.
Those who have a large number win the game.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @sumitkr2000 !!
For now it is too simple to have on GameZone 🎮 
Make sure you add some more features !!
We would like to hear more from you !! 💗

**Comment by kunjgit** [comment]
Hey @sumitkr2000 ! we are already having a game with similar logic so once it will be on GameZone you can do enhancement 👀 
Or you can come up with unique game idea !

**Comment by kunjgit** [comment]
Hey @sumitkr2000 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by sumitkr2000** [comment]
What does it mean?
