### ISSUE TITLE
[New game]: Add Super Tetris game

### ISSUE THREAD

**Issue by pavitraag** [kunjgit/GameZone#5002]
### 🎮 Game Request

Super Tetris is a puzzle video game that involves manipulating falling tetrominoes (geometric shapes composed of four square blocks each) to create horizontal lines without gaps. When a line is completed, it disappears, and the player earns points. The game becomes progressively harder as the tetrominoes fall faster. The goal is to keep the playfield from filling up as long as possible.

### Point down the features

Just like classical Tetris Game. You use up key to rotate a shape, left key to move left and right key to move right. Also you can use space key to drop down current shape immediately. If you want a pause, just press P key. The right panel shows the next shape.

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @pavitraag ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by pavitraag** [comment]
can you assign me under gssoc

**Comment by kunjgit** [comment]
Hey @pavitraag ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by kunjgit** [comment]
Hey @pavitraag ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
