### ISSUE TITLE
[New game]: Minecraft

### ISSUE THREAD

**Issue by arunimaChintu** [kunjgit/GameZone#5009]
### 🎮 Game Request

Minecraft is a sandbox game that allows players to build and explore a blocky, procedurally generated 3D world. The core mechanics involve gathering resources, crafting tools and items, and constructing structures. Players can explore vast landscapes, mine for valuable ores, and battle various creatures. The game has two main modes: Survival and Creative. In Survival mode, players must manage their health and hunger while avoiding or defeating hostile mobs. In Creative mode, players have unlimited resources and can freely create and destroy blocks without any restrictions.

### Point down the features

Endless Exploration: Players can explore an infinite world filled with diverse biomes, structures, and hidden treasures.
Resource Gathering and Crafting: Collect resources from the environment to craft tools, weapons, and other items necessary for survival and creativity.
Building and Construction: Use blocks to construct buildings, landscapes, and complex structures limited only by the player's imagination.
Multiplayer: Play with friends or join online servers to collaborate or compete in various game modes.
Regular Updates: The game receives frequent updates that introduce new features, blocks, mobs, and gameplay mechanics.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @arunimaChintu ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @arunimaChintu ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
