### ISSUE TITLE
[New game]: Icy_tower game

### ISSUE THREAD

**Issue by pavitraag** [kunjgit/GameZone#5011]
### 🎮 Game Request

This is a platform game set in a tower, where the player's goal is to jump from one "floor" to the next and go as high as possible without falling. The higher the player's character climbs, the faster the tower's floors move downward and the harder the game becomes. By default, the player controls the character using a keyboard.

### Point down the features

-Role: Escaping from the tower

-Actions: Moving left, moving rigt, and jumping to climb the stairs.

-Role: Showing the current gianed score depending on the number of revealed stairs.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @pavitraag , You can't have another issue before completing the previous one 😀 
 you already have the following 1 open issues 👀 ! :

#5002

**Comment by kunjgit** [comment]
Hey @pavitraag ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by kunjgit** [comment]
Hey @pavitraag ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)
