### ISSUE TITLE
[New game]: Animal Name Guessing

### ISSUE THREAD

**Issue by shellygarg10** [kunjgit/GameZone#5015]
### 🎮 Game Request

Game logic and basic description

- User have to guess to animal name by asking a question
- Right answer 5m and for wrong answer loos 1 chance to play!

### Point down the features

Game points

Each correct answer is 5 points  
You have 3 chances to guess the correct animal
If you fail to guess the correct animal after your three chances are up, you lose 1 point

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @shellygarg10 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by shellygarg10** [comment]
@kunjgit please assign this to me.

**Comment by shellygarg10** [comment]
@kunjgit please assign it to me

**Comment by kunjgit** [comment]
Hey @shellygarg10 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
