### ISSUE TITLE
[New game]: Underwater Shoot

### ISSUE THREAD

**Issue by kosuri-indu** [kunjgit/GameZone#5018]
### 🎮 Game Request

Game logic and basic description
Underwater Shoot is a fun and interactive game where players click on creatures to score points. The goal is to score as many points as possible within 60 seconds.

### Point down the features

Game points
- Click on the creatures to shoot them.
- Large Creatures: 5 points
- Medium Creatures: 10 points
- Small Creatures: 15 points
- Score as many points as possible within 60 seconds!

![Screenshot 2024-07-28 171446](https://github.com/user-attachments/assets/3bcf7d95-338f-4108-a8a3-c63913a73c04)

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @kosuri-indu ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @kosuri-indu ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
