### ISSUE TITLE
[Documentation Bug]: Typo in README 

### ISSUE THREAD

**Issue by MisterMickey** [kunjgit/GameZone#502]
### Describe the bug ✍️

There are typos in GameZone/Games/Simon_Game_Challenge which needs to be fixed.
Kindly assign me this issue under GSSOC'23 so that I can fix them.

### Provide step by step information reproduce the bug 📄

I'll thoroughly check the whole README and fix all the typos.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @MisterMickey ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by MisterMickey** [comment]
/assign

Sure, I'll follow the CODE OF CONDUCT and CONTRIBUTING GUIDELINES.

**Comment by kunjgit** [comment]
Hey @MisterMickey ! , This issue is already assigned to @MisterMickey. 💗 
 You can work on other issues 🚀 
 If there is anything wrong you can contact us on [Discord🕹️](https://discord.gg/fgwk4XZfxG)👀

**Comment by Harshvardhan-Dubey-Github** [comment]
v

**Comment by soorjya** [comment]
I'm a contributor for GSSoC '23, I want to contribute to this issue. Please assign me.

**Comment by kunjgit** [comment]
Hey @MisterMickey ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
