### ISSUE TITLE
[New game]: Bejeweled

### ISSUE THREAD

**Issue by shellygarg10** [kunjgit/GameZone#5022]
### 🎮 Game Request

Game logic and basic description

Bejeweled is a puzzle game where the player's objective is to swap adjacent gems in a grid to create matches of three or more identical gems. When a match is made, those gems are removed from the grid, and new gems fall from the top to fill the empty spaces.

### Point down the features

Game points

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @shellygarg10 , You can't have another issue before completing the previous one 😀 
 you already have the following 1 open issues 👀 ! :

#5015

**Comment by kunjgit** [comment]
Hey @shellygarg10 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
