### ISSUE TITLE
[README.md Bug]: The Games section looks so messy and unorganized.

### ISSUE THREAD

**Issue by PRASANNA-THE-PRASANN1** [kunjgit/GameZone#5028]
### Describe the bug ✍️

The Games section looks so messy and unorganized hence giving bad impression of project. 

### Provide step by step information reproduce the bug 📄

Assign this issue to me, @kunjgit I will organize and align the games section and enhance the README.md page.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @PRASANNA-THE-PRASANN1 , You can't have another issue before completing the previous one 😀 
 you already have the following 1 open issues 👀 ! :

#4978

**Comment by kunjgit** [comment]
Hey @PRASANNA-THE-PRASANN1 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by kunjgit** [comment]
Hey @PRASANNA-THE-PRASANN1 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)
