### ISSUE TITLE
[New game]: Picross

### ISSUE THREAD

**Issue by Aditijainnn** [kunjgit/GameZone#5029]
### 🎮 Game Request

This is a playable [picross puzzle](http://en.wikipedia.org/wiki/Nonogram) generator written in JavaScript

### Point down the features

Game points
Adjustable grid dimensions (the code is generic and supports any dimension, but a 30x30 game can take up to 2 hours)
* Custom game seeds (allows multiple computers to play using the same starting puzzle configuration)
* Option to toggle crossouts, helping you track numbers that have already been solved
* Auto-saves using HTML5 web storage
* Progress indicator
* Mistakes counter

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Aditijainnn , You can't have another issue before completing the previous one 😀 
 you already have the following 1 open issues 👀 ! :

#4436

**Comment by kunjgit** [comment]
Hey @Aditijainnn ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by kunjgit** [comment]
Hey @Aditijainnn ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by Aditijainnn** [comment]
> Hey @Aditijainnn ! Thank you for raising an issue 💗 You can self assign the issue by commenting /assign in comment 😀 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone) Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

/assign
