### ISSUE TITLE
[New game]: Beat Blaster game

### ISSUE THREAD

**Issue by sagnik3788** [kunjgit/GameZone#503]
### 🎮 Game Request

Game logic and basic description

The game logic for a drum kit game is relatively simple. The player must press the correct keys on the keyboard to play the correct notes. The notes are usually displayed on the screen, and the player must press the keys in time with the music. The game can be made more challenging by adding different types of notes, such as sharps and flats.

The basic description of a drum kit game is that the player is given a drum kit and must play the correct notes in time with the music. The player can earn points for playing the notes correctly, and the game can be made more challenging by adding different types of notes.

Here are some additional features that could be added to a drum kit game:

Different difficulty levels
Different genres of music
A scoring system
A leaderboard
A practice mode
A multiplayer mode
These features would make the game more challenging, engaging, and rewarding. They would also allow players to customize the game to their own preferences.

Here are some tips for creating a drum kit game:

Start with a simple game and add complexity as you go.
Use a variety of sounds to create a rich and immersive experience.
Make the game challenging but not impossible.
Reward players for their accomplishments.
Promote the game on social media and gaming websites.
With a little effort, you can create a drum kit game that is fun and engaging for players of all ages.

### Point down the features

Game points

There are many different drum games, and the points system for each game can vary. However, there are some general principles that apply to most drum games.

Correctly hitting a drum sound will usually earn the player a fixed number of points. For example, the player might earn 10 points for each correct drum sound played.
The number of points earned can also be affected by the timing of the hit. Players will usually earn more points for hitting a drum sound on time than for hitting it early or late.
In some games, players can also earn bonus points for hitting multiple drum sounds in a row or for hitting a particularly difficult drum sound.
The total score of a player is calculated by adding up the points earned for each hit. The player with the highest score at the end of the game wins.
Here are some examples of different drum games and their point systems:

Guitar Hero and Rock Band are two popular rhythm games that use real or simulated guitars to play along with popular songs. In these games, players earn points for hitting notes on the guitar in time with the music. The number of points earned can also be affected by the difficulty of the note.
Taiko no Tatsujin is a Japanese rhythm game that uses a large drum to play along with music. In this game, players earn points for hitting the drum with the correct timing and force. The number of points earned can also be affected by the size of the drum hit.
DJ Hero is a rhythm game that uses a turntable to mix and scratch music. In this game, players earn points for mixing and scratching the music in time with the beat. The number of points earned can also be affected by the difficulty of the mix or scratch.
These are just a few examples of different drum games and their point systems. There are many other drum games available, each with its own unique point system.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @sagnik3788 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by Harshvardhan-Dubey-Github** [comment]
please assign me this issue

**Comment by kunjgit** [comment]
Hello @sagnik3788, Time's Uppp!⏰ 
 Sorry for closing your issue! 
 But it's more than a week since we haven't received anything from your side 😢 . 
 Come up with new ideas, create a new issue and make sure you finish it within a week! 🔥 
 All the best! 🚀 
 Happy Hacking! 💗

**Comment by kunjgit** [comment]
Hey @sagnik3788 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
