### ISSUE TITLE
[New game]:  Tower defenser

### ISSUE THREAD

**Issue by Aditijainnn** [kunjgit/GameZone#5030]
### 🎮 Game Request

A simple game whose goal is to defend the castle from the incoming waves of enemies. The player can defend the castle by placing towers that deal damage to enemies and building walls that temporarily distract the enemy from the target (castle). Unfortunately, enemies can destroy any object.

### Point down the features

Game points
 There are two types of towers in the game. They differ primarily in attack range and durability and therefore in price. During the game, you can increase the tower's attack range or sell it. Its price will of course depend on its condition - a tower that has been attacked by an enemy will no longer have its maximum value.

The player can also build a wall. The wall does not attack the enemy, but temporarily stops them. The enemy stands against the wall that stands in his way and destroys it until he can go through it. This gives you extra time to think about your game strategy.

You can see different types of enemies. They differ in the maximum health and strength. If the tower kills an enemy, you will receive money - the amount depends on the type of enemy. Enemies are a bit lazy - they always look for the nearest object and choose the shortest path to it.

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Aditijainnn , You can't have another issue before completing the previous one 😀 
 you already have the following 1 open issues 👀 ! :

#4436

**Comment by kunjgit** [comment]
Hey @Aditijainnn ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by kunjgit** [comment]
Hey @Aditijainnn ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)
