### ISSUE TITLE
[New game]: Jigsaw Sudoku

### ISSUE THREAD

**Issue by its-kritika** [kunjgit/GameZone#5037]
### 🎮 Game Request

**Game logic and basic description**
Jigsaw Sudoku is an engaging variant of the classic Sudoku puzzle where you fill a 9x9 grid with numbers 1 through 9. Instead of standard 3x3 sub grids, the grid is divided into irregular regions, adding a unique and challenging twist to the traditional number placement game.

### Point down the features

- Irregular Regions: Instead of the standard 3x3 subgrids, the grid is divided into irregularly shaped regions that still contain exactly nine cells each.
- Standard Sudoku Rules: Each row, column, and irregular region must contain all of the digits from 1 to 9 without repetition.
- Variety of Shapes: The irregular regions can have a variety of shapes, providing a different challenge compared to the regular subgrids in standard Sudoku.
- Logical Deduction: The game requires logical thinking and deduction to determine the correct placement of numbers.
- Visual Appeal: The irregular regions often make the puzzle visually more interesting and can add a layer of complexity to the solving process.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @its-kritika , You can't have another issue before completing the previous one 😀 
 you already have the following 1 open issues 👀 ! :

#4246

**Comment by kunjgit** [comment]
Hey @its-kritika ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by kunjgit** [comment]
Hey @its-kritika ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)
