### ISSUE TITLE
Enhance  styling of the balloon popup game.

### ISSUE THREAD

**Issue by Siwanikaushik** [kunjgit/GameZone#5044]
### Do you want to have the enhancement of existing game ? 😀 Describe yourself..

Hi @kunjgit ,
I want to enhance the styling of balloon popup game as it looks a little dull & also the location & designing of balloons are not proper. 
So , in order to make this game more interesting I wants to add some more styling to this game using my skills & knowledge.
![Screenshot (243)](https://github.com/user-attachments/assets/9161fd6e-92dd-4218-aea6-96352948d9e9)
I request you to assign me this issue.
I shall be very thankful to you
Siwani(GSSoC'24 Contributor)

### Describe the solution you'd like

The steps that I will follow are:
I will fork the repository & then make changes in the game using HTML & CSS.
Please assign me this issue.
 

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Siwanikaushik! 🙂 
 It seems like you are not following proper guidelines !! 👀 
 Read documentation properly !!🙏 
 If you have any queries reach out to us on [Discord🕹️](https://discord.gg/fgwk4XZfxG) .

**Comment by kunjgit** [comment]
Hey @Siwanikaushik ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @Siwanikaushik ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
