### ISSUE TITLE
[Enhancement]: Enhancing UI of Balloon Popup Game and adding features.

### ISSUE THREAD

**Issue by Changingthegame** [kunjgit/GameZone#5048]
### Do you want to have the enhancement of existing game ? 😀 Describe yourself..

I viewed this game and found that the UI of the game is not that much nice and also the designs of the balloon and the background of the game are not that much attractive , so this should be improved so that the user interface looks dashing and attractive.

### Describe the solution you'd like

Firstly, I would make the background attractive and add some new designs with some new features if possible and finally making the UI of the game nice and attractive. I want to use some nice fonts and colors in this game.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Changingthegame ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @Changingthegame ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
