### ISSUE TITLE
[Bug]: Fixing gamesData.json

### ISSUE THREAD

**Issue by abhay-sen** [kunjgit/GameZone#5049]
### Give a brief about the bug ✍️

The games data.json file has a lot of error that isnt letting the game to be rendered locally and i would like to fix that as it would take a lot of time im raising an issue for this to get assigned to a level
![image](https://github.com/user-attachments/assets/eb22e7c8-9997-47c8-904b-415c9b73d705)
![image](https://github.com/user-attachments/assets/a4122796-a17c-4f9d-8bb8-4ffcaaf8bca5)

### What is the expected behavior? 🤔

the games should render as it is rendering in the website locally too but there is supposed to be a bug in gamesData.json

### Provide step by step information reproduce the bug 📄

clone the repo
open assets folder
open the gamesData.json
and run the index.html with live server

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by abhay-sen** [comment]
@kunjgit @ishita-43 respected mentors could you also assign a level to this

**Comment by abhay-sen** [comment]
@kunjgit @ishita-43 mentors please assign this a issue as finding and removing duplicate data and redundancy in the json file is a very tedious work and it wouldnt be worth it if i wont gain any points from that

**Comment by ishita-43** [comment]
You do gain points for gssoc level also and there will be assigned levels on pr which will be counted in the leaderboard also the level on issue are currently being generated automatically
Any way level is assigned you  can work on the issue

**Comment by abhay-sen** [comment]
> You do gain points for gssoc level also and there will be assigned levels on pr which will be counted in the leaderboard also the level on issue are currently being generated automatically Any way level is assigned you can work on the issue

sorry for the trouble maam

**Comment by ishita-43** [comment]
It's ok, it's better to have label on issue as well as bug

**Comment by kunjgit** [comment]
Hey @abhay-sen ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
