### ISSUE TITLE
[New game]: The Enigma of Blackwood Manor

### ISSUE THREAD

**Issue by priyashuu** [kunjgit/GameZone#5055]
### 🎮 Game Request

Game logic and basic description
Welcome to "The Enigma of Blackwood Manor," an immersive mystery adventure game set in the eerie and enigmatic Blackwood Manor. As the protagonist, you are a renowned detective called to solve the mysterious disappearance of the manor's owner, Lady Blackwood. With a rich storyline, intriguing characters, and challenging puzzles, players will navigate through the manor's dark corridors, uncover secrets, and piece together clues to solve the mystery.

### Point down the features

Game points

1. **Compelling Storyline**: Unravel the mystery of Lady Blackwood's disappearance through an engaging narrative.
  
2. **Exploration**: Navigate through different rooms and areas of the manor by clicking on doorways and interactive objects.

3. **Clue Collection**: Discover and collect clues and items hidden throughout the manor to progress in the game.

4. **Puzzle Solving**: Solve various puzzles and mini-games, such as lock picking, code breaking, and pattern matching.

5. **Dialogue System**: Interact with characters and ghosts, engaging in branching dialogues to gather information and influence the story.

6. **Inventory Management**: Store and use collected items to interact with other objects and solve puzzles.

7. **Objectives and Clues Tracking**: Keep track of current objectives and collected clues in the HUD for easy reference.

8. **Atmospheric Visuals and Sounds**: Enhance the eerie setting with background images, character sprites, animations, sound effects, and background music.

9. **Multiple Endings**: Offer different story outcomes based on player choices and actions throughout the game.

10. **User-Friendly Interface**: Intuitive navigation, clear HUD elements, and responsive design for a seamless gameplay experience.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @priyashuu , You can't have another issue before completing the previous one 😀 
 you already have the following 1 open issues 👀 ! :

#4754

**Comment by kunjgit** [comment]
Hey @priyashuu ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by kunjgit** [comment]
Hey @priyashuu ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)
