### ISSUE TITLE
[New game]: Add King sword Runner

### ISSUE THREAD

**Issue by Vaibhav-kesarwani** [kunjgit/GameZone#5056]
### 🎮 Game Request

Game logic and basic description
The 2D game which have the king player which have to reach the his castle after dfeating enemy

### Point down the features

Game points
1. Player Movement
2. Battle System
3. Graphics and UI
4. A Moment of Triumph
5. Health

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Vaibhav-kesarwani ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by Vaibhav-kesarwani** [comment]
@ishita-43 Please review the PR and merge it

**Comment by ishita-43** [comment]
Done Reviewing!!

**Comment by kunjgit** [comment]
Hey @Vaibhav-kesarwani ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
