### ISSUE TITLE
Add a Scroll to Top button Matched to Website Design theme 

### ISSUE THREAD

**Issue by MastanSayyad** [kunjgit/GameZone#5062]
Hey @kunjgit @ishita-43 

I would like to create a scroll to top button matched to website design theme as the home page is too lengthy it will helps users to scroll back to the top in just one click!

![image](https://github.com/user-attachments/assets/7ac20c76-1a42-4f83-8794-667b312ebe2d)

**Comment by kunjgit** [comment]
Hey @MastanSayyad! 🙂 
 It seems like you are not following proper guidelines !! 👀 
 Read documentation properly !!🙏 
 If you have any queries reach out to us on [Discord🕹️](https://discord.gg/fgwk4XZfxG) .

**Comment by kunjgit** [comment]
Hey @MastanSayyad ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by kunjgit** [comment]
Hey @MastanSayyad ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by ishita-43** [comment]
Duplicate issue, closing

**Comment by kunjgit** [comment]
Hey @MastanSayyad ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
