### ISSUE TITLE
[New game]: Synonym Symphony

### ISSUE THREAD

**Issue by DharshiBalasubramaniyam** [kunjgit/GameZone#5064]
### 🎮 Game Request

Game logic and basic description: Players are given a word and must find as many synonyms as possible within a time limit. The challenge increases as they progress, with more obscure or context-specific synonyms required.

### Point down the features

Game points: 

The game checks if the player's input is a valid synonym and add 10 points.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @DharshiBalasubramaniyam ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @DharshiBalasubramaniyam ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
