### ISSUE TITLE
[Bug]: The newsletter section is not responsive on footer

### ISSUE THREAD

**Issue by vishanurag** [kunjgit/GameZone#5068]
### Give a brief about the bug ✍️

Description

- The newsletter section is not responsive on footer

![Screenshot 2024-08-02 140517](https://github.com/user-attachments/assets/aaed2b99-cd4a-4b70-9420-2a4912f9aa9d)

### What is the expected behavior? 🤔

Description

- The newsletter section should be responsive for good user-experience.

### Provide step by step information reproduce the bug 📄

Description

- I will use css media-queries & bootstrap classes in order to resolve this issue.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by vishanurag** [comment]
Please assign this issue to me under GSSoC'24

**Comment by kunjgit** [comment]
Hey @vishanurag ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @vishanurag ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
