### ISSUE TITLE
[New game]: Guess the number game

### ISSUE THREAD

**Issue by tanishkaa08** [kunjgit/GameZone#5083]
### 🎮 Game Request

The user gets 10 chances to guess the number between 1 to 100. If guessed correctly within 10 tries the user wins.

### Point down the features

The game will have a input box to guess the number and a submit button to submit the number, when clicked it displays whether the given number is higher or lower than the number to be guessed. if guessed correctly within 10 tries the screen displays the user won.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @tanishkaa08 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @tanishkaa08! 
We are already having a similar game request in #4877 👀 
Make sure you come up with a cool unique idea 😀 
 Waiting for your new game idea 💗.

**Comment by kunjgit** [comment]
Hey @tanishkaa08 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
