### ISSUE TITLE
[New game]: Sentence scramble 

### ISSUE THREAD

**Issue by DharshiBalasubramaniyam** [kunjgit/GameZone#5085]
### 🎮 Game Request

1. Select difficulty level. According to the level you will recieve 5 sentences to arrange.
2. Unscramble the sentence.
3. Type your answer and click "Check Answer."
4. You have 60 seconds per sentence.<br>
5. Complete all 5 sentences to finish the game.

### Point down the features

Game points

1 point for i correct answer

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @DharshiBalasubramaniyam ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @DharshiBalasubramaniyam ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
