### ISSUE TITLE
Add Cursor Trail Effect Matched to Website Design Theme

### ISSUE THREAD

**Issue by RadhikaMalpani1702** [kunjgit/GameZone#5087]
Hey @kunjgit 

We aim to enhance the user experience on our website by adding a cursor trail effect that aligns with our current website design theme. The cursor trail effect should be visually appealing and not interfere with the website's usability.

like this

https://github.com/user-attachments/assets/03164b10-5328-46d9-81aa-880c9498a0aa

### Describe the solution you'd like

I propose to add a cursor trail effect that matches the design theme of the website. The trail effect should:

1) Use the primary color scheme of the website for consistency.
2) Be smooth and responsive to enhance the user experience.
3) Not interfere with other interactive elements on the site.
4) Be optimized for performance to avoid any lag or slow down.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @RadhikaMalpani1702 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @RadhikaMalpani1702! 🙂 
 It seems like you are not following proper guidelines !! 👀 
 Read documentation properly !!🙏 
 If you have any queries reach out to us on [Discord🕹️](https://discord.gg/fgwk4XZfxG) .

**Comment by kunjgit** [comment]
Hey @RadhikaMalpani1702 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
