### ISSUE TITLE
[New game]: Gravity Drops

### ISSUE THREAD

**Issue by kosuri-indu** [kunjgit/GameZone#5097]
### 🎮 Game Request

Game logic and basic description
Gravity Drops is a fun and interactive game where players click on the canvas to add paint drops. The goal is to create unique patterns by manipulating gravity and the movement of the paint drops.

### Point down the features

Game points
- Click on the canvas to add paint drops.
- Change the color of the paint drops using the color picker.
- Increase or decrease gravity to control the movement of the drops.
- Clear the canvas without resetting the timer.
- Reset the canvas and timer to start fresh.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @kosuri-indu ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @kosuri-indu ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
