### ISSUE TITLE
[New game]: Tower of Hanoi

### ISSUE THREAD

**Issue by aasn0119** [kunjgit/GameZone#51]
### 🎮 Game Request

**_Game logic and basic description_**

Tower of Hanoi is a classic mathematical puzzle that consists of three pegs and a number of disks of different sizes. The objective of the game is to move the entire stack of disks from one peg to another, following specific rules.

### Point down the features

**_Game points :_** 

- [ ] Game Setup:

_The game starts with all the disks stacked on one peg in ascending order of size, with the largest disk at the bottom and the smallest at the top.
The other two pegs are empty initially._

- [ ] Objectives:

The goal is to move all the disks from the starting peg to a target peg, following the rules below.
The target peg can be any of the two empty pegs.

- [ ] Rules:

1. Only one disk can be moved at a time.

2. Each move consists of taking the top disk from one of the pegs and placing it on top of the stack on another peg.

3. A larger disk must never be placed on top of a smaller disk.
4.  The order of disk sizes must be maintained throughout the game.

- [ ] Gameplay:

To make a move, the player selects the peg from which to take the top disk and the peg on which to place it.
The player can choose any legal move as long as it adheres to the rules.

**_Solving the Puzzle:_**

**_The Tower of Hanoi puzzle is solved when all the disks are successfully moved to the target peg, maintaining the correct order of sizes.
The challenge of the Tower of Hanoi puzzle lies in finding the optimal solution with the fewest number of moves. The minimum number of moves required to solve the puzzle is 2^n - 1, where n is the number of disks._**

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey  @aasn0119 ! Thank you for raising an issue 💗 You have been assigned this issue you can start working on the issue 🎮

**Comment by kunjgit** [comment]
Hello @aasn0119, Time's Uppp!⏰ 
 Sorry for closing your issue! 
 But it's more than a week since we haven't received anything from your side 😢 . 
 Come up with new ideas, create a new issue and make sure you finish it within a week! 🔥 
 All the best! 🚀 
 Happy Hacking! 💗

**Comment by kunjgit** [comment]
Hey @aasn0119 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
