### ISSUE TITLE
[Documentation Bug]:  Open games in New Tab 

### ISSUE THREAD

**Issue by kshitijarvikar** [kunjgit/GameZone#510]
### Describe the bug ✍️

when we click on any particular game, it opens in same tab. which makes it hard to get back to home back and keep same game open. we can open each game in new tab.

it does work when clicked on link below. but doesn't work when clicked on game image

we can fix this by adding  target blank

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @kshitijarvikar ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by Harshvardhan-Dubey-Github** [comment]
please assign me this issue

**Comment by kshitijarvikar** [comment]
> please assign me this issue 
> 

This bug is already solved and pull request has been made

**Comment by kunjgit** [comment]
Hey @kshitijarvikar ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
