### ISSUE TITLE
[New game]: add number sorting game

### ISSUE THREAD

**Issue by AmruthaPariprolu** [kunjgit/GameZone#5108]
### 🎮 Game Request

Game logic and basic description
the player will be given a list of numbers and he/she need to sort them in ascending order

### Point down the features

Game points

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @AmruthaPariprolu , You can't have another issue before completing the previous one 😀 
 you already have the following 1 open issues 👀 ! :

#5103

**Comment by kunjgit** [comment]
Hey @AmruthaPariprolu ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)
