### ISSUE TITLE
[New game]: Sky Lift Dash

### ISSUE THREAD

**Issue by SanskarSinghiit** [kunjgit/GameZone#5110]
#### Objective: 
Prevent the ball from reaching the top of the screen by gliding it through a moving gap in horizontal walls.
#### Gameplay:
  1.  Walls move upward continuously.
  2.   The ball falls under gravity.
  3.   Align the ball with the moving gap to avoid collision.
  4.   End Condition: The game ends if the ball reaches the top of the screen.

### Game points

- Dynamic Walls:    Horizontal walls move upward at increasing speeds.
- Gap Alignment: Ball must navigate through a moving gap in the walls.
- Gravity Mechanic: Ball falls continuously, simulating gravity.
- Game Over: Triggered if the ball touches the top edge of the screen.
- Score Tracking: Track and display the time survived or number of successful passes through the gap.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @SanskarSinghiit ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @SanskarSinghiit ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
