### ISSUE TITLE
[New game]: Add Tower Building Game

### ISSUE THREAD

**Issue by ImmidiSivani** [kunjgit/GameZone#5111]
### 🎮 Game Request

Game logic and basic description
In this game user need to build the tower as high as possible by placing blocks on top of each other. any imbalance cause the tower to  become unstable and collapse.

### Point down the features

Game points
Players earn points based on the height of the tower or the number of blocks successfully stacked.

### Select program in which you are contributing
GSSoC24
_No response_

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @ImmidiSivani ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @ImmidiSivani ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
