### ISSUE TITLE
[New game]: Pac Go

### ISSUE THREAD

**Issue by Aditijainnn** [kunjgit/GameZone#5114]
### 🎮 Game Request

Game logic and basic description
![screenshot](https://github.com/user-attachments/assets/065bdeee-2163-4424-9933-55e57fddb0da)

### Point down the features

Game points
The four enemies that try to catch Pac-Man. Each ghost has its own unique behavior

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Aditijainnn , You can't have another issue before completing the previous one 😀 
 you already have the following 1 open issues 👀 ! :

#4436

**Comment by kunjgit** [comment]
Hey @Aditijainnn ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by kunjgit** [comment]
Hey @Aditijainnn ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)
