### ISSUE TITLE
[New game]: tether game 

### ISSUE THREAD

**Issue by Aditijainnn** [kunjgit/GameZone#5116]
### 🎮 Game Request

Game logic and basic description
tether! is game where you wreck as many enemies as possible using your tether, however if an enemy touches your ball then you get obliterated! This game has full mobile and offline support, designed as a progressive web application! This is my group's end-of-the-year project for our CS class.

### Point down the features

![image](https://github.com/user-attachments/assets/3868f97c-18c7-4bd4-994f-119aa650d7e3)

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Aditijainnn ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @Aditijainnn! 
We are already having a similar game request in #5100 👀 
Make sure you come up with a cool unique idea 😀 
 Waiting for your new game idea 💗.

**Comment by kunjgit** [comment]
Hey @Aditijainnn ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
