### ISSUE TITLE
[New game]: Debris Dodge

### ISSUE THREAD

**Issue by Aditijainnn** [kunjgit/GameZone#5117]
### 🎮 Game Request

Game logic and basic description
 This is a 2D game where you control a tank, survive against waves of enemies, and collect bonuses to boost your performance. Test your skills, strategize, and aim for the highest score!

### Point down the features

Game points
In this game, you take control of a tank in a 2D environment. Your goal is to survive against waves of enemies, while also collecting bonuses that can help you in your battle. The game features different terrains, a variety of enemies, and exciting gameplay mechanics.
### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Aditijainnn ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
