### ISSUE TITLE
[New game]: quiz game base on javascript question

### ISSUE THREAD

**Issue by samirzjadhav** [kunjgit/GameZone#512]
### 🎮 Game Request

Game logic and basic description
this game is based on a javascript question like  1+1 === 2
like this 
the answer will be true or false
![Screen Shot 2023-05-28 at 1 04 58 PM](https://github.com/kunjgit/GameZone/assets/102903265/88531233-549f-4abe-8af9-50ac23d0e87a)

### Point down the features

Game points
1. good for learning javascript
2. game UI is good 

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @samirzjadhav ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by Harshvardhan-Dubey-Github** [comment]
please assign me this issue

**Comment by rt-001** [comment]
@kunjgit assign this to me pls.

**Comment by kunjgit** [comment]
Hello @samirzjadhav, Time's Uppp!⏰ 
 Sorry for closing your issue! 
 But it's more than a week since we haven't received anything from your side 😢 . 
 Come up with new ideas, create a new issue and make sure you finish it within a week! 🔥 
 All the best! 🚀 
 Happy Hacking! 💗

**Comment by kunjgit** [comment]
Hey @samirzjadhav ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
