### ISSUE TITLE
[New game]:  Hit-the-mole

### ISSUE THREAD

**Issue by Sourabh782** [kunjgit/GameZone#5124]
### 🎮 Game Request

Game logic and basic description
Test your reflexes and speed with our Mole-hitter game! In this fun and addictive game, moles pop up randomly from their holes, and it's your job to whack them before they disappear. The more moles you hit, the higher your score. But be quick – the moles get faster and more elusive as you progress through the levels.

### Point down the features

Game points
Hitting mole to gain points

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Sourabh782 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by Sourabh782** [comment]
Thanks, i'll be working on it

**Comment by kunjgit** [comment]
Hey @Sourabh782 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
