### ISSUE TITLE
[New game]: Block Vault

### ISSUE THREAD

**Issue by SanskarSinghiit** [kunjgit/GameZone#5131]
#### Objective: 
Players control a block that must jump over other horizontally incoming blocks. Inspired by the Google Dino game, it challenges players to time their jumps precisely to avoid obstacles and score high.

### Point down the features

- **Horizontal Obstacles:** Blocks move across the screen.
- **Jump Mechanic:** Player can jump to avoid obstacles.
- **Speed Increase:** Obstacles speed up over time.
- **Scoring System:** Points for each obstacle avoided.
- **Game Over:** Collision with an obstacle ends the game.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @SanskarSinghiit ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @SanskarSinghiit ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
