### ISSUE TITLE
[New game]: Harry Potter wizard quiz game.

### ISSUE THREAD

**Issue by sweta-singh28** [kunjgit/GameZone#5133]
### 🎮 Game Request

Game logic and basic description
The Harry Potter Wizard Quiz Game is a trivia-based game designed for fans of the Harry Potter series. Players test their knowledge of the magical world, answering questions about characters, spells, potions, and key events from the books and movies. Points are earned for correct answers, and the goal is to achieve the highest score, proving your expertise as a true wizard or witch.

### Point down the features

Game points

Diverse Question Categories: Includes questions on characters, spells, potions, magical creatures, Hogwarts houses, and key events from both the books and movies.

Time-Based Challenges: Players must answer questions within a set time limit to earn points, adding an element of urgency to the gameplay.

Interactive Animations and Sound Effects: Engaging visual and audio effects that bring the magical world to life with every correct or incorrect answer.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @sweta-singh28 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @sweta-singh28 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
