### ISSUE TITLE
[New game]: Path Finder Challenge

### ISSUE THREAD

**Issue by nikki-05** [kunjgit/GameZone#5134]
### 🎮 Game Request

Game logic and basic description
Path Finder Challenge is a grid-based puzzle game where the player must navigate from a source tile to a destination tile on an 8x8 grid. The grid contains various types of tiles, including normal tiles, obstacles, bonuses, and special tiles. The player interacts with the grid by clicking on tiles to select a path. The game ends when the player either successfully reaches the destination or runs out of time. If the player selects an obstacle tile, they lose points. The game also features a timer and a scoring system to track the player’s progress.

### Point down the features

Features :
-Fixed Grid Layout: The grid is static, with a consistent layout where the source is always in the top-left corner and the destination is in the bottom-right corner.
-Tile Types:
Normal Tiles:, Obstacle Tiles, Bonus Tiles
-Score System: Players earn points for selecting normal and bonus tiles and lose points for selecting obstacles.
-Timer: A countdown timer limits the duration of the game. The game ends when the timer reaches zero.
-Selection Path: Players can select a path from the source to the destination. The tiles on the selected path are highlighted.
-Restart and Start Game: Buttons are provided to start a new game or restart the current game.
-Dark Theme Option: A toggle button allows switching between light and dark themes for better visual comfort.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @nikki-05 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @nikki-05 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
