### ISSUE TITLE
[Feature Request]: Adding a Game Community Forum for the website

### ISSUE THREAD

**Issue by pooranjoyb** [kunjgit/GameZone#514]
### Description

I would like to add a **Game discussion Forum** for the website. So that players can discuss and comment about the games and improve the community.

## Outcomes : 
- A community forum can help us increase user engagement, and get invaluable product feedback. 
- The forum becomes even more powerful when combined with a knowledge base.
- The feedbacks and comments will be rendered in the discussions section.
- It will ensure a friendly environment among the people visiting the website to search for games.

### Will add it here probably, above the footer
![image](https://github.com/kunjgit/GameZone/assets/90945182/e7f5ea72-0193-4ca2-aa79-d2d183376e9e)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines]
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @pooranjoyb! 🙂 
 It seems like you are not following proper guidelines !! 👀 
 Read documentation properly !!🙏 
 If you have any queries reach out to us on [Discord🕹️](https://discord.gg/fgwk4XZfxG) .

**Comment by kunjgit** [comment]
Hey @pooranjoyb ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @pooranjoyb ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by pooranjoyb** [comment]
> Hey @pooranjoyb ! Thank you so much for your raising the issue💗 
>  It’s all yours, you can come anytime again and make some contributions! 🚀 
>  Alone, we can do little, but together we can do so much! 😇
> 

Hello @kunjgit should I reopen the issue? Like I didn't get why the issue is closed.
