### ISSUE TITLE
[New game]: Elemental Flux

### ISSUE THREAD

**Issue by Shantnu-singh** [kunjgit/GameZone#5141]
### 🎮 Game Request

Elemental Flux is an engaging and educational drag-and-drop card game that challenges players to distinguish between renewable and non-renewable energy sources. In this visually stunning showdown, players must correctly categorize various energy sources, learning about sustainability and resource management in the process.

### Point down the features

- Intuitive drag-and-drop gameplay
- Beautifully designed cards representing different energy sources
- Dynamic scoring system
- Educational content about renewable and non-renewable energy
- Sleek, modern user interface
- Responsive design for both desktop and mobile play

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Shantnu-singh , You can't have another issue before completing the previous one 😀 
 you already have the following 1 open issues 👀 ! :

#4770

**Comment by kunjgit** [comment]
Hey @Shantnu-singh ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by kunjgit** [comment]
Hey @Shantnu-singh ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)
