### ISSUE TITLE
[New game]: Random Choice Picker 🎲

### ISSUE THREAD

**Issue by SanskarSinghiit** [kunjgit/GameZone#5143]
### 🎮 Game Request

Introducing the Random Choice Picker!
Enter your choices into a textarea, hit ENTER, and let the game shuffle and reveal a random option.
Perfect for making quick decisions or adding a bit of fun!

![image](https://github.com/user-attachments/assets/04929904-083d-418c-ba97-eb0fb37b3906)

### Point down the features

- **Interactive Textarea**: Input choices separated by commas.
- **Pick Button**: Randomly selects a choice when pressed.
- **Result Display**: Shows the selected choice.
- **Responsive Design**: Optimized for all devices.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @SanskarSinghiit ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @SanskarSinghiit ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
