### ISSUE TITLE
[New game: Rainy Day

### ISSUE THREAD

**Issue by Shantnu-singh** [kunjgit/GameZone#5148]
### 🎮 Game Request

Water Drop Catcher is an interactive browser-based game where players control a cloud to catch falling water drops. The game aims to raise awareness about water conservation in a fun and engaging way.

### Point down the features

- Responsive cloud movement using arrow keys or touch controls
- Randomly falling water drops
- Score tracking for caught water drops
- Lives system (game over after 5 missed drops)
- Modern and sleek design
- Restart functionality

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Shantnu-singh , You can't have another issue before completing the previous one 😀 
 you already have the following 1 open issues 👀 ! :

#4770

**Comment by kunjgit** [comment]
Hey @Shantnu-singh ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by kunjgit** [comment]
Hey @Shantnu-singh ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)
