### ISSUE TITLE
[New game]: A word scramble game.

### ISSUE THREAD

**Issue by medhacodes** [kunjgit/GameZone#516]
### 🎮 Game Request

Game logic and basic description

In this game, a word will be scrambled and the user has to guess the word using the given hint in a limited time period. If the user enters the correct word the notification pops as "correct answer", it the timer goes off, the notification pops as "times up" and displays the correct answer.

### Point down the features

-Pop notification system
- Timer
- Hints
- Easy to understand 
- Fun

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

@kunjgit please assign this issue to me.

**Comment by kunjgit** [comment]
Hey @medhacodes ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hello @medhacodes, Time's Uppp!⏰ 
 Sorry for closing your issue! 
 But it's more than a week since we haven't received anything from your side 😢 . 
 Come up with new ideas, create a new issue and make sure you finish it within a week! 🔥 
 All the best! 🚀 
 Happy Hacking! 💗

**Comment by kunjgit** [comment]
Hey @medhacodes ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
