### ISSUE TITLE
[New game]: Gravity Switch Game

### ISSUE THREAD

**Issue by Ishitamukherjee2004** [kunjgit/GameZone#5161]
### 🎮 Game Request

Game logic and basic description
Controls:

- Space bar: Switch gravity direction (up or down)
- No horizontal movement: Focus on vertical movement and gravity switching

Gameplay:

1. Start by falling downwards due to gravity.
2. Switch gravity direction by pressing the space bar when you're close to a platform.
3. Use the switched gravity to move upwards or downwards onto platforms.
4. Continue switching gravity to navigate through the platforms.
5. Reach the top or bottom of the game container to win (not implemented in this basic version).

### Point down the features

Game points

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Ishitamukherjee2004 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by Ishitamukherjee2004** [comment]
@kunjgit pls add the gssoc level

**Comment by kunjgit** [comment]
Hey @Ishitamukherjee2004 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
