### ISSUE TITLE
[New game]: Add Pacman Game 👾

### ISSUE THREAD

**Issue by SanskarSinghiit** [kunjgit/GameZone#5165]
### 🎮 Game Request

Add a classic Pac-Man game where players navigate Pac-Man through a maze, eating pellets and avoiding ghosts.
The game will feature multiple levels, scoring, and ghost AI.

### Point down the features

**Game Logic and Features:**
- **Gameplay:** Navigate Pac-Man through a maze, eat pellets, and avoid or chase ghosts.
- **Levels:** Progress through increasing difficulty levels.
- **Score Tracking:** Track and beat high scores.
- **Ghosts:** Aggressive and nonchalant behaviors for ghosts.
- **Pellets:** Different types of pellets with varying scores.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @SanskarSinghiit , You can't have another issue before completing the previous one 😀 
 you already have the following 1 open issues 👀 ! :

#5159

**Comment by kunjgit** [comment]
Hey @SanskarSinghiit ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by kunjgit** [comment]
Hey @SanskarSinghiit ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)
