### ISSUE TITLE
[New game]: Pokémon-Style Game

### ISSUE THREAD

**Issue by Explorer003** [kunjgit/GameZone#517]
### 🎮 Game Request

- Wanted to create a **Pokémon-style game** 
- In this Pokémon-inspired game, players will explore a vast world filled with diverse monsters.
- We will fight the monsters with various fighting styles.

### Point down the features

- Exploration plays a crucial role in the game. Players will traverse diverse environments such as forests, mountains, caves, and cities, each containing unique monsters to encounter. 
- Using the keys on the keyboard we can move the player forward, backward right and left.
- There will be a specific area in which our player can move and once player steps on a particular location, the monster gets activated and the battle begins.
- There will be a life status bar, showing the current health and health will decrement upon the subsequent attacks.
 
It will look like as seen in the Pictures below.
![Screenshot (154)](https://github.com/kunjgit/GameZone/assets/107935613/c3f30f46-8345-46b3-bf9b-04c5f97948e7)
![Screenshot (153)](https://github.com/kunjgit/GameZone/assets/107935613/863e4cd2-5fdb-46c8-b714-69f517b670ef)

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Explorer003 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @Explorer003 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by kunjgit** [comment]
Hey @Explorer003 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
