### ISSUE TITLE
[Documentation Bug]: Enhance README Structure and Fix Improperly Added Links

### ISSUE THREAD

**Issue by priyashuu** [kunjgit/GameZone#5170]
### Describe the bug ✍️

Describe your bug here
The current README file has several issues:
- The structure is not well-organized, which may confuse new contributors or users.
- Several contributors did not properly add links, leading to broken or unclear references.
![game issues](https://github.com/user-attachments/assets/50bb0951-78a2-4406-8b77-76cf1c00484d)

### Provide step by step information reproduce the bug 📄

Description
- Restructure the README to follow a clear and consistent format.
- Review and correct all improperly added links.
- Consider adding a section for new contributors on how to properly format links.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @priyashuu , You can't have another issue before completing the previous one 😀 
 you already have the following 1 open issues 👀 ! :

#4754

**Comment by kunjgit** [comment]
Hey @priyashuu ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by kunjgit** [comment]
Hey @priyashuu ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)
