### ISSUE TITLE
The UI of GameZone

### ISSUE THREAD

**Issue by mayu-z** [kunjgit/GameZone#5178]
Hey Kunj,

This is Mayuresh

Great work on [GameZone](https://kunjgit.github.io/GameZone/) really liked your games but I think the UI could be better so I'd like to fix the css and js part of the project.

### **Here are the things that might need a fixing for a better UI:**

- The fonts, a little change in font could make the project 4x better and attractive.
- The colors, honestly I think changes in colors of the background and divs could bring out the real potential of the project
- The nav-bar, is more of a simple choice and the logo as well.
- The icons, the icons used could be better which will give the website a decent look.
- the theme should be dark from default for a better experience.

_These are the changes I could think of and I'll come up with more while working on it hope you get it._

Thank you,

**Comment by kunjgit** [comment]
Hey @mayu-z ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @mayu-z! 🙂 
 It seems like you are not following proper guidelines !! 👀 
 Read documentation properly !!🙏 
 If you have any queries reach out to us on [Discord🕹️](https://discord.gg/fgwk4XZfxG) .

**Comment by kunjgit** [comment]
Hey @mayu-z ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
