### ISSUE TITLE
[New game]: Fight game

### ISSUE THREAD

**Issue by S-ishita** [kunjgit/GameZone#52]
### 🎮 Game Request

A fighting game is a genre of video game in which a gamer battles against another character controlled by another gamer.
This fighting game feature special moves that are triggered through rapid sequences of button presses.

### Point down the features

Player 1: Controls:W A D Space F
Player 2: Controls:ArrowUp ArrowLeft ArrowRight ArrowDown

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @S-ishita  ! It is really interesting but we want to hear more…..
Can you elaborate the features 🤔!
We are looking forward have your valuable contribution in GameZone 🎮

**Comment by S-ishita** [comment]
VARIOUS FEATURES ARE:

- jumping of players
- hitting of players
- music/game sounds
- timer
![f](https://github.com/kunjgit/GameZone/assets/104543751/9b64c68b-21fb-47e2-9871-b22c17b81b94)
![f1](https://github.com/kunjgit/GameZone/assets/104543751/fe4ab7af-426f-4919-8443-85d3e87cbe7e)

**Comment by kunjgit** [comment]
Hey  @S-ishita ! Thank you for raising an issue 💗 You have been assigned this issue you can start working on the issue 🎮

**Comment by kunjgit** [comment]
Hey @S-ishita ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
