### ISSUE TITLE
[New game]: Minesweeper

### ISSUE THREAD

**Issue by singh-anushka** [kunjgit/GameZone#53]
### 🎮 Game Request

Game logic and basic description
In Minesweeper, you need to uncover all the squares on the grid without detonating any mines. The grid is initially covered with hidden squares, some of which contain mines. Your task is to reveal the safe squares while avoiding the explosive mines lurking beneath.
This is prepared using HTML, CSS and JavaScript.

The game is played on a rectangular grid, typically ranging from 8x8, with 5 mines. Each square on the grid can be in one of three states: hidden, revealed, or flagged. Initially, all squares are hidden, and you must choose which squares to reveal.

To uncover a square, you can click on it using your mouse or touch the corresponding area on a touchscreen device. Once a square is revealed, it will display a number, indicating how many mines are adjacent to that square. Use these numbers strategically to deduce the location of mines and proceed further.

### Point down the features

There are no points earned in intermediate moves, but if you encounter a mine, it's game over! The mine will explode, revealing its location, and you'll have to start again. However, if you successfully uncover all the safe squares without triggering any mines, You Win!

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @singh-anushka ! It is really interesting but we want to hear more…..
Can you elaborate the features 🤔!
We are looking forward have your valuable contribution in GameZone 🎮

**Comment by singh-anushka** [comment]
I updated the issue, now please add the GSSOC23 label. And can I start working on the same?

**Comment by singh-anushka** [comment]
> Hey @singh-anushka ! It is really interesting but we want to hear more….. Can you elaborate the features 🤔! We are looking forward have your valuable contribution in GameZone 🎮

I updated the issue, now please add the GSSOC23 label. And can I start working on the same?
