### ISSUE TITLE
[New game]: 2048Game

### ISSUE THREAD

**Issue by MohammadAsiya** [kunjgit/GameZone#530]
### 🎮 Game Request

Game logic and basic description:
2048 is a popular single-player puzzle game that challenges players to combine numbered tiles to reach the ultimate goal of creating a tile with the number 2048. The game is played on a 4x4 grid, and the objective is to merge tiles by sliding them in different directions and creating higher-valued tiles.

Here's a breakdown of the game logic and rules:

Game Setup:
        The game starts with two randomly generated tiles, each with a value of either 2 or 4, placed on the grid.
        The grid is initially empty except for these two tiles.
Gameplay:
         The player can use arrow keys (up, down, left, right) or swipe gestures to slide the tiles in one of the four directions.
         All tiles on the grid move simultaneously in the selected direction, sliding as far as possible until they either reach the edge 
         of the grid or collide with another tile.
          When two tiles with the same value collide, they merge into a single tile with double the value.
          After each move, a new tile (either 2 or 4) is randomly generated and placed on an empty spot on the grid.
          The player continues to make moves, merging tiles and trying to create higher-valued tiles.
Goal:
         The primary objective is to reach the 2048 tile by merging tiles of lower values.
        However, the game doesn't end when the 2048 tile is created. The player can continue to play and aim for higher-valued  
        tiles.
Game Over:
        The game ends when there are no available moves left, i.e., the player cannot slide any tiles to merge or create empty spots 
        on the grid.
         If the grid becomes completely filled with tiles and no more moves are possible, it results in a game over.
Scoring:
       Each merge operation earns points equal to the value of the merged tile.
       The player's score is the sum of all the points earned during the game.
       The goal is to achieve the highest possible score.

### Point down the features

Game points:
       Each merge operation earns points equal to the value of the merged tile.
       The player's score is the sum of all the points earned during the game.
       The goal is to achieve the highest possible score.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @MohammadAsiya ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by soorjya** [comment]
I'm a contributor for GSSoC '23, I want to contribute to this issue. Please assign me.

**Comment by kunjgit** [comment]
Hello @MohammadAsiya, Time's Uppp!⏰ 
 Sorry for closing your issue! 
 But it's more than a week since we haven't received anything from your side 😢 . 
 Come up with new ideas, create a new issue and make sure you finish it within a week! 🔥 
 All the best! 🚀 
 Happy Hacking! 💗

**Comment by kunjgit** [comment]
Hey @MohammadAsiya ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
