### ISSUE TITLE
[Documentation Bug]: Align Tech Stack section in README.md

### ISSUE THREAD

**Issue by simon-riley-aka-ghost** [kunjgit/GameZone#531]
### Describe the bug ✍️

The Tech Stack section is not aligned in the centre. I want to fix this issue.
**Screenshot**

![Screenshot from 2023-05-28 21-22-07](https://github.com/kunjgit/GameZone/assets/134860752/cdfaa466-5a29-454f-9a75-3c8c23975d3e)
 

### Provide step by step information reproduce the bug 📄

I'll centre it by containing the tech stacks into a div with align attribute set to the centre.

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @simon-riley-aka-ghost ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @simon-riley-aka-ghost ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
