### ISSUE TITLE
[New game]: Rock Paper Scissors

### ISSUE THREAD

**Issue by singh-anushka** [kunjgit/GameZone#54]
### 🎮 Game Request

Game logic and basic description
Basic rock paper scissors game made using HTML, CSS and Javascript.

### Point down the features

Game points

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @singh-anushka we are already having similar game request in #11 !!
Thank you for showing your interest in GameZone 🎮 💗
