### ISSUE TITLE
[New game]: Sudoku Game

### ISSUE THREAD

**Issue by roshan798** [kunjgit/GameZone#549]
### 🎮 Game Request

Game logic and basic description
 I have created a Sudoku game using HTML, CSS, and JavaScript, featuring a backtracking algorithm to generate unique puzzles and validate their solutions.
 The Sudoku game I have developed offers a classic and engaging puzzle-solving experience.

### Point down the features

Game points
Game Mechanics: The game follows the traditional rules of Sudoku, where players must fill a 9x9 grid with numbers from 1 to 9, ensuring that each row, each column, and each of the nine 3x3 sub-grids contain all the numbers from 1 to 9 without repetition.

Puzzle Generation: Using a backtracking algorithm, the game generates unique Sudoku puzzles for players to solve. This algorithm ensures that each generated puzzle has only one valid solution, guaranteeing an enjoyable and challenging experience for players.

User Interface: The game boasts a visually appealing and intuitive user interface created using HTML and CSS. The design provides a smooth and responsive experience across various devices and screen sizes, enhancing user engagement.

Solution Validation: After filling in the grid, the game includes a solution validation feature to check the correctness of the player's solution. It provides immediate feedback, indicating any incorrect entries or notifying the player when the puzzle is solved successfully.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @roshan798! 
We are already having a similar game request in #446 👀 
Make sure you come up with a cool unique idea 😀 
 Waiting for your new game idea 💗.

**Comment by kunjgit** [comment]
Hey @roshan798 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @roshan798 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by kunjgit** [comment]
Hey @roshan798 ! , This issue is already assigned to @roshan798. 💗 
 You can work on other issues 🚀 
 If there is anything wrong you can contact us on [Discord🕹️](https://discord.gg/fgwk4XZfxG)👀
