### ISSUE TITLE
[New game]: Wordle

### ISSUE THREAD

**Issue by singh-anushka** [kunjgit/GameZone#55]
### 🎮 Game Request

Game logic and basic description
Basic wordle game made using HTML, CSS and Javascript.

### Point down the features

Game points

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @singh-anushka ! It is really interesting but we want to hear more…..
Can you elaborate the features 🤔!
We are looking forward have your valuable contribution in GameZone 🎮

**Comment by kunjgit** [comment]
We are having #87 that is more specific so we are closing your issue !! 
Thank you for raising an issue 💗

**Comment by ritik48** [comment]
@kunjgit please assign me this. I have completed the game today.
