### ISSUE TITLE
[New game]: Not_morethan5

### ISSUE THREAD

**Issue by SusanStorm** [kunjgit/GameZone#550]
### 🎮 Game Request

Basic description:
It is a simple game word guessing game where the has to guess the word by filling the blanks.User has to guess one letter at a time to fill in all the blanks and user can make only 5 wrong attempts.That'why !(not)more than 5 :).
How to play:
Simply users have to guess the name of animals.On screen they are able to see three things,that help them to guess the name and continue in the game. 1.Number of letters. 2.Number of guesses remaining,it is shown by the blocks.every time user make a mistake it increase the a block in structure.once the structure touches the base ,the game is over. 3.Also If users don't want to contiue with the same word,they can go to new word also.
Screenshots:
![Screenshot (75)](https://github.com/kunjgit/GameZone/assets/114725350/015ada83-6195-4ca0-96c0-97e8ca947be2)
![Screenshot (77)](https://github.com/kunjgit/GameZone/assets/114725350/30bc071e-74b8-4d43-b6ce-7ac590a6b7d6)
![Screenshot (78)](https://github.com/kunjgit/GameZone/assets/114725350/19f22009-8d87-4200-aa49-0449ea6e9f74)
![Screenshot (82)](https://github.com/kunjgit/GameZone/assets/114725350/7763c403-3508-482e-8011-fd4bf2fcc27d)
![Screenshot (83)](https://github.com/kunjgit/GameZone/assets/114725350/62e6d59f-bee4-4f2e-91de-2c218871ac44)

### Point down the features

Game points:
The game consist of three parts: 
1.How to play section: It helps users to understand about the game and rules they have to follow. 
2.New Game section : To enter in to the game. 
3.Dark and light mode section : Users can toggle their screen between light and dark mode as per their requirement.
Link: https://susanstorm.github.io/Not-morethan5/

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @SusanStorm ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @SusanStorm ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
