### ISSUE TITLE
To make the better interface for snake game

### ISSUE THREAD

**Issue by charan-1303** [kunjgit/GameZone#559]
### Is your enhancement request related to a problem? Please describe.➕

actually the background of snake game was not that good i want to improve that using css , i will make it look better so that user can get a better experiance while playing the game.  @kunjgit  
I want to do this project 
so kindly assign me this :)
![Screenshot (91)](https://github.com/kunjgit/GameZone/assets/131485387/09f916a5-3a45-4bf9-9edd-0337e0fa8434)

### Describe the solution you'd like

I want to give good background for this game and i will make some changes in font of sanke game so that my backgreound and font will be of same theme. actually now it is very  vibrant so that user cannot concentrate on that game . so by making a new good background the problem will be resolved :)

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @charan-1303 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @charan-1303! 🙂 
 It seems like you are not following proper guidelines !! 👀 
 Read documentation properly !!🙏 
 If you have any queries reach out to us on [Discord🕹️](https://discord.gg/fgwk4XZfxG) .

**Comment by kunjgit** [comment]
Hey @charan-1303 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
