### ISSUE TITLE
[New game]: Dinosaur Game

### ISSUE THREAD

**Issue by singh-anushka** [kunjgit/GameZone#56]
### 🎮 Game Request

Game logic and basic description
In this game, there is a prehistoric landscape where our player is a dinosaur. The objective is simple: help the dinosaur navigate through an endless desert while avoiding obstacles and surviving for as long as possible. As you progress, the game becomes increasingly challenging. Cacti and flying pterodactyls will try to block your path, and you must time your jumps and crouches perfectly to avoid them. 

Basic google chrome dinosaur game made using HTML, CSS and Javascript.

### Point down the features

Game points
Each time dinosaur dodges an obstacle, a point is scored. As the points increase the game becomes more difficult.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @singh-anushka  ! It is really interesting but we want to hear more…..
Can you elaborate the features 🤔!
We are looking forward have your valuable contribution in GameZone 🎮

**Comment by singh-anushka** [comment]
@kunjgit I updated the issue, now please add the GSSOC23 label. And can I start working on the same?
