### ISSUE TITLE
[New game]: Menja Game

### ISSUE THREAD

**Issue by trishanu-init** [kunjgit/GameZone#561]
### 🎮 Game Request

This exhilarating game consists of multi color cubes that jump from beneath the screen and the user needs to slice the cube using the mouse controls before the cube crosses the bottom of the screen. the game also has a slow-mo mode which gets activated when a n user slices a electric blue cube.

I hope everyone enjoys this game..!

### Point down the features

- Beautiful Graphics
- Slow-Mo  Mode
- Fun to Play
- Game can be Paused

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @trishanu-init ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
