### ISSUE TITLE
[New game]: Moto Racing Game

### ISSUE THREAD

**Issue by anandpiyush1521** [kunjgit/GameZone#565]
### 🎮 Game Request

Game logic and basic description

Single player game using html css and js.

### Point down the features

Game points

simple player.
user friendly

![Screenshot (1631)](https://github.com/kunjgit/GameZone/assets/75721333/1b93e1cd-31bf-47d7-8cb0-653cd43ff765)
![Screenshot (1632)](https://github.com/kunjgit/GameZone/assets/75721333/a7f1bf70-164d-460c-9476-5572f3af149c)

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @anandpiyush1521 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hello @anandpiyush1521, Time's Uppp!⏰ 
 Sorry for closing your issue! 
 But it's more than a week since we haven't received anything from your side 😢 . 
 Come up with new ideas, create a new issue and make sure you finish it within a week! 🔥 
 All the best! 🚀 
 Happy Hacking! 💗

**Comment by kunjgit** [comment]
Hey @anandpiyush1521 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
