### ISSUE TITLE
[New game]: Number Guessing Game.

### ISSUE THREAD

**Issue by Alkaison** [kunjgit/GameZone#57]
## Game logic and basic description

- User has to guess a number between 1 to 10.
- If the guesses number is invalid a error message will be poped up.
- The number of guesses it would took will also be counted.
- Proper validation.

## Game points

- User has to guess a number between 1 to 10.
- If the guesses number is invalid a error message will be poped up.
- The number of guesses it would took will also be counted.
- Proper validation.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by Alkaison** [comment]
Hi @kunjgit, can you please assign the GSSoC'23 label to this issue? It would a great contributing to GameZone.

**Comment by Alkaison** [comment]
- Fixed: #63 

Please assign this to me and review it. Also do add the GSSoC'23 label.

**Comment by kunjgit** [comment]
Hey @Alkaison  ! Thank you for raising an issue 💗 
Please increase the complexity of the game it is too simple for now add some new features !!

**Comment by Alkaison** [comment]
Hey @kunjgit, Should I make it like guess between 1 to 100. The user would get a hint whether its higher or lower than the enter input ? 

How do you suggest ?

**Comment by Alkaison** [comment]
Btw it got unassigned, please do the needful.

**Comment by kunjgit** [comment]
The game you are requesting is too simple and not having much complex logic !!
make sure you come up with something good 🚀
