### ISSUE TITLE
[New game]: Rabbit Rush

### ISSUE THREAD

**Issue by aditya-agr** [kunjgit/GameZone#575]
### 🎮 Game Request

It is a simple rush game in which we have to save the running rabbit from hinderance in his path by jumping over it. During game, one monster follows the rabbit to catch it and we have save rabbit from it.
How to play:
The user has to simply tap on screen to jump over the hinderance in the path of rabbit.

### Point down the features

Beautiful Graphics
Melodious background sound
Slow-Mo Mode
Fun to Play
Game can be Paused

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @aditya-agr ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by aditya-agr** [comment]
Please review my pull request. @kunjgit

**Comment by aditya-agr** [comment]
It has been already assigned to me ?

**Comment by aditya-agr** [comment]
Hey @ShubhaSwarup I had made this issue and already working on it. So please unassign yourself from this issue.

**Comment by kunjgit** [comment]
Hey @aditya-agr ! , This issue is already assigned to @ShubhaSwarup. 💗 
 You can work on other issues 🚀 
 If there is anything wrong you can contact us on [Discord🕹️](https://discord.gg/fgwk4XZfxG)👀

**Comment by kunjgit** [comment]
Hey @aditya-agr ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
