### ISSUE TITLE
[New game]: 2048 single-player sliding tile puzzle

### ISSUE THREAD

**Issue by thevirengarg** [kunjgit/GameZone#579]
### 🎮 Game Request

Game logic and basic description: 2048 is played on a plain 4×4 grid, with numbered tiles that slide when a player moves them using the four arrow keys. Every turn, a new tile randomly appears in an empty spot on the board with a value of either 2 or 4. If two tiles of the same number collide while moving, they will merge into a tile with the total value of the two tiles that collided. If a move causes three consecutive tiles of the same value to slide together, only the two tiles farthest along the direction of motion will combine. The game is won when a tile with a value of 2048 appears on the board. Players can continue beyond that to reach higher scores. When the player has no legal moves (there are no empty spaces and no adjacent tiles with the same value), the game ends.

### Point down the features

Game points: A scoreboard on the upper right keeps track of the user's score. The user's score starts at zero and is increased whenever two tiles combine, by the value of the new tile.
![Screenshot (198)](https://github.com/kunjgit/GameZone/assets/111726483/982d03c7-7c43-4d1c-9542-4f1994cf44b4)
![Screenshot (197)](https://github.com/kunjgit/GameZone/assets/111726483/a39c3b24-ac2e-4825-b6b0-47c1d891ca6c)

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @thevirengarg ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @thevirengarg ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
