### ISSUE TITLE
[New game]: Card matching game

### ISSUE THREAD

**Issue by singh-anushka** [kunjgit/GameZone#58]
### 🎮 Game Request

Game logic and basic description
Basic card matching game using HTML, CSS and JavaScript.
In this 2 cards are flipped consecutively if they match a point is scored; else they are flipped back again.

### Point down the features

Game points
If 2 cards are matched, 10 points are scored.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @singh-anushka  ! We are already having similar game request before in #34 !
Thank you soo much for having your interest in GameZone 💗
