### ISSUE TITLE
[Bug]: Whack_a_Mole button issue

### ISSUE THREAD

**Issue by programerr01** [kunjgit/GameZone#581]
### Give a brief about the bug ✍️

Whack a Mole `Start new Game` button not working properly, timer count increases as you click more on it 

![www_screencapture_com_2023-5-29_22_19](https://github.com/kunjgit/GameZone/assets/61112300/7397d7d7-aa99-490b-9a22-90ccd913d76b)

### What is the expected behavior? 🤔

The counter should decrease every second 

### Provide step by step information reproduce the bug 📄

- go to [Whack_a_Mole](https://kunjgit.github.io/GameZone/Games/Whack_a_Mole)
- start playing 
-  click on `start new game` after few seconds

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @programerr01 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hello @programerr01, Time's Uppp!⏰ 
 Sorry for closing your issue! 
 But it's more than a week since we haven't received anything from your side 😢 . 
 Come up with new ideas, create a new issue and make sure you finish it within a week! 🔥 
 All the best! 🚀 
 Happy Hacking! 💗

**Comment by kunjgit** [comment]
Hey @programerr01 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
