### ISSUE TITLE
[New game]: Blast Zone

### ISSUE THREAD

**Issue by rt-001** [kunjgit/GameZone#586]
### 🎮 Game Request

Game logic and basic description
The game is called Blast Zone. It is a simple 2D game where the player controls a rectangular shape and shoots bullets to destroy enemy shapes. 

1. The player controls the rectangular shape using the Left and Right arrow keys or the A and D keys to move horizontally.
2. The player can shoot bullets by pressing the Spacebar key.
3. Enemies, represented by other rectangular shapes, move horizontally across the screen.
4. The player's goal is to shoot and destroy the enemies before they reach the player's position.
5. If an enemy bullet collides with the player, the player loses a life. The player starts with a certain number of lives.
6. The game ends when the player loses all lives.
7. The player's score increases for each enemy destroyed.

### Point down the features

Game points

1. Game Objective: The objective of the game is to control a player character and destroy enemy units while avoiding their bullets. The player aims to achieve the highest score possible.

2. Controls: The player can use either the left and right arrow keys or the A and D keys to move the player character horizontally. The spacebar is used to shoot bullets.

3. Enemies and Bullets: The game features various enemy units that move horizontally across the screen and shoot bullets at the player. The player needs to dodge enemy bullets while strategically shooting them down.

4. Player Character: The player controls a character capable of shooting bullets to destroy enemies. The character can move left and right to avoid enemy attacks.

5. Score: The game keeps track of the player's score, which increases as the player destroys enemies. The score serves as a measure of the player's performance in the game.

6. Lives: The player starts the game with a certain number of lives (typically three). Each time the player is hit by an enemy bullet, they lose a life. If the player loses all their lives, the game is over.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @rt-001 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hello @rt-001, Time's Uppp!⏰ 
 Sorry for closing your issue! 
 But it's more than a week since we haven't received anything from your side 😢 . 
 Come up with new ideas, create a new issue and make sure you finish it within a week! 🔥 
 All the best! 🚀 
 Happy Hacking! 💗

**Comment by kunjgit** [comment]
Hey @rt-001 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
