### ISSUE TITLE
[New game]: Flames Game

### ISSUE THREAD

**Issue by Uglycrown** [kunjgit/GameZone#588]
### 🎮 Game Request

Game logic and basic description

The Flames Game is a popular and fun game that reveals the relationship between two individuals. The game uses the acronym "FLAMES" to determine the connection or compatibility between two people based on their names.

Here's how the game works:

1. Input: The players are required to enter their names (Name 1 and Name 2) into the provided input fields.

2. Name Preparation: The entered names are converted to lowercase and any spaces are removed. This ensures consistency during the comparison process.

3. Letter Comparison: The game compares each letter in Name 1 with the letters in Name 2. Common letters between the two names are eliminated until only distinct letters remain.

4. Count Calculation: The total count of the remaining letters (after elimination) is calculated.

5. Relationship Determination: The relationship between the two individuals is determined using the "FLAMES" acronym:
          . F (Friendship): If the count is divisible by 6, it means there is a friendship connection between the individuals.
 . L (Love): If the count is divisible by 5, it means there is a romantic or love connection.
 . A (Affection): If the count is divisible by 4, it signifies an affectionate bond.
 . M (Marriage): If the count is divisible by 3, it indicates a potential for marriage or a lifelong commitment.
 . E (Enemies): If the count is divisible by 2, it signifies a relationship of enmity or incompatibility.
 . S (Sibling): If none of the above conditions apply, it means the individuals share a sibling or familial bond.

6. Result Display: The game displays the determined relationship between the two individuals based on the outcome of the FLAMES calculation.

### Point down the features

Game points

1. Input Names: Players can enter their names in the input fields provided. This allows for customization and personalization of the game experience.

2. Dynamic Name Processing: The game processes the entered names by converting them to lowercase and removing any spaces or special characters. This ensures consistency and accuracy during the comparison process.

3. Letter Comparison: The game compares each letter in Name 1 with the letters in Name 2. This comparison identifies the common letters between the two names.

4. Letter Elimination: The game eliminates the common letters from both names, leaving only the distinct letters. This step helps in calculating the remaining count.

5. Relationship Calculation: The game calculates the total count of the remaining letters and uses it to determine the relationship between the two individuals using the "FLAMES" acronym.

6. Result Display: The game displays the determined relationship between the two individuals based on the outcome of the FLAMES calculation. The result is shown to the players, providing them with an entertaining and often surprising revelation.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Uglycrown ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @singhapeksha ! , This issue is already assigned to @Uglycrown. 💗 
 You can work on other issues 🚀 
 If there is anything wrong you can contact us on [Discord🕹️](https://discord.gg/fgwk4XZfxG)👀

**Comment by kunjgit** [comment]
Hello @Uglycrown, Time's Uppp!⏰ 
 Sorry for closing your issue! 
 But it's more than a week since we haven't received anything from your side 😢 . 
 Come up with new ideas, create a new issue and make sure you finish it within a week! 🔥 
 All the best! 🚀 
 Happy Hacking! 💗

**Comment by kunjgit** [comment]
Hey @Uglycrown ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
