### ISSUE TITLE
[New game]: Bullseye Game

### ISSUE THREAD

**Issue by rt-001** [kunjgit/GameZone#589]
### 🎮 Game Request

Game logic and basic description

The provided code creates an interactive game where players can aim and launch an arrow toward a target using mouse input. The game interface will include visual components such as paths, gradients, and other elements that make up the game's graphics. Through mouse events, players can draw back the arrow, adjust its aim, and release it to launch toward the target. The code also includes functions for hit testing to determine if the arrow hits the target and displays corresponding messages based on the outcome (hit, bullseye, or miss).

### Point down the features

Game points

1. Gameplay: The player can drag back an arrow by clicking and holding the mouse button. The arrow is aimed by moving the mouse cursor. Releasing the mouse button launches the arrow towards the target.
2. Target: The target consists of concentric circles colored in shades of white and orange. The orange center represents the bullseye, while the white circles represent the outer rings.
3. Bow: The bow is represented by a line with an arrowhead. It rotates and scales based on the player's aim and the distance of the arrow pull.
4. Arrow: The arrow is represented by a line with an arrowhead. It is pulled back by the player and released towards the target.
5. Results: Depending on the accuracy of the shot, different messages are displayed. If the arrow hits the bullseye, a "Bullseye" message is shown. If the arrow hits the target but not the bullseye, a "Hit" message is shown. If the arrow misses the target, a "Miss" message is shown.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @rt-001 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hello @rt-001, Time's Uppp!⏰ 
 Sorry for closing your issue! 
 But it's more than a week since we haven't received anything from your side 😢 . 
 Come up with new ideas, create a new issue and make sure you finish it within a week! 🔥 
 All the best! 🚀 
 Happy Hacking! 💗

**Comment by kunjgit** [comment]
Hey @rt-001 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
