### ISSUE TITLE
[New game]:  Quiz Game

### ISSUE THREAD

**Issue by SnigdhaP2022** [kunjgit/GameZone#595]
### 🎮 Game Request

Game logic and basic description
This Quiz Game is designed with some questions which help in learning HTML, CSS and many things about web developing. In order to answer the question, we will have a stipulated time frame and will be given points according to correctly answered questions.

### Point down the features

Game points
It starts with Clicking the Start Quiz button.
I have included 5 Questions, with a time frame of 15sec to answer each question. It gives +1 for every correct answer and 0 for the wrong answer.
In end the it shows the points secured along with Replay and Quit Buttons.

![Quiz game](https://github.com/kunjgit/GameZone/assets/102572480/41948f02-39a9-4575-87c4-d498b3eb43c8)

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @SnigdhaP2022 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)
