### ISSUE TITLE
[New game]: Dino Runner

### ISSUE THREAD

**Issue by Atharva-3000** [kunjgit/GameZone#6]
### 🎮 Game Request

Game logic and basic description:
This game is made with the use of HTML, CSS, and vanilla JS, it's a very easy game with a dino as your character and your aim is to jump over the enemy, this game has engaging sound to make it funny and a score tracker. This app is good for beginner.

### Point down the features

Game points:
Score tracker
Easy to play
Intuitive sounds
Engaging graphics.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey  @Atharva-3000 ! Thank you for raising an issue 💗 You have been assigned this issue you can start working on the issue 🎮

**Comment by Atharva-3000** [comment]
I've successfully made a PR, can you please review it once?

**Comment by kunjgit** [comment]
Hey @Atharva-3000 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
