### ISSUE TITLE
[New game]: Snake and Ladder game

### ISSUE THREAD

**Issue by sujanrupu** [kunjgit/GameZone#60]
### 🎮 Game Request

I would like to add the **snake and ladder game** in this repository. I will use **HTML, CSS, JavaScript** for the game, It will be a pre frontend game. This game will consist of several features, all of which are similar with real life snake ladder game. The UI of this game is quite beautiful.

### Point down the features

**Features of the game:**

1. User can select who will first roll the dice, the user or the computer.
2. User can select an avatar.
3. Dice movement of both the user and computer at every step will be visible to the user.
4. All the features of real life game is present here also, such as **ladder, snake and additional points**.
5. User can see the movement of his/her avatar and avatar of computer after rolling of dice at each step.
6. A congratulations message will be displayed after the winning of the user.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by sujanrupu** [comment]
Please assign me this task for GSSOC 2023

**Comment by kunjgit** [comment]
Hey  @sujanrupu ! Thank you for raising an issue 💗 You have been assigned this issue you can start working on the issue 🎮

**Comment by kunjgit** [comment]
Hey @sujanrupu ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
