### ISSUE TITLE
[New game]: TOWER BLOCKS 🚀

### ISSUE THREAD

**Issue by 0xabdulkhalid** [kunjgit/GameZone#601]
### 🎮 Game Request

Game logic and basic description
- Tower Blocks is a simple yet addictive game where you have to stack blocks to build the tallest tower possible.

- To play Tower Blocks, simply tap on the screen to drop a block. The blocks will fall straight down, so you need to be careful not to let them hit the ground or other blocks. As you stack more blocks, the tower will become more unstable, so you need to be strategic about where you place each block.

- The goal of the game is to build the tallest tower possible. The game ends when the tower falls over. You can earn points for each block that you stack, and your score will be displayed at the end of the game.

### Point down the features

Game points

- Simple and addictive gameplay: Tower Blocks is a simple game to learn, but it can be challenging to master. The gameplay is addictive and will keep you coming back for more.

- Variety of levels: There are a variety of levels to play, each with its own unique challenges. This keeps the game fresh and prevents it from becoming repetitive.

- Free to play and fully Offline: Tower Blocks is a free game, so you can try it out without any risk.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @0xabdulkhalid ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @0xabdulkhalid! 
We are already having a similar game request in #481 👀 
Make sure you come up with a cool unique idea 😀 
 Waiting for your new game idea 💗.

**Comment by kunjgit** [comment]
Hey @0xabdulkhalid ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by 0xabdulkhalid** [comment]
Thanks for pointing this out!, sure i have other games let me raise an issue for them.
