### ISSUE TITLE
[Bug]: The website has a very plane background which can be made interesting. [GSSoC'23]

### ISSUE THREAD

**Issue by 1Shubham7** [kunjgit/GameZone#602]
### Give a brief about the bug ✍️

The website has a very plane background which can be made interesting. A better background. with some gradient in it will make it more fun and interesting.

Here is one sample : 
![homepage for issue](https://github.com/kunjgit/GameZone/assets/116020663/13725017-5ce9-404d-a14e-4b80f52a1c27)

We can add such gradients to give a more fun look to the website.

### What is the expected behavior? 🤔

A better background. with some gradient in it will make it more fun and interesting.

### Provide step by step information reproduce the bug 📄

I will design a new backgroung through figma and add it to the website

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @1Shubham7 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by 1Shubham7** [comment]
@kunjgit If you are not accepting the PR, shall I close the issue. Here are some more gradients : 
![GRADIENTS](https://github.com/kunjgit/GameZone/assets/116020663/33dacd09-9345-4f46-8570-32bdff4cf8c5)

I even created Dark Black gradients that match the current background:
![black bradients](https://github.com/kunjgit/GameZone/assets/116020663/2d1faf28-183b-438c-8e84-c8520e5baf6c)

Please try them, trust me they will look good.
Or else do inform me if I should close this issue.

**Comment by kunjgit** [comment]
Hello @1Shubham7, Time's Uppp!⏰ 
 Sorry for closing your issue! 
 But it's more than a week since we haven't received anything from your side 😢 . 
 Come up with new ideas, create a new issue and make sure you finish it within a week! 🔥 
 All the best! 🚀 
 Happy Hacking! 💗

**Comment by kunjgit** [comment]
Hey @1Shubham7 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by 1Shubham7** [comment]
seriously @kunjgit , you didn't reply me for a week about which gradient should I proceed with. But no worries, thank you for having me.
