### ISSUE TITLE
[New game]: UNTRULY TOWER 🚀

### ISSUE THREAD

**Issue by 0xabdulkhalid** [kunjgit/GameZone#604]
### 🎮 Game Request

Game logic and basic description
- This game is about traversing the tower from bottom to top with left, right and spacebar(jump) keys
- It's quite addictive to play
- This games look will so much close to retro games

### Point down the features

Game points
- We can get points for passing every footstep

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @0xabdulkhalid ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by 0xabdulkhalid** [comment]
> /assign

Bro, who are you ?

**Comment by kunjgit** [comment]
Hey @0xabdulkhalid ! , This issue is already assigned to @rt-001. 💗 
 You can work on other issues 🚀 
 If there is anything wrong you can contact us on [Discord🕹️](https://discord.gg/fgwk4XZfxG)👀

**Comment by kunjgit** [comment]
Hey @0xabdulkhalid ! , This issue is already assigned to @rt-001. 💗 
 You can work on other issues 🚀 
 If there is anything wrong you can contact us on [Discord🕹️](https://discord.gg/fgwk4XZfxG)👀

**Comment by 0xabdulkhalid** [comment]
Brother @rt-001 please don't interfere on other's issue, please try to create your own

**Comment by 0xabdulkhalid** [comment]
> /assign

It's totally illegel, i created this issue and made a PR though. Please create your own & unassign yourself from this issue.

You're not following Contributing Guidelines

**Comment by kunjgit** [comment]
Hey @0xabdulkhalid ! , This issue is already assigned to @rt-001. 💗 
 You can work on other issues 🚀 
 If there is anything wrong you can contact us on [Discord🕹️](https://discord.gg/fgwk4XZfxG)👀

**Comment by rt-001** [comment]
@0xabdulkhalid, I am unassigning it.
I thought you weren't interested.

**Comment by rt-001** [comment]
@0xabdulkhalid u can assign it now.

**Comment by kunjgit** [comment]
@rt-001 Hope you will not misuse it again 👀 !!!

**Comment by kunjgit** [comment]
Hey @0xabdulkhalid ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
