### ISSUE TITLE
[Documentation Bug]: Fix Text in README

### ISSUE THREAD

**Issue by Sriparno08** [kunjgit/GameZone#607]
### Describe the bug ✍️

This sentence in README:

> This open source repository contains collection of games build on basic tech stacks in web development . Use your creativity and build your own game and contribute to the repository by making PR

can be changed to:

> This open source repository contains a collection of games built on basic tech stacks in web development. Use your creativity, build your own game and contribute to the repository by making a PR

### Provide step by step information reproduce the bug 📄

1. Go to README
2. Find the sentence

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Sriparno08 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
