### ISSUE TITLE
[New game]: Guess the brand 

### ISSUE THREAD

**Issue by whiteknight16** [kunjgit/GameZone#609]
### 🎮 Game Request

A brand logo will appear and you will have to choose the correct name of brand. you will be socred for each correct guess and a high score too

### Point down the features

- Made with HTML CSS and JS
- Hi Socre feature
- Several brands 

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hello @whiteknight16, Time's Uppp!⏰ 
 Sorry for closing your issue! 
 But it's more than a week since we haven't received anything from your side 😢 . 
 Come up with new ideas, create a new issue and make sure you finish it within a week! 🔥 
 All the best! 🚀 
 Happy Hacking! 💗

**Comment by kunjgit** [comment]
Hey @whiteknight16 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
