### ISSUE TITLE
[Enhancement]: Add timer in Master_Typing and after that give a assesment.

### ISSUE THREAD

**Issue by samratghosh291** [kunjgit/GameZone#61]
### Is your enhancement request related to a problem? Please describe.➕

Game enhancement
Add a start and a restart button for starting and Restarting the game. 
Add a timer to assess the user's accuracy.
 

### Describe the solution you'd like

Solution steps

- Create a Start Button and a restart button.
- Start Timer for 1 min(default)  using addEventListner().
- During typing calculate the wrong and right entry.
- Calculate Percentage.
- Display Assessment.

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @samratghosh291  ! Thank you for raising an issue 💗 You have been assigned this issue you can start working on the issue 🎮

**Comment by samratghosh291** [comment]
Okay, Thank You 😃

**Comment by samratghosh291** [comment]
@kunjgit I have my end sem from 1 to 15th of June. So, I will be active before that. Consider me those days.

**Comment by samratghosh291** [comment]
@kunjgit please add a level tag with it.

**Comment by kunjgit** [comment]
Hey @samratghosh291 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
