### ISSUE TITLE
adding responsiveness to search bar

### ISSUE THREAD

**Issue by gaur15** [kunjgit/GameZone#617]
### Is your enhancement request related to a problem? Please describe.➕

adding responsiveness to search  bar will increase user experience with the site

### Describe the solution you'd like

i would like to add responsive code to the site by using javascript 

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @gaur15 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @gaur15! 🙂 
 It seems like you are not following proper guidelines !! 👀 
 Read documentation properly !!🙏 
 If you have any queries reach out to us on [Discord🕹️](https://discord.gg/fgwk4XZfxG) .

**Comment by kunjgit** [comment]
Hey @gaur15 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by gaur15** [comment]
> Hey @gaur15! 🙂 It seems like you are not following proper guidelines !! 👀 Read documentation properly !!🙏 If you have any queries reach out to us on [Discord🕹️](https://discord.gg/fgwk4XZfxG) .

sorry Sir I was that issue was merged so I raised this one . sorry for in convenience
