### ISSUE TITLE
changing the background css and text in snake game

### ISSUE THREAD

**Issue by charan-1303** [kunjgit/GameZone#618]
### Is your enhancement request related to a problem? Please describe.➕

hey @kunjgit  please assign me this so that I can work on this issue.
here in this snake game actually the css is very poor and i want to improve the background css and also the text which is used in this game . by changing this chnages it iwll give the user a better experiance and so that it becomes a user friendly game while palying. 
![Screenshot (91)](https://github.com/kunjgit/GameZone/assets/131485387/d2638d84-a60d-4282-9b4c-a2e7028222ab)

### Describe the solution you'd like

at first I start with background and i ll make changes so that it looks better and by making the the changes in text also using css and i will make sure that both the background and text will be in same theme.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @charan-1303 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @charan-1303! 🙂 
 It seems like you are not following proper guidelines !! 👀 
 Read documentation properly !!🙏 
 If you have any queries reach out to us on [Discord🕹️](https://discord.gg/fgwk4XZfxG) .

**Comment by kunjgit** [comment]
Hey @charan-1303 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
