### ISSUE TITLE
[New game]: Remember Last Colour

### ISSUE THREAD

**Issue by NikhilCode12** [kunjgit/GameZone#622]
### 🎮 Game Request

Game logic and basic description

This is a game made with Javascript and JQuery. Firstly, it lets the user choose the color with the sound associated with the color. User can select the color which made the sound and then game starts, if the user breaks the sequence (selecting wrong color or forgets the previous sequence) it will be game over!! It also takes the level count of the user. Level of the user is shown on the h1 element of the html page.

### Point down the features

Game points

- Shows level of the user
- Makes different sounds at different colors
- Creates a warning sound if the game ends or user chooses different sequence of color (red background)
- Fun to play
- Fully Responsive to play 
- Mouse movements are tracked to count the level

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @NikhilCode12 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by NikhilCode12** [comment]
I have made a PR to the #622 issue. It was fun contributing to the GameZone

**Comment by kunjgit** [comment]
Hello @NikhilCode12, Time's Uppp!⏰ 
 Sorry for closing your issue! 
 But it's more than a week since we haven't received anything from your side 😢 . 
 Come up with new ideas, create a new issue and make sure you finish it within a week! 🔥 
 All the best! 🚀 
 Happy Hacking! 💗

**Comment by kunjgit** [comment]
Hey @NikhilCode12 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
