### ISSUE TITLE
[Enhancement]: Guess_The_Number

### ISSUE THREAD

**Issue by rishiofficial** [kunjgit/GameZone#626]
### Is your enhancement request related to a problem? Please describe.➕

Title: Allowing Button Click Event Triggered by Both Mouse Click and Keyboard Enter

I would like to request an enhancement for the current functionality of the button click event to be triggered not only by a mouse click but also by pressing the Enter key on the keyboard. This enhancement aims to provide a more inclusive and user-friendly experience by allowing users to interact with the button using both mouse and keyboard.

### Describe the solution you'd like

Currently, the button click event is only triggered when the user clicks on the button using the mouse. With this enhancement, we propose adding support for triggering the button click event when the user presses the Enter key while the button is in focus.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @rishiofficial ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @rishiofficial ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
