### ISSUE TITLE
[New game]Breakout Game 

### ISSUE THREAD

**Issue by Sreenija03** [kunjgit/GameZone#635]
### 🎮 Game Request

This game is to break all the the boxes using a ball by bouncing it off a sliding bar which will  be constantly moving under the blocks

### Point down the features

This game will be developed using javascript and it will have a score counter displayed on the top

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hello @Sreenija03, Time's Uppp!⏰ 
 Sorry for closing your issue! 
 But it's more than a week since we haven't received anything from your side 😢 . 
 Come up with new ideas, create a new issue and make sure you finish it within a week! 🔥 
 All the best! 🚀 
 Happy Hacking! 💗

**Comment by kunjgit** [comment]
Hey @Sreenija03 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
