### ISSUE TITLE
[New game]: emoji catcher game

### ISSUE THREAD

**Issue by S-ishita** [kunjgit/GameZone#638]
### 🎮 Game Request

All you need to do is catch the emoji within the time of 60 secs

### Point down the features

Your score increases as you catch an emoji

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @S-ishita ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @S-ishita! 
We are already having a similar game request in #529 👀 
Make sure you come up with a cool unique idea 😀 
 Waiting for your new game idea 💗.
