### ISSUE TITLE
2 Player Ball Game - Desktop Application { Java }

### ISSUE THREAD

**Issue by neel13062003** [kunjgit/GameZone#64]
### 🎮 Game Request

I would like to add a two-player ball game to this repository. I will use Java to make this game, It will be a pre-frontend game. This game will consist of several features, all of us might enjoy while playing this game. The UI of this game is quite beautiful.

### Point down the features

2 Players can play game 
One player plays with keyboad - { W , S  } & another plays with  { Up, Down arrows key }
I will host this game live now = https://2-player-ball-game-neelsoni.netlify.app/  you can watch it.

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @neel13062003 ! 
I found the game really interesting but as we are having games live on our website it would be great if you are able to do the same with the tech stacks we are having !! 
Thank you for raising an issue 💗

**Comment by Lavesh12** [comment]
Hello,
I hope you're doing well. I am interested in contributing to this project as part of GSSoC. It aligns with my skills and interests, and I believe I can make a meaningful contribution to the project Could you please assign this task to me? 
Looking forward to hearing from you.
Thank you,
Lavesh Vishwakarma

**Comment by kunjgit** [comment]
Hello @neel13062003, Time's Uppp!⏰ 
 Sorry for closing your issue! 
 But it's more than a week since we haven't received anything from your side 😢 . 
 Come up with new ideas, create a new issue and make sure you finish it within a week! 🔥 
 All the best! 🚀 
 Happy Hacking! 💗

**Comment by kunjgit** [comment]
Hey @neel13062003 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
