### ISSUE TITLE
[New game]:  Avax Gods

### ISSUE THREAD

**Issue by Google-Ka-Dinosaur** [kunjgit/GameZone#641]
### 🎮 Game Request

A basic NFT battlecard game using web3 technology and blockchain
![Screenshot (194)](https://github.com/kunjgit/GameZone/assets/98577878/3cea4931-7d3f-47e3-984e-019eea63e62c)

### Point down the features

great UI/UX
Easy to play
Based on blockchain.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Google-Ka-Dinosaur ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
