### ISSUE TITLE
[Bug]: Adding a custom error page

### ISSUE THREAD

**Issue by Google-Ka-Dinosaur** [kunjgit/GameZone#642]
### Give a brief about the bug ✍️

![Screenshot (199)](https://github.com/kunjgit/GameZone/assets/98577878/2d6d9a75-7825-4aba-9118-619d281281ce)

### What is the expected behavior? 🤔

The error page is just the default one that appears on typing incorrect url. A custom error page could be better and much more appealing.

### Provide step by step information reproduce the bug 📄

 I would like to make a custom error page which matches with the theme.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Google-Ka-Dinosaur ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @Google-Ka-Dinosaur ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
