### ISSUE TITLE
[New game]: Martian Crash

### ISSUE THREAD

**Issue by ainaagnihotri** [kunjgit/GameZone#645]
### 🎮 Game Request

The spacecraft was heading towards the Mars but due to some technical issues ,engine failure and also outer space particles    and also space creatures blocking its way it is losing its balance.  The space craft has to maintain its balance and protect itself from the space creatures and outer space particles and finally reach to the  Mars.

### Point down the features

*Game points it will have
*Through out the game there will be space -BGM
*When it will reach the Mars ,victory BGM

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hello @ainaagnihotri, Time's Uppp!⏰ 
 Sorry for closing your issue! 
 But it's more than a week since we haven't received anything from your side 😢 . 
 Come up with new ideas, create a new issue and make sure you finish it within a week! 🔥 
 All the best! 🚀 
 Happy Hacking! 💗

**Comment by kunjgit** [comment]
Hey @ainaagnihotri ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
