### ISSUE TITLE
[New game]: Add Whack-a-mole 

### ISSUE THREAD

**Issue by amelia2802** [kunjgit/GameZone#65]
### 🎮 Game Request

Game logic and basic description
The player has to strike the mole when it's visible on the screen. If they do not strike the mole within a certain time or with enough force, it eventually sinks back into its hole with no score. After a designated time limit, the game ends, regardless of the player's score. The final score is based on the number of moles the player struck.

### Point down the features

Game points

The game is built with javascript which includes two displays for the time left, the player's Score.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @amelia2802 ! we are already having it on #20 !
