### ISSUE TITLE
[New game]: Drum Game

### ISSUE THREAD

**Issue by shivamsisodia07** [kunjgit/GameZone#651]
### 🎮 Game Request

A drum kit game using JavaScript is a game that allows the user to play a drum kit using their keyboard. The game is created using HTML, CSS, and JavaScript. 

### Point down the features

1. **A variety of drum sounds**: The drum kit should be able to produce a variety of drum sounds, such as snare drums, bass drums, cymbals, and toms.

2. **Customization:** The user should be able to customize the drum kit to their liking, such as choosing the different drum sounds and the layout of the kit.

3. **Easy to use:** The drum kit should be easy to use, even for beginners. The user should be able to start playing right away without having to learn a lot of complicated controls.
Responsive: The drum kit should be responsive to the user's input. The user should be able to play the drums smoothly and without any lag.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @shivamsisodia07 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hello @shivamsisodia07, Time's Uppp!⏰ 
 Sorry for closing your issue! 
 But it's more than a week since we haven't received anything from your side 😢 . 
 Come up with new ideas, create a new issue and make sure you finish it within a week! 🔥 
 All the best! 🚀 
 Happy Hacking! 💗

**Comment by kunjgit** [comment]
Hey @shivamsisodia07 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
