### ISSUE TITLE
[New game]: snake-water-gun

### ISSUE THREAD

**Issue by nitinramjas8742** [kunjgit/GameZone#652]
### 🎮 Game Request

It is a popular game that is played by children and adults all over the world. The game is simple to learn but can be challenging to master.

To play Snake Water Gun, you will need two or more players. Each player will choose one of the three objects: snake, water, or gun. The players will then simultaneously make their gestures.

The winner of each round is determined by the following rules:

Snake beats water (the snake drinks the water).
Water beats gun (the gun drowns in the water).
Gun beats snake (the gun shoots the snake).
If both players make the same gesture, the round is a tie.

The game is played until there is only one player left. The player who is left standing is the winner.

### Point down the features

Game points
Multiplayer mode or bi-player mode
Tournament
Round system(league and knockout)
statistics
rewards and penalties

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @nitinramjas8742 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hello @nitinramjas8742, Time's Uppp!⏰ 
 Sorry for closing your issue! 
 But it's more than a week since we haven't received anything from your side 😢 . 
 Come up with new ideas, create a new issue and make sure you finish it within a week! 🔥 
 All the best! 🚀 
 Happy Hacking! 💗
