### ISSUE TITLE
[New game]: Multiplayer Chess

### ISSUE THREAD

**Issue by Vidhi-44** [kunjgit/GameZone#66]
### 🎮 Game Request

I would like to add Chess Game using HTML, CSS and Javascript . The UI will be simple and great of this game . IT would be fun in playing.

### Point down the features

 Some Features that I would like to add is .

* Player can select the choice of color .
* The pawns and the other chess pieces would also be attractive .
* Player can retake its chance once again.
* There would be a congratulations message at the end of the game .
* Would be simple but nice to play.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Vidhi-44 ! we are already having it on #42 !!
Thank you for raising issue 💗
