### ISSUE TITLE
[Question]: Can I Add FAQ'S in GameZone using  bootstrap?

### ISSUE THREAD

**Issue by Dimple-Choudhary** [kunjgit/GameZone#662]
### Description
I have created an issue in the "Question or support request" because I am not sure whether we can add other features to the website GameZone,_if we can I would Like to create FAQ section using Bootstrap below are few questions examples:_

1. What is GameZone?
2. Is GameZone really free to play?
3. Can I submit my own game to GameZone?
4. Are there any multiplayer games available on GameZone?

@kunjgit,If you would like FAQs in GameZone  assign me this issue under GSSoC'23.

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Dimple-Choudhary ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by Dimple-Choudhary** [comment]
Hey! @kunjgit 
I want to discuss the questions and answers to be added in FAQ , below are 5 questions and they answers if you would Like to  add more or change  any of them Let me Know :)
```
1) What is GameZone?
=>🕹️ GameZone is an open-source website that offers a collection of free-to-play games. 🌐🎮
It serves as a platform where game enthusiasts and developers can come together to contribute, collaborate, and share their games with the community. 👥🚀
2)  Is GameZone really free to play?
=> Yes! GameZone is completely free to play. 🆓🎮
          All the games available on the website can be accessed and enjoyed without any cost.
3) How can I contribute to GameZone?
=> Build and contribute games on GitHub. 
          PRs welcome! Star the repo, join Discord for collaboration. 
          Let's create together! 🎮💗🚀
4)     Can I submit my own game to GameZone?
=>  Yes, you can submit your own games to GameZone! It's an open-source project on GitHub. 🎮🎁
5)Can I play games on GameZone on my mobile device?
=>    Yes, you can play games on GameZone on your mobile device. 📱🎮
```
Also, I am not sure about 5 answer

**Comment by kunjgit** [comment]
Hey @Dimple-Choudhary ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
