### ISSUE TITLE
[New game]: Connect Four

### ISSUE THREAD

**Issue by kalashvasaniya** [kunjgit/GameZone#665]
### 🎮 Game Request

Game logic and basic description

### Point down the features

 It's a classic two-player strategy game where the goal is to be the first to connect four of your colored discs in a row, either vertically, horizontally, or diagonally on a grid.

### Select program in which you are contributing

Javascript

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @kalashvasaniya ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)
