### ISSUE TITLE
[New game]: Bingo

### ISSUE THREAD

**Issue by singh-anushka** [kunjgit/GameZone#667]
### 🎮 Game Request

Game logic and basic description

- This is game is go for any number for players.
- There are 25 numbers will keep in the game.
- In one move, one player tell which number will he/she want to cut, that number will also be cut down by each and every member of the game.

### Point down the features

Game points

1. In this game, Winner will decide when the winner one will cut the all the letters of the "BINGO".

2. Letter of the BINGO can be cut when a straight line passing through those 5 numbers which are cut marked by the members.

3. One cut mark number can also be part of the other straight line.

4. This game will give user a best experience.

5. Result will be declared and stored for each and every rounds till the user is playing the game on the website.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @singh-anushka ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hello @singh-anushka, Time's Uppp!⏰ 
 Sorry for closing your issue! 
 But it's more than a week since we haven't received anything from your side 😢 . 
 Come up with new ideas, create a new issue and make sure you finish it within a week! 🔥 
 All the best! 🚀 
 Happy Hacking! 💗

**Comment by kunjgit** [comment]
Hey @singh-anushka ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
