### ISSUE TITLE
[New game]: Puzzle Game

### ISSUE THREAD

**Issue by SJ-Kumar** [kunjgit/GameZone#669]
### 🎮 Game Request

The game logic of the puzzle game involves dragging and dropping puzzle pieces to solve the puzzle.

### Point down the features

Game Board:
The game board is a 5x5 grid represented by the <div> element with the id "board".
Each cell of the grid contains an <img> element with a blank image initially.

Puzzle Pieces:
The puzzle pieces are represented by the <img> elements within the <div> element with the id "pieces".
Each puzzle piece is randomly assigned an image from a set of puzzle images.
The puzzle pieces are draggable, and dragging is enabled using event listeners.

Drag and Drop Functionality:
When a puzzle piece is dragged (dragstart event), the reference to the dragged tile is stored in the currTile variable.
The dragover event is handled to prevent the default behavior.
The dragenter and dragleave events are used to provide visual feedback when dragging a puzzle piece over another.
When a puzzle piece is dropped onto another (drop event), the reference to the target tile is stored in the otherTile variable.
The dragend event is triggered after the drop is completed, and the puzzle pieces' images are swapped.
The turn count is incremented, and the updated turn count is displayed on the page.

Puzzle Generation:
The puzzle pieces are generated randomly by shuffling an array of puzzle image names.
The shuffled array is used to assign images to the puzzle pieces.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @SJ-Kumar ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @SJ-Kumar! 
We are already having a similar game request in #579 👀 
Make sure you come up with a cool unique idea 😀 
 Waiting for your new game idea 💗.

**Comment by kunjgit** [comment]
Hey @SJ-Kumar ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
