### ISSUE TITLE
[New game]: 🐷 The Pig Game: A Beautifully Designed 2-Player Adventure! 🎮

### ISSUE THREAD

**Issue by PrateekPsingh** [kunjgit/GameZone#67]
### 🎮 Game Request

Game logic and basic description: Pig game is a classic dice game that has been enjoyed for decades. Players take turns rolling a single die, trying to accumulate points by adding their roll results to a running total. However, rolling a 1 wipes out all the points gained in that turn. It's a game of risk and strategy, where players must decide when to push their luck and when to play it safe. With various rule variations and commercial adaptations, Pig offers endless fun and can even be used by teachers to teach probability concepts. For the implementation of the Pig game, I will be utilizing HTML, CSS, and JavaScript.

### Point down the features

Game points:

In the Pig game, players accumulate points as they take turns rolling a single die. The points are added to a running total, and the objective is to reach a predetermined target score (often 100) to win the game. However, there are specific rules regarding point accumulation in the game:

Rolling a 1: If a player rolls a 1, they lose all the points accumulated in that turn, and their turn ends. The accumulated points are not added to their overall score.

Rolling a 2-6: If a player rolls a number between 2 and 6 (inclusive), they can choose to either continue rolling the die to accumulate more points or end their turn and add the accumulated points to their overall score.

Choosing to End Turn: If a player decides to end their turn voluntarily (without rolling a 1), the accumulated points from that turn are added to their overall score.

Winning the Game: The first player to reach or exceed the target score (e.g., 100 points) wins the game.

In addition to the core gameplay mechanics, it also contains a "New Game" button that offers players the ability to reset the entire game to its initial state

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by Aditi323** [comment]
Please assign this to me as a GSSOC contibutor.

**Comment by kunjgit** [comment]
Hey  @PrateekPsingh ! Thank you for raising an issue 💗 You have been assigned this issue you can start working on the issue 🎮

**Comment by kunjgit** [comment]
Hello @PrateekPsingh, Time's Uppp!⏰ 
 Sorry for closing your issue! 
 But it's more than a week since we haven't received anything from your side 😢 . 
 Come up with new ideas, create a new issue and make sure you finish it within a week! 🔥 
 All the best! 🚀 
 Happy Hacking! 💗

**Comment by kunjgit** [comment]
Hey @PrateekPsingh ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
