### ISSUE TITLE
[New game]: Reaction Time Tester

### ISSUE THREAD

**Issue by SJ-Kumar** [kunjgit/GameZone#670]
### 🎮 Game Request

The game logic is as follows:

1. When the "Start" button is clicked, the red box appears, and a random time delay is set.
2. After the delay, the red box changes to green, indicating the player should tap on it as quickly as possible. The reaction time is calculated and displayed.

### Point down the features

User-friendly interface: The game has a clear and intuitive interface with instructions provided.
Reaction time measurement: The game accurately measures the player's reaction time based on their click/tap on the target.
Randomized timing: The delay before the target changes color is randomized, adding unpredictability and challenge to the game.
Visual feedback: The game provides visual feedback with color changes and messages to guide the player throughout the gameplay.
Score display: The player's reaction time score is displayed in seconds, allowing them to track and compare their performance.
Restart functionality: The game can be restarted by clicking the "Start" button again, allowing for multiple attempts and improvement of reaction time.
Responsive design: The game is designed to be responsive and adaptable to different screen sizes and devices.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @SJ-Kumar ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hello @SJ-Kumar, Time's Uppp!⏰ 
 Sorry for closing your issue! 
 But it's more than a week since we haven't received anything from your side 😢 . 
 Come up with new ideas, create a new issue and make sure you finish it within a week! 🔥 
 All the best! 🚀 
 Happy Hacking! 💗

**Comment by kunjgit** [comment]
Hey @SJ-Kumar ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
