### ISSUE TITLE
[New game]: Jump and Run Game 

### ISSUE THREAD

**Issue by Vidhi-44** [kunjgit/GameZone#68]
### 🎮 Game Request

The Jump and run game will be a fun game . There may be object and there would be hurdles for which it has to Jump the hurdles and run it from  there . It will be coded using HTML, CSS and Javascript .

### Point down the features

Game points : 

* Simple but attractive UI .
*  Good color combination .
*  After every hurdle crossed some points will be added .
*  A Congratulation message in the end.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey  @Vidhi-44  ! Thank you for raising an issue 💗 You have been assigned this issue you can start working on the issue 🎮

**Comment by Vidhi-44** [comment]
> Hey @Vidhi-44 ! Thank you for raising an issue 💗 You have been assigned this issue you can start working on the issue 🎮

Yess ! I will do this .. Thankyou !

**Comment by kunjgit** [comment]
Hello @Vidhi-44, Time's Uppp!⏰ 
 Sorry for closing your issue! 
 But it's more than a week since we haven't received anything from your side 😢 . 
 Come up with new ideas, create a new issue and make sure you finish it within a week! 🔥 
 All the best! 🚀 
 Happy Hacking! 💗

**Comment by kunjgit** [comment]
Hey @Vidhi-44 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by Vidhi-44** [comment]
Hey ! will you please assign me this again . I have the codebase ready.
