### ISSUE TITLE
[Enhancement]: 

### ISSUE THREAD

**Issue by samSoumyajitD** [kunjgit/GameZone#683]
### Is your enhancement request related to a problem? Please describe.➕

Game enhancement

The user interface of the Love Calculator exhibits room for improvement, presenting an opportunity to enhance its visual appeal and captivate the attention of users. By implementing refinements, such as enhancing the aesthetics and incorporating visually appealing elements, we can elevate the overall attractiveness and appeal of the user interface. This endeavor aims to create a more engaging and captivating experience for users, fostering increased interest and interaction with the Love Calculator.

### Describe the solution you'd like

Solution steps

-The fonts need to change 
-The background of the game can be made more i catchy
-It is not responsive
![01 06 2023_21 36 35_REC](https://github.com/kunjgit/GameZone/assets/92439710/c2f51cda-2b7a-4239-aa3c-d3f129edf078)
-The colors can we changed
- The result that comes after the calculation can be made more eye catchy 

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @samSoumyajitD ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hello @samSoumyajitD, Time's Uppp!⏰ 
 Sorry for closing your issue! 
 But it's more than a week since we haven't received anything from your side 😢 . 
 Come up with new ideas, create a new issue and make sure you finish it within a week! 🔥 
 All the best! 🚀 
 Happy Hacking! 💗

**Comment by kunjgit** [comment]
Hey @samSoumyajitD ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
