### ISSUE TITLE
[New game]: Snake Feeder Game [GSSoC'23]

### ISSUE THREAD

**Issue by Avdhesh-Varshney** [kunjgit/GameZone#687]
### 🎮 Game Request

Game logic and basic description

In this game, Players control a growing snake and guide it to eat food items while avoiding collisions with its own body and the game boundaries. 
The players are to accumulate points by consuming feeders, with the challenge increasing as the snake grows longer. 

### Point down the features

Game points

Points are distributed according to the below points :
1. Food items consumption
2. Length of the snake
3. Time bonus, etc.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Avdhesh-Varshney ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by Avdhesh-Varshney** [comment]
Sirs, @kunjgit @Arun9739 @raju-kumar21 please /assign this task to me to contribute under GSSoC'23.

**Comment by Avdhesh-Varshney** [comment]
Thank you so much sir @kunjgit for assigning this task to me

**Comment by kunjgit** [comment]
Hello @Avdhesh-Varshney, Time's Uppp!⏰ 
 Sorry for closing your issue! 
 But it's more than a week since we haven't received anything from your side 😢 . 
 Come up with new ideas, create a new issue and make sure you finish it within a week! 🔥 
 All the best! 🚀 
 Happy Hacking! 💗

**Comment by kunjgit** [comment]
Hey @Avdhesh-Varshney ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
