### ISSUE TITLE
[Enhancement]: Adding instruction for user guidance in the Simon game

### ISSUE THREAD

**Issue by Yashika-Agrawal** [kunjgit/GameZone#69]
### Is your enhancement request related to a problem? Please describe.➕

Game enhancement: I would like to add instructions to the game to provide clear guidance to the users on how to play and understand the game mechanics. This improvement will enhance the user experience and make the game more accessible to players of all skill levels.

### Describe the solution you'd like

Solution step: Clear and concise instructional content that outlines the game rules, objectives, and how to interact with the game. Break down the instructions into logical steps to make it easy for users to follow.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Yashika-Agrawal ! Make sure you add a short video of game if possible in Readme of the game !! 
Thank you for raising an issue !! 💗

**Comment by kunjgit** [comment]
Hello @Yashika-Agrawal, Time's Uppp!⏰ 
 Sorry for closing your issue! 
 But it's more than a week since we haven't received anything from your side 😢 . 
 Come up with new ideas, create a new issue and make sure you finish it within a week! 🔥 
 All the best! 🚀 
 Happy Hacking! 💗

**Comment by kunjgit** [comment]
Hey @Yashika-Agrawal ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
