### ISSUE TITLE
[New game]: FlipCard

### ISSUE THREAD

**Issue by MisterMickey** [kunjgit/GameZone#690]
### 🎮 Game Request

About the Game:

FlipCard-Memory Game is a modern version of the classical flip card game in which the user has to pull a card
and remember what is the symbol in that card when two cards having the same symbol are flipped then those cards vanish.

### Point down the features

The Flipcard Memory Game is a classic memory-matching game where the player's goal is to flip cards and find matching pairs within a certain time limit. Here are the detailed features of the game:

**Landing Page:** There will be 4 cards labelled as F, L, I, & P at the beginning of the game and 3 of them(F, I,&P) will be flippable and 'L' will not be. Flipping 'F' will show Figures(stats including the best score of all three modes, total flips, matched flips and wrong flips), flipping 'I' will show game instructions and flipping 'P' will let us choose between difficulty mode(casual, medium, or hard) after selecting any of the mode game will begin.

**Game Board:** The game board consists of a grid of face-down cards. The number of cards and the grid size can vary depending on the difficulty level or customization options.

**Card Flipping:** The player can select any two face-down cards to flip them face-up. This allows the player to see the images or symbols on the cards.

**Matching Pairs:** The objective is to find matching pairs of cards. When the player flips two cards and they match, both cards vanish from the game board. If the cards don't match, they are flipped back face-down, and the player will continue flipping other cards.

**Time Limit:** The game is played against the clock, meaning there is a time limit for completing the game. The player must match all the pairs before time runs out to win the game. The time limit will be set based on the game's difficulty level or adjustable by the player.

**Difficulty Levels:** The game offers multiple difficulty levels to cater to players of different skill levels. Higher difficulty levels have larger grids and more cards, making it harder to remember the card placements.

**Scoring:** The game can track the player's score based on their performance. Points will be awarded for each successful match.

**Progress Tracking:** The game will keep track of the player's progress and will be displayed to the player by flipping the 'F' card at the end or beginning of the game.

These are some of the core features of a Flipcard Memory Game.

Please mark this issue as Level-3

![Screenshot from 2023-05-29 22-34-31](https://github.com/kunjgit/GameZone/assets/93720428/ebe0abe5-bdde-4210-b23d-808c19ae606a)
![Screenshot from 2023-05-29 22-34-20](https://github.com/kunjgit/GameZone/assets/93720428/c9e2efc1-730d-43a4-8dc3-2a30806cb93d)
![Screenshot from 2023-05-29 22-34-17](https://github.com/kunjgit/GameZone/assets/93720428/39b44b16-a5d7-428c-a244-0ddec10491fb)
![Screenshot from 2023-05-29 22-34-09](https://github.com/kunjgit/GameZone/assets/93720428/27314fd2-2b90-4a31-a9c6-2c9f55ef7c23)
![Screenshot from 2023-05-29 22-33-59](https://github.com/kunjgit/GameZone/assets/93720428/a9f58ade-3fd8-4ada-b9bf-df67109a430d)

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @MisterMickey ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by SimranLahrani842** [comment]
> /assign

It's already done and merged you can check readme.md.

**Comment by kunjgit** [comment]
Hey @SimranLahrani842 ! , This issue is already assigned to @MisterMickey. 💗 
 You can work on other issues 🚀 
 If there is anything wrong you can contact us on [Discord🕹️](https://discord.gg/fgwk4XZfxG)👀

**Comment by kunjgit** [comment]
Hey @MisterMickey ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
