### ISSUE TITLE
[New game]: Rock Paper Scissor

### ISSUE THREAD

**Issue by anilkoduru** [kunjgit/GameZone#691]
### 🎮 Game Request

This game contains three buttons with Rock, Paper and scissor. User has to select any one of the button and the computer will randomly select the button amongst the three. According to the algorithm I will say whether the user has win or lose.

### Point down the features

**`Score`**: The user will get a point, if he wins the game and will lose the point if he lost the game.
**`Restart`**: User can start the game freshly by choosing this option.
**`Rules`**: This section helps the users to understand the game if he/she is new to this game``

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @anilkoduru ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @anilkoduru ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
