### ISSUE TITLE
[New game]: cast and catch

### ISSUE THREAD

**Issue by Sheetal-05** [kunjgit/GameZone#694]
### 🎮 Game Request

Game logic and basic description

The game can be created using HTML CSS and JavaScript.

Description:
The Fishing Game is a simple and addictive game where the player tries to catch fish using a fishing hook. The player's goal is to catch as many fish as possible within a given time limit or until a certain score is reached. It tests the player's timing and reflexes as they try to hook the fish swimming in the pond.

Game Logic:

1. The game starts with a pond background image and a fishing hook positioned at the bottom center of the pond.
2. Fish of different sizes and types swim randomly in the pond.
3. The player can control the fishing hook using mouse clicks.
4. If the hook overlaps with the fish, the player scores points, and the caught fish is removed from the pond.
5. If the hook misses the fish, no points are scored.
6. The game continues for a certain duration.
7. The player's score is displayed on the screen during the game.
8. After the game ends, the player can restart the game to play again.

### Point down the features

Game points
If the hook overlaps with the fish, the player scores points and the caught fish is removed from the pond.
If the hook misses the fish, no points are scored.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Sheetal-05 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)
