### ISSUE TITLE
[Enhancement]: Adding the Search Bar for Easy Search of Games

### ISSUE THREAD

**Issue by dishamodi0910** [kunjgit/GameZone#695]
### Is your enhancement request related to a problem? Please describe.➕

Game enhancement
Adding the search bar to the home page so it's easy for everyone to switch between games.

# Why this enhancement?
GameZone is having a lot many games. So if anyone wishes to go to a particular game, scrolling up and down seems frustrating, so the search bar can help there.

### Describe the solution you'd like

Solution steps
Adding the functionality by finding the particular matched game using the javascript function.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @dishamodi0910 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @dishamodi0910 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
