### ISSUE TITLE
[New game]: UNO game 

### ISSUE THREAD

**Issue by Sheetal-05** [kunjgit/GameZone#696]
### 🎮 Game Request

Game logic and basic description

Description: 
This game is a classic version of Uno that was created using HTML, CSS, and JavaScript.

Game logic:
1. Start the game by shuffling the deck of cards and dealing 7 cards to each player.
2. Place the top card of the deck face-up on the discard pile. Each player takes turns.
3. On a player's turn, they must either play a card from their hand or draw a card from the deck. To play a card, the player must choose a card from their hand that matches the color or number of the card on the discard pile.
4. Special action cards (e.g., skip, reverse, draw 2, wild, wild draw 4) have specific rules associated with them. These actions can change the gameplay and affect other players.
5. If a player cannot play a card from their hand, they must draw a card from the deck. If the drawn card can be played, the player can play it immediately.
6. The game continues until one player has no cards left in their hand. That player is declared the winner.
7. If the deck of cards runs out, reshuffle the discard pile (except for the top card) to form a new deck.

### Point down the features

Game points
The game continues until one player has no cards left in their hand. That player is declared the winner.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Sheetal-05! 
We are already having a similar game request in #660 👀 
Make sure you come up with a cool unique idea 😀 
 Waiting for your new game idea 💗.

**Comment by kunjgit** [comment]
Hey @Sheetal-05 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by kunjgit** [comment]
Hey @Sheetal-05 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by Sheetal-05** [comment]
@kunjgit 
I appreciate the opportunity, but before I jump at it, I just wanted to be sure I could actually work on this, as it is now closed. 
please confirm.

**Comment by Sheetal-05** [comment]
@kunjgit 
The game is not exactly the same, but it is a classic rendition of the popular uno game in which you draw a card and the computer plays along if the number or color matches; if not, you draw another card. Other cards include skipping, adding, and switching colors, just like in the original Uno game.
