### ISSUE TITLE
[Enhancement]: Aligning the name of the application and toggle bar in same height

### ISSUE THREAD

**Issue by anilkoduru** [kunjgit/GameZone#699]
### Is your enhancement request related to a problem? Please describe.➕

![image](https://github.com/kunjgit/GameZone/assets/88759473/e2e44796-ea8a-4efc-a361-e4282e1f093a)
The name and the toggle bar is not at the same height and that doesnot look good so I would like to do a change. 

### Describe the solution you'd like

Solution steps
Include both the name and the toggle bar in the same div and applying the flex.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @anilkoduru ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @anilkoduru ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
