### ISSUE TITLE
[New game]: Drum Kit Game

### ISSUE THREAD

**Issue by k-deepak04** [kunjgit/GameZone#70]
### 🎮 Game Request

Title: "Drum Kit Game"

Objective:
The objective of the game is to play the drum sounds accurately in response to visual cues and earn points.

Features and Gameplay:

1. Game Interface:
- The game will use the provided drum kit layout from the code.
- The title "Drum Kit Game" will be displayed at the top.
- A score counter will be shown to track the player's score.

2. Gameplay Mechanics:
- When the game starts, the player will see a visual cue indicating which drum sound to play.
- The player can play the drum sound by clicking the corresponding button or pressing the assigned key on the keyboard.
- Each time the player plays the correct drum sound, they will earn points.
- If the player plays a wrong drum sound or misses a beat, they won't earn any points.
- The game will continue with new visual cues until a certain number of rounds or a specific duration is reached.

3. Scoring System:
- Each correct drum sound played by the player will earn them a certain number of points.
- The points earned per drum sound can be a fixed amount for simplicity.
- The player's score will be displayed on the screen during the game.

4. Timing and Difficulty:
- The game can include a time limit for each round or a fixed number of rounds.
- As the game progresses, the visual cues can become faster or more challenging, increasing the difficulty.
- The player can aim to achieve the highest score possible within the given time or number of rounds.

5. Sound Effects and Visual Feedback:
- Each time the player plays a drum sound, the corresponding button will animate or change color to provide visual feedback.
- The game can include sound effects to enhance the experience when playing the drum sounds.

Points System:
- Each correct drum sound played will earn the player a fixed number of points.
- For example, the player can earn 10 points for each correct drum sound played.

The proposed game "Drum Kit Game" focuses on accuracy and timing, challenging players to match the visual cues with the correct drum sounds and earn points. It provides a simple and engaging gameplay experience using the existing code.

### Point down the features

![image](https://github.com/kunjgit/GameZone/assets/96341431/5224e7e6-60ab-43cc-a7c3-79cf6fa0918e)

there would be visuals,keys written in the image user have to use that

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @k-deepak04 !! We are already having the similar game request in #3 !!
Thank you for raising issue !! 💗
