### ISSUE TITLE
[New game]: FRANTIC RUN OF VALOROUS RABBIT

### ISSUE THREAD

**Issue by 0xabdulkhalid** [kunjgit/GameZone#700]
### 🎮 Game Request

Game logic and basic description
- This game is about a frantic run of an valorous rabbit, which may run endless. Yeah this is an endless running game
- This game's graphics is some similar like Roblox's graphics
- Quite addictive game, which may be fun for so many peoples

### Point down the features

Game points
- Pick up the carrots by jumping, those carrots you picked up will provide you points.
- Stay away from hedgehogs so that you can run faster. 

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @0xabdulkhalid ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @0xabdulkhalid ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
