### ISSUE TITLE
[New game]: Projectile game

### ISSUE THREAD

**Issue by SimranLahrani842** [kunjgit/GameZone#707]
### 🎮 Game Request

Game logic and basic description
 Use the WASD or arrow keys to navigate, and use the space bar to send your projectile. You can only send one projectile at a time. You earn around 35 points per hit. The enemy will stay on the left of the dividing line, and the player will stay on the right. Start now!

### Point down the features

Game points
45 seconds to score 750 target.

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @SimranLahrani842 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @SimranLahrani842 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
