### ISSUE TITLE
[New game]:  Stick Hero game

### ISSUE THREAD

**Issue by Yashika-Agrawal** [kunjgit/GameZone#71]
### 🎮 Game Request

Game logic and basic description:  Players will control a stick figure character who can extend and retract a stick to bridge gaps between platforms. The player's input, such as tapping or clicking, will determine the length of the stick.
The game will feature platforms of varying lengths and heights placed at different distances. The player needs to accurately gauge the length of the stick and position it to reach the next platform without falling.
 The player must adjust the stick length to match the gap width and ensure the stick lands on the next platform securely. The game will end if the stick falls short of the platform or extends beyond it, resulting in the player's character falling.
![image](https://github.com/kunjgit/GameZone/assets/97408966/106976b5-8e8e-4bd0-8d63-6f6ed0d347d1)

### Point down the features

Stick Extension: Players will have the ability to extend and retract the stick by tapping or clicking on the screen.
Platform Placement: Platforms of varying lengths will be placed at different distances, creating gaps for the player to bridge.
Gap Width Variation: The gaps between platforms will have different widths, challenging the player to adjust the stick length accordingly.
If the user makes the stick more than the gap between , the hero will fall down.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by Yashika-Agrawal** [comment]
Hey @kunjgit , I am a GSsoc'23 contributor, I would like to work on this game as I m polishing my skills in JavaScript and this game aligns with my skills.

**Comment by kunjgit** [comment]
Hey @Yashika-Agrawal  ! Thank you for raising an issue 💗 You have been assigned this issue you can start working on the issue 🎮

**Comment by kunjgit** [comment]
Hey @Yashika-Agrawal ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
