### ISSUE TITLE
[New game]: PACIFIC AIR BATTLE

### ISSUE THREAD

**Issue by 0xabdulkhalid** [kunjgit/GameZone#710]
### 🎮 Game Request

Game logic and basic description
- In this game, you will take control of a fighter jet and engage in aerial combat against enemy jets.
- You will need to use your skills and experience to dodge enemy fire and take down your targets.
- This game has good graphics 

### Point down the features

Game points
- The objective of the game is to destroy all of the enemy jets. You can do this by using your weapons to shoot them down or by ramming them.
- This game is challenging and will require you to use all of your skills and experience to succeed.
- You will get points for Attacking the enemies, you can get mediboxes to boost your health and much more!

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @0xabdulkhalid ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @0xabdulkhalid ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
