### ISSUE TITLE
[New game]: Tetris Game

### ISSUE THREAD

**Issue by utkarshjaulkar** [kunjgit/GameZone#716]
### 🎮 Game Request

Game logic and basic description:
<br>
Objective: The goal of Tetris is to score points by arranging falling tetrominoes (geometric shapes composed of four blocks) to create complete horizontal lines on the game board.
<br>
Falling Tetrominoes: Tetrominoes descend from the top of the screen one at a time. Players can move and rotate the tetrominoes to fit them into available spaces.
<br>
Line Clearing: When a horizontal line is completely filled with blocks, it clears from the board, and the player earns points. Clearing multiple lines simultaneously earns bonus points.
<br>
Increasing Difficulty: As the game progresses, the tetrominoes fall faster, making it more challenging to position them correctly. The level increases as the player clears a certain number of lines.
<br>

Addictive Gameplay: Tetris is known for its addictive nature due to its simple yet strategic gameplay. Players must think quickly and plan ahead to maximize their score and prevent the board from filling up.

### Point down the features

Game points: +1 for correct placement of the block.

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @utkarshjaulkar ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @utkarshjaulkar! 
We are already having a similar game request in #523 👀 
Make sure you come up with a cool unique idea 😀 
 Waiting for your new game idea 💗.
