### ISSUE TITLE
[New game]: Wild Card Bonanza

### ISSUE THREAD

**Issue by Sheetal-05** [kunjgit/GameZone#717]
### 🎮 Game Request

Game logic and basic description:

The game can be implemented using Html, CSS, and Javascript.

1. Player take turns. On each turn:
The player can either play a card from their hand that matches the color or number of the top card on the discard pile, or they can draw a card from the deck.
If the player plays a card, and it matches the number or color we move forward.
If the player cannot play a card, they must draw a card from the deck.
2. After the player's turn, it's the computer's turn. The computer will analyze its hand and play a card if there is a match with the top card on the discard pile. 
Continue alternating turns between the player and the computer until one of the players has no cards left in their hand.
At the end of the game, the one with no cards will be the winner.

### Point down the features

Game points
At the end of the game, the one with no cards will be the winner.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Sheetal-05 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @Sheetal-05 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
