### ISSUE TITLE
[New game]: Stack Game

### ISSUE THREAD

**Issue by utkarshjaulkar** [kunjgit/GameZone#718]
### 🎮 Game Request

Game logic and basic description:-
<br>
Objective: The goal of the Stack game is to stack blocks as high as possible by precisely placing them on top of each other.
<br>
Falling Blocks: Blocks descend from the top of the screen one at a time. Players need to time their taps or clicks to drop the blocks onto the previous block. The blocks are usually rectangular in shape.
<br>
Precise Placement: Players must aim to align each block directly on top of the previous block. If a block is not aligned correctly and overhangs the previous one, the overhanging portion is trimmed off, reducing the available surface area for the next block.
<br>
Building Height: The goal is to stack blocks as high as possible without any overhanging portions. The higher the stack, the more points the player earns.
<br>
Game Over: If a block is not placed correctly, causing the trimmed portion to fall off the stack, the game ends. The player's final score, which is based on the height of the stack, is displayed, and they can choose to play again.
<br><br>
Stack is a simple yet addictive game that challenges players to test their precision and timing skills as they aim to build the tallest tower possible.

### Point down the features

Game points:- +1 for mounting a stack on another.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @utkarshjaulkar ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @utkarshjaulkar ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
