### ISSUE TITLE
[New game]: DANTE (3D)

### ISSUE THREAD

**Issue by 0xabdulkhalid** [kunjgit/GameZone#722]
### 🎮 Game Request

Game logic and basic description
- The Game "Dante" is about a simulation orientated game
- The Dante's responsibility is to catch up all ghosts from the Hell

### Point down the features

Game points
- Catching the Ghosts & Hard level of ghost gains more points
- Catching new powers to attack ghosts

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @0xabdulkhalid ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)
