### ISSUE TITLE
Memory Game 🎮  

### ISSUE THREAD

**Issue by PriyankaTamhankar01** [kunjgit/GameZone#73]
### 🎮 Game Request

PokeMatch Game is a simple online fun game. 

Game Logic:

1. The game consists of a grid of Pokémon cards, face-down initially.
2. The player can flip two cards at a time to reveal their Pokémon.
3. If the two flipped cards have the same Pokémon, they remain face-up and are considered a match.
4. If the two flipped cards have different Pokémon, they are flipped back face-down.
5. The player's goal is to find all the matching pairs of Pokémon cards.

### Point down the features

Features of the Game:
Move Counter: The game keeps count of the number of moves made by the player. Each pair of card flips counts as one move.
Restart Button: The game provides a restart button that allows the player to reset the game and play again.
Score/Stats Display: The game may display the player's final score, including the number of moves made and the time taken to finish the game.
Theme/Design: The game may have a Pokémon-themed design, with appealing visuals and animations.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by hiteshi2803** [comment]
I would like to work on this. Please assign it to me

**Comment by kunjgit** [comment]
Hey @PriyankaTamhankar01 !! We are already having the similar game request in #34 
Make sure you come up with some new idea ! 😃 
Thank you for raising an issue  💗
