### ISSUE TITLE
[New game]: 3D dungeon game

### ISSUE THREAD

**Issue by S-ishita** [kunjgit/GameZone#730]
### 🎮 Game Request

 :package: 3D environment build on native html/css
*  :video_game: one full level with interactive items and puzzles
*  :ant: bugs and fps drops are also avalible
  

### Point down the features

Complete the given tasks to win the game

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @S-ishita ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
