### ISSUE TITLE
[New game]: Planet game

### ISSUE THREAD

**Issue by S-ishita** [kunjgit/GameZone#732]
### 🎮 Game Request

player needs to avoid junks and destroy asteroids

### Point down the features

Game points will be awarded on the basis of tokens collected and missions completed

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @S-ishita ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
