### ISSUE TITLE
Bongo Cat 

### ISSUE THREAD

**Issue by Ayush2966** [kunjgit/GameZone#733]
### 🎮 Game Request

A music instrument game application that produces different sounds on clicking keyboard keys.
for example You can play piano using  the number keys 1 to 0 
![Screenshot 2023-06-02 211515](https://github.com/kunjgit/GameZone/assets/96340111/5df5bff0-ea29-4f88-ba8b-43bf24259619)
 live demo (https://iiitian-cat.netlify.app/)

### Point down the features

One can play various instruments like bongos, piano, cymbal, cowbell and marimba using keyboard keys.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Ayush2966! 🙂 
 It seems like you are not following proper guidelines !! 👀 
 Read documentation properly !!🙏 
 If you have any queries reach out to us on [Discord🕹️](https://discord.gg/fgwk4XZfxG) .

**Comment by kunjgit** [comment]
Hey @Ayush2966 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @Ayush2966 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
