### ISSUE TITLE
[New game]: Retro Dungeon Puzzle

### ISSUE THREAD

**Issue by MisterMickey** [kunjgit/GameZone#738]
### 🎮 Game Request

The Retro Dungeon Maze Puzzle game is a thrilling and immersive experience that transports players back to the enchanting world of classic video games. With its pixelated graphics and nostalgic atmosphere, this game captures the essence of retro gaming.

The Retro Dungeon Maze Puzzle game features a set of game logic that governs the mechanics and rules of the gameplay. Here's a high-level overview of the game logic:

>Maze Generation: The game generates random mazes with walls, corridors, and various obstacles using algorithms like depth-first search or recursive backtracking.

>Player Movement: The player can move in four directions (up, down, left, and right) using touch controls. The game ensures that the player stays within the boundaries of the maze and cannot move through walls.

>Objectives: The primary objective of the game is to find the exit of each maze and progress to the next level. To achieve this, the player may need to collect keys or other items scattered throughout the maze.

>Collisions and Interactions: The game checks for collisions between the player and the obstacle.

### Point down the features

Here are the features of the Retro Dungeon Maze Puzzle game:

> Randomly generated mazes with walls, corridors, and obstacles

> Player movement in four directions (up, down, left, and right)

> Objectives to find the exit of each maze and progress to the next level

> Collection of keys and other items scattered throughout the maze

> Collisions with enemies to avoid.

>Game over conditions for losing and victory conditions for winning

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @MisterMickey ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by MisterMickey** [comment]
> @kunjgit probably this is same as #730

@S-ishita I don't think so they both are not the same, mine is different it's a Retro-styled 2-d Maze game.

**Comment by kunjgit** [comment]
Hey @MisterMickey ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
