### ISSUE TITLE
[New game]: DuckHunt

### ISSUE THREAD

**Issue by MisterMickey** [kunjgit/GameZone#741]
### 🎮 Game Request

- DuckHunt is a fast-paced shooting game where players aim to shoot down flying ducks with precise timing and accuracy. Test your reflexes and compete for the highest score in this classic hunting experience.

## Features 

> Game Setup: The game initializes the necessary components.

> Duck Generation: Duck is randomly generated and appears on the screen in different positions and flight paths. 

> Player Input: The player aims at the ducks using the mouse.

> Shooting Mechanism: When the player clicks, a shot is fired. The game calculates if the shot intersects with a duck's hitbox.

> Hit or Miss Detection: If the shot hits a duck, the game registers a successful hit.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @MisterMickey ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @MisterMickey ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
