### ISSUE TITLE
[Bug]: Lights Out Game not working

### ISSUE THREAD

**Issue by Vishalqw78** [kunjgit/GameZone#746]
### Give a brief about the bug ✍️

Description

- The game is not working due to scripting errors in both HTML and Javascript files.

 - Adding media queries for Responsive Design for a particular length in css

### What is the expected behavior? 🤔

Description

- The expected behavior is the game to start on start. 
- The Game should be responsive at medium length.

### Provide step by step information reproduce the bug 📄

Description

- I have to correct the linking error in the HTML code.
- Adding media queries in the CSS to implement responsiveness.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Vishalqw78 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @Vishalqw78 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
