### ISSUE TITLE
[New game]: PING PONG (MULTIPLAYER)

### ISSUE THREAD

**Issue by 0xabdulkhalid** [kunjgit/GameZone#747]
### 🎮 Game Request

Game logic and basic description
- Ping pong, also known as table tennis, is a sport in which two or four players hit a lightweight ball back and forth across a table using small solid rackets. 
- They must prevent the ball from touching the surface of the table on their side

### Point down the features

Game points
- Players must allow a ball played towards them to bounce once on their side of the table and must return it so that it bounces on the opposite side. 
- A point is scored when a player fails to return the ball within the rules. A player or team wins a game by scoring 11 points with a two-point margin. 
- A match is usually the best of any odd number of games (usually the best of five).

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @0xabdulkhalid ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by mubasharaKhan** [comment]
assign me this issue under GSSoC'23 label

**Comment by 0xabdulkhalid** [comment]
Salam alaykum Sister @mubasharaKhan, this issue is already assigned for me.

I've created a PR in order to be merged.

You can create your own issue, Thanks!

**Comment by kunjgit** [comment]
Hey @0xabdulkhalid ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
