### ISSUE TITLE
[New game]: SONIC THE HEDGEHOG

### ISSUE THREAD

**Issue by 0xabdulkhalid** [kunjgit/GameZone#748]
### 🎮 Game Request

Game logic and basic description
- To play, simply hit left or right key to move Sonic around the screen. You can also jump by `up` key. 
- To dash, hit down key. Sonic will dash forward and destroy any obstacles in his path.

### Point down the features

Game points

-  Use your power-ups wisely. Power-ups can help you collect more rings, run faster, and jump higher.
-  Collect coins. Coins can be used to unlock new characters and stages.
-  Challenge your friends. See who can get the farthest in the game.
- As you play, you will collect rings, which can be used to purchase power-ups. 
- Power-ups can help you collect more rings, run faster, and jump higher. 
- You can also collect coins, which can be used to unlock new characters and stages.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @0xabdulkhalid ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @0xabdulkhalid ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
