### ISSUE TITLE
Wumpus World

### ISSUE THREAD

**Issue by sanikapatil06** [kunjgit/GameZone#75]
### 🎮 Game Request

The Wumpus World game is a classic puzzle game where players navigate through a grid-based cave system to find gold while avoiding deadly traps and the menacing Wumpus creature. The game logic involves turn-based movement, where players make decisions to move in four cardinal directions or shoot an arrow to a neighboring room. The objective is to locate the gold without falling into bottomless pits or encountering the Wumpus. Players rely on perceptual clues such as a breeze indicating nearby pits or a stench revealing the Wumpus' presence. The game features include a  cave environment in the form of grids generated with random placement of hazards and objects and a scoring system to track player performance.

### Point down the features

🎯Dynamic Cave Generation: Each game session generates a unique cave layout with the randomized placement of hazards, gold, and the Wumpus, providing new challenges and experiences with every playthrough.
🎯Perceptual Clues: Players rely on perceptual cues such as breezes indicating nearby pits or stenches revealing the Wumpus' presence, helping them strategize their movements and avoid deadly encounters.
🎯Scoring System: A scoring mechanism tracks player performance, considering factors such as the number of turns taken, gold collected, and hazards encountered, adding a competitive element to the gameplay.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey  @sanikapatil06 ! Thank you for raising an issue 💗 You have been assigned this issue you can start working on the issue 🎮

**Comment by kunjgit** [comment]
Hello @sanikapatil06, Time's Uppp!⏰ 
 Sorry for closing your issue! 
 But it's more than a week since we haven't received anything from your side 😢 . 
 Come up with new ideas, create a new issue and make sure you finish it within a week! 🔥 
 All the best! 🚀 
 Happy Hacking! 💗

**Comment by kunjgit** [comment]
Hey @sanikapatil06 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
