### ISSUE TITLE
[New game]: Flappy Bird Game

### ISSUE THREAD

**Issue by varunshankar07** [kunjgit/GameZone#77]
### 🎮 Game Request

I would like to implement a Flappy Bird game using HTML, CSS, and JavaScript. The game will involve controlling a bird that navigates through gaps between pipes by tapping or clicking to keep it airborne. 

### Point down the features

**Background Themes**: Allow players to choose from different background themes or dynamically change the background based on the player's progress or game events.
**Sound Effects and Music**: Enhance the game's audio experience by adding sound effects for actions like flapping, scoring, colliding, and background music to create an immersive atmosphere.
**High Scores**: Store and display the highest scores achieved by player, creating a competitive element and encouraging replay ability.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by Saurabhrajput1234** [comment]
Hii sir I want to work on this issue please assign me this  Flappy bird game  to develop.(GSSoC23).
thanks you

**Comment by kunjgit** [comment]
Hey @varunshankar07 !! we are already having the similar game request in #22 !! 
Make sure you come up with some new idea 😃 
Looking forward to have your exciting idea in your next issue !! 
Thank you soo much for raising an issue

**Comment by varunshankar07** [comment]
@kunjgit Sure. i really didn't notice
