### ISSUE TITLE
[New game]: 

### ISSUE THREAD

**Issue by Saurabh13042004** [kunjgit/GameZone#771]
### 🎮 Game Request

Drum Kit  Game . 
Drum kit is a simple web application where you can play different sounds by pressing the keys on your keyboard. The application is built using HTML, CSS and Javascript. The application is fully responsive and works on all devices.

### Point down the features

User can play diffrent drum sounds by the keyboard keys written on the drum
Diffrent sounds like kick,tom,crash and snare has been included.
Responsive design
Code parts having comments to describe them

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Saurabh13042004 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @Saurabh13042004! 
We are already having a similar game request in #765 👀 
Make sure you come up with a cool unique idea 😀 
 Waiting for your new game idea 💗.

**Comment by kunjgit** [comment]
Hey @Saurabh13042004 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
