### ISSUE TITLE
[Enhancement]:  Drum Kit

### ISSUE THREAD

**Issue by Saurabh13042004** [kunjgit/GameZone#773]
### Is your enhancement request related to a problem? Please describe.➕

Game enhancement

Previous drum kit upload on GameZon repo was not working . I fixed some bugs and made it functional. And also edited its readme.md

### Describe the solution you'd like

Solution steps
-Change some Javascript Logic.
-Fix some small issues .
- Edit Readme.md according to CODE OF CONDUCT of GameZone

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Saurabh13042004 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @Saurabh13042004 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
