### ISSUE TITLE
[New game]: Emoji Puzzle Game [GSSoC'23]

### ISSUE THREAD

**Issue by Avdhesh-Varshney** [kunjgit/GameZone#777]
### 🎮 Game Request

Game logic and basic description

- Game is just a math riddle which creates some equations by using the emojis.
- Solve these equations and write the answer.
- This will update the score board according to the right and wrong answers.

### Point down the features

Game points

Points are given according to the wrong and right answer entered.
- (+1) for right answer
- (-1) for wrong answer

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Avdhesh-Varshney ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @Avdhesh-Varshney ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
