### ISSUE TITLE
[New game]: Bubble Blast: A Fun Bubble Shooter Game

### ISSUE THREAD

**Issue by md-rosh02** [kunjgit/GameZone#78]
### 🎮 Game Request

Bubble Blast is an exciting and addictive bubble shooter game built with JavaScript, HTML, and CSS. Shoot and match colorful bubbles to clear the board and earn points. Challenge yourself with increasingly difficult levels and strive for high scores.

### Point down the features

   - Engaging Gameplay: Enjoy hours of fun as you aim, shoot, and strategically match bubbles to create explosive combinations.
   - Power-Ups and Boosters: Utilize special power-ups and boosters to enhance your gameplay and overcome challenging situations.
   - Responsive and Intuitive Controls: Seamlessly control the shooter with easy-to-use mouse or touch inputs for precise aiming and shooting.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by Saurabhrajput1234** [comment]
Hi, sir I want to work on this game ,please assign this to me.( GSSoc23)
thank you .

**Comment by kunjgit** [comment]
Hey  @md-rosh02 ! Thank you for raising an issue 💗 You have been assigned this issue you can start working on the issue 🎮

**Comment by md-rosh02** [comment]
> Hey @md-rosh02 ! Thank you for raising an issue 💗 You have been assigned this issue you can start working on the issue 🎮

Thank You @kunjgit for assigning me this issue .........

**Comment by kunjgit** [comment]
Hey @md-rosh02 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
