### ISSUE TITLE
Add A Creative Footer Section

### ISSUE THREAD

**Issue by deepeshgupta3257** [kunjgit/GameZone#782]
### Describe your question or ask for support.❓

It's not a problem but having a good footer makes a website look cool and makes it easy for a user to get the details about the social media handles and much more important parts from the bottom also.
I have a good solution for your website to add an attractive and informative footer section that will consist of all the important information about the website and all the official social media handles.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @deepeshgupta3257 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @deepeshgupta3257! 🙂 
 It seems like you are not following proper guidelines !! 👀 
 Read documentation properly !!🙏 
 If you have any queries reach out to us on [Discord🕹️](https://discord.gg/fgwk4XZfxG) .

**Comment by kunjgit** [comment]
Hey @deepeshgupta3257 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by deepeshgupta3257** [comment]
Did I have open the issue again because this is closed

**Comment by deepeshgupta3257** [comment]
@kunjgit
