### ISSUE TITLE
[New game]: Ping Pong Game

### ISSUE THREAD

**Issue by Khaleeq01** [kunjgit/GameZone#79]
### 🎮 Game Request

I want to make smaller and easier version of this game. The main points for the game are -
1. There will be 2 rods at the top and bottom of the screen.
2. Both rods will be controlled with the same keys. In other words, they will move together.
3. When the game starts, an alert should be shown about the highest score and the player who scored it. If there is no such record, say 'this is your first time'.
4. If the score becomes highest, then store the name and max-score in local storage.
5. After every round, when one wins an alert will be displayed showing the winning player and his score

### Point down the features

1. Every round should start when the 'Enter' key is pressed. ( You can use another key as well )
2. The rods will only move horizontally using the 'a' and 'd' keys. ( You can use other keys as well )
3. The losing rod will get the ball for the next match and the rods and ball will move to center.
4. The score will be counted from the start of every match.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey  @Khaleeq01 ! Thank you for raising an issue 💗 You have been assigned this issue you can start working on the issue 🎮

**Comment by Khaleeq01** [comment]
@kunjgit I completed this project will accept my PR

**Comment by kunjgit** [comment]
Hello @Khaleeq01, Time's Uppp!⏰ 
 Sorry for closing your issue! 
 But it's more than a week since we haven't received anything from your side 😢 . 
 Come up with new ideas, create a new issue and make sure you finish it within a week! 🔥 
 All the best! 🚀 
 Happy Hacking! 💗

**Comment by kunjgit** [comment]
Hey @Khaleeq01 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
