### ISSUE TITLE
[New game]: The Pong 

### ISSUE THREAD

**Issue by Kris0011** [kunjgit/GameZone#799]
### 🎮 Game Request

Pong is a classic arcade game that tests your reflexes and hand-eye coordination. It is a single-player game where you control a paddle to compete against the computer. The objective is to prevent the ball from escaping your side of the screen while trying to make it pass the computer's paddle. The player who successfully scores the most points wins the game.

-The game starts with the ball positioned in the center of the screen and moving in a random direction.
-You control a paddle that can only move vertically along the screen's edge.
-The computer controls the opponent's paddle, which moves automatically to hit the ball.
-Your task is to hit the ball back and forth, trying to make it pass the computer's paddle.
-The ball bounces off the paddles and the top/bottom edges of the screen.
-When you fail to hit the ball with your paddle, the computer scores a point.
-When the computer fails to hit the ball, you score a point.

### Point down the features

-Difficulty levels: Implement different difficulty levels that adjust the speed and behavior of the computer opponent, allowing players of various skill levels to enjoy the game.
-Multiplayer mode: Add a two-player mode where two human players can compete against each other, each controlling a paddle on opposite sides of the screen.
-Customizable visuals: Allow players to customize the appearance of their paddles, ball, and background by selecting different colors or themes.
-High scores leaderboard: Implement a leaderboard to keep track of the highest scores achieved in the game, providing players with a competitive element and motivation to improve their performance.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Kris0011 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @Kris0011! 
We are already having a similar game request in #765 👀 
Make sure you come up with a cool unique idea 😀 
 Waiting for your new game idea 💗.

**Comment by kunjgit** [comment]
Hey @Kris0011 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
