### ISSUE TITLE
[New game]: Country Guesser

### ISSUE THREAD

**Issue by S-ishita** [kunjgit/GameZone#80]
### 🎮 Game Request

A simple web game where you can blind guess all the countries.
TECHSTACK USED:

- JavaScript
- CSS3
- HTML5

### Point down the features

Simply Type the Name of a Country in the Input field and Hit Enter. It will display the country name if it's spelled correctly or if it's not a duplicate. It will also show your progress.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @S-ishita  ! It is really interesting but we want to hear more…..
Can you elaborate the features 🤔!
We are looking forward have your valuable contribution in GameZone 🎮

**Comment by S-ishita** [comment]
This game will basically use javascript and has a database of about 200 countries .The player needs to guess country name .
THe progress will be visible to the player.

**Comment by Lavesh12** [comment]
Hello,
I hope you're doing well. I am interested in contributing to this project as part of GSSoC. It aligns with my skills and interests, and I believe I can make a meaningful contribution to the project Could you please assign this task to me? 
Looking forward to hearing from you.
Thank you,
Lavesh Vishwakarma

**Comment by kunjgit** [comment]
Hey @S-ishita ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
