### ISSUE TITLE
[New game]: PAC-MAN Doodle

### ISSUE THREAD

**Issue by Poonam-13** [kunjgit/GameZone#801]
### 🎮 Game Request

Pac-Man is a classic arcade game where players control a character named Pac-Man to navigate through a maze filled with dots and avoid ghost enemies. The objective is to eat all the dots in the maze while avoiding the ghosts. Power pellets are available to temporarily turn the tables, allowing Pac-Man to eat the ghosts. The game ends when all the dots are eaten, or when a ghost captures Pac-Man.

### Point down the features

- Classic gameplay inspired by the original Pac-Man arcade game.
- Use arrow keys or touch gestures to control Pac-Man's movement.
- Engaging maze layout with dots and power pellets.
- Colorful graphics and visually appealing game elements.
- Dynamic ghost AI that presents challenges and strategies.
- Score tracking to keep a record of the player's progress.
- Audio effects and background music for an immersive experience.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Poonam-13 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @Poonam-13 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
