### ISSUE TITLE
[New game]: Typing Game

### ISSUE THREAD

**Issue by Venkat-Vivek** [kunjgit/GameZone#814]
### 🎮 Game Request

The game tests the users typing speeds.
1.Everyone wants to learn typing but this can be enhanced through typing game.
2.A random text gets displayed over the screen and the end user needs to type the text generated over the screen as fast as possible with good accuracy.
3.A scoreboard will be displayed after completing the task according to the speed and accuracy of the user.

Tech Stacks used: HTML, CSS, JS

### Point down the features

1.A timer will be set for every new game of 60 seconds.
2.Points gets generated according to the mistakes done and time taken in completing the typing task.
3.Number typing mistakes committed will be displayed.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Venkat-Vivek ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @Venkat-Vivek! 
We are already having a similar game request in #798 👀 
Make sure you come up with a cool unique idea 😀 
 Waiting for your new game idea 💗.

**Comment by kunjgit** [comment]
Hey @Venkat-Vivek ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
