### ISSUE TITLE
[New game]: Imagetrivia Flash game

### ISSUE THREAD

**Issue by Shreya111111** [kunjgit/GameZone#815]
### 🎮 Game Request

Game logic and basic description
It is web trivia game which consists of quizzes related to computer science and other fields made using HTML,CSS and Javascript.

### Point down the features

Game points

* Question Series
*  Options
*  Timer
*  Scorelist

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Shreya111111 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by Shreya111111** [comment]
@kunjgit  plz check the game attached and review the PR

**Comment by kunjgit** [comment]
Hey @Shreya111111 👋!
 
  @kunjgit here, 
 We have this annoucement to make 📢!! 
 💥 Special Announcement: 
It's the **Call to all the designers** 🔥 🎨 
As you all know that GameZone has crossed 100 games 💗 , it's time that we all come up together and make the UI even better!!
We are redesigning the thumbnails, make sure you come up with the aesthetic and cool ideas 🚀 !
You are supposed to share the 4 different templates that can be used. Make sure that the size is: **1280 px X 720 px.** 
The frame should be such that there is only a single image of the game that's taking up the major portion of the frame. Any kind of text should not be there. 
 **The design should be catchy and aesthetic!** 🔥 

 **Note:** You are not supposed to create any issue right now for the same. 
You have to share different designs right now in ⁠[Discord](https://discord.gg/fgwk4XZfxG)  and Project Admin would be selecting one design and would be assigning the issue. After that only, you have to start working on it.

**Comment by kunjgit** [comment]
Hello @Shreya111111, Time's Uppp!⏰ 
 Sorry for closing your issue! 
 But it's more than a week since we haven't received anything from your side 😢 . 
 Come up with new ideas, create a new issue and make sure you finish it within a week! 🔥 
 All the best! 🚀 
 Happy Hacking! 💗

**Comment by kunjgit** [comment]
Hey @Shreya111111 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
