### ISSUE TITLE
[New game]: 

### ISSUE THREAD

**Issue by Durgesh4993** [kunjgit/GameZone#817]
### 🎮 Game Request

Game logic and basic description
Blanks Detective is a mystery themed, point-and-click, logic puzzle game with randomly generated puzzles! Fill in the empty spaces on the board as new clues are revealed. If you solve correctly on the first try before the 'possible thumbs up' message, you get a 'gold medal'. Watch out, your evidence may get stolen along the way.

### Point down the features

Demo Vedio:

https://github.com/kunjgit/GameZone/assets/98798977/daf1aefb-176e-4a7e-8d36-7d6e2c70e5b3

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Durgesh4993 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @Durgesh4993! 
We are already having a similar game request in #780 👀 
Make sure you come up with a cool unique idea 😀 
 Waiting for your new game idea 💗.

**Comment by kunjgit** [comment]
Hey @Durgesh4993 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
