### ISSUE TITLE
[New game]: Pig Dice Game [GSSoC'23]

### ISSUE THREAD

**Issue by Avdhesh-Varshney** [kunjgit/GameZone#823]
### 🎮 Game Request

Game logic and basic description

- This game is so easy.
- This is a multi player game.
- For the chance of that player, that player will roll the dice upto 1 will not be coming on the dice.
- If 1 comes then score, player 2 will get the chance of rolling.

### Point down the features

Game points

- The one who scores 100 first will win the match.
- Player is continuously rolling the dice and at middle if he want to hold the dice then their current score will add to the main score.
- But if it will show 1 in between then his score will become 0 (not the main score).
- In this way, second player will get the chance and same rules are also applied for that player.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Avdhesh-Varshney ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)
