### ISSUE TITLE
[New game]: Plankman

### ISSUE THREAD

**Issue by MisterMickey** [kunjgit/GameZone#828]
### 🎮 Game Request

Plankman is an engaging pirate-themed hangman game, crafted using HTML and CSS. Challenge your movie knowledge as you attempt to guess the hidden film titles before running out of guesses. Prepare to walk the plank if your movie expertise falls short in this thrilling, word-guessing adventure!

## **How to play? 🕹️**
- Open the Plankman game in your web browser.
- The game will present you with a blank space representing a movie title.
- Guess a letter from the movie title by clicking on the corresponding letter on the virtual keyboard or by typing it on your physical keyboard.
- If the letter you guessed is present in the movie title, it will be revealed in its correct position(s) in the blank space.
- If the letter you guessed is not in the movie title, a part of the hangman's plank will be added to the visual display.
- Keep guessing letters one by one, trying to fill in the blanks and complete the movie title before the hangman's plank is complete.
- Be careful! You have a limited number of incorrect guesses before the hangman's plank is fully built, leading to the end of the game.
- Guess the movie title correctly before the hangman's plank is complete to win the game.
- If you run out of guesses and the hangman's plank is fully built, the game is over, and you lose.
- Challenge yourself to improve your score by guessing more movie titles correctly and with fewer incorrect guesses.

## **Functionalities 🎮** 

- Engaging pirate theme with captivating visuals and design.
- Developed using HTML and CSS for a seamless web experience.
- Guess movie titles within a limited number of attempts.
- Test your movie knowledge and trivia skills.
- Enjoy a thrilling and immersive word-guessing adventure.
- Progressively challenging levels to keep you engaged.
- Interactive and user-friendly interface for easy gameplay.
- Track your score and attempt to beat your own records.
- Educational and entertaining, perfect for movie enthusiasts.
- Suitable for all ages, providing hours of fun and entertainment.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @MisterMickey ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @MisterMickey 👋!
 
  @kunjgit here, 
 We have this annoucement to make 📢!! 
 💥 Special Announcement: 
It's the **Call to all the designers** 🔥 🎨 
As you all know that GameZone has crossed 100 games 💗 , it's time that we all come up together and make the UI even better!!
We are redesigning the thumbnails, make sure you come up with the aesthetic and cool ideas 🚀 !
You are supposed to share the 4 different templates that can be used. Make sure that the size is: **1280 px X 720 px.** 
The frame should be such that there is only a single image of the game that's taking up the major portion of the frame. Any kind of text should not be there. 
 **The design should be catchy and aesthetic!** 🔥 

 **Note:** You are not supposed to create any issue right now for the same. 
You have to share different designs right now in ⁠[Discord](https://discord.gg/fgwk4XZfxG)  and Project Admin would be selecting one design and would be assigning the issue. After that only, you have to start working on it.

**Comment by MisterMickey** [comment]
@kunjgit Kindly review my open PR so that I make another one for this issue.

**Comment by kunjgit** [comment]
Hey @MisterMickey ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
