### ISSUE TITLE
[Enhancement]: add more feature in snake and ladder

### ISSUE THREAD

**Issue by Nishant5789** [kunjgit/GameZone#83]
### Is your enhancement request related to a problem? Please describe.➕

Game enhancement

- Play with other player over internet
- Display the minimum number of moves required to reach the destination

### Describe the solution you'd like

- But we need to change tech stake Reat JS,
- Integrate the Socket.io module into the game to enable online multiplayer functionality. This will allow users to play the game with other players over the internet.
- Display the minimum number of moves required to reach the destination for both players after complete every move using bfs algo

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by Nishant5789** [comment]
hey review my enhancement request

**Comment by kunjgit** [comment]
Hey @Nishant5789 ! 
You have to think about the live preview of game we have on our website also that how you will able to implement there !!
Also the game itself is not there for now so after the game will be there we will look into it !!!
Thank you soo much for raising issue 💗 
Reach out once game is on GameZone till then hold your breath 😃

**Comment by Lavesh12** [comment]
Hello,
I hope you're doing well. I am interested in contributing to this project as part of GSSoC. It aligns with my skills and interests, and I believe I can make a meaningful contribution to the project Could you please assign this task to me? 
Looking forward to hearing from you.
Thank you,
Lavesh Vishwakarma

**Comment by kunjgit** [comment]
Hello @Nishant5789, Time's Uppp!⏰ 
 Sorry for closing your issue! 
 But it's more than a week since we haven't received anything from your side 😢 . 
 Come up with new ideas, create a new issue and make sure you finish it within a week! 🔥 
 All the best! 🚀 
 Happy Hacking! 💗

**Comment by kunjgit** [comment]
Hey @Nishant5789 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
