### ISSUE TITLE
[New game]: Sudoku

### ISSUE THREAD

**Issue by hiteshi2803** [kunjgit/GameZone#84]
### 🎮 Game Request

Consists of a 9 × 9 grid with numbers appearing in some of the squares. The objective of the puzzle is to fill the remaining squares, using all the numbers 1–9 exactly once in each row, column, and the nine 3 × 3 sub grids. 

### Point down the features

Warning signs for incorrect number being filled
Counting number of moves 

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by Aditi323** [comment]
Please assign this to me as a GSSOC contibutor.

**Comment by kunjgit** [comment]
Hey @Aditi323 ! we are already having similar request in #10 !! 
Thank you for raising an issue 💗
