### ISSUE TITLE
[Feature]: Add "Trending Games" Section in GameZone Website

### ISSUE THREAD

**Issue by NarendraKoya999** [kunjgit/GameZone#854]
### What that Feature Can Do ??

- **This Issue is linking to Issue No:** 
- **Coming to this Feature, Create Trending Games Section in Below or Above the Search Bar.**
- **When Click on Trending Games Button, It' showing Most Liked Games by Users shown in Ascending to Descending Order(Limit is Optional).Like Top 10 or Top 5 Games.**

### Advantages:

- **Whenever New Users visit on GameZone Website, Then Particular Users Interest to see Top Trending Games on Webpage.**
- **This above cause gives More Brand Value to this Website and Possible to allow More Users entering into these Games.**

**Comment by kunjgit** [comment]
Hey @NarendraKoya999 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by NarendraKoya999** [comment]
Please Delete This Issue. I want to Create this Issue Under Our Guidelines
