### ISSUE TITLE
[New game]: Space Exploration

### ISSUE THREAD

**Issue by S-ishita** [kunjgit/GameZone#856]
### 🎮 Game Request

Explore space by flying from planet to planet. You don’t have to visit all planets, just try to go as far as possible.

To leave the orbit of a planet just click or tap the screen, or press the spacebar.

### Point down the features

The more successful you are, the more coins you get. Use these coins to unlock new spacecrafts for your next explorations.
Collect coins to unlock new spacecrafts. 

- There is nothing special about blue planets.
-  Orange planets are cloudy, which makes it hard to see where you are.
- Red planets are dangerous! Leave them as soon as possible after arrival.
- <b>Green planets</b> will brighten up when it is a good time to leave.
-  When you reach a <b>silver planet</b> you get 5 coins.
- When you reach a <b>golden planet</b> you get 10 coins.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @S-ishita ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
