### ISSUE TITLE
[New game]: Goal Rush

### ISSUE THREAD

**Issue by Sheetal-05** [kunjgit/GameZone#862]
### 🎮 Game Request

Game logic and basic description
The game is the web version of the Football Game created using Html, CSS, and javascript.

Game logic :
1. Two players control characters represented by blue squares on a soccer field.
2. Each player has a goal at one end of the field that they need to defend.
3. The ball, represented by a red circle, moves automatically and can bounce off the walls.
4. The ability to move a player's character horizontally allows them to intercept the ball and try to score goals into the opponent's goal.
5. If a player successfully made a goal, they earn a point.
6. The game continues for a predetermined duration or until a specific number of goals is reached.
7. Players can restart the game by refreshing the page.

### Point down the features

Game points
The game continues for a predetermined duration or until the specified number of goals is reached, the one with the higher goals/ points wins.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Sheetal-05 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @Sheetal-05 👋!
 
  @kunjgit here, 
 We have this annoucement to make 📢!! 
 💥 Special Announcement: 
It's the **Call to all the designers** 🔥 🎨 
As you all know that GameZone has crossed 100 games 💗 , it's time that we all come up together and make the UI even better!!
We are redesigning the thumbnails, make sure you come up with the aesthetic and cool ideas 🚀 !
You are supposed to share the 4 different templates that can be used. Make sure that the size is: **1280 px X 720 px.** 
The frame should be such that there is only a single image of the game that's taking up the major portion of the frame. Any kind of text should not be there. 
 **The design should be catchy and aesthetic!** 🔥 

 **Note:** You are not supposed to create any issue right now for the same. 
You have to share different designs right now in ⁠[Discord](https://discord.gg/fgwk4XZfxG)  and Project Admin would be selecting one design and would be assigning the issue. After that only, you have to start working on it.

**Comment by kunjgit** [comment]
Hey @Sheetal-05 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
