### ISSUE TITLE
[New game]: Falling Ball

### ISSUE THREAD

**Issue by Harshit-Chordiya** [kunjgit/GameZone#867]
### 🎮 Game Request

"Falling Ball" is a fun game that tests your reflexes and coordination. In this game, your aim is to guide a ball along an unending vertical maze studded with holes. 
This game tests your agility, timing, and decision-making abilities. It provides a thrilling and fast-paced gaming experience that will keep you engaged as you strive to beat your high score.

### Point down the features

# How to Play 

- Launch the game "Falling Ball" on your device.
- As the game starts, you will see a ball at the top-center of the screen, ready to descend.
- Your task is to control horizontal movement of ball to pass through the holes in the walls.
- Use the  left and right controls to guide the ball .Time your movements carefully to ensure that the ball aligns with the gap in each wall as it descends.
- The ball must pass through each hole to increase your score. The more holes you successfully navigate, the higher your score will be.
- .Be cautious not to let the ball touch the top of the screen, as this will instantly end the game.
- Keep your focus, maintain good hand-eye coordination, and stay alert to anticipate upcoming gaps and obstacles.
- Try to beat your own high score or challenge friends to see who can achieve the longest hole-passing streak.

Enjoy the fun and thrilling gameplay of "Falling Ball" and have fun!

Remember, practice makes perfect, so keep playing and aim for new high scores with each attempt!

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Harshit-Chordiya ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @Harshit-Chordiya 👋!
 
  @kunjgit here, 
 We have this annoucement to make 📢!! 
 💥 Special Announcement: 
It's the **Call to all the designers** 🔥 🎨 
As you all know that GameZone has crossed 100 games 💗 , it's time that we all come up together and make the UI even better!!
We are redesigning the thumbnails, make sure you come up with the aesthetic and cool ideas 🚀 !
You are supposed to share the 4 different templates that can be used. Make sure that the size is: **1280 px X 720 px.** 
The frame should be such that there is only a single image of the game that's taking up the major portion of the frame. Any kind of text should not be there. 
 **The design should be catchy and aesthetic!** 🔥 

 **Note:** You are not supposed to create any issue right now for the same. 
You have to share different designs right now in ⁠[Discord](https://discord.gg/fgwk4XZfxG)  and Project Admin would be selecting one design and would be assigning the issue. After that only, you have to start working on it.

**Comment by kunjgit** [comment]
Hello @Harshit-Chordiya, Time's Uppp!⏰ 
 Sorry for closing your issue! 
 But it's more than a week since we haven't received anything from your side 😢 . 
 Come up with new ideas, create a new issue and make sure you finish it within a week! 🔥 
 All the best! 🚀 
 Happy Hacking! 💗

**Comment by kunjgit** [comment]
Hey @Harshit-Chordiya ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
