### ISSUE TITLE
[New game]: Wordle

### ISSUE THREAD

**Issue by ritik48** [kunjgit/GameZone#87]
#### Wordle is a word game.
Here user will be displayed blank boxes, and will have to guess the word.
With each guesses the user will be given a hint like:

- if the letter in the guess exists in the original word but is at wrong position, then it's color will change to yellow.
- if the letter in the guess exists in the original word and is at a right position, then it's color will change to green.

#### Features: 
- flexibility in selecting word length
- easy, medium and tough category options
-there will be fixed number of guesses. and based on in how many guess user figured out the word, score will be given.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @ritik48  ! Thank you for raising an issue 💗 You have been assigned this issue you can start working on the issue 🎮

**Comment by kunjgit** [comment]
Hey @ritik48 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by ritik48** [comment]
@kunjgit my end sem finished two days ago, and soon after that I started creating the game and I was about to create the pr tomorrow.
