### ISSUE TITLE
[New game]: Blackjack game

### ISSUE THREAD

**Issue by sumitkr2000** [kunjgit/GameZone#88]
### 🎮 Game Request

It is a simple blackjack card game created using HTML CSS and javascript

### Point down the features

Game of cards

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by sumitkr2000** [comment]
@shishiro26 I am working on this project.

**Comment by kunjgit** [comment]
Hey @sumitkr2000  ! It is really interesting but we want to hear more…..
Can you elaborate the features 🤔!
We are looking forward have your valuable contribution in GameZone 🎮

**Comment by sumitkr2000** [comment]
Thia is a game based on cards. Its called blackjack. @kunjgit

**Comment by Lavesh12** [comment]
Hello,
I hope you're doing well. I am interested in contributing to this project as part of GSSoC. It aligns with my skills and interests, and I believe I can make a meaningful contribution to the project Could you please assign this task to me? 
Looking forward to hearing from you.
Thank you,
Lavesh Vishwakarma

**Comment by kunjgit** [comment]
Hello @sumitkr2000, Time's Uppp!⏰ 
 Sorry for closing your issue! 
 But it's more than a week since we haven't received anything from your side 😢 . 
 Come up with new ideas, create a new issue and make sure you finish it within a week! 🔥 
 All the best! 🚀 
 Happy Hacking! 💗

**Comment by kunjgit** [comment]
Hey @sumitkr2000 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
