### ISSUE TITLE
[Bug]: All the images for the games are not displayed in same size on home page

### ISSUE THREAD

**Issue by trishanu-init** [kunjgit/GameZone#881]
### Give a brief about the bug ✍️

All the images uploaded to the assets folder that are displayed on the home page of the website are sized differently  and ruins the look of the website.
<br>
![issue](https://github.com/kunjgit/GameZone/assets/85580785/ac1c4bbb-057e-40b3-b8b5-bcd634076269)

### What is the expected behavior? 🤔

All the images should be made to fit to the same dimension .
Like this👇
<br>
<img width="785" alt="issue resolved" src="https://github.com/kunjgit/GameZone/assets/85580785/90f4798c-0b5b-47e2-81ee-e48c6f3972a5">

### Provide step by step information reproduce the bug 📄

- added id="controller" for the image of game controller
`<figure class="project-img">
              <div class="project-item-icon-box">
                <img
                  src="https://raw.githubusercontent.com/Tarikul-Islam-Anik/Animated-Fluent-Emojis/master/Emojis/Activities/Video%20Game.png"
                  alt="Eye" width="3" id="controller"/>
              </div>`

- changed the css of class project-img img i.e fixed all images to be of same size and object-fit as fill
`.project-img img {
  width: 213.75px;
  height: 123.37px;
  object-fit: fill;
  transition: var(--transition-1);
}`

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @trishanu-init ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @trishanu-init ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
