### ISSUE TITLE
[New game]: Flip a Coin

### ISSUE THREAD

**Issue by VSatwika** [kunjgit/GameZone#885]
### 🎮 Game Request

 - Flip a coin is a game that will automatically flip coins for you after a little playtime.
 - A user guesses if a coin will be heads or tails
 - They can play as many times as they would like.

### Point down the features

 - There are two sides in it Head and Tail 
 - A man flips it and an another calls it.
 - If the call was correct then the person wins and if it is false he losses. 

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hello @VSatwika, Time's Uppp!⏰ 
 Sorry for closing your issue! 
 But it's more than a week since we haven't received anything from your side 😢 . 
 Come up with new ideas, create a new issue and make sure you finish it within a week! 🔥 
 All the best! 🚀 
 Happy Hacking! 💗

**Comment by kunjgit** [comment]
Hey @VSatwika ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
