### ISSUE TITLE
[New game]: Catch the Bunny!

### ISSUE THREAD

**Issue by dishamodi0910** [kunjgit/GameZone#887]
### 🎮 Game Request

Game logic and basic description
There will be various bunnies present. The user has to catch as many bunnies as possible within a given time interval.
Based on the number of bunnies caught, he/she would be given scores.

### Point down the features

Game points
1. There would be a fixed time interval within which the user has to catch the bunnies.
2. Based on the number of bunnies caught, the user will be given the scores.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @dishamodi0910 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @dishamodi0910 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
