### ISSUE TITLE
 Tic-Tac-Toe

### ISSUE THREAD

**Issue by Ash0807** [kunjgit/GameZone#888]
### 🎮 Game Request

Description 📃

X and O have to play turn by turn.
whose ever turn it is, it will be displayed on screen.

Functionalities 🎮

There is sound on each and every turn.
The screen will appear if anyone wins or draw the match.
The game can also restart in between if required. 

How to play? 🕹️

X player always plays first. He can click on any 9 of the boxes.
Next is O's turn he can click in any 9 of the boxes.
If any 3 appear the same either X or O in row, column or diagonally then he wins.

### Point down the features

This is a simple Tic-Tac-Toe game can be played within the two players. It has the best UI interface having good background animation, user feel the best experience during playing the game. 

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Ash0807 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @Ash0807 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
