### ISSUE TITLE
[New game]: Breakout Game

### ISSUE THREAD

**Issue by sumitkr2000** [kunjgit/GameZone#89]
### 🎮 Game Request

This game is based on a bouncing ball by which we have to break another ball in the opposite direction. Please assign me this issue. Thank you!

### Point down the features

One ball for the player.
Another stationary ball to break.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @sumitkr2000  ! Thank you for raising an issue 💗 You have been assigned this issue you can start working on the issue 🎮

**Comment by kunjgit** [comment]
Hey @sumitkr2000 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
