### ISSUE TITLE
[New game]: TRACK NOT FOUND 👾

### ISSUE THREAD

**Issue by 0xabdulkhalid** [kunjgit/GameZone#890]
### 🎮 Game Request

Game logic and basic description
- Hey! Where's the track?!, I'm not kidding we want to guide the train for passing through right tracks
- Play with perspective and optical illusions to help your train cross a river in 11 different levels!

### Point down the features

Game points
- Completing the levels only, there's no points allotted for our action.
- But you can try to collect these three trophies:
	- Bonk on the mountain
	- Save the bridge
	- Complete the game
 

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @0xabdulkhalid ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @0xabdulkhalid ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
