### ISSUE TITLE
[New game]: I WANT TO GOOGLE THE GAME 👾

### ISSUE THREAD

**Issue by 0xabdulkhalid** [kunjgit/GameZone#892]
### 🎮 Game Request

Game logic and basic description
- In a world where the game cannot be found, you point your browser to the venerable search engine.
- Overcome the obstacles of the uncharted Internet, such as paywalls, dark patterns, and web standards.
- You have to walk this path alone.
- You want to google the game.

### Point down the features

Game points
- Just completing the puzzles one by one, the game points are not provided in this game

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @0xabdulkhalid ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
