### ISSUE TITLE
[New game]: Pong ball

### ISSUE THREAD

**Issue by mridul588** [kunjgit/GameZone#897]
### 🎮 Game Request

Game logic and basic description
1.Ball Movement and Collision Detection:  It checks for collisions with the top and bottom edges of the game window and reverses the ball's vertical direction accordingly. When the ball collides with a paddle, its horizontal direction is reversed.
2.Scoring: The logic keeps track of the players' scores and updates them when the ball crosses the left or right edge of the game window. The score is displayed on the screen, and the ball is reset to the center after a score is registered.

![Screenshot (2)](https://github.com/kunjgit/GameZone/assets/98095736/d9b79262-e539-4f2c-8dd3-fe36cf2235c3)

### Point down the features

Game points
1.The game features two players controlling paddles with specific keys: Player 1 uses "Z" and "S," while Player 2 uses the up and down arrow keys.
2.A ball is also present and moves across the screen. It bounces off the top and bottom edges.
3.If the ball hits the left edge, Player 2's score increases, and if it hits the right edge, Player 1's score increases.
4.When the ball collides with a paddle, its horizontal direction is reversed.
5.The scores for both players are displayed on the screen.
6.The game runs in a continuous loop, updating the paddle positions and ball movement.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @mridul588 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @mridul588 👋!
 
  @kunjgit here, 
 We have this annoucement to make 📢!! 
 💥 Special Announcement: 
It's the **Call to all the designers** 🔥 🎨 
As you all know that GameZone has crossed 100 games 💗 , it's time that we all come up together and make the UI even better!!
We are redesigning the thumbnails, make sure you come up with the aesthetic and cool ideas 🚀 !
You are supposed to share the 4 different templates that can be used. Make sure that the size is: **1280 px X 720 px.** 
The frame should be such that there is only a single image of the game that's taking up the major portion of the frame. Any kind of text should not be there. 
 **The design should be catchy and aesthetic!** 🔥 

 **Note:** You are not supposed to create any issue right now for the same. 
You have to share different designs right now in ⁠[Discord](https://discord.gg/fgwk4XZfxG)  and Project Admin would be selecting one design and would be assigning the issue. After that only, you have to start working on it.

**Comment by kunjgit** [comment]
Hey @mridul588 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
