### ISSUE TITLE
DICE SHOWDOWN GAME

### ISSUE THREAD

**Issue by Himanshu07-debug** [kunjgit/GameZone#9]
### Game Description

The Dice Game is an exciting and engaging multiplayer game where two players compete to roll the highest number on their dice. It offers a thrilling experience that combines luck and strategy. The game is designed to entertain and challenge players of all ages.

### Game Logic

The game follows a simple set of rules:

1. Each player rolls a dice, which generates a random number between 1 and 6, ensuring a fair and unpredictable result.
2. The player with the higher number wins the game.
3. If both players roll the same number, the game ends in a tie.
The game provides an intuitive user interface with visually appealing dice images and a prominent heading that announces the winner or a tie. Players can easily continue playing by refreshing the page to generate new random numbers for the dice.

### Point down the features

1. **Multiplayer Gameplay**: The Dice Game allows two players to compete against each other in real-time. Players can take turns rolling the dice and experience the excitement of head-to-head gameplay.

2. **Randomized Dice Rolls:** The game utilizes a random number generator to simulate the roll of the dice. This ensures fairness and unpredictability in each round, adding an element of chance to the gameplay.

These features contribute to an engaging and interactive gaming experience

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by Chirag-04** [comment]
@Himanshu07-debug I find this project extremely fascinating and inspiring. I am genuinely excited about the opportunity to work on it and contribute my skills and expertise. I kindly request you to assign it to me

**Comment by kunjgit** [comment]
Hey  @Himanshu07-debug ! Thank you for raising an issue 💗 You have been assigned this issue you can start working on the issue 🎮

**Comment by kunjgit** [comment]
Hey @Himanshu07-debug ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
