### ISSUE TITLE
[New game]: Love calculator

### ISSUE THREAD

**Issue by sumitkr2000** [kunjgit/GameZone#91]
### 🎮 Game Request

I want to add a love calculator for the couples who want to see what the percentage of their love is. It simply requires the name of their partner and shows the love percent. Please assign me this issue. Thank you!

### Point down the features

A simple form

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by VC6378** [comment]
Please assign me this issue, I can work upon making this calculator.

**Comment by kunjgit** [comment]
Hey @sumitkr2000  ! It is really interesting but we want to hear more…..
Can you elaborate the features 🤔!
We are looking forward have your valuable contribution in GameZone 🎮

**Comment by sumitkr2000** [comment]
@kunjgit This is a simple calculator which takes the names of the lover and using random() function in the javascript we can show the percentage of love randomly.

**Comment by Lavesh12** [comment]
Hello,
I hope you're doing well. I am interested in contributing to this project as part of GSSoC. It aligns with my skills and interests, and I believe I can make a meaningful contribution to the project Could you please assign this task to me? 
Looking forward to hearing from you.
Thank you,
Lavesh Vishwakarma

**Comment by sumitkr2000** [comment]
@kunjgit This is a simple calculator which takes the names of the lover and using random() function in the javascript we can show the percentage of love randomly.

**Comment by sumitkr2000** [comment]
@kunjgit Please assign me this issue.

**Comment by soorjya** [comment]
Hello,
I hope you're doing well. I am interested in contributing to this project as part of GSSoC. It aligns with my skills and interests, and I believe I can make a meaningful contribution to the project Could you please assign this task to me?
Looking forward to hearing from you.
Thank you,

**Comment by kunjgit** [comment]
Hey @sumitkr2000 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
