### ISSUE TITLE
[New game]: Maximize Boxes!

### ISSUE THREAD

**Issue by dishamodi0910** [kunjgit/GameZone#922]
### 🎮 Game Request

Game logic and basic description
It is a multiplayer game.
Based on the lines connected, the boxes would be coloured.
The one with maximum number of boxes would be the winner.

### Point down the features

Game points
1. It is a multiplayer game.
2. The player has to select the lines. The one with the line at the last would fill the connecting boxes.
3. The player with the maximum boxes covered would be the winner.
4. The size of the board can be adjustable by user.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @dishamodi0910 👋!
 
  @kunjgit here, 
 We have this annoucement to make 📢!! 
 💥 Special Announcement: 
It's the **Call to all the designers** 🔥 🎨 
As you all know that GameZone has crossed 100 games 💗 , it's time that we all come up together and make the UI even better!!
We are redesigning the thumbnails, make sure you come up with the aesthetic and cool ideas 🚀 !
You are supposed to share the 4 different templates that can be used. Make sure that the size is: **1280 px X 720 px.** 
The frame should be such that there is only a single image of the game that's taking up the major portion of the frame. Any kind of text should not be there. 
 **The design should be catchy and aesthetic!** 🔥 

 **Note:** You are not supposed to create any issue right now for the same. 
You have to share different designs right now in ⁠[Discord](https://discord.gg/fgwk4XZfxG)  and Project Admin would be selecting one design and would be assigning the issue. After that only, you have to start working on it.

**Comment by kunjgit** [comment]
Hey @dishamodi0910 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
