### ISSUE TITLE
[New game]: IMMUNITY COLLAPSE  👾

### ISSUE THREAD

**Issue by 0xabdulkhalid** [kunjgit/GameZone#928]
### 🎮 Game Request

Game logic and basic description
- You are a virus and must eliminate all blood cells present.
- To eliminate a cell, you must absorb it. But be careful, you have to be bigger than her to absorb it.
- To move, you must give an impulse which will eject matter and cause you to lose mass, Take your time.

### Point down the features

Game points
- There's no points for our actions, but there are more levels and progress move on this game

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @0xabdulkhalid ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @0xabdulkhalid ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
