### ISSUE TITLE
[Enhancement]: Adding AI player to the game Tic Tac Toe

### ISSUE THREAD

**Issue by dhruvishavaghani** [kunjgit/GameZone#94]
### Is your enhancement request related to a problem? Please describe.➕

Game enhancement: Tic Tac Toe is a 2 player game. I can add AI player to it to make it more interesting for players and to have fun of gaming against the AI player.

### Describe the solution you'd like

Solution steps: - I will use the Min-Max algorithm to implement the AI player.
                         - It will use backtracking to see all possible winning moves.
                         - Hence it will make the game more challenging and exciting for the player. 
                  

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @dhruvishavaghani ! 
It is pretty interesting but still we are not having Tic Tac Toe on GameZone 🎮 
once the PR is accepted for that then you can reach out to us and do the enhancement 😃 
Thank you !!

**Comment by Lavesh12** [comment]
Hello,
I hope you're doing well. I am interested in contributing to this project as part of GSSoC. It aligns with my skills and interests, and I believe I can make a meaningful contribution to the project Could you please assign this task to me? 
Looking forward to hearing from you.
Thank you,
Lavesh Vishwakarma

**Comment by soorjya** [comment]
Hello,
I hope you're doing well. I am interested in contributing to this project as part of GSSoC. It aligns with my skills and interests, and I believe I can make a meaningful contribution to the project Could you please assign this task to me?
Looking forward to hearing from you.
Thank you,

**Comment by kunjgit** [comment]
Hello @dhruvishavaghani, Time's Uppp!⏰ 
 Sorry for closing your issue! 
 But it's more than a week since we haven't received anything from your side 😢 . 
 Come up with new ideas, create a new issue and make sure you finish it within a week! 🔥 
 All the best! 🚀 
 Happy Hacking! 💗

**Comment by kunjgit** [comment]
Hey @dhruvishavaghani ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
