### ISSUE TITLE
[New game]: Stone, Paper, Scissors Game

### ISSUE THREAD

**Issue by KhushiTayal** [kunjgit/GameZone#95]
### 🎮 Game Request

Game logic and basic description
The "Stone, Paper, Scissors" game can be implemented as a digital version where one player is human and the other player's response is generated randomly by the computer.
The game has three possible outcomes: a stone beats scissors, scissors beat paper, and paper beats stone. The players simultaneously make one of three hand gestures representing either a stone (a closed fist), paper (an open hand), or scissors (a fist with the index and middle fingers extended).

The rules are as follows:

Stone beats scissors (blunts or breaks scissors)
Scissors beat paper (cut paper)
Paper beats stone (wraps stone)

### Point down the features

Game points
Display the options for the human player to choose from (stone, paper, scissors).
Prompt the human player to make their selection.
Generate a random response for the computer player (stone, paper, scissors).
Compare the choices of the human player and the computer player to determine the winner based on the game rules.
Display the result of the round (e.g., "You win!", "Computer wins!", or "It's a tie!").

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

Please assign this to me

**Comment by iamsuyashpatel07** [comment]
Hey! I want to work on this issue,Can I work!

**Comment by DhairyaMajmudar** [comment]
Hey 👋 I'm Dhairya. I would be happy if you could this issue to me. I'll contribute to this issue under GSSoc'23. I can create a beautiful tic-tac-toe web app using HTML, CSS and JS

**Comment by DhairyaMajmudar** [comment]
Hey 👋 I'm Dhairya. I would be happy if you could this issue to me. I'll contribute to this issue under GSSoc'23. I can create a beautiful stone paper scissor web game using HTML, CSS and JS

**Comment by kunjgit** [comment]
Hey @KhushiTayal ! we are already having the same game request in #11 !
Thank you you may do enhancement later on !!
