### ISSUE TITLE
[New game]: Sciara of Colors 

### ISSUE THREAD

**Issue by S-ishita** [kunjgit/GameZone#956]
### 🎮 Game Request

Sciara of Colors is a frenetic mobile Puzzle Game.
Tap on the moving coloured squares of the same colour specified on the left of the screen.
Every time you destroy a correct coloured square the timer will be incremented; otherwise you loose preciuos time!
And pay attenction, because every square that go off the screen the timer will be decreased! Good luck, and be faster, before the timer is done, or you loose the game!

### Point down the features

Game points will be provided on basis of blocks destroyed

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @S-ishita ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @S-ishita ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
