### ISSUE TITLE
[Word Scramble Game]: 

### ISSUE THREAD

**Issue by sinhapalak** [kunjgit/GameZone#96]
### 🎮 Game Request

In this game, jumbled words will be given with timer and a hint. One needs to guess the correct word.

### Point down the features

It will have a timer and hint. One can also refresh for new word.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @sinhapalak ! we are already having similar game request on #29 !! 
Thank you 💗 !!
