### ISSUE TITLE
Color_guess

### ISSUE THREAD

**Issue by prachisingh1008** [kunjgit/GameZone#961]
### 🎮 Game Request

Game logic and basic description
 The game logic for "Color Guess" is as follows:

The game presents the player with a set of color options displayed as buttons.
One of the colors is randomly chosen as the target color.
The RGB values of the target color are displayed at the top.
The player needs to guess the correct color by clicking on one of the color buttons.
If the player selects the correct color, a success message is displayed.
If the player selects the wrong color, a try again message is displayed.
The player can click the "New Colors" button to reset the game and generate a new set of colors.

### Point down the features

Game points
Here are the features of the "Color Guess" game:

Random Color Generation: The game generates a random target color for the player to guess. The RGB values of the target color are displayed at the top.

Color Buttons: The game presents the player with a set of color options displayed as buttons. The number of color options can be customized.

Guessing the Correct Color: The player needs to click on one of the color buttons to guess the correct color. If the selected color matches the target color, the player wins the game.

Play Again: After the player wins or loses the game, they can click the "Play Again" button to reset the game and generate a new set of colors to guess.

Responsive Design: The game interface can be designed to be responsive, allowing more challenging as the player needs to identify the correct color among a larger range of options.

Responsive Design: The game interface can be designed to be responsive, allowing it to adapt to different screen sizes and devices for an optimal playing experience.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @prachisingh1008! 🙂 
 It seems like you are not following proper guidelines !! 👀 
 Read documentation properly !!🙏 
 If you have any queries reach out to us on [Discord🕹️](https://discord.gg/fgwk4XZfxG) .

**Comment by kunjgit** [comment]
Hey @prachisingh1008 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by prachisingh1008** [comment]
assign it to me
