### ISSUE TITLE
[Enhancement]: Website's Design Improvement

### ISSUE THREAD

**Issue by iamRabia-N** [kunjgit/GameZone#97]
### Is your enhancement request related to a problem? Please describe.➕

Game enhancement

### Describe the solution you'd like

I'll align the website's stuff, and work on typography.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by yugank01** [comment]
I would like to add a search bar for the website.

**Comment by kunjgit** [comment]
Hey @iamRabia-N ! Please elaborate more about your enhancement and also specify what are the changes you want to make ❤️

**Comment by iamRabia-N** [comment]
Hi @kunjgit! 
On Homepage, the three gaming categories will be centralized. I'll change the logo and the gaming categories typeface so that it will feel more like in gaming world. 
On Tilting Maze page, the stuff on right side will be aligned in center. 
On Simon page, the boxes will be adjusted in a way that it fits the screen so that user don't need to scroll.

You can assign me one page or whole website work. I would love to work on it.

**Comment by iamRabia-N** [comment]
> Hi @kunjgit! On Homepage, the three gaming categories will be centralized. I'll change the logo and the gaming categories typeface so that it will feel more like in gaming world. On Tilting Maze page, the stuff on right side will be aligned in center. On Simon page, the boxes will be adjusted in a way that it fits the screen so that user don't need to scroll.
> 
> You can assign me one page or whole website work. I would love to work on it.

@kunjgit

**Comment by kunjgit** [comment]
Hello @iamRabia-N, Time's Uppp!⏰ 
 Sorry for closing your issue! 
 But it's more than a week since we haven't received anything from your side 😢 . 
 Come up with new ideas, create a new issue and make sure you finish it within a week! 🔥 
 All the best! 🚀 
 Happy Hacking! 💗

**Comment by kunjgit** [comment]
Hey @iamRabia-N ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by iamRabia-N** [comment]
Hi @kunjgit 
I want to start my work on this issue. I can see design changes in overall website and I would love to make it look even better. Kindly assign it to me so that I can work on it.
