### ISSUE TITLE
[New game]: BEYONDER 👾

### ISSUE THREAD

**Issue by 0xabdulkhalid** [kunjgit/GameZone#975]
### 🎮 Game Request

Game logic and basic description
- You're dead. There is one thing left to do: go beyonder.
- Follow the flow, or be a lost soul forever.
- This game can be played on Desktop, Mobile and WebXR

### Point down the features

Game points
- You move in the direction you're looking.
- Go faster by using a mouse button, trigger or touch.
- How fast can you reach the place that lies beyonder?

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @0xabdulkhalid ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @0xabdulkhalid ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
