### ISSUE TITLE
[New game]: Whac-a-mole

### ISSUE THREAD

**Issue by Shaba1406** [kunjgit/GameZone#98]
### 🎮 Game Request

I want to add a Whac-a-mole game using html css and javascript 

### Point down the features

a user can experience this game virtually just tapping on mole they can earn the points

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by Shaba1406** [comment]
Please assign me under girlscript summer of code @kunjgit

**Comment by kunjgit** [comment]
Hey @Shaba1406  ! we are already having the same game request in #20 
Thank you for raising an issue 💗
