### ISSUE TITLE
[New game]: 3D Car Racing Game!

### ISSUE THREAD

**Issue by Parul1606** [kunjgit/GameZone#991]
### 🎮 Game Request

Get ready for a simple yet exciting car racing game developed with JavaScript! Step into the driver's seat and navigate through fun and challenging tracks. Enjoy the thrill of speeding through a vibrant environment and aim to achieve maximum points within a time limit. With its user-friendly interface and beginner-friendly design, this game is perfect for those looking to dive into the world of game development using JavaScript. Start your engines and race to victory!

### Point down the features

Features:- 
1. Press the Insert Coin (C) button and start the game.
2. Now, press the upside and downside buttons to accelerate your car.
3. And, <> to move left or right.
4. Game also features the sound/ music button which you can turn on or turn off it.
5. Now, Drive according to the situation and enjoy! Grab maximum points!!

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @Parul1606 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @Parul1606 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
