### ISSUE TITLE
[New game]:Flappy Bird 

### ISSUE THREAD

**Issue by PUJAmangale1221** [kunjgit/GameZone#994]
### 🎮 Game Request

Game logic and basic description
Flappy Bird is a side-scrolling game where the player controls a bird and tries to navigate it through obstacles. The bird moves upward when the player interacts and falls due to gravity. The game ends if the bird collides with the boundaries or obstacles. The player earns points for successfully passing through gaps between obstacles. The goal is to achieve the highest score possible by avoiding collisions and navigating through the obstacles.

### Point down the features

Game points

Simple Gameplay: Flappy Bird features straightforward gameplay where the player controls a bird by tapping the screen or pressing a key to make it flap its wings and fly.

Challenging Obstacles: The game presents a series of pipes or obstacles with small gaps in between. The player must navigate the bird through these gaps without touching the pipes.

One-Touch Controls: The game utilizes simple one-touch controls, making it easy to learn and play. Players tap or click to make the bird flap its wings, allowing it to ascend and descend in a rhythmic pattern.

Endless Scrolling: Flappy Bird is an endless scrolling game, meaning the obstacles keep coming indefinitely. The player's goal is to survive for as long as possible by avoiding collisions.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @PUJAmangale1221 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hello @PUJAmangale1221, Time's Uppp!⏰ 
 Sorry for closing your issue! 
 But it's more than a week since we haven't received anything from your side 😢 . 
 Come up with new ideas, create a new issue and make sure you finish it within a week! 🔥 
 All the best! 🚀 
 Happy Hacking! 💗

**Comment by kunjgit** [comment]
Hey @PUJAmangale1221 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
