### ISSUE TITLE
[New game]: diamond run

### ISSUE THREAD

**Issue by S-ishita** [kunjgit/GameZone#999]
### 🎮 Game Request

- "Here we are. Main security is disabled, the doors are on local. Only four stories between you and the diamond. Remember, you only have one hour."
- "The diamond is here ! But you have a feeling that something isn't right .. maybe you forgot to disable some hidden sensors and all hell will break loose once you grab it.",
- "Oops .. you half expected a wailing siren, but instead the building went dark. The elevators seem to be out as well, you will need another way down.",
- "You escape the tower empty handed, trying to recover your breath from the stress. Looking at the building again, you swear to come back better prepared. After all, there still is some time left.",
						

### Point down the features

- "You lost count of time ... the main security system reactivates, bolting all doors shut and trapping you inside. GAME OVER.",
- "You close the entrance door and prompty vanish into the darkness. Slowly, you start to realize that you made it, the diamond is 
     yours. A new life begins. YOU WIN."
 					

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @S-ishita ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Hey @S-ishita ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
